### ISSUE TITLE
Error while importing transactions

### ISSUE THREAD

**Issue by geertplaisier** [firefly-iii/firefly-iii#1312]
I am running Firefly III version 4.7.2

#### Description of my issue:

When I try to import transactions using CSV (from ING) I get the following error:

```
In ImportBill.php line 67:

  Type error: Return value of FireflyIII\Import\Object\ImportBill::getBill()
  must be an instance of FireflyIII\Models\Bill, null returned
```

#### Steps to reproduce 

Fresh install, used ING config from repository, download CSV, changed no settings, import using command-line

#### Other important details (log files, system info):

...
```
[2018-04-02 20:44:40] local.DEBUG: Find mapped budget based on field "id" with value
[2018-04-02 20:44:40] local.DEBUG: In getMappedObject() for Budget
[2018-04-02 20:44:40] local.DEBUG: Array is empty, nothing will come of this.
[2018-04-02 20:44:40] local.DEBUG: Find mapped budget based on field "name" with value
[2018-04-02 20:44:40] local.DEBUG: In getMappedObject() for Budget
[2018-04-02 20:44:40] local.DEBUG: Array is empty, nothing will come of this.
[2018-04-02 20:44:40] local.DEBUG: Found no budget on mapped data or no map present.
[2018-04-02 20:44:40] local.DEBUG: In findExistingObject() for Budget
[2018-04-02 20:44:40] local.DEBUG: Found NO existing budgets.
[2018-04-02 20:44:40] local.DEBUG: In findMappedObject() for Category
[2018-04-02 20:44:40] local.DEBUG: Find mapped category based on field "id" with value
[2018-04-02 20:44:40] local.DEBUG: In getMappedObject() for Category
[2018-04-02 20:44:40] local.DEBUG: Array is empty, nothing will come of this.
[2018-04-02 20:44:40] local.DEBUG: Find mapped category based on field "name" with value
[2018-04-02 20:44:40] local.DEBUG: In getMappedObject() for Category
[2018-04-02 20:44:40] local.DEBUG: Array is empty, nothing will come of this.
[2018-04-02 20:44:40] local.DEBUG: Found no category on mapped data or no map present.
[2018-04-02 20:44:40] local.DEBUG: In findExistingObject() for Category
[2018-04-02 20:44:40] local.DEBUG: Found NO existing categories.
[2018-04-02 20:44:40] local.DEBUG: In findMappedObject() for Bill
[2018-04-02 20:44:40] local.DEBUG: Find mapped bill based on field "id" with value
[2018-04-02 20:44:40] local.DEBUG: In getMappedObject() for Bill
[2018-04-02 20:44:40] local.DEBUG: Array is empty, nothing will come of this.
[2018-04-02 20:44:40] local.DEBUG: Find mapped bill based on field "name" with value
[2018-04-02 20:44:40] local.DEBUG: In getMappedObject() for Bill
[2018-04-02 20:44:40] local.DEBUG: Array is empty, nothing will come of this.
[2018-04-02 20:44:40] local.DEBUG: Found no bill on mapped data or no map present.
[2018-04-02 20:44:40] local.DEBUG: In findExistingObject() for Bill
[2018-04-02 20:44:40] local.DEBUG: Found NO existing bills.
[2018-04-02 20:44:40] local.ERROR: Type error: Return value of FireflyIII\Import\Object\ImportBill::getBill() must be an instance of FireflyIII\Models\Bill, null returned {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Type error: Return value of FireflyIII\\Import\\Object\\ImportBill::getBill() must be an instance of FireflyIII\\Models\\Bill, null returned at /var/www/firefly-iii/app/Import/Object/ImportBill.php:67)
[stacktrace]
#0 /var/www/firefly-iii/app/Import/Storage/ImportStorage.php(224): FireflyIII\\Import\\Object\\ImportBill->getBill()
#1 /var/www/firefly-iii/app/Import/Storage/ImportStorage.php(161): FireflyIII\\Import\\Storage\\ImportStorage->storeImportJournal(0, Object(FireflyIII\\Import\\Object\\ImportJournal))
#2 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Support/Collection.php(376): FireflyIII\\Import\\Storage\\ImportStorage->FireflyIII\\Import\\Storage\\{closure}(Object(FireflyIII\\Import\\Object\\ImportJournal), 0)
#3 /var/www/firefly-iii/app/Import/Storage/ImportStorage.php(168): Illuminate\\Support\\Collection->each(Object(Closure))
#4 /var/www/firefly-iii/app/Import/Routine/FileRoutine.php(303): FireflyIII\\Import\\Storage\\ImportStorage->store()
#5 /var/www/firefly-iii/app/Import/Routine/FileRoutine.php(112): FireflyIII\\Import\\Routine\\FileRoutine->storeObjects(Object(Illuminate\\Support\\Collection))
#6 /var/www/firefly-iii/app/Console/Commands/Import.php(93): FireflyIII\\Import\\Routine\\FileRoutine->run()
#7 [internal function]: FireflyIII\\Console\\Commands\\Import->handle()
#8 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(29): call_user_func_array(Array, Array)
#9 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(87): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#10 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(31): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#11 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Container/Container.php(564): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#12 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Console/Command.php(183): Illuminate\\Container\\Container->call(Array)
#13 /var/www/firefly-iii/vendor/symfony/console/Command/Command.php(252): Illuminate\\Console\\Command->execute(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#14 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Console/Command.php(170): Symfony\\Component\\Console\\Command\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#15 /var/www/firefly-iii/vendor/symfony/console/Application.php(865): Illuminate\\Console\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#16 /var/www/firefly-iii/vendor/symfony/console/Application.php(241): Symfony\\Component\\Console\\Application->doRunCommand(Object(FireflyIII\\Console\\Commands\\Import), Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#17 /var/www/firefly-iii/vendor/symfony/console/Application.php(143): Symfony\\Component\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#18 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Console/Application.php(88): Symfony\\Component\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#19 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(122): Illuminate\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#20 /var/www/firefly-iii/artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#21 {main}
"}
```

**Comment by JC5** [comment]
That's a sloppy one. My apologies. I will push a new release this week.

**Comment by JC5** [comment]
New release is live!
