### ISSUE TITLE
Crypt not found

### ISSUE THREAD

**Issue by gavu** [firefly-iii/firefly-iii#1317]
Hi,

I just received 2 emails from my FF3 install. Did I upgrade my install wrong/incomplete?

```
Firefly III v4.7.2 ran into an error: Class 'FireflyIII\Services\Internal\File\Crypt' not found

The error was of type "Symfony\Component\Debug\Exception\FatalThrowableError".

The error occured on/at: Wed, 04 Apr 2018 04:00:22 +0000.

This error occured in file /var/www/firefly-iii/app/Services/Internal/File/EncryptService.php on line 45 with code 0.

There was no user logged in for this error or no user was detected.
```

```
#0 /var/www/firefly-iii/app/Console/Commands/CreateImport.php(110): FireflyIII\Services\Internal\File\EncryptService->encrypt('/home/skynet/aq...', 'RxfPlWhK6lzU')
#1 [internal function]: FireflyIII\Console\Commands\CreateImport->handle()
#2 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(29): call_user_func_array(Array, Array)
#3 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(87): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#4 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(31): Illuminate\Container\BoundMethod::callBoundMethod(Object(Illuminate\Foundation\Application), Array, Object(Closure))
#5 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Container/Container.php(564): Illuminate\Container\BoundMethod::call(Object(Illuminate\Foundation\Application), Array, Array, NULL)
#6 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Console/Command.php(183): Illuminate\Container\Container->call(Array)
#7 /var/www/firefly-iii/vendor/symfony/console/Command/Command.php(252): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#8 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Console/Command.php(170): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#9 /var/www/firefly-iii/vendor/symfony/console/Application.php(865): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#10 /var/www/firefly-iii/vendor/symfony/console/Application.php(241): Symfony\Component\Console\Application->doRunCommand(Object(FireflyIII\Console\Commands\CreateImport), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#11 /var/www/firefly-iii/vendor/symfony/console/Application.php(143): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#12 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Console/Application.php(88): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#13 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(122): Illuminate\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#14 /var/www/firefly-iii/artisan(37): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#15 {main}
```

**Comment by JC5** [comment]
New release is live!
