### ISSUE TITLE
CLI import error: Call to a member function bills() on null

### ISSUE THREAD

**Issue by gavu** [firefly-iii/firefly-iii#1389]
I am running Firefly III version 4.7.3

CLI importer fails with following error

#### Description of my issue:

```
php artisan firefly:start-import bmlza05SbEBW
Going to import job with key "bmlza05SbEBW" of type "file"

In BillRepository.php line 86:
                                             
  Call to a member function bills() on null  
```

**Comment by JC5** [comment]
Could you share the stack trace from the log files? I'm trying to find where it's being called from.

**Comment by gavu** [comment]
Hi, of course, here is the email FF3 generated:

```
Firefly III v4.7.3 ran into an error: Call to a member function bills() on null

The error was of type "Symfony\Component\Debug\Exception\FatalThrowableError".

The error occured on/at: Sat, 28 Apr 2018 20:59:33 +0000.

This error occured in file /var/www/firefly-iii/app/Repositories/Bill/BillRepository.php on line 86 with code 0.

There was no user logged in for this error or no user was detected.

The IP address related to this error is: 127.0.0.1

The full stacktrace is below. If you think this is a bug in Firefly III, you can forward this message to thegrumpydictator@gmail.com. This can help fix the bug you just encountered.

If you prefer, you can also open a new issue on GitHub.

The full stacktrace is below:

#0 /var/www/firefly-iii/app/TransactionRules/Actions/LinkToBill.php(61): FireflyIII\Repositories\Bill\BillRepository->findByName('Ergo Versicheru...')
#1 /var/www/firefly-iii/app/TransactionRules/Processor.php(251): FireflyIII\TransactionRules\Actions\LinkToBill->act(Object(FireflyIII\Models\TransactionJournal))
#2 /var/www/firefly-iii/app/TransactionRules/Processor.php(226): FireflyIII\TransactionRules\Processor->actions()
#3 /var/www/firefly-iii/app/Import/Storage/ImportSupport.php(64): FireflyIII\TransactionRules\Processor->handleTransactionJournal(Object(FireflyIII\Models\TransactionJournal))
#4 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Support/Collection.php(374): FireflyIII\Import\Storage\ImportStorage->FireflyIII\Import\Storage\{closure}(Object(FireflyIII\Models\Rule), 79)
#5 /var/www/firefly-iii/app/Import/Storage/ImportSupport.php(70): Illuminate\Support\Collection->each(Object(Closure))
#6 /var/www/firefly-iii/app/Import/Storage/ImportStorage.php(287): FireflyIII\Import\Storage\ImportStorage->applyRules(Object(FireflyIII\Models\TransactionJournal))
#7 /var/www/firefly-iii/app/Import/Storage/ImportStorage.php(146): FireflyIII\Import\Storage\ImportStorage->storeImportJournal(1, Object(FireflyIII\Import\Object\ImportJournal))
#8 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Support/Collection.php(374): FireflyIII\Import\Storage\ImportStorage->FireflyIII\Import\Storage\{closure}(Object(FireflyIII\Import\Object\ImportJournal), 1)
#9 /var/www/firefly-iii/app/Import/Storage/ImportStorage.php(153): Illuminate\Support\Collection->each(Object(Closure))
#10 /var/www/firefly-iii/app/Import/Routine/FileRoutine.php(303): FireflyIII\Import\Storage\ImportStorage->store()
#11 /var/www/firefly-iii/app/Import/Routine/FileRoutine.php(112): FireflyIII\Import\Routine\FileRoutine->storeObjects(Object(Illuminate\Support\Collection))
#12 /var/www/firefly-iii/app/Console/Commands/Import.php(85): FireflyIII\Import\Routine\FileRoutine->run()
#13 [internal function]: FireflyIII\Console\Commands\Import->handle()
#14 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(29): call_user_func_array(Array, Array)
#15 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(87): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#16 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(31): Illuminate\Container\BoundMethod::callBoundMethod(Object(Illuminate\Foundation\Application), Array, Object(Closure))
#17 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Container/Container.php(564): Illuminate\Container\BoundMethod::call(Object(Illuminate\Foundation\Application), Array, Array, NULL)
#18 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Console/Command.php(183): Illuminate\Container\Container->call(Array)
#19 /var/www/firefly-iii/vendor/symfony/console/Command/Command.php(252): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#20 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Console/Command.php(170): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#21 /var/www/firefly-iii/vendor/symfony/console/Application.php(865): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#22 /var/www/firefly-iii/vendor/symfony/console/Application.php(241): Symfony\Component\Console\Application->doRunCommand(Object(FireflyIII\Console\Commands\Import), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#23 /var/www/firefly-iii/vendor/symfony/console/Application.php(143): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#24 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Console/Application.php(89): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#25 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(122): Illuminate\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#26 /var/www/firefly-iii/artisan(37): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#27 {main}
```

**Comment by JC5** [comment]
I've pushed a [very tiny fix](https://github.com/firefly-iii/firefly-iii/commit/88348f59c27ec96068acf24ce54917074377d61b). Could you apply that manually, see what happens?

**Comment by gavu** [comment]
I have 2 accounts

```
php artisan firefly:start-import 4uCG28nJwPFF
Going to import job with key "4uCG28nJwPFF" of type "file"
The import has finished. 0 transactions have been imported out of 0 records.
```

and
```php artisan firefly:start-import Mhv0OM2q92ND
Going to import job with key "Mhv0OM2q92ND" of type "file"
The import has finished. 1 transactions have been imported out of 1 records.
```

everything seems to be working again. Thanks for the quick fix!

**Comment by JC5** [comment]
You're welcome! I'll wait with an official release until more errors popup. If not, 4.7.4 will include this automatically.
