### ISSUE TITLE
Empty fields when edit multiple transactions at once

### ISSUE THREAD

**Issue by marviins87** [firefly-iii/firefly-iii#1425]
I am running Firefly III version 4.7.3

#### Description of my issue:
I'm not able to edit multiple transactions at once after the upgrade to 4.7.3.
When i select multiple rows and choose "Edit" (so not Bulk edit) then the 'Van', 'Naar' and 'Categorie' fields are not filled in. In the transactions overview those fields have a value.
[debug.txt](https://github.com/firefly-iii/firefly-iii/files/1980955/debug.txt)
![screen](https://user-images.githubusercontent.com/31892758/39717255-f4585a3a-5232-11e8-946b-a1dea27bdb1d.png)
![screen2](https://user-images.githubusercontent.com/31892758/39717256-f474d124-5232-11e8-8f05-d366119c8607.png)

**Comment by JC5** [comment]
Yep, confirmed! I'll get it fixed for the next release. Thanks for reporting!

**Comment by lexelby** [comment]
Is it possible that this could cause the following error when trying to mass-edit categories?

```
[2018-05-23 16:08:57] local.ERROR: Exception is: {"class":"Symfony\\Component\\Debug\\Exception\\FatalThrowableError","errorMessage":"Type error: Return value of FireflyIII\\Services\\Internal\\Update\\Transaction
UpdateService::findAccount() must be an instance of FireflyIII\\Models\\Account, null returned","time":"Wed, 23 May 2018 16:08:57 +0000","file":"\/home\/lex\/firefly\/app\/Services\/Internal\/Support\/TransactionS
erviceTrait.php","line":124,"code":0,"version":"4.7.3.2"}  
[2018-05-23 16:08:57] local.ERROR: Type error: Return value of FireflyIII\Services\Internal\Update\TransactionUpdateService::findAccount() must be an instance of FireflyIII\Models\Account, null returned {"userId":
1,"email":"fireflyiii@lex.gd","exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Type error: Return value of FireflyIII\\Services\\Internal\\Update\\TransactionUpdateService
::findAccount() must be an instance of FireflyIII\\Models\\Account, null returned at /home/lex/firefly/app/Services/Internal/Support/TransactionServiceTrait.php:124)
[stacktrace]
#0 /home/lex/firefly/app/Services/Internal/Update/TransactionUpdateService.php(85): FireflyIII\\Services\\Internal\\Update\\TransactionUpdateService->findAccount('Asset account', 0, '')
#1 /home/lex/firefly/app/Services/Internal/Update/JournalUpdateService.php(80): FireflyIII\\Services\\Internal\\Update\\TransactionUpdateService->update(Object(FireflyIII\\Models\\Transaction), Array)
#2 /home/lex/firefly/vendor/laravel/framework/src/Illuminate/Support/Collection.php(374): FireflyIII\\Services\\Internal\\Update\\JournalUpdateService->FireflyIII\\Services\\Internal\\Update\\{closure}(Object(FireflyIII\\Models\\Transaction), 0)
#3 /home/lex/firefly/app/Services/Internal/Update/JournalUpdateService.php(81): Illuminate\\Support\\Collection->each(Object(Closure))
#4 /home/lex/firefly/app/Repositories/Journal/JournalRepository.php(737): FireflyIII\\Services\\Internal\\Update\\JournalUpdateService->update(Object(FireflyIII\\Models\\TransactionJournal), Array)
#5 /home/lex/firefly/app/Http/Controllers/Transaction/MassController.php(236): FireflyIII\\Repositories\\Journal\\JournalRepository->update(Object(FireflyIII\\Models\\TransactionJournal), Array)
#6 [internal function]: FireflyIII\\Http\\Controllers\\Transaction\\MassController->update(Object(FireflyIII\\Http\\Requests\\MassEditJournalRequest), Object(FireflyIII\\Repositories\\Journal\\JournalRepository))
#7 /home/lex/firefly/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): call_user_func_array(Array, Array)
#8 /home/lex/firefly/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\\Routing\\Controller->callAction('update', Array)
#9 /home/lex/firefly/vendor/laravel/framework/src/Illuminate/Routing/Route.php(212): Illuminate\\Routing\\ControllerDispatcher->dispatch(Object(Illuminate\\Routing\\Route), Object(FireflyIII\\Http\\Controllers\\Transaction\\MassController), 'update')
```

If not, I could file a separate issue.
