### ISSUE TITLE
Issues with particular transaction after uprade

### ISSUE THREAD

**Issue by skibbipl** [firefly-iii/firefly-iii#1427]
I am running Firefly III version 4.7.3

#### Description of my issue:
I've upgraded my FIrefly instance to latest 4.7.3 from 4.7.1.4. During upgrade following warning was displayed:
```
Transaction #780 referred to the wrong category. Was category #49 but is fixed to be category #36.
Transaction #780 referred to the wrong category. Was category #49 but is fixed to be category #36.
```
I've checked the transaction and I found out that indeed category was changed (incorrectly BTW). Here is a screenshot of the transaction from my "production" 4.7.1.4 instance:
![obraz](https://user-images.githubusercontent.com/4746858/39758948-a2604374-52d1-11e8-8b99-07dfd5d517ef.png)

So on 4.7.3 instance I've tried to update the wrong category for this transaction and after the update I'm seeing something like this:
![obraz](https://user-images.githubusercontent.com/4746858/39759497-204002b0-52d3-11e8-9509-74fb1846add7.png)
The main problem is that I cannot remove any more splits #4-6 - after update transaction is restored to this 6 part split state. This is how firefly displays the transaction:
![obraz](https://user-images.githubusercontent.com/4746858/39759651-810120c0-52d3-11e8-84c7-2f52fb2448a0.png)
After clicking around trying to delete different splits I triggered following error:
```
Whoops! An error occurred.
Unfortunately, this error was not recoverable. Firefly III broke. The error is:
Undefined index: amount
```
And the logs:
```
[2018-05-08 13:24:39] production.ERROR: Exception is: {"class":"ErrorException","errorMessage":"Undefined index: amount","time":"Tue, 08 May 2018 13:24:39 +0000","file":"\/var\/www\/firefly-dev\/app\/Http\/Requests\/SplitJournalFormRequest.php","line":94,"code":0,"version":"4.7.3"}
[2018-05-08 13:24:39] production.ERROR: Undefined index: amount {"userId":1,"email":"xxxx@yyy.zzz","exception":"[object] (ErrorException(code: 0): Undefined index: amount at /var/www/firefly-dev/app/Http/Requests/SplitJournalFormRequest.php:94)
[stacktrace]
#0 /var/www/firefly-dev/app/Http/Requests/SplitJournalFormRequest.php(94): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError(8, 'Undefined index...', '/var/www/darksp...', 94, Array)
#1 /var/www/firefly-dev/app/Http/Requests/SplitJournalFormRequest.php(153): FireflyIII\\Http\\Requests\\SplitJournalFormRequest->getAll()
#2 /var/www/firefly-dev/app/Http/Requests/SplitJournalFormRequest.php(143): FireflyIII\\Http\\Requests\\SplitJournalFormRequest->sameAccounts(Object(FireflyIII\\Validation\\FireflyValidator))
#3 [internal function]: FireflyIII\\Http\\Requests\\SplitJournalFormRequest->FireflyIII\\Http\\Requests\\{closure}(Object(FireflyIII\\Validation\\FireflyValidator))
#4 /var/www/firefly-dev/vendor/laravel/framework/src/Illuminate/Validation/Validator.php(246): call_user_func_array(Object(Closure), Array)
#5 [internal function]: Illuminate\\Validation\\Validator->Illuminate\\Validation\\{closure}()
#6 /var/www/firefly-dev/vendor/laravel/framework/src/Illuminate/Validation/Validator.php(280): call_user_func(Object(Closure))
#7 /var/www/firefly-dev/vendor/laravel/framework/src/Illuminate/Validation/ValidatesWhenResolvedTrait.php(23): Illuminate\\Validation\\Validator->passes()
#8 /var/www/firefly-dev/vendor/laravel/framework/src/Illuminate/Foundation/Providers/FormRequestServiceProvider.php(31): Illuminate\\Foundation\\Http\\FormRequest->validateResolved()
#9 /var/www/firefly-dev/vendor/laravel/framework/src/Illuminate/Container/Container.php(1057): Illuminate\\Foundation\\Providers\\FormRequestServiceProvider->Illuminate\\Foundation\\Providers\\{closure}(Object(FireflyIII\\Http\\Requests\\SplitJournalFormRequest), Object(Illuminate\\Foundation\\Application))
#10 /var/www/firefly-dev/vendor/laravel/framework/src/Illuminate/Container/Container.php(1021): Illuminate\\Container\\Container->fireCallbackArray(Object(FireflyIII\\Http\\Requests\\SplitJournalFormRequest), Array)
#11 /var/www/firefly-dev/vendor/laravel/framework/src/Illuminate/Container/Container.php(1006): Illuminate\\Container\\Container->fireAfterResolvingCallbacks('FireflyIII\\\\Http...', Object(FireflyIII\\Http\\Requests\\SplitJournalFormRequest))
#12 /var/www/firefly-dev/vendor/laravel/framework/src/Illuminate/Container/Container.php(665): Illuminate\\Container\\Container->fireResolvingCallbacks('FireflyIII\\\\Http...', Object(FireflyIII\\Http\\Requests\\SplitJournalFormRequest))
#13 /var/www/firefly-dev/vendor/laravel/framework/src/Illuminate/Container/Container.php(601): Illuminate\\Container\\Container->resolve('FireflyIII\\\\Http...', Array)
#14 /var/www/firefly-dev/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(734): Illuminate\\Container\\Container->make('FireflyIII\\\\Http...', Array)
#15 /var/www/firefly-dev/vendor/laravel/framework/src/Illuminate/Routing/RouteDependencyResolverTrait.php(79): Illuminate\\Foundation\\Application->make('FireflyIII\\\\Http...')
#16 /var/www/firefly-dev/vendor/laravel/framework/src/Illuminate/Routing/RouteDependencyResolverTrait.php(46): Illuminate\\Routing\\ControllerDispatcher->transformDependency(Object(ReflectionParameter), Array)
#17 /var/www/firefly-dev/vendor/laravel/framework/src/Illuminate/Routing/RouteDependencyResolverTrait.php(27): Illuminate\\Routing\\ControllerDispatcher->resolveMethodDependencies(Array, Object(ReflectionMethod))
#18 /var/www/firefly-dev/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(41): Illuminate\\Routing\\ControllerDispatcher->resolveClassMethodDependencies(Array, Object(FireflyIII\\Http\\Controllers\\Transaction\\SplitController), 'update')
#19 /var/www/firefly-dev/vendor/laravel/framework/src/Illuminate/Routing/Route.php(212): Illuminate\\Routing\\ControllerDispatcher->dispatch(Object(Illuminate\\Routing\\Route), Object(FireflyIII\\Http\\Controllers\\Transaction\\SplitController), 'update')
#20 /var/www/firefly-dev/vendor/laravel/framework/src/Illuminate/Routing/Route.php(169): Illuminate\\Routing\\Route->runController()
#21 /var/www/firefly-dev/vendor/laravel/framework/src/Illuminate/Routing/Router.php(659): Illuminate\\Routing\\Route->run()
#22 /var/www/firefly-dev/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#23 /var/www/firefly-dev/app/Http/Controllers/Transaction/SplitController.php(86): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#24 /var/www/firefly-dev/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(131): FireflyIII\\Http\\Controllers\\Transaction\\SplitController->FireflyIII\\Http\\Controllers\\Transaction\\{closure}(Object(Illuminate\\Http\\Request), Object(Closure))
#25 /var/www/firefly-dev/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#26 /var/www/firefly-dev/app/Http/Controllers/Controller.php(109): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#27 /var/www/firefly-dev/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(131): FireflyIII\\Http\\Controllers\\Controller->FireflyIII\\Http\\Controllers\\{closure}(Object(Illuminate\\Http\\Request), Object(Closure))
#28 /var/www/firefly-dev/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#29 /var/www/firefly-dev/app/Http/Middleware/Binder.php(77): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#30 /var/www/firefly-dev/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): FireflyIII\\Http\\Middleware\\Binder->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#31 /var/www/firefly-dev/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#32 /var/www/firefly-dev/app/Http/Middleware/Range.php(63): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#33 /var/www/firefly-dev/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): FireflyIII\\Http\\Middleware\\Range->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#34 /var/www/firefly-dev/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#35 /var/www/firefly-dev/app/Http/Middleware/AuthenticateTwoFactor.php(78): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#36 /var/www/firefly-dev/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): FireflyIII\\Http\\Middleware\\AuthenticateTwoFactor->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#37 /var/www/firefly-dev/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#38 /var/www/firefly-dev/app/Http/Middleware/Authenticate.php(72): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#39 /var/www/firefly-dev/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): FireflyIII\\Http\\Middleware\\Authenticate->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#40 /var/www/firefly-dev/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#41 /var/www/firefly-dev/vendor/laravel/passport/src/Http/Middleware/CreateFreshApiToken.php(50): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#42 /var/www/firefly-dev/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Laravel\\Passport\\Http\\Middleware\\CreateFreshApiToken->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#43 /var/www/firefly-dev/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#44 /var/www/firefly-dev/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(67): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#45 /var/www/firefly-dev/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#46 /var/www/firefly-dev/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#47 /var/www/firefly-dev/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#48 /var/www/firefly-dev/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#49 /var/www/firefly-dev/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#50 /var/www/firefly-dev/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(63): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#51 /var/www/firefly-dev/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Session\\Middleware\\StartSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#52 /var/www/firefly-dev/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#53 /var/www/firefly-dev/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#54 /var/www/firefly-dev/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#55 /var/www/firefly-dev/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#56 /var/www/firefly-dev/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(59): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#57 /var/www/firefly-dev/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#58 /var/www/firefly-dev/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#59 /var/www/firefly-dev/app/Http/Middleware/Sandstorm.php(58): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#60 /var/www/firefly-dev/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): FireflyIII\\Http\\Middleware\\Sandstorm->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#61 /var/www/firefly-dev/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#62 /var/www/firefly-dev/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#63 /var/www/firefly-dev/vendor/laravel/framework/src/Illuminate/Routing/Router.php(661): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#64 /var/www/firefly-dev/vendor/laravel/framework/src/Illuminate/Routing/Router.php(636): Illuminate\\Routing\\Router->runRouteWithinStack(Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request))
#65 /var/www/firefly-dev/vendor/laravel/framework/src/Illuminate/Routing/Router.php(602): Illuminate\\Routing\\Router->runRoute(Object(Illuminate\\Http\\Request), Object(Illuminate\\Routing\\Route))
#66 /var/www/firefly-dev/vendor/laravel/framework/src/Illuminate/Routing/Router.php(591): Illuminate\\Routing\\Router->dispatchToRoute(Object(Illuminate\\Http\\Request))
#67 /var/www/firefly-dev/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(176): Illuminate\\Routing\\Router->dispatch(Object(Illuminate\\Http\\Request))
#68 /var/www/firefly-dev/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}(Object(Illuminate\\Http\\Request))
#69 /var/www/firefly-dev/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#70 /var/www/firefly-dev/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Fideloper\\Proxy\\TrustProxies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#71 /var/www/firefly-dev/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#72 /var/www/firefly-dev/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(30): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#73 /var/www/firefly-dev/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#74 /var/www/firefly-dev/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#75 /var/www/firefly-dev/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(30): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#76 /var/www/firefly-dev/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#77 /var/www/firefly-dev/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#78 /var/www/firefly-dev/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#79 /var/www/firefly-dev/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#80 /var/www/firefly-dev/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#81 /var/www/firefly-dev/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(46): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#82 /var/www/firefly-dev/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#83 /var/www/firefly-dev/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#84 /var/www/firefly-dev/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#85 /var/www/firefly-dev/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(151): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#86 /var/www/firefly-dev/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(116): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#87 /var/www/firefly-dev/public/index.php(75): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#88 {main}
"}
```

**Comment by JC5** [comment]
I think I know what went wrong. Not sure if I can fix it remotely.

If you open your database, try this query. Replace X with the journal ID (from the URL, `transactions/show/x`)

```
select * from transactions where transaction_journal_id = X and deleted_at is null order by id DESC
```

This should give you a list of transactions. Twice as many as the splits. You will notice that one is positive, and the other one is negative.

I expect a table like this. Pay close attention to the "identifier"-field.

Debug information generated at 2018-05-08 14:44:57 UTC for Firefly III version **4.7.3**.

| Amount | Identifier |
| --- | --- |
| 12.34 | 0 |
| -12.34 | 0 |
| 40 | 1 |
| -40 | 1 |
| 20.03 | 2 |
| -20.03 | 2 |

Is this structure recognisable in your database?

**Comment by skibbipl** [comment]
Yes, I have this:
![obraz](https://user-images.githubusercontent.com/4746858/39813347-575615d8-5390-11e8-9211-712c5841ef5d.png)
I can see that split 64 is doubled.

**Comment by JC5** [comment]
OK, you can either remove those double ones, or change the second pair of two's in three's. That should fix it for now. I'll have to add something that prevents this from happening.

**Comment by skibbipl** [comment]
Do you mean like delete the last two records from the table transactions?

**Comment by JC5** [comment]
Yes. If you want to, you can also set a date in the `deleted_at` field, which has the same effect.
