### ISSUE TITLE
Trouble after installing - Be right back message

### ISSUE THREAD

**Issue by nblracer880** [firefly-iii/firefly-iii#1472]
I am running Firefly III version 4.7.4

I installed in cpanel using softaculous.

I am getting a page which says "Be right back" when I try to browse to the installation.

I've searched all over but not having any luck. Thanks in advance to anyone who can help :)
```
`[2018-06-07 19:58:33] local.ERROR: could not find driver (SQL: select `id`, `name`, `data` from `configuration` where `name` = is_demo_site and `configuration`.`deleted_at` is null limit 1) {"exception":"[object] (Illuminate\\Database\\QueryException(code: 0): could not find driver (SQL: select `id`, `name`, `data` from `configuration` where `name` = is_demo_site and `configuration`.`deleted_at` is null limit 1) at /home/billsjnet10/public_html/vendor/laravel/framework/src/Illuminate/Database/Connection.php:664, Doctrine\\DBAL\\Driver\\PDOException(code: 0): could not find driver at /home/billsjnet10/public_html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:50, PDOException(code: 0): could not find driver at /home/billsjnet10/public_html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:46)
[stacktrace]
#0 /home/billsjnet10/public_html/vendor/laravel/framework/src/Illuminate/Database/Connection.php(624): Illuminate\\Database\\Connection->runQueryCallback('select `id`, `n...', Array, Object(Closure))
#1 /home/billsjnet10/public_html/vendor/laravel/framework/src/Illuminate/Database/Connection.php(333): Illuminate\\Database\\Connection->run('select `id`, `n...', Array, Object(Closure))
#2 /home/billsjnet10/public_html/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(1909): Illuminate\\Database\\Connection->select('select `id`, `n...', Array, true)
#3 /home/billsjnet10/public_html/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(1894): Illuminate\\Database\\Query\\Builder->runSelect()
#4 /home/billsjnet10/public_html/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(481): Illuminate\\Database\\Query\\Builder->get(Array)
#5 /home/billsjnet10/public_html/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(465): Illuminate\\Database\\Eloquent\\Builder->getModels(Array)
#6 /home/billsjnet10/public_html/vendor/laravel/framework/src/Illuminate/Database/Concerns/BuildsQueries.php(77): Illuminate\\Database\\Eloquent\\Builder->get(Array)
#7 /home/billsjnet10/public_html/app/Support/FireflyConfig.php(65): Illuminate\\Database\\Eloquent\\Builder->first(Array)
#8 /home/billsjnet10/public_html/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(221): FireflyIII\\Support\\FireflyConfig->get('is_demo_site', false)
#9 /home/billsjnet10/public_html/app/Http/Controllers/Controller.php(68): Illuminate\\Support\\Facades\\Facade::__callStatic('get', Array)
#10 /home/billsjnet10/public_html/app/Http/Controllers/HomeController.php(55): FireflyIII\\Http\\Controllers\\Controller->__construct()
#11 [internal function]: FireflyIII\\Http\\Controllers\\HomeController->__construct()
#12 /home/billsjnet10/public_html/vendor/laravel/framework/src/Illuminate/Container/Container.php(800): ReflectionClass->newInstanceArgs(Array)
#13 /home/billsjnet10/public_html/vendor/laravel/framework/src/Illuminate/Container/Container.php(646): Illuminate\\Container\\Container->build('FireflyIII\\\\Http...')
#14 /home/billsjnet10/public_html/vendor/laravel/framework/src/Illuminate/Container/Container.php(601): Illuminate\\Container\\Container->resolve('FireflyIII\\\\Http...', Array)
#15 /home/billsjnet10/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(734): Illuminate\\Container\\Container->make('FireflyIII\\\\Http...', Array)
#16 /home/billsjnet10/public_html/vendor/laravel/framework/src/Illuminate/Routing/Route.php(226): Illuminate\\Foundation\\Application->make('FireflyIII\\\\Http...')
#17 /home/billsjnet10/public_html/vendor/laravel/framework/src/Illuminate/Routing/Route.php(796): Illuminate\\Routing\\Route->getController()
#18 /home/billsjnet10/public_html/vendor/laravel/framework/src/Illuminate/Routing/Route.php(757): Illuminate\\Routing\\Route->controllerMiddleware()
#19 /home/billsjnet10/public_html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(672): Illuminate\\Routing\\Route->gatherMiddleware()
#20 /home/billsjnet10/public_html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(652): Illuminate\\Routing\\Router->gatherRouteMiddleware(Object(Illuminate\\Routing\\Route))
#21 /home/billsjnet10/public_html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(636): Illuminate\\Routing\\Router->runRouteWithinStack(Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request))
#22 /home/billsjnet10/public_html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(602): Illuminate\\Routing\\Router->runRoute(Object(Illuminate\\Http\\Request), Object(Illuminate\\Routing\\Route))
#23 /home/billsjnet10/public_html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(591): Illuminate\\Routing\\Router->dispatchToRoute(Object(Illuminate\\Http\\Request))
#24 /home/billsjnet10/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(176): Illuminate\\Routing\\Router->dispatch(Object(Illuminate\\Http\\Request))
#25 /home/billsjnet10/public_html/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}(Object(Illuminate\\Http\\Request))
#26 /home/billsjnet10/public_html/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#27 /home/billsjnet10/public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Fideloper\\Proxy\\TrustProxies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#28 /home/billsjnet10/public_html/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#29 /home/billsjnet10/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(31): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#30 /home/billsjnet10/public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#31 /home/billsjnet10/public_html/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#32 /home/billsjnet10/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(31): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#33 /home/billsjnet10/public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#34 /home/billsjnet10/public_html/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#35 /home/billsjnet10/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#36 /home/billsjnet10/public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#37 /home/billsjnet10/public_html/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#38 /home/billsjnet10/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(51): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#39 /home/billsjnet10/public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#40 /home/billsjnet10/public_html/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#41 /home/billsjnet10/public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(104): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#42 /home/billsjnet10/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(151): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#43 /home/billsjnet10/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(116): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#44 /home/billsjnet10/public_html/public/index.php(76): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#45 {main}
"} `
```

**Comment by JC5** [comment]
It seems that your PHP installation is not equipped to handle MySQL. I believe your hosting provider must solve this for you.

**Comment by nblracer880** [comment]
Thanks for the tip. I host my cpanel server at home. I enabled php 7.1 for the account I dedicated to host my installation of Firefly III. I installed the required PHP extensions that the installer said I needed. Do you know what the extension I need is called?

Thank you :)

**Comment by nblracer880** [comment]
Got it. Had to install php71-php-mysqlnd

Thanks for pointing me in the right direction!
