### ISSUE TITLE
Problem after direct import

### ISSUE THREAD

**Issue by colomarco** [firefly-iii/firefly-iii#1529]
I am running Firefly III version 4.7.4

I'm importing directly on database tables because I created a function that read from another external db and manage some data. After that, if I try open the transaction page, I obtain the following error.

I see that after import, if I update an account (just clicking on button update, without doing anything else) all starts to work again without any trouble. 
Have I to clean variables or something after importing in this way? 

Thank you so much.

| Variable | Content |
| --- | --- |
| FF version | 4.7.4 |
| FF API version | 0.3 |
| App environment | local |
| App debug mode | true |
| App cache driver | file |
| App logging | notice, daily |
| PHP version | 7.1.18 |
| Display errors | Off |
| Session start | 2018-07-01 00:00:00 |
| Session end | 2018-07-31 23:59:59 |
| Session first | 2018-01-01 00:00:00 |
| Error reporting | ALL errors |
| Host | Linux |
| Interface | apache2handler |
| UserID | 1 |
| Attempt at "en" | false |
| Attempt at "English" | false |
| Attempt at "en_US" | 'en_US' |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| DB drivers | mysql, pgsql, sqlite, sqlsrv |
| Current driver | mysql |
| Using Sandstorm? | no |
| Is Sandstorm (.env) | false |
| Is Docker (.env) | false |
| bunq uses sandbox | false |
| Trusted proxies (.env) |  |
| User agent | Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/11.1.1 Safari/605.1.15 |
| Loaded extensions | Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, session, standard, apache2handler, sqlsrv, libsodium, apcu, bcmath, bz2, calendar, ctype, curl, dba, dom, enchant, mbstring, fileinfo, ftp, gd, geoip, gettext, gmp, iconv, igbinary, imagick, imap, interbase, intl, json, ldap, exif, mcrypt, mongodb, mysqlnd, mysqli, odbc, PDO, pdo_dblib, PDO_Firebird, pdo_mysql, PDO_ODBC, pdo_pgsql, pdo_sqlite, pdo_sqlsrv, pgsql, Phar, posix, pspell, recode, redis, shmop, SimpleXML, snmp, soap, sockets, sqlite3, sysvmsg, sysvsem, sysvshm, tidy, tokenizer, xml, wddx, xmlreader, xmlrpc, xmlwriter, xsl, memcached, zip, Zend OPcache, xdebug |
| Installed packages | bacon/bacon-qr-code@1.0.3, bunq/sdk_php@dev-master, davejamesmiller/laravel-breadcrumbs@5.1.0, defuse/php-encryption@v2.2.0, doctrine/annotations@v1.6.0, doctrine/cache@v1.7.1, doctrine/collections@v1.5.0, doctrine/common@v2.8.1, doctrine/dbal@v2.7.1, doctrine/inflector@v1.3.0, doctrine/lexer@v1.0.1, dragonmantank/cron-expression@v2.1.0, egulias/email-validator@2.1.4, erusev/parsedown@1.7.1, fideloper/proxy@4.0.0, firebase/php-jwt@v5.0.0, guzzlehttp/guzzle@6.3.3, guzzlehttp/promises@v1.3.1, guzzlehttp/psr7@1.4.2, laravel/framework@v5.6.23, laravel/passport@v5.0.3, laravelcollective/html@v5.6.9, lcobucci/jwt@3.2.2, league/commonmark@0.17.5, league/csv@9.1.4, league/event@2.1.2, league/flysystem@1.0.45, league/fractal@0.17.0, league/oauth2-server@6.1.1, monolog/monolog@1.23.0, nesbot/carbon@1.25.0, paragonie/constant_time_encoding@v2.2.2, paragonie/random_compat@v2.0.12, phpseclib/phpseclib@2.0.11, pragmarx/google2fa@v3.0.1, pragmarx/google2fa-laravel@v0.2.0, psr/container@1.0.0, psr/http-message@1.0.1, psr/log@1.0.2, psr/simple-cache@1.0.1, ramsey/uuid@3.7.3, rcrowe/twigbridge@v0.9.6, rmccue/requests@v1.7.0, swiftmailer/swiftmailer@v6.0.2, symfony/console@v4.1.0, symfony/css-selector@v4.1.0, symfony/debug@v4.1.0, symfony/event-dispatcher@v4.1.0, symfony/finder@v4.1.0, symfony/http-foundation@v4.1.0, symfony/http-kernel@v4.1.0, symfony/polyfill-ctype@v1.8.0, symfony/polyfill-mbstring@v1.8.0, symfony/polyfill-php56@v1.8.0, symfony/polyfill-php72@v1.8.0, symfony/polyfill-util@v1.8.0, symfony/process@v4.1.0, symfony/psr-http-message-bridge@v1.0.2, symfony/routing@v4.1.0, symfony/translation@v4.1.0, symfony/var-dumper@v4.1.0, tijsverkoyen/css-to-inline-styles@2.2.1, twig/twig@v1.35.3, vlucas/phpdotenv@v2.4.0, zendframework/zend-diactoros@1.7.2,  |

Stack trace
```
#0 /var/www/html/firefly/storage/framework/views/twig/7f/7f83678d99af3d6dbf073a14bc33140f46a96e2d4444d7a51f3c0f176e20a8a2.php(133): FireflyIII\Support\Twig\Extension\Transaction->budgets(Object(FireflyIII\Models\Transaction))
#1 /var/www/html/firefly/vendor/twig/twig/lib/Twig/Template.php(432): __TwigTemplate_11277ac6d9f1cca4f3fcbc31f09bde23b349a273185e9b1c519258eff1e95948->doDisplay(Array, Array)
#2 /var/www/html/firefly/vendor/twig/twig/lib/Twig/Template.php(403): Twig_Template->displayWithErrorHandling(Array, Array)
#3 /var/www/html/firefly/vendor/rcrowe/twigbridge/src/Twig/Template.php(41): Twig_Template->display(Array, Array)
#4 /var/www/html/firefly/storage/framework/views/twig/d8/d84b70002d7065956e8aeff3084f5fba0690ac4046d849537f08076ffbd91c10.php(110): TwigBridge\Twig\Template->display(Array)
#5 /var/www/html/firefly/vendor/twig/twig/lib/Twig/Template.php(432): __TwigTemplate_7d8a2f38e01e8d124edb902dfc373a0e27e1881def788447af9870d4970c0066->doDisplay(Array, Array)
#6 /var/www/html/firefly/vendor/twig/twig/lib/Twig/Template.php(403): Twig_Template->displayWithErrorHandling(Array, Array)
#7 /var/www/html/firefly/vendor/rcrowe/twigbridge/src/Twig/Template.php(41): Twig_Template->display(Array, Array)
#8 /var/www/html/firefly/storage/framework/views/twig/f3/f324c188325d67857da875b6a9e4c0e4db05d3a53db10e26c77272cd84e5a8b5.php(107): TwigBridge\Twig\Template->display(Array)
#9 /var/www/html/firefly/vendor/twig/twig/lib/Twig/Template.php(215): __TwigTemplate_2e62dbe27a420c12a2a7c2117f197484a989a4b5a8d36c3824567f536a00dbe9->block_content(Array, Array)
#10 /var/www/html/firefly/storage/framework/views/twig/29/298043aaf74254cfdcb4376d4f3c6e6ff66e79f440b1aef705141b1891b50788.php(256): Twig_Template->displayBlock('content', Array, Array)
#11 /var/www/html/firefly/vendor/twig/twig/lib/Twig/Template.php(432): __TwigTemplate_deebe9bd16b936454ddd7dfbd39dfabf94b9f2401ce88abc1280ac2dd30b0050->doDisplay(Array, Array)
#12 /var/www/html/firefly/vendor/twig/twig/lib/Twig/Template.php(403): Twig_Template->displayWithErrorHandling(Array, Array)
#13 /var/www/html/firefly/vendor/rcrowe/twigbridge/src/Twig/Template.php(41): Twig_Template->display(Array, Array)
#14 /var/www/html/firefly/storage/framework/views/twig/f3/f324c188325d67857da875b6a9e4c0e4db05d3a53db10e26c77272cd84e5a8b5.php(26): TwigBridge\Twig\Template->display(Array, Array)
#15 /var/www/html/firefly/vendor/twig/twig/lib/Twig/Template.php(432): __TwigTemplate_2e62dbe27a420c12a2a7c2117f197484a989a4b5a8d36c3824567f536a00dbe9->doDisplay(Array, Array)
#16 /var/www/html/firefly/vendor/twig/twig/lib/Twig/Template.php(403): Twig_Template->displayWithErrorHandling(Array, Array)
#17 /var/www/html/firefly/vendor/rcrowe/twigbridge/src/Twig/Template.php(41): Twig_Template->display(Array, Array)
#18 /var/www/html/firefly/vendor/twig/twig/lib/Twig/Template.php(411): TwigBridge\Twig\Template->display(Array)
#19 /var/www/html/firefly/vendor/rcrowe/twigbridge/src/Engine/Twig.php(91): Twig_Template->render(Array)
#20 /var/www/html/firefly/vendor/laravel/framework/src/Illuminate/View/View.php(142): TwigBridge\Engine\Twig->get('/var/www/html/f...', Array)
#21 /var/www/html/firefly/vendor/laravel/framework/src/Illuminate/View/View.php(125): Illuminate\View\View->getContents()
#22 /var/www/html/firefly/vendor/laravel/framework/src/Illuminate/View/View.php(90): Illuminate\View\View->renderContents()
#23 /var/www/html/firefly/vendor/laravel/framework/src/Illuminate/Http/Response.php(42): Illuminate\View\View->render()
#24 /var/www/html/firefly/vendor/symfony/http-foundation/Response.php(197): Illuminate\Http\Response->setContent(Object(Illuminate\View\View))
#25 /var/www/html/firefly/vendor/laravel/framework/src/Illuminate/Routing/Router.php(727): Symfony\Component\HttpFoundation\Response->__construct(Object(Illuminate\View\View))
#26 /var/www/html/firefly/vendor/laravel/framework/src/Illuminate/Routing/Router.php(699): Illuminate\Routing\Router::toResponse(Object(Illuminate\Http\Request), Object(Illuminate\View\View))
#27 /var/www/html/firefly/vendor/laravel/framework/src/Illuminate/Routing/Router.php(659): Illuminate\Routing\Router->prepareResponse(Object(Illuminate\Http\Request), Object(Illuminate\View\View))
#28 /var/www/html/firefly/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#29 /var/www/html/firefly/app/Http/Controllers/TransactionController.php(65): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#30 /var/www/html/firefly/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(133): FireflyIII\Http\Controllers\TransactionController->FireflyIII\Http\Controllers\{closure}(Object(Illuminate\Http\Request), Object(Closure))
#31 /var/www/html/firefly/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#32 /var/www/html/firefly/app/Http/Controllers/Controller.php(109): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#33 /var/www/html/firefly/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(133): FireflyIII\Http\Controllers\Controller->FireflyIII\Http\Controllers\{closure}(Object(Illuminate\Http\Request), Object(Closure))
#34 /var/www/html/firefly/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#35 /var/www/html/firefly/app/Http/Middleware/Binder.php(77): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#36 /var/www/html/firefly/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): FireflyIII\Http\Middleware\Binder->handle(Object(Illuminate\Http\Request), Object(Closure))
#37 /var/www/html/firefly/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#38 /var/www/html/firefly/app/Http/Middleware/Range.php(63): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#39 /var/www/html/firefly/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): FireflyIII\Http\Middleware\Range->handle(Object(Illuminate\Http\Request), Object(Closure))
#40 /var/www/html/firefly/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#41 /var/www/html/firefly/app/Http/Middleware/AuthenticateTwoFactor.php(78): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#42 /var/www/html/firefly/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): FireflyIII\Http\Middleware\AuthenticateTwoFactor->handle(Object(Illuminate\Http\Request), Object(Closure))
#43 /var/www/html/firefly/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#44 /var/www/html/firefly/app/Http/Middleware/Authenticate.php(73): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#45 /var/www/html/firefly/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): FireflyIII\Http\Middleware\Authenticate->handle(Object(Illuminate\Http\Request), Object(Closure))
#46 /var/www/html/firefly/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#47 /var/www/html/firefly/vendor/laravel/passport/src/Http/Middleware/CreateFreshApiToken.php(50): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#48 /var/www/html/firefly/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Laravel\Passport\Http\Middleware\CreateFreshApiToken->handle(Object(Illuminate\Http\Request), Object(Closure))
#49 /var/www/html/firefly/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#50 /var/www/html/firefly/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(67): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#51 /var/www/html/firefly/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\Foundation\Http\Middleware\VerifyCsrfToken->handle(Object(Illuminate\Http\Request), Object(Closure))
#52 /var/www/html/firefly/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#53 /var/www/html/firefly/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#54 /var/www/html/firefly/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#55 /var/www/html/firefly/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#56 /var/www/html/firefly/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(63): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#57 /var/www/html/firefly/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#58 /var/www/html/firefly/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#59 /var/www/html/firefly/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#60 /var/www/html/firefly/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure))
#61 /var/www/html/firefly/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#62 /var/www/html/firefly/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(59): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#63 /var/www/html/firefly/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
#64 /var/www/html/firefly/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#65 /var/www/html/firefly/app/Http/Middleware/Sandstorm.php(58): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#66 /var/www/html/firefly/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): FireflyIII\Http\Middleware\Sandstorm->handle(Object(Illuminate\Http\Request), Object(Closure))
#67 /var/www/html/firefly/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#68 /var/www/html/firefly/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(104): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#69 /var/www/html/firefly/vendor/laravel/framework/src/Illuminate/Routing/Router.php(661): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#70 /var/www/html/firefly/vendor/laravel/framework/src/Illuminate/Routing/Router.php(636): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#71 /var/www/html/firefly/vendor/laravel/framework/src/Illuminate/Routing/Router.php(602): Illuminate\Routing\Router->runRoute(Object(Illuminate\Http\Request), Object(Illuminate\Routing\Route))
#72 /var/www/html/firefly/vendor/laravel/framework/src/Illuminate/Routing/Router.php(591): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#73 /var/www/html/firefly/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(176): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#74 /var/www/html/firefly/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#75 /var/www/html/firefly/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#76 /var/www/html/firefly/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Fideloper\Proxy\TrustProxies->handle(Object(Illuminate\Http\Request), Object(Closure))
#77 /var/www/html/firefly/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#78 /var/www/html/firefly/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(31): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#79 /var/www/html/firefly/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle(Object(Illuminate\Http\Request), Object(Closure))
#80 /var/www/html/firefly/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#81 /var/www/html/firefly/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(31): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#82 /var/www/html/firefly/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle(Object(Illuminate\Http\Request), Object(Closure))
#83 /var/www/html/firefly/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#84 /var/www/html/firefly/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#85 /var/www/html/firefly/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\Foundation\Http\Middleware\ValidatePostSize->handle(Object(Illuminate\Http\Request), Object(Closure))
#86 /var/www/html/firefly/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#87 /var/www/html/firefly/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(51): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#88 /var/www/html/firefly/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#89 /var/www/html/firefly/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#90 /var/www/html/firefly/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(104): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#91 /var/www/html/firefly/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(151): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#92 /var/www/html/firefly/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(116): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#93 /var/www/html/firefly/public/index.php(76): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#94 {main}
```

**Comment by JC5** [comment]
- I see you stack trace, but no actual error.
- Do you edit the transaction itself, or one of the related accounts?

**Comment by colomarco** [comment]
I do an insert on the transaction_journals table, then for each insert get the ID and create the 2 transactions (- and +) in transactions table. After that if I try to open the wirthdraw or deposit pages, I get this error.
But if I just click on update button in the account page, all works great then.

![schermata 2018-07-03 alle 16 35 56](https://user-images.githubusercontent.com/15124892/42226424-35e0c6c6-7edf-11e8-8c4c-cb76de301192.png)

**Comment by JC5** [comment]
Thanks for the screenshot! Which "the account page" are you talking about?

**Comment by colomarco** [comment]
In this page, I click on the green button without changing anything. After that i can open withdrawal and deposit without troubles.
Sorry for the italian page :)
![schermata 2018-07-03 alle 16 46 13](https://user-images.githubusercontent.com/15124892/42227068-ee5264fc-7ee0-11e8-897f-c8df204d4463.png)

**Comment by JC5** [comment]
Strange, because that one should not influence the page you were visiting. 

Try to browse to `/flush` after your manual import. That might clear the cache. If you are on the command line, run `php artisan cache:clear`.

**Comment by colomarco** [comment]
Oh great! This seems to work! 
I have to ask you one more thing...If I run my custom import php script inside the firefly folder (I put that in a custom folder called "import" under firefly/public), all the transactions are created twice. I'm pretty sure the loop is done just once, because if I run the same script outside firefly folder (I tried under /opt/), all works great!

**Comment by JC5** [comment]
That can only happen if your script actually executes twice. Are the entries in the database twice too?

**Comment by colomarco** [comment]
Yes the entries in the database are twice too. I run it just once, but inside that folder its executed twice and can't understand why. 
By the way I can run it outside the folder and all works. 
Is there a possibility to add a voice menu that just execute my custom script? Something like a simple exec of my php script?

**Comment by JC5** [comment]
That is strange, I don't know why either!

But I can't offer it inside Firefly III, I'm afraid.

**Comment by colomarco** [comment]
Oh ok I understand! 
Thank you so much for helping me! :)

**Comment by JC5** [comment]
:+1: you're welcome!
