### ISSUE TITLE
Generating a new private key failed. (on ampps)

### ISSUE THREAD

**Issue by quaasteniet** [firefly-iii/firefly-iii#1595]
I am running Firefly III version 4.7.5.3

**Description**
After inserting my api key from bunq and public ip, I hit submit, error appears.
I looked at the php.ini and see 'extension=php_openssl.dll' so that should be enabled.

**Steps to reproduce** 
- Insert api key
- Insert IP
- Hit submit

**Extra info**

Debug information generated at 2018-08-05 09:10:30 UTC for Firefly III version **4.7.5.3**.

| Variable | Content |
| --- | --- |
| FF version | 4.7.5.3 |
| FF API version | 0.6 |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | notice, daily |
| PHP version | 7.1.8 |
| Display errors | Off |
| Session start | 2018-08-01 00:00:00 |
| Session end | 2018-08-31 23:59:59 |
| Session first | 2018-08-04 00:00:00 |
| Error reporting | ALL errors |
| Host | WINNT |
| Interface | apache2handler |
| UserID | 1 |
| Attempt at "en" | 'en' |
| Attempt at "English" | 'English_United States.1252' |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| DB drivers | mysql, sqlite |
| Current driver | mysql |
| Using Sandstorm? | no |
| Is Sandstorm (.env) | false |
| Is Docker (.env) | false |
| bunq uses sandbox | false |
| Trusted proxies (.env) |  |
| User agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.75 Safari/537.36 OPR/55.0.2994.29 (Edition beta) |
| Loaded extensions | Core, bcmath, calendar, ctype, date, filter, hash, iconv, json, mcrypt, SPL, pcre, readline, Reflection, session, standard, mysqlnd, tokenizer, zip, zlib, libxml, dom, PDO, bz2, SimpleXML, xml, wddx, xmlreader, xmlwriter, apache2handler, openssl, curl, fileinfo, gd, gettext, gmp, intl, imap, mbstring, exif, mysqli, Phar, pdo_mysql, pdo_sqlite, soap, sockets, sqlite3, tidy, xmlrpc, xsl, com_dotnet, ionCube Loader, xdebug |
| Installed packages | bacon/bacon-qr-code@1.0.3, bunq/sdk_php@dev-master, davejamesmiller/laravel-breadcrumbs@5.1.0, defuse/php-encryption@v2.2.1, doctrine/cache@v1.7.1, doctrine/dbal@v2.8.0, doctrine/event-manager@v1.0.0, doctrine/inflector@v1.3.0, doctrine/lexer@v1.0.1, dragonmantank/cron-expression@v2.2.0, egulias/email-validator@2.1.4, erusev/parsedown@1.7.1, fideloper/proxy@4.0.0, firebase/php-jwt@v5.0.0, guzzlehttp/guzzle@6.3.3, guzzlehttp/promises@v1.3.1, guzzlehttp/psr7@1.4.2, laravel/framework@v5.6.29, laravel/passport@v5.0.3, laravelcollective/html@v5.6.10, lcobucci/jwt@3.2.2, league/commonmark@0.17.5, league/csv@9.1.4, league/event@2.1.2, league/flysystem@1.0.45, league/fractal@0.17.0, league/oauth2-server@6.1.1, monolog/monolog@1.23.0, nesbot/carbon@1.25.0, paragonie/constant_time_encoding@v2.2.2, paragonie/random_compat@v2.0.17, phpseclib/phpseclib@2.0.11, pragmarx/google2fa@v3.0.1, pragmarx/google2fa-laravel@v0.2.0, psr/container@1.0.0, psr/http-message@1.0.1, psr/log@1.0.2, psr/simple-cache@1.0.1, ramsey/uuid@3.8.0, rcrowe/twigbridge@v0.9.6, swiftmailer/swiftmailer@v6.1.2, symfony/console@v4.1.2, symfony/css-selector@v4.1.2, symfony/debug@v4.1.2, symfony/event-dispatcher@v4.1.2, symfony/finder@v4.1.2, symfony/http-foundation@v4.1.2, symfony/http-kernel@v4.1.2, symfony/polyfill-ctype@v1.8.0, symfony/polyfill-mbstring@v1.8.0, symfony/polyfill-php56@v1.8.0, symfony/polyfill-php72@v1.8.0, symfony/polyfill-util@v1.8.0, symfony/process@v4.1.2, symfony/psr-http-message-bridge@v1.0.2, symfony/routing@v4.1.2, symfony/translation@v4.1.2, symfony/var-dumper@v4.1.2, tijsverkoyen/css-to-inline-styles@2.2.1, twig/twig@v1.35.4, vlucas/phpdotenv@v2.5.0, zendframework/zend-diactoros@1.8.3,  |

```
Truncated from this point <----|\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#39 C:\Program Files (x86)\Ampps\www\firefly\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#40 C:\Program Files (x86)\Ampps\www\firefly\vendor\laravel\framework\src\Illuminate\Session\Middleware\StartSession.php(63): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#41 C:\Program Files (x86)\Ampps\www\firefly\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(151): Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#42 C:\Program Files (x86)\Ampps\www\firefly\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#43 C:\Program Files (x86)\Ampps\www\firefly\vendor\laravel\framework\src\Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse.php(37): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#44 C:\Program Files (x86)\Ampps\www\firefly\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(151): Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure))
#45 C:\Program Files (x86)\Ampps\www\firefly\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#46 C:\Program Files (x86)\Ampps\www\firefly\vendor\laravel\framework\src\Illuminate\Cookie\Middleware\EncryptCookies.php(59): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#47 C:\Program Files (x86)\Ampps\www\firefly\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(151): Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
#48 C:\Program Files (x86)\Ampps\www\firefly\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#49 C:\Program Files (x86)\Ampps\www\firefly\app\Http\Middleware\Sandstorm.php(54): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#50 C:\Program Files (x86)\Ampps\www\firefly\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(151): FireflyIII\Http\Middleware\Sandstorm->handle(Object(Illuminate\Http\Request), Object(Closure))
#51 C:\Program Files (x86)\Ampps\www\firefly\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#52 C:\Program Files (x86)\Ampps\www\firefly\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(104): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#53 C:\Program Files (x86)\Ampps\www\firefly\vendor\laravel\framework\src\Illuminate\Routing\Router.php(667): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#54 C:\Program Files (x86)\Ampps\www\firefly\vendor\laravel\framework\src\Illuminate\Routing\Router.php(642): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#55 C:\Program Files (x86)\Ampps\www\firefly\vendor\laravel\framework\src\Illuminate\Routing\Router.php(608): Illuminate\Routing\Router->runRoute(Object(Illuminate\Http\Request), Object(Illuminate\Routing\Route))
#56 C:\Program Files (x86)\Ampps\www\firefly\vendor\laravel\framework\src\Illuminate\Routing\Router.php(597): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#57 C:\Program Files (x86)\Ampps\www\firefly\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(176): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#58 C:\Program Files (x86)\Ampps\www\firefly\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(30): Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#59 C:\Program Files (x86)\Ampps\www\firefly\vendor\fideloper\proxy\src\TrustProxies.php(57): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#60 C:\Program Files (x86)\Ampps\www\firefly\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(151): Fideloper\Proxy\TrustProxies->handle(Object(Illuminate\Http\Request), Object(Closure))
#61 C:\Program Files (x86)\Ampps\www\firefly\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#62 C:\Program Files (x86)\Ampps\www\firefly\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\TransformsRequest.php(31): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#63 C:\Program Files (x86)\Ampps\www\firefly\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(151): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle(Object(Illuminate\Http\Request), Object(Closure))
#64 C:\Program Files (x86)\Ampps\www\firefly\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#65 C:\Program Files (x86)\Ampps\www\firefly\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\TransformsRequest.php(31): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#66 C:\Program Files (x86)\Ampps\www\firefly\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(151): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle(Object(Illuminate\Http\Request), Object(Closure))
#67 C:\Program Files (x86)\Ampps\www\firefly\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#68 C:\Program Files (x86)\Ampps\www\firefly\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\ValidatePostSize.php(27): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#69 C:\Program Files (x86)\Ampps\www\firefly\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(151): Illuminate\Foundation\Http\Middleware\ValidatePostSize->handle(Object(Illuminate\Http\Request), Object(Closure))
#70 C:\Program Files (x86)\Ampps\www\firefly\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#71 C:\Program Files (x86)\Ampps\www\firefly\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode.php(62): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#72 C:\Program Files (x86)\Ampps\www\firefly\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(151): Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#73 C:\Program Files (x86)\Ampps\www\firefly\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#74 C:\Program Files (x86)\Ampps\www\firefly\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(104): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#75 C:\Program Files (x86)\Ampps\www\firefly\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(151): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#76 C:\Program Files (x86)\Ampps\www\firefly\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(116): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#77 C:\Program Files (x86)\Ampps\www\firefly\public\index.php(76): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#78 {main}  

```

**Bonus points**
Earn bonus points by:

- Add a screenshot
- Replicate the problem on the demo site https://demo.firefly-iii.org/

**Comment by JC5** [comment]
You may not actually have openssl installed, which is a prerequisite for the openssl generation to work. Or there is no valid OPENSSL_CONF file, which will also prevent it from working.

Check out this guide that gives some hints on how to do this: http://php.net/manual/en/openssl.installation.php

A simple check to see if OpenSSL is configured correctly is this PHP file:

```
$config = array(
    "digest_alg" => "sha512",
    "private_key_bits" => 4096,
    "private_key_type" => OPENSSL_KEYTYPE_RSA,
);
    
// Create the private and public key
$res = openssl_pkey_new($config);

// Extract the private key from $res to $privKey
openssl_pkey_export($res, $privKey);

// Extract the public key from $res to $pubKey
$pubKey = openssl_pkey_get_details($res);
$pubKey = $pubKey["key"];

$data = 'plaintext data goes here';

// Encrypt the data to $encrypted using the public key
openssl_public_encrypt($data, $encrypted, $pubKey);

// Decrypt the data using the private key and store the results in $decrypted
openssl_private_decrypt($encrypted, $decrypted, $privKey);

echo $decrypted;
```

**Comment by quaasteniet** [comment]
It seems it's installed, this is also what I get from ampps info. That open-ssl is coming with the package, and by going to configuration -> php extensions . you can enable it. 
![tst-ssl](https://user-images.githubusercontent.com/19488831/43685274-3aff1d16-98b0-11e8-9f18-e06dc2b9bfc1.JPG)

**Comment by JC5** [comment]
Yes, but looking at the errors you're getting that's clearly not enough to actually make it work, is it?

Enabling the openssl extension from PHP won't do much without an actual openSSL installation.

**Comment by quaasteniet** [comment]
Ahh! that explains it, I was confused because Ampps seemed to indicate it came with the package, but now I understand I need to really install it next to Ampps. Thanks will try that

**Comment by JC5** [comment]
Thanks, let me know if it works!

I apologize for my tone, reading back I see I come across a bit rude. That wasn’t my intention.

**Comment by quaasteniet** [comment]
No worries!

**Comment by JC5** [comment]
Damn, that's annoying. I know openSSL on Windows can be tricky to run. But if it works! :+1:
