### ISSUE TITLE
No such file or directory after update

### ISSUE THREAD

**Issue by Johnpojohn** [firefly-iii/firefly-iii#1661]
**Bug description**
I am running Firefly III as a Docker container on a Synology NAS. After the last watchtower pull and database upgrade, i get the following error on the browser and log (Stacktrace attached)

local.ERROR: file_put_contents(/var/www/firefly-iii/storage/framework/cache/data/79/42/7942698bef726131c5478e8a9c79d865c6c9ad9a): failed to open stream: No such file or directory {"exception":"[object] (ErrorException(code: 0): file_put_contents(/var/www/firefly-iii/storage/framework/cache/data/79/42/7942698bef726131c5478e8a9c79d865c6c9ad9a): failed to open stream: No such file or directory at /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php:122)

**Steps to reproduce**
Clear container, pull latest image, create new container, input all environment variables, upgrade existing database through docker exec, launch browser app

[stacktrace.xlsx](https://github.com/firefly-iii/firefly-iii/files/2353288/stacktrace.xlsx)

**Comment by JC5** [comment]
Try running the following command in your container: `php artisan cache:clear`.

Could you add the stack trace as a plain text file or contained within code tags?

**Comment by Johnpojohn** [comment]
[trace.txt](https://github.com/firefly-iii/firefly-iii/files/2353502/trace.txt)

The command worked, but the result is still the same

**Comment by JC5** [comment]
Mmm. There's a good change that the `/var/www/firefly-iii/storage` directory is not owned by `www-data:www-data`. Which is weird because the entrypoint should take care of that.

Try the following:

```
chown -R www-data:www-data /var/www/firefly-iii/storage
chmod -R 777 /var/www/firefly-iii/storage
```

It's a basic trick but it should work.

**Comment by Johnpojohn** [comment]
Yup, that fixed it. Thanks!

**Comment by JC5** [comment]
Very good! Keep an eye on that container. The issue you ran into shouldn't happen.

When the next version comes out, see if you can save the logs from the upgrade. I am curious to see what happens. Thanks!

**Comment by pkoziol** [comment]
I run into this one while upgrading Firefly III from version 4.7.5.3 to 4.7.8.

I solved it by myself running:
```
koziolek@my-server:~/docker/firefly-iii$ docker-compose exec app bash
root@5b1bbc6e07c7:/var/www/firefly-iii# ls -l
total 1068
-rw-r--r--  1 root     root       4686 Oct 28 20:37 Dockerfile
-rw-r--r--  1 root     root      35148 Oct 28 20:37 LICENSE
-rw-r--r--  1 root     root      12962 Nov  8 18:28 NONE
-rw-r--r--  1 root     root         59 Oct 28 20:37 Procfile
drwxr-xr-x 26 root     root       4096 Oct 28 20:37 app
-rw-r--r--  1 root     root       1390 Oct 28 20:37 app.json
-rwxr-xr-x  1 root     root       1686 Oct 28 20:37 artisan
drwxr-xr-x  1 root     root       4096 Oct 28 20:37 bootstrap
-rw-r--r--  1 root     root      83304 Oct 28 20:37 changelog.md
-rw-r--r--  1 root     root       3411 Oct 28 20:37 composer.json
-rw-r--r--  1 root     root     266021 Oct 28 20:37 composer.lock
drwxr-xr-x  2 root     root       4096 Oct 28 20:37 config
-rw-r--r--  1 root     root       2803 Oct 28 20:37 crowdin.yml
drwxr-xr-x  5 root     root       4096 Oct 28 20:37 database
-rw-r--r--  1 root     root       1087 Oct 28 20:37 docker-compose.yml
-rw-r--r--  1 root     root       1708 Oct 28 20:37 index.php
-rw-r--r--  1 root     root        355 Oct 28 20:37 nginx_app.conf
-rwxr-xr-x  1 root     root     562163 Oct 28 20:37 package-lock.json
-rwxr-xr-x  1 root     root       1189 Oct 28 20:37 package.json
-rw-r--r--  1 root     root       1474 Oct 28 20:37 phpunit.coverage.specific.xml
-rw-r--r--  1 root     root       1469 Oct 28 20:37 phpunit.coverage.xml
-rw-r--r--  1 root     root       1262 Oct 28 20:37 phpunit.xml
drwxr-xr-x  8 root     root       4096 Oct 28 20:37 public
-rw-r--r--  1 root     root      12443 Oct 28 20:37 readme.md
drwxr-xr-x  6 root     root       4096 Oct 28 20:37 resources
drwxr-xr-x  2 root     root       4096 Oct 28 20:37 routes
-rw-r--r--  1 root     root        588 Oct 28 20:37 server.php
drwxrwxr-x  1 www-data www-data   4096 Nov  8 18:28 storage
drwxr-xr-x  6 root     root       4096 Oct 28 20:37 tests
drwxr-xr-x  1 root     root       4096 Oct 28 20:57 vendor
-rw-r--r--  1 root     root        492 Oct 28 20:37 webpack.mix.js
root@5b1bbc6e07c7:/var/www/firefly-iii# cd storage/
root@5b1bbc6e07c7:/var/www/firefly-iii/storage# ls -l
total 40
drwxrwxr-x 1 www-data www-data 4096 Oct 28 20:37 app
drwxrwxr-x 1 www-data www-data 4096 Oct 28 20:37 build
drwxrwxr-x 1 www-data www-data 4096 Oct 28 20:37 database
drwxrwxr-x 1 www-data www-data 4096 Oct 28 20:37 debugbar
drwxrwxr-x 2 www-data www-data 4096 Feb 24  2018 export
drwxrwxr-x 1 www-data www-data 4096 Oct 28 20:37 framework
drwxrwxr-x 1 www-data www-data 4096 Oct 28 20:37 logs
-rw-r--r-- 1 root     root     3292 Nov  8 18:28 oauth-private.key
-rw-r--r-- 1 root     root      812 Nov  8 18:28 oauth-public.key
drwxrwxr-x 2 www-data www-data 4096 Feb 24  2018 upload
root@5b1bbc6e07c7:/var/www/firefly-iii/storage# cd framework/
root@5b1bbc6e07c7:/var/www/firefly-iii/storage/framework# ls -l
total 16
drwxrwxr-x 1 www-data www-data 4096 Nov  8 18:28 cache
drwxrwxr-x 1 www-data www-data 4096 Oct 28 20:37 sessions
drwxrwxr-x 1 www-data www-data 4096 Oct 28 20:37 testing
drwxrwxr-x 1 www-data www-data 4096 Nov  8 18:28 views
root@5b1bbc6e07c7:/var/www/firefly-iii/storage/framework# cd cache/
root@5b1bbc6e07c7:/var/www/firefly-iii/storage/framework/cache# ls -l
total 4
drwxr-xr-x 2 root root 4096 Nov  8 18:28 data
root@5b1bbc6e07c7:/var/www/firefly-iii/storage/framework/cache# chown -R www-data:www-data data/
root@5b1bbc6e07c7:/var/www/firefly-iii/storage/framework/cache# exit
```

Unfortunately I didn't listed contents of `data`, but I guess all files were owned by root?

Command history:
```
koziolek@my-server:~/docker/firefly-iii$ history | tail -n 30
...
 2611  2018-11-08 18:19:35 docker ps | grep firefly
 2612  2018-11-08 18:20:14 docker-compose ps
 2613  2018-11-08 18:20:20 docker-compose pull app
 2614  2018-11-08 18:20:31 vim docker-compose.yml
 2615  2018-11-08 18:23:27 docker-compose pull app
 2616  2018-11-08 18:24:34 docker image ls | grep firef
 2617  2018-11-08 18:24:41 df -h
 2618  2018-11-08 18:25:03 docker-compose restart app
 2619  2018-11-08 18:25:34 docker-compose up -d
 2620  2018-11-08 18:26:15 docker-compose exec app php artisan migrate --seed
 2621  2018-11-08 18:28:02 docker-compose exec app php artisan firefly:upgrade-database
 2622  2018-11-08 18:28:23 docker-compose exec app php artisan firefly:verify
 2623  2018-11-08 18:28:35 docker-compose exec app php artisan passport:install
 2624  2018-11-08 18:28:46 docker-compose exec app php artisan cache:clear
 2625  2018-11-08 18:29:06 history | less
 2626  2018-11-08 18:29:52 docker-compose exec app bash
 2627  2018-11-08 18:49:56 docker-compose logs app | less
...
```

Logs:
```
Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
Discovered Package: adldap2/adldap2-laravel
Discovered Package: danhunsaker/laravel-flysystem-others
Discovered Package: davejamesmiller/laravel-breadcrumbs
Discovered Package: fideloper/proxy
Discovered Package: laravel/passport
Discovered Package: laravelcollective/html
Discovered Package: nesbot/carbon
Discovered Package: pragmarx/google2fa-laravel
Discovered Package: rcrowe/twigbridge
Package manifest generated successfully.
+------------------------------------------------------------------------------+
|                                                                              |
| Thank you for installing Firefly III, v4.7.8!                                |
|                                                                              |
|                                                                              |
+------------------------------------------------------------------------------+
2018-11-08 18:25:59,110 CRIT Supervisor running as root (no user in config file)
2018-11-08 18:25:59,112 INFO Included extra file "/etc/supervisor/conf.d/cronjob.conf" during parsing
2018-11-08 18:25:59,112 INFO Included extra file "/etc/supervisor/conf.d/firefly-iii.conf" during parsing
2018-11-08 18:25:59,140 INFO RPC interface 'supervisor' initialized
2018-11-08 18:25:59,140 CRIT Server 'unix_http_server' running without any HTTP authentication checking
2018-11-08 18:25:59,140 INFO supervisord started with pid 1
2018-11-08 18:26:00,145 INFO spawned: 'cron' with pid 48
2018-11-08 18:26:00,149 INFO spawned: 'apache2' with pid 49
2018-11-08 18:26:00,404 DEBG 'apache2' stderr output:
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.21.0.3. Set the 'ServerName' directive globally to suppress this message

2018-11-08 18:26:00,446 DEBG 'apache2' stderr output:
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.21.0.3. Set the 'ServerName' directive globally to suppress this message

2018-11-08 18:26:00,521 DEBG 'apache2' stderr output:
[Thu Nov 08 18:26:00.521241 2018] [mpm_prefork:notice] [pid 49] AH00163: Apache/2.4.25 (Debian) PHP/7.2.11 OpenSSL/1.0.2l configured -- resuming normal operations
[Thu Nov 08 18:26:00.521426 2018] [core:notice] [pid 49] AH00094: Command line: '/usr/sbin/apache2 -D FOREGROUND'

2018-11-08 18:26:01,525 INFO success: apache2 entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2018-11-08 18:26:10,548 INFO success: cron entered RUNNING state, process has stayed up for > than 10 seconds (startsecs)
[2018-11-08 18:28:51] production.ERROR: file_put_contents(/var/www/firefly-iii/storage/framework/cache/data/79/42/7942698bef726131c5478e8a9c79d865c6c9ad9a): failed to open stream: No such file or directory {"exception":"[object] (ErrorException(code: 0): file_put_contents(/var/www/firefly-iii/storage/framework/cache/data/79/42/7942698bef726131c5478e8a9c79d865c6c9ad9a): failed to open stream: No such file or directory at /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php:122)
[stacktrace]
#0 [internal function]: Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError(2, 'file_put_conten...', '/var/www/firefl...', 122, Array)
#1 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php(122): file_put_contents('/var/www/firefl...', '9999999999O:31:...', 2)
#2 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Cache/FileStore.php(65): Illuminate\\Filesystem\\Filesystem->put('/var/www/firefl...', '9999999999O:31:...', true)
#3 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Cache/FileStore.php(119): Illuminate\\Cache\\FileStore->put('ff-config-is_de...', Object(FireflyIII\\Models\\Configuration), 0)
#4 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Cache/Repository.php(305): Illuminate\\Cache\\FileStore->forever('ff-config-is_de...', Object(FireflyIII\\Models\\Configuration))
#5 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Cache/CacheManager.php(304): Illuminate\\Cache\\Repository->forever('ff-config-is_de...', Object(FireflyIII\\Models\\Configuration))
#6 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(223): Illuminate\\Cache\\CacheManager->__call('forever', Array)
#7 /var/www/firefly-iii/app/Support/FireflyConfig.php(68): Illuminate\\Support\\Facades\\Facade::__callStatic('forever', Array)
#8 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(223): FireflyIII\\Support\\FireflyConfig->get('is_demo_site', false)
#9 /var/www/firefly-iii/app/Http/Controllers/Controller.php(64): Illuminate\\Support\\Facades\\Facade::__callStatic('get', Array)
#10 /var/www/firefly-iii/app/Http/Controllers/HomeController.php(48): FireflyIII\\Http\\Controllers\\Controller->__construct()
#11 [internal function]: FireflyIII\\Http\\Controllers\\HomeController->__construct()
#12 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Container/Container.php(812): ReflectionClass->newInstanceArgs(Array)
#13 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Container/Container.php(658): Illuminate\\Container\\Container->build('FireflyIII\\\\Http...')
#14 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Container/Container.php(609): Illuminate\\Container\\Container->resolve('FireflyIII\\\\Http...', Array)
#15 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(733): Illuminate\\Container\\Container->make('FireflyIII\\\\Http...', Array)
#16 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Routing/Route.php(226): Illuminate\\Foundation\\Application->make('FireflyIII\\\\Http...')
#17 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Routing/Route.php(796): Illuminate\\Routing\\Route->getController()
#18 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Routing/Route.php(757): Illuminate\\Routing\\Route->controllerMiddleware()
#19 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Routing/Router.php(692): Illuminate\\Routing\\Route->gatherMiddleware()
#20 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Routing/Router.php(672): Illuminate\\Routing\\Router->gatherRouteMiddleware(Object(Illuminate\\Routing\\Route))
#21 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Routing/Router.php(656): Illuminate\\Routing\\Router->runRouteWithinStack(Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request))
#22 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Routing/Router.php(622): Illuminate\\Routing\\Router->runRoute(Object(Illuminate\\Http\\Request), Object(Illuminate\\Routing\\Route))
#23 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Routing/Router.php(611): Illuminate\\Routing\\Router->dispatchToRoute(Object(Illuminate\\Http\\Request))
#24 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(176): Illuminate\\Routing\\Router->dispatch(Object(Illuminate\\Http\\Request))
#25 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}(Object(Illuminate\\Http\\Request))
#26 /var/www/firefly-iii/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#27 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Fideloper\\Proxy\\TrustProxies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#28 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#29 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(31): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#30 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#31 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#32 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(31): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#33 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#34 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#35 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#36 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#37 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#38 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(62): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#39 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#40 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#41 /var/www/firefly-iii/app/Http/Middleware/SecureHeaders.php(45): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#42 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): FireflyIII\\Http\\Middleware\\SecureHeaders->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#43 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#44 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(104): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#45 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(151): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#46 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(116): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#47 /var/www/firefly-iii/public/index.php(76): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#48 {main}
"} 
2018-11-08 18:28:51,820 DEBG 'apache2' stdout output:
[2018-11-08 18:28:51] production.ERROR: file_put_contents(/var/www/firefly-iii/storage/framework/cache/data/79/42/7942698bef726131c5478e8a9c79d865c6c9ad9a): failed to open stream: No such file or directory {"exception":"[object] (ErrorException(code: 0): file_put_contents(/var/www/firefly-iii/storage/framework/cache/data/79/42/7942698bef726131c5478e8a9c79d865c6c9ad9a): failed to open stream: No such file or directory at /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php:122)
[stacktrace]
#0 [internal function]: Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError(2, 'file_put_conten...', '/var/www/firefl...', 122, Array)
#1 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php(122): file_put_contents('/var/www/firefl...', '9999999999O:31:...', 2)
#2 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Cache/FileStore.php(65): Illuminate\\Filesystem\\Filesystem->put('/var/www/firefl...', '9999999999O:31:...', true)
#3 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Cache/FileStore.php(119): Illuminate\\Cache\\FileStore->put('ff-config-is_de...', Object(FireflyIII\\Models\\Configuration), 0)
#4 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Cache/Repository.php(305): Illuminate\\Cache\\FileStore->forever('ff-config-is_de...', Object(FireflyIII\\Models\\Configuration))
#5 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Cache/CacheManager.php(304): Illuminate\\Cache\\Repository->forever('ff-config-is_de...', Object(FireflyIII\\Models\\Configuration))
#6 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(223): Illuminate\\Cache\\CacheManager->__call('forever', Array)
#7 /var/www/firefly-iii/app/Support/FireflyConfig.php(68): Illuminate\\Support\\Facades\\Facade::__callStatic('forever', Array)
#8 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(223): FireflyIII\\Support\\FireflyConfig->get('is_demo_site', false)
#9 /var/www/firefly-iii/app/Http/Controllers/Controller.php(64): Illuminate\\Support\\Facades\\Facade::__callStatic('get', Array)
#10 /var/www/firefly-iii/app/Http/Controllers/HomeController.php(48): FireflyIII\\Http\\Controllers\\Controller->__construct()
#11 [internal function]: FireflyIII\\Http\\Controllers\\HomeController->__construct()
#12 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Container/Container.php(812): ReflectionClass->newInstanceArgs(Array)
#13 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Container/Container.php(658): Illuminate\\Container\\Container->build('FireflyIII\\\\Http...')
#14 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Container/Container.php(609): Illuminate\\Container\\Container->resolve('FireflyIII\\\\Http...', Array)
#15 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(733): Illuminate\\Container\\Container->make('FireflyIII\\\\Http...', Array)
#16 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Routing/Route.php(226): Illuminate\\Foundation\\Application->make('FireflyIII\\\\Http...')
#17 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Routing/Route.php(796): Illuminate\\Routing\\Route->getController()
#18 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Routing/Route.php(757): Illuminate\\Routing\\Route->controllerMiddleware()
#19 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Routing/Router.php(692): Illuminate\\Routing\\Route->gatherMiddleware()
#20 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Routing/Router.php(672): Illuminate\\Routing\\Router->gatherRouteMiddleware(Object(Illuminate\\Routing\\Route))
#21 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Routing/Router.php(656): Illuminate\\Routing\\Router->runRouteWithinStack(Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request))
#22 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Routing/Router.php(622): Illuminate\\Routing\\Router->runRoute(Object(Illuminate\\Http\\Request), Object(Illuminate\\Routing\\Route))
#23 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Routing/Router.php(611): Illuminate\\Routing\\Router->dispatchToRoute(Object(Illuminate\\Http\\Request))
#24 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(176): Illuminate\\Routing\\Router->dispatch(Object(Illuminate\\Http\\Request))
#25 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}(Object(Illuminate\\Http\\Request))
#26 /var/www/firefly-iii/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#27 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Fideloper\\Proxy\\TrustProxies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#28 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#29 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(31): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#30 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#31 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#32 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(31): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#33 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#34 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#35 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#36 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#37 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#38 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(62): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#39 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#40 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#41 /var/www/firefly-iii/app/Http/Middleware/SecureHeaders.php(45): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#42 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): FireflyIII\\Http\\Middleware\\SecureHeaders->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#43 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#44 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(104): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#45 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(151): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#46 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(116): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#47 /var/www/firefly-iii/public/index.php(76): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#48 {main}
"} 

172.18.0.7 - - [08/Nov/2018:18:28:51 +0100] "GET / HTTP/1.1" 500 3640 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:63.0) Gecko/20100101 Firefox/63.0"
2018-11-08 18:28:51,861 DEBG 'apache2' stdout output:
172.18.0.7 - - [08/Nov/2018:18:28:51 +0100] "GET / HTTP/1.1" 500 3640 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:63.0) Gecko/20100101 Firefox/63.0"
```

I run all `docker-compose exec app php artisan ...` commands as me (`koziolek`) on the host, which runs it as `root` in the container (judging by who I was after opening bash).

**Comment by pkoziol** [comment]
Or maybe run php artisan as different user like:
```
koziolek@my-server:~/docker/firefly-iii$ docker-compose exec app su www-data -s /bin/bash -c whoami
www-data
```
vs default way:
```
koziolek@my-server:~/docker/firefly-iii$ docker-compose exec app whoami
root
```

**Comment by JC5** [comment]
Good idea!
