### ISSUE TITLE
CronJobs: PDOException(code: 0): could not find driver 

### ISSUE THREAD

**Issue by skuzzle** [firefly-iii/firefly-iii#1688]
Hi,

this is just a minor issue.

**Bug description**
I am running Firefly III version 4.7.6.2

When I execute the cron script using 
```
php artisan firefly:cron
```

I get above message on the console. Below follows a complete stack trace. I believe this might have to do with my recent upgrade to PHP 7.2.9. As you might remember, I run this stuff on a windows server x_x
It seems that firefly creates the transactions correclty though.

Here is a short excerpt from `phph -i`:

```
pdo_mysql

PDO Driver for MySQL => enabled
Client API version => mysqlnd 5.0.12-dev - 20150407 - $Id: 38fea24f2847fa7519001be390c98ae0acafe387 $
```

And now the stack trace (I shortened the absolute paths):

```
[2018-09-13 15:35:25] production.ERROR: could not find driver (SQL: select * from 'recurrences' where 'recurrences'.'deleted_at' is null order by 'active' desc, 'title' asc) {"exception":"[object] (Illuminate\\Database\\QueryException(code: 0): could not find driver (SQL: select * from 'recurrences' where 'recurrences'.'deleted_at' is null order by 'active' desc, 'title' asc) at C:\
[...]\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Connection.php:664, Doctrine\\DBAL\\Driver\\PDOException(code: 0): could not find driver at C:\
[...]\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOConnection.php:50, PDOException(code: 0): could not find driver at C:\
[...]\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOConnection.php:46)
[stacktrace]
#0  C:\[...]\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Connection.php(624): Illuminate\\Database\\Connection->runQueryCallback('select * from '...', Array, Object(Closure))
#1  C:\[...]\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Connection.php(333): Illuminate\\Database\\Connection->run('select * from '...', Array, Object(Closure))
#2  C:\[...]\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Query\\Builder.php(1963): Illuminate\\Database\\Connection->select('select * from '...', Array, true)
#3  C:\[...]\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Query\\Builder.php(1951): Illuminate\\Database\\Query\\Builder->runSelect()
#4  C:\[...]\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Query\\Builder.php(2435): Illuminate\\Database\\Query\\Builder->Illuminate\\Database\\Query\\{closure}()
#5  C:\[...]\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Query\\Builder.php(1952): Illuminate\\Database\\Query\\Builder->onceWithColumns(Array, Object(Closure))
#6  C:\[...]\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Eloquent\\Builder.php(481): Illuminate\\Database\\Query\\Builder->get(Array)
#7  C:\[...]\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Eloquent\\Builder.php(465): Illuminate\\Database\\Eloquent\\Builder->getModels(Array)
#8  C:\[...]\\app\\Repositories\\Recurring\\RecurringRepository.php(108): Illuminate\\Database\\Eloquent\\Builder->get()
#9  C:\[...]\\app\\Jobs\\CreateRecurringTransactions.php(87): FireflyIII\\Repositories\\Recurring\\RecurringRepository->getAll()
#10 C:\[...]\\app\\Support\\Cronjobs\\RecurringCronjob.php(81): FireflyIII\\Jobs\\CreateRecurringTransactions->handle()
#11 C:\[...]\\app\\Support\\Cronjobs\\RecurringCronjob.php(64): FireflyIII\\Support\\Cronjobs\\RecurringCronjob->fireRecurring()
#12 C:\[...]\\app\\Console\\Commands\\Cron.php(48): FireflyIII\\Support\\Cronjobs\\RecurringCronjob->fire()
#13 [internal function]: FireflyIII\\Console\\Commands\\Cron->handle()
#14 C:\[...]\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\BoundMethod.php(29): call_user_func_array(Array, Array)
#15 C:\[...]\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\BoundMethod.php(87): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#16 C:\[...]\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\BoundMethod.php(31): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#17 C:\[...]\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\Container.php(564): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#18 C:\[...]\\vendor\\laravel\\framework\\src\\Illuminate\\Console\\Command.php(179): Illuminate\\Container\\Container->call(Array)
#19 C:\[...]\\vendor\\symfony\\console\\Command\\Command.php(251): Illuminate\\Console\\Command->execute(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#20 C:\[...]\\vendor\\laravel\\framework\\src\\Illuminate\\Console\\Command.php(166): Symfony\\Component\\Console\\Command\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#21 C:\[...]\\vendor\\symfony\\console\\Application.php(886): Illuminate\\Console\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#22 C:\[...]\\vendor\\symfony\\console\\Application.php(262): Symfony\\Component\\Console\\Application->doRunCommand(Object(FireflyIII\\Console\\Commands\\Cron), Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#23 C:\[...]\\vendor\\symfony\\console\\Application.php(145): Symfony\\Component\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#24 C:\[...]\\vendor\\laravel\\framework\\src\\Illuminate\\Console\\Application.php(89): Symfony\\Component\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#25 C:\[...]\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Console\\Kernel.php(122): Illuminate\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#26 C:\[...]\\artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#27 {main}
"} 
```

**Comment by JC5** [comment]
Mmmm. So either it can find the driver in order to create the transactions, or it can't find the driver and it won't create any transactions.

It can't be that it cannot find the driver and still creates transactions :wink:

Do other commands work, like firefly:verify or firefly:upgrade?

**Comment by skuzzle** [comment]
It seems like this was a configuration issue on my machine. There was a mixture of different php versions running, where the php 7.2 would use the php 7.1 configuration file or something like this. I believe that I've solved this now
