### ISSUE TITLE
Recurring transactions cron job fails

### ISSUE THREAD

**Issue by spirituallyinsane** [firefly-iii/firefly-iii#1804]
**Bug description**
I am running Firefly III version 4.7.7

cron job to create recurring transactions fails to error: 
```
In RecurringRepository.php line 406:
                                                                               
  Argument 1 passed to FireflyIII\Repositories\Recurring\RecurringRepository:  
  :setUser() must be an instance of FireflyIII\User, null given, called in /h  
  ome4/broadsp9/firefly-iii/app/Jobs/CreateRecurringTransactions.php on line   
  104
```
This is reproduced when attempting to run the job manually from a shell prompt.

**Steps to reproduce**
1. Set up cron job using steps in [official documentation](https://firefly-iii.readthedocs.io/en/latest/installation/cronjob.html), specifically using `crontab -e` and adding the job of form: 
```
# cron job for Firefly III
0 3 * * * /usr/bin/php /var/www/firefly-iii/artisan firefly:cron
```
2. Wait for cron job to fire. 

**OR**

From a shell, attempt to run the PHP command directly.

**Expected behavior**
cron job will run without errors, and recurring transactions will be created.

**Extra info**
Please add extra info here, such as OS, browser, and the output from the /debug page of your Firefly III installation (click the version at the bottom).

Debug information generated at 2018-10-19 13:58:30 America/Chicago for Firefly III version **4.7.7**.

| Variable | Content |
| --- | --- |
| FF version | 4.7.7 |
| FF API version | 0.8 |
| App environment | local |
| App debug mode | true |
| App cache driver | file |
| App logging | info, daily |
| PHP version | 7.2.11 |
| Display errors | Off |
| Session start | 2018-10-01 00:00:00 |
| Session end | 2018-10-31 23:59:59 |
| Session first | 2017-02-23 00:00:00 |
| Error reporting | ALL errors |
| Host | Linux |
| Interface | cgi-fcgi |
| UserID | 2 |
| Attempt at "en" | false |
| Attempt at "English" | false |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | mysql |
| Using Sandstorm? | no |
| Is Sandstorm (.env) | false |
| Is Docker (.env) | false |
| bunq uses sandbox | false |
| Trusted proxies (.env) |  |
| User agent | Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36 |
| Loaded extensions | Core, date, libxml, openssl, pcre, zlib, filter, hash, pcntl, readline, Reflection, SPL, session, standard, cgi-fcgi, bcmath, bz2, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, gmp, iconv, imap, intl, json, exif, mcrypt, mysqlnd, odbc, PDO, pgsql, Phar, posix, pspell, SimpleXML, soap, sockets, sqlite3, tidy, tokenizer, xml, xmlwriter, xsl, zip, mysqli, pdo_mysql, PDO_ODBC, pdo_pgsql, pdo_sqlite, wddx, xmlreader, xmlrpc, imagick, ionCube Loader |
| Installed packages | bacon/bacon-qr-code@1.0.3, bunq/sdk_php@dev-master, davejamesmiller/laravel-breadcrumbs@5.1.2, defuse/php-encryption@v2.2.1, doctrine/cache@v1.8.0, doctrine/dbal@v2.8.0, doctrine/event-manager@v1.0.0, doctrine/inflector@v1.3.0, doctrine/lexer@v1.0.1, dragonmantank/cron-expression@v2.2.0, egulias/email-validator@2.1.6, erusev/parsedown@1.7.1, fideloper/proxy@4.0.0, firebase/php-jwt@v5.0.0, guzzlehttp/guzzle@6.3.3, guzzlehttp/promises@v1.3.1, guzzlehttp/psr7@1.4.2, laravel/framework@v5.7.6, laravel/passport@v7.0.2, laravelcollective/html@v5.7.1, lcobucci/jwt@3.2.4, league/commonmark@0.18.0, league/csv@9.1.4, league/event@2.1.2, league/flysystem@1.0.47, league/fractal@0.17.0, league/oauth2-server@7.2.0, monolog/monolog@1.23.0, nesbot/carbon@1.34.0, paragonie/constant_time_encoding@v2.2.2, paragonie/random_compat@v9.99.99, phpseclib/phpseclib@2.0.11, pragmarx/google2fa@v3.0.3, pragmarx/google2fa-laravel@v0.2.0, psr/container@1.0.0, psr/http-message@1.0.1, psr/log@1.0.2, psr/simple-cache@1.0.1, ramsey/uuid@3.8.0, rcrowe/twigbridge@v0.9.8, swiftmailer/swiftmailer@v6.1.3, symfony/console@v4.1.4, symfony/css-selector@v4.1.4, symfony/debug@v4.1.4, symfony/event-dispatcher@v4.1.4, symfony/finder@v4.1.4, symfony/http-foundation@v4.1.4, symfony/http-kernel@v4.1.4, symfony/polyfill-ctype@v1.9.0, symfony/polyfill-mbstring@v1.9.0, symfony/polyfill-php56@v1.9.0, symfony/polyfill-php72@v1.9.0, symfony/polyfill-util@v1.9.0, symfony/process@v4.1.4, symfony/psr-http-message-bridge@v1.1.0, symfony/routing@v4.1.4, symfony/translation@v4.1.4, symfony/var-dumper@v4.1.4, tijsverkoyen/css-to-inline-styles@2.2.1, twig/twig@v1.35.4, vlucas/phpdotenv@v2.5.1, zendframework/zend-diactoros@1.8.6,  |

**Comment by JC5** [comment]
Could you share some details from the database? The situation that `$recurrence->user` is null is pretty much impossible. I could add a check for this but if I start at this level I would have to rewrite everything :grin:

I would like to see if there are recurrences that are owned by a deleted user, for example. Otherwise I have no idea what could be going on.

**Comment by spirituallyinsane** [comment]
I'm happy to share some tables if that's helpful.  It definitely looks like there's a recurring transaction assigned to a deleted user: 

![image](https://user-images.githubusercontent.com/14048499/47248661-dfbefd80-d3d9-11e8-8081-458bb711b469.png)

I had originally created a test user to try out a few things, then deleted that user and created my current user.  Let me know what else you'd like to see from the database, and I'll gladly get them to you.

**Comment by JC5** [comment]
How did you delete your test user?

MySQL supports foreign keys, and tries to keep the integrity of the database. Judging by what you're telling me, you managed to delete the user but not the related tables. This is, by default, impossible. If you delete a row from the `users` table, all related information in the database will be gone too. The same applies when you delete your account from within Firefly III.

Also important, which version of MySQL and phpMyAdmin are you running?

It's not really a bug, but the consequences of a database that is missing vital information, and I can't do much more to prevent that.

**Comment by spirituallyinsane** [comment]
Certainly.  I deleted the user from inside Firefly, using the following link:

![image](https://user-images.githubusercontent.com/14048499/47252380-d94c7800-d411-11e8-9b5d-67cd21e8a09c.png)

I'm using phpMyAdmin 4.7.7, looks like MySQL version is:
`mysql  Ver 14.14 Distrib 5.6.41-84.1, for Linux (x86_64) using  6.0`

Of note, there doesn't appear to be a users table in the database.  I spent a fair bit of time going through the tables to try and find where the users were defined, and couldn't find it!  It makes much more sense now that I know there's supposed to be a users table.

I have only accessed the database using Firefly, or for read-only through phpMyAdmin.  I'm curious how the users table got dropped.

**Comment by JC5** [comment]
This is getting stranger and stranger. The users are located in a table called `users`. If that table is gone nothing should work :grin:.

**Comment by spirituallyinsane** [comment]
Alas, I am userless!  
![image](https://user-images.githubusercontent.com/14048499/47252520-4fea7500-d414-11e8-8f42-1d1b59bb3ebe.png)

I'm going look in the database backup I made before I deleted the user.  Will advise if users table appears to have been dropped during user deletion.

**Comment by spirituallyinsane** [comment]
There was definitely something going on after I created the new user account.  Recurring stack traces:
```
[2018-10-16 11:04:39] local.ERROR: The payload is invalid. {"userId":2,"email":"spirituallyinsane@gmail.com","exception":"[object] (Illuminate\\Contracts\\Encryption\\DecryptException(code: 0): The payload is invalid. at /home4/broadsp9/firefly-iii/vendor/laravel/framework/src/Illuminate/Encryption/Encrypter.php:191)
[stacktrace]
#0 /home4/broadsp9/firefly-iii/vendor/laravel/framework/src/Illuminate/Encryption/Encrypter.php(134): Illuminate\\Encryption\\Encrypter->getJsonPayload(NULL)
#1 /home4/broadsp9/firefly-iii/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(223): Illuminate\\Encryption\\Encrypter->decrypt('Paycheck')
#2 /home4/broadsp9/firefly-iii/app/Support/Steam.php(390): Illuminate\\Support\\Facades\\Facade::__callStatic('decrypt', Array)
#3 /home4/broadsp9/firefly-iii/app/Support/Search/Modifier.php(200): FireflyIII\\Support\\Steam->decrypt(1, 'Paycheck')
#4 /home4/broadsp9/firefly-iii/app/Support/Search/Modifier.php(76): FireflyIII\\Support\\Search\\Modifier::category(Object(FireflyIII\\Models\\Transaction), 'paycheck')
#5 /home4/broadsp9/firefly-iii/app/Support/Search/Search.php(286): FireflyIII\\Support\\Search\\Modifier::apply(Array, Object(FireflyIII\\Models\\Transaction))
#6 /home4/broadsp9/firefly-iii/app/Support/Search/Search.php(137): FireflyIII\\Support\\Search\\Search->matchModifiers(Object(FireflyIII\\Models\\Transaction))
#7 [internal function]: FireflyIII\\Support\\Search\\Search->FireflyIII\\Support\\Search\\{closure}(Object(FireflyIII\\Models\\Transaction), 0)
#8 /home4/broadsp9/firefly-iii/vendor/laravel/framework/src/Illuminate/Support/Arr.php(617): array_filter(Array, Object(Closure), 1)
#9 /home4/broadsp9/firefly-iii/vendor/laravel/framework/src/Illuminate/Support/Collection.php(481): Illuminate\\Support\\Arr::where(Array, Object(Closure))
#10 /home4/broadsp9/firefly-iii/app/Support/Search/Search.php(143): Illuminate\\Support\\Collection->filter(Object(Closure))
#11 /home4/broadsp9/firefly-iii/app/Http/Controllers/SearchController.php(100): FireflyIII\\Support\\Search\\Search->searchTransactions()
#12 [internal function]: FireflyIII\\Http\\Controllers\\SearchController->search(Object(Illuminate\\Http\\Request), Object(FireflyIII\\Support\\Search\\Search))
#13 /home4/broadsp9/firefly-iii/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): call_user_func_array(Array, Array)
#14 /home4/broadsp9/firefly-iii/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\\Routing\\Controller->callAction('search', Array)
#15 /home4/broadsp9/firefly-iii/vendor/laravel/framework/src/Illuminate/Routing/Route.php(212): Illuminate\\Routing\\ControllerDispatcher->dispatch(Object(Illuminate\\Routing\\Route), Object(FireflyIII\\Http\\Controllers\\SearchController), 'search')
#16 /home4/broadsp9/firefly-iii/vendor/laravel/framework/src/Illuminate/Routing/Route.php(169): Illuminate\\Routing\\Route->runController()
#17 /home4/broadsp9/firefly-iii/vendor/laravel/framework/src/Illuminate/Routing/Router.php(679): Illuminate\\Routing\\Route->run()
#18 /home4/broadsp9/firefly-iii/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#19 /home4/broadsp9/firefly-iii/app/Http/Controllers/SearchController.php(50): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#20 /home4/broadsp9/firefly-iii/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(133): FireflyIII\\Http\\Controllers\\SearchController->FireflyIII\\Http\\Controllers\\{closure}(Object(Illuminate\\Http\\Request), Object(Closure))
#21 /home4/broadsp9/firefly-iii/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#22 /home4/broadsp9/firefly-iii/app/Http/Controllers/Controller.php(88): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#23 /home4/broadsp9/firefly-iii/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(133): FireflyIII\\Http\\Controllers\\Controller->FireflyIII\\Http\\Controllers\\{closure}(Object(Illuminate\\Http\\Request), Object(Closure))
#24 /home4/broadsp9/firefly-iii/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#25 /home4/broadsp9/firefly-iii/app/Http/Middleware/Binder.php(78): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#26 /home4/broadsp9/firefly-iii/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): FireflyIII\\Http\\Middleware\\Binder->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#27 /home4/broadsp9/firefly-iii/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#28 /home4/broadsp9/firefly-iii/app/Http/Middleware/Range.php(60): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#29 /home4/broadsp9/firefly-iii/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): FireflyIII\\Http\\Middleware\\Range->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#30 /home4/broadsp9/firefly-iii/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#31 /home4/broadsp9/firefly-iii/app/Http/Middleware/AuthenticateTwoFactor.php(86): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#32 /home4/broadsp9/firefly-iii/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): FireflyIII\\Http\\Middleware\\AuthenticateTwoFactor->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#33 /home4/broadsp9/firefly-iii/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#34 /home4/broadsp9/firefly-iii/app/Http/Middleware/Authenticate.php(73): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#35 /home4/broadsp9/firefly-iii/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): FireflyIII\\Http\\Middleware\\Authenticate->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#36 /home4/broadsp9/firefly-iii/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#37 /home4/broadsp9/firefly-iii/vendor/laravel/passport/src/Http/Middleware/CreateFreshApiToken.php(50): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#38 /home4/broadsp9/firefly-iii/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Laravel\\Passport\\Http\\Middleware\\CreateFreshApiToken->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#39 /home4/broadsp9/firefly-iii/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#40 /home4/broadsp9/firefly-iii/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(75): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#41 /home4/broadsp9/firefly-iii/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#42 /home4/broadsp9/firefly-iii/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#43 /home4/broadsp9/firefly-iii/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#44 /home4/broadsp9/firefly-iii/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#45 /home4/broadsp9/firefly-iii/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#46 /home4/broadsp9/firefly-iii/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(63): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#47 /home4/broadsp9/firefly-iii/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\Session\\Middleware\\StartSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#48 /home4/broadsp9/firefly-iii/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#49 /home4/broadsp9/firefly-iii/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#50 /home4/broadsp9/firefly-iii/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#51 /home4/broadsp9/firefly-iii/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#52 /home4/broadsp9/firefly-iii/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(66): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#53 /home4/broadsp9/firefly-iii/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#54 /home4/broadsp9/firefly-iii/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#55 /home4/broadsp9/firefly-iii/app/Http/Middleware/Sandstorm.php(54): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#56 /home4/broadsp9/firefly-iii/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): FireflyIII\\Http\\Middleware\\Sandstorm->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#57 /home4/broadsp9/firefly-iii/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#58 /home4/broadsp9/firefly-iii/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(104): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#59 /home4/broadsp9/firefly-iii/vendor/laravel/framework/src/Illuminate/Routing/Router.php(681): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#60 /home4/broadsp9/firefly-iii/vendor/laravel/framework/src/Illuminate/Routing/Router.php(656): Illuminate\\Routing\\Router->runRouteWithinStack(Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request))
#61 /home4/broadsp9/firefly-iii/vendor/laravel/framework/src/Illuminate/Routing/Router.php(622): Illuminate\\Routing\\Router->runRoute(Object(Illuminate\\Http\\Request), Object(Illuminate\\Routing\\Route))
#62 /home4/broadsp9/firefly-iii/vendor/laravel/framework/src/Illuminate/Routing/Router.php(611): Illuminate\\Routing\\Router->dispatchToRoute(Object(Illuminate\\Http\\Request))
#63 /home4/broadsp9/firefly-iii/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(176): Illuminate\\Routing\\Router->dispatch(Object(Illuminate\\Http\\Request))
#64 /home4/broadsp9/firefly-iii/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}(Object(Illuminate\\Http\\Request))
#65 /home4/broadsp9/firefly-iii/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#66 /home4/broadsp9/firefly-iii/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Fideloper\\Proxy\\TrustProxies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#67 /home4/broadsp9/firefly-iii/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#68 /home4/broadsp9/firefly-iii/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(31): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#69 /home4/broadsp9/firefly-iii/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#70 /home4/broadsp9/firefly-iii/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#71 /home4/broadsp9/firefly-iii/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(31): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#72 /home4/broadsp9/firefly-iii/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#73 /home4/broadsp9/firefly-iii/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#74 /home4/broadsp9/firefly-iii/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#75 /home4/broadsp9/firefly-iii/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#76 /home4/broadsp9/firefly-iii/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#77 /home4/broadsp9/firefly-iii/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(62): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#78 /home4/broadsp9/firefly-iii/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#79 /home4/broadsp9/firefly-iii/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#80 /home4/broadsp9/firefly-iii/app/Http/Middleware/SecureHeaders.php(46): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#81 /home4/broadsp9/firefly-iii/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): FireflyIII\\Http\\Middleware\\SecureHeaders->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#82 /home4/broadsp9/firefly-iii/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#83 /home4/broadsp9/firefly-iii/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(104): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#84 /home4/broadsp9/firefly-iii/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(151): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#85 /home4/broadsp9/firefly-iii/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(116): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#86 /home4/broadsp9/firefly-iii/public/index.php(76): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#87 {main}
"} 
```

**Comment by spirituallyinsane** [comment]
Well, I feel a little ridiculous now.  The users table does exist just fine.  I guess it just wasn't displaying because in phpMyAdmin there were so many tables?  I filtered for it, and lo and behold it is there.

![image](https://user-images.githubusercontent.com/14048499/47252974-16693800-d41b-11e8-8b7b-f5464e9fe78f.png)

**Comment by spirituallyinsane** [comment]
Just for resolution's sake, I deleted the orphaned recurrence from the database after making a backup, and the cron jobs fire successfully after that.  I'm not sure what to blame for the orphaned recurrence, but if it would be helpful to look through a database backup, I can send one over to you.

**Comment by JC5** [comment]
That's OK. I wonder what the deal is with the foreign keys not getting deleted but that's not something I can tell from a DB backup.

Glad to hear it works!
