### ISSUE TITLE
Problems after upgrade

### ISSUE THREAD

**Issue by erdelyijanos** [firefly-iii/firefly-iii#1849]
I am running Firefly III version 4.7.8

I upgraded the installation.
After that I cannot create transactions. There is only a "be right back" page.
All other pages are working, only new withdrawal, new deposit, new transfer are not.
I have the following in the log:

[2018-11-01 22:29:58] local.ERROR: Driver [mirror] is not supported. {"userId":1,"email":"erdelyi4@protonmail.ch","exception":"[object] (InvalidArgumentException(code: 0): Driver [mirror] is not supported. at /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Filesystem/FilesystemManager.php:127)
[stacktrace]
#0 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Filesystem/FilesystemManager.php(103): Illuminate\\Filesystem\\FilesystemManager->resolve('upload')
#1 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Filesystem/FilesystemManager.php(80): Illuminate\\Filesystem\\FilesystemManager->get('upload')
#2 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(221): Illuminate\\Filesystem\\FilesystemManager->disk('upload')
#3 /var/www/firefly-iii/app/Helpers/Attachments/AttachmentHelper.php(66): Illuminate\\Support\\Facades\\Facade::__callStatic('disk', Array)
#4 [internal function]: FireflyIII\\Helpers\\Attachments\\AttachmentHelper->__construct()
#5 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Container/Container.php(800): ReflectionClass->newInstanceArgs(Array)
#6 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Container/Container.php(646): Illuminate\\Container\\Container->build('FireflyIII\\\\Help...')
#7 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Container/Container.php(601): Illuminate\\Container\\Container->resolve('FireflyIII\\\\Help...', Array)
#8 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(734): Illuminate\\Container\\Container->make('FireflyIII\\\\Help...', Array)
#9 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Container/Container.php(256): Illuminate\\Foundation\\Application->make('FireflyIII\\\\Help...', Array)
#10 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Container/Container.php(764): Illuminate\\Container\\Container->Illuminate\\Container\\{closure}(Object(Illuminate\\Foundation\\Application), Array)...

What did I wrong?

Thanks
Janos

**Comment by JC5** [comment]
Run `composer install --no-dev` to also update the dependencies.

**Comment by erdelyijanos** [comment]
Thanks that was it.
Would it be possible to update the upgrade instructions with this information?
