### ISSUE TITLE
YNAB Import gives error: Job could not be started or crashed: The import routine crashed: Cannot find Firefly III asset account with ID #0. Job must stop now.

### ISSUE THREAD

**Issue by timoerlemans** [firefly-iii/firefly-iii#1989]
I am running Firefly III version 4.7.9

**Description**
I'm trying to import You Need A Budget into Firefly III. I did all the necessary work (secret ID etc.) and I'm able to select a budget (I have 2 budgets in YNAB) and I can assign my YNAB accounts to my Firefly III accounts. After this, it starts importing (and it does import some things like expenses and revenue accounts. But after a few seconds, it stops and gives this error: 
> YNAB Import gives error: Job could not be started or crashed: The import routine crashed: Cannot find Firefly III asset account with ID #0. Job must stop now.

Tried it with other budget and different assigned accounts (also removed the first bank account I created and made a new one), but nothing seems to fix it...

**Steps to reproduce** 
See above (if possible)

**Extra info**
Please add extra info here, such as OS, browser, and the output from the `/debug`-page of your Firefly III installation (click the version at the bottom). 

I run the app on a (free) Heroku instance.

/debug info:
```Debug information generated at 2019-01-08 17:22:25 UTC for Firefly III version **4.7.9**.

| Variable | Content |
| --- | --- |
| FF version | 4.7.9 |
| FF API version | 0.9.0 |
| App environment | heroku |
| App debug mode | false |
| App cache driver | file |
| App logging | , stdout |
| PHP version | 7.3.0 |
| Display errors | Off |
| Session start | 2019-01-01 00:00:00 |
| Session end | 2019-01-31 23:59:59 |
| Session first | 2018-05-14 00:00:00 |
| Error reporting | ALL errors |
| Host | Linux |
| Interface | fpm-fcgi |
| UserID | 1 |
| Attempt at "en" | 'en' |
| Attempt at "English" | false |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| DB drivers | mysql, pgsql |
| Current driver | pgsql |
| Login provider |   |
| Storage disks | local-upload  |
| Using Sandstorm? | no |
| Is Sandstorm (.env) | false |
| Is Docker (.env) | false |
| bunq uses sandbox | false |
| Trusted proxies (.env) | ** |
| User agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36 |
| Loaded extensions | Core, date, libxml, openssl, pcre, zlib, bz2, ctype, curl, dom, fileinfo, filter, hash, iconv, json, SPL, PDO, session, pdo_pgsql, pgsql, standard, posix, readline, Reflection, Phar, SimpleXML, sockets, mysqlnd, mysqli, tokenizer, xml, xmlreader, xmlwriter, zip, pdo_mysql, cgi-fcgi, bcmath, gd, intl, ldap, mbstring, Zend OPcache |
``` 

Log with error and stack trace:

```
2019-01-08T17:13:42.610161+00:00 app[web.1]: [2019-01-08 17:13:42] heroku.DEBUG: Will search for account of type "Expense account" using findByAccountNumber() and argument "e986aec9-2104-4ffe-b6d9-1a633f3f9124".  
2019-01-08T17:13:42.613193+00:00 app[web.1]: [2019-01-08 17:13:42] heroku.DEBUG: Found result: Account #132, named "bol.com"  
2019-01-08T17:13:42.613290+00:00 app[web.1]: [2019-01-08 17:13:42] heroku.DEBUG: Final source account: #83 ("Bankrekening Tim")  
2019-01-08T17:13:42.613383+00:00 app[web.1]: [2019-01-08 17:13:42] heroku.DEBUG: Final destination account: #132 ("bol.com")  
2019-01-08T17:13:42.613459+00:00 app[web.1]: [2019-01-08 17:13:42] heroku.DEBUG: Done with entry #117  
2019-01-08T17:13:42.616823+00:00 app[web.1]: [2019-01-08 17:13:42] heroku.ERROR: The import routine crashed: Cannot find Firefly III asset account with ID #0. Job must stop now.  
2019-01-08T17:13:42.617025+00:00 app[web.1]: [2019-01-08 17:13:42] heroku.ERROR: #0 /app/app/Support/Import/Routine/Ynab/ImportDataHandler.php(74): FireflyIII\Support\Import\Routine\Ynab\ImportDataHandler->getLocalAccount(0)
2019-01-08T17:13:42.617174+00:00 app[web.1]: #1 /app/app/Import/Routine/YnabRoutine.php(119): FireflyIII\Support\Import\Routine\Ynab\ImportDataHandler->run()
2019-01-08T17:13:42.617303+00:00 app[web.1]: #2 /app/app/Http/Controllers/Import/JobStatusController.php(171): FireflyIII\Import\Routine\YnabRoutine->run()
2019-01-08T17:13:42.617436+00:00 app[web.1]: #3 [internal function]: FireflyIII\Http\Controllers\Import\JobStatusController->start(Object(FireflyIII\Models\ImportJob))
2019-01-08T17:13:42.617559+00:00 app[web.1]: #4 /app/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): call_user_func_array(Array, Array)
2019-01-08T17:13:42.617730+00:00 app[web.1]: #5 /app/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\Routing\Controller->callAction('start', Array)
2019-01-08T17:13:42.618001+00:00 app[web.1]: #6 /app/vendor/laravel/framework/src/Illuminate/Routing/Route.php(212): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(FireflyIII\Http\Controllers\Import\JobStatusController), 'start')
2019-01-08T17:13:42.618143+00:00 app[web.1]: #7 /app/vendor/laravel/framework/src/Illuminate/Routing/Route.php(169): Illuminate\Routing\Route->runController()
2019-01-08T17:13:42.618247+00:00 app[web.1]: #8 /app/vendor/laravel/framework/src/Illuminate/Routing/Router.php(682): Illuminate\Routing\Route->run()
2019-01-08T17:13:42.618422+00:00 app[web.1]: #9 /app/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
2019-01-08T17:13:42.618616+00:00 app[web.1]: #10 /app/app/Http/Controllers/Import/JobStatusController.php(59): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
2019-01-08T17:13:42.618881+00:00 app[web.1]: #11 /app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(133): FireflyIII\Http\Controllers\Import\JobStatusController->FireflyIII\Http\Controllers\Import\{closure}(Object(Illuminate\Http\Request), Object(Closure))
2019-01-08T17:13:42.619073+00:00 app[web.1]: #12 /app/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
2019-01-08T17:13:42.619238+00:00 app[web.1]: #13 /app/app/Http/Controllers/Controller.php(88): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
2019-01-08T17:13:42.619469+00:00 app[web.1]: #14 /app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(133): FireflyIII\Http\Controllers\Controller->FireflyIII\Http\Controllers\{closure}(Object(Illuminate\Http\Request), Object(Closure))
2019-01-08T17:13:42.619656+00:00 app[web.1]: #15 /app/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
2019-01-08T17:13:42.619811+00:00 app[web.1]: #16 /app/app/Http/Middleware/Binder.php(78): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
2019-01-08T17:13:42.619991+00:00 app[web.1]: #17 /app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): FireflyIII\Http\Middleware\Binder->handle(Object(Illuminate\Http\Request), Object(Closure))
2019-01-08T17:13:42.620174+00:00 app[web.1]: #18 /app/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
2019-01-08T17:13:42.620356+00:00 app[web.1]: #19 /app/app/Http/Middleware/Range.php(60): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
2019-01-08T17:13:42.620546+00:00 app[web.1]: #20 /app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): FireflyIII\Http\Middleware\Range->handle(Object(Illuminate\Http\Request), Object(Closure))
2019-01-08T17:13:42.620737+00:00 app[web.1]: #21 /app/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
2019-01-08T17:13:42.620909+00:00 app[web.1]: #22 /app/app/Http/Middleware/AuthenticateTwoFactor.php(86): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
2019-01-08T17:13:42.621135+00:00 app[web.1]: #23 /app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): FireflyIII\Http\Middleware\AuthenticateTwoFactor->handle(Object(Illuminate\Http\Request), Object(Closure))
2019-01-08T17:13:42.621327+00:00 app[web.1]: #24 /app/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
2019-01-08T17:13:42.621492+00:00 app[web.1]: #25 /app/app/Http/Middleware/Authenticate.php(73): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
2019-01-08T17:13:42.621691+00:00 app[web.1]: #26 /app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): FireflyIII\Http\Middleware\Authenticate->handle(Object(Illuminate\Http\Request), Object(Closure))
2019-01-08T17:13:42.621885+00:00 app[web.1]: #27 /app/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
2019-01-08T17:13:42.622082+00:00 app[web.1]: #28 /app/vendor/laravel/passport/src/Http/Middleware/CreateFreshApiToken.php(50): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
2019-01-08T17:13:42.622295+00:00 app[web.1]: #29 /app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Laravel\Passport\Http\Middleware\CreateFreshApiToken->handle(Object(Illuminate\Http\Request), Object(Closure))
2019-01-08T17:13:42.622502+00:00 app[web.1]: #30 /app/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
2019-01-08T17:13:42.622738+00:00 app[web.1]: #31 /app/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(75): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
2019-01-08T17:13:42.622988+00:00 app[web.1]: #32 /app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\Foundation\Http\Middleware\VerifyCsrfToken->handle(Object(Illuminate\Http\Request), Object(Closure))
2019-01-08T17:13:42.623165+00:00 app[web.1]: #33 /app/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
2019-01-08T17:13:42.623367+00:00 app[web.1]: #34 /app/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
2019-01-08T17:13:42.623572+00:00 app[web.1]: #35 /app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
2019-01-08T17:13:42.623757+00:00 app[web.1]: #36 /app/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
2019-01-08T17:13:42.623955+00:00 app[web.1]: #37 /app/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(63): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
2019-01-08T17:13:42.624150+00:00 app[web.1]: #38 /app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
2019-01-08T17:13:42.624382+00:00 app[web.1]: #39 /app/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
2019-01-08T17:13:42.624600+00:00 app[web.1]: #40 /app/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
2019-01-08T17:13:42.624811+00:00 app[web.1]: #41 /app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure))
2019-01-08T17:13:42.625012+00:00 app[web.1]: #42 /app/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
2019-01-08T17:13:42.625211+00:00 app[web.1]: #43 /app/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(66): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
2019-01-08T17:13:42.625407+00:00 app[web.1]: #44 /app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
2019-01-08T17:13:42.625615+00:00 app[web.1]: #45 /app/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
2019-01-08T17:13:42.625770+00:00 app[web.1]: #46 /app/app/Http/Middleware/Sandstorm.php(54): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
2019-01-08T17:13:42.625958+00:00 app[web.1]: #47 /app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): FireflyIII\Http\Middleware\Sandstorm->handle(Object(Illuminate\Http\Request), Object(Closure))
2019-01-08T17:13:42.626142+00:00 app[web.1]: #48 /app/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
2019-01-08T17:13:42.626325+00:00 app[web.1]: #49 /app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(104): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
2019-01-08T17:13:42.626463+00:00 app[web.1]: #50 /app/vendor/laravel/framework/src/Illuminate/Routing/Router.php(684): Illuminate\Pipeline\Pipeline->then(Object(Closure))
2019-01-08T17:13:42.626671+00:00 app[web.1]: #51 /app/vendor/laravel/framework/src/Illuminate/Routing/Router.php(659): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
2019-01-08T17:13:42.626876+00:00 app[web.1]: #52 /app/vendor/laravel/framework/src/Illuminate/Routing/Router.php(625): Illuminate\Routing\Router->runRoute(Object(Illuminate\Http\Request), Object(Illuminate\Routing\Route))
2019-01-08T17:13:42.627039+00:00 app[web.1]: #53 /app/vendor/laravel/framework/src/Illuminate/Routing/Router.php(614): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
2019-01-08T17:13:42.627211+00:00 app[web.1]: #54 /app/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(176): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
2019-01-08T17:13:42.627422+00:00 app[web.1]: #55 /app/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
2019-01-08T17:13:42.627582+00:00 app[web.1]: #56 /app/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
2019-01-08T17:13:42.627761+00:00 app[web.1]: #57 /app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Fideloper\Proxy\TrustProxies->handle(Object(Illuminate\Http\Request), Object(Closure))
2019-01-08T17:13:42.627948+00:00 app[web.1]: #58 /app/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
2019-01-08T17:13:42.628161+00:00 app[web.1]: #59 /app/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(31): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
2019-01-08T17:13:42.628403+00:00 app[web.1]: #60 /app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle(Object(Illuminate\Http\Request), Object(Closure))
2019-01-08T17:13:42.628589+00:00 app[web.1]: #61 /app/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
2019-01-08T17:13:42.628804+00:00 app[web.1]: #62 /app/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(31): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
2019-01-08T17:13:42.629011+00:00 app[web.1]: #63 /app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle(Object(Illuminate\Http\Request), Object(Closure))
2019-01-08T17:13:42.629194+00:00 app[web.1]: #64 /app/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
2019-01-08T17:13:42.629426+00:00 app[web.1]: #65 /app/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
2019-01-08T17:13:42.629665+00:00 app[web.1]: #66 /app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\Foundation\Http\Middleware\ValidatePostSize->handle(Object(Illuminate\Http\Request), Object(Closure))
2019-01-08T17:13:42.629852+00:00 app[web.1]: #67 /app/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
2019-01-08T17:13:42.630072+00:00 app[web.1]: #68 /app/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(62): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
2019-01-08T17:13:42.630287+00:00 app[web.1]: #69 /app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
2019-01-08T17:13:42.630471+00:00 app[web.1]: #70 /app/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
2019-01-08T17:13:42.630628+00:00 app[web.1]: #71 /app/app/Http/Middleware/SecureHeaders.php(45): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
2019-01-08T17:13:42.630820+00:00 app[web.1]: #72 /app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): FireflyIII\Http\Middleware\SecureHeaders->handle(Object(Illuminate\Http\Request), Object(Closure))
2019-01-08T17:13:42.631014+00:00 app[web.1]: #73 /app/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
2019-01-08T17:13:42.631211+00:00 app[web.1]: #74 /app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(104): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
2019-01-08T17:13:42.631355+00:00 app[web.1]: #75 /app/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(151): Illuminate\Pipeline\Pipeline->then(Object(Closure))
2019-01-08T17:13:42.631545+00:00 app[web.1]: #76 /app/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(116): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
2019-01-08T17:13:42.631672+00:00 app[web.1]: #77 /app/public/index.php(76): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
2019-01-08T17:13:42.631693+00:00 app[web.1]: #78 {main}  
2019-01-08T17:13:42.631786+00:00 app[web.1]: [2019-01-08 17:13:42] heroku.DEBUG: Set status of job "Cg9AdKNOD9pA" to "error"  
```

**Comment by JC5** [comment]
Strange. I can't really imagine why the job would fail. Can you access your database?

**Comment by timoerlemans** [comment]
Yes, I can.

**Comment by timoerlemans** [comment]
Here is the field configuration (the JSON is valid according to jsonlint):

```
{
  "access_token": "hidden",
  "access_token_expires": 1546974658,
  "budgets": [
    { "id": "57d46822-dd62-4fdb-bbeb-488af99614a7", "name": "hidden", "currency_code": "EUR" },
    { "id": "f104fe2a-20c2-4deb-92af-b9248169cbee", "name": "hidden", "currency_code": "EUR" }
  ],
  "selected_budget": "f104fe2a-20c2-4deb-92af-b9248169cbee",
  "accounts": [
    {
      "id": "ee992a8e-714a-4a46-b4ff-014b12902141",
      "name": "hidden",
      "type": "checking",
      "on_budget": true,
      "closed": false,
      "note": null,
      "balance": 0,
      "cleared_balance": 0,
      "uncleared_balance": 0,
      "transfer_payee_id": "d8662a6e-f196-4d70-a26c-04f51ff9c217",
      "deleted": false
    },
    {
      "id": "756c8c70-6560-467e-b521-0fb296cfb51d",
      "name": "hidden",
      "type": "savings",
      "on_budget": true,
      "closed": false,
      "note": null,
      "balance": 0,
      "cleared_balance": 0,
      "uncleared_balance": 0,
      "transfer_payee_id": "4be9c4bf-2c9f-4b35-b5c8-d297356be2ba",
      "deleted": false
    },
    {
      "id": "8f346973-3a19-43b5-972c-20615ec304fe",
      "name": "hidden",
      "type": "otherLiability",
      "on_budget": false,
      "closed": false,
      "note": null,
      "balance": 0,
      "cleared_balance": 0,
      "uncleared_balance": 0,
      "transfer_payee_id": "f09dc1c2-f9e2-4624-99e6-f2cb6d773698",
      "deleted": false
    },
    {
      "id": "92dfc386-f961-4dfe-a6ef-7fd81aab13a6",
      "name": "hidden",
      "type": "savings",
      "on_budget": true,
      "closed": false,
      "note": null,
      "balance": 0,
      "cleared_balance": 0,
      "uncleared_balance": 0,
      "transfer_payee_id": "22011ca1-4254-4998-b4a8-867f34f4d152",
      "deleted": false
    }
  ],
  "mapping": {
    "ee992a8e-714a-4a46-b4ff-014b12902141": 78,
    "756c8c70-6560-467e-b521-0fb296cfb51d": 0,
    "8f346973-3a19-43b5-972c-20615ec304fe": 0,
    "92dfc386-f961-4dfe-a6ef-7fd81aab13a6": 0
  },
  "apply-rules": true
}
```

**Comment by JC5** [comment]
I think I found the issue, but I can't confirm it. I assume you have four accounts at YNAB, and linked only one to Firefly III? So only for one account, you selected an asset account to import into?

**Comment by timoerlemans** [comment]
In this case I did, yes. But it doesn't matter if I link the other ones as well, I still get the same error.
(Except for the otherLiability one, because that's not an account but a Liability)

**Comment by JC5** [comment]
Is the number also 0 3x for the configuration of those new import jobs?

**Comment by timoerlemans** [comment]
Sorry, should have mentioned that I changed those numbers to 0 for privacy reasons.

**Comment by JC5** [comment]
Alright, so in this part specifically:
```
  "mapping": {
    "ee992a8e-714a-4a46-b4ff-014b12902141": x,
    "756c8c70-6560-467e-b521-0fb296cfb51d": x,
    "8f346973-3a19-43b5-972c-20615ec304fe": x,
    "92dfc386-f961-4dfe-a6ef-7fd81aab13a6": x
  },
```

The `x`'s are in fact filled with numbers, and these numbers are not 0?

**Comment by furgoose** [comment]
I had this issue and found that it would error unless I assigned an account for everything to be imported into (do not import didn't work)

**Comment by JC5** [comment]
Thanks for the feedback. I'll check it out!
