### ISSUE TITLE
500 server error after upgrade in docker

### ISSUE THREAD

**Issue by agilob** [firefly-iii/firefly-iii#2076]
**Bug description**
```
1b6fc4cf30f6        jc5x/firefly-iii:latest    ".deploy/docker/entr…"   3 hours ago         Up 2 hours          0.0.0.0:8777->80/tcp   firefly_iii_app
```

```
[2019-02-11 19:22:00] local.ERROR: Unable to create the cache directory (/var/www/firefly-iii/storage/framework/views/twig/a3). {"exception":"[object] (RuntimeException(code: 0): Unable to create the cache directory (/var/www/firefly-iii/storage/framework/views/twig/a3). at /var/www/firefly-iii/vendor/twig/twig/lib/Twig/Cache/Filesystem.php:55)
[stacktrace]
#0 /var/www/firefly-iii/vendor/twig/twig/lib/Twig/Environment.php(457): Twig_Cache_Filesystem->write('/var/www/firefl...', '<?php\
\
/* /var/...')
#1 /var/www/firefly-iii/vendor/rcrowe/twigbridge/src/Bridge.php(75): Twig_Environment->loadTemplate('/var/www/firefl...', NULL)
#2 /var/www/firefly-iii/vendor/rcrowe/twigbridge/src/Engine/Compiler.php(99): TwigBridge\\Bridge->loadTemplate('/var/www/firefl...')
#3 /var/www/firefly-iii/vendor/rcrowe/twigbridge/src/Engine/Twig.php(91): TwigBridge\\Engine\\Compiler->load('/var/www/firefl...')
#4 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/View/View.php(142): TwigBridge\\Engine\\Twig->get('/var/www/firefl...', Array)
#5 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/View/View.php(125): Illuminate\\View\\View->getContents()
#6 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/View/View.php(90): Illuminate\\View\\View->renderContents()
#7 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Http/Response.php(42): Illuminate\\View\\View->render()
#8 /var/www/firefly-iii/vendor/symfony/http-foundation/Response.php(202): Illuminate\\Http\\Response->setContent(Object(Illuminate\\View\\View))
#9 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Routing/ResponseFactory.php(55): Symfony\\Component\\HttpFoundation\\Response->__construct(Object(Illuminate\\View\\View), 500, Array)
#10 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Routing/ResponseFactory.php(81): Illuminate\\Routing\\ResponseFactory->make(Object(Illuminate\\View\\View), 500, Array)
#11 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(380): Illuminate\\Routing\\ResponseFactory->view('errors::500', Array, 500, Array)
#12 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(289): Illuminate\\Foundation\\Exceptions\\Handler->renderHttpException(Object(Symfony\\Component\\HttpKernel\\Exception\\HttpException))
#13 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(188): Illuminate\\Foundation\\Exceptions\\Handler->prepareResponse(Object(Illuminate\\Http\\Request), Object(Symfony\\Component\\HttpKernel\\Exception\\HttpException))
#14 /var/www/firefly-iii/app/Exceptions/Handler.php(101): Illuminate\\Foundation\\Exceptions\\Handler->render(Object(Illuminate\\Http\\Request), Object(RuntimeException))
#15 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(326): FireflyIII\\Exceptions\\Handler->render(Object(Illuminate\\Http\\Request), Object(RuntimeException))
#16 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(120): Illuminate\\Foundation\\Http\\Kernel->renderException(Object(Illuminate\\Http\\Request), Object(RuntimeException))
#17 /var/www/firefly-iii/public/index.php(76): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#18 {main}
"} 
[2019-02-11 19:22:00] local.ERROR: Uncaught RuntimeException: Unable to create the cache directory (/var/www/firefly-iii/storage/framework/views/twig/a3). in /var/www/firefly-iii/vendor/twig/twig/lib/Twig/Cache/Filesystem.php:55
Stack trace:
#0 /var/www/firefly-iii/vendor/twig/twig/lib/Twig/Environment.php(457): Twig_Cache_Filesystem->write('/var/www/firefl...', '<?php\n\n/* /var/...')
#1 /var/www/firefly-iii/vendor/rcrowe/twigbridge/src/Bridge.php(75): Twig_Environment->loadTemplate('/var/www/firefl...', NULL)
#2 /var/www/firefly-iii/vendor/rcrowe/twigbridge/src/Engine/Compiler.php(99): TwigBridge\Bridge->loadTemplate('/var/www/firefl...')
#3 /var/www/firefly-iii/vendor/rcrowe/twigbridge/src/Engine/Twig.php(91): TwigBridge\Engine\Compiler->load('/var/www/firefl...')
#4 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/View/View.php(142): TwigBridge\Engine\Twig->get('/var/www/firefl...', Array)
#5 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/View/View.php(125): Illuminate\View\View->getContents()
#6 /var/www/firefly- {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalErrorException(code: 1): Uncaught RuntimeException: Unable to create the cache directory (/var/www/firefly-iii/storage/framework/views/twig/a3). in /var/www/firefly-iii/vendor/twig/twig/lib/Twig/Cache/Filesystem.php:55
Stack trace:
#0 /var/www/firefly-iii/vendor/twig/twig/lib/Twig/Environment.php(457): Twig_Cache_Filesystem->write('/var/www/firefl...', '<?php\
\
/* /var/...')
#1 /var/www/firefly-iii/vendor/rcrowe/twigbridge/src/Bridge.php(75): Twig_Environment->loadTemplate('/var/www/firefl...', NULL)
#2 /var/www/firefly-iii/vendor/rcrowe/twigbridge/src/Engine/Compiler.php(99): TwigBridge\\Bridge->loadTemplate('/var/www/firefl...')
#3 /var/www/firefly-iii/vendor/rcrowe/twigbridge/src/Engine/Twig.php(91): TwigBridge\\Engine\\Compiler->load('/var/www/firefl...')
#4 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/View/View.php(142): TwigBridge\\Engine\\Twig->get('/var/www/firefl...', Array)
#5 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/View/View.php(125): Illuminate\\View\\View->getContents()
#6 /var/www/firefly- at /var/www/firefly-iii/vendor/twig/twig/lib/Twig/Cache/Filesystem.php:55)
[stacktrace]
#0 {main}
"} 
172.17.0.1 - - [11/Feb/2019:19:22:00 +0000] "GET / HTTP/1.1" 500 211 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:65.0) Gecko/20100101 Firefox/65.0"

````

**Comment by JC5** [comment]
I need a little more than a log dump.

**Comment by agilob** [comment]
what do you need?

**Comment by agilob** [comment]
There's really nothing more. A few weeks ago I installed firefly in docker using the way described in docs. It was updated today and can't visit it
![screenshot_20190211_193921](https://user-images.githubusercontent.com/2544251/52588643-d9dfa300-2e34-11e9-8aaf-4cbe62f9fe3d.png)

**Comment by JC5** [comment]
Have you tried recreating the image, or restarting it?

**Comment by agilob** [comment]
I tried restarting, will recreate in few mins

**Comment by agilob** [comment]
still the same

**Comment by JC5** [comment]
Ok. I have no idea and I’ll do some research later.

**Comment by agilob** [comment]
is there anything I can do in meantime to get it working?

**Comment by JC5** [comment]
Sorry. I don’t know what’s causing this and so far you’re the only one. I have very little to go on.

**Comment by SvenDub** [comment]
I had the same issue with exactly the same error message. Found that `/var/storage` (which is symlinked to by `/var/www/firefly-iii/storage` is not writable by `www-data`. Fixed it by executing `chown -R www-data:www-data /var/storage`. This sets www-data as the owner for the whole directory, not sure if that is required but it works for me.

**Comment by agilob** [comment]
Thanks, that's better, now I'm getting message "be right back" with stacktrace:


```
[2019-02-11 21:20:17] local.ERROR: Trailing data {"userId":1,"email":"firefly@agilob.net","exception":"[object] (InvalidArgumentException(code: 0): Trailing data at /var/www/firefly-iii/vendor/nesbot/carbon/src/Carbon/Carbon.php:910)
[stacktrace]
#0 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Concerns/HasAttributes.php(797): Carbon\\Carbon::createFromFormat('Y-m-d H:i:s', '2019-02-02 00:0...')
#1 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Concerns/HasAttributes.php(500): Illuminate\\Database\\Eloquent\\Model->asDateTime('2019-02-02 00:0...')
#2 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Concerns/HasAttributes.php(351): Illuminate\\Database\\Eloquent\\Model->castAttribute('date', '2019-02-02 00:0...')
#3 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Concerns/HasAttributes.php(317): Illuminate\\Database\\Eloquent\\Model->getAttributeValue('date')
#4 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1538): Illuminate\\Database\\Eloquent\\Model->getAttribute('date')
#5 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1583): Illuminate\\Database\\Eloquent\\Model->offsetExists('date')
#6 /var/www/firefly-iii/app/Http/Middleware/Range.php(142): Illuminate\\Database\\Eloquent\\Model->__isset('date')
#7 /var/www/firefly-iii/app/Http/Middleware/Range.php(48): FireflyIII\\Http\\Middleware\\Range->setRange()
#8 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): FireflyIII\\Http\\Middleware\\Range->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#9 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#10 /var/www/firefly-iii/app/Http/Middleware/AuthenticateTwoFactor.php(86): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#11 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): FireflyIII\\Http\\Middleware\\AuthenticateTwoFactor->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#12 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#13 /var/www/firefly-iii/app/Http/Middleware/Authenticate.php(73): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#14 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): FireflyIII\\Http\\Middleware\\Authenticate->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#15 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#16 /var/www/firefly-iii/vendor/laravel/passport/src/Http/Middleware/CreateFreshApiToken.php(50): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#17 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Laravel\\Passport\\Http\\Middleware\\CreateFreshApiToken->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#18 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#19 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(75): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#20 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#21 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#22 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#23 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#24 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#25 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(63): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#26 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\Session\\Middleware\\StartSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#27 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#28 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#29 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#30 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#31 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(66): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#32 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#33 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#34 /var/www/firefly-iii/app/Http/Middleware/Sandstorm.php(54): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#35 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): FireflyIII\\Http\\Middleware\\Sandstorm->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#36 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#37 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(104): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#38 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Routing/Router.php(684): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#39 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Routing/Router.php(659): Illuminate\\Routing\\Router->runRouteWithinStack(Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request))
#40 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Routing/Router.php(625): Illuminate\\Routing\\Router->runRoute(Object(Illuminate\\Http\\Request), Object(Illuminate\\Routing\\Route))
#41 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Routing/Router.php(614): Illuminate\\Routing\\Router->dispatchToRoute(Object(Illuminate\\Http\\Request))
#42 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(176): Illuminate\\Routing\\Router->dispatch(Object(Illuminate\\Http\\Request))
#43 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}(Object(Illuminate\\Http\\Request))
#44 /var/www/firefly-iii/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#45 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Fideloper\\Proxy\\TrustProxies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#46 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#47 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(31): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#48 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#49 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#50 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(31): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#51 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#52 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#53 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#54 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#55 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#56 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(62): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#57 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#58 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#59 /var/www/firefly-iii/app/Http/Middleware/SecureHeaders.php(45): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#60 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): FireflyIII\\Http\\Middleware\\SecureHeaders->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#61 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#62 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(104): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#63 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(151): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#64 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(116): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#65 /var/www/firefly-iii/public/index.php(76): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#66 {main}
"
```

I'll comeback to this tomorrow.

**Comment by wpuckering** [comment]
Came to chime in that I'm experiencing the exact same problem as described above. Definitely an issue with the latest Docker image.

**Comment by krispek** [comment]
Here's another one, due to an update of the docker image today. Fixed it with `chown -R www-data:www-data /var/storage` as well.

**Comment by JC5** [comment]
Thanks guys. It’s weird. That same command is in entrypoint.sh. I’ll check it out.

Regarding the trailing data. Are you using Postgres by any chance?

**Comment by krispek** [comment]
Nope, I'm using MySQL (8.0.15). :)

**Comment by downforce** [comment]
I had the same problem and created my own image by adding the following line:
```RUN chown -R www-data:www-data /var/www && \
    **chown -R www-data:www-data $FIREFLY_PATH/storage && \**```

In terms of entrypoint.sh, it seems to have -R duplicated, but that shouldn't stop it working.
```chown -R www-data:www-data -R $FIREFLY_PATH/storage```

**Comment by JC5** [comment]
I think I know what happened. The master build failed on Github so I built it myself. Some directories were already present. Usually, docker doesn’t create those until entrypoint.sh. 

I can’t fix this in 4.7.11 but a new release this weekend shouldn’t suffer from this. Make sure you upgrade from 4.7.10 directly if possible.

**Comment by agilob** [comment]
I use postgresql as recommended

**Comment by evolsano** [comment]
I have the same problem as agilob. Fixing the permission doesn't help, and it show Be right back error.

`chown -R www-data:www-data /var/www && \
 chown -R www-data:www-data $FIREFLY_PATH/storage`

Any interim solution before JC5 fix it?

**Comment by agilob** [comment]
The error with "be right back" has been reported here https://github.com/firefly-iii/firefly-iii/issues/2071 and "fixed" in comments. I will give it a try later today.

>The master build failed on Github so I built it myself.

that means you built the docker image as different user, different UID and pushed that to docker repo, now depending on how we run firefly we might or might not get this issue. built system must be consistent or provide migration scripts. If you want to built the docker from your PC you should create a user with the same UID/username as `www-data` on github and run `docker build` as this user from your machine.

**Comment by wouterverduin** [comment]
Ran into the exact same issue. (docker-compose build)

Upgraded from 4.7.9 yesterday. Ran into the 500 error. Attempted to recreate everything because i thought i f*cked up. Even using the same docker-compose file as the one from github results in the same 500 error.  

Even pruned my docker considering i create the problem my self lol.
Attempted the chown www-date but says no such file or directory?

What is the best way to go? Wait fo new release?

**Comment by agilob** [comment]
@wouterverduin you need to exec command on your host `sudo docker exec -it firefly_iii_app /bin/bash` this will move you to docker instance bash where you execute the command. after running it you just type `exit` and go back to your host. this will leave you with "be right back" state, you have to downgrade firefly as described in 2071 I linked above

**Comment by wouterverduin** [comment]
@agilob Thanks!

Stopped attempting to fix it though. It isnt essential to get it running before the weekend so ill just await the new upgrade and try that one. To busy to manually fix thing if it will be easily resolved coming weekend :)

**Comment by Ryonez** [comment]
I'm kicking myself for not checking first for any issues...

I recommend pulling this update from docker hub. It's a confirmed issue and will stop others from updating to something broken.

Did get somewhat lucky, the shared database I'm setting up only has firefly on it currently.

**Comment by agilob** [comment]
@Ryonez never have shared databases

**Comment by Ryonez** [comment]
Why not?

**Comment by JC5** [comment]
I pushed new images (arm and amd64) to `jc5x/firefly-iii:develop`. I invite you to try to upgrade from 4.7.10 to that one, if you have the time (and are willing to try it).

I hope this fixes the issue!

**Comment by DracoMilesX** [comment]
Had the same issue and the develop docker tag solved the issue for me. Thanks

**Comment by wouterverduin** [comment]
@JC5  I Salute you! Just used the develop branch and worked like a charm with docker-compose like it did before!

My next beer is on you! :)

**Comment by downforce** [comment]
Awesome, just changed to :develop in my docker-compose and everything came good, no data loss.

Thanks!

**Comment by evolsano** [comment]
@JC5 kudos on the fix. It's back online again.

**Comment by NanneHuiges** [comment]
Hmm, I'm having the same "trailing data" error.

I've done a chown to all the storage directories, and as well to the complet /var/www direcotry: I suspected it was the vendor dir that was owned by root causing this, but after chmodding the stuff I still get the error.

The login-page works, and i get the 'be right back' only after loggin in.

I build my own images, as i'm running on raspberry. Is there something I need to do during build that's different?

**Comment by JC5** [comment]
Could you try it with jc5x/firefly-iii:develop? It should be compatible with your Raspberry.

**Comment by NanneHuiges** [comment]
sure!
I'm assuming I still need to build it myself, right?

**Comment by JC5** [comment]
No a pull should work just fine.

**Comment by NanneHuiges** [comment]
so basically write this down as meddling users I guess. I just removed all the wacky things I changed to get the stuff working on raspberry when that wasn't automatic.
I downloaded the develop docker file, i changed the image-definition to include `:develop` and now it works, 'old' database and all still perfect so cheers :D

Thanks for the help, I wasn't aware that it now works on raspberry out of the box, i'll just use that then!

**Comment by JC5** [comment]
No problem! It's pretty recent so you haven't missed a lot :)

**Comment by Ryonez** [comment]
Should I switch to `jc5x/firefly-iii:develop`, or wait for either 4.7.11 to be pulled?

I'm not sure what happening with that version as it's broken for everyone, right? Or do you plan to switch the develop in?

I've rolled back to 4.7.10 at the moment, so I'm just trying to figure what's happening currently.

**Comment by JC5** [comment]
I plan to release 4.7.12 this weekend. You can wait, or use develop in the mean time.

**Comment by Ryonez** [comment]
I'm happy to wait. Will jump from .10 to .12 when it's released, thank you.

**Comment by JC5** [comment]
4.7.12 has been released. Follow the status of the Docker build on [Travis CI](https://travis-ci.com/firefly-iii/firefly-iii/builds).
