### ISSUE TITLE
adldap configuration

### ISSUE THREAD

**Issue by farot** [firefly-iii/firefly-iii#2102]
I am running Firefly III version 4.7.12

**Description**
I Be right back.

**Extra info**
I do not use ldap

[19-Feb-2019 12:43:33] WARNING: [pool www] child 92 said into stdout: "[2019-02-19 12:43:33] local.ERROR: Option port must be an integer. {"exception"
:"[object] (Adldap\\Configuration\\ConfigurationException(code: 0): Option port must be an integer. at /var/www/firefly/vendor/adldap2/adldap2/src/Con
figuration/Validators/IntegerValidator.php:22)"
[19-Feb-2019 12:43:33] WARNING: [pool www] child 92 said into stdout: "[stacktrace]"
[19-Feb-2019 12:43:33] WARNING: [pool www] child 92 said into stdout: "#0 /var/www/firefly/vendor/adldap2/adldap2/src/Configuration/DomainConfiguratio
n.php(161): Adldap\\Configuration\\Validators\\IntegerValidator->validate()"
[19-Feb-2019 12:43:33] WARNING: [pool www] child 92 said into stdout: "#1 /var/www/firefly/vendor/adldap2/adldap2/src/Configuration/DomainConfiguratio
n.php(95): Adldap\\Configuration\\DomainConfiguration->validate('port', '')"
[19-Feb-2019 12:43:33] WARNING: [pool www] child 92 said into stdout: "#2 /var/www/firefly/vendor/adldap2/adldap2/src/Configuration/DomainConfiguratio
n.php(78): Adldap\\Configuration\\DomainConfiguration->set('port', '')"
[19-Feb-2019 12:43:33] WARNING: [pool www] child 92 said into stdout: "#3 /var/www/firefly/vendor/adldap2/adldap2/src/Connections/Provider.php(83): Ad
ldap\\Configuration\\DomainConfiguration->__construct(Array)"
[19-Feb-2019 12:43:33] WARNING: [pool www] child 92 said into stdout: "#4 /var/www/firefly/vendor/adldap2/adldap2/src/Connections/Provider.php(58): Ad
ldap\\Connections\\Provider->setConfiguration(Array)"

**Comment by JC5** [comment]
Make sure you download the latest version here. There has been a hotfix:

https://github.com/firefly-iii/firefly-iii/releases

**Comment by farot** [comment]
Actually I had not seen version 4.7.12.1
Thank you

**Comment by JC5** [comment]
No problem. I plan to push a new version this weekend that corrects that.
