### ISSUE TITLE
SQLSTATE[HY000] [2002] No route to host  

### ISSUE THREAD

**Issue by JamborJan** [firefly-iii/firefly-iii#2329]
I am running Firefly III version v4.7.17 on Docker based on [jc5x/firefly-iii:latest](https://hub.docker.com/r/jc5x/firefly-iii/tags).

**Description**
I have been using docker with the build in bridge networking mode. Thus to talk to each container I had to use the host address and the mapped port. This was also true for the mariadb container. Firefly-iii used to work with that just as expected.

Now I switched to a macvlan type of setup. It's not 100% pure standard docker macvlan as I'm, running the containers on a QNAP NAS and there a [3rd party driver called qnet](https://qnap-dev.github.io/container-station-api/qnet.html) is used which is set up just like macvlan, all containers get their own mac address and you must manually assign a valid IP address for it, which is just what I want and need.

I changed the `FF_DB_HOST` to reflect the new IP address of the mariadb container. The `FF_APP_ENV` is still set to `local` as I didn`t find any documentation stating other values.

All containers are just running fine. My mariadb container can be accessed from the phpmyadmin container I'm running and I can connect to the firefly-iii database with the user the application is using from phpmyadmin. so I guess the network setup is working. I can also connect from within the firefly-iii container when I temporary install the mysql client. **BUT** firefly-iii cannot connect to the database the log always shows stuff like this when I startup the container:

```
In Connection.php line 664:

  SQLSTATE[HY000] [2002] No route to host (SQL: insert into `oauth_clients` (  
  `user_id`, `name`, `secret`, `redirect`, `personal_access_client`, `passwor  
  d_client`, `revoked`, `updated_at`, `created_at`) values (, FireflyIII Pers  
  onal Access Client, blahblahblahblah, http://localh  
  ost, 1, 0, 0, 2019-07-04 20:25:27, 2019-07-04 20:25:27))                     

In PDOConnection.php line 31:

  SQLSTATE[HY000] [2002] No route to host  

In PDOConnection.php line 27:

  SQLSTATE[HY000] [2002] No route to host  

```

**Extra info**
 

As I cannot log into my instance due to this issue, I cannot add the output from /debug here. I guess pretty much all is said above concerning technical setup and dependencies. If not please let me know.

**Bonus points**
- I guess screenshots make no sense here
- Same for drawing, or maybe if you don't know what macvlan is:

![CB7420CB-A04D-41D1-A0F2-D5A1BCBBCA04](https://user-images.githubusercontent.com/7508960/60754989-9b1bd680-9fe9-11e9-863e-c4157f32af30.jpeg)
(taken from @nigelpoulton s [course "Docker Networking" on Pluralsight](https://www.pluralsight.com/courses/docker-networking), sorry for the subliminal advertising but Nigel is really a great guy and I've learned a lot about docker and related stuff from him.)

**Comment by JC5** [comment]
It's all pretty basic PHP, and the container is almost untouched. I'm not really sure what could go wrong.

**Comment by JamborJan** [comment]
Do you have any idea how I could do some further testing?

**Comment by JC5** [comment]
If the errors appear during launch but the container still launches, you could fire them off by hand. The commands don't need to fire every time the container launches anyway.

```
docker exec -it xxxxxx php artisan migrate --seed
docker exec -it xxxxxx php artisan firefly:decrypt-all
docker exec -it xxxxxx php artisan firefly:upgrade-database
docker exec -it xxxxxx php artisan firefly:verify
docker exec -it xxxxxx php artisan passport:install
docker exec -it xxxxxx php artisan cache:clear
docker exec -it xxxxxx php artisan firefly:instructions install

```

**Comment by JamborJan** [comment]
I started these commands one by one from within the container and all were okay. But anyway, when I start the container I get the same problem and I end up with a login prompt where I cannot login because there is no database connection. Detail here: I disabled logins at all so the prompt should not be there in the first place.

## results from the commands
(please find the startup log at the bottom)

```
root@fireflyiii:/var/www/firefly-iii# php artisan migrate --seed
**************************************
*     Application In Production!     *
**************************************

 Do you really wish to run this command? (yes/no) [no]:
 > yes

Nothing to migrate.
Seeding: AccountTypeSeeder
[2019-07-07 11:00:16] production.INFO: Could not create account type "Default account". It might exist already.
[2019-07-07 11:00:16] production.INFO: Could not create account type "Cash account". It might exist already.
[2019-07-07 11:00:16] production.INFO: Could not create account type "Asset account". It might exist already.
[2019-07-07 11:00:17] production.INFO: Could not create account type "Expense account". It might exist already.
[2019-07-07 11:00:17] production.INFO: Could not create account type "Revenue account". It might exist already.
[2019-07-07 11:00:17] production.INFO: Could not create account type "Initial balance account". It might exist already.
[2019-07-07 11:00:17] production.INFO: Could not create account type "Beneficiary account". It might exist already.
[2019-07-07 11:00:17] production.INFO: Could not create account type "Import account". It might exist already.
[2019-07-07 11:00:17] production.INFO: Could not create account type "Loan". It might exist already.
[2019-07-07 11:00:17] production.INFO: Could not create account type "Reconciliation account". It might exist already.
[2019-07-07 11:00:17] production.INFO: Could not create account type "Debt". It might exist already.
[2019-07-07 11:00:17] production.INFO: Could not create account type "Mortgage". It might exist already.
Seeding: TransactionCurrencySeeder
[2019-07-07 11:00:17] production.INFO: Could not create transaction currency "EUR". It might exist already.
[2019-07-07 11:00:17] production.INFO: Could not create transaction currency "HUF". It might exist already.
[2019-07-07 11:00:17] production.INFO: Could not create transaction currency "GBP". It might exist already.
[2019-07-07 11:00:18] production.INFO: Could not create transaction currency "UAH". It might exist already.
[2019-07-07 11:00:18] production.INFO: Could not create transaction currency "PLN". It might exist already.
[2019-07-07 11:00:18] production.INFO: Could not create transaction currency "TRY". It might exist already.
[2019-07-07 11:00:18] production.INFO: Could not create transaction currency "USD". It might exist already.
[2019-07-07 11:00:18] production.INFO: Could not create transaction currency "BRL". It might exist already.
[2019-07-07 11:00:18] production.INFO: Could not create transaction currency "CAD". It might exist already.
[2019-07-07 11:00:18] production.INFO: Could not create transaction currency "IDR". It might exist already.
[2019-07-07 11:00:18] production.INFO: Could not create transaction currency "AUD". It might exist already.
[2019-07-07 11:00:18] production.INFO: Could not create transaction currency "NZD". It might exist already.
[2019-07-07 11:00:18] production.INFO: Could not create transaction currency "EGP". It might exist already.
[2019-07-07 11:00:18] production.INFO: Could not create transaction currency "MAD". It might exist already.
[2019-07-07 11:00:18] production.INFO: Could not create transaction currency "ZAR". It might exist already.
[2019-07-07 11:00:18] production.INFO: Could not create transaction currency "JPY". It might exist already.
[2019-07-07 11:00:18] production.INFO: Could not create transaction currency "RMB". It might exist already.
[2019-07-07 11:00:18] production.INFO: Could not create transaction currency "RUB". It might exist already.
[2019-07-07 11:00:18] production.INFO: Could not create transaction currency "INR". It might exist already.
[2019-07-07 11:00:18] production.INFO: Could not create transaction currency "XBT". It might exist already.
[2019-07-07 11:00:18] production.INFO: Could not create transaction currency "BCH". It might exist already.
[2019-07-07 11:00:18] production.INFO: Could not create transaction currency "ETH". It might exist already.
[2019-07-07 11:00:18] production.INFO: Could not create transaction currency "ILS". It might exist already.
[2019-07-07 11:00:18] production.INFO: Could not create transaction currency "CHF". It might exist already.
[2019-07-07 11:00:19] production.INFO: Could not create transaction currency "HRK". It might exist already.
Seeding: TransactionTypeSeeder
[2019-07-07 11:00:19] production.INFO: Could not create transaction type "Withdrawal". It might exist already.
[2019-07-07 11:00:19] production.INFO: Could not create transaction type "Deposit". It might exist already.
[2019-07-07 11:00:19] production.INFO: Could not create transaction type "Transfer". It might exist already.
[2019-07-07 11:00:19] production.INFO: Could not create transaction type "Opening balance". It might exist already.
[2019-07-07 11:00:19] production.INFO: Could not create transaction type "Reconciliation". It might exist already.
Seeding: PermissionSeeder
[2019-07-07 11:00:19] production.INFO: Could not create role "Site Owner". It might exist already.
[2019-07-07 11:00:19] production.INFO: Could not create role "Demo User". It might exist already.
Seeding: LinkTypeSeeder
[2019-07-07 11:00:19] production.INFO: Could not create link type "Related". It might exist already.
[2019-07-07 11:00:19] production.INFO: Could not create link type "Refund". It might exist already.
[2019-07-07 11:00:19] production.INFO: Could not create link type "Paid". It might exist already.
[2019-07-07 11:00:19] production.INFO: Could not create link type "Reimbursement". It might exist already.
Seeding: ConfigSeeder
[2019-07-07 11:00:19] production.WARNING: Database entry exists. Update to latest version (10)
Database seeding completed successfully.
```

```
root@fireflyiii:/var/www/firefly-iii# php artisan firefly:decrypt-all
Going to decrypt the database.
No decryption required for table "accounts".
No decryption required for table "attachments".
No decryption required for table "bills".
No decryption required for table "budgets".
No decryption required for table "categories".
No decryption required for table "piggy_banks".
No decryption required for table "preferences".
No decryption required for table "tags".
No decryption required for table "transaction_journals".
No decryption required for table "transactions".
No decryption required for table "journal_links".
Done!
```

```
root@fireflyiii:/var/www/firefly-iii# php artisan firefly:upgrade-database
Updating currency information..
Done updating currency information..
Firefly III database is up to date.
```

```
root@fireflyiii:/var/www/firefly-iii# php artisan firefly:verify
Amount integrity OK for user #1
No orphaned transactions!
No orphaned journals!
All link types OK!
All access tokens OK!
Amount integrity OK!
```

```
root@fireflyiii:/var/www/firefly-iii# php artisan passport:install
Encryption keys already exist. Use the --force option to overwrite them.
[2019-07-07 11:04:08] production.INFO: OAuth client generated but no user associated.
Personal access client created successfully.
Client ID: 20
Client secret: xxxxxxxxxxxxxxxx
[2019-07-07 11:04:08] production.INFO: OAuth client generated but no user associated.
Password grant client created successfully.
Client ID: 21
Client secret: xxxxxxxxxxxxxxxx
```

```
root@fireflyiii:/var/www/firefly-iii# php artisan cache:clear
Application cache cleared!
```

```
root@fireflyiii:/var/www/firefly-iii# php artisan firefly:instructions install
+------------------------------------------------------------------------------+
|                                                                              |
| Thank you for installing Firefly III, v4.7.17!                               |
|                                                                              |
|                                                                              |
+------------------------------------------------------------------------------+
```

## Container Startup Log

```

Now in entrypoint.sh for Firefly III

Architecture:          x86_64

CPU op-mode(s):        32-bit, 64-bit

Byte Order:            Little Endian

CPU(s):                4

-line CPU(s) list:   0-3

Thread(s) per core:    1

Core(s) per socket:    4

Socket(s):             1

Vendor ID:             AuthenticAMD

CPU family:            22

Model:                 48

Model name:            AMD GX-420MC SOC

Stepping:              1

CPU MHz:               2000.000

CPU max MHz:           2000.0000

CPU min MHz:           1000.0000

BogoMIPS:              3992.60

Virtualization:        AMD-V

d cache:             32K

i cache:             32K

L2 cache:              2048K

Flags:                 fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good nopl nonstop_tsc extd_apicid aperfmperf eagerfpu pni pclmulqdq monitor ssse3 cx16 sse4_1 sse4_2 movbe popcnt aes xsave avx f16c rdrand lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw ibs skinit wdt topoext perfctr_nb bpext perfctr_l2 arat hw_pstate npt lbrv svm_lock nrip_save tsc_scale flushbyasid decodeassists pausefilter pfthreshold vmmcall bmi1 xsaveopt

Making directories...

Touch DB file (if SQLlite)...

Run chown on /var/www/firefly-iii/storage...

Run chmod on /var/www/firefly-iii/storage...

Remove log file...

Map environment variables on .env file...

Dump auto load...

Generating optimized autoload files> Illuminate\Foundation\ComposerScripts::postAutoloadDump

Generated optimized autoload files containing 4639 classes

Discover packages...

Discovered Package: adldap2/adldap2-laravel

Discovered Package: danhunsaker/laravel-flysystem-others

Discovered Package: davejamesmiller/laravel-breadcrumbs

Discovered Package: fideloper/proxy

Discovered Package: laravel/passport

Discovered Package: laravelcollective/html

Discovered Package: nesbot/carbon

Discovered Package: pragmarx/google2fa-laravel

Discovered Package: rcrowe/twigbridge

Package manifest generated successfully.

Run various artisan commands...

**************************************

*     Application In Production!     *

**************************************


Command Cancelled!

Going to decrypt the database.

[2019-07-07 11:07:32] production.ERROR: SQLSTATE[HY000] [2002] No route to host (SQL: select `id`, `name`, `data` from `configuration` where `name` = is_decrypted_accounts and `configuration`.`deleted_at` is null limit 1) {"exception":"[object] (Illuminate\\Database\\QueryException(code: 2002): SQLSTATE[HY000] [2002] No route to host (SQL: select `id`, `name`, `data` from `configuration` where `name` = is_decrypted_accounts and `configuration`.`deleted_at` is null limit 1) at /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Database/Connection.php:664, Doctrine\\DBAL\\Driver\\PDOException(code: 2002): SQLSTATE[HY000] [2002] No route to host at /var/www/firefly-iii/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:31, PDOException(code: 2002): SQLSTATE[HY000] [2002] No route to host at /var/www/firefly-iii/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:27)

[stacktrace]

#0 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Database/Connection.php(624): Illuminate\\Database\\Connection->runQueryCallback('select `id`, `n...', Array, Object(Closure))

#1 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Database/Connection.php(333): Illuminate\\Database\\Connection->run('select `id`, `n...', Array, Object(Closure))

#2 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2100): Illuminate\\Database\\Connection->select('select `id`, `n...', Array, true)

#3 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2088): Illuminate\\Database\\Query\\Builder->runSelect()

#4 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2574): Illuminate\\Database\\Query\\Builder->Illuminate\\Database\\Query\\{closure}()

#5 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2089): Illuminate\\Database\\Query\\Builder->onceWithColumns(Array, Object(Closure))

#6 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(519): Illuminate\\Database\\Query\\Builder->get(Array)

#7 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(503): Illuminate\\Database\\Eloquent\\Builder->getModels(Array)

#8 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Database/Concerns/BuildsQueries.php(77): Illuminate\\Database\\Eloquent\\Builder->get(Array)

#9 /var/www/firefly-iii/app/Support/FireflyConfig.php(65): Illuminate\\Database\\Eloquent\\Builder->first(Array)

#10 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(237): FireflyIII\\Support\\FireflyConfig->get('is_decrypted_ac...', false)

#11 /var/www/firefly-iii/app/Console/Commands/DecryptDatabase.php(132): Illuminate\\Support\\Facades\\Facade::__callStatic('get', Array)

#12 /var/www/firefly-iii/app/Console/Commands/DecryptDatabase.php(78): FireflyIII\\Console\\Commands\\DecryptDatabase->isDecrypted('accounts')

#13 [internal function]: FireflyIII\\Console\\Commands\\DecryptDatabase->handle()

#14 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(32): call_user_func_array(Array, Array)

#15 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(90): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()

#16 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(34): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))

#17 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Container/Container.php(580): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)

#18 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Console/Command.php(183): Illuminate\\Container\\Container->call(Array)

#19 /var/www/firefly-iii/vendor/symfony/console/Command/Command.php(255): Illuminate\\Console\\Command->execute(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))

#20 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Console/Command.php(170): Symfony\\Component\\Console\\Command\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))

#21 /var/www/firefly-iii/vendor/symfony/console/Application.php(908): Illuminate\\Console\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))

#22 /var/www/firefly-iii/vendor/symfony/console/Application.php(269): Symfony\\Component\\Console\\Application->doRunCommand(Object(FireflyIII\\Console\\Commands\\DecryptDatabase), Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))

#23 /var/www/firefly-iii/vendor/symfony/console/Application.php(145): Symfony\\Component\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))

#24 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Console/Application.php(90): Symfony\\Component\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))

#25 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(122): Illuminate\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))

#26 /var/www/firefly-iii/artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))

#27 {main}

"} 


In Connection.php line 664:

                                                                               

  SQLSTATE[HY000] [2002] No route to host (SQL: select `id`, `name`, `data` f  

  rom `configuration` where `name` = is_decrypted_accounts and `configuration  

  `.`deleted_at` is null limit 1)                                              

                                                                               


In PDOConnection.php line 31:

                                           

  SQLSTATE[HY000] [2002] No route to host  

                                           


In PDOConnection.php line 27:

                                           

  SQLSTATE[HY000] [2002] No route to host  
```

**Comment by JC5** [comment]
>  Detail here: I disabled logins at all so the prompt should not be there in the first place.

What do you mean?

**Comment by JamborJan** [comment]
Sorry, that was a false information. Actually I have the single user setup and a password automation ... sorry for that.

I also switched back both containers to the bridge network, then everything is fine and working again. Going back to the macular setup and everything is broken again. Strange stuff.

**Comment by JamborJan** [comment]
Okay, i've a pretty wired setup now which is working. Besides the macvlan network I also assigned the default bridge network to both containers (marinade and firefly) and I changed back the ENV entry to connect to the DB on the default bridge network. As the firefly container is still assigned to the macvlan network I can access firefly with the IP address / name in my network I wanted to have.

Pretty weird stuff. Do you have any idea what I could do to track down the problem? I don't want to waste your time here especially as I have a working solution now which also might help others.

**Comment by JC5** [comment]
Very strange. Not really sure to be honest. For the next release I will overhaul the docker image and configuration, and that should make it a lot simpler to manage.
