### ISSUE TITLE
Getting artisan post-install-cmd error 255 (FreeBSD)

### ISSUE THREAD

**Issue by rubenverhoef** [firefly-iii/firefly-iii#2387]
I am installing Firefly III version 4.8.0

**Description**

I'm trying to install Firefly III on my FreeNAS (FreeBSD 11.2) server but i get:
````
Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan firefly:instructions install
Script @php artisan firefly:instructions install handling the post-install-cmd event returned with error code 255
````
when running:
````
composer create-project grumpydictator/firefly-iii --no-dev --prefer-dist firefly-iii 4.8.0
````
Any idea what i can do to fix this?

**Extra info**
* FreeNAS 11.2 (FreeBSD 11.2)

Composer is successfull installed using:
````
curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
````
Installed packages:
* nginx
* php72
* php72-bcmath
* php72-intl
* php72-curl
* php72-zip
* php72-gd
* php72-xml
* php72-mbstring
* php72-ldap
* php72-json
* php72-phar
* php72-filter
* php72-hash
* php72-openssl
* php72-zlib
* php72-fileinfo
* php72-simplexml
* php72-tokenizer
* php72-iconv
* php72-pdo_mysql
* php72-dom

**Comment by JC5** [comment]
Is there anything in the logs? The instructions command only outputs text so there’s not much that you’re missing.

**Comment by rubenverhoef** [comment]
Do you know where i can find the log? or which logs are you referring to?

**Comment by rubenverhoef** [comment]
Found the problem!
I was testing to install with verbose but no more related information was coming.
Than i was installing using:
````
composer --verbose create-project grumpydictator/                                                                                      firefly-iii --prefer-dist firefly-iii 4.8.0
````
(without the --no-dev) and i got 
````
Generating optimized autoload files
> post-autoload-dump: Illuminate\Foundation\ComposerScripts::postAutoloadDump
> post-install-cmd: @php artisan firefly:instructions install
PHP Fatal error:  Interface 'SessionHandlerInterface' not found in /usr/local/w                                                                                      ww/firefly-iii/vendor/laravel/framework/src/Illuminate/Session/FileSessionHandl                                                                                      er.php on line 10
PHP Fatal error:  Uncaught TypeError: Argument 2 passed to Illuminate\Session\E                                                                                      ncryptedStore::__construct() must be an instance of SessionHandlerInterface, in                                                                                      stance of Illuminate\Session\FileSessionHandler given, called in /usr/local/www                                                                                      /firefly-iii/vendor/laravel/framework/src/Illuminate/Session/SessionManager.php                                                                                       on line 189 and defined in /usr/local/www/firefly-iii/vendor/laravel/framework                                                                                      /src/Illuminate/Session/EncryptedStore.php:27
Stack trace:
#0 /usr/local/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Session/S                                                                                      essionManager.php(189): Illuminate\Session\EncryptedStore->__construct('firefly                                                                                      _session', Object(Illuminate\Session\FileSessionHandler), Object(Illuminate\Enc                                                                                      ryption\Encrypter))
#1 /usr/local/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Session/S                                                                                      essionManager.php(176): Illuminate\Session\SessionManager->buildEncryptedSessio                                                                                      n(Object(Illuminate\Session\FileSessionHandler))
#2 /usr/local/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Session/S                                                                                      essionManager.php(62): Illuminate\Session\Ses in /usr/local/www/firefly-iii/ven                                                                                      dor/laravel/framework/src/Illuminate/Session/EncryptedStore.php on line 27
Script @php artisan firefly:instructions install handling the post-install-cmd                                                                                       event returned with error code 255
````
After an google hit the solution was to install the `php72-session` package. Now it is installing like it would.

@JC5  Thanks for your fast reply! appreciate it a lot.

**Comment by JC5** [comment]
I'll add this to the composer requirements as well. That should make the error appear sooner.
