### ISSUE TITLE
Initial bank setup error: Trying to get property 'user' of non-object

### ISSUE THREAD

**Issue by hamuz** [firefly-iii/firefly-iii#2388]
**Bug description**
I am running Firefly III version 4.8.0#**develop**, and my problem is:

Error:
Trying to get property 'user' of non-object

**Steps to reproduce**

1. Deploy on heroku 
https://heroku.com/deploy?template=https://github.com/firefly-iii/firefly-iii/tree/develop
2. Complete user registration
3. In first account form: "Bank Test", amount: 0, currencly: ILS, savings: 0
4. Finish, and get error. (Trying to get property 'user' of non-object)

**Expected behavior**

Initial setup complete without erros and redirected to main screen.

**Extra info**

Debug information generated at 2019-08-10 08:59:14 UTC for Firefly III version **4.8.0**.

| Variable | Content |
| --- | --- |
| FF version | 4.8.0 |
| FF API version | 0.10.0 |
| App environment | heroku |
| App debug mode | false |
| App cache driver | file |
| App logging | , stdout |
| PHP version | 7.3.8 |
| Display errors | Off |
| Session start | 2019-08-01 00:00:00 |
| Session end | 2019-08-31 23:59:59 |
| Session first | 2019-01-01 00:00:00 |
| Error reporting | ALL errors |
| Host | Linux |
| Interface | fpm-fcgi |
| UserID | 1 |
| Attempt at "en" | 'en' |
| Attempt at "English" | false |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| DB drivers | mysql, pgsql |
| Current driver | pgsql |
| Login provider |   |
| Storage disks | local-upload  |
| Using Sandstorm? | no |
| Is Sandstorm (.env) | false |
| Is Docker (.env) | false |
| bunq uses sandbox | false |
| Trusted proxies (.env) | ** |
| User agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.100 Safari/537.36 |
| Loaded extensions | Core, date, libxml, openssl, pcre, zlib, bz2, ctype, curl, dom, fileinfo, filter, hash, iconv, json, SPL, PDO, session, pdo_pgsql, pgsql, standard, posix, readline, Reflection, Phar, SimpleXML, sockets, mysqlnd, mysqli, tokenizer, xml, xmlreader, xmlwriter, zip, pdo_mysql, cgi-fcgi, bcmath, gd, intl, ldap, mbstring, Zend OPcache |

**Bonus points**

Stacktrace from logs:
```
2019-08-10T09:06:43.457296+00:00 app[web.1]: Beep boop,
2019-08-10T09:06:43.457352+00:00 app[web.1]: The Firefly III Mail Robot
2019-08-10T09:06:43.457536+00:00 app[web.1]: PS: This message was sent because a request from IP 4.3.2.1 triggered it.
2019-08-10T09:06:43.457540+00:00 app[web.1]:   
2019-08-10T09:06:43.457953+00:00 app[web.1]: [2019-08-10 09:06:43] heroku.ERROR: Trying to get property 'user' of non-object {"userId":1,"exception":"[object] (ErrorException(code: 0): Trying to get property 'user' of non-object at /app/app/Factory/TransactionGroupFactory.php:66)
2019-08-10T09:06:43.457982+00:00 app[web.1]: [stacktrace]
2019-08-10T09:06:43.458292+00:00 app[web.1]: #0 /app/app/Factory/TransactionGroupFactory.php(66): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError(8, 'Trying to get p...', '/app/app/Factor...', 66, Array)
2019-08-10T09:06:43.458515+00:00 app[web.1]: #1 /app/app/Services/Internal/Support/AccountServiceTrait.php(264): FireflyIII\\Factory\\TransactionGroupFactory->create(Array)
2019-08-10T09:06:43.458800+00:00 app[web.1]: #2 /app/app/Services/Internal/Support/AccountServiceTrait.php(291): FireflyIII\\Factory\\AccountFactory->createOBGroup(Object(FireflyIII\\Models\\Account), Array)
2019-08-10T09:06:43.459040+00:00 app[web.1]: #3 /app/app/Factory/AccountFactory.php(120): FireflyIII\\Factory\\AccountFactory->updateOBGroup(Object(FireflyIII\\Models\\Account), Array)
2019-08-10T09:06:43.459235+00:00 app[web.1]: #4 /app/app/Repositories/Account/AccountRepository.php(525): FireflyIII\\Factory\\AccountFactory->create(Array)
2019-08-10T09:06:43.459478+00:00 app[web.1]: #5 /app/app/Support/Http/Controllers/CreateStuff.php(72): FireflyIII\\Repositories\\Account\\AccountRepository->store(Array)
2019-08-10T09:06:43.459880+00:00 app[web.1]: #6 /app/app/Http/Controllers/NewUserController.php(105): FireflyIII\\Http\\Controllers\\NewUserController->createAssetAccount(Object(FireflyIII\\Http\\Requests\\NewUserFormRequest), Object(FireflyIII\\Models\\TransactionCurrency))
2019-08-10T09:06:43.460228+00:00 app[web.1]: #7 [internal function]: FireflyIII\\Http\\Controllers\\NewUserController->submit(Object(FireflyIII\\Http\\Requests\\NewUserFormRequest), Object(FireflyIII\\Repositories\\Currency\\CurrencyRepository))
2019-08-10T09:06:43.460420+00:00 app[web.1]: #8 /app/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): call_user_func_array(Array, Array)
2019-08-10T09:06:43.460676+00:00 app[web.1]: #9 /app/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\\Routing\\Controller->callAction('submit', Array)
2019-08-10T09:06:43.461103+00:00 app[web.1]: #10 /app/vendor/laravel/framework/src/Illuminate/Routing/Route.php(219): Illuminate\\Routing\\ControllerDispatcher->dispatch(Object(Illuminate\\Routing\\Route), Object(FireflyIII\\Http\\Controllers\\NewUserController), 'submit')
2019-08-10T09:06:43.461313+00:00 app[web.1]: #11 /app/vendor/laravel/framework/src/Illuminate/Routing/Route.php(176): Illuminate\\Routing\\Route->runController()
2019-08-10T09:06:43.461527+00:00 app[web.1]: #12 /app/vendor/laravel/framework/src/Illuminate/Routing/Router.php(680): Illuminate\\Routing\\Route->run()
2019-08-10T09:06:43.461860+00:00 app[web.1]: #13 /app/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
2019-08-10T09:06:43.462125+00:00 app[web.1]: #14 /app/app/Http/Controllers/NewUserController.php(51): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
2019-08-10T09:06:43.462540+00:00 app[web.1]: #15 /app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(145): FireflyIII\\Http\\Controllers\\NewUserController->FireflyIII\\Http\\Controllers\\{closure}(Object(Illuminate\\Http\\Request), Object(Closure))
2019-08-10T09:06:43.462844+00:00 app[web.1]: #16 /app/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
2019-08-10T09:06:43.463107+00:00 app[web.1]: #17 /app/app/Http/Controllers/Controller.php(88): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
2019-08-10T09:06:43.463464+00:00 app[web.1]: #18 /app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(145): FireflyIII\\Http\\Controllers\\Controller->FireflyIII\\Http\\Controllers\\{closure}(Object(Illuminate\\Http\\Request), Object(Closure))
2019-08-10T09:06:43.463811+00:00 app[web.1]: #19 /app/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
2019-08-10T09:06:43.464092+00:00 app[web.1]: #20 /app/app/Http/Middleware/InterestingMessage.php(56): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
2019-08-10T09:06:43.464358+00:00 app[web.1]: #21 /app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): FireflyIII\\Http\\Middleware\\InterestingMessage->handle(Object(Illuminate\\Http\\Request), Object(Closure))
2019-08-10T09:06:43.464651+00:00 app[web.1]: #22 /app/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
2019-08-10T09:06:43.464896+00:00 app[web.1]: #23 /app/app/Http/Middleware/Binder.php(78): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
2019-08-10T09:06:43.465194+00:00 app[web.1]: #24 /app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): FireflyIII\\Http\\Middleware\\Binder->handle(Object(Illuminate\\Http\\Request), Object(Closure))
2019-08-10T09:06:43.465526+00:00 app[web.1]: #25 /app/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
2019-08-10T09:06:43.465769+00:00 app[web.1]: #26 /app/app/Http/Middleware/Range.php(60): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
2019-08-10T09:06:43.466069+00:00 app[web.1]: #27 /app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): FireflyIII\\Http\\Middleware\\Range->handle(Object(Illuminate\\Http\\Request), Object(Closure))
2019-08-10T09:06:43.466386+00:00 app[web.1]: #28 /app/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
2019-08-10T09:06:43.466661+00:00 app[web.1]: #29 /app/vendor/pragmarx/google2fa-laravel/src/Middleware.php(15): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
2019-08-10T09:06:43.466962+00:00 app[web.1]: #30 /app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): PragmaRX\\Google2FALaravel\\Middleware->handle(Object(Illuminate\\Http\\Request), Object(Closure))
2019-08-10T09:06:43.467274+00:00 app[web.1]: #31 /app/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
2019-08-10T09:06:43.467528+00:00 app[web.1]: #32 /app/app/Http/Middleware/Authenticate.php(73): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
2019-08-10T09:06:43.467938+00:00 app[web.1]: #33 /app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): FireflyIII\\Http\\Middleware\\Authenticate->handle(Object(Illuminate\\Http\\Request), Object(Closure))
2019-08-10T09:06:43.468325+00:00 app[web.1]: #34 /app/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
2019-08-10T09:06:43.468730+00:00 app[web.1]: #35 /app/vendor/laravel/passport/src/Http/Middleware/CreateFreshApiToken.php(50): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
2019-08-10T09:06:43.469186+00:00 app[web.1]: #36 /app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Laravel\\Passport\\Http\\Middleware\\CreateFreshApiToken->handle(Object(Illuminate\\Http\\Request), Object(Closure))
2019-08-10T09:06:43.469630+00:00 app[web.1]: #37 /app/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
2019-08-10T09:06:43.470139+00:00 app[web.1]: #38 /app/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(75): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
2019-08-10T09:06:43.470584+00:00 app[web.1]: #39 /app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle(Object(Illuminate\\Http\\Request), Object(Closure))
2019-08-10T09:06:43.471020+00:00 app[web.1]: #40 /app/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
2019-08-10T09:06:43.471463+00:00 app[web.1]: #41 /app/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
2019-08-10T09:06:43.471910+00:00 app[web.1]: #42 /app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
2019-08-10T09:06:43.472356+00:00 app[web.1]: #43 /app/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
2019-08-10T09:06:43.472781+00:00 app[web.1]: #44 /app/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(56): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
2019-08-10T09:06:43.473245+00:00 app[web.1]: #45 /app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\\Session\\Middleware\\StartSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
2019-08-10T09:06:43.473673+00:00 app[web.1]: #46 /app/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
2019-08-10T09:06:43.474177+00:00 app[web.1]: #47 /app/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
2019-08-10T09:06:43.474654+00:00 app[web.1]: #48 /app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle(Object(Illuminate\\Http\\Request), Object(Closure))
2019-08-10T09:06:43.475053+00:00 app[web.1]: #49 /app/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
2019-08-10T09:06:43.475508+00:00 app[web.1]: #50 /app/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(66): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
2019-08-10T09:06:43.475954+00:00 app[web.1]: #51 /app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
2019-08-10T09:06:43.476394+00:00 app[web.1]: #52 /app/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
2019-08-10T09:06:43.476739+00:00 app[web.1]: #53 /app/app/Http/Middleware/Sandstorm.php(54): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
2019-08-10T09:06:43.477179+00:00 app[web.1]: #54 /app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): FireflyIII\\Http\\Middleware\\Sandstorm->handle(Object(Illuminate\\Http\\Request), Object(Closure))
2019-08-10T09:06:43.477609+00:00 app[web.1]: #55 /app/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
2019-08-10T09:06:43.478058+00:00 app[web.1]: #56 /app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(104): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
2019-08-10T09:06:43.478357+00:00 app[web.1]: #57 /app/vendor/laravel/framework/src/Illuminate/Routing/Router.php(682): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
2019-08-10T09:06:43.478829+00:00 app[web.1]: #58 /app/vendor/laravel/framework/src/Illuminate/Routing/Router.php(657): Illuminate\\Routing\\Router->runRouteWithinStack(Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request))
2019-08-10T09:06:43.479270+00:00 app[web.1]: #59 /app/vendor/laravel/framework/src/Illuminate/Routing/Router.php(623): Illuminate\\Routing\\Router->runRoute(Object(Illuminate\\Http\\Request), Object(Illuminate\\Routing\\Route))
2019-08-10T09:06:43.479644+00:00 app[web.1]: #60 /app/vendor/laravel/framework/src/Illuminate/Routing/Router.php(612): Illuminate\\Routing\\Router->dispatchToRoute(Object(Illuminate\\Http\\Request))
2019-08-10T09:06:43.480010+00:00 app[web.1]: #61 /app/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(176): Illuminate\\Routing\\Router->dispatch(Object(Illuminate\\Http\\Request))
2019-08-10T09:06:43.480513+00:00 app[web.1]: #62 /app/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}(Object(Illuminate\\Http\\Request))
2019-08-10T09:06:43.480897+00:00 app[web.1]: #63 /app/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
2019-08-10T09:06:43.481285+00:00 app[web.1]: #64 /app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Fideloper\\Proxy\\TrustProxies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
2019-08-10T09:06:43.481814+00:00 app[web.1]: #65 /app/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
2019-08-10T09:06:43.482298+00:00 app[web.1]: #66 /app/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
2019-08-10T09:06:43.482795+00:00 app[web.1]: #67 /app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
2019-08-10T09:06:43.483208+00:00 app[web.1]: #68 /app/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
2019-08-10T09:06:43.483685+00:00 app[web.1]: #69 /app/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
2019-08-10T09:06:43.484158+00:00 app[web.1]: #70 /app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
2019-08-10T09:06:43.484603+00:00 app[web.1]: #71 /app/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
2019-08-10T09:06:43.485072+00:00 app[web.1]: #72 /app/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
2019-08-10T09:06:43.485555+00:00 app[web.1]: #73 /app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
2019-08-10T09:06:43.485954+00:00 app[web.1]: #74 /app/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
2019-08-10T09:06:43.486449+00:00 app[web.1]: #75 /app/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(62): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
2019-08-10T09:06:43.486935+00:00 app[web.1]: #76 /app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode->handle(Object(Illuminate\\Http\\Request), Object(Closure))
2019-08-10T09:06:43.487329+00:00 app[web.1]: #77 /app/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
2019-08-10T09:06:43.487693+00:00 app[web.1]: #78 /app/app/Http/Middleware/SecureHeaders.php(45): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
2019-08-10T09:06:43.488125+00:00 app[web.1]: #79 /app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): FireflyIII\\Http\\Middleware\\SecureHeaders->handle(Object(Illuminate\\Http\\Request), Object(Closure))
2019-08-10T09:06:43.488543+00:00 app[web.1]: #80 /app/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
2019-08-10T09:06:43.488960+00:00 app[web.1]: #81 /app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(104): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
2019-08-10T09:06:43.489282+00:00 app[web.1]: #82 /app/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(151): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
2019-08-10T09:06:43.489686+00:00 app[web.1]: #83 /app/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(116): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
2019-08-10T09:06:43.489885+00:00 app[web.1]: #84 /app/public/index.php(76): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
2019-08-10T09:06:43.489893+00:00 app[web.1]: #85 {main}
2019-08-10T09:06:43.489904+00:00 app[web.1]: "} 
2019-08-10T09:06:43.490291+00:00 app[web.1]: 1.2.3.4 - - [10/Aug/2019:09:06:43 +0000] "POST /new-user/submit HTTP/1.1" 500 3114 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.100 Safari/537.36
```

**Comment by JC5** [comment]
Nice find, I can confirm the bug. It happens to normal users as well. I've pushed a fix which will go live next week, probably in the weekend. 

You can pick it up from the develop branch. In the mean time, the best solution is to submit an amount and then editing the account.
