### ISSUE TITLE
Upgrading from 4.7.8 to develop (4.8.0.3?) fails on sql constraint

### ISSUE THREAD

**Issue by hamuz** [firefly-iii/firefly-iii#2468]
**Bug description**
I am running Firefly III version 4.7.8, and my problem is:
Upgrading to develop(23/08/2019) (4.8.03?)

**Steps to reproduce**
1. Deploy develop.
2. run on server:
```
php artisan cache:clear
php artisan migrate --seed
php artisan firefly-iii:upgrade-database
```
First two completed successfully, 3rd fails with:
```
SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`firefly`.`transaction_groups`, CONSTRAINT `transaction_groups_user_id_foreign` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE) (SQL: insert into `transaction_groups` (`user_id`, `title`, `updated_at`, `created_at`) values (1, xxxx, 2019-08-23 11:05:22, 2019-08-23 11:05:22)) 
```

3. Deleted constraint `transaction_groups_user_id_foreign` on `firefly`.`transaction_groups`
4. `php artisan firefly-iii:upgrade-database`
succeeds.

5. Failing to recreate it with: 
```ALTER TABLE `transaction_groups` ADD CONSTRAINT `transaction_groups_user_id_foreign` FOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;```

#1005 - Can't create table `firefly`.`transaction_groups` (errno: 150 "Foreign key constraint is incorrectly formed")

**Expected behavior**
` php artisan firefly-iii:upgrade-database `
to succeed without dropping constraint.

**Extra info**

**Bonus points**

```
SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`firefly`.`transaction_groups`, CONSTRAINT `transaction_groups_user_id_foreign` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE) (SQL: insert into `transaction_groups` (`user_id`, `title`, `updated_at`, `created_at`) values (1, xxxx, 2019-08-23 11:05:22, 2019-08-23 11:05:22)) {"exception":"[object] (Illuminate\\Database\\QueryException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`firefly`.`transaction_groups`, CONSTRAINT `transaction_groups_user_id_foreign` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE) (SQL: insert into `transaction_groups` (`user_id`, `title`, `updated_at`, `created_at`) values (1, xxxx, 2019-08-23 11:05:22, 2019-08-23 11:05:22)) at /app/vendor/laravel/framework/src/Illuminate/Database/Connection.php:664, Doctrine\\DBAL\\Driver\\PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`firefly`.`transaction_groups`, CONSTRAINT `transaction_groups_user_id_foreign` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE) at /app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:119, PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`firefly`.`transaction_groups`, CONSTRAINT `transaction_groups_user_id_foreign` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE) at /app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:117)
[stacktrace]
#0 /app/vendor/laravel/framework/src/Illuminate/Database/Connection.php(624): Illuminate\\Database\\Connection->runQueryCallback('insert into `tr...', Array, Object(Closure))
#1 /app/vendor/laravel/framework/src/Illuminate/Database/Connection.php(459): Illuminate\\Database\\Connection->run('insert into `tr...', Array, Object(Closure))
#2 /app/vendor/laravel/framework/src/Illuminate/Database/Connection.php(411): Illuminate\\Database\\Connection->statement('insert into `tr...', Array)
#3 /app/vendor/laravel/framework/src/Illuminate/Database/Query/Processors/Processor.php(32): Illuminate\\Database\\Connection->insert('insert into `tr...', Array)
#4 /app/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2690): Illuminate\\Database\\Query\\Processors\\Processor->processInsertGetId(Object(Illuminate\\Database\\Query\\Builder), 'insert into `tr...', Array, 'id')
#5 /app/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(1353): Illuminate\\Database\\Query\\Builder->insertGetId(Array, 'id')
#6 /app/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(839): Illuminate\\Database\\Eloquent\\Builder->__call('insertGetId', Array)
#7 /app/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(804): Illuminate\\Database\\Eloquent\\Model->insertAndSetId(Object(Illuminate\\Database\\Eloquent\\Builder), Array)
#8 /app/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(667): Illuminate\\Database\\Eloquent\\Model->performInsert(Object(Illuminate\\Database\\Eloquent\\Builder))
#9 /app/app/Factory/TransactionGroupFactory.php(64): Illuminate\\Database\\Eloquent\\Model->save()
#10 /app/app/Console/Commands/Upgrade/MigrateToGroups.php(351): FireflyIII\\Factory\\TransactionGroupFactory->create(Array)
#11 /app/app/Console/Commands/Upgrade/MigrateToGroups.php(228): FireflyIII\\Console\\Commands\\Upgrade\\MigrateToGroups->makeMultiGroup(Object(FireflyIII\\Models\\TransactionJournal))
#12 /app/app/Console/Commands/Upgrade/MigrateToGroups.php(92): FireflyIII\\Console\\Commands\\Upgrade\\MigrateToGroups->makeGroupsFromSplitJournals()
#13 [internal function]: FireflyIII\\Console\\Commands\\Upgrade\\MigrateToGroups->handle()
#14 /app/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(32): call_user_func_array(Array, Array)
#15 /app/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(90): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#16 /app/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(34): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#17 /app/vendor/laravel/framework/src/Illuminate/Container/Container.php(576): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#18 /app/vendor/laravel/framework/src/Illuminate/Console/Command.php(183): Illuminate\\Container\\Container->call(Array)
#19 /app/vendor/symfony/console/Command/Command.php(255): Illuminate\\Console\\Command->execute(Object(Symfony\\Component\\Console\\Input\\StringInput), Object(Illuminate\\Console\\OutputStyle))
#20 /app/vendor/laravel/framework/src/Illuminate/Console/Command.php(170): Symfony\\Component\\Console\\Command\\Command->run(Object(Symfony\\Component\\Console\\Input\\StringInput), Object(Illuminate\\Console\\OutputStyle))
#21 /app/vendor/symfony/console/Application.php(921): Illuminate\\Console\\Command->run(Object(Symfony\\Component\\Console\\Input\\StringInput), Object(Symfony\\Component\\Console\\Output\\BufferedOutput))
#22 /app/vendor/symfony/console/Application.php(273): Symfony\\Component\\Console\\Application->doRunCommand(Object(FireflyIII\\Console\\Commands\\Upgrade\\MigrateToGroups), Object(Symfony\\Component\\Console\\Input\\StringInput), Object(Symfony\\Component\\Console\\Output\\BufferedOutput))
#23 /app/vendor/symfony/console/Application.php(149): Symfony\\Component\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\StringInput), Object(Symfony\\Component\\Console\\Output\\BufferedOutput))
#24 /app/vendor/laravel/framework/src/Illuminate/Console/Application.php(90): Symfony\\Component\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\StringInput), Object(Symfony\\Component\\Console\\Output\\BufferedOutput))
#25 /app/vendor/laravel/framework/src/Illuminate/Console/Application.php(182): Illuminate\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\StringInput), Object(Symfony\\Component\\Console\\Output\\BufferedOutput))
#26 /app/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(275): Illuminate\\Console\\Application->call('firefly-iii:mig...', Array, NULL)
#27 /app/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(237): Illuminate\\Foundation\\Console\\Kernel->call('firefly-iii:mig...', Array)
#28 /app/app/Console/Commands/Upgrade/UpgradeDatabase.php(104): Illuminate\\Support\\Facades\\Facade::__callStatic('call', Array)
#29 [internal function]: FireflyIII\\Console\\Commands\\Upgrade\\UpgradeDatabase->handle()
#30 /app/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(32): call_user_func_array(Array, Array)
#31 /app/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(90): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#32 /app/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(34): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#33 /app/vendor/laravel/framework/src/Illuminate/Container/Container.php(576): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#34 /app/vendor/laravel/framework/src/Illuminate/Console/Command.php(183): Illuminate\\Container\\Container->call(Array)
#35 /app/vendor/symfony/console/Command/Command.php(255): Illuminate\\Console\\Command->execute(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#36 /app/vendor/laravel/framework/src/Illuminate/Console/Command.php(170): Symfony\\Component\\Console\\Command\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#37 /app/vendor/symfony/console/Application.php(921): Illuminate\\Console\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#38 /app/vendor/symfony/console/Application.php(273): Symfony\\Component\\Console\\Application->doRunCommand(Object(FireflyIII\\Console\\Commands\\Upgrade\\UpgradeDatabase), Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#39 /app/vendor/symfony/console/Application.php(149): Symfony\\Component\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#40 /app/vendor/laravel/framework/src/Illuminate/Console/Application.php(90): Symfony\\Component\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#41 /app/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(133): Illuminate\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#42 /app/artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#43 {main}
"} 

In Connection.php line 664:
                                                                               
  SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update   
  a child row: a foreign key constraint fails (`firefly`.`transactio  
  n_groups`, CONSTRAINT `transaction_groups_user_id_foreign` FOREIGN KEY (`us  
  er_id`) REFERENCES `users` (`id`) ON DELETE CASCADE) (SQL: insert into `tra  
  nsaction_groups` (`user_id`, `title`, `updated_at`, `created_at`) values (1  
  , xxx, 2019-08-23 11:05:22, 2019-08-23 11:05:22))                  
                                                                               

In PDOStatement.php line 119:
                                                                               
  SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update   
  a child row: a foreign key constraint fails (`firefly`.`transactio  
  n_groups`, CONSTRAINT `transaction_groups_user_id_foreign` FOREIGN KEY (`us  
  er_id`) REFERENCES `users` (`id`) ON DELETE CASCADE)                         
                                                                               

In PDOStatement.php line 117:
                                                                               
  SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update   
  a child row: a foreign key constraint fails (`firefly`.`transactio  
  n_groups`, CONSTRAINT `transaction_groups_user_id_foreign` FOREIGN KEY (`us  
  er_id`) REFERENCES `users` (`id`) ON DELETE CASCADE)                         
                                                                               
```

**Comment by JC5** [comment]
That's an inconsistency in your database. Does user_id 1 exist in the users table?

**Comment by hamuz** [comment]
Yes, I've checked that, I had 3 users, with ids 1, 2 and 3.
And as far as I can tell, the types match `int(10) unsigned`

**Comment by JC5** [comment]
OK, that was my next question. But that also leaves me clueless. There are no other constraints on that table. :/

**Comment by hamuz** [comment]
when I select distinct user_id I get 1, 2, and 3.
At the time the constraint failed, the groups DB was empty.

**Comment by hamuz** [comment]
Are you interested in getting to the bottom of this?
I can recreate this situation from backup and provide you `users` and `transaction_groups` tables in the means of SQL dump (pre-constraint dropping).

The impact is mostly focused on pre-4.8 users upgrading to 4.8+.

I would understand if you wish to conserve energy and focus on other matters, no hard feelings. I will close the issue if so.
( I will remain without that constraint, by it's not a deal breaker )

**Comment by JC5** [comment]
No please do, I'll dive into the issue.

**Comment by hamuz** [comment]
Deployed version was:
https://github.com/hamuz/firefly-iii/commit/acd2694f2f4ea130d7aa01ff34feca7c5a833d25

Tables **before** upgrade:
```
--
-- Table structure for table `users`
--

DROP TABLE IF EXISTS `users`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `users` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  `email` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `password` varchar(60) COLLATE utf8mb4_unicode_ci NOT NULL,
  `remember_token` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `reset` varchar(32) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `blocked` tinyint(3) unsigned NOT NULL DEFAULT 0,
  `blocked_code` varchar(25) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM AUTO_INCREMENT=4 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Dumping data for table `users`
--

LOCK TABLES `users` WRITE;
/*!40000 ALTER TABLE `users` DISABLE KEYS */;
INSERT INTO `users` (`id`, `created_at`, `updated_at`, `email`, `password`, `remember_token`, `reset`, `blocked`, `blocked_code`) VALUES (1,'2018-01-01 01:01:01','2018-01-01 01:01:01','1@gmail.com','$2y$10$11111111111111111111111111111111111111111111111111111','xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',NULL,0,NULL),(2,'2018-02-02 02:02:02','2018-02-02 02:02:02','2@gmail.com','$2y$10$11111111111111111111111111111111111111111111111111111','xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',NULL,0,NULL),(3,'2018-09-27 03:03:03','2018-03-03 03:03:03','3@gmail.com','$2y$10$11111111111111111111111111111111111111111111111111111','xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',NULL,0,NULL);
/*!40000 ALTER TABLE `users` ENABLE KEYS */;
UNLOCK TABLES;

--
-- Table structure for table `transaction_groups`
--

DROP TABLE IF EXISTS `transaction_groups`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `transaction_groups` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  `deleted_at` timestamp NULL DEFAULT NULL,
  `user_id` int(10) unsigned NOT NULL,
  `title` varchar(1024) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `transaction_groups_user_id_foreign` (`user_id`),
  CONSTRAINT `transaction_groups_user_id_foreign` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Dumping data for table `transaction_groups`
--

LOCK TABLES `transaction_groups` WRITE;
/*!40000 ALTER TABLE `transaction_groups` DISABLE KEYS */;
/*!40000 ALTER TABLE `transaction_groups` ENABLE KEYS */;
UNLOCK TABLES;
```

Than deployed this version:
https://github.com/hamuz/firefly-iii/commit/02df24bbc975ba5493a982893d5784e954306bbe
https://github.com/hamuz/firefly-iii/compare/acd2694f...02df24bb

Run:
```
php artisan cache:clear
php artisan migrate --seed
php artisan firefly-iii:upgrade-database
```

Log:

```
~ $ php artisan cache:clear
Application cache cleared!
~ $ php artisan migrate --seed
Migrating: 2019_01_28_193833_changes_for_v4710
Migrated:  2019_01_28_193833_changes_for_v4710 (0.07 seconds)
Migrating: 2019_02_05_055516_changes_for_v4711
Migrated:  2019_02_05_055516_changes_for_v4711 (0.68 seconds)
Migrating: 2019_02_11_170529_changes_for_v4712
Migrated:  2019_02_11_170529_changes_for_v4712 (0.21 seconds)
Migrating: 2019_03_11_223700_fix_ldap_configuration
Migrated:  2019_03_11_223700_fix_ldap_configuration (0.22 seconds)
Migrating: 2019_03_22_183214_changes_for_v480
Migrated:  2019_03_22_183214_changes_for_v480 (0.65 seconds)
Seeding: AccountTypeSeeder
[2019-08-23 14:08:10] heroku.INFO: Could not create account type "Default account". It might exist already.  
[2019-08-23 14:08:10] heroku.INFO: Could not create account type "Cash account". It might exist already.  
[2019-08-23 14:08:10] heroku.INFO: Could not create account type "Asset account". It might exist already.  
[2019-08-23 14:08:10] heroku.INFO: Could not create account type "Expense account". It might exist already.  
[2019-08-23 14:08:10] heroku.INFO: Could not create account type "Revenue account". It might exist already.  
[2019-08-23 14:08:10] heroku.INFO: Could not create account type "Initial balance account". It might exist already.  
[2019-08-23 14:08:10] heroku.INFO: Could not create account type "Beneficiary account". It might exist already.  
[2019-08-23 14:08:10] heroku.INFO: Could not create account type "Import account". It might exist already.  
[2019-08-23 14:08:10] heroku.INFO: Could not create account type "Loan". It might exist already.  
[2019-08-23 14:08:10] heroku.INFO: Could not create account type "Reconciliation account". It might exist already.  
[2019-08-23 14:08:10] heroku.INFO: Could not create account type "Debt". It might exist already.  
[2019-08-23 14:08:10] heroku.INFO: Could not create account type "Mortgage". It might exist already.  
Seeding: TransactionCurrencySeeder
[2019-08-23 14:08:10] heroku.INFO: Could not create transaction currency "EUR". It might exist already.  
[2019-08-23 14:08:10] heroku.INFO: Could not create transaction currency "HUF". It might exist already.  
[2019-08-23 14:08:10] heroku.INFO: Could not create transaction currency "GBP". It might exist already.  
[2019-08-23 14:08:10] heroku.INFO: Could not create transaction currency "UAH". It might exist already.  
[2019-08-23 14:08:10] heroku.INFO: Could not create transaction currency "PLN". It might exist already.  
[2019-08-23 14:08:10] heroku.INFO: Could not create transaction currency "TRY". It might exist already.  
[2019-08-23 14:08:10] heroku.INFO: Could not create transaction currency "USD". It might exist already.  
[2019-08-23 14:08:10] heroku.INFO: Could not create transaction currency "BRL". It might exist already.  
[2019-08-23 14:08:10] heroku.INFO: Could not create transaction currency "CAD". It might exist already.  
[2019-08-23 14:08:10] heroku.INFO: Could not create transaction currency "IDR". It might exist already.  
[2019-08-23 14:08:10] heroku.INFO: Could not create transaction currency "AUD". It might exist already.  
[2019-08-23 14:08:10] heroku.INFO: Could not create transaction currency "NZD". It might exist already.  
[2019-08-23 14:08:10] heroku.INFO: Could not create transaction currency "EGP". It might exist already.  
[2019-08-23 14:08:10] heroku.INFO: Could not create transaction currency "MAD". It might exist already.  
[2019-08-23 14:08:10] heroku.INFO: Could not create transaction currency "ZAR". It might exist already.  
[2019-08-23 14:08:10] heroku.INFO: Could not create transaction currency "JPY". It might exist already.  
[2019-08-23 14:08:11] heroku.INFO: Could not create transaction currency "RMB". It might exist already.  
[2019-08-23 14:08:11] heroku.INFO: Could not create transaction currency "RUB". It might exist already.  
[2019-08-23 14:08:11] heroku.INFO: Could not create transaction currency "INR". It might exist already.  
[2019-08-23 14:08:11] heroku.INFO: Could not create transaction currency "XBT". It might exist already.  
[2019-08-23 14:08:11] heroku.INFO: Could not create transaction currency "BCH". It might exist already.  
[2019-08-23 14:08:11] heroku.INFO: Could not create transaction currency "ETH". It might exist already.  
[2019-08-23 14:08:11] heroku.INFO: Could not create transaction currency "ILS". It might exist already.  
[2019-08-23 14:08:11] heroku.INFO: Could not create transaction currency "CHF". It might exist already.  
Seeding: TransactionTypeSeeder
[2019-08-23 14:08:11] heroku.INFO: Could not create transaction type "Withdrawal". It might exist already.  
[2019-08-23 14:08:11] heroku.INFO: Could not create transaction type "Deposit". It might exist already.  
[2019-08-23 14:08:11] heroku.INFO: Could not create transaction type "Transfer". It might exist already.  
[2019-08-23 14:08:11] heroku.INFO: Could not create transaction type "Opening balance". It might exist already.  
[2019-08-23 14:08:11] heroku.INFO: Could not create transaction type "Reconciliation". It might exist already.  
Seeding: PermissionSeeder
[2019-08-23 14:08:11] heroku.INFO: Could not create role "Site Owner". It might exist already.  
[2019-08-23 14:08:11] heroku.INFO: Could not create role "Demo User". It might exist already.  
Seeding: LinkTypeSeeder
Seeding: ConfigSeeder
[2019-08-23 14:08:11] heroku.WARNING: Database entry exists. Update to latest version (11)  
Database seeding completed successfully.
```

Tables **after** upgrades:
```
--
-- Table structure for table `users`
--

DROP TABLE IF EXISTS `users`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `users` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `objectguid` char(36) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  `email` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `password` varchar(60) COLLATE utf8mb4_unicode_ci NOT NULL,
  `remember_token` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `reset` varchar(32) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `blocked` tinyint(3) unsigned NOT NULL DEFAULT 0,
  `blocked_code` varchar(25) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `mfa_secret` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM AUTO_INCREMENT=4 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Dumping data for table `users`
--

LOCK TABLES `users` WRITE;
/*!40000 ALTER TABLE `users` DISABLE KEYS */;
INSERT INTO `users` (`id`, `objectguid`, `created_at`, `updated_at`, `email`, `password`, `remember_token`, `reset`, `blocked`, `blocked_code`, `mfa_secret`) VALUES (1,NULL,'2018-01-01 01:01:01','2018-01-01 01:01:01','1@gmail.com','$2y$10$11111111111111111111111111111111111111111111111111111','xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',NULL,0,NULL,NULL),(2,NULL,'2018-02-02 02:02:02','2018-02-02 02:02:02','2@gmail.com','$2y$10$11111111111111111111111111111111111111111111111111111','xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',NULL,0,NULL,NULL),(3,NULL,'2018-09-27 03:03:03','2018-03-03 03:03:03','3@gmail.com','$2y$10$11111111111111111111111111111111111111111111111111111','xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',NULL,0,NULL,NULL);
/*!40000 ALTER TABLE `users` ENABLE KEYS */;
UNLOCK TABLES;

--
-- Table structure for table `transaction_groups`
--

DROP TABLE IF EXISTS `transaction_groups`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `transaction_groups` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  `deleted_at` timestamp NULL DEFAULT NULL,
  `user_id` int(10) unsigned NOT NULL,
  `title` varchar(1024) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `transaction_groups_user_id_foreign` (`user_id`),
  CONSTRAINT `transaction_groups_user_id_foreign` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Dumping data for table `transaction_groups`
--

LOCK TABLES `transaction_groups` WRITE;
/*!40000 ALTER TABLE `transaction_groups` DISABLE KEYS */;
/*!40000 ALTER TABLE `transaction_groups` ENABLE KEYS */;
UNLOCK TABLES;
```

**Comment by JC5** [comment]
I see that your users table is a MyISAM table. I think we had a few issues in the past that were related to MyISAM.

I was able to migrate successfully from a plain 4.7.8 to a plain 4.8.0.3, with the caveat that I only added a single user and single journal.

```
vagrant@ubuntu-bionic:/sites/temp/firefly-478/firefly-iii$ php artisan migrate --seed
[..]
Database seeding completed successfully.
```

And from the dev dir.
```
vagrant@ubuntu-bionic:/sites/FF3/firefly-iii$ php artisan ca:cl
Application cache cleared!
vagrant@ubuntu-bionic:/sites/FF3/firefly-iii$ php artisan firefly-iii:upgrade
[..]
+------------------------------------------------------------------------------+
```

I'll pull the specific commits later tonight but I think the MyISAM thing may be the culprit here.
