### ISSUE TITLE
Error when creating transaction after upgrading to 4.8.0.3

### ISSUE THREAD

**Issue by scott-mcnulty** [firefly-iii/firefly-iii#2504]
**Bug description**
I am running Firefly III version 4.8.0.3, and my problem is:

After recently upgrading to the latest version deployed on Heroku I'm getting this error when trying to enter a transaction:

```
2019-08-27T11:45:42.082824+00:00 app[web.1]: [2019-08-27 11:45:42] heroku.ERROR: Key path "file:///app/storage/oauth-public.key" does not exist or is not readable {"exception":"[object] (LogicException(code: 0): Key path \"file:///app/storage/oauth-public.key\" does not exist or is not readable at /app/vendor/league/oauth2-server/src/CryptKey.php:48)
2019-08-27T11:45:42.082846+00:00 app[web.1]: [stacktrace]
2019-08-27T11:45:42.083110+00:00 app[web.1]: #0 /app/vendor/laravel/passport/src/PassportServiceProvider.php(243): League\\OAuth2\\Server\\CryptKey->__construct('file:///app/sto...', NULL, false)
2019-08-27T11:45:42.083345+00:00 app[web.1]: #1 /app/vendor/laravel/passport/src/PassportServiceProvider.php(224): Laravel\\Passport\\PassportServiceProvider->makeCryptKey('public')
2019-08-27T11:45:42.083694+00:00 app[web.1]: #2 /app/vendor/laravel/framework/src/Illuminate/Container/Container.php(785): Laravel\\Passport\\PassportServiceProvider->Laravel\\Passport\\{closure}(Object(Illuminate\\Foundation\\Application), Array)
2019-08-27T11:45:42.083904+00:00 app[web.1]: #3 /app/vendor/laravel/framework/src/Illuminate/Container/Container.php(667): Illuminate\\Container\\Container->build(Object(Closure))
2019-08-27T11:45:42.084184+00:00 app[web.1]: #4 /app/vendor/laravel/framework/src/Illuminate/Container/Container.php(615): Illuminate\\Container\\Container->resolve('League\\\\OAuth2\\\\S...', Array)
2019-08-27T11:45:42.084445+00:00 app[web.1]: #5 /app/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(767): Illuminate\\Container\\Container->make('League\\\\OAuth2\\\\S...', Array)
2019-08-27T11:45:42.084699+00:00 app[web.1]: #6 /app/vendor/laravel/passport/src/PassportServiceProvider.php(270): Illuminate\\Foundation\\Application->make('League\\\\OAuth2\\\\S...')
2019-08-27T11:45:42.084931+00:00 app[web.1]: #7 [internal function]: Laravel\\Passport\\PassportServiceProvider->Laravel\\Passport\\{closure}(Object(Illuminate\\Http\\Request), NULL)
2019-08-27T11:45:42.085179+00:00 app[web.1]: #8 /app/vendor/laravel/framework/src/Illuminate/Auth/RequestGuard.php(58): call_user_func(Object(Closure), Object(Illuminate\\Http\\Request), NULL)
2019-08-27T11:45:42.085372+00:00 app[web.1]: #9 /app/vendor/laravel/framework/src/Illuminate/Auth/GuardHelpers.php(60): Illuminate\\Auth\\RequestGuard->user()
2019-08-27T11:45:42.085529+00:00 app[web.1]: #10 /app/app/Http/Middleware/Authenticate.php(128): Illuminate\\Auth\\RequestGuard->check()
2019-08-27T11:45:42.085780+00:00 app[web.1]: #11 /app/app/Http/Middleware/Authenticate.php(71): FireflyIII\\Http\\Middleware\\Authenticate->authenticate(Object(Illuminate\\Http\\Request), Array)
2019-08-27T11:45:42.086093+00:00 app[web.1]: #12 /app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): FireflyIII\\Http\\Middleware\\Authenticate->handle(Object(Illuminate\\Http\\Request), Object(Closure), 'api')
2019-08-27T11:45:42.086404+00:00 app[web.1]: #13 /app/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
2019-08-27T11:45:42.086692+00:00 app[web.1]: #14 /app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(104): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
2019-08-27T11:45:42.086907+00:00 app[web.1]: #15 /app/vendor/laravel/framework/src/Illuminate/Routing/Router.php(682): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
2019-08-27T11:45:42.087231+00:00 app[web.1]: #16 /app/vendor/laravel/framework/src/Illuminate/Routing/Router.php(657): Illuminate\\Routing\\Router->runRouteWithinStack(Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request))
2019-08-27T11:45:42.087537+00:00 app[web.1]: #17 /app/vendor/laravel/framework/src/Illuminate/Routing/Router.php(623): Illuminate\\Routing\\Router->runRoute(Object(Illuminate\\Http\\Request), Object(Illuminate\\Routing\\Route))
2019-08-27T11:45:42.087816+00:00 app[web.1]: #18 /app/vendor/laravel/framework/src/Illuminate/Routing/Router.php(612): Illuminate\\Routing\\Router->dispatchToRoute(Object(Illuminate\\Http\\Request))
2019-08-27T11:45:42.088077+00:00 app[web.1]: #19 /app/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(176): Illuminate\\Routing\\Router->dispatch(Object(Illuminate\\Http\\Request))
2019-08-27T11:45:42.088392+00:00 app[web.1]: #20 /app/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}(Object(Illuminate\\Http\\Request))
2019-08-27T11:45:42.088682+00:00 app[web.1]: #21 /app/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
2019-08-27T11:45:42.088959+00:00 app[web.1]: #22 /app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Fideloper\\Proxy\\TrustProxies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
2019-08-27T11:45:42.089251+00:00 app[web.1]: #23 /app/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
2019-08-27T11:45:42.089587+00:00 app[web.1]: #24 /app/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
2019-08-27T11:45:42.089927+00:00 app[web.1]: #25 /app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
2019-08-27T11:45:42.090234+00:00 app[web.1]: #26 /app/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
2019-08-27T11:45:42.090577+00:00 app[web.1]: #27 /app/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
2019-08-27T11:45:42.090918+00:00 app[web.1]: #28 /app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
2019-08-27T11:45:42.091220+00:00 app[web.1]: #29 /app/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
2019-08-27T11:45:42.091563+00:00 app[web.1]: #30 /app/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
2019-08-27T11:45:42.091899+00:00 app[web.1]: #31 /app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
2019-08-27T11:45:42.092217+00:00 app[web.1]: #32 /app/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
2019-08-27T11:45:42.092569+00:00 app[web.1]: #33 /app/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(62): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
2019-08-27T11:45:42.092932+00:00 app[web.1]: #34 /app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode->handle(Object(Illuminate\\Http\\Request), Object(Closure))
2019-08-27T11:45:42.093232+00:00 app[web.1]: #35 /app/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
2019-08-27T11:45:42.093493+00:00 app[web.1]: #36 /app/app/Http/Middleware/SecureHeaders.php(45): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
2019-08-27T11:45:42.093833+00:00 app[web.1]: #37 /app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): FireflyIII\\Http\\Middleware\\SecureHeaders->handle(Object(Illuminate\\Http\\Request), Object(Closure))
2019-08-27T11:45:42.094134+00:00 app[web.1]: #38 /app/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
2019-08-27T11:45:42.094439+00:00 app[web.1]: #39 /app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(104): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
2019-08-27T11:45:42.094678+00:00 app[web.1]: #40 /app/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(151): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
2019-08-27T11:45:42.094991+00:00 app[web.1]: #41 /app/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(116): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
2019-08-27T11:45:42.095192+00:00 app[web.1]: #42 /app/public/index.php(76): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
2019-08-27T11:45:42.095226+00:00 app[web.1]: #43 {main}
2019-08-27T11:45:42.095231+00:00 app[web.1]: "}
```

![Screenshot from 2019-08-27 06-50-09](https://user-images.githubusercontent.com/8903363/63768883-fd30e380-c896-11e9-9112-7003c160d7df.png)

**Steps to reproduce**
Fresh deploy to Heroku and try to make a transaction

**Expected behavior**
Transaction created

**Comment by JC5** [comment]
> It's something with the way Heroku runs its ephemeral file system. It used to be so "just" the API doesn't work. But Firefly III is increasingly relying on its own API.
> 
> I have no solution yet.

**Comment by jakubmilkowski** [comment]
Hello unfortunately I faced with the same issue while creating/cloning transaction:

`2019-09-11T07:01:15.574384+00:00 app[web.1]: [2019-09-11 07:01:15] heroku.ERROR: Key path "file:///app/storage/oauth-private.key" does not exist or is not readable {"exception":"[object] (LogicException(code: 0): Key path \"file:///app/storage/oauth-private.key\" does not exist or is not readable at /app/vendor/league/oauth2-server/src/CryptKey.php:48)`

I tried to restart all dynos but with no luck.

**Comment by scott-mcnulty** [comment]
I just tried with the [latest version](https://github.com/firefly-iii/firefly-iii/commit/d550a626e90e6307603d12fa36241fbc98bf0be3) to Heroku and I'm able to successfully create transactions now

**Comment by jakubmilkowski** [comment]
Hi Scott, thank you for answer. After setting up the fresh install of 4.8.1 release on Heroku I also was able to create/edit transactions, but it looks like it changed after around one day. I just checked and still I can't add new transaction (getting the same error).

**Comment by JC5** [comment]
A fix for some other issue will probably also fix this. I'm marking this as fixed but please open a new issue if problems persist.
