### ISSUE TITLE
Undefined index: type in YNAB import

### ISSUE THREAD

**Issue by mikl** [firefly-iii/firefly-iii#2592]
**Bug description**
I am running Firefly III version 4.8.1, and my problem is:

While trying to import data from YNAB, after selecting how to map the YNAB accounts to Firefly accounts, it works for a while, and then reports a fatal error.

**Steps to reproduce**

Set up import from YNAB via OAUTH, and start the import.

**Expected behavior**

The import should succeed.

**Extra info**
Using latest Firefox on macOS.

Firefly running on an Ubuntu 18.04 server with PHP 7.3

<details>
  <summary>Debug info</summary>

Debug information generated at 2019-09-12 21:49:02 Europe/Zurich for Firefly III version **4.8.1**.

| Variable | Content |
| --- | --- |
| FF version | 4.8.1 |
| FF API version | 0.10.2 |
| App environment | production |
| App debug mode | false |
| App cache driver | file |
| App logging | , daily |
| PHP version | 7.3.9-1+ubuntu18.04.1+deb.sury.org+1 |
| Display errors | Off |
| Session start | 2019-09-01 00:00:00 |
| Session end | 2019-09-30 23:59:59 |
| Session first | 2019-01-01 00:00:00 |
| Error reporting | ALL errors |
| Host | Linux |
| Interface | fpm-fcgi |
| UserID | 1 |
| Attempt at "en" | false |
| Attempt at "English" | false |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| DB drivers | mysql, pgsql |
| Current driver | pgsql |
| Login provider |   |
| Storage disks | local-upload  |
| Using Sandstorm? | no |
| Is Sandstorm (.env) | false |
| Is Docker (.env) | false |
| bunq uses sandbox | false |
| Trusted proxies (.env) |  |
| User agent | Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:70.0) Gecko/20100101 Firefox/70.0 |
| Loaded extensions | Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, sodium, session, standard, cgi-fcgi, mysqlnd, PDO, xml, apcu, bcmath, bz2, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, iconv, igbinary, intl, json, ldap, exif, mysqli, pdo_mysql, pdo_pgsql, pgsql, Phar, posix, readline, redis, shmop, SimpleXML, sockets, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xmlreader, xmlwriter, xsl, yaml, zip, Zend OPcache |

</details>

**Bonus points**

<details>
  <summary>Full stacktrace</summary>

```
[2019-09-12 21:33:44] production.ERROR: Undefined index: type {"userId":1,"exception":"[object] (ErrorException(code: 0): Undefined index: type at /srv/www/sites/ffy/ff-4.8.1/app/Import/Storage/ImportArrayStorage.php:116)
[stacktrace]
#0 /srv/www/sites/ffy/ff-4.8.1/app/Import/Storage/ImportArrayStorage.php(116): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError(8, 'Undefined index...', '/srv/www/sites/...', 116, Array)
#1 /srv/www/sites/ffy/ff-4.8.1/app/Import/Storage/ImportArrayStorage.php(86): FireflyIII\\Import\\Storage\\ImportArrayStorage->countTransfers()
#2 /srv/www/sites/ffy/ff-4.8.1/app/Support/Http/Controllers/CreateStuff.php(212): FireflyIII\\Import\\Storage\\ImportArrayStorage->setImportJob(Object(FireflyIII\\Models\\ImportJob))
#3 /srv/www/sites/ffy/ff-4.8.1/app/Http/Controllers/Import/JobStatusController.php(217): FireflyIII\\Http\\Controllers\\Import\\JobStatusController->storeTransactions(Object(FireflyIII\\Models\\ImportJob))
#4 [internal function]: FireflyIII\\Http\\Controllers\\Import\\JobStatusController->store(Object(FireflyIII\\Models\\ImportJob))
#5 /srv/www/sites/ffy/ff-4.8.1/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): call_user_func_array(Array, Array)
#6 /srv/www/sites/ffy/ff-4.8.1/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\\Routing\\Controller->callAction('store', Array)
#7 /srv/www/sites/ffy/ff-4.8.1/vendor/laravel/framework/src/Illuminate/Routing/Route.php(219): Illuminate\\Routing\\ControllerDispatcher->dispatch(Object(Illuminate\\Routing\\Route), Object(FireflyIII\\Http\\Controllers\\Import\\JobStatusController), 'store')
#8 /srv/www/sites/ffy/ff-4.8.1/vendor/laravel/framework/src/Illuminate/Routing/Route.php(176): Illuminate\\Routing\\Route->runController()
#9 /srv/www/sites/ffy/ff-4.8.1/vendor/laravel/framework/src/Illuminate/Routing/Router.php(680): Illuminate\\Routing\\Route->run()
#10 /srv/www/sites/ffy/ff-4.8.1/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#11 /srv/www/sites/ffy/ff-4.8.1/app/Http/Controllers/Import/JobStatusController.php(59): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#12 /srv/www/sites/ffy/ff-4.8.1/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(145): FireflyIII\\Http\\Controllers\\Import\\JobStatusController->FireflyIII\\Http\\Controllers\\Import\\{closure}(Object(Illuminate\\Http\\Request), Object(Closure))
#13 /srv/www/sites/ffy/ff-4.8.1/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#14 /srv/www/sites/ffy/ff-4.8.1/app/Http/Controllers/Controller.php(82): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#15 /srv/www/sites/ffy/ff-4.8.1/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(145): FireflyIII\\Http\\Controllers\\Controller->FireflyIII\\Http\\Controllers\\{closure}(Object(Illuminate\\Http\\Request), Object(Closure))
#16 /srv/www/sites/ffy/ff-4.8.1/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#17 /srv/www/sites/ffy/ff-4.8.1/app/Http/Middleware/InterestingMessage.php(58): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#18 /srv/www/sites/ffy/ff-4.8.1/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): FireflyIII\\Http\\Middleware\\InterestingMessage->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#19 /srv/www/sites/ffy/ff-4.8.1/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#20 /srv/www/sites/ffy/ff-4.8.1/app/Http/Middleware/Binder.php(78): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#21 /srv/www/sites/ffy/ff-4.8.1/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): FireflyIII\\Http\\Middleware\\Binder->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#22 /srv/www/sites/ffy/ff-4.8.1/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#23 /srv/www/sites/ffy/ff-4.8.1/app/Http/Middleware/Range.php(60): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#24 /srv/www/sites/ffy/ff-4.8.1/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): FireflyIII\\Http\\Middleware\\Range->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#25 /srv/www/sites/ffy/ff-4.8.1/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#26 /srv/www/sites/ffy/ff-4.8.1/vendor/pragmarx/google2fa-laravel/src/Middleware.php(15): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#27 /srv/www/sites/ffy/ff-4.8.1/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): PragmaRX\\Google2FALaravel\\Middleware->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#28 /srv/www/sites/ffy/ff-4.8.1/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#29 /srv/www/sites/ffy/ff-4.8.1/app/Http/Middleware/Authenticate.php(73): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#30 /srv/www/sites/ffy/ff-4.8.1/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): FireflyIII\\Http\\Middleware\\Authenticate->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#31 /srv/www/sites/ffy/ff-4.8.1/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#32 /srv/www/sites/ffy/ff-4.8.1/vendor/laravel/passport/src/Http/Middleware/CreateFreshApiToken.php(50): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#33 /srv/www/sites/ffy/ff-4.8.1/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Laravel\\Passport\\Http\\Middleware\\CreateFreshApiToken->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#34 /srv/www/sites/ffy/ff-4.8.1/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#35 /srv/www/sites/ffy/ff-4.8.1/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(75): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#36 /srv/www/sites/ffy/ff-4.8.1/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#37 /srv/www/sites/ffy/ff-4.8.1/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#38 /srv/www/sites/ffy/ff-4.8.1/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#39 /srv/www/sites/ffy/ff-4.8.1/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#40 /srv/www/sites/ffy/ff-4.8.1/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#41 /srv/www/sites/ffy/ff-4.8.1/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(56): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#42 /srv/www/sites/ffy/ff-4.8.1/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\\Session\\Middleware\\StartSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#43 /srv/www/sites/ffy/ff-4.8.1/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#44 /srv/www/sites/ffy/ff-4.8.1/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#45 /srv/www/sites/ffy/ff-4.8.1/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#46 /srv/www/sites/ffy/ff-4.8.1/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#47 /srv/www/sites/ffy/ff-4.8.1/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(66): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#48 /srv/www/sites/ffy/ff-4.8.1/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#49 /srv/www/sites/ffy/ff-4.8.1/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#50 /srv/www/sites/ffy/ff-4.8.1/app/Http/Middleware/Sandstorm.php(54): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#51 /srv/www/sites/ffy/ff-4.8.1/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): FireflyIII\\Http\\Middleware\\Sandstorm->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#52 /srv/www/sites/ffy/ff-4.8.1/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#53 /srv/www/sites/ffy/ff-4.8.1/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(104): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#54 /srv/www/sites/ffy/ff-4.8.1/vendor/laravel/framework/src/Illuminate/Routing/Router.php(682): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#55 /srv/www/sites/ffy/ff-4.8.1/vendor/laravel/framework/src/Illuminate/Routing/Router.php(657): Illuminate\\Routing\\Router->runRouteWithinStack(Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request))
#56 /srv/www/sites/ffy/ff-4.8.1/vendor/laravel/framework/src/Illuminate/Routing/Router.php(623): Illuminate\\Routing\\Router->runRoute(Object(Illuminate\\Http\\Request), Object(Illuminate\\Routing\\Route))
#57 /srv/www/sites/ffy/ff-4.8.1/vendor/laravel/framework/src/Illuminate/Routing/Router.php(612): Illuminate\\Routing\\Router->dispatchToRoute(Object(Illuminate\\Http\\Request))
#58 /srv/www/sites/ffy/ff-4.8.1/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(176): Illuminate\\Routing\\Router->dispatch(Object(Illuminate\\Http\\Request))
#59 /srv/www/sites/ffy/ff-4.8.1/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}(Object(Illuminate\\Http\\Request))
#60 /srv/www/sites/ffy/ff-4.8.1/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#61 /srv/www/sites/ffy/ff-4.8.1/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Fideloper\\Proxy\\TrustProxies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#62 /srv/www/sites/ffy/ff-4.8.1/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#63 /srv/www/sites/ffy/ff-4.8.1/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#64 /srv/www/sites/ffy/ff-4.8.1/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#65 /srv/www/sites/ffy/ff-4.8.1/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#66 /srv/www/sites/ffy/ff-4.8.1/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#67 /srv/www/sites/ffy/ff-4.8.1/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#68 /srv/www/sites/ffy/ff-4.8.1/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#69 /srv/www/sites/ffy/ff-4.8.1/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#70 /srv/www/sites/ffy/ff-4.8.1/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#71 /srv/www/sites/ffy/ff-4.8.1/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#72 /srv/www/sites/ffy/ff-4.8.1/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(62): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#73 /srv/www/sites/ffy/ff-4.8.1/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#74 /srv/www/sites/ffy/ff-4.8.1/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#75 /srv/www/sites/ffy/ff-4.8.1/app/Http/Middleware/SecureHeaders.php(45): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#76 /srv/www/sites/ffy/ff-4.8.1/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): FireflyIII\\Http\\Middleware\\SecureHeaders->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#77 /srv/www/sites/ffy/ff-4.8.1/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#78 /srv/www/sites/ffy/ff-4.8.1/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(104): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#79 /srv/www/sites/ffy/ff-4.8.1/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(151): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#80 /srv/www/sites/ffy/ff-4.8.1/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(116): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#81 /srv/www/sites/ffy/ff-4.8.1/public/index.php(76): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#82 {main}
"}
```
</details>

Let me know if I can do anything else to help debug this.

**Comment by mikl** [comment]
I applied your fix to my 4.8.1 installation, it now does get through the import stage, but I now get hundreds of errors like

```
Row #1294 ("(empty)") could not be imported. It already exists.
Row #1336 ("(empty)") could not be imported. It already exists.
Row #1414 ("Tatjanas ting, tilbagebetalt via Twist") could not be imported. It already exists.
Row #1475 ("EUR kontant") could not be imported. It already exists.
```

(The text in quotes is the content of the note field in YNAB).

That’s a little disconcerting, not sure if it’s related?

**Comment by mikl** [comment]
It looks very strange, my main checking account came out with a balance of -$140k (it has a positive balance in YNAB). I’ll try to get a copy going on a dev setup, so I can see where it went wrong.

**Comment by JC5** [comment]
There might not be much I can do, but let me know regardless.
