### ISSUE TITLE
Error when creating transaction - release 4.8.1.1

### ISSUE THREAD

**Issue by jakubmilkowski** [firefly-iii/firefly-iii#2654]
**Bug description**
I am running Firefly III version 4.8.1.1 and my problem is:
Right after deploying the newest release on Heroku Firefly worked perfectly but unfortunately after approximately 24 hours it throws an error while trying to create new withdrawal.

**Steps to reproduce**
Create new withdrawal. 

**Expected behavior**
New withdrawal successfully created.

**Extra info**
Related issue:
[#2504 ](https://github.com/firefly-iii/firefly-iii/issues/2504)

I tried it in mobile Chrome, Internet Explorer and Win10 Chrome (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.132 Safari/537.36)
Please find stack trace below:

```
2019-09-24T11:02:07.777948+00:00 app[web.1]: [2019-09-24 11:02:07] heroku.ERROR: Key path "file:///app/storage/oauth-public.key" does not exist or is not readable {"exception":"[object] (LogicException(code: 0): Key path \"file:///app/storage/oauth-public.key\" does not exist or is not readable at /app/vendor/league/oauth2-server/src/CryptKey.php:48)
2019-09-24T11:02:07.777971+00:00 app[web.1]: [stacktrace]
2019-09-24T11:02:07.778241+00:00 app[web.1]: #0 /app/vendor/laravel/passport/src/PassportServiceProvider.php(243): League\\OAuth2\\Server\\CryptKey->__construct('file:///app/sto...', NULL, false)
2019-09-24T11:02:07.778487+00:00 app[web.1]: #1 /app/vendor/laravel/passport/src/PassportServiceProvider.php(224): Laravel\\Passport\\PassportServiceProvider->makeCryptKey('public')
2019-09-24T11:02:07.778783+00:00 app[web.1]: #2 /app/vendor/laravel/framework/src/Illuminate/Container/Container.php(785): Laravel\\Passport\\PassportServiceProvider->Laravel\\Passport\\{closure}(Object(Illuminate\\Foundation\\Application), Array)
2019-09-24T11:02:07.778973+00:00 app[web.1]: #3 /app/vendor/laravel/framework/src/Illuminate/Container/Container.php(667): Illuminate\\Container\\Container->build(Object(Closure))
2019-09-24T11:02:07.779214+00:00 app[web.1]: #4 /app/vendor/laravel/framework/src/Illuminate/Container/Container.php(615): Illuminate\\Container\\Container->resolve('League\\\\OAuth2\\\\S...', Array)
2019-09-24T11:02:07.779432+00:00 app[web.1]: #5 /app/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(767): Illuminate\\Container\\Container->make('League\\\\OAuth2\\\\S...', Array)
2019-09-24T11:02:07.779632+00:00 app[web.1]: #6 /app/vendor/laravel/passport/src/PassportServiceProvider.php(270): Illuminate\\Foundation\\Application->make('League\\\\OAuth2\\\\S...')
2019-09-24T11:02:07.779841+00:00 app[web.1]: #7 [internal function]: Laravel\\Passport\\PassportServiceProvider->Laravel\\Passport\\{closure}(Object(Illuminate\\Http\\Request), NULL)
2019-09-24T11:02:07.780053+00:00 app[web.1]: #8 /app/vendor/laravel/framework/src/Illuminate/Auth/RequestGuard.php(58): call_user_func(Object(Closure), Object(Illuminate\\Http\\Request), NULL)
2019-09-24T11:02:07.780220+00:00 app[web.1]: #9 /app/vendor/laravel/framework/src/Illuminate/Auth/GuardHelpers.php(60): Illuminate\\Auth\\RequestGuard->user()
2019-09-24T11:02:07.780353+00:00 app[web.1]: #10 /app/app/Http/Middleware/Authenticate.php(128): Illuminate\\Auth\\RequestGuard->check()
2019-09-24T11:02:07.780567+00:00 app[web.1]: #11 /app/app/Http/Middleware/Authenticate.php(71): FireflyIII\\Http\\Middleware\\Authenticate->authenticate(Object(Illuminate\\Http\\Request), Array)
2019-09-24T11:02:07.780875+00:00 app[web.1]: #12 /app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): FireflyIII\\Http\\Middleware\\Authenticate->handle(Object(Illuminate\\Http\\Request), Object(Closure), 'api')
2019-09-24T11:02:07.781122+00:00 app[web.1]: #13 /app/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
2019-09-24T11:02:07.781369+00:00 app[web.1]: #14 /app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(104): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
2019-09-24T11:02:07.781554+00:00 app[web.1]: #15 /app/vendor/laravel/framework/src/Illuminate/Routing/Router.php(682): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
2019-09-24T11:02:07.781830+00:00 app[web.1]: #16 /app/vendor/laravel/framework/src/Illuminate/Routing/Router.php(657): Illuminate\\Routing\\Router->runRouteWithinStack(Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request))
2019-09-24T11:02:07.782089+00:00 app[web.1]: #17 /app/vendor/laravel/framework/src/Illuminate/Routing/Router.php(623): Illuminate\\Routing\\Router->runRoute(Object(Illuminate\\Http\\Request), Object(Illuminate\\Routing\\Route))
2019-09-24T11:02:07.782310+00:00 app[web.1]: #18 /app/vendor/laravel/framework/src/Illuminate/Routing/Router.php(612): Illuminate\\Routing\\Router->dispatchToRoute(Object(Illuminate\\Http\\Request))
2019-09-24T11:02:07.782532+00:00 app[web.1]: #19 /app/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(176): Illuminate\\Routing\\Router->dispatch(Object(Illuminate\\Http\\Request))
2019-09-24T11:02:07.782802+00:00 app[web.1]: #20 /app/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}(Object(Illuminate\\Http\\Request))
2019-09-24T11:02:07.783022+00:00 app[web.1]: #21 /app/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
2019-09-24T11:02:07.783312+00:00 app[web.1]: #22 /app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Fideloper\\Proxy\\TrustProxies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
2019-09-24T11:02:07.783629+00:00 app[web.1]: #23 /app/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
2019-09-24T11:02:07.784037+00:00 app[web.1]: #24 /app/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
2019-09-24T11:02:07.784304+00:00 app[web.1]: #25 /app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
2019-09-24T11:02:07.784561+00:00 app[web.1]: #26 /app/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
2019-09-24T11:02:07.784862+00:00 app[web.1]: #27 /app/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
2019-09-24T11:02:07.785139+00:00 app[web.1]: #28 /app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
2019-09-24T11:02:07.785389+00:00 app[web.1]: #29 /app/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
2019-09-24T11:02:07.785706+00:00 app[web.1]: #30 /app/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
2019-09-24T11:02:07.785985+00:00 app[web.1]: #31 /app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
2019-09-24T11:02:07.786233+00:00 app[web.1]: #32 /app/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
2019-09-24T11:02:07.786553+00:00 app[web.1]: #33 /app/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(62): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
2019-09-24T11:02:07.786852+00:00 app[web.1]: #34 /app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode->handle(Object(Illuminate\\Http\\Request), Object(Closure))
2019-09-24T11:02:07.787179+00:00 app[web.1]: #35 /app/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
2019-09-24T11:02:07.787460+00:00 app[web.1]: #36 /app/app/Http/Middleware/SecureHeaders.php(45): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
2019-09-24T11:02:07.787783+00:00 app[web.1]: #37 /app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): FireflyIII\\Http\\Middleware\\SecureHeaders->handle(Object(Illuminate\\Http\\Request), Object(Closure))
2019-09-24T11:02:07.788031+00:00 app[web.1]: #38 /app/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
2019-09-24T11:02:07.788282+00:00 app[web.1]: #39 /app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(104): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
2019-09-24T11:02:07.788478+00:00 app[web.1]: #40 /app/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(151): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
2019-09-24T11:02:07.788794+00:00 app[web.1]: #41 /app/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(116): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
2019-09-24T11:02:07.788954+00:00 app[web.1]: #42 /app/public/index.php(76): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
2019-09-24T11:02:07.788974+00:00 app[web.1]: #43 {main}
2019-09-24T11:02:07.788977+00:00 app[web.1]: "}
```
![2019-09-24_13-11-25](https://user-images.githubusercontent.com/11717602/65506933-054b6580-decd-11e9-91a2-a8f04f49c868.png)

**Comment by JC5** [comment]
https://github.com/firefly-iii/firefly-iii/issues/2504
