### ISSUE TITLE
Fatal error when importing transactions (md5_file() expects parameter 1 to be a valid path, bool given)

### ISSUE THREAD

**Issue by Moc** [firefly-iii/firefly-iii#2676]
**Bug description**
I am running Firefly III version 4.8.1.1 and my problem is that I receive a fatal error when trying to import transactions (ING Bank CSV with default.json config file). 

**Steps to reproduce**
See above. 

**Expected behavior**
I think this speaks for itself :) 

**Extra info**

Debug information generated at 2019-10-01 15:16:01 Europe/Amsterdam for Firefly III version **4.8.1.1**.

| Variable | Content |
| --- | --- |
| FF version | 4.8.1.1 |
| FF API version | 0.10.2 |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | , daily |
| PHP version | 7.3.9 |
| Display errors | Off |
| Session start | 2019-10-01 00:00:00 |
| Session end | 2019-10-31 23:59:59 |
| Session first | 2019-10-01 00:00:00 |
| Error reporting | ALL errors |
| Host | WINNT |
| Interface | cgi-fcgi |
| UserID | 1 |
| Attempt at "en" | 'en' |
| Attempt at "English" | 'English_United States.1252' |
| Attempt at "en_US.utf8" | false |
| Attempt at "en_US.UTF-8" | false |
| DB drivers | mysql |
| Current driver | mysql |
| Login provider |   |
| Storage disks | local-upload  |
| Using Sandstorm? | no |
| Is Sandstorm (.env) | false |
| Is Docker (.env) | false |
| bunq uses sandbox | false |
| Trusted proxies (.env) |  |
| User agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36 |
| Loaded extensions | Core, bcmath, calendar, ctype, date, filter, hash, iconv, json, SPL, pcre, readline, Reflection, session, standard, mysqlnd, tokenizer, zip, zlib, libxml, dom, PDO, openssl, SimpleXML, xml, wddx, xmlreader, xmlwriter, cgi-fcgi, curl, fileinfo, gd, intl, ldap, mbstring, exif, mysqli, Phar, pdo_mysql, xsl |

**Bonus points**
```
[2019-10-01 15:12:24] local.ERROR: Exception is: {"class":"Symfony\\Component\\Debug\\Exception\\FatalThrowableError","errorMessage":"md5_file() expects parameter 1 to be a valid path, bool given","time":"Tue, 01 Oct 2019 15:12:24 +0200","file":"C:\\webdev\\www\\firefly\\app\\Repositories\\ImportJob\\ImportJobRepository.php","line":432,"code":0,"version":"4.8.1.1","url":"http:\/\/localhost\/firefly\/public\/import\/job\/configuration\/vLrTX8yoyref","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/77.0.3865.90 Safari\/537.36","json":true}  
[2019-10-01 15:12:24] local.ERROR: md5_file() expects parameter 1 to be a valid path, bool given {"userId":1,"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): md5_file() expects parameter 1 to be a valid path, bool given at C:\\webdev\\www\\firefly\\app\\Repositories\\ImportJob\\ImportJobRepository.php:432)
[stacktrace]
#0 C:\\webdev\\www\\firefly\\app\\Repositories\\ImportJob\\ImportJobRepository.php(432): md5_file(false)
#1 C:\\webdev\\www\\firefly\\app\\Http\\Controllers\\Import\\JobConfigurationController.php(147): FireflyIII\\Repositories\\ImportJob\\ImportJobRepository->storeFileUpload(Object(FireflyIII\\Models\\ImportJob), 'import_file', Object(Illuminate\\Http\\UploadedFile))
#2 [internal function]: FireflyIII\\Http\\Controllers\\Import\\JobConfigurationController->post(Object(Illuminate\\Http\\Request), Object(FireflyIII\\Models\\ImportJob))
#3 C:\\webdev\\www\\firefly\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Controller.php(54): call_user_func_array(Array, Array)
#4 C:\\webdev\\www\\firefly\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\ControllerDispatcher.php(45): Illuminate\\Routing\\Controller->callAction('post', Array)
#5 C:\\webdev\\www\\firefly\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Route.php(219): Illuminate\\Routing\\ControllerDispatcher->dispatch(Object(Illuminate\\Routing\\Route), Object(FireflyIII\\Http\\Controllers\\Import\\JobConfigurationController), 'post')
#6 C:\\webdev\\www\\firefly\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Route.php(176): Illuminate\\Routing\\Route->runController()
#7 C:\\webdev\\www\\firefly\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(680): Illuminate\\Routing\\Route->run()
#8 C:\\webdev\\www\\firefly\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php(30): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#9 C:\\webdev\\www\\firefly\\app\\Http\\Controllers\\Import\\JobConfigurationController.php(57): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#10 C:\\webdev\\www\\firefly\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(145): FireflyIII\\Http\\Controllers\\Import\\JobConfigurationController->FireflyIII\\Http\\Controllers\\Import\\{closure}(Object(Illuminate\\Http\\Request), Object(Closure))
#11 C:\\webdev\\www\\firefly\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#12 C:\\webdev\\www\\firefly\\app\\Http\\Controllers\\Controller.php(82): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#13 C:\\webdev\\www\\firefly\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(145): FireflyIII\\Http\\Controllers\\Controller->FireflyIII\\Http\\Controllers\\{closure}(Object(Illuminate\\Http\\Request), Object(Closure))
#14 C:\\webdev\\www\\firefly\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#15 C:\\webdev\\www\\firefly\\app\\Http\\Middleware\\InterestingMessage.php(58): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#16 C:\\webdev\\www\\firefly\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(163): FireflyIII\\Http\\Middleware\\InterestingMessage->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#17 C:\\webdev\\www\\firefly\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#18 C:\\webdev\\www\\firefly\\app\\Http\\Middleware\\Binder.php(78): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#19 C:\\webdev\\www\\firefly\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(163): FireflyIII\\Http\\Middleware\\Binder->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#20 C:\\webdev\\www\\firefly\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#21 C:\\webdev\\www\\firefly\\app\\Http\\Middleware\\Range.php(60): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#22 C:\\webdev\\www\\firefly\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(163): FireflyIII\\Http\\Middleware\\Range->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#23 C:\\webdev\\www\\firefly\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#24 C:\\webdev\\www\\firefly\\vendor\\pragmarx\\google2fa-laravel\\src\\Middleware.php(15): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#25 C:\\webdev\\www\\firefly\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(163): PragmaRX\\Google2FALaravel\\Middleware->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#26 C:\\webdev\\www\\firefly\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#27 C:\\webdev\\www\\firefly\\app\\Http\\Middleware\\Authenticate.php(73): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#28 C:\\webdev\\www\\firefly\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(163): FireflyIII\\Http\\Middleware\\Authenticate->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#29 C:\\webdev\\www\\firefly\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#30 C:\\webdev\\www\\firefly\\vendor\\laravel\\passport\\src\\Http\\Middleware\\CreateFreshApiToken.php(50): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#31 C:\\webdev\\www\\firefly\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(163): Laravel\\Passport\\Http\\Middleware\\CreateFreshApiToken->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#32 C:\\webdev\\www\\firefly\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#33 C:\\webdev\\www\\firefly\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken.php(75): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#34 C:\\webdev\\www\\firefly\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(163): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#35 C:\\webdev\\www\\firefly\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#36 C:\\webdev\\www\\firefly\\vendor\\laravel\\framework\\src\\Illuminate\\View\\Middleware\\ShareErrorsFromSession.php(49): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#37 C:\\webdev\\www\\firefly\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(163): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#38 C:\\webdev\\www\\firefly\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#39 C:\\webdev\\www\\firefly\\vendor\\laravel\\framework\\src\\Illuminate\\Session\\Middleware\\StartSession.php(56): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#40 C:\\webdev\\www\\firefly\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(163): Illuminate\\Session\\Middleware\\StartSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#41 C:\\webdev\\www\\firefly\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#42 C:\\webdev\\www\\firefly\\vendor\\laravel\\framework\\src\\Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse.php(37): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#43 C:\\webdev\\www\\firefly\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(163): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#44 C:\\webdev\\www\\firefly\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#45 C:\\webdev\\www\\firefly\\vendor\\laravel\\framework\\src\\Illuminate\\Cookie\\Middleware\\EncryptCookies.php(66): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#46 C:\\webdev\\www\\firefly\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(163): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#47 C:\\webdev\\www\\firefly\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#48 C:\\webdev\\www\\firefly\\app\\Http\\Middleware\\Sandstorm.php(54): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#49 C:\\webdev\\www\\firefly\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(163): FireflyIII\\Http\\Middleware\\Sandstorm->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#50 C:\\webdev\\www\\firefly\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#51 C:\\webdev\\www\\firefly\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(104): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#52 C:\\webdev\\www\\firefly\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(682): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#53 C:\\webdev\\www\\firefly\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(657): Illuminate\\Routing\\Router->runRouteWithinStack(Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request))
#54 C:\\webdev\\www\\firefly\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(623): Illuminate\\Routing\\Router->runRoute(Object(Illuminate\\Http\\Request), Object(Illuminate\\Routing\\Route))
#55 C:\\webdev\\www\\firefly\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(612): Illuminate\\Routing\\Router->dispatchToRoute(Object(Illuminate\\Http\\Request))
#56 C:\\webdev\\www\\firefly\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Kernel.php(176): Illuminate\\Routing\\Router->dispatch(Object(Illuminate\\Http\\Request))
#57 C:\\webdev\\www\\firefly\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php(30): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}(Object(Illuminate\\Http\\Request))
#58 C:\\webdev\\www\\firefly\\vendor\\fideloper\\proxy\\src\\TrustProxies.php(57): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#59 C:\\webdev\\www\\firefly\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(163): Fideloper\\Proxy\\TrustProxies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#60 C:\\webdev\\www\\firefly\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#61 C:\\webdev\\www\\firefly\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest.php(21): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#62 C:\\webdev\\www\\firefly\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(163): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#63 C:\\webdev\\www\\firefly\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#64 C:\\webdev\\www\\firefly\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest.php(21): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#65 C:\\webdev\\www\\firefly\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(163): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#66 C:\\webdev\\www\\firefly\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#67 C:\\webdev\\www\\firefly\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize.php(27): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#68 C:\\webdev\\www\\firefly\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(163): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#69 C:\\webdev\\www\\firefly\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#70 C:\\webdev\\www\\firefly\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode.php(62): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#71 C:\\webdev\\www\\firefly\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(163): Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#72 C:\\webdev\\www\\firefly\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#73 C:\\webdev\\www\\firefly\\app\\Http\\Middleware\\SecureHeaders.php(45): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#74 C:\\webdev\\www\\firefly\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(163): FireflyIII\\Http\\Middleware\\SecureHeaders->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#75 C:\\webdev\\www\\firefly\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#76 C:\\webdev\\www\\firefly\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(104): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#77 C:\\webdev\\www\\firefly\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Kernel.php(151): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#78 C:\\webdev\\www\\firefly\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Kernel.php(116): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#79 C:\\webdev\\www\\firefly\\public\\index.php(76): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#80 {main}
"} 
```

**Comment by JC5** [comment]
Something probably went wrong with the file upload. I'm not sure what the cause is; running PHP on Windows doesn't always work perfectly well.

**Comment by Moc** [comment]
Yeah I understand that. This was working fine on a previous version of Firefly however... 
Is there anything else I can test?

**Comment by JC5** [comment]
Nothing changed in that part of the code I'm afraid. Are the write permissions OK?

**Comment by Moc** [comment]
Yes, it's a localhost installation with full permissions. I don't see anything that could interfere permissions wise. Shouldn't it throw some error somewhere if wouldn't be able to place the file?

**Comment by JC5** [comment]
Yes, which is why it's weird it crashes at this point. The method that returns false is `getRealPath()`, which only happens when the file no longer exists.

You could try to run `var_dump($file->getRealPath());exit;` and see what the path is. Does the file exist?

**Comment by Moc** [comment]
Returns `bool(false)`

**Comment by Moc** [comment]
Ok found it. It was indeed an issue with the write permissions, sorry. 
`C:/Windows/Temp` was not accessible for my logged in user.

**Comment by JC5** [comment]
No problem, glad it's fixed!
