### ISSUE TITLE
Non-numeric value encountered on 2FA login v4.8.1.5

### ISSUE THREAD

**Issue by dealanis** [firefly-iii/firefly-iii#2757]
**Bug description**
I am running Firefly III version 4.8.1.5, and my problem is:

After migrating to new version and logging in the 2FA authorization process fails to finish with exception "A non-numeric value encountered". Tried with the recommended deletion of preferences rows and "php artisan ca:cl" without success. Firefly keeps asking for authorization code even if rows are deleted and php artisan clear cache executed. Also tried with another explorer, remove and restart container.

**Steps to reproduce**
Have 2FA on.
Migrate to firefly 4.8.1.5 using docker.
Login and introduce auth code.
Error: A non-numeric value encountered.

**Extra info**
Rolled back to 4.8.1.4 version and 2FA is still requested but after input firefly logins correctly. Even if preferences rows are deleted, I suppose there is a new extra step to properly disable 2FA on recent versions.

EDIT further testing: Disabled 2FA on 4.8.1.4, and updated again to 4.8.1.5 and had success logging in, then reactivated 2FA succesfully but on the second code (after configuring) it fails with same error as reported before.

Thanks again for your great work!

**Bonus points**

Firefly III v4.8.1.5 ran into an error: A non-numeric value encountered.

The error was of type "ErrorException".

This error occured in file "/var/www/firefly-iii/vendor/pragmarx/google2fa/src/Google2FA.php" on line 232 with code 0.

URL is: https://<firefly>/two-factor/submit
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.120 Safari/537.36

```
> The full stacktrace is below:
> #0 /var/www/firefly-iii/vendor/pragmarx/google2fa/src/Google2FA.php(232): Illuminate\Foundation\Bootstrap\HandleExceptions-&gt;handleE$
> #1 /var/www/firefly-iii/vendor/pragmarx/google2fa/src/Google2FA.php(451): PragmaRX\Google2FA\Google2FA-&gt;makeStartingTimestamp(1, 52$
> #2 /var/www/firefly-iii/vendor/pragmarx/google2fa-laravel/src/Google2FA.php(264): PragmaRX\Google2FA\Google2FA-&gt;verifyKey(&#039;QCH$
> #3 /var/www/firefly-iii/vendor/pragmarx/google2fa-laravel/src/Google2FA.php(279): PragmaRX\Google2FALaravel\Google2FA-&gt;verifyGoogle$
> #4 /var/www/firefly-iii/vendor/pragmarx/google2fa-laravel/src/Support/Authenticator.php(150): PragmaRX\Google2FALaravel\Google2FA-&gt;$
> #5 /var/www/firefly-iii/vendor/pragmarx/google2fa-laravel/src/Support/Authenticator.php(134): PragmaRX\Google2FALaravel\Support\Authen$
> #6 /var/www/firefly-iii/vendor/pragmarx/google2fa-laravel/src/Support/Authenticator.php(106): PragmaRX\Google2FALaravel\Support\Authen$
> #7 /var/www/firefly-iii/app/Http/Controllers/Auth/TwoFactorController.php(62): PragmaRX\Google2FALaravel\Support\Authenticator-&gt;isA$
> #8 [internal function]: FireflyIII\Http\Controllers\Auth\TwoFactorController-&gt;submitMFA(Object(Illuminate\Http\Request))
> #9 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): call_user_func_array(Array, Array)
> #10 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\Routing\Controller-&$
> #11 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Routing/Route.php(219): Illuminate\Routing\ControllerDispatcher-&gt;d$
> #12 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Routing/Route.php(176): Illuminate\Routing\Route-&gt;runController()
> #13 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Routing/Router.php(680): Illuminate\Routing\Route-&gt;run()
> #14 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\Routing\Router-&gt;Illuminate\Ro$
> #15 /var/www/firefly-iii/app/Http/Controllers/Controller.php(82): Illuminate\Routing\Pipeline-&gt;Illuminate\Routing\{closure}(Object($
> #16 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(145): FireflyIII\Http\Controllers\Controller-&g$
> #17 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline-&gt;Illuminate$
> #18 /var/www/firefly-iii/app/Http/Middleware/Binder.php(78): Illuminate\Routing\Pipeline-&gt;Illuminate\Routing\{closure}(Object(Illum$
> #19 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): FireflyIII\Http\Middleware\Binder-&gt;han$
> #20 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline-&gt;Illuminate$
> #21 /var/www/firefly-iii/app/Http/Middleware/Authenticate.php(73): Illuminate\Routing\Pipeline-&gt;Illuminate\Routing\{closure}(Object$
> #22 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): FireflyIII\Http\Middleware\Authenticate-&$
> #23 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline-&gt;Illuminate$
> #24 /var/www/firefly-iii/app/Http/Middleware/Installer.php(80): Illuminate\Routing\Pipeline-&gt;Illuminate\Routing\{closure}(Object(Il$
> #25 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): FireflyIII\Http\Middleware\Installer-&gt;$
> #26 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline-&gt;Illuminate$
> #27 /var/www/firefly-iii/vendor/laravel/passport/src/Http/Middleware/CreateFreshApiToken.php(50): Illuminate\Routing\Pipeline-&gt;Illu$
> #28 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Laravel\Passport\Http\Middleware\CreateFr$
> #29 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline-&gt;Illuminate$
> #30 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(75): Illuminate\Routin$
> #31 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\Foundation\Http\Middleware\Ver$
> #32 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline-&gt;Illuminate$
> #33 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\Routing\Pi$
> #34 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\View\Middleware\ShareErrorsFro$
> #35 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline-&gt;Illuminate$
> #36 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(56): Illuminate\Routing\Pipeline-$
> #37 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\Session\Middleware\StartSessio$
> #38 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline-&gt;Illuminate$
> #39 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\Rout$
> #40 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\Cookie\Middleware\AddQueuedCoo$
> #41 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline-&gt;Illuminate$
> #42 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(66): Illuminate\Routing\Pipeline$
> #43 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\Cookie\Middleware\EncryptCooki$
> #44 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline-&gt;Illuminate$
> #45 /var/www/firefly-iii/app/Http/Middleware/Sandstorm.php(54): Illuminate\Routing\Pipeline-&gt;Illuminate\Routing\{closure}(Object(Il$
> #46 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): FireflyIII\Http\Middleware\Sandstorm-&gt;$
> #47 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline-&gt;Illuminate$
> #48 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(104): Illuminate\Routing\Pipeline-&gt;Illuminat$
> #49 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Routing/Router.php(682): Illuminate\Pipeline\Pipeline-&gt;then(Object$
> #50 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Routing/Router.php(657): Illuminate\Routing\Router-&gt;runRouteWithin$
> #51 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Routing/Router.php(623): Illuminate\Routing\Router-&gt;runRoute(Objec$
> #52 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Routing/Router.php(612): Illuminate\Routing\Router-&gt;dispatchToRout$
> #53 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(176): Illuminate\Routing\Router-&gt;dispat$
> #54 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\Foundation\Http\Kernel-&gt;Illum$
> #55 /var/www/firefly-iii/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\Routing\Pipeline-&gt;Illuminate\Routing\{closure}$
> #56 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Fideloper\Proxy\TrustProxies-&gt;handle(O$
> #57 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline-&gt;Illuminate$
> #58 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\Rout$
> #59 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\Foundation\Http\Middleware\Tra$
> #60 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline-&gt;Illuminate$
> #61 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\Rout$
> #62 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\Foundation\Http\Middleware\Tra$
> #63 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline-&gt;Illuminate$
> #64 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\Routi$
> #65 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\Foundation\Http\Middleware\Val$
> #66 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline-&gt;Illuminate$
> #67 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(62): Illuminat$
> #68 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\Foundation\Http\Middleware\Che$
> #69 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline-&gt;Illuminate$
> #70 /var/www/firefly-iii/app/Http/Middleware/SecureHeaders.php(45): Illuminate\Routing\Pipeline-&gt;Illuminate\Routing\{closure}(Objec$
> #71 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): FireflyIII\Http\Middleware\SecureHeaders-$
> #72 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline-&gt;Illuminate$
> #73 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(104): Illuminate\Routing\Pipeline-&gt;Illuminat$
> #74 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(151): Illuminate\Pipeline\Pipeline-&gt;the$
> #75 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(116): Illuminate\Foundation\Http\Kernel-&g$
> #76 /var/www/firefly-iii/public/index.php(76): Illuminate\Foundation\Http\Kernel-&gt;handle(Object(Illuminate\Http\Request))
> #77 {main}
```

**Comment by JC5** [comment]
Yes, this is an issue introduced in one of the packages I use. I hoped an upgrade would fix it but apparently the fix is only applied to a specific version of the package. I've updated the develop branch and it will go live before the weekend.

In the meantime, disable 2FA to use Firefly III.

**Comment by dealanis** [comment]
Great! yeah will do that. Thanks!! :D

**Comment by JC5** [comment]
No worries, sorry for messing up. I'm keeping this issue open just in case other people ask the same thing :)

**Comment by aronwk-aaron** [comment]
Also seeing thisexact issue on 4.8.1.5 . Waiting for new release to be cut. Thanks!

**Comment by CrackerFormula** [comment]
in docker jc5x/firefly-iii:latest how would one roll back to 4.8.1.4. first time needing to do this.
