### ISSUE TITLE
Database creation error with docker

### ISSUE THREAD

**Issue by TheObserver6995** [firefly-iii/firefly-iii#2915]
**Bug description**
I am running Firefly III version 4.8.2 (stable) and my problem is:
When installing firefly via docker, the database does not seem to get created:
Head of the log:
```
firefly-iii      | Now in entrypoint.sh for Firefly III
firefly-iii      | Making directories...
firefly-iii      | Touch DB file (if SQLlite)...
firefly-iii      | Run chown on /var/www/firefly-iii/storage...
firefly-iii      | Run chmod on /var/www/firefly-iii/storage...
firefly-iii      | Remove log file...
firefly-iii      | Dump auto load...
firefly-iii      | Generating optimized autoload files> Illuminate\Foundation\ComposerScripts::postAutoloadDump
Generated optimized autoload files containing 5053 classes
firefly-iii      | Discover packages...
firefly-iii      | Discovered Package: adldap2/adldap2-laravel
firefly-iii      | Discovered Package: danhunsaker/laravel-flysystem-others
firefly-iii      | Discovered Package: davejamesmiller/laravel-breadcrumbs
firefly-iii      | Discovered Package: fideloper/proxy
firefly-iii      | Discovered Package: laravel/passport
firefly-iii      | Discovered Package: laravelcollective/html
firefly-iii      | Discovered Package: nesbot/carbon
firefly-iii      | Discovered Package: pragmarx/google2fa-laravel
firefly-iii      | Discovered Package: rcrowe/twigbridge
firefly-iii      | Package manifest generated successfully.
firefly-iii      | Run various artisan commands...
firefly-iii      | wait-for-it.sh: waiting 15 seconds for postgres:5432
firefly-iii      | wait-for-it.sh: postgres:5432 is available after 0 seconds
firefly-iii      | db is up. Time to execute artisan commands
firefly-iii      | Application cache cleared!
firefly-iii      | This command currently applies to MySQL connections only.
firefly-iii      | Error when connecting to DB: SQLSTATE[HY000] [2002] Connection refused
firefly-iii      | **************************************
firefly-iii      | *     Application In Production!     *
firefly-iii      | **************************************
firefly-iii      | 
firefly-iii      | Command Cancelled!
firefly-iii      | Going to decrypt the database.
firefly-iii      | [2019-12-26 10:36:59] production.ERROR: SQLSTATE[42P01]: Undefined table: 7 FEHLER:  Relation »configuration« existiert nicht
firefly-iii      | LINE 1: select "id", "name", "data" from "configuration" where "name...
firefly-iii      |                                          ^ (SQL: select "id", "name", "data" from "configuration" where "name" = is_decrypted_accounts and "configuration"."deleted_at" is null limit 1) {"exception":"[object] (Illuminate\\Database\\QueryException(code: 42P01): SQLSTATE[42P01]: Undefined table: 7 FEHLER:  Relation »configuration« existiert nicht
firefly-iii      | LINE 1: select \"id\", \"name\", \"data\" from \"configuration\" where \"name...
firefly-iii      |                                          ^ (SQL: select \"id\", \"name\", \"data\" from \"configuration\" where \"name\" = is_decrypted_accounts and \"configuration\".\"deleted_at\" is null limit 1) at /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Database/Connection.php:664, Doctrine\\DBAL\\Driver\\PDOException(code: 42P01): SQLSTATE[42P01]: Undefined table: 7 FEHLER:  Relation »configuration« existiert nicht
firefly-iii      | LINE 1: select \"id\", \"name\", \"data\" from \"configuration\" where \"name...
firefly-iii      |                                          ^ at /var/www/firefly-iii/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:123, PDOException(code: 42P01): SQLSTATE[42P01]: Undefined table: 7 FEHLER:  Relation »configuration« existiert nicht
firefly-iii      | LINE 1: select \"id\", \"name\", \"data\" from \"configuration\" where \"name...
firefly-iii      |                                          ^ at /var/www/firefly-iii/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:121)
firefly-iii      | [stacktrace]
firefly-iii      | #0 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Database/Connection.php(624): Illuminate\\Database\\Connection->runQueryCallback('select \"id\", \"n...', Array, Object(Closure))
firefly-iii      | #1 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Database/Connection.php(333): Illuminate\\Database\\Connection->run('select \"id\", \"n...', Array, Object(Closure))
firefly-iii      | #2 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2130): Illuminate\\Database\\Connection->select('select \"id\", \"n...', Array, true)
firefly-iii      | #3 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2118): Illuminate\\Database\\Query\\Builder->runSelect()
firefly-iii      | #4 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2604): Illuminate\\Database\\Query\\Builder->Illuminate\\Database\\Query\\{closure}()
firefly-iii      | #5 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2119): Illuminate\\Database\\Query\\Builder->onceWithColumns(Array, Object(Closure))
firefly-iii      | #6 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(521): Illuminate\\Database\\Query\\Builder->get(Array)
firefly-iii      | #7 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(505): Illuminate\\Database\\Eloquent\\Builder->getModels(Array)
firefly-iii      | #8 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Database/Concerns/BuildsQueries.php(77): Illuminate\\Database\\Eloquent\\Builder->get(Array)
firefly-iii      | #9 /var/www/firefly-iii/app/Support/FireflyConfig.php(83): Illuminate\\Database\\Eloquent\\Builder->first(Array)
firefly-iii      | #10 /var/www/firefly-iii/app/Console/Commands/DecryptDatabase.php(132): FireflyIII\\Support\\FireflyConfig->get('is_decrypted_ac...', false)
firefly-iii      | #11 /var/www/firefly-iii/app/Console/Commands/DecryptDatabase.php(78): FireflyIII\\Console\\Commands\\DecryptDatabase->isDecrypted('accounts')
firefly-iii      | #12 [internal function]: FireflyIII\\Console\\Commands\\DecryptDatabase->handle()
firefly-iii      | #13 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(32): call_user_func_array(Array, Array)
firefly-iii      | #14 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(90): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
firefly-iii      | #15 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(34): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
firefly-iii      | #16 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Container/Container.php(576): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
firefly-iii      | #17 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Console/Command.php(183): Illuminate\\Container\\Container->call(Array)
firefly-iii      | #18 /var/www/firefly-iii/vendor/symfony/console/Command/Command.php(255): Illuminate\\Console\\Command->execute(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
firefly-iii      | #19 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Console/Command.php(170): Symfony\\Component\\Console\\Command\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
firefly-iii      | #20 /var/www/firefly-iii/vendor/symfony/console/Application.php(1011): Illuminate\\Console\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
firefly-iii      | #21 /var/www/firefly-iii/vendor/symfony/console/Application.php(272): Symfony\\Component\\Console\\Application->doRunCommand(Object(FireflyIII\\Console\\Commands\\DecryptDatabase), Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
firefly-iii      | #22 /var/www/firefly-iii/vendor/symfony/console/Application.php(148): Symfony\\Component\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
firefly-iii      | #23 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Console/Application.php(90): Symfony\\Component\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
firefly-iii      | #24 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(133): Illuminate\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
firefly-iii      | #25 /var/www/firefly-iii/artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
firefly-iii      | #26 {main}
firefly-iii      | "} 
firefly-iii      | 
firefly-iii      | In Connection.php line 664:
firefly-iii      |                                                                                
firefly-iii      |   SQLSTATE[42P01]: Undefined table: 7 FEHLER:  Relation »configuration« exist  
firefly-iii      |   iert nicht                                                                   
firefly-iii      |   LINE 1: select "id", "name", "data" from "configuration" where "name...      
firefly-iii      |                                            ^ (SQL: select "id", "name", "data  
firefly-iii      |   " from "configuration" where "name" = is_decrypted_accounts and "configurat  
firefly-iii      |   ion"."deleted_at" is null limit 1)                                           
firefly-iii      |                                                                                
firefly-iii      | 
firefly-iii      | In PDOStatement.php line 123:
firefly-iii      |                                                                                
firefly-iii      |   SQLSTATE[42P01]: Undefined table: 7 FEHLER:  Relation »configuration« exist  
firefly-iii      |   iert nicht                                                                   
firefly-iii      |   LINE 1: select "id", "name", "data" from "configuration" where "name...      
firefly-iii      |                                            ^                                   
firefly-iii      |                                                                                
firefly-iii      | 
firefly-iii      | In PDOStatement.php line 121:
firefly-iii      |                                                                                
firefly-iii      |   SQLSTATE[42P01]: Undefined table: 7 FEHLER:  Relation »configuration« exist  
firefly-iii      |   iert nicht                                                                   
firefly-iii      |   LINE 1: select "id", "name", "data" from "configuration" where "name...      
firefly-iii      |                                            ^                                   
firefly-iii      |                                                                                
firefly-iii      | 
firefly-iii      | [2019-12-26 10:36:59] production.ERROR: SQLSTATE[42P01]: Undefined table: 7 FEHLER:  Relation »configuration« existiert nicht
```

At the beginning firefly says "connection refused" and afterwards "command canceled", but in the postgresql log, no failed connection attempt gets logged. The errors afterwards "Undefined table", get logged in postgresql, so the connection *can* be established.

The log is in german, but i assume you can understand it anyway. "FEHLER:  Relation »configuration« existiert nicht" translates to "ERROR: Relation »configuration« does not exist".

Dockerfile:
```
FROM jc5x/firefly-iii:stable AS firefly-iii
EXPOSE 80
ENV APP_ENV=production
ENV APP_DEBUG=false
ENV SITE_OWNER=mail@example.com
ENV TZ=Europe/Berlin
ENV APP_URL=https://firefly.example.com
ENV TRUSTED_PROXIES=**
ENV LOG_CHANNEL=docker_out
ENV APP_LOG_LEVEL=notice
ENV APP_KEY=appKey
ENV DB_CONNECTION=pgsql
ENV DB_HOST=postgres
ENV DB_PORT=5432
ENV DB_DATABASE=firefly-iii
ENV DB_USERNAME=firefly-iii
ENV DB_PASSWORD=DBPW
ENV LOGIN_PROVIDER=ldap
ENV ADLDAP_CONNECTION_SCHEME=OpenLDAP
ENV ADLDAP_AUTO_CONNECT=true
ENV ADLDAP_CONTROLLERS=openldap
ENV ADLDAP_TIMEOUT=5
ENV ADLDAP_FOLLOW_REFFERALS=false
ENV ADLDAP_PORT=636
ENV ADLDAP_USE_TLS=true
ENV ADLDAP_BASEDN=BaseDN
ENV ADLDAP_ADMIN_USERNAME=firefly-iii
ENV ADLDAP_ADMIN_PASSWORD=AdminPW
ENV ADLDAP_DISCOVER_FIELD="uid"
ENV ADLDAP_AUTH_FIELD="uid"
ENV ADLDAP_SYNC_FIELD="uid"
```

**Steps to reproduce**
Installing firefly via docker.

**Extra info**
The problem can be solved by running "docker exec firefly-iii php artisan migrate:refresh --seed --force". Afterwards the Web interface is accessible.

Completely deleting the Database, container and all volumes did not solve the problem.

-->

**Comment by JC5** [comment]
Leave `APP_ENV` on `local` and try again. Firefly III won't create the database for you.

**Comment by TheObserver6995** [comment]
Changing APP_ENV to locale did not solve the problem. Of course, I deleted the database,  created a new one (empty), and deleted the container before I tried it.

**Comment by JC5** [comment]
Indeed. Are you still getting “connection refused” errors in your log files?

**Comment by TheObserver6995** [comment]
Yes, with your proposed solution, there is still one connection refused error, and a bunch of Undefined Table ... errors afterwards.

As already mentioned, manually running "docker exec firefly-iii php artisan migrate:refresh --seed --force" does solve the problem, so I cannot understand how this could be an configuration error.

**Comment by JC5** [comment]
Neither can I, there’s practically no difference between doing it yourself and letting the script do it. Especially since the wait-for-it script should verify the connection’s there. 

I’m sorry it doesn’t work as expected. I did add some debug info for the next release, and I hope it’ll make a bit more clear what’s going on.

**Comment by TheObserver6995** [comment]
Thanks for your help anyway. There is a workaround available, so it isn't that much of an problem for me.

As soon as the new release is available on dockerhub, i'll happily try it out and paste you the log if you wish to. Just give me a ping in this issue, so I don't forget it.

**Comment by JC5** [comment]
Will do. The bot will auto close this one, but I’ll keep an eye open.
