### ISSUE TITLE
cli export-data - invalid access token

### ISSUE THREAD

**Issue by tribly** [firefly-iii/firefly-iii#2980]
I am running Firefly III version 5.0.0-beta.1

**Description**
Updated to the newest beta to use the cli export utility but the ouput i get is `Invalid access token.` after running any `export-data` command, e.g. `php artisan firefly-iii:export-data --export-accounts`

**Log**
```
[2020-01-09 13:08:15] local.ERROR: Invalid access token for user #1.    
[2020-01-09 13:08:15] local.ERROR: Token given is "", expected something else.
```

**Comment by JC5** [comment]
Go to your profile for your token.

**Comment by JC5** [comment]
Check out `php artisan help firefly-iii:export-data` for more details.

**Comment by tribly** [comment]
Is there any other way to get the token except going to the profile? I still can't get permissions right (https://github.com/firefly-iii/firefly-iii/issues/2970).

**Comment by JC5** [comment]
It might be in your preference table, under `access_token`, but for the life of me I can't remember if it's encrypted or not.

**Comment by tribly** [comment]
Found the token and it was not encrypted. But now I'm getting the following error:
```
[2020-01-10 11:48:56] local.ERROR: Exception is: {"class":"Symfony\\Component\\Debug\\Exception\\FatalThrowableError","errorMessage":"Return value of FireflyIII\\Console\\Commands\\Export\\ExportData::getDateParameter() must be an instance of Carbon\\Carbon, null returned","time":"Fri, 10 Jan 2020 11:48:56 +0100","file":"\/usr\/share\/webapps\/firefly-iii\/app\/Console\/Commands\/Export\/ExportData.php","line":238,"code":0,"version":"5.0.0-alpha.2","url":"https:\/\/f.tribly.de","userAgent":"Symfony","json":true}  
[2020-01-10 11:48:56] local.ERROR: Return value of FireflyIII\Console\Commands\Export\ExportData::getDateParameter() must be an instance of Carbon\Carbon, null returned {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Return value of FireflyIII\\Console\\Commands\\Export\\ExportData::getDateParameter() must be an instance of Carbon\\Carbon, null returned at /usr/share/webapps/firefly-iii/app/Console/Commands/Export/ExportData.php:238)
[stacktrace]
#0 /usr/share/webapps/firefly-iii/app/Console/Commands/Export/ExportData.php(264): FireflyIII\\Console\\Commands\\Export\\ExportData->getDateParameter('start')
#1 /usr/share/webapps/firefly-iii/app/Console/Commands/Export/ExportData.php(113): FireflyIII\\Console\\Commands\\Export\\ExportData->parseOptions()
#2 [internal function]: FireflyIII\\Console\\Commands\\Export\\ExportData->handle()
#3 /usr/share/webapps/firefly-iii/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(32): call_user_func_array(Array, Array)
#4 /usr/share/webapps/firefly-iii/vendor/laravel/framework/src/Illuminate/Container/Util.php(36): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#5 /usr/share/webapps/firefly-iii/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(90): Illuminate\\Container\\Util::unwrapIfClosure(Object(Closure))
#6 /usr/share/webapps/firefly-iii/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(34): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#7 /usr/share/webapps/firefly-iii/vendor/laravel/framework/src/Illuminate/Container/Container.php(590): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#8 /usr/share/webapps/firefly-iii/vendor/laravel/framework/src/Illuminate/Console/Command.php(202): Illuminate\\Container\\Container->call(Array)
#9 /usr/share/webapps/firefly-iii/vendor/symfony/console/Command/Command.php(255): Illuminate\\Console\\Command->execute(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#10 /usr/share/webapps/firefly-iii/vendor/laravel/framework/src/Illuminate/Console/Command.php(189): Symfony\\Component\\Console\\Command\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#11 /usr/share/webapps/firefly-iii/vendor/symfony/console/Application.php(1011): Illuminate\\Console\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#12 /usr/share/webapps/firefly-iii/vendor/symfony/console/Application.php(272): Symfony\\Component\\Console\\Application->doRunCommand(Object(FireflyIII\\Console\\Commands\\Export\\ExportData), Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#13 /usr/share/webapps/firefly-iii/vendor/symfony/console/Application.php(148): Symfony\\Component\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#14 /usr/share/webapps/firefly-iii/vendor/laravel/framework/src/Illuminate/Console/Application.php(93): Symfony\\Component\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#15 /usr/share/webapps/firefly-iii/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(131): Illuminate\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#16 /usr/share/webapps/firefly-iii/artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#17 {main}
"} 
```

**Comment by JC5** [comment]
Thanks for letting me know. That seems to be a bug indeed. It should be fixed in the next release.
