### ISSUE TITLE
Installation: Connection refused, “Command currently applies to MySQL connections only” “MySQL server has gone away”

### ISSUE THREAD

**Issue by ldon13** [firefly-iii/firefly-iii#2990]
I am running Firefly III version 4.8.2, and recently tried 5.0.0-beta.1

**Description**
php artisan command
Installed using Docker compose on Docker for Mac

How do I access the logs? via docker container? /storage file via container isn’t a directory.

Not sure if this is the debug logs shown when switching from notice to debug variable.

```
Now in entrypoint.sh for Firefly III
Making directories...
Touch DB file (if SQLlite)...
Run chown on /var/www/firefly-iii/storage...
Run chmod on /var/www/firefly-iii/storage...
Remove log file...
Dump auto load...
Generating optimized autoload files> Illuminate\Foundation\ComposerScripts::postAutoloadDump
Generated optimized autoload files containing 5053 classes
Discover packages...
Discovered Package: adldap2/adldap2-laravel
Discovered Package: danhunsaker/laravel-flysystem-others
Discovered Package: davejamesmiller/laravel-breadcrumbs
Discovered Package: fideloper/proxy
Discovered Package: laravel/passport
Discovered Package: laravelcollective/html
Discovered Package: nesbot/carbon
Discovered Package: pragmarx/google2fa-laravel
Discovered Package: rcrowe/twigbridge
Package manifest generated successfully.
Run various artisan commands...
wait-for-it.sh: waiting 15 seconds for 172.20.0.2:5432
wait-for-it.sh: 172.20.0.2:5432 is available after 0 seconds
db is up. Time to execute artisan commands
Application cache cleared!
This command currently applies to MySQL connections only.
Error when connecting to DB: SQLSTATE[HY000] [2002] Connection refused
Now in entrypoint.sh for Firefly III
Making directories...
Touch DB file (if SQLlite)...
Run chown on /var/www/firefly-iii/storage...
Run chmod on /var/www/firefly-iii/storage...
Remove log file...
Dump auto load...
Generating optimized autoload files> Illuminate\Foundation\ComposerScripts::postAutoloadDump
Generated optimized autoload files containing 5053 classes
Discover packages...
Discovered Package: adldap2/adldap2-laravel
Discovered Package: danhunsaker/laravel-flysystem-others
Discovered Package: davejamesmiller/laravel-breadcrumbs
Discovered Package: fideloper/proxy
Discovered Package: laravel/passport
Discovered Package: laravelcollective/html
Discovered Package: nesbot/carbon
Discovered Package: pragmarx/google2fa-laravel
Discovered Package: rcrowe/twigbridge
Package manifest generated successfully.
Run various artisan commands...
wait-for-it.sh: waiting 15 seconds for 172.20.0.2:5432
wait-for-it.sh: 172.20.0.2:5432 is available after 0 seconds
db is up. Time to execute artisan commands
Application cache cleared!
This command currently applies to MySQL connections only.
Error when connecting to DB: SQLSTATE[HY000] [2002] Connection refused
[2020-01-12 11:47:51] local.ERROR: SQLSTATE[HY000] [2006] MySQL server has gone away {"exception":"[object] (Doctrine\\DBAL\\Driver\\PDOException(code: 2006): SQLSTATE[HY000] [2006] MySQL server has gone away at /var/www/firefly-iii/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:31, PDOException(code: 2006): SQLSTATE[HY000] [2006] MySQL server has gone away at /var/www/firefly-iii/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:27, PDOException(code: 0): PDO::__construct(): MySQL server has gone away at /var/www/firefly-iii/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:27)
[stacktrace]
#0 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Database/Connectors/Connector.php(67): Doctrine\\DBAL\\Driver\\PDOConnection->__construct('mysql:host=172....', 'firefly', 'dbpostgres', Array)
#1 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Database/Connectors/Connector.php(100): Illuminate\\Database\\Connectors\\Connector->createPdoConnection('mysql:host=172....', 'firefly', 'dbpostgres', Array)
#2 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Database/Connectors/Connector.php(50): Illuminate\\Database\\Connectors\\Connector->tryAgainIfCausedByLostConnection(Object(Doctrine\\DBAL\\Driver\\PDOException), 'mysql:host=172....', 'firefly', 'dbpostgres', Array)
#3 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Database/Connectors/MySqlConnector.php(24): Illuminate\\Database\\Connectors\\Connector->createConnection('mysql:host=172....', Array, Array)
#4 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Database/Connectors/ConnectionFactory.php(182): Illuminate\\Database\\Connectors\\MySqlConnector->connect(Array)
#5 [internal function]: Illuminate\\Database\\Connectors\\ConnectionFactory->Illuminate\\Database\\Connectors\\{closure}()
#6 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Database/Connection.php(919): call_user_func(Object(Closure))
#7 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Database/DatabaseManager.php(259): Illuminate\\Database\\Connection->getPdo()
#8 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Database/DatabaseManager.php(245): Illuminate\\Database\\DatabaseManager->refreshPdoConnections('mysql')
#9 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Database/DatabaseManager.php(65): Illuminate\\Database\\DatabaseManager->reconnect('mysql')
#10 [internal function]: Illuminate\\Database\\DatabaseManager->Illuminate\\Database\\{closure}(Object(Illuminate\\Database\\MySqlConnection))
#11 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Database/Connection.php(756): call_user_func(Object(Closure), Object(Illuminate\\Database\\MySqlConnection))
#12 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Database/Connection.php(736): Illuminate\\Database\\Connection->reconnect()
#13 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Database/Connection.php(718): Illuminate\\Database\\Connection->tryAgainIfCausedByLostConnection(Object(Illuminate\\Database\\QueryException), 'select * from i...', Array, Object(Closure))
#14 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Database/Connection.php(627): Illuminate\\Database\\Connection->handleQueryException(Object(Illuminate\\Database\\QueryException), 'select * from i...', Array, Object(Closure))
#15 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Database/Connection.php(333): Illuminate\\Database\\Connection->run('select * from i...', Array, Object(Closure))
#16 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Database/Schema/MySqlBuilder.php(18): Illuminate\\Database\\Connection->select('select * from i...', Array)
#17 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Database/Migrations/DatabaseMigrationRepository.php(169): Illuminate\\Database\\Schema\\MySqlBuilder->hasTable('migrations')
#18 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php(585): Illuminate\\Database\\Migrations\\DatabaseMigrationRepository->repositoryExists()
#19 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Database/Console/Migrations/MigrateCommand.php(91): Illuminate\\Database\\Migrations\\Migrator->repositoryExists()
#20 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Database/Console/Migrations/MigrateCommand.php(63): Illuminate\\Database\\Console\\Migrations\\MigrateCommand->prepareDatabase()
#21 [internal function]: Illuminate\\Database\\Console\\Migrations\\MigrateCommand->handle()
#22 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(32): call_user_func_array(Array, Array)
#23 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(90): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#24 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(34): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#25 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Container/Container.php(576): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#26 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Console/Command.php(183): Illuminate\\Container\\Container->call(Array)
#27 /var/www/firefly-iii/vendor/symfony/console/Command/Command.php(255): Illuminate\\Console\\Command->execute(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#28 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Console/Command.php(170): Symfony\\Component\\Console\\Command\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#29 /var/www/firefly-iii/vendor/symfony/console/Application.php(1011): Illuminate\\Console\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#30 /var/www/firefly-iii/vendor/symfony/console/Application.php(272): Symfony\\Component\\Console\\Application->doRunCommand(Object(Illuminate\\Database\\Console\\Migrations\\MigrateCommand), Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#31 /var/www/firefly-iii/vendor/symfony/console/Application.php(148): Symfony\\Component\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#32 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Console/Application.php(90): Symfony\\Component\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#33 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(133): Illuminate\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#34 /var/www/firefly-iii/artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#35 {main}
"} 
2020-01-12T01:47:51.214984214Z 
In PDOConnection.php line 31:
                                                     
  SQLSTATE[HY000] [2006] MySQL server has gone away  
                                                     
2020-01-12T01:47:51.216492789Z 
In PDOConnection.php line 27:
                                                     
  SQLSTATE[HY000] [2006] MySQL server has gone away  
                                                     
2020-01-12T01:47:51.217878169Z 
In PDOConnection.php line 27:
                                                  
  PDO::__construct(): MySQL server has gone away  
```

**Comment by ldon13** [comment]
Duplicate of #2947

**Comment by JC5** [comment]
So can I closet his?

**Comment by ldon13** [comment]
Why? I mentioned that @negativzeroey has the same issue but without the “MySQL server has gone away” error, I noticed someone else using the —force option for  executing the php migrate command. I’ll give that a try later this afternoon.

php artisan migrate:refresh --seed --force
