### ISSUE TITLE
Eventual "Woops" screen

### ISSUE THREAD

**Issue by andrew-filippov** [firefly-iii/firefly-iii#3209]
**Bug description**
I am running selfhosted Firefly III version 5.1.1 behind NGINX on Debian GNU/Linux 10 (buster) OS, 

Some Comp. specs (probably issue is caused by small performance capabilities):
- CPU Atom N330
- RAM 2Gb
- HDD 1TB 2.5" 5400rpm (I don't remember manufacturer - it's regular hdd from my laptop)

Sometimes (approx. once per week), "Woops!" screen Error occurs when I manipulate some data. It's not related to specific action or routine.
At first time it was occurred when I tried to add new asset account, next time - when I was importing my billing transactions.

As you can see from included log, It claims, that folder for cache is missing. When it happened, the only way to make firefly running again - make login onto server and create missed directory manually. When it's done, app is working as usual until next time.  

**My Debug screen**
Debug information generated at 2020-03-26 07:44:24 Europe/Kiev for Firefly III version **5.1.1**.

| Variable | Content |
| --- | --- |
| FF version | 5.1.1 |
| FF API version | 1.0.2 |
| Installation ID | b2c27d92-be90-5c10-8589-005df5b314e6 |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | notice, stack |
| PHP version | 7.3.14-1\~deb10u1 |
| Display errors | Off |
| Session start | 2020-03-01 00:00:00 |
| Session end | 2020-03-31 23:59:59 |
| Session first | 2019-12-13 00:00:00 |
| Error reporting | ALL errors |
| Host | Linux |
| Interface | fpm-fcgi |
| UserID | 1 |
| Attempt at "en" | false |
| Attempt at "English" | false |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| DB drivers | mysql |
| Current driver | mysql |
| Login provider |   |
| Trusted proxies (.env) |  |
| User agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.149 Safari/537.36 |
| Loaded extensions | Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, session, sodium, standard, cgi-fcgi, mysqlnd, PDO, xml, bcmath, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, iconv, intl, json, ldap, exif, mysqli, pdo_mysql, Phar, posix, readline, shmop, SimpleXML, sockets, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xmlreader, xmlwriter, xsl, Zend OPcache |

**My Log**
```
[2020-03-26 07:44:08] local.ERROR: Exception is: {"class":"ErrorException","errorMessage":"file_put_contents(\/mnt\/data0\/web\/firefly\/storage\/framework\/cache\/data\/22\/35\/2235de15a8399435823a2466a970979fd5c1f0c7): failed to open stream: No such file or directory","time":"Thu, 26 Mar 2020 07:44:08 +0200","file":"\/mnt\/data0\/web\/firefly\/vendor\/laravel\/framework\/src\/Illuminate\/Filesystem\/Filesystem.php","line":133,"code":0,"version":"5.1.1","url":"http:\/\/firefly.hda.lan\/transactions\/withdrawal\/all?message=created&transaction_group_id=459","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/80.0.3987.149 Safari\/537.36","json":true}
[2020-03-26 07:44:08] local.ERROR: file_put_contents(/mnt/data0/web/firefly/storage/framework/cache/data/22/35/2235de15a8399435823a2466a970979fd5c1f0c7): failed to open stream: No such file or directory {"userId":1,"exception":"[object] (ErrorException(code: 0): file_put_contents(/mnt/data0/web/firefly/storage/framework/cache/data/22/35/2235de15a8399435823a2466a970979fd5c1f0c7): failed to open stream: No such file or directory at /mnt/data0/web/firefly/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php:133)
[stacktrace]
#0 [internal function]: Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError(2, 'file_put_conten...', '/mnt/data0/web/...', 133, Array)
#1 /mnt/data0/web/firefly/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php(133): file_put_contents('/mnt/data0/web/...', '9999999999O:37:...', 2)
#2 /mnt/data0/web/firefly/vendor/laravel/framework/src/Illuminate/Cache/FileStore.php(74): Illuminate\\Filesystem\\Filesystem->put('/mnt/data0/web/...', '9999999999O:37:...', true)
#3 /mnt/data0/web/firefly/vendor/laravel/framework/src/Illuminate/Cache/FileStore.php(138): Illuminate\\Cache\\FileStore->put('87b2fd00d9ac58f...', Object(FireflyIII\\Models\\TransactionCurrency), 0)
#4 /mnt/data0/web/firefly/vendor/laravel/framework/src/Illuminate/Cache/Repository.php(355): Illuminate\\Cache\\FileStore->forever('87b2fd00d9ac58f...', Object(FireflyIII\\Models\\TransactionCurrency))
#5 /mnt/data0/web/firefly/vendor/laravel/framework/src/Illuminate/Cache/CacheManager.php(378): Illuminate\\Cache\\Repository->forever('87b2fd00d9ac58f...', Object(FireflyIII\\Models\\TransactionCurrency))
#6 /mnt/data0/web/firefly/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(261): Illuminate\\Cache\\CacheManager->__call('forever', Array)
#7 /mnt/data0/web/firefly/app/Support/CacheProperties.php(93): Illuminate\\Support\\Facades\\Facade::__callStatic('forever', Array)
#8 /mnt/data0/web/firefly/app/Support/Amount.php(316): FireflyIII\\Support\\CacheProperties->store(Object(FireflyIII\\Models\\TransactionCurrency))
#9 /mnt/data0/web/firefly/app/Support/Amount.php(281): FireflyIII\\Support\\Amount->getDefaultCurrencyByUser(Object(FireflyIII\\User))
#10 /mnt/data0/web/firefly/app/Http/Middleware/Range.php(94): FireflyIII\\Support\\Amount->getDefaultCurrency()
#11 /mnt/data0/web/firefly/app/Http/Middleware/Range.php(51): FireflyIII\\Http\\Middleware\\Range->configureView()
#12 /mnt/data0/web/firefly/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): FireflyIII\\Http\\Middleware\\Range->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#13 /mnt/data0/web/firefly/vendor/jc5/google2fa-laravel/src/Middleware.php(29): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#14 /mnt/data0/web/firefly/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): PragmaRX\\Google2FALaravel\\Middleware->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#15 /mnt/data0/web/firefly/app/Http/Middleware/Authenticate.php(73): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#16 /mnt/data0/web/firefly/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): FireflyIII\\Http\\Middleware\\Authenticate->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#17 /mnt/data0/web/firefly/vendor/laravel/passport/src/Http/Middleware/CreateFreshApiToken.php(50): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#18 /mnt/data0/web/firefly/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Laravel\\Passport\\Http\\Middleware\\CreateFreshApiToken->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#19 /mnt/data0/web/firefly/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(76): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#20 /mnt/data0/web/firefly/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#21 /mnt/data0/web/firefly/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#22 /mnt/data0/web/firefly/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#23 /mnt/data0/web/firefly/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(56): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#24 /mnt/data0/web/firefly/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Session\\Middleware\\StartSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#25 /mnt/data0/web/firefly/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#26 /mnt/data0/web/firefly/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#27 /mnt/data0/web/firefly/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(66): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#28 /mnt/data0/web/firefly/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#29 /mnt/data0/web/firefly/app/Http/Middleware/Sandstorm.php(54): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#30 /mnt/data0/web/firefly/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): FireflyIII\\Http\\Middleware\\Sandstorm->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#31 /mnt/data0/web/firefly/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(105): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#32 /mnt/data0/web/firefly/vendor/laravel/framework/src/Illuminate/Routing/Router.php(683): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#33 /mnt/data0/web/firefly/vendor/laravel/framework/src/Illuminate/Routing/Router.php(658): Illuminate\\Routing\\Router->runRouteWithinStack(Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request))
#34 /mnt/data0/web/firefly/vendor/laravel/framework/src/Illuminate/Routing/Router.php(624): Illuminate\\Routing\\Router->runRoute(Object(Illuminate\\Http\\Request), Object(Illuminate\\Routing\\Route))
#35 /mnt/data0/web/firefly/vendor/laravel/framework/src/Illuminate/Routing/Router.php(613): Illuminate\\Routing\\Router->dispatchToRoute(Object(Illuminate\\Http\\Request))
#36 /mnt/data0/web/firefly/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(170): Illuminate\\Routing\\Router->dispatch(Object(Illuminate\\Http\\Request))
#37 /mnt/data0/web/firefly/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(130): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}(Object(Illuminate\\Http\\Request))
#38 /mnt/data0/web/firefly/app/Http/Middleware/InstallationId.php(59): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#39 /mnt/data0/web/firefly/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): FireflyIII\\Http\\Middleware\\InstallationId->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#40 /mnt/data0/web/firefly/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#41 /mnt/data0/web/firefly/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Fideloper\\Proxy\\TrustProxies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#42 /mnt/data0/web/firefly/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#43 /mnt/data0/web/firefly/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#44 /mnt/data0/web/firefly/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#45 /mnt/data0/web/firefly/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#46 /mnt/data0/web/firefly/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#47 /mnt/data0/web/firefly/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#48 /mnt/data0/web/firefly/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(63): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#49 /mnt/data0/web/firefly/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#50 /mnt/data0/web/firefly/app/Http/Middleware/SecureHeaders.php(50): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#51 /mnt/data0/web/firefly/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): FireflyIII\\Http\\Middleware\\SecureHeaders->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#52 /mnt/data0/web/firefly/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(105): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#53 /mnt/data0/web/firefly/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(145): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#54 /mnt/data0/web/firefly/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(110): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#55 /mnt/data0/web/firefly/public/index.php(76): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#56 {main}
```

**Bonus points**

- [x] Nobody reported this bug before
- [x] I have added a stack trace from my log files.
- [ ] I have added a screenshot.
- [ ] I was able to replicate it on the demo site https://demo.firefly-iii.org/

**Comment by JC5** [comment]
Hi! Thanks for the bug report. It looks like some kind of permissions issue. This is often the cause.

Try to make sure that the entire Firefly III directory is owned by the user who's running the web server. This is often `www-data`. Try something like this: `sudo chown -R www-data:www-data /var/www/firefly-iii`.

Whenever you run `php artisan` commands or other commands, run them as the `www-data` user as well (or whichever user this is): `sudo -u www-data php artisan ... `.

You can clear the cache from the command line by running: `sudo -u www-data php artisan cache:clear` or by visiting /flush on your installation. 

That should fix this.

**Comment by andrew-filippov** [comment]
Thanks for the quick response.
Firefly's folder has already www-data as owner.
 I had visited /flush at the moment. Thanks for advise!

**Comment by fictitiousexistence** [comment]
Hi- Did clearing the cache work for you?

I know I had this issue previously and some other issues with firefly and php 7.4. even though the directories and files all had the correct permissions, owner, and group set. To fix it I had to give php-fpm write permissions to the firefly install by doing the below command:

# systemctl edit php-fpm.service

and saving this file with the below contents (your install path is probably different)
![image](https://user-images.githubusercontent.com/20089581/78419199-663cbe80-7611-11ea-90a8-b3c75ac5ea1d.png)

Then restart php-fpm and nginx.

**Comment by andrew-filippov** [comment]
Yeah.. using /flush fix this issue for me (at least, I have not seen "woops" screen anymore). I think issue can be closed. Thank for responses!
