### ISSUE TITLE
Application update check fails at startup

### ISSUE THREAD

**Issue by MouettE-SC** [firefly-iii/firefly-iii#3218]
I am running Firefly III version 5.1.1.

**Description**
Update check fails on application start

**Extra info**
I managed to manually disable the update check in mysql so I can still use the app. Manual update check from the UI fails too. I think the json returned by https://version.firefly-iii.org/index.json misses the firefly-iii key.

**Bonus points**

- [X] I have read the FAQ at https://bit.ly/FF3-FAQ
- [X] I added a screenshot 
![image](https://user-images.githubusercontent.com/8431184/77867662-2edfa380-7206-11ea-9f04-e7674f639bac.png)
- [X] I added log files (see https://bit.ly/FF3-get-logs)
```
[2020-03-29 21:20:03] local.DEBUG: Installer middleware for URI https://<masked>
[2020-03-29 21:20:03] local.DEBUG: Now in routine hasNoTables()
[2020-03-29 21:20:03] local.DEBUG: Everything seems OK with the tables.
[2020-03-29 21:20:03] local.INFO: Configured DB version (12) equals expected DB version (12)
[2020-03-29 21:20:03] local.INFO: Installed Firefly III version (5.1.1) equals expected Firefly III version (5.1.1)

...... bla bla groupcollector ....

[2020-03-29 21:20:03] local.DEBUG: Now in checkForUpdates()
[2020-03-29 21:20:03] local.DEBUG: Last check time is 1584131728, current time is 1585531203, difference is 1399475
[2020-03-29 21:20:03] local.DEBUG: Have not checked for a new version in a week!
[2020-03-29 21:20:03] local.DEBUG: Now in getLatestRelease()
[2020-03-29 21:20:03] local.DEBUG: Now in getUpdateInformation(stable)
[2020-03-29 21:20:03] local.DEBUG: Now in contactServer(stable)
[2020-03-29 21:20:03] local.DEBUG: Going to call https://version.firefly-iii.org/index.json
[2020-03-29 21:20:03] local.ERROR: No valid update channel "stable"
[2020-03-29 21:20:03] local.ERROR: {
    "csv": {
        "stable": {
            "version": null,
            "date": null,
            "title": null,
            "description": null,
            "from_github": false,
            "link": null,
            "is_stable": null,
            "is_beta": null,
            "is_alpha": null
        },
        "beta": {
            "version": "1.0.0-beta.2",
            "date": "2020-03-13",
            "title": null,
            "description": null,
            "from_github": true,
            "link": "https:\/\/github.com\/firefly-iii\/csv-importer\/releases\/tag\/1.0.0-beta.2",
            "is_stable": null,
            "is_beta": true,
            "is_alpha": null
        },
        "alpha": {
            "version": "1.0.0-beta.2",
            "date": "2020-03-13",
            "title": null,
            "description": null,
            "from_github": true,
            "link": "https:\/\/github.com\/firefly-iii\/csv-importer\/releases\/tag\/1.0.0-beta.2",
            "is_stable": null,
            "is_beta": true,
            "is_alpha": null
        }
    },
    "bunq": {
        "stable": {
            "version": null,
            "date": null,
            "title": null,
            "description": null,
            "from_github": false,
            "link": null,
            "is_stable": null,
            "is_beta": null,
            "is_alpha": null
        },
        "beta": {
            "version": "1.0.0-beta.1",
            "date": "2020-03-13",
            "title": null,
            "description": null,
            "from_github": true,
            "link": "https:\/\/github.com\/firefly-iii\/bunq-importer\/releases\/tag\/1.0.0-beta.1",
            "is_stable": null,
            "is_beta": true,
            "is_alpha": null
        },
        "alpha": {
            "version": "1.0.0-beta.1",
            "date": "2020-03-13",
            "title": null,
            "description": null,
            "from_github": true,
            "link": "https:\/\/github.com\/firefly-iii\/bunq-importer\/releases\/tag\/1.0.0-beta.1",
            "is_stable": null,
            "is_beta": true,
            "is_alpha": null
        }
    }
}
[2020-03-29 21:20:03] local.ERROR: Exception is: {"class":"ErrorException","errorMessage":"Undefined index: firefly_iii","time":"Sun, 29 Mar 2020 21:20:03 -0400","file":"\/srv\/www\/<masked>\/app\/Services\/FireflyIIIOrg\/Update\/UpdateRequest.php","line":211,"code":0,"version":"5.1.1","url":"https:\/\/<masked>","userAgent":"Mozilla\/5.0 (X11; Linux x86_64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/80.0.3987.158 Safari\/537.36","json":true}

.... bla bla bla error email ....

[2020-03-29 21:20:03] local.ERROR: Undefined index: firefly_iii {"userId":1,"exception":"[object] (ErrorException(code: 0): Undefined index: firefly_iii at /srv/www/<masked>/app/Services/FireflyIIIOrg/Update/UpdateRequest.php:211)
[stacktrace]
#0 /srv/www/<masked>/app/Services/FireflyIIIOrg/Update/UpdateRequest.php(211): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError(8, 'Undefined index...', '/srv/www/<masked>...', 211, Array)
#1 /srv/www/<masked>/app/Services/FireflyIIIOrg/Update/UpdateRequest.php(51): FireflyIII\\Services\\FireflyIIIOrg\\Update\\UpdateRequest->contactServer('stable')
#2 /srv/www/<masked>/app/Helpers/Update/UpdateTrait.php(49): FireflyIII\\Services\\FireflyIIIOrg\\Update\\UpdateRequest->getUpdateInformation('stable')
#3 /srv/www/<masked>/app/Handlers/Events/VersionCheckEventHandler.php(82): FireflyIII\\Handlers\\Events\\VersionCheckEventHandler->getLatestRelease()
#4 [internal function]: FireflyIII\\Handlers\\Events\\VersionCheckEventHandler->checkForUpdates(Object(FireflyIII\\Events\\RequestedVersionCheckStatus))
```
- [ ] I was able to replicate the issue on the demo site. (I tried but got "The feature you try to access is not available to demo users.")

**Comment by JC5** [comment]
I see what you mean. I’ll pick it up :)

**Comment by JC5** [comment]
The key is back. GitHub sent back a 500 error last night. I've updated the script so it won't overwrite yesterday's result if an error occurs.
