### ISSUE TITLE
CSV Importer Internal Server Error 500

### ISSUE THREAD

**Issue by eyeofmaat** [firefly-iii/firefly-iii#3279]
Using current CSV importer (Docker fireflyiii/csv-importer:develop) v1.0.4

This is the first time i am trying to use it, and i am getting internal server error.

**Steps to reproduce**
1. Select CVS file, leave config empty
2. Adjust date field to d/m/Y (for Australia)
3. Select Default import account
4. Click on Submit
5. Error 500

Using Notepad++, i have confirmed file in UTF-8
CSV from bank is simple 3 column file. Date, Amount (positive/negative), Description
i.e
17/04/2020,-800.00,DESCRIPTION
16/04/2020,800.00,DESCRIPTION

Original file had quotes around the amount and braces around BPAY transaction IDs, but i removed for testing. (no change, same error)
i.e
17/04/2020,"-800.00",DESCRIPTION {123456}
16/04/2020,"800.00",DESCRIPTION

Docker logs show JSON error: (I can get you more stack trace if needed)

[2020-04-20 06:11:47] production.DEBUG: Now at App\Http\Controllers\Import\ConfigurationController::phpDate  ,
[2020-04-20 06:11:55] production.DEBUG: Now at App\Http\Controllers\Import\ConfigurationController::phpDate  ,
[2020-04-20 06:17:16] production.DEBUG: Now at App\Http\Controllers\Import\ConfigurationController::postIndex  ,
[2020-04-20 06:17:16] production.ERROR: Syntax error {"exception":"[object] (JsonException(code: 4): Syntax error at /var/www/html/app/Http/Request/ConfigurationPostRequest.php:49),
[stacktrace],
#0 /var/www/html/app/Http/Request/ConfigurationPostRequest.php(49): json_decode('', true, 512, 4194304),
#1 /var/www/html/app/Http/Controllers/Import/ConfigurationController.php(141): App\\Http\\Request\\ConfigurationPostRequest->getAll(),
#2 [internal function]: App\\Http\\Controllers\\Import\\ConfigurationController->postIndex(Object(App\\Http\\Request\\ConfigurationPostRequest)),
#3 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): call_user_func_array(Array, Array),
#4 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\\Routing\\Controller->callAction('postIndex', Array),
#5 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Route.php(225): Illuminate\\Routing\\ControllerDispatcher->dispatch(Object(Illuminate\\Routing\\Route), Object(App\\Http\\Controllers\\Import\\ConfigurationController), 'postIndex'),
#6 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Route.php(182): Illuminate\\Routing\\Route->runController(),
#7 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(685): Illuminate\\Routing\\Route->run(),
#8 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request)),
#9 /var/www/html/app/Http/Middleware/ConfigComplete.php(50): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request)),
#10 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): App\\Http\\Middleware\\ConfigComplete->handle(Object(Illuminate\\Http\\Request), Object(Closure))

In addition, navigating back to the root and selecting "Start Here" jumps straight to config. It no longer prompts to upload file. This feels wrong. I need to re-create the docker container before i can get the upload prompts again (as i needed to do when testing different file formats)

Regards,
Craig

**Comment by JC5** [comment]
I pushed a fix, and the build is running. In [a few minutes](https://travis-ci.com/github/firefly-iii/csv-importer-docker/builds/160574038), you should be able to download a new Docker image that doesn't contain this bug. Thanks for reporting the issue.

If you want to start over entirely during a CSV import, browse to the `/flush` URL. But also, check out https://github.com/firefly-iii/firefly-iii/issues/3275.

**Comment by eyeofmaat** [comment]
thanks. I can confirm that the docker build is fixed now.

**Comment by lartificier74** [comment]
Hi,

I do have a similar 500 server error.

Using current CSV importer v1.0.4. I am running firefly 5.2.4 on Docker on Synology.

CSV from bank is simple 3 column file. Date; Amount (positive/negative); Description
i.e
17/04/2020;-800.00;DESCRIPTION
16/04/2020;800.00;DESCRIPTION

I am certainly doing something not correctly. Thanks for your help.

Docker logs:

upbeat_bassi
date,stream,content
2020-04-26 22:41:17,stdout,172.17.0.1 - - [26/Apr/2020:22:41:17 +0000] "POST /import/configure HTTP/1.1" 500 322562 "http://192.168.0.10:8081/import/configure" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:75.0) Gecko/20100101 Firefox/75.0"

2020-04-26 22:41:17,stdout,"} 

2020-04-26 22:41:17,stdout,#46 {main}

2020-04-26 22:41:17,stdout,#45 /var/www/html/public/index.php(99): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))

2020-04-26 22:41:17,stdout,#44 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(109): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))

2020-04-26 22:41:17,stdout,#43 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(140): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))

2020-04-26 22:41:17,stdout,#42 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))

2020-04-26 22:41:17,stdout,"#41 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Fideloper\\Proxy\\TrustProxies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
"
2020-04-26 22:41:17,stdout,#40 /var/www/html/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))

2020-04-26 22:41:17,stdout,"#39 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Fruitcake\\Cors\\HandleCors->handle(Object(Illuminate\\Http\\Request), Object(Closure))
"
2020-04-26 22:41:17,stdout,#38 /var/www/html/vendor/fruitcake/laravel-cors/src/HandleCors.php(36): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))

2020-04-26 22:41:17,stdout,"#37 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode->handle(Object(Illuminate\\Http\\Request), Object(Closure))
"
2020-04-26 22:41:17,stdout,#36 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(63): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))

2020-04-26 22:41:17,stdout,"#35 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
"
2020-04-26 22:41:17,stdout,#34 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))

2020-04-26 22:41:17,stdout,"#33 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
"
2020-04-26 22:41:17,stdout,#32 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))

2020-04-26 22:41:17,stdout,"#31 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
"
2020-04-26 22:41:17,stdout,#30 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))

2020-04-26 22:41:17,stdout,#29 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}(Object(Illuminate\\Http\\Request))
