### ISSUE TITLE
Error 500 on 5.2.3 with french language

### ISSUE THREAD

**Issue by Crupuk** [firefly-iii/firefly-iii#3287]
**Bug description**
Hi, 

I have a error on FireFly-iii ( french ) updated this morning to 5.2.3.

I have some errors 500 for these files : 

![image](https://user-images.githubusercontent.com/670728/79951332-ca1c0f80-8478-11ea-88b0-4b79edee8386.png)

With debug enabled these error are show if i Try to open one of these url : 

![image](https://user-images.githubusercontent.com/670728/79951474-0bacba80-8479-11ea-898e-300aa12b5e31.png)

```
Error
This error occured in file /var/www/html/soez.be/budget/www/resources/views/v1/javascript/variables.twig on line 33 with code 0.

Stack trace
#0 /var/www/html/soez.be/budget/www/vendor/rcrowe/twigbridge/src/Engine/Twig.php(93): TwigBridge\Engine\Twig->handleTwigError()
#1 /var/www/html/soez.be/budget/www/vendor/laravel/framework/src/Illuminate/View/View.php(143): TwigBridge\Engine\Twig->get()
#2 /var/www/html/soez.be/budget/www/vendor/laravel/framework/src/Illuminate/View/View.php(126): Illuminate\View\View->getContents()
#3 /var/www/html/soez.be/budget/www/vendor/laravel/framework/src/Illuminate/View/View.php(91): Illuminate\View\View->renderContents()
#4 /var/www/html/soez.be/budget/www/vendor/laravel/framework/src/Illuminate/Http/Response.php(42): Illuminate\View\View->render()
#5 /var/www/html/soez.be/budget/www/vendor/symfony/http-foundation/Response.php(205): Illuminate\Http\Response->setContent()
#6 /var/www/html/soez.be/budget/www/vendor/laravel/framework/src/Illuminate/Routing/ResponseFactory.php(55): Symfony\Component\HttpFoundation\Response->__construct()
#7 /var/www/html/soez.be/budget/www/vendor/laravel/framework/src/Illuminate/Routing/ResponseFactory.php(85): Illuminate\Routing\ResponseFactory->make()
#8 /var/www/html/soez.be/budget/www/app/Http/Controllers/JavascriptController.php(144): Illuminate\Routing\ResponseFactory->view()
#9 [internal function]: FireflyIII\Http\Controllers\JavascriptController->variables()
#10 /var/www/html/soez.be/budget/www/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): call_user_func_array()
#11 /var/www/html/soez.be/budget/www/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\Routing\Controller->callAction()
#12 /var/www/html/soez.be/budget/www/vendor/laravel/framework/src/Illuminate/Routing/Route.php(219): Illuminate\Routing\ControllerDispatcher->dispatch()
#13 /var/www/html/soez.be/budget/www/vendor/laravel/framework/src/Illuminate/Routing/Route.php(176): Illuminate\Routing\Route->runController()
#14 /var/www/html/soez.be/budget/www/vendor/laravel/framework/src/Illuminate/Routing/Router.php(681): Illuminate\Routing\Route->run()
#15 /var/www/html/soez.be/budget/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(130): Illuminate\Routing\Router->Illuminate\Routing\{closure}()
#16 /var/www/html/soez.be/budget/www/app/Http/Controllers/Controller.php(107): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#17 /var/www/html/soez.be/budget/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(153): FireflyIII\Http\Controllers\Controller->FireflyIII\Http\Controllers\{closure}()
#18 /var/www/html/soez.be/budget/www/app/Http/Middleware/InterestingMessage.php(59): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#19 /var/www/html/soez.be/budget/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): FireflyIII\Http\Middleware\InterestingMessage->handle()
#20 /var/www/html/soez.be/budget/www/app/Http/Middleware/Binder.php(79): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#21 /var/www/html/soez.be/budget/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): FireflyIII\Http\Middleware\Binder->handle()
#22 /var/www/html/soez.be/budget/www/app/Http/Middleware/Range.php(60): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#23 /var/www/html/soez.be/budget/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): FireflyIII\Http\Middleware\Range->handle()
#24 /var/www/html/soez.be/budget/www/vendor/jc5/google2fa-laravel/src/Middleware.php(29): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#25 /var/www/html/soez.be/budget/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): PragmaRX\Google2FALaravel\Middleware->handle()
#26 /var/www/html/soez.be/budget/www/app/Http/Middleware/Authenticate.php(74): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#27 /var/www/html/soez.be/budget/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): FireflyIII\Http\Middleware\Authenticate->handle()
#28 /var/www/html/soez.be/budget/www/vendor/laravel/passport/src/Http/Middleware/CreateFreshApiToken.php(50): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#29 /var/www/html/soez.be/budget/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Laravel\Passport\Http\Middleware\CreateFreshApiToken->handle()
#30 /var/www/html/soez.be/budget/www/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(76): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#31 /var/www/html/soez.be/budget/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Foundation\Http\Middleware\VerifyCsrfToken->handle()
#32 /var/www/html/soez.be/budget/www/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#33 /var/www/html/soez.be/budget/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\View\Middleware\ShareErrorsFromSession->handle()
#34 /var/www/html/soez.be/budget/www/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(56): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#35 /var/www/html/soez.be/budget/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Session\Middleware\StartSession->handle()
#36 /var/www/html/soez.be/budget/www/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#37 /var/www/html/soez.be/budget/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle()
#38 /var/www/html/soez.be/budget/www/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(66): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#39 /var/www/html/soez.be/budget/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Cookie\Middleware\EncryptCookies->handle()
#40 /var/www/html/soez.be/budget/www/app/Http/Middleware/Sandstorm.php(54): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#41 /var/www/html/soez.be/budget/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): FireflyIII\Http\Middleware\Sandstorm->handle()
#42 /var/www/html/soez.be/budget/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(105): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#43 /var/www/html/soez.be/budget/www/vendor/laravel/framework/src/Illuminate/Routing/Router.php(683): Illuminate\Pipeline\Pipeline->then()
#44 /var/www/html/soez.be/budget/www/vendor/laravel/framework/src/Illuminate/Routing/Router.php(658): Illuminate\Routing\Router->runRouteWithinStack()
#45 /var/www/html/soez.be/budget/www/vendor/laravel/framework/src/Illuminate/Routing/Router.php(624): Illuminate\Routing\Router->runRoute()
#46 /var/www/html/soez.be/budget/www/vendor/laravel/framework/src/Illuminate/Routing/Router.php(613): Illuminate\Routing\Router->dispatchToRoute()
#47 /var/www/html/soez.be/budget/www/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(170): Illuminate\Routing\Router->dispatch()
#48 /var/www/html/soez.be/budget/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(130): Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}()
#49 /var/www/html/soez.be/budget/www/app/Http/Middleware/InstallationId.php(59): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#50 /var/www/html/soez.be/budget/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): FireflyIII\Http\Middleware\InstallationId->handle()
#51 /var/www/html/soez.be/budget/www/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#52 /var/www/html/soez.be/budget/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Fideloper\Proxy\TrustProxies->handle()
#53 /var/www/html/soez.be/budget/www/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#54 /var/www/html/soez.be/budget/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle()
#55 /var/www/html/soez.be/budget/www/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#56 /var/www/html/soez.be/budget/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle()
#57 /var/www/html/soez.be/budget/www/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#58 /var/www/html/soez.be/budget/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Foundation\Http\Middleware\ValidatePostSize->handle()
#59 /var/www/html/soez.be/budget/www/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(63): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#60 /var/www/html/soez.be/budget/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle()
#61 /var/www/html/soez.be/budget/www/app/Http/Middleware/SecureHeaders.php(51): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#62 /var/www/html/soez.be/budget/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): FireflyIII\Http\Middleware\SecureHeaders->handle()
#63 /var/www/html/soez.be/budget/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(105): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#64 /var/www/html/soez.be/budget/www/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(145): Illuminate\Pipeline\Pipeline->then()
#65 /var/www/html/soez.be/budget/www/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(110): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter()
#66 /var/www/html/soez.be/budget/www/public/index.php(76): Illuminate\Foundation\Http\Kernel->handle()
#67 {main}
```

No error if I put Firefly-iii back to English-Us 

**Steps to reproduce**
Update to 5.2.3 , switch to french.

**Extra info**
Debug information generated at 2020-04-22 09:13:56 Europe/Amsterdam for Firefly III version **5.2.3**.

| Variable | Content |
| --- | --- |
| FF version | 5.2.3 |
| FF API version | 1.1.0 |
| Installation ID | b2c27d92-be90-5c10-8589-005df5b314e6 |
| App environment | local |
| App debug mode | true |
| App cache driver | file |
| App logging | debug, stdout |
| PHP version | 7.4.5 |
| Display errors | Off |
| Session start | 2020-04-01 00:00:00 |
| Session end | 2020-04-30 23:59:59 |
| Session first | 2015-12-15 00:00:00 |
| Error reporting | ALL errors |
| Host | Linux |
| Interface | fpm-fcgi |
| UserID | 3 |
| Attempt at "en" | false |
| Attempt at "English" | false |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| DB drivers | mysql, sqlite |
| Current driver | mysql |
| Login provider |   |
| Trusted proxies (.env) |  |
| User agent | Mozilla/5.0 (X11; Fedora; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.163 Safari/537.36 |
| Loaded extensions | Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, session, standard, cgi-fcgi, bcmath, bz2, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, iconv, intl, json, ldap, exif, mysqlnd, PDO, Phar, SimpleXML, sockets, sodium, sqlite3, tokenizer, xml, xmlwriter, xsl, mysqli, pdo_mysql, pdo_sqlite, xmlreader, zip, mysql, Zend OPcache |

**Bonus points**

- [ ] Nobody reported this bug before
- [x] I have added a stack trace from my log files 
- [x] I have added a screenshot.
- [ ] I was able to replicate it on the demo site https://demo.firefly-iii.org/ ( Not updated :-( ) 

Thanks for your help

**Comment by JC5** [comment]
I can't replicate this locally but I know the root cause. Stay tuned.

It has to do with local language packs which I can't do much about.

**Comment by JC5** [comment]
For now, you can fix this manually. Open file `app/Support/Steam.php` and go to line 619. Remove this entry:

```
sprintf('%s', $locale),
```

That should fix it. Problem exists because your Linux installation has non-utf8 packages.

**Comment by JC5** [comment]
https://github.com/firefly-iii/firefly-iii/issues/3288
