### ISSUE TITLE
csv-importer: php7.4: bcmod(): bcmath function argument is not well-formed

### ISSUE THREAD

**Issue by ovv** [firefly-iii/firefly-iii#3299]
**Bug description**

csv-importer version: 1.0.6
php: 7.4

Incompatible change in bcmath lead to error parsing invalid IBAN: 
https://www.php.net/manual/en/migration74.incompatible.php#migration74.incompatible.bcmath

```
[stacktrace]
#0 [internal function]: Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError(2, 'bcmod(): bcmath...', '/builds/infra/f...', 11, Array)
#1 /builds/infra/firefly-importer/csv-importer/app/Services/CSV/Converter/Iban.php(67): bcmod('1111111-11111-', '11')
#2 /builds/infra/firefly-importer/csv-importer/app/Services/CSV/Converter/Iban.php(42): App\\Services\\CSV\\Converter\\Iban->isValidIban('111-1111111-11')
#3 /builds/infra/firefly-importer/csv-importer/app/Services/CSV/Converter/ConverterService.php(54): App\\Services\\CSV\\Converter\\Iban->convert('111-1111111-11')
#4 /builds/infra/firefly-importer/csv-importer/app/Services/Import/ColumnValue.php(124): App\\Services\\CSV\\Converter\\ConverterService::convert('Iban', '111-1111111-11', NULL)
#5 /builds/infra/firefly-importer/csv-importer/app/Services/Import/Routine/ColumnValueConverter.php(163): App\\Services\\Import\\ColumnValue->getParsedValue()
#6 /builds/infra/firefly-importer/csv-importer/app/Services/Import/Routine/ColumnValueConverter.php(72): App\\Services\\Import\\Routine\\ColumnValueConverter->processValueArray(Array)
#7 /builds/infra/firefly-importer/csv-importer/app/Services/Import/ImportRoutineManager.php(169): App\\Services\\Import\\Routine\\ColumnValueConverter->processValueArrays(Array)
#8 /builds/infra/firefly-importer/csv-importer/app/Console/StartImport.php(58): App\\Services\\Import\\ImportRoutineManager->start()
#9 /builds/infra/firefly-importer/csv-importer/app/Console/Commands/Import.php(103): App\\Console\\Commands\\Import->startImport('Statement,Date,...', Array)
#10 [internal function]: App\\Console\\Commands\\Import->handle()
#11 /builds/infra/firefly-importer/csv-importer/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(33): call_user_func_array(Array, Array)
#12 /builds/infra/firefly-importer/csv-importer/vendor/laravel/framework/src/Illuminate/Container/Util.php(36): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#13 /builds/infra/firefly-importer/csv-importer/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(91): Illuminate\\Container\\Util::unwrapIfClosure(Object(Closure))
#14 /builds/infra/firefly-importer/csv-importer/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(35): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#15 /builds/infra/firefly-importer/csv-importer/vendor/laravel/framework/src/Illuminate/Container/Container.php(592): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#16 /builds/infra/firefly-importer/csv-importer/vendor/laravel/framework/src/Illuminate/Console/Command.php(134): Illuminate\\Container\\Container->call(Array)
#17 /builds/infra/firefly-importer/csv-importer/vendor/symfony/console/Command/Command.php(255): Illuminate\\Console\\Command->execute(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#18 /builds/infra/firefly-importer/csv-importer/vendor/laravel/framework/src/Illuminate/Console/Command.php(121): Symfony\\Component\\Console\\Command\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#19 /builds/infra/firefly-importer/csv-importer/vendor/symfony/console/Application.php(912): Illuminate\\Console\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#20 /builds/infra/firefly-importer/csv-importer/vendor/symfony/console/Application.php(264): Symfony\\Component\\Console\\Application->doRunCommand(Object(App\\Console\\Commands\\Import), Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#21 /builds/infra/firefly-importer/csv-importer/vendor/symfony/console/Application.php(140): Symfony\\Component\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#22 /builds/infra/firefly-importer/csv-importer/vendor/laravel/framework/src/Illuminate/Console/Application.php(93): Symfony\\Component\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#23 /builds/infra/firefly-importer/csv-importer/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(129): Illuminate\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#24 /builds/infra/firefly-importer/csv-importer/artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#25 {main}
"} 
In Iban.php line 67:
                                                        
  bcmod(): bcmath function argument is not well-formed  
```

**Comment by JC5** [comment]
Nice find :+1:

I pushed a fix. The Docker image will be fixed when [this build](https://travis-ci.com/github/firefly-iii/csv-importer-docker/builds/162053996) is finished.

**Comment by ovv** [comment]
I can confirm it's fixed. Thanks
