### ISSUE TITLE
CSV Import error 500

### ISSUE THREAD

**Issue by lartificier74** [firefly-iii/firefly-iii#3300]
Hi,
I do have a similar 500 server error.
Using current CSV importer v1.0.4. I am running firefly 5.2.4 on Docker on Synology.
CSV from bank is simple 3 column file. Date; Amount (positive/negative); Description  i.e  17/04/2020;-800.00;DESCRIPTION  16/04/2020;800.00;DESCRIPTION
I am certainly doing something not correctly. Thanks for your help.
Docker logs:
upbeat_bassi  date,stream,content  2020-04-26 22:41:17,stdout,172.17.0.1 - - [26/Apr/2020:22:41:17 +0000] "POST /import/configure HTTP/1.1" 500 322562 "http://192.168.0.10:8081/import/configure" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:75.0) Gecko/20100101 Firefox/75.0"
2020-04-26 22:41:17,stdout,"}
2020-04-26 22:41:17,stdout,#46 {main}
2020-04-26 22:41:17,stdout,#45 /var/www/html/public/index.php(99): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
2020-04-26 22:41:17,stdout,#44 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(109): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
2020-04-26 22:41:17,stdout,#43 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(140): Illuminate\Pipeline\Pipeline->then(Object(Closure))
2020-04-26 22:41:17,stdout,#42 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
2020-04-26 22:41:17,stdout,"#41 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Fideloper\Proxy\TrustProxies->handle(Object(Illuminate\Http\Request), Object(Closure))  "  2020-04-26 22:41:17,stdout,#40 /var/www/html/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
2020-04-26 22:41:17,stdout,"#39 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Fruitcake\Cors\HandleCors->handle(Object(Illuminate\Http\Request), Object(Closure))  "  2020-04-26 22:41:17,stdout,#38 /var/www/html/vendor/fruitcake/laravel-cors/src/HandleCors.php(36): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
2020-04-26 22:41:17,stdout,"#37 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))  "  2020-04-26 22:41:17,stdout,#36 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(63): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
2020-04-26 22:41:17,stdout,"#35 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Foundation\Http\Middleware\ValidatePostSize->handle(Object(Illuminate\Http\Request), Object(Closure))  "  2020-04-26 22:41:17,stdout,#34 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
2020-04-26 22:41:17,stdout,"#33 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle(Object(Illuminate\Http\Request), Object(Closure))  "  2020-04-26 22:41:17,stdout,#32 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
2020-04-26 22:41:17,stdout,"#31 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle(Object(Illuminate\Http\Request), Object(Closure))  "  2020-04-26 22:41:17,stdout,#30 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
2020-04-26 22:41:17,stdout,#29 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))

**Comment by JC5** [comment]
Please make sure you run the latest version of the CSV importer.

**Comment by lartificier74** [comment]
All set! Newbie mistake...
Thanks a lot!

**Comment by lartificier74** [comment]
Hi @JC5 !

Here is the newbie again... sorry
My first CSV transfer did work well but since few days I have issue with the dates.
Basically, all the transactions I import will appear with the same date which seems to be the current day. Did I miss something again?

Also I was wondering regarding the multi currencies, are you planning having the exchange rates included so for example in the summary of the accounts you can see everything in only one currency?

Thanks for your help!!

MP

**Comment by JC5** [comment]
Check out: https://firefly-iii.gitbook.io/firefly-iii-csv-importer/importing-data/configure#date-format

And https://docs.firefly-iii.org/support/features
