### ISSUE TITLE
csv-importer gets stuck in error loop when trying to import non UTF-8 encoded csv

### ISSUE THREAD

**Issue by skuethe** [firefly-iii/firefly-iii#3312]
**Bug description**
Running **csv-importer** on version **1.0.6**

I tried to import CSV file from bank which was ANSI encoded. csv-importer showed a quick error message in the browser but then quickly moved on to show import progress bar and got stuck in an import loop. I had to manually clear files in `storage/*` folders to get it working again (later saw that there seems to be the possibility to call `/flush` on the application).

Log throws the following error:

```
[2020-04-30 15:56:25] local.ERROR: Malformed UTF-8 characters, possibly incorrectly encoded {"exception":"[object] (JsonException(code: 5): Malformed UTF-8 characters, possibly incorrectly encoded at /var/www/firefly/csv-importer/app/Services/Import/Routine/CSVFileProcessor.php:178)
```

but continues to process the file and then gets stuck with the following messages:

```
[2020-04-30 15:56:26] local.DEBUG: Now at App\Http\Controllers\Import\RunController::status(FpmgHy2Jl8Wy6Wam)
[2020-04-30 15:56:26] local.DEBUG: Now in startOrFindJob(FpmgHy2Jl8Wy6Wam)
[2020-04-30 15:56:26] local.DEBUG: Try to see if file exists for job FpmgHy2Jl8Wy6Wam.
[2020-04-30 15:56:26] local.DEBUG: Status file exists for job FpmgHy2Jl8Wy6Wam.
[2020-04-30 15:56:27] local.DEBUG: Now at App\Http\Controllers\Import\RunController::status(FpmgHy2Jl8Wy6Wam)
[2020-04-30 15:56:27] local.DEBUG: Now in startOrFindJob(FpmgHy2Jl8Wy6Wam)
[2020-04-30 15:56:27] local.DEBUG: Try to see if file exists for job FpmgHy2Jl8Wy6Wam.
[2020-04-30 15:56:27] local.DEBUG: Status file exists for job FpmgHy2Jl8Wy6Wam.
[2020-04-30 15:56:28] local.DEBUG: Now at App\Http\Controllers\Import\RunController::status(FpmgHy2Jl8Wy6Wam)
[2020-04-30 15:56:28] local.DEBUG: Now in startOrFindJob(FpmgHy2Jl8Wy6Wam)
[2020-04-30 15:56:28] local.DEBUG: Try to see if file exists for job FpmgHy2Jl8Wy6Wam.
[2020-04-30 15:56:28] local.DEBUG: Status file exists for job FpmgHy2Jl8Wy6Wam.
[2020-04-30 15:56:29] local.DEBUG: Now at App\Http\Controllers\Import\RunController::status(FpmgHy2Jl8Wy6Wam)
[2020-04-30 15:56:29] local.DEBUG: Now in startOrFindJob(FpmgHy2Jl8Wy6Wam)
[2020-04-30 15:56:29] local.DEBUG: Try to see if file exists for job FpmgHy2Jl8Wy6Wam.
[2020-04-30 15:56:29] local.DEBUG: Status file exists for job FpmgHy2Jl8Wy6Wam.
[2020-04-30 15:56:30] local.DEBUG: Now at App\Http\Controllers\Import\RunController::status(FpmgHy2Jl8Wy6Wam)
[2020-04-30 15:56:30] local.DEBUG: Now in startOrFindJob(FpmgHy2Jl8Wy6Wam)
[2020-04-30 15:56:30] local.DEBUG: Try to see if file exists for job FpmgHy2Jl8Wy6Wam.
[2020-04-30 15:56:30] local.DEBUG: Status file exists for job FpmgHy2Jl8Wy6Wam.
[...]
```

**Steps to reproduce**
Import a csv file encoded as ANSI (or maybe any non-UTF-8 format for that matter? Did not test other encodings).

**Extra info**
server: Debian 10
browser: Firefox 75

**Comment by JC5** [comment]
https://firefly-iii.gitbook.io/firefly-iii-csv-importer/importing-data/upload


Make sure the file is encoded in UTF-8. Use a tool like Sublime Text or Notepad++ to convert the file if necessary.

**Comment by skuethe** [comment]
Yeah I did that, but it would be nice if the tool did not break in an infinite loop after mistakenly uploading a file with the wrong encoding :)

**Comment by JC5** [comment]
I’ll try to catch the error :)

**Comment by carroarmato0** [comment]
I can confirm I'm seeing this too.  @skuethe  KBC bank by any chance? :)

**Comment by skuethe** [comment]
Nope, my test was with comdirect @carroarmato0

**Comment by rnorden** [comment]
I can confirm this too.
Stack trace:

`
[2020-06-20 18:27:38] production.ERROR: Malformed UTF-8 characters, possibly incorrectly encoded {"exception":"[object] (JsonException(code: 5): Malformed UTF-8 characters, possibly incorrectly encoded at /var/www/html/app/Services/Import/Routine/CSVFileProcessor.php:178)
[stacktrace]
#0 /var/www/html/app/Services/Import/Routine/CSVFileProcessor.php(178): json_encode()
#1 /var/www/html/app/Services/Import/Routine/CSVFileProcessor.php(161): App\\Services\\Import\\Routine\\CSVFileProcessor->removeDuplicateLines()
#2 /var/www/html/app/Services/Import/Routine/CSVFileProcessor.php(107): App\\Services\\Import\\Routine\\CSVFileProcessor->processCSVLines()
#3 /var/www/html/app/Services/Import/ImportRoutineManager.php(165): App\\Services\\Import\\Routine\\CSVFileProcessor->processCSVFile()
#4 /var/www/html/app/Http/Controllers/Import/RunController.php(115): App\\Services\\Import\\ImportRoutineManager->start()
`
