### ISSUE TITLE
Uncaught RuntimeException: Unable to create the cache 

### ISSUE THREAD

**Issue by wranglatang** [firefly-iii/firefly-iii#3313]
Im running firefly on unraid in docker using the latest tag.

I just tried to log on to check some finances but the page wont load. When i look at the log i see the below output:

I have tried updating file permisstions deleting the appdata folder for firefly and recreating it but still the same
```
[2020-04-30 20:30:34] local.ERROR: Uncaught RuntimeException: Unable to create the cache directory (/var/www/firefly-iii/storage/framework/views/twig/0e). in /var/www/firefly-iii/vendor/twig/twig/src/Cache/FilesystemCache.php:57

Stack trace:
#0 /var/www/firefly-iii/vendor/twig/twig/src/Environment.php(409): Twig\Cache\FilesystemCache->write('/var/www/firefl...', '<?php\n\nuse Twig...')
#1 /var/www/firefly-iii/vendor/twig/twig/src/Environment.php(381): Twig\Environment->loadClass('__TwigTemplate_...', '/var/www/firefl...', NULL)
#2 /var/www/firefly-iii/vendor/rcrowe/twigbridge/src/Bridge.php(75): Twig\Environment->loadTemplate('/var/www/firefl...', NULL)
#3 /var/www/firefly-iii/vendor/rcrowe/twigbridge/src/Engine/Compiler.php(99): TwigBridge\Bridge->loadTemplate('/var/www/firefl...')
#4 /var/www/firefly-iii/vendor/rcrowe/twigbridge/src/Engine/Twig.php(91): TwigBridge\Engine\Compiler->load('/var/www/firefl...')
#5 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/View/View.php(143): TwigBridge\Engine\Twig->get('/var/www/firefl...', Ar {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalErrorException(code: 1): Uncaught RuntimeException: Unable to create the cache directory (/var/www/firefly-iii/storage/framework/views/twig/0e). in /var/www/firefly-iii/vendor/twig/twig/src/Cache/FilesystemCache.php:57
Stack trace:
#0 /var/www/firefly-iii/vendor/twig/twig/src/Environment.php(409): Twig\\Cache\\FilesystemCache->write('/var/www/firefl...', '<?php\
\
use Twig...')
#1 /var/www/firefly-iii/vendor/twig/twig/src/Environment.php(381): Twig\\Environment->loadClass('__TwigTemplate_...', '/var/www/firefl...', NULL)
#2 /var/www/firefly-iii/vendor/rcrowe/twigbridge/src/Bridge.php(75): Twig\\Environment->loadTemplate('/var/www/firefl...', NULL)
#3 /var/www/firefly-iii/vendor/rcrowe/twigbridge/src/Engine/Compiler.php(99): TwigBridge\\Bridge->loadTemplate('/var/www/firefl...')
#4 /var/www/firefly-iii/vendor/rcrowe/twigbridge/src/Engine/Twig.php(91): TwigBridge\\Engine\\Compiler->load('/var/www/firefl...')
#5 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/View/View.php(143): TwigBridge\\Engine\\Twig->get('/var/www/firefl...', Ar at /var/www/firefly-iii/vendor/twig/twig/src/Cache/FilesystemCache.php:57)
[stacktrace]

}
"}
[Thu Apr 30 20:30:34.112309 2020] [php7:error] [pid 348] [client 172.18.0.1:41726] PHP Fatal error: Uncaught RuntimeException: Unable to create the cache directory (/var/www/firefly-iii/storage/framework/views/twig/8f). in /var/www/firefly-iii/vendor/twig/twig/src/Cache/FilesystemCache.php:57\nStack trace:\n#0 /var/www/firefly-iii/vendor/twig/twig/src/Environment.php(409): Twig\\Cache\\FilesystemCache->write('/var/www/firefl...', '<?php\\n\\nuse Twig...')\n#1 /var/www/firefly-iii/vendor/twig/twig/src/Environment.php(381): Twig\\Environment->loadClass('__TwigTemplate_...', '/var/www/firefl...', NULL)\n#2 /var/www/firefly-iii/vendor/rcrowe/twigbridge/src/Bridge.php(75): Twig\\Environment->loadTemplate('/var/www/firefl...', NULL)\n#3 /var/www/firefly-iii/vendor/rcrowe/twigbridge/src/Engine/Compiler.php(99): TwigBridge\\Bridge->loadTemplate('/var/www/firefl...')\n#4 /var/www/firefly-iii/vendor/rcrowe/twigbridge/src/Engine/Twig.php(91): TwigBridge\\Engine\\Compiler->load('/var/www/firefl...')\n#5 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/View/View.php(143): TwigBridge\\Engine\\Twig->get('/var/www/firefl...', Ar in /var/www/firefly-iii/vendor/twig/twig/src/Cache/FilesystemCache.php on line 57
```

**Comment by JC5** [comment]
I don't know anything about Unraid, sorry. Maybe somebody else does.

**Comment by wranglatang** [comment]
Okay, Weird! I just forced the container to re-download and start. Looks like its back up again! Hmm
