### ISSUE TITLE
Very long loading time when server has no internet access

### ISSUE THREAD

**Issue by SuperSandro2000** [firefly-iii/firefly-iii#3427]
**Bug description**
I am running Firefly III version 5.2.6, and my problem is:

When the webserver has no internet connectivity it takes a really long time to open the first page cause it is waiting for a curl timeout.

**Steps to reproduce**
- Remove internet access from the web server
- open firefly and wait

**Extra info**
``Error! Guzzle: cURL error 7: Failed to connect to version.firefly-iii.org port 443: Connection timed out (see https://curl.haxx.se/libcurl/c/libcurl-errors.html)``

```
2020-06-03T21:30:37.438484181Z [2020-06-03 23:30:37] production.ERROR: cURL error 7: Failed to connect to version.firefly-iii.org port 443: Connection timed out (see https://curl.haxx.se/libcurl/c/libcurl-e
rrors.html)
2020-06-03T21:30:37.438763850Z [2020-06-03 23:30:37] production.ERROR: #0 /var/www/html/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(155): GuzzleHttp\Handler\CurlFactory::createRejection()
2020-06-03T21:30:37.438801219Z #1 /var/www/html/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(105): GuzzleHttp\Handler\CurlFactory::finishError()
2020-06-03T21:30:37.438829728Z #2 /var/www/html/vendor/guzzlehttp/guzzle/src/Handler/CurlHandler.php(43): GuzzleHttp\Handler\CurlFactory::finish()
2020-06-03T21:30:37.438841096Z #3 /var/www/html/vendor/guzzlehttp/guzzle/src/Handler/Proxy.php(28): GuzzleHttp\Handler\CurlHandler->__invoke()
2020-06-03T21:30:37.438853917Z #4 /var/www/html/vendor/guzzlehttp/guzzle/src/Handler/Proxy.php(51): GuzzleHttp\Handler\Proxy::GuzzleHttp\Handler\{closure}()
2020-06-03T21:30:37.438865652Z #5 /var/www/html/vendor/guzzlehttp/guzzle/src/PrepareBodyMiddleware.php(37): GuzzleHttp\Handler\Proxy::GuzzleHttp\Handler\{closure}()
2020-06-03T21:30:37.438876079Z #6 /var/www/html/vendor/guzzlehttp/guzzle/src/Middleware.php(29): GuzzleHttp\PrepareBodyMiddleware->__invoke()
2020-06-03T21:30:37.438886269Z #7 /var/www/html/vendor/guzzlehttp/guzzle/src/RedirectMiddleware.php(70): GuzzleHttp\Middleware::GuzzleHttp\{closure}()
2020-06-03T21:30:37.438896714Z #8 /var/www/html/vendor/guzzlehttp/guzzle/src/Middleware.php(59): GuzzleHttp\RedirectMiddleware->__invoke()
2020-06-03T21:30:37.438906654Z #9 /var/www/html/vendor/guzzlehttp/guzzle/src/HandlerStack.php(71): GuzzleHttp\Middleware::GuzzleHttp\{closure}()
2020-06-03T21:30:37.438916650Z #10 /var/www/html/vendor/guzzlehttp/guzzle/src/Client.php(352): GuzzleHttp\HandlerStack->__invoke()
2020-06-03T21:30:37.438928135Z #11 /var/www/html/vendor/guzzlehttp/guzzle/src/Client.php(163): GuzzleHttp\Client->transfer()
2020-06-03T21:30:37.438940647Z #12 /var/www/html/vendor/guzzlehttp/guzzle/src/Client.php(183): GuzzleHttp\Client->requestAsync()
2020-06-03T21:30:37.438953088Z #13 /var/www/html/app/Services/FireflyIIIOrg/Update/UpdateRequest.php(176): GuzzleHttp\Client->request()
2020-06-03T21:30:37.438962226Z #14 /var/www/html/app/Services/FireflyIIIOrg/Update/UpdateRequest.php(52): FireflyIII\Services\FireflyIIIOrg\Update\UpdateRequest->contactServer()
2020-06-03T21:30:37.438973730Z #15 /var/www/html/app/Helpers/Update/UpdateTrait.php(49): FireflyIII\Services\FireflyIIIOrg\Update\UpdateRequest->getUpdateInformation()
2020-06-03T21:30:37.438988345Z #16 /var/www/html/app/Handlers/Events/VersionCheckEventHandler.php(84): FireflyIII\Handlers\Events\VersionCheckEventHandler->getLatestRelease()
2020-06-03T21:30:37.438997964Z #17 [internal function]: FireflyIII\Handlers\Events\VersionCheckEventHandler->checkForUpdates()
2020-06-03T21:30:37.439010368Z #18 /var/www/html/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(388): call_user_func_array()
2020-06-03T21:30:37.439021002Z #19 /var/www/html/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(218): Illuminate\Events\Dispatcher->Illuminate\Events\{closure}()
2020-06-03T21:30:37.439031649Z #20 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php(477): Illuminate\Events\Dispatcher->dispatch()
2020-06-03T21:30:37.439043704Z #21 /var/www/html/app/Http/Controllers/HomeController.php(149): event()
2020-06-03T21:30:37.439054862Z #22 [internal function]: FireflyIII\Http\Controllers\HomeController->index()
2020-06-03T21:30:37.439078625Z #23 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): call_user_func_array()
2020-06-03T21:30:37.439092013Z #24 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\Routing\Controller->callAction()
2020-06-03T21:30:37.439105117Z #25 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Route.php(219): Illuminate\Routing\ControllerDispatcher->dispatch()
2020-06-03T21:30:37.439118443Z #26 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Route.php(176): Illuminate\Routing\Route->runController()
2020-06-03T21:30:37.439130829Z #27 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(681): Illuminate\Routing\Route->run()
2020-06-03T21:30:37.439142536Z #28 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(130): Illuminate\Routing\Router->Illuminate\Routing\{closure}()
2020-06-03T21:30:37.439154536Z #29 /var/www/html/app/Http/Middleware/Installer.php(81): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
2020-06-03T21:30:37.439167970Z #30 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): FireflyIII\Http\Middleware\Installer->handle()
2020-06-03T21:30:37.439182111Z #31 /var/www/html/app/Http/Controllers/Controller.php(107): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
2020-06-03T21:30:37.439191554Z #32 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(153): FireflyIII\Http\Controllers\Controller->FireflyIII\Http\Controllers\{closure}()
2020-06-03T21:30:37.439203844Z #33 /var/www/html/app/Http/Middleware/InterestingMessage.php(59): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
2020-06-03T21:30:37.439215644Z #34 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): FireflyIII\Http\Middleware\InterestingMessage->handle()
2020-06-03T21:30:37.439226324Z #35 /var/www/html/app/Http/Middleware/Binder.php(79): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
2020-06-03T21:30:37.439238608Z #36 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): FireflyIII\Http\Middleware\Binder->handle()
2020-06-03T21:30:37.439251515Z #37 /var/www/html/app/Http/Middleware/Range.php(60): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
2020-06-03T21:30:37.439263641Z #38 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): FireflyIII\Http\Middleware\Range->handle()
2020-06-03T21:30:37.439276153Z #39 /var/www/html/vendor/jc5/google2fa-laravel/src/Middleware.php(29): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
2020-06-03T21:30:37.439288363Z #40 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): PragmaRX\Google2FALaravel\Middleware->handle()
2020-06-03T21:30:37.439300995Z #41 /var/www/html/app/Http/Middleware/Authenticate.php(74): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
2020-06-03T21:30:37.439313248Z #42 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): FireflyIII\Http\Middleware\Authenticate->handle()
2020-06-03T21:30:37.439337504Z #43 /var/www/html/vendor/laravel/passport/src/Http/Middleware/CreateFreshApiToken.php(50): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
2020-06-03T21:30:37.439352080Z #44 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Laravel\Passport\Http\Middleware\CreateFreshApiToken->handle()
2020-06-03T21:30:37.439365943Z #45 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(76): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
2020-06-03T21:30:37.439379827Z #46 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Foundation\Http\Middleware\VerifyCsrfToken->handle()
2020-06-03T21:30:37.439393601Z #47 /var/www/html/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
2020-06-03T21:30:37.439409175Z #48 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\View\Middleware\ShareErrorsFromSession->handle()
2020-06-03T21:30:37.439422689Z #49 /var/www/html/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(56): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
2020-06-03T21:30:37.439436938Z #50 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Session\Middleware\StartSession->handle()
2020-06-03T21:30:37.439450573Z #51 /var/www/html/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
2020-06-03T21:30:37.439464445Z #52 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle()
2020-06-03T21:30:37.439477373Z #53 /var/www/html/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(66): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
2020-06-03T21:30:37.439491452Z #54 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Cookie\Middleware\EncryptCookies->handle()
2020-06-03T21:30:37.439504544Z #55 /var/www/html/app/Http/Middleware/Sandstorm.php(54): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
2020-06-03T21:30:37.439516997Z #56 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): FireflyIII\Http\Middleware\Sandstorm->handle()
2020-06-03T21:30:37.439530564Z #57 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(105): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
2020-06-03T21:30:37.439543825Z #58 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(683): Illuminate\Pipeline\Pipeline->then()
2020-06-03T21:30:37.439556328Z #59 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(658): Illuminate\Routing\Router->runRouteWithinStack()
2020-06-03T21:30:37.439564998Z #60 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(624): Illuminate\Routing\Router->runRoute()
2020-06-03T21:30:37.439585775Z #61 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(613): Illuminate\Routing\Router->dispatchToRoute()
2020-06-03T21:30:37.439598863Z #62 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(170): Illuminate\Routing\Router->dispatch()
2020-06-03T21:30:37.439612137Z #63 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(130): Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}()
2020-06-03T21:30:37.439624292Z #64 /var/www/html/app/Http/Middleware/InstallationId.php(59): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
2020-06-03T21:30:37.439634044Z #65 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): FireflyIII\Http\Middleware\InstallationId->handle()
2020-06-03T21:30:37.439645013Z #66 /var/www/html/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
2020-06-03T21:30:37.439656209Z #67 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Fideloper\Proxy\TrustProxies->handle()
2020-06-03T21:30:37.439667586Z #68 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
2020-06-03T21:30:37.439680308Z #69 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle()
2020-06-03T21:30:37.439691586Z #70 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
2020-06-03T21:30:37.439702136Z #71 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle()
2020-06-03T21:30:37.439713495Z #72 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
2020-06-03T21:30:37.439725538Z #73 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Foundation\Http\Middleware\ValidatePostSize->handle()
2020-06-03T21:30:37.439738112Z #74 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(63): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closur
e}()
2020-06-03T21:30:37.439749801Z #75 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle()
2020-06-03T21:30:37.439762575Z #76 /var/www/html/app/Http/Middleware/SecureHeaders.php(51): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
2020-06-03T21:30:37.439773863Z #77 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): FireflyIII\Http\Middleware\SecureHeaders->handle()
2020-06-03T21:30:37.439785240Z #78 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(105): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
2020-06-03T21:30:37.439808426Z #79 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(145): Illuminate\Pipeline\Pipeline->then()
2020-06-03T21:30:37.439821774Z #80 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(110): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter()
2020-06-03T21:30:37.439833792Z #81 /var/www/html/public/index.php(76): Illuminate\Foundation\Http\Kernel->handle()
2020-06-03T21:30:37.439845657Z #82 {main}
2020-06-03T21:30:37.439856593Z [2020-06-03 23:30:37] production.ERROR: Update information contains an error.
2020-06-03T21:30:37.439868725Z [2020-06-03 23:30:37] production.ERROR: Guzzle: cURL error 7: Failed to connect to version.firefly-iii.org port 443: Connection timed out (see https://curl.haxx.se/libcurl/c/l
ibcurl-errors.html)
```

**Bonus points**

- I searched and nobody reported this bug before
- I have added a stack trace from my log files 
- I have added a screenshot.
- I was able to replicate it on the demo site https://demo.firefly-iii.org/

**Comment by JC5** [comment]
Indeed. Nicely spotted! I have added a time-out to the entry.

I will leave this ticket open to make sure that Firefly III doesn't keep trying after it failed (so a second refresh won't be as long).
