### ISSUE TITLE
Cannot build 5.2.7 with composer

### ISSUE THREAD

**Issue by sephrat** [firefly-iii/firefly-iii#3443]
**Bug description**
When I run `composer create-project grumpydictator/firefly-iii --no-dev --prefer-dist firefly-iii-updated 5.2.7` I get an error at step `@php artisan firefly:instructions install`
Tried the same command with 5.2.6, it works fine.

**Extra info**
```
[2020-06-06 11:39:02] local.ERROR: SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Name or service not known (SQL: select `id`, `name`, `data` from `configuration` where `name` = installation_id and `configuration`.`deleted_at` is null limit 1) {"exception":"[object] (Illuminate\\Database\\QueryException(code: 2002): SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Name or service not known (SQL: select `id`, `name`, `data` from `configuration` where `name` = installation_id and `configuration`.`deleted_at` is null limit 1) at /var/www/firefly-iii-updated/vendor/laravel/framework/src/Illuminate/Database/Connection.php:669)
[stacktrace]
#0 /var/www/firefly-iii-updated/vendor/laravel/framework/src/Illuminate/Database/Connection.php(629): Illuminate\\Database\\Connection->runQueryCallback()
#1 /var/www/firefly-iii-updated/vendor/laravel/framework/src/Illuminate/Database/Connection.php(338): Illuminate\\Database\\Connection->run()
#2 /var/www/firefly-iii-updated/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2149): Illuminate\\Database\\Connection->select()
#3 /var/www/firefly-iii-updated/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2137): Illuminate\\Database\\Query\\Builder->runSelect()
#4 /var/www/firefly-iii-updated/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2609): Illuminate\\Database\\Query\\Builder->Illuminate\\Database\\Query\\{closure}()
#5 /var/www/firefly-iii-updated/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2138): Illuminate\\Database\\Query\\Builder->onceWithColumns()
#6 /var/www/firefly-iii-updated/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(537): Illuminate\\Database\\Query\\Builder->get()
#7 /var/www/firefly-iii-updated/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(521): Illuminate\\Database\\Eloquent\\Builder->getModels()
#8 /var/www/firefly-iii-updated/vendor/laravel/framework/src/Illuminate/Database/Concerns/BuildsQueries.php(143): Illuminate\\Database\\Eloquent\\Builder->get()
#9 /var/www/firefly-iii-updated/app/Support/FireflyConfig.php(83): Illuminate\\Database\\Eloquent\\Builder->first()
#10 /var/www/firefly-iii-updated/app/Support/System/GeneratesInstallationId.php(19): FireflyIII\\Support\\FireflyConfig->get()
#11 /var/www/firefly-iii-updated/app/Console/Commands/UpgradeFireflyInstructions.php(56): FireflyIII\\Console\\Commands\\UpgradeFireflyInstructions->generateInstallationId()
#12 [internal function]: FireflyIII\\Console\\Commands\\UpgradeFireflyInstructions->handle()
#13 /var/www/firefly-iii-updated/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(32): call_user_func_array()
#14 /var/www/firefly-iii-updated/vendor/laravel/framework/src/Illuminate/Container/Util.php(36): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#15 /var/www/firefly-iii-updated/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(90): Illuminate\\Container\\Util::unwrapIfClosure()
#16 /var/www/firefly-iii-updated/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(34): Illuminate\\Container\\BoundMethod::callBoundMethod()
#17 /var/www/firefly-iii-updated/vendor/laravel/framework/src/Illuminate/Container/Container.php(590): Illuminate\\Container\\BoundMethod::call()
#18 /var/www/firefly-iii-updated/vendor/laravel/framework/src/Illuminate/Console/Command.php(134): Illuminate\\Container\\Container->call()
#19 /var/www/firefly-iii-updated/vendor/symfony/console/Command/Command.php(255): Illuminate\\Console\\Command->execute()
#20 /var/www/firefly-iii-updated/vendor/laravel/framework/src/Illuminate/Console/Command.php(121): Symfony\\Component\\Console\\Command\\Command->run()
#21 /var/www/firefly-iii-updated/vendor/symfony/console/Application.php(1000): Illuminate\\Console\\Command->run()
#22 /var/www/firefly-iii-updated/vendor/symfony/console/Application.php(271): Symfony\\Component\\Console\\Application->doRunCommand()
#23 /var/www/firefly-iii-updated/vendor/symfony/console/Application.php(147): Symfony\\Component\\Console\\Application->doRun()
#24 /var/www/firefly-iii-updated/vendor/laravel/framework/src/Illuminate/Console/Application.php(93): Symfony\\Component\\Console\\Application->run()
#25 /var/www/firefly-iii-updated/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(131): Illuminate\\Console\\Application->run()
#26 /var/www/firefly-iii-updated/artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle()
#27 {main}

[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDOException(code: 2002): SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Name or service not known at /var/www/firefly-iii-updated/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:31)
[stacktrace]
#0 /var/www/firefly-iii-updated/vendor/laravel/framework/src/Illuminate/Database/Connectors/Connector.php(67): Doctrine\\DBAL\\Driver\\PDOConnection->__construct()
#1 /var/www/firefly-iii-updated/vendor/laravel/framework/src/Illuminate/Database/Connectors/Connector.php(46): Illuminate\\Database\\Connectors\\Connector->createPdoConnection()
#2 /var/www/firefly-iii-updated/vendor/laravel/framework/src/Illuminate/Database/Connectors/MySqlConnector.php(24): Illuminate\\Database\\Connectors\\Connector->createConnection()
#3 /var/www/firefly-iii-updated/vendor/laravel/framework/src/Illuminate/Database/Connectors/ConnectionFactory.php(182): Illuminate\\Database\\Connectors\\MySqlConnector->connect()
#4 [internal function]: Illuminate\\Database\\Connectors\\ConnectionFactory->Illuminate\\Database\\Connectors\\{closure}()
#5 /var/www/firefly-iii-updated/vendor/laravel/framework/src/Illuminate/Database/Connection.php(924): call_user_func()
#6 /var/www/firefly-iii-updated/vendor/laravel/framework/src/Illuminate/Database/Connection.php(959): Illuminate\\Database\\Connection->getPdo()
#7 /var/www/firefly-iii-updated/vendor/laravel/framework/src/Illuminate/Database/Connection.php(404): Illuminate\\Database\\Connection->getReadPdo()
#8 /var/www/firefly-iii-updated/vendor/laravel/framework/src/Illuminate/Database/Connection.php(330): Illuminate\\Database\\Connection->getPdoForSelect()
#9 /var/www/firefly-iii-updated/vendor/laravel/framework/src/Illuminate/Database/Connection.php(662): Illuminate\\Database\\Connection->Illuminate\\Database\\{closure}()
#10 /var/www/firefly-iii-updated/vendor/laravel/framework/src/Illuminate/Database/Connection.php(629): Illuminate\\Database\\Connection->runQueryCallback()
#11 /var/www/firefly-iii-updated/vendor/laravel/framework/src/Illuminate/Database/Connection.php(338): Illuminate\\Database\\Connection->run()
#12 /var/www/firefly-iii-updated/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2149): Illuminate\\Database\\Connection->select()
#13 /var/www/firefly-iii-updated/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2137): Illuminate\\Database\\Query\\Builder->runSelect()
#14 /var/www/firefly-iii-updated/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2609): Illuminate\\Database\\Query\\Builder->Illuminate\\Database\\Query\\{closure}()
#15 /var/www/firefly-iii-updated/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2138): Illuminate\\Database\\Query\\Builder->onceWithColumns()
#16 /var/www/firefly-iii-updated/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(537): Illuminate\\Database\\Query\\Builder->get()
#17 /var/www/firefly-iii-updated/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(521): Illuminate\\Database\\Eloquent\\Builder->getModels()
#18 /var/www/firefly-iii-updated/vendor/laravel/framework/src/Illuminate/Database/Concerns/BuildsQueries.php(143): Illuminate\\Database\\Eloquent\\Builder->get()
#19 /var/www/firefly-iii-updated/app/Support/FireflyConfig.php(83): Illuminate\\Database\\Eloquent\\Builder->first()
#20 /var/www/firefly-iii-updated/app/Support/System/GeneratesInstallationId.php(19): FireflyIII\\Support\\FireflyConfig->get()
#21 /var/www/firefly-iii-updated/app/Console/Commands/UpgradeFireflyInstructions.php(56): FireflyIII\\Console\\Commands\\UpgradeFireflyInstructions->generateInstallationId()
#22 [internal function]: FireflyIII\\Console\\Commands\\UpgradeFireflyInstructions->handle()
#23 /var/www/firefly-iii-updated/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(32): call_user_func_array()
#24 /var/www/firefly-iii-updated/vendor/laravel/framework/src/Illuminate/Container/Util.php(36): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#25 /var/www/firefly-iii-updated/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(90): Illuminate\\Container\\Util::unwrapIfClosure()
#26 /var/www/firefly-iii-updated/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(34): Illuminate\\Container\\BoundMethod::callBoundMethod()
#27 /var/www/firefly-iii-updated/vendor/laravel/framework/src/Illuminate/Container/Container.php(590): Illuminate\\Container\\BoundMethod::call()
#28 /var/www/firefly-iii-updated/vendor/laravel/framework/src/Illuminate/Console/Command.php(134): Illuminate\\Container\\Container->call()
#29 /var/www/firefly-iii-updated/vendor/symfony/console/Command/Command.php(255): Illuminate\\Console\\Command->execute()
#30 /var/www/firefly-iii-updated/vendor/laravel/framework/src/Illuminate/Console/Command.php(121): Symfony\\Component\\Console\\Command\\Command->run()
#31 /var/www/firefly-iii-updated/vendor/symfony/console/Application.php(1000): Illuminate\\Console\\Command->run()
#32 /var/www/firefly-iii-updated/vendor/symfony/console/Application.php(271): Symfony\\Component\\Console\\Application->doRunCommand()
#33 /var/www/firefly-iii-updated/vendor/symfony/console/Application.php(147): Symfony\\Component\\Console\\Application->doRun()
#34 /var/www/firefly-iii-updated/vendor/laravel/framework/src/Illuminate/Console/Application.php(93): Symfony\\Component\\Console\\Application->run()
#35 /var/www/firefly-iii-updated/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(131): Illuminate\\Console\\Application->run()
#36 /var/www/firefly-iii-updated/artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle()
#37 {main}

[previous exception] [object] (PDOException(code: 2002): SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Name or service not known at /var/www/firefly-iii-updated/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:27)
[stacktrace]
#0 /var/www/firefly-iii-updated/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php(27): PDO->__construct()
#1 /var/www/firefly-iii-updated/vendor/laravel/framework/src/Illuminate/Database/Connectors/Connector.php(67): Doctrine\\DBAL\\Driver\\PDOConnection->__construct()
#2 /var/www/firefly-iii-updated/vendor/laravel/framework/src/Illuminate/Database/Connectors/Connector.php(46): Illuminate\\Database\\Connectors\\Connector->createPdoConnection()
#3 /var/www/firefly-iii-updated/vendor/laravel/framework/src/Illuminate/Database/Connectors/MySqlConnector.php(24): Illuminate\\Database\\Connectors\\Connector->createConnection()
#4 /var/www/firefly-iii-updated/vendor/laravel/framework/src/Illuminate/Database/Connectors/ConnectionFactory.php(182): Illuminate\\Database\\Connectors\\MySqlConnector->connect()
#5 [internal function]: Illuminate\\Database\\Connectors\\ConnectionFactory->Illuminate\\Database\\Connectors\\{closure}()
#6 /var/www/firefly-iii-updated/vendor/laravel/framework/src/Illuminate/Database/Connection.php(924): call_user_func()
#7 /var/www/firefly-iii-updated/vendor/laravel/framework/src/Illuminate/Database/Connection.php(959): Illuminate\\Database\\Connection->getPdo()
#8 /var/www/firefly-iii-updated/vendor/laravel/framework/src/Illuminate/Database/Connection.php(404): Illuminate\\Database\\Connection->getReadPdo()
#9 /var/www/firefly-iii-updated/vendor/laravel/framework/src/Illuminate/Database/Connection.php(330): Illuminate\\Database\\Connection->getPdoForSelect()
#10 /var/www/firefly-iii-updated/vendor/laravel/framework/src/Illuminate/Database/Connection.php(662): Illuminate\\Database\\Connection->Illuminate\\Database\\{closure}()
#11 /var/www/firefly-iii-updated/vendor/laravel/framework/src/Illuminate/Database/Connection.php(629): Illuminate\\Database\\Connection->runQueryCallback()
#12 /var/www/firefly-iii-updated/vendor/laravel/framework/src/Illuminate/Database/Connection.php(338): Illuminate\\Database\\Connection->run()
#13 /var/www/firefly-iii-updated/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2149): Illuminate\\Database\\Connection->select()
#14 /var/www/firefly-iii-updated/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2137): Illuminate\\Database\\Query\\Builder->runSelect()
#15 /var/www/firefly-iii-updated/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2609): Illuminate\\Database\\Query\\Builder->Illuminate\\Database\\Query\\{closure}()
#16 /var/www/firefly-iii-updated/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2138): Illuminate\\Database\\Query\\Builder->onceWithColumns()
#17 /var/www/firefly-iii-updated/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(537): Illuminate\\Database\\Query\\Builder->get()
#18 /var/www/firefly-iii-updated/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(521): Illuminate\\Database\\Eloquent\\Builder->getModels()
#19 /var/www/firefly-iii-updated/vendor/laravel/framework/src/Illuminate/Database/Concerns/BuildsQueries.php(143): Illuminate\\Database\\Eloquent\\Builder->get()
#20 /var/www/firefly-iii-updated/app/Support/FireflyConfig.php(83): Illuminate\\Database\\Eloquent\\Builder->first()
#21 /var/www/firefly-iii-updated/app/Support/System/GeneratesInstallationId.php(19): FireflyIII\\Support\\FireflyConfig->get()
#22 /var/www/firefly-iii-updated/app/Console/Commands/UpgradeFireflyInstructions.php(56): FireflyIII\\Console\\Commands\\UpgradeFireflyInstructions->generateInstallationId()
#23 [internal function]: FireflyIII\\Console\\Commands\\UpgradeFireflyInstructions->handle()
#24 /var/www/firefly-iii-updated/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(32): call_user_func_array()
#25 /var/www/firefly-iii-updated/vendor/laravel/framework/src/Illuminate/Container/Util.php(36): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#26 /var/www/firefly-iii-updated/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(90): Illuminate\\Container\\Util::unwrapIfClosure()
#27 /var/www/firefly-iii-updated/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(34): Illuminate\\Container\\BoundMethod::callBoundMethod()
#28 /var/www/firefly-iii-updated/vendor/laravel/framework/src/Illuminate/Container/Container.php(590): Illuminate\\Container\\BoundMethod::call()
#29 /var/www/firefly-iii-updated/vendor/laravel/framework/src/Illuminate/Console/Command.php(134): Illuminate\\Container\\Container->call()
#30 /var/www/firefly-iii-updated/vendor/symfony/console/Command/Command.php(255): Illuminate\\Console\\Command->execute()
#31 /var/www/firefly-iii-updated/vendor/laravel/framework/src/Illuminate/Console/Command.php(121): Symfony\\Component\\Console\\Command\\Command->run()
#32 /var/www/firefly-iii-updated/vendor/symfony/console/Application.php(1000): Illuminate\\Console\\Command->run()
#33 /var/www/firefly-iii-updated/vendor/symfony/console/Application.php(271): Symfony\\Component\\Console\\Application->doRunCommand()
#34 /var/www/firefly-iii-updated/vendor/symfony/console/Application.php(147): Symfony\\Component\\Console\\Application->doRun()
#35 /var/www/firefly-iii-updated/vendor/laravel/framework/src/Illuminate/Console/Application.php(93): Symfony\\Component\\Console\\Application->run()
#36 /var/www/firefly-iii-updated/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(131): Illuminate\\Console\\Application->run()
#37 /var/www/firefly-iii-updated/artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle()
#38 {main}

[previous exception] [object] (PDOException(code: 0): PDO::__construct(): php_network_getaddresses: getaddrinfo failed: Name or service not known at /var/www/firefly-iii-updated/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:27)
[stacktrace]
#0 /var/www/firefly-iii-updated/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php(27): PDO->__construct()
#1 /var/www/firefly-iii-updated/vendor/laravel/framework/src/Illuminate/Database/Connectors/Connector.php(67): Doctrine\\DBAL\\Driver\\PDOConnection->__construct()
#2 /var/www/firefly-iii-updated/vendor/laravel/framework/src/Illuminate/Database/Connectors/Connector.php(46): Illuminate\\Database\\Connectors\\Connector->createPdoConnection()
#3 /var/www/firefly-iii-updated/vendor/laravel/framework/src/Illuminate/Database/Connectors/MySqlConnector.php(24): Illuminate\\Database\\Connectors\\Connector->createConnection()
#4 /var/www/firefly-iii-updated/vendor/laravel/framework/src/Illuminate/Database/Connectors/ConnectionFactory.php(182): Illuminate\\Database\\Connectors\\MySqlConnector->connect()
#5 [internal function]: Illuminate\\Database\\Connectors\\ConnectionFactory->Illuminate\\Database\\Connectors\\{closure}()
#6 /var/www/firefly-iii-updated/vendor/laravel/framework/src/Illuminate/Database/Connection.php(924): call_user_func()
#7 /var/www/firefly-iii-updated/vendor/laravel/framework/src/Illuminate/Database/Connection.php(959): Illuminate\\Database\\Connection->getPdo()
#8 /var/www/firefly-iii-updated/vendor/laravel/framework/src/Illuminate/Database/Connection.php(404): Illuminate\\Database\\Connection->getReadPdo()
#9 /var/www/firefly-iii-updated/vendor/laravel/framework/src/Illuminate/Database/Connection.php(330): Illuminate\\Database\\Connection->getPdoForSelect()
#10 /var/www/firefly-iii-updated/vendor/laravel/framework/src/Illuminate/Database/Connection.php(662): Illuminate\\Database\\Connection->Illuminate\\Database\\{closure}()
#11 /var/www/firefly-iii-updated/vendor/laravel/framework/src/Illuminate/Database/Connection.php(629): Illuminate\\Database\\Connection->runQueryCallback()
#12 /var/www/firefly-iii-updated/vendor/laravel/framework/src/Illuminate/Database/Connection.php(338): Illuminate\\Database\\Connection->run()
#13 /var/www/firefly-iii-updated/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2149): Illuminate\\Database\\Connection->select()
#14 /var/www/firefly-iii-updated/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2137): Illuminate\\Database\\Query\\Builder->runSelect()
#15 /var/www/firefly-iii-updated/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2609): Illuminate\\Database\\Query\\Builder->Illuminate\\Database\\Query\\{closure}()
#16 /var/www/firefly-iii-updated/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2138): Illuminate\\Database\\Query\\Builder->onceWithColumns()
#17 /var/www/firefly-iii-updated/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(537): Illuminate\\Database\\Query\\Builder->get()
#18 /var/www/firefly-iii-updated/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(521): Illuminate\\Database\\Eloquent\\Builder->getModels()
#19 /var/www/firefly-iii-updated/vendor/laravel/framework/src/Illuminate/Database/Concerns/BuildsQueries.php(143): Illuminate\\Database\\Eloquent\\Builder->get()
#20 /var/www/firefly-iii-updated/app/Support/FireflyConfig.php(83): Illuminate\\Database\\Eloquent\\Builder->first()
#21 /var/www/firefly-iii-updated/app/Support/System/GeneratesInstallationId.php(19): FireflyIII\\Support\\FireflyConfig->get()
#22 /var/www/firefly-iii-updated/app/Console/Commands/UpgradeFireflyInstructions.php(56): FireflyIII\\Console\\Commands\\UpgradeFireflyInstructions->generateInstallationId()
#23 [internal function]: FireflyIII\\Console\\Commands\\UpgradeFireflyInstructions->handle()
#24 /var/www/firefly-iii-updated/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(32): call_user_func_array()
#25 /var/www/firefly-iii-updated/vendor/laravel/framework/src/Illuminate/Container/Util.php(36): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#26 /var/www/firefly-iii-updated/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(90): Illuminate\\Container\\Util::unwrapIfClosure()
#27 /var/www/firefly-iii-updated/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(34): Illuminate\\Container\\BoundMethod::callBoundMethod()
#28 /var/www/firefly-iii-updated/vendor/laravel/framework/src/Illuminate/Container/Container.php(590): Illuminate\\Container\\BoundMethod::call()
#29 /var/www/firefly-iii-updated/vendor/laravel/framework/src/Illuminate/Console/Command.php(134): Illuminate\\Container\\Container->call()
#30 /var/www/firefly-iii-updated/vendor/symfony/console/Command/Command.php(255): Illuminate\\Console\\Command->execute()
#31 /var/www/firefly-iii-updated/vendor/laravel/framework/src/Illuminate/Console/Command.php(121): Symfony\\Component\\Console\\Command\\Command->run()
#32 /var/www/firefly-iii-updated/vendor/symfony/console/Application.php(1000): Illuminate\\Console\\Command->run()
#33 /var/www/firefly-iii-updated/vendor/symfony/console/Application.php(271): Symfony\\Component\\Console\\Application->doRunCommand()
#34 /var/www/firefly-iii-updated/vendor/symfony/console/Application.php(147): Symfony\\Component\\Console\\Application->doRun()
#35 /var/www/firefly-iii-updated/vendor/laravel/framework/src/Illuminate/Console/Application.php(93): Symfony\\Component\\Console\\Application->run()
#36 /var/www/firefly-iii-updated/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(131): Illuminate\\Console\\Application->run()
#37 /var/www/firefly-iii-updated/artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle()
#38 {main}
"} 

In Connection.php line 669:
                                                                               
  SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Name o  
  r service not known (SQL: select `id`, `name`, `data` from `configuration`   
  where `name` = installation_id and `configuration`.`deleted_at` is null lim  
  it 1)                                                                        
                                                                               

In PDOConnection.php line 31:
                                                                               
  SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Name o  
  r service not known                                                          
                                                                               

In PDOConnection.php line 27:
                                                                               
  SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Name o  
  r service not known                                                          
                                                                               

In PDOConnection.php line 27:
                                                                               
  PDO::__construct(): php_network_getaddresses: getaddrinfo failed: Name or s  
  ervice not known                                                             
                                                                               

Script @php artisan firefly:instructions install handling the post-install-cmd event returned with error code 1
```

**Comment by JC5** [comment]
Confirmed. Stay tuned for 5.2.8.

**Comment by JC5** [comment]
5.2.8 should work as expected.

**Comment by JC5** [comment]
Yes it works! Thanks for letting me know!

**Comment by sephrat** [comment]
Thanks for the quick fix!
