### ISSUE TITLE
failed to open stream: No such file or directory (on cache file)

### ISSUE THREAD

**Issue by DenBeke** [firefly-iii/firefly-iii#3446]
I am running Firefly III version 5.2.7 with Docker.

**Description**

Since yesterdays update I can't load any page after the login page:

```
[2020-06-07 14:34:47] local.ERROR: Exception is: {"class":"ErrorException","errorMessage":"file_put_contents(\/var\/www\/firefly-iii\/storage\/framework\/cache\/data\/1e\/71\/1e714d5d3c4978639d54f96e8937cf8a32894468): failed to open stream: No such file or directory","time":"Sun, 07 Jun 2020 14:34:47 +0200","file":"\/var\/www\/firefly-iii\/vendor\/laravel\/framework\/src\/Illuminate\/Filesystem\/Filesystem.php","line":133,"code":0,"version":"5.2.7","url":"https:\/\/ripple.arry.be","userAgent":"Mozilla\/5.0 (Linux; Android 10; SNE-LX1) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/83.0.4103.96 Mobile Safari\/537.36","json":true}  
```

I already tried restarting/removing/purging the container.

I'm running (on the same docker host) a Firefly installation with exactly the same configuration.
This other installation doesn't have any problems at all. But the installation I'm running here for a friend has the `file_put_contents` error.

**Extra info**

Debug information generated at 2020-06-07 14:28:15 Europe/Brussels for Firefly III version *5.2.7*.

| Scope | Version |
| --- | --- |
| Firefly III | 5.2.7 |
| Firefly III API | 1.1.0 |
| PHP | 7.3.18 |
| Host | Linux |

| System info | Value |
| --- | --- |
| Installation ID | b2c27d92-be90-5c10-8589-005df5b314e6 |
| Using docker? | true |
| Telemetry | false |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | warning, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Interface | apache2handler |
| Default language | en_US |
| Default locale | equal |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | mysql |
| Login provider | eloquent  |
| Trusted proxies (.env) | ** |

| User info | Value |
| --- | --- |
| Session start | 2020-06-01 00:00:00 |
| Session end | 2020-06-30 23:59:59 |
| Session first | 0001-03-01 00:00:00 |
| User ID | 1 |
| User language | nl_NL |
| User locale | nl_NL |
| Attempt at "nl_NL.utf8" | 'nl_NL.utf8' |
| Attempt at "nl_NL.UTF-8" | 'nl_NL.UTF-8' |
| User agent | Mozilla/5.0 (Linux; Android 10; SNE-LX1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.96 Mobile Safari/537.36 |

**Comment by DenBeke** [comment]
The complete stacktrace:

```
Jun 7, 2020 @ 14:34:47.000	[2020-06-07 14:34:47] local.ERROR: file_put_contents(/var/www/firefly-iii/storage/framework/cache/data/1e/71/1e714d5d3c4978639d54f96e8937cf8a32894468): failed to open stream: No such file or directory {"userId":1,"exception":"[object] (ErrorException(code: 0): file_put_contents(/var/www/firefly-iii/storage/framework/cache/data/1e/71/1e714d5d3c4978639d54f96e8937cf8a32894468): failed to open stream: No such file or directory at /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php:133)
Jun 7, 2020 @ 14:34:47.000	[stacktrace]
Jun 7, 2020 @ 14:34:47.000	#0 [internal function]: Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError(2, 'file_put_conten...', '/var/www/firefl...', 133, Array)
Jun 7, 2020 @ 14:34:47.000	#1 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php(133): file_put_contents('/var/www/firefl...', '9999999999O:37:...', 2)
Jun 7, 2020 @ 14:34:47.000	#2 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Cache/FileStore.php(74): Illuminate\\Filesystem\\Filesystem->put('/var/www/firefl...', '9999999999O:37:...', true)
Jun 7, 2020 @ 14:34:47.000	#3 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Cache/FileStore.php(152): Illuminate\\Cache\\FileStore->put('e1f4be84e30749b...', Object(FireflyIII\\Models\\TransactionCurrency), 0)
Jun 7, 2020 @ 14:34:47.000	#4 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Cache/Repository.php(355): Illuminate\\Cache\\FileStore->forever('e1f4be84e30749b...', Object(FireflyIII\\Models\\TransactionCurrency))
Jun 7, 2020 @ 14:34:47.000	#5 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Cache/CacheManager.php(378): Illuminate\\Cache\\Repository->forever('e1f4be84e30749b...', Object(FireflyIII\\Models\\TransactionCurrency))
Jun 7, 2020 @ 14:34:47.000	#6 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(261): Illuminate\\Cache\\CacheManager->__call('forever', Array)
Jun 7, 2020 @ 14:34:47.000	#7 /var/www/firefly-iii/app/Support/CacheProperties.php(95): Illuminate\\Support\\Facades\\Facade::__callStatic('forever', Array)
Jun 7, 2020 @ 14:34:47.000	#8 /var/www/firefly-iii/app/Support/Amount.php(298): FireflyIII\\Support\\CacheProperties->store(Object(FireflyIII\\Models\\TransactionCurrency))
Jun 7, 2020 @ 14:34:47.000	#9 /var/www/firefly-iii/app/Support/Amount.php(250): FireflyIII\\Support\\Amount->getDefaultCurrencyByUser(Object(FireflyIII\\User))
Jun 7, 2020 @ 14:34:47.000	#10 /var/www/firefly-iii/app/Http/Middleware/Range.php(98): FireflyIII\\Support\\Amount->getDefaultCurrency()
Jun 7, 2020 @ 14:34:47.000	#11 /var/www/firefly-iii/app/Http/Middleware/Range.php(54): FireflyIII\\Http\\Middleware\\Range->configureView()
Jun 7, 2020 @ 14:34:47.000	#12 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): FireflyIII\\Http\\Middleware\\Range->handle(Object(Illuminate\\Http\\Request), Object(Closure))
Jun 7, 2020 @ 14:34:47.000	#13 /var/www/firefly-iii/vendor/jc5/google2fa-laravel/src/Middleware.php(29): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
Jun 7, 2020 @ 14:34:47.000	#14 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): PragmaRX\\Google2FALaravel\\Middleware->handle(Object(Illuminate\\Http\\Request), Object(Closure))
Jun 7, 2020 @ 14:34:47.000	#15 /var/www/firefly-iii/app/Http/Middleware/Authenticate.php(74): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
Jun 7, 2020 @ 14:34:47.000	#16 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): FireflyIII\\Http\\Middleware\\Authenticate->handle(Object(Illuminate\\Http\\Request), Object(Closure))
Jun 7, 2020 @ 14:34:47.000	#17 /var/www/firefly-iii/vendor/laravel/passport/src/Http/Middleware/CreateFreshApiToken.php(50): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
Jun 7, 2020 @ 14:34:47.000	#18 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Laravel\\Passport\\Http\\Middleware\\CreateFreshApiToken->handle(Object(Illuminate\\Http\\Request), Object(Closure))
Jun 7, 2020 @ 14:34:47.000	#19 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(76): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
Jun 7, 2020 @ 14:34:47.000	#20 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle(Object(Illuminate\\Http\\Request), Object(Closure))
Jun 7, 2020 @ 14:34:47.000	#21 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
Jun 7, 2020 @ 14:34:47.000	#22 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
Jun 7, 2020 @ 14:34:47.000	#23 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(56): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
Jun 7, 2020 @ 14:34:47.000	#24 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Session\\Middleware\\StartSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
Jun 7, 2020 @ 14:34:47.000	#25 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
Jun 7, 2020 @ 14:34:47.000	#26 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle(Object(Illuminate\\Http\\Request), Object(Closure))
Jun 7, 2020 @ 14:34:47.000	#27 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(66): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
Jun 7, 2020 @ 14:34:47.000	#28 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
Jun 7, 2020 @ 14:34:47.000	#29 /var/www/firefly-iii/app/Http/Middleware/Sandstorm.php(54): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
Jun 7, 2020 @ 14:34:47.000	#30 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): FireflyIII\\Http\\Middleware\\Sandstorm->handle(Object(Illuminate\\Http\\Request), Object(Closure))
Jun 7, 2020 @ 14:34:47.000	#31 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(105): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
Jun 7, 2020 @ 14:34:47.000	#32 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Routing/Router.php(683): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
Jun 7, 2020 @ 14:34:47.000	#33 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Routing/Router.php(658): Illuminate\\Routing\\Router->runRouteWithinStack(Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request))
Jun 7, 2020 @ 14:34:47.000	#34 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Routing/Router.php(624): Illuminate\\Routing\\Router->runRoute(Object(Illuminate\\Http\\Request), Object(Illuminate\\Routing\\Route))
Jun 7, 2020 @ 14:34:47.000	#35 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Routing/Router.php(613): Illuminate\\Routing\\Router->dispatchToRoute(Object(Illuminate\\Http\\Request))
Jun 7, 2020 @ 14:34:47.000	#36 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(170): Illuminate\\Routing\\Router->dispatch(Object(Illuminate\\Http\\Request))
Jun 7, 2020 @ 14:34:47.000	#37 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(130): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}(Object(Illuminate\\Http\\Request))
Jun 7, 2020 @ 14:34:47.000	#38 /var/www/firefly-iii/app/Http/Middleware/InstallationId.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
Jun 7, 2020 @ 14:34:47.000	#39 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): FireflyIII\\Http\\Middleware\\InstallationId->handle(Object(Illuminate\\Http\\Request), Object(Closure))
Jun 7, 2020 @ 14:34:47.000	#40 /var/www/firefly-iii/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
Jun 7, 2020 @ 14:34:47.000	#41 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Fideloper\\Proxy\\TrustProxies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
Jun 7, 2020 @ 14:34:47.000	#42 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
Jun 7, 2020 @ 14:34:47.000	#43 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
Jun 7, 2020 @ 14:34:47.000	#44 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
Jun 7, 2020 @ 14:34:47.000	#45 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
Jun 7, 2020 @ 14:34:47.000	#46 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
Jun 7, 2020 @ 14:34:47.000	#47 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
Jun 7, 2020 @ 14:34:47.000	#48 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(63): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
Jun 7, 2020 @ 14:34:47.000	#49 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode->handle(Object(Illuminate\\Http\\Request), Object(Closure))
Jun 7, 2020 @ 14:34:47.000	#50 /var/www/firefly-iii/app/Http/Middleware/SecureHeaders.php(51): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
Jun 7, 2020 @ 14:34:47.000	#51 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): FireflyIII\\Http\\Middleware\\SecureHeaders->handle(Object(Illuminate\\Http\\Request), Object(Closure))
Jun 7, 2020 @ 14:34:47.000	#52 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(105): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
Jun 7, 2020 @ 14:34:47.000	#53 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(145): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
Jun 7, 2020 @ 14:34:47.000	#54 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(110): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
Jun 7, 2020 @ 14:34:47.000	#55 /var/www/firefly-iii/public/index.php(76): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
Jun 7, 2020 @ 14:34:47.000	#56 {main}
Jun 7, 2020 @ 14:34:47.000	"} 
```

**Comment by JC5** [comment]
https://github.com/firefly-iii/firefly-iii/issues/3445

Browse to /flush, recreate the container

**Comment by DenBeke** [comment]
Thank you very much, @JC5 !

**Comment by JC5** [comment]
I've just finished building the 5.2.8 Docker image again. If you can, remove the container, **also** remove the image and restart the container. Your host should re-download the image before starting Firefly III again. With a little luck this fixes the issue permanently.

You can verify that you have the latest version of the Docker image because the `/debug` page will report that you're running PHP 7.4 instead of 7.3.

**Comment by DenBeke** [comment]
I just upgraded the images. All is working perfectly fine!
Thank you!!

**Comment by AlexKalopsia** [comment]
I'm on 5.2.8 and got the same issue.

`file_put_contents(/var/www/firefly-iii/storage/framework/cache/data/1e/cd/1ecddfc1e3080f06b990c6b6cdc47777c0b6ce01): failed to open stream: No such file or directory `

The logs don't show anything from around this timestamp.
