### ISSUE TITLE
Failed to update of docker from 5.2.8 to 5.3.0

### ISSUE THREAD

**Issue by tinganhsu** [firefly-iii/firefly-iii#3522]
**Bug description**
I am running Firefly III version 5.2.8, and my problem is:
when i try to upgrade to 5.3.0 using docker, web fail to initalize

**Steps to reproduce**

update the docker version to lastest(5.3.0)

**Extra info**

last line of docker logs
```
Go!
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.18.0.4. Set the 'ServerName' directive globally to suppress this message
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.18.0.4. Set the 'ServerName' directive globally to suppress this message
[Fri Jul 03 22:42:25.250846 2020] [mpm_prefork:notice] [pid 1] AH00163: Apache/2.4.38 (Debian) PHP/7.4.7 OpenSSL/1.1.1d configured -- resuming normal operations
[Fri Jul 03 22:42:25.250938 2020] [core:notice] [pid 1] AH00094: Command line: 'apache2 -D FOREGROUND'
```
**Bonus points**

- I searched and nobody reported this bug before

**Comment by vjFaLk** [comment]
I'm having the same issue. The latest docker image isn't working for me. 

Getting this when I open up the login page -

**Comment by Nightmareish** [comment]
Also having this same issue, with the same error messages. My Firefly instance is unaccessible.

**Comment by JC5** [comment]
What user are you running the docker images under?

**Comment by Nightmareish** [comment]
My docker images run as root because I'm lazy.

**Comment by tinganhsu** [comment]
I'm using unraid system and saw the command of it web gui said: 
```
root@localhost:# /usr/local/emhttp/plugins/dynamix.docker.manager/scripts/docker run -d --name='Firefly-III'
```
I think it is using root for docker

**Comment by Nightmareish** [comment]
> I'm using unraid system and saw the command of it web gui said:
> 
> ```
> root@localhost:# /usr/local/emhttp/plugins/dynamix.docker.manager/scripts/docker run -d --name='Firefly-III'
> ```
> 
> I think it is using root for docker

I'm using Unraid too, and yes, unless you spend the time to configure it otherwise, all dockers run as root.

**Comment by JC5** [comment]
Ah Unraid. That explains it. I'll wait for people without Unraid to run into issues before I start hacking away, if you don't mind.

**Comment by vjFaLk** [comment]
@JC5 Hey, I'm not using Unraid. I changed the permissions of the volume Firefly III so that the error log would work, and then I got this - 

```
7/3/2020 9:48:50 PM[2020-07-03 21:48:50] local.ERROR: Exception is: {"class":"ErrorException","errorMessage":"Trying to get property 'data' of non-object","time":"Fri, 03 Jul 2020 21:48:50 +0530","file":"\/var\/www\/firefly-iii\/app\/Http\/Controllers\/Controller.php","line":58,"code":0,"version":"5.3.0","url":"http:\/\/192.168.1.33:8889","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/83.0.4103.116 Safari\/537.36","json":true}
7/3/2020 9:48:50 PM[2020-07-03 21:48:50] local.ERROR: Exception when mailing: Address in mailbox given [] does not comply with RFC 2822, 3.6.2.
7/3/2020 9:48:50 PM[2020-07-03 21:48:50] local.ERROR: Trying to get property 'data' of non-object {"exception":"[object] (ErrorException(code: 0): Trying to get property 'data' of non-object at /var/www/firefly-iii/app/Http/Controllers/Controller.php:58)
7/3/2020 9:48:50 PM[stacktrace]
7/3/2020 9:48:50 PM#0 /var/www/firefly-iii/app/Http/Controllers/Controller.php(58): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError()
7/3/2020 9:48:50 PM#1 /var/www/firefly-iii/app/Http/Controllers/HomeController.php(55): FireflyIII\\Http\\Controllers\\Controller->__construct()
7/3/2020 9:48:50 PM#2 [internal function]: FireflyIII\\Http\\Controllers\\HomeController->__construct()
7/3/2020 9:48:50 PM#3 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Container/Container.php(845): ReflectionClass->newInstanceArgs()
7/3/2020 9:48:50 PM#4 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Container/Container.php(687): Illuminate\\Container\\Container->build()
7/3/2020 9:48:50 PM#5 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(796): Illuminate\\Container\\Container->resolve()
7/3/2020 9:48:50 PM#6 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Container/Container.php(633): Illuminate\\Foundation\\Application->resolve()
7/3/2020 9:48:50 PM#7 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(781): Illuminate\\Container\\Container->make()
7/3/2020 9:48:50 PM#8 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Routing/Route.php(253): Illuminate\\Foundation\\Application->make()
7/3/2020 9:48:50 PM#9 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Routing/Route.php(970): Illuminate\\Routing\\Route->getController()
7/3/2020 9:48:50 PM#10 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Routing/Route.php(931): Illuminate\\Routing\\Route->controllerMiddleware()
7/3/2020 9:48:50 PM#11 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Routing/Router.php(702): Illuminate\\Routing\\Route->gatherMiddleware()
7/3/2020 9:48:50 PM#12 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Routing/Router.php(678): Illuminate\\Routing\\Router->gatherRouteMiddleware()
7/3/2020 9:48:50 PM#13 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Routing/Router.php(662): Illuminate\\Routing\\Router->runRouteWithinStack()
7/3/2020 9:48:50 PM#14 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Routing/Router.php(628): Illuminate\\Routing\\Router->runRoute()
7/3/2020 9:48:50 PM#15 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Routing/Router.php(617): Illuminate\\Routing\\Router->dispatchToRoute()
7/3/2020 9:48:50 PM#16 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(165): Illuminate\\Routing\\Router->dispatch()
7/3/2020 9:48:50 PM#17 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}()
7/3/2020 9:48:50 PM#18 /var/www/firefly-iii/app/Http/Middleware/InstallationId.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
7/3/2020 9:48:50 PM#19 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): FireflyIII\\Http\\Middleware\\InstallationId->handle()
7/3/2020 9:48:50 PM#20 /var/www/firefly-iii/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
7/3/2020 9:48:50 PM#21 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Fideloper\\Proxy\\TrustProxies->handle()
7/3/2020 9:48:50 PM#22 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
7/3/2020 9:48:50 PM#23 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
7/3/2020 9:48:50 PM#24 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
7/3/2020 9:48:50 PM#25 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
7/3/2020 9:48:50 PM#26 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
7/3/2020 9:48:50 PM#27 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle()
7/3/2020 9:48:50 PM#28 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(63): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
7/3/2020 9:48:50 PM#29 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode->handle()
7/3/2020 9:48:50 PM#30 /var/www/firefly-iii/app/Http/Middleware/SecureHeaders.php(51): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
7/3/2020 9:48:50 PM#31 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): FireflyIII\\Http\\Middleware\\SecureHeaders->handle()
7/3/2020 9:48:50 PM#32 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
7/3/2020 9:48:50 PM#33 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(140): Illuminate\\Pipeline\\Pipeline->then()
7/3/2020 9:48:50 PM#34 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(109): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter()
7/3/2020 9:48:50 PM#35 /var/www/firefly-iii/public/index.php(76): Illuminate\\Foundation\\Http\\Kernel->handle()
7/3/2020 9:48:50 PM#36 {main}
7/3/2020 9:48:50 PM"}
```

**Comment by JC5** [comment]
That points to a database issue I'm afraid, and it may have nothing to do with this error. Could you do me a favor, and spin up the `develop` tag? It should be ready when this page reports green (4 times):

https://travis-ci.com/github/firefly-iii/docker/builds/174231907

**Comment by vjFaLk** [comment]
Okay, so on upgrading to develop, it seems to have fixed the issue...and when I rolled back to stable it's still working...?

Anothing thing I noticed is that the app is now being served at port 8080, and I think it used to be served at port 80? I might be mistaken...

**Comment by JC5** [comment]
Yes, the port 8080 thing is in the release notes. So if you upgraded to 5.3.0, you should've noticed 😉 .

But I'm surprised the roll back and forth is still working. Do you have any mapping to the entire directory `/var/www/firefly-iii/storage`?

**Comment by vjFaLk** [comment]
I swear I went through the notes twice! Didn't notice the 8080 thing at all.

Nah, I don't have any mounts at all. Docker seems to have created volumes
for the export and upload folder however.

**Comment by hecspc** [comment]
Same issue as OP. Running docker on proxmox VM

**Comment by Dreytac** [comment]
The Unraid issue is due to the change of the port from 80 to 8080. In Unraid, you need to remove the old host port (for me was port 5080 => 80) and add a new one redirecting port 5080 to 8080.

**Comment by tinganhsu** [comment]
Thanks!! @Dreytac @JC5 
I've found that I did not notice that docker image had change port to 8080
after change in docker template and nignx setting, everything work normally.!

**Comment by Dreytac** [comment]
@tinganhsu I didn't notice it either, until I stumbled on this.

As a side note: If you're using an Nginx proxy on Unraid, you just need to change the port from 80 to 8080 in the proxy config for most configurations.

**Comment by lguima** [comment]
I'm using `docker-compose` locally and getting the same log as @tinganhsu.

Can I point to `develop` too? Or do a downgrade back to the previous version?

**Comment by wkunker** [comment]
Changing the port from 80 to 8080 in my docker-compose.yml worked for me. Is there any risk of the port changing again in the future? Thanks

**Comment by JC5** [comment]
@lguima Have you tried changing the port already?
@wkunker I was planning on changing the port every release just to mess with people. Kidding 😉 . It shouldn't change in the future again.

**Comment by lguima** [comment]
I'm using WSL 2 and I changed the port but I got lost in which URL I should access.

At the end, I just needed to change from `localhost` to the container IP.

Thank you!
