### ISSUE TITLE
Spectre Importer runs into 500 server error: nextPossibleRefreshAt must be string, null used

### ISSUE THREAD

**Issue by totti4ever** [firefly-iii/firefly-iii#3543]
**Bug description**
I am running Firefly III spectre import version 1.0.2 (docker), and my problem is:

Spectre Importer --> click _start here_ --> click _upload_ without selecting a file (expected result would be the list of accounts from spectre)
and woosh, I get an 500 server error (stack trace below)

Importing from spectre by docker cmd line and earlier produced json files works like a charm!

**Steps to reproduce**
Afterwards this error already comes straight after clicking _start here_, only restarting the container helps to get one step further as described in the beginning.

**Extra info**
```
2020-07-10T08:42:05.876156228Z [2020-07-10 10:42:05] production.DEBUG: About to get connections.
2020-07-10T08:42:05.876775589Z [2020-07-10 10:42:05] production.DEBUG: ListConnectionsRequest::get()
2020-07-10T08:42:05.877167351Z [2020-07-10 10:42:05] production.DEBUG: setParameters {"customer_id":"24xxxxxxxxxxxxxx"}
2020-07-10T08:42:06.036253085Z [2020-07-10 10:42:06] production.ERROR: Typed property App\Services\Spectre\Model\Connection::$nextPossibleRefreshAt must be string, null used {"exception":"[object] (TypeError(code: 0): Typed property App\\Services\\Spectre\\Model\\Connection::$nextPossibleRefreshAt must be string, null used at /var/www/html/app/Services/Spectre/Model/Connection.php:67)
2020-07-10T08:42:06.036294273Z [stacktrace]
2020-07-10T08:42:06.036304863Z #0 /var/www/html/app/Services/Spectre/Response/ListConnectionsResponse.php(51): App\\Services\\Spectre\\Model\\Connection::fromArray()
2020-07-10T08:42:06.036315070Z #1 /var/www/html/app/Services/Spectre/Request/ListConnectionsRequest.php(80): App\\Services\\Spectre\\Response\\ListConnectionsResponse->__construct()
2020-07-10T08:42:06.036325096Z #2 /var/www/html/app/Http/Controllers/Import/ConnectionController.php(120): App\\Services\\Spectre\\Request\\ListConnectionsRequest->get()
2020-07-10T08:42:06.036334372Z #3 [internal function]: App\\Http\\Controllers\\Import\\ConnectionController->index()
2020-07-10T08:42:06.036343608Z #4 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): call_user_func_array()
2020-07-10T08:42:06.036351909Z #5 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\\Routing\\Controller->callAction()
2020-07-10T08:42:06.036360481Z #6 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Route.php(239): Illuminate\\Routing\\ControllerDispatcher->dispatch()
2020-07-10T08:42:06.036368905Z #7 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Route.php(196): Illuminate\\Routing\\Route->runController()
2020-07-10T08:42:06.036377810Z #8 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(685): Illuminate\\Routing\\Route->run()
2020-07-10T08:42:06.036386267Z #9 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}()
2020-07-10T08:42:06.036394844Z #10 /var/www/html/app/Http/Middleware/ConnectionSelected.php(51): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
2020-07-10T08:42:06.036403466Z #11 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): App\\Http\\Middleware\\ConnectionSelected->handle()
2020-07-10T08:42:06.036413571Z #12 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(41): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
2020-07-10T08:42:06.036422818Z #13 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle()
2020-07-10T08:42:06.036431527Z #14 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(76): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
2020-07-10T08:42:06.036440237Z #15 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle()
2020-07-10T08:42:06.036448881Z #16 /var/www/html/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
2020-07-10T08:42:06.036468866Z #17 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle()
2020-07-10T08:42:06.036478253Z #18 /var/www/html/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(116): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
2020-07-10T08:42:06.036487073Z #19 /var/www/html/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(62): Illuminate\\Session\\Middleware\\StartSession->handleStatefulRequest()
2020-07-10T08:42:06.036495795Z #20 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Session\\Middleware\\StartSession->handle()
2020-07-10T08:42:06.036504397Z #21 /var/www/html/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
2020-07-10T08:42:06.036513147Z #22 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle()
2020-07-10T08:42:06.036521588Z #23 /var/www/html/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(66): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
2020-07-10T08:42:06.036530151Z #24 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle()
2020-07-10T08:42:06.036539258Z #25 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
2020-07-10T08:42:06.036548118Z #26 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(687): Illuminate\\Pipeline\\Pipeline->then()
2020-07-10T08:42:06.036556550Z #27 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(662): Illuminate\\Routing\\Router->runRouteWithinStack()
2020-07-10T08:42:06.036564962Z #28 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(628): Illuminate\\Routing\\Router->runRoute()
2020-07-10T08:42:06.036573245Z #29 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(617): Illuminate\\Routing\\Router->dispatchToRoute()
2020-07-10T08:42:06.036581670Z #30 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(165): Illuminate\\Routing\\Router->dispatch()
2020-07-10T08:42:06.036589866Z #31 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}()
2020-07-10T08:42:06.036598939Z #32 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
2020-07-10T08:42:06.036607776Z #33 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
2020-07-10T08:42:06.036621522Z #34 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
2020-07-10T08:42:06.036630909Z #35 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
2020-07-10T08:42:06.036639345Z #36 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
2020-07-10T08:42:06.036647974Z #37 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle()
2020-07-10T08:42:06.036657379Z #38 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(63): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
2020-07-10T08:42:06.036666241Z #39 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode->handle()
2020-07-10T08:42:06.036674933Z #40 /var/www/html/vendor/fruitcake/laravel-cors/src/HandleCors.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
2020-07-10T08:42:06.036683260Z #41 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Fruitcake\\Cors\\HandleCors->handle()
2020-07-10T08:42:06.036691531Z #42 /var/www/html/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
2020-07-10T08:42:06.036699940Z #43 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Fideloper\\Proxy\\TrustProxies->handle()
2020-07-10T08:42:06.036708118Z #44 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
2020-07-10T08:42:06.036716637Z #45 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(140): Illuminate\\Pipeline\\Pipeline->then()
2020-07-10T08:42:06.036724641Z #46 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(109): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter()
2020-07-10T08:42:06.036733113Z #47 /var/www/html/public/index.php(75): Illuminate\\Foundation\\Http\\Kernel->handle()
2020-07-10T08:42:06.036742201Z #48 {main}
2020-07-10T08:42:06.036749467Z "}
2020-07-10T08:42:06.051575067Z 172.16.0.10 - - [10/Jul/2020:10:42:05 +0200] "GET /import/spectre-connections HTTP/1.1" 500 2516 "http://spectre/import/start" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_5) AppleWebKit/537.xy (KHTML, like Gecko) Chrome/83.0.xxxx.zzz Safari/537.xy"
```

**Comment by JC5** [comment]
Weird! This is an internal Spectre thing that supposedly never says NULL. 

I kicked of another Docker build, on the `develop` tag. It has some other stuff as well but I included a fix for this issue. Could you switch tags, download the new image, and check out what happens?

**Comment by totti4ever** [comment]
perfectly fixed the issue! thanks a lot :-)

I was on dev anyway, didn't mention that - sorry

**Comment by JC5** [comment]
Not to worry! Case closed. :+1:

**Comment by JC5** [comment]
1.0.3 is building.
