### ISSUE TITLE
Spectre Import: Error when trying to set a specific range during spectre import

### ISSUE THREAD

**Issue by totti4ever** [firefly-iii/firefly-iii#3548]
**Bug description**
I am running Firefly III spectre import dev-version@docker, and my problem is:

I selected specific range during setup of the import configuration in the web UI and when I clicked on next, I again got an 500 server error

**Extra info**
```
2020-07-11T13:00:10.110853282Z [2020-07-11 15:00:10] production.ERROR: Call to a member function format() on string {"exception":"[object] (Error(code: 0): Call to a member function format() on string at /var/www/html/app/Services/Configuration/Configuration.php:445)
2020-07-11T13:00:10.110887367Z [stacktrace]
2020-07-11T13:00:10.110896939Z #0 /var/www/html/app/Http/Controllers/Import/ConfigurationController.php(147): App\\Services\\Configuration\\Configuration->updateDateRange()
2020-07-11T13:00:10.110907032Z #1 [internal function]: App\\Http\\Controllers\\Import\\ConfigurationController->post()
2020-07-11T13:00:10.110916223Z #2 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): call_user_func_array()
...
```

**Comment by JC5** [comment]
Found and fixed. :)

**Comment by totti4ever** [comment]
successfully tested it

**Comment by JC5** [comment]
New version is released.
