### ISSUE TITLE
GuzzleException: Server error (500 server error)

### ISSUE THREAD

**Issue by totti4ever** [firefly-iii/firefly-iii#3558]
**Bug description**
I am running Firefly III spectre importer at latest-dev@docker, and my problem is:

at the end of the import (cmd-line docker) the logs show an exception. Funny enough, sometimes it works - but from 5 accounts I started the import for, only 1 was able to write it's result to firefly.

Sorry to bother you again....

**Steps to reproduce**
run the spectre import by docker command line command

**Extra info**
see stack trace below

**Bonus points**
```
[2020-07-13 12:59:50] production.DEBUG: Going to collect all target accounts from Firefly III.
[2020-07-13 13:00:22] production.ERROR: GuzzleException: Server error: `GET http://fireflyiii:8080/api/v1/accounts?page=2` resulted in a `500 Internal Server Error` response:
{"message":"Internal Firefly III Exception: file_put_contents(\/var\/www\/firefly-iii\/storage\/framework\/cache\/data\/ (truncated...)
 {"exception":"[object] (GrumpyDictator\\FFIIIApiSupport\\Exceptions\\ApiHttpException(code: 0): GuzzleException: Server error: `GET http://fireflyiii:8080/api/v1/accounts?page=2` resulted in a `500 Internal Server Error` response:
{\"message\":\"Internal Firefly III Exception: file_put_contents(\\/var\\/www\\/firefly-iii\\/storage\\/framework\\/cache\\/data\\/ (truncated...)
 at /var/www/html/vendor/firefly-iii/api-support-classes/src/Request/GetAccountsRequest.php:91)
[stacktrace]
#0 /var/www/html/app/Services/Sync/GenerateTransactions.php(77): GrumpyDictator\\FFIIIApiSupport\\Request\\GetAccountsRequest->get()
#1 /var/www/html/app/Services/Sync/RoutineManager.php(164): App\\Services\\Sync\\GenerateTransactions->collectTargetAccounts()
#2 /var/www/html/app/Console/StartSync.php(62): App\\Services\\Sync\\RoutineManager->start()
#3 /var/www/html/app/Console/Commands/SpectreImport.php(113): App\\Console\\Commands\\SpectreImport->startSync()
#4 [internal function]: App\\Console\\Commands\\SpectreImport->handle()
#5 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(33): call_user_func_array()
#6 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Util.php(37): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#7 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(91): Illuminate\\Container\\Util::unwrapIfClosure()
#8 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(35): Illuminate\\Container\\BoundMethod::callBoundMethod()
#9 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(592): Illuminate\\Container\\BoundMethod::call()
#10 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(134): Illuminate\\Container\\Container->call()
#11 /var/www/html/vendor/symfony/console/Command/Command.php(258): Illuminate\\Console\\Command->execute()
#12 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(121): Symfony\\Component\\Console\\Command\\Command->run()
#13 /var/www/html/vendor/symfony/console/Application.php(911): Illuminate\\Console\\Command->run()
#14 /var/www/html/vendor/symfony/console/Application.php(264): Symfony\\Component\\Console\\Application->doRunCommand()
#15 /var/www/html/vendor/symfony/console/Application.php(140): Symfony\\Component\\Console\\Application->doRun()
#16 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Application.php(93): Symfony\\Component\\Console\\Application->run()
#17 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(129): Illuminate\\Console\\Application->run()
#18 /var/www/html/artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle()
#19 {main}
"}

In GetAccountsRequest.php line 91:

  GuzzleException: Server error: `GET http://fireflyiii:8080/api/v1/accounts?
  page=2` resulted in a `500 Internal Server Error` response:
  {"message":"Internal Firefly III Exception: file_put_contents(\/var\/www\/f
  irefly-iii\/storage\/framework\/cache\/data\/ (truncated...)

```

**Comment by JC5** [comment]
I rebuilt the 5.3.1 image due to a permission error. Please delete your current `latest` image for Firefly III itself and download it again. Let me know if it works. My apologies for the problem.

**Comment by totti4ever** [comment]
I actually the other issue, but didn't link it in my head to my problem - sorry!

Issues is fixed for me now anyways!

P.S.: simple pull was enough, didn't have to remove latest image

**Comment by JC5** [comment]
5.3.2 is out, and should fix this issue. For my administration, please open a new issue if problems persist.
