### ISSUE TITLE
5.3.1 installation issue

### ISSUE THREAD

**Issue by captainark** [firefly-iii/firefly-iii#3559]
**Bug description**
I am running Firefly III version 5.3.1, and my problem is:

I'm getting an error message when trying to install this version from composer.

**Steps to reproduce**

Run `composer create-project grumpydictator/firefly-iii --no-dev --prefer-dist firefly-5.3.1 5.3.1`.

**Extra info**

Here's the error message I'm getting : 

```
> @php artisan firefly:instructions install
[2020-07-13 14:00:20] local.ERROR: Query exception while polling for config var: could not find driver (SQL: select `id`, `name`, `data` from `configuration` where `name` = installation_id and `configuration`.`deleted_at` is null limit 1)
[2020-07-13 14:00:20] local.ERROR: #0 /var/www/firefly-5.3.1/vendor/laravel/framework/src/Illuminate/Database/Connection.php(631): Illuminate\Database\Connection->runQueryCallback()
#1 /var/www/firefly-5.3.1/vendor/laravel/framework/src/Illuminate/Database/Connection.php(339): Illuminate\Database\Connection->run()
#2 /var/www/firefly-5.3.1/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2203): Illuminate\Database\Connection->select()
#3 /var/www/firefly-5.3.1/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2191): Illuminate\Database\Query\Builder->runSelect()
#4 /var/www/firefly-5.3.1/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2686): Illuminate\Database\Query\Builder->Illuminate\Database\Query\{closure}()
#5 /var/www/firefly-5.3.1/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2192): Illuminate\Database\Query\Builder->onceWithColumns()
#6 /var/www/firefly-5.3.1/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(539): Illuminate\Database\Query\Builder->get()
#7 /var/www/firefly-5.3.1/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(523): Illuminate\Database\Eloquent\Builder->getModels()
#8 /var/www/firefly-5.3.1/vendor/laravel/framework/src/Illuminate/Database/Concerns/BuildsQueries.php(143): Illuminate\Database\Eloquent\Builder->get()
#9 /var/www/firefly-5.3.1/app/Support/FireflyConfig.php(88): Illuminate\Database\Eloquent\Builder->first()
#10 /var/www/firefly-5.3.1/app/Support/System/GeneratesInstallationId.php(40): FireflyIII\Support\FireflyConfig->get()
#11 /var/www/firefly-5.3.1/app/Console/Commands/UpgradeFireflyInstructions.php(56): FireflyIII\Console\Commands\UpgradeFireflyInstructions->generateInstallationId()
#12 [internal function]: FireflyIII\Console\Commands\UpgradeFireflyInstructions->handle()
#13 /var/www/firefly-5.3.1/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(33): call_user_func_array()
#14 /var/www/firefly-5.3.1/vendor/laravel/framework/src/Illuminate/Container/Util.php(37): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#15 /var/www/firefly-5.3.1/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(91): Illuminate\Container\Util::unwrapIfClosure()
#16 /var/www/firefly-5.3.1/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(35): Illuminate\Container\BoundMethod::callBoundMethod()
#17 /var/www/firefly-5.3.1/vendor/laravel/framework/src/Illuminate/Container/Container.php(592): Illuminate\Container\BoundMethod::call()
#18 /var/www/firefly-5.3.1/vendor/laravel/framework/src/Illuminate/Console/Command.php(134): Illuminate\Container\Container->call()
#19 /var/www/firefly-5.3.1/vendor/symfony/console/Command/Command.php(258): Illuminate\Console\Command->execute()
#20 /var/www/firefly-5.3.1/vendor/laravel/framework/src/Illuminate/Console/Command.php(121): Symfony\Component\Console\Command\Command->run()
#21 /var/www/firefly-5.3.1/vendor/symfony/console/Application.php(911): Illuminate\Console\Command->run()
#22 /var/www/firefly-5.3.1/vendor/symfony/console/Application.php(264): Symfony\Component\Console\Application->doRunCommand()
#23 /var/www/firefly-5.3.1/vendor/symfony/console/Application.php(140): Symfony\Component\Console\Application->doRun()
#24 /var/www/firefly-5.3.1/vendor/laravel/framework/src/Illuminate/Console/Application.php(93): Symfony\Component\Console\Application->run()
#25 /var/www/firefly-5.3.1/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(129): Illuminate\Console\Application->run()
#26 /var/www/firefly-5.3.1/artisan(37): Illuminate\Foundation\Console\Kernel->handle()
#27 {main}
[2020-07-13 14:00:20] local.ERROR: Exception is: {"class":"FireflyIII\\Exceptions\\FireflyException","errorMessage":"Could not poll the database: could not find driver (SQL: select `id`, `name`, `data` from `configuration` where `name` = installation_id and `configuration`.`deleted_at` is null limit 1)","time":"Mon, 13 Jul 2020 14:00:20 +0200","file":"\/var\/www\/firefly-5.3.1\/app\/Support\/FireflyConfig.php","line":92,"code":0,"version":"5.3.1","url":"http:\/\/localhost","userAgent":"Symfony","json":true}
[2020-07-13 14:00:20] local.ERROR: Could not poll the database: could not find driver (SQL: select `id`, `name`, `data` from `configuration` where `name` = installation_id and `configuration`.`deleted_at` is null limit 1) {"exception":"[object] (FireflyIII\\Exceptions\\FireflyException(code: 0): Could not poll the database: could not find driver (SQL: select `id`, `name`, `data` from `configuration` where `name` = installation_id and `configuration`.`deleted_at` is null limit 1) at /var/www/firefly-5.3.1/app/Support/FireflyConfig.php:92)
[stacktrace]
#0 /var/www/firefly-5.3.1/app/Support/System/GeneratesInstallationId.php(40): FireflyIII\\Support\\FireflyConfig->get()
#1 /var/www/firefly-5.3.1/app/Console/Commands/UpgradeFireflyInstructions.php(56): FireflyIII\\Console\\Commands\\UpgradeFireflyInstructions->generateInstallationId()
#2 [internal function]: FireflyIII\\Console\\Commands\\UpgradeFireflyInstructions->handle()
#3 /var/www/firefly-5.3.1/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(33): call_user_func_array()
#4 /var/www/firefly-5.3.1/vendor/laravel/framework/src/Illuminate/Container/Util.php(37): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#5 /var/www/firefly-5.3.1/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(91): Illuminate\\Container\\Util::unwrapIfClosure()
#6 /var/www/firefly-5.3.1/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(35): Illuminate\\Container\\BoundMethod::callBoundMethod()
#7 /var/www/firefly-5.3.1/vendor/laravel/framework/src/Illuminate/Container/Container.php(592): Illuminate\\Container\\BoundMethod::call()
#8 /var/www/firefly-5.3.1/vendor/laravel/framework/src/Illuminate/Console/Command.php(134): Illuminate\\Container\\Container->call()
#9 /var/www/firefly-5.3.1/vendor/symfony/console/Command/Command.php(258): Illuminate\\Console\\Command->execute()
#10 /var/www/firefly-5.3.1/vendor/laravel/framework/src/Illuminate/Console/Command.php(121): Symfony\\Component\\Console\\Command\\Command->run()
#11 /var/www/firefly-5.3.1/vendor/symfony/console/Application.php(911): Illuminate\\Console\\Command->run()
#12 /var/www/firefly-5.3.1/vendor/symfony/console/Application.php(264): Symfony\\Component\\Console\\Application->doRunCommand()
#13 /var/www/firefly-5.3.1/vendor/symfony/console/Application.php(140): Symfony\\Component\\Console\\Application->doRun()
#14 /var/www/firefly-5.3.1/vendor/laravel/framework/src/Illuminate/Console/Application.php(93): Symfony\\Component\\Console\\Application->run()
#15 /var/www/firefly-5.3.1/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(129): Illuminate\\Console\\Application->run()
#16 /var/www/firefly-5.3.1/artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle()
#17 {main}
"}

In FireflyConfig.php line 92:

  Could not poll the database: could not find driver (SQL: select `id`, `name
  `, `data` from `configuration` where `name` = installation_id and `configur
  ation`.`deleted_at` is null limit 1)


Script @php artisan firefly:instructions install handling the post-install-cmd event returned with error code 1
```

**Comment by JC5** [comment]
Confirmed. My apologies! I will push 5.3.2 as soon as possible to fix this.

**Comment by Bravesun** [comment]
I'm glad I'm not the only one with this problem.

**Comment by ngalfas** [comment]
yeah i just updated to 5.3.1 on a FreeBSD iocage container and i have error 500.
cleaned artisan cache, no effect. 
tried /flush, no effect.

i will wait for 5.3.2  or downgrade if i need to use it.

**Comment by JC5** [comment]
I have a fix ready, will deploy later today. Thanks all for your patience.

**Comment by JC5** [comment]
5.3.2 is out, and should fix this issue. For my administration, please open a new issue if problems persist.

**Comment by Bravesun** [comment]
Installation completed successfully.
Thanks.
