### ISSUE TITLE
Spectre import: mapping doesn't work

### ISSUE THREAD

**Issue by totti4ever** [firefly-iii/firefly-iii#3560]
**Bug description**
I am running Firefly III spectre import latest-dev@docker, and my problem is:

I try to map the accounts `Bank Account (direct debit)` and `Bank Account` from the Paypal transactions to my main account as those are the automatic transactions by Paypal to get the money from my account. The latter one is I think used for when I manually send money back to my account (from some refund or so).

**Steps to reproduce**
Start either web ui or docker command-line for (in my case) Paypal and activate mapping:
```
    "mapping": {
        "accounts": {
            "Bank Account (direct debit)": "1",
            "Bank Account": "1"
        },
    },
```

Still, the transactions create/use an additional account name `Bank Account (direct debit)` and `Bank Account` within Firefly III :-(

**Extra info**
See log of the import run below

**Bonus points**
```
[2020-07-13 14:45:51] production.DEBUG: Going to add import tag to transaction group #6433
[2020-07-13 14:45:51] production.DEBUG: Trying to send transaction #46 {"apply_rules":true,"error_if_duplicate_hash":true,"transactions":[{"type":"deposit","date":"2020-07-11 00:00:00","amount":"12.34","description":"Bank Account (direct debit)","order":0,"currency_code":"EUR","external_id":"260.....77","internal_reference":"254.....08","destination_id":532,"source_name":"Bank Account (direct debit)"}]}
[2020-07-13 14:45:52] production.INFO: Message: oV.....Fn 47: Created transaction #6434: <a href="http://fireflyiii:8080/transactions/show/6434">Bank Account (direct debit)</a> (EUR 12.34)
[2020-07-13 14:45:52] production.DEBUG: Now in Sync storeJobStatus(oV.....Fn): waiting_to_start
[2020-07-13 14:45:52] production.DEBUG: Done with storing.
```

**Comment by JC5** [comment]
I have to check, but that's not the correct format for mapping. Have you tried it through the user interface?

**Comment by totti4ever** [comment]
That snippet comes from the web interface! Here comes the whole thing (shortened only by additional accounts for privacy reasons):
```
{
    "ignore_duplicate_transactions": true,
    "rules": true,
    "skip_form": false,
    "add_import_tag": true,
    "do_mapping": true,
    "mapping": {
        "accounts": {
            "Bank Account (direct debit)": "1",
            "Shop der Deutschen Post (DPDHL Group)": "0",
			...,
        },
        "categories": {
            "income": "0",
            "shopping": "0"
        }
    },
    "identifier": "246...01",
    "connection": "254...03",
    "version": 1,
    "accounts": {
        "254...08": 532
    },
    "date_range": "partial",
    "date_range_number": 14,
    "date_range_unit": "d",
    "date_not_before": "2020-06-29",
    "date_not_after": "",
    "account_types": {
        "566": "expense",
		...
        "632": "revenue",
        "1": "asset",
        ...
        "538": "cash"
    },
    "ignore_spectre_categories": true
}
```

**Comment by JC5** [comment]
Oh right, thanks! I'll check it out. The mapping code is slightly different for Spectre. I'll get back to you :+1:

**Comment by JC5** [comment]
I pushed some experimental fixes; the develop tag is now building. The mapping may be ignored when the mapped account is a revenue account while it's expected to be an expense account. And vice versa. This is a work in progress.

**Comment by totti4ever** [comment]
Works for me now, with the quoted syntax, though. So, the docs for spectre aren't correct anymore.

Thanks again for the quick solution - helps a LOT!

**Comment by JC5** [comment]
Thx, no problem! I’ll update the docs as well :)

**Comment by totti4ever** [comment]
Hmm, at first I only deleted the transfer transaction from my main account to Paypal and the import run successfully added it again with the correct mapping.

Now, after running the importer again, I get an error  - does it have to do with this revenue/asset account classifcation? It is a normal/main account.

Or should I open another issue for this?

```
[2020-07-14 09:03:04] production.DEBUG: Amount is positive: assume transfer or deposit.
[2020-07-14 09:03:04] production.DEBUG: Account name "Bank Account (direct debit)" is mapped to Firefly III account ID "1"
[2020-07-14 09:03:04] production.WARNING: Cannot find account type for Firefly III account #1.
[2020-07-14 09:03:04] production.DEBUG: Going to download account #1
[2020-07-14 09:03:05] production.DEBUG: Discovered that account #1 is of type "asset"
[2020-07-14 09:03:05] production.DEBUG: Account type for Firefly III account #1 is "asset"
[2020-07-14 09:03:05] production.DEBUG: Parsed Spectre transaction #254.....15
[2020-07-14 09:03:05] production.DEBUG: Remove Spectre categories + tags.
[2020-07-14 09:03:05] production.DEBUG: Amount is negative: assume transfer or withdrawal.
[2020-07-14 09:03:05] production.DEBUG: Parsed Spectre transaction #254.....24
[2020-07-14 09:03:05] production.DEBUG: Remove Spectre categories + tags.
[2020-07-14 09:03:05] production.DEBUG: Amount is negative: assume transfer or withdrawal.
[2020-07-14 09:03:05] production.DEBUG: Parsed Spectre transaction #254.....25
[2020-07-14 09:03:05] production.DEBUG: Remove Spectre categories + tags.
[2020-07-14 09:03:05] production.DEBUG: Amount is negative: assume transfer or withdrawal.
[2020-07-14 09:03:05] production.ERROR: Undefined index: source_name {"exception":"[object] (ErrorException(code: 0): Undefined index: source_name at /var/www/html/app/Services/Sync/GenerateTransactions.php:214)
[stacktrace]
#0 /var/www/html/app/Services/Sync/GenerateTransactions.php(214): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError()
#1 /var/www/html/app/Services/Sync/GenerateTransactions.php(116): App\\Services\\Sync\\GenerateTransactions->generateTransaction()
#2 /var/www/html/app/Services/Sync/RoutineManager.php(166): App\\Services\\Sync\\GenerateTransactions->getTransactions()
#3 /var/www/html/app/Console/StartSync.php(62): App\\Services\\Sync\\RoutineManager->start()
#4 /var/www/html/app/Console/Commands/SpectreImport.php(113): App\\Console\\Commands\\SpectreImport->startSync()
#5 [internal function]: App\\Console\\Commands\\SpectreImport->handle()
#6 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(33): call_user_func_array()
#7 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Util.php(37): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#8 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(91): Illuminate\\Container\\Util::unwrapIfClosure()
#9 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(35): Illuminate\\Container\\BoundMethod::callBoundMethod()
#10 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(592): Illuminate\\Container\\BoundMethod::call()
#11 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(134): Illuminate\\Container\\Container->call()
#12 /var/www/html/vendor/symfony/console/Command/Command.php(258): Illuminate\\Console\\Command->execute()
#13 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(121): Symfony\\Component\\Console\\Command\\Command->run()
#14 /var/www/html/vendor/symfony/console/Application.php(911): Illuminate\\Console\\Command->run()
#15 /var/www/html/vendor/symfony/console/Application.php(264): Symfony\\Component\\Console\\Application->doRunCommand()
#16 /var/www/html/vendor/symfony/console/Application.php(140): Symfony\\Component\\Console\\Application->doRun()
#17 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Application.php(93): Symfony\\Component\\Console\\Application->run()
#18 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(129): Illuminate\\Console\\Application->run()
#19 /var/www/html/artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle()
#20 {main}
"}

In GenerateTransactions.php line 214:
  Undefined index: source_name
```

**Comment by JC5** [comment]
That's alright. I'll pick it up :)

**Comment by JC5** [comment]
Should be fixed! Docker build is ready.

**Comment by totti4ever** [comment]
works as expected!

**Comment by JC5** [comment]
Cool! I'll pick up the official version over the weekend.

**Comment by JC5** [comment]
New release is almost here.
