### ISSUE TITLE
[csv-importer] Resolving timed out, leads to hanging job

### ISSUE THREAD

**Issue by ntnn** [firefly-iii/firefly-iii#3676]
**Bug description**
I am running Firefly III version 5.3.3 and csv-importer version 2.0.1, and my problem is:

When running `csv-importer` I sometimes get a resolver error, which causes an exception to be thrown (which then sometimes hangs the job UI, but that is a different issue: #3658).

**Steps to reproduce**
I'm not entirely sure how the issue is produced in the first place.

I run a local caching DNS server. The DNS server isn't under load and responds immediately to manual requests.
I've also looked into the requested domains from the PC running `csv-importer` and it only requested the server running the firefly instance and all received requests were served.

What would help immensely to debug this would be to have the domain that was requested in the error message, akin to:
`production.ERROR: curl errored when {GET/POST/PUT}ing URI {uri}: {curl exception} ...` and then the stacktrace.

Adding a retry would also be possible to prevent intermittent errors from breaking the entire job.

**Extra info**
Log entry:
```
[2020-08-08 22:10:32] production.ERROR: cURL error 28: Resolving timed out after 3140 milliseconds (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) {"exception":"[object] (GrumpyDictator\\FFIIIApiSupport\\Exceptions\\ApiHttpException(code: 0): cURL error 28: Resolving timed out after 3140 milliseconds (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) at /var/www/html/vendor/firefly-iii/api-support-classes/src/Request/PutTransactionRequest.php:60)
[stacktrace]
#0 /var/www/html/app/Services/Import/Routine/APISubmitter.php(127): GrumpyDictator\\FFIIIApiSupport\\Request\\PutTransactionRequest->put()
#1 /var/www/html/app/Services/Import/Routine/APISubmitter.php(77): App\\Services\\Import\\Routine\\APISubmitter->addTagToGroups()
#2 /var/www/html/app/Services/Import/ImportRoutineManager.php(178): App\\Services\\Import\\Routine\\APISubmitter->processTransactions()
#3 /var/www/html/app/Http/Controllers/Import/RunController.php(115): App\\Services\\Import\\ImportRoutineManager->start()
#4 [internal function]: App\\Http\\Controllers\\Import\\RunController->start()
#5 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): call_user_func_array()
#6 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\\Routing\\Controller->callAction()
#7 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Route.php(239): Illuminate\\Routing\\ControllerDispatcher->dispatch()
#8 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Route.php(196): Illuminate\\Routing\\Route->runController()
#9 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(685): Illuminate\\Routing\\Route->run()
#10 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}()
#11 /var/www/html/app/Http/Middleware/ReadyForImport.php(47): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#12 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): App\\Http\\Middleware\\ReadyForImport->handle()
#13 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(41): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#14 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle()
#15 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(77): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#16 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle()
#17 /var/www/html/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#18 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle()
#19 /var/www/html/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(116): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#20 /var/www/html/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(62): Illuminate\\Session\\Middleware\\StartSession->handleStatefulRequest()
#21 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Session\\Middleware\\StartSession->handle()
#22 /var/www/html/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#23 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle()
#24 /var/www/html/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(67): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#25 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle()
#26 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#27 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(687): Illuminate\\Pipeline\\Pipeline->then()
#28 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(662): Illuminate\\Routing\\Router->runRouteWithinStack()
#29 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(628): Illuminate\\Routing\\Router->runRoute()
#30 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(617): Illuminate\\Routing\\Router->dispatchToRoute()
#31 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(165): Illuminate\\Routing\\Router->dispatch()
#32 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}()
#33 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#34 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#35 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#36 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#37 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#38 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle()
#39 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(63): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#40 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode->handle()
#41 /var/www/html/vendor/fruitcake/laravel-cors/src/HandleCors.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#42 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Fruitcake\\Cors\\HandleCors->handle()
#43 /var/www/html/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#44 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Fideloper\\Proxy\\TrustProxies->handle()
#45 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#46 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(140): Illuminate\\Pipeline\\Pipeline->then()
#47 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(109): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter()
#48 /var/www/html/public/index.php(99): Illuminate\\Foundation\\Http\\Kernel->handle()
#49 {main}
"}
```

**Bonus points**

[x] I searched and nobody reported this bug before
[x] I have added a stack trace from my log files 
[ ] I have added a screenshot.
[ ] I was able to replicate it on the demo site https://demo.firefly-iii.org/

**Comment by ntnn** [comment]
I've been trying to replicate the issue manually, but DNS requests using dig and nslookup never fail.
What did happen though was that requests to firefly using curl at times took a bit longer - up to five seconds:
```
100   362  100   362    0     0   1875      0 --:--:-- --:--:-- --:--:--  1875
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   362  100   362    0     0     69      0  0:00:05  0:00:05 --:--:--    76
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   362  100   362    0     0   2943      0 --:--:-- --:--:-- --:--:--  2919
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   362  100   362    0     0   1946      0 --:--:-- --:--:-- --:--:--  1946
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   362  100   362    0     0     69      0  0:00:05  0:00:05 --:--:--    83
```

And the request was just to firefly's landing page, no API request that requires actual changes.
Maybe there's an error in the used curl library which may confuse a timeout in the response from firefly with a resolve error? 

In any case I'm guessing the answers take too long or time out because firefly in my configuration can't answer all requests in time.
I've looked through the docs and I haven't seen any value to increase the amount of workers (given - I don't know if laravel even uses workers to handle requests in the first place).

**Comment by JC5** [comment]
Thanks for the expansive reports. I've seen it happen as well, and a little piece of code to retry the command is something I'll add to the list. I'm not sure what's happening with the curl library.

It's on my list to make the code that connects to Firefly III more robust.

**Comment by JC5** [comment]
New release is out, 2.0.2.

**Comment by ntnn** [comment]
Thank you, I did a couple big imports and I've had no timeouts!
