### ISSUE TITLE
YNAB Importer: Class 'App\Services\Sync\Log' not found

### ISSUE THREAD

**Issue by blinkiz** [firefly-iii/firefly-iii#3698]
Am using docker image fireflyiii/ynab-importer:release-2.0.1-amd64.
Application stops working at the step below.
Let me know if you need any more information. :slightly_smiling_face: 
```
...
[2020-08-13 18:40:56] local.INFO: Message: TUNKBgeuLDZaRXom 0: Parsed 214 YNAB transactions for further processing.  
[2020-08-13 18:40:56] local.DEBUG: Now in Sync storeJobStatus(TUNKBgeuLDZaRXom): job_running  
[2020-08-13 18:40:56] local.DEBUG: Done with storing.  
[2020-08-13 18:40:56] local.DEBUG: Generated 214 Firefly III transactions.  
[2020-08-13 18:40:56] local.DEBUG: Going to send them to Firefly III.  
[2020-08-13 18:40:56] local.ERROR: Class 'App\Services\Sync\Log' not found {"exception":"[object] (Error(code: 0): Class 'App\\Services\\Sync\\Log' not found at /var/www/html/app/Services/Sync/SendTransactions.php:66)
[stacktrace]
#0 /var/www/html/app/Services/Sync/RoutineManager.php(181): App\\Services\\Sync\\SendTransactions->send()
#1 /var/www/html/app/Http/Controllers/Import/SyncController.php(127): App\\Services\\Sync\\RoutineManager->start()
#2 [internal function]: App\\Http\\Controllers\\Import\\SyncController->start()
...
```

**Comment by JC5** [comment]
Lol whoops. Stay tuned.

**Comment by JC5** [comment]
2.0.2 is out, Docker image will be ready in a minute

https://travis-ci.com/github/firefly-iii/ynab-importer-docker/builds/179645555
