### ISSUE TITLE
CSV Importer returns error 500 (api/v1/search/accounts)

### ISSUE THREAD

**Issue by voarsh2** [firefly-iii/firefly-iii#3741]
**Bug description**
I am running Firefly III version 5.3.3, and my problem is I can't complete my CSV import.

**Steps to reproduce**
Run the importer using my data (which I can't give the whole file)

**Extra info**

``` local.DEBUG: Going to search account with name "Pennies Add Up Pot"
 local.ERROR: Server error: `GET http://firefly-iii.astrizstudios.com/firefly-iii/public/api/v1/search/accounts?query=Pennies+Add+Up+Pot&field=name&page=1` resulted in a `500 Internal Server Error` response:
<HTML>
<HEAD>
<TITLE>500 Internal Server Error</TITLE>
<BASE href="/error_docs/"><!--></BASE><!-->
< (truncated...)
 {"exception":" (App\\Exceptions\\ImportException(code: 0): Server error: `GET http://firefly-iii.astrizstudios.com/firefly-iii/public/api/v1/search/accounts?query=Pennies+Add+Up+Pot&field=name&page=1` resulted in a `500 Internal Server Error` response:
<HTML>
<HEAD>
<TITLE>500 Internal Server Error</TITLE>
<BASE href=\"/error_docs/\"><!--></BASE><!-->
< (truncated...)
 at /var/www/vhosts/vmi111998.contaboserver.net/firefly-iii.astrizstudios.com/csv-importer/app/Services/Import/Task/Accounts.php:318)

#0 /var/www/vhosts/vmi111998.contaboserver.net/firefly-iii.astrizstudios.com/csv-importer/app/Services/Import/Task/Accounts.php(127): App\\Services\\Import\\Task\\Accounts->findByName()
#1 /var/www/vhosts/vmi111998.contaboserver.net/firefly-iii.astrizstudios.com/csv-importer/app/Services/Import/Task/Accounts.php(399): App\\Services\\Import\\Task\\Accounts->findAccount()
#2 /var/www/vhosts/vmi111998.contaboserver.net/firefly-iii.astrizstudios.com/csv-importer/app/Services/Import/Task/Accounts.php(54): App\\Services\\Import\\Task\\Accounts->processTransaction()
#3 /var/www/vhosts/vmi111998.contaboserver.net/firefly-iii.astrizstudios.com/csv-importer/app/Services/Import/Routine/PseudoTransactionProcessor.php(172): App\\Services\\Import\\Task\\Accounts->process()
#4 /var/www/vhosts/vmi111998.contaboserver.net/firefly-iii.astrizstudios.com/csv-importer/app/Services/Import/Routine/PseudoTransactionProcessor.php(83): App\\Services\\Import\\Routine\\PseudoTransactionProcessor->processPseudoLine()
#5 /var/www/vhosts/vmi111998.contaboserver.net/firefly-iii.astrizstudios.com/csv-importer/app/Services/Import/ImportRoutineManager.php(170): App\\Services\\Import\\Routine\\PseudoTransactionProcessor->processPseudo()
#6 /var/www/vhosts/vmi111998.contaboserver.net/firefly-iii.astrizstudios.com/csv-importer/app/Console/StartImport.php(60): App\\Services\\Import\\ImportRoutineManager->start()
#7 /var/www/vhosts/vmi111998.contaboserver.net/firefly-iii.astrizstudios.com/csv-importer/app/Console/Commands/Import.php(109): App\\Console\\Commands\\Import->startImport()
#8 : App\\Console\\Commands\\Import->handle()
#9 /var/www/vhosts/vmi111998.contaboserver.net/firefly-iii.astrizstudios.com/csv-importer/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): call_user_func_array()
#10 /var/www/vhosts/vmi111998.contaboserver.net/firefly-iii.astrizstudios.com/csv-importer/vendor/laravel/framework/src/Illuminate/Container/Util.php(37): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#11 /var/www/vhosts/vmi111998.contaboserver.net/firefly-iii.astrizstudios.com/csv-importer/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(95): Illuminate\\Container\\Util::unwrapIfClosure()
#12 /var/www/vhosts/vmi111998.contaboserver.net/firefly-iii.astrizstudios.com/csv-importer/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(39): Illuminate\\Container\\BoundMethod::callBoundMethod()
#13 /var/www/vhosts/vmi111998.contaboserver.net/firefly-iii.astrizstudios.com/csv-importer/vendor/laravel/framework/src/Illuminate/Container/Container.php(596): Illuminate\\Container\\BoundMethod::call()
#14 /var/www/vhosts/vmi111998.contaboserver.net/firefly-iii.astrizstudios.com/csv-importer/vendor/laravel/framework/src/Illuminate/Console/Command.php(134): Illuminate\\Container\\Container->call()
#15 /var/www/vhosts/vmi111998.contaboserver.net/firefly-iii.astrizstudios.com/csv-importer/vendor/symfony/console/Command/Command.php(258): Illuminate\\Console\\Command->execute()
#16 /var/www/vhosts/vmi111998.contaboserver.net/firefly-iii.astrizstudios.com/csv-importer/vendor/laravel/framework/src/Illuminate/Console/Command.php(121): Symfony\\Component\\Console\\Command\\Command->run()
#17 /var/www/vhosts/vmi111998.contaboserver.net/firefly-iii.astrizstudios.com/csv-importer/vendor/symfony/console/Application.php(911): Illuminate\\Console\\Command->run()
#18 /var/www/vhosts/vmi111998.contaboserver.net/firefly-iii.astrizstudios.com/csv-importer/vendor/symfony/console/Application.php(264): Symfony\\Component\\Console\\Application->doRunCommand()
#19 /var/www/vhosts/vmi111998.contaboserver.net/firefly-iii.astrizstudios.com/csv-importer/vendor/symfony/console/Application.php(140): Symfony\\Component\\Console\\Application->doRun()
#20 /var/www/vhosts/vmi111998.contaboserver.net/firefly-iii.astrizstudios.com/csv-importer/vendor/laravel/framework/src/Illuminate/Console/Application.php(93): Symfony\\Component\\Console\\Application->run()
#21 /var/www/vhosts/vmi111998.contaboserver.net/firefly-iii.astrizstudios.com/csv-importer/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(129): Illuminate\\Console\\Application->run()
#22 /var/www/vhosts/vmi111998.contaboserver.net/firefly-iii.astrizstudios.com/csv-importer/artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle()
#23 {main}
"}

In Accounts.php line 318:

  Server error: `GET http://firefly-iii.astrizstudios.com/firefly-iii/public/api/v1/search/accounts?query=Pennies+Add+Up+Pot&field=name&page=1` resulted in a
   `500 Internal Server Error` response:
  <HTML>
  <HEAD>
  <TITLE>500 Internal Server Error</TITLE>
  <BASE href="/error_docs/"><!--></BASE><!-->
  < (truncated...)```

**Comment by JC5** [comment]
I would like to know the error Firefly III produced.

**Comment by voarsh2** [comment]
Hmm.

That was the output from CSV importer.

You want me to dig thru the web logs of FireFly iii?

**Comment by JC5** [comment]
Yes. Should be easy though. Just open the CSV importer and Firefly III produces a 500, apparantly. That's the root cause.

**Comment by psychowood** [comment]
If you have the token by hand (as you should since are using the importer) you can try it directly from the shell:

`curl -X GET "http://firefly-iii.astrizstudios.com/firefly-iii/public/api/v1/search/accounts?query=Pennies+Add+Up+Pot&field=name&page=1" -H  "accept: application/json" -H  "Authorization: Bearer $$$PERSONAL_ACCESS_TOKEN$$$"`

Replace $$$PERSONAL_ACCESS_TOKEN$$$ and you are ready to go.

**Comment by voarsh2** [comment]
Here's the 500 code from firefly iii:
```GET /firefly-iii/public/api/v1/search/accounts?query=Pennies+Add+Up+Pot&field=name&page=1 HTTP/1.0```

@psychowood here's your output

-bash: application/json -H Authorization:: No such file or directory
+  Done                    field=name
root@vmi339593:/var/www/vhosts/vmi111998.contaboserver.net/firefly-iii.astrizstudios.com/csv-importer# <!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8" />
        <meta http-equiv="refresh" content="0;url='http://firefly-iii.astrizstudios.com/firefly-iii/public/login'" />

        <title>Redirecting to http://firefly-iii.astrizstudios.com/firefly-iii/public/login</title>
    </head>
    <body>
        Redirecting to <a href="http://firefly-iii.astrizstudios.com/firefly-iii/public/login">http://firefly-iii.astrizstudios.com/firefly-iii/public/login</a>.
    </body>
</html>

**Comment by psychowood** [comment]
There's something wrong in your command output, are you running it on Windows or forgot some double quotes around the url?
