### ISSUE TITLE
CSV import can't find availiable firefly URL

### ISSUE THREAD

**Issue by azzamsa** [firefly-iii/firefly-iii#3749]
I am running Firefly III version **5.3.3**.

**Description**
I want to import the generated simple CSV from GNUCash, however running `run-hosted.sh` from csv importer repository resulted in the importer error: **Can't find availiable firefly URL** 

**Extra info**

![image](https://user-images.githubusercontent.com/17734314/91672409-948adf80-eb58-11ea-8ece-8c9cd70ce285.png)

However, **the url is valid**

![image](https://user-images.githubusercontent.com/17734314/91672417-a8364600-eb58-11ea-9d87-a30c0d2a38d4.png)

```bash
$ telnet  127.0.0.1 80
Trying 127.0.0.1...
Connected to 127.0.0.1.
Escape character is '^]'.
```

**run-hosted.sh**

```bash
PERSONAL_ACCESS_TOKEN=eyJ0eXA....

FIREFLY_III_URI=http://127.0.0.1:80

docker run \
--rm \
-e FIREFLY_III_ACCESS_TOKEN=$PERSONAL_ACCESS_TOKEN \
-e FIREFLY_III_URI=$FIREFLY_III_URI \
-p 8082:80 \
fireflyiii/csv-importer:latest
```

I am running firefly with docker.

``` bash
$ docker ps
CONTAINER ID        IMAGE                               COMMAND             CREATED             STATUS              PORTS                          NAMES
bb1dbaead729        jc5x/firefly-iii:latest             "/entrypoint.sh"    2 hours ago         Up 2 hours          80/tcp, 0.0.0.0:80->8080/tcp   firefly_fireflyiii_1
a8a42cbb5d08        yobasystems/alpine-mariad`
```

**csv import log**

```log

$ ./run-hosted.sh
Now in entrypoint.sh (v1.2) for Firefly III CSV importer.
Please wait for the container to start...
Firefly III CSV importer v2.0.5
PHP: cli 7.4.8 Linux
Will now run Apache web server:
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.17.0.2. Set the 'ServerName' directive globally to suppress this message
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.17.0.2. Set the 'ServerName' directive globally to suppress this message
[Sun Aug 30 23:32:00.678335 2020] [mpm_prefork:notice] [pid 1] AH00163: Apache/2.4.38 (Debian) PHP/7.4.8 OpenSSL/1.1.1d configured -- resuming normal operations
[Sun Aug 30 23:32:00.678370 2020] [core:notice] [pid 1] AH00094: Command line: 'apache2 -D FOREGROUND'
[2020-08-31 01:32:04] production.DEBUG: Now at App\Http\Controllers\IndexController::index
172.17.0.1 - - [30/Aug/2020:23:32:04 +0000] "GET / HTTP/1.1" 200 2338 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:80.0) Gecko/20100101 Firefox/80.0"
127.0.0.1 - - [30/Aug/2020:23:32:04 +0000] "GET /api/v1/about HTTP/1.1" 404 299 "-" "GuzzleHttp/6.5.5 curl/7.64.0 PHP/7.4.8"
[2020-08-31 01:32:04] production.ERROR: Return value of App\Http\Controllers\TokenController::doValidate() must be an instance of Illuminate\Http\JsonResponse, array returned {"exception":"[object] (TypeError(code: 0): Return value of App\\Http\\Controllers\\TokenController::doValidate() must be an instance of Illuminate\\Http\\JsonResponse, array returned at /var/www/html/app/Http/Controllers/TokenController.php:58)
[stacktrace]
#0 [internal function]: App\\Http\\Controllers\\TokenController->doValidate()
#1 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): call_user_func_array()
#2 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\\Routing\\Controller->callAction()
#3 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Route.php(239): Illuminate\\Routing\\ControllerDispatcher->dispatch()
#4 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Route.php(196): Illuminate\\Routing\\Route->runController()
#5 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(685): Illuminate\\Routing\\Route->run()
#6 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}()
#7 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(41): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#8 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle()
#9 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(77): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#10 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle()
#11 /var/www/html/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#12 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle()
#13 /var/www/html/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(116): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#14 /var/www/html/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(62): Illuminate\\Session\\Middleware\\StartSession->handleStatefulRequest()
#15 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Session\\Middleware\\StartSession->handle()
#16 /var/www/html/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#17 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle()
#18 /var/www/html/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(67): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#19 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle()
#20 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#21 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(687): Illuminate\\Pipeline\\Pipeline->then()
#22 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(662): Illuminate\\Routing\\Router->runRouteWithinStack()
#23 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(628): Illuminate\\Routing\\Router->runRoute()
#24 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(617): Illuminate\\Routing\\Router->dispatchToRoute()
#25 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(165): Illuminate\\Routing\\Router->dispatch()
#26 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}()
#27 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#28 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#29 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#30 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#31 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#32 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle()
#33 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(63): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#34 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode->handle()
#35 /var/www/html/vendor/fruitcake/laravel-cors/src/HandleCors.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#36 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Fruitcake\\Cors\\HandleCors->handle()
#37 /var/www/html/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#38 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Fideloper\\Proxy\\TrustProxies->handle()
#39 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#40 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(140): Illuminate\\Pipeline\\Pipeline->then()
#41 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(109): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter()
#42 /var/www/html/public/index.php(99): Illuminate\\Foundation\\Http\\Kernel->handle()
#43 {main}
"}
172.17.0.1 - - [30/Aug/2020:23:32:04 +0000] "GET /token/validate HTTP/1.1" 500 1145 "http://127.0.0.1:8082/" "Mozilla/5.0 (X11; Linux x86_64; rv:80.0) Gecko/20100101 Firefox/80.0"
127.0.0.1 - - [30/Aug/2020:23:32:04 +0000] "GET /api/v1/about HTTP/1.1" 404 299 "-" "GuzzleHttp/6.5.5 curl/7.64.0 PHP/7.4.8"
172.17.0.1 - - [30/Aug/2020:23:32:04 +0000] "GET /token HTTP/1.1" 200 2160 "http://127.0.0.1:8082/" "Mozilla/5.0 (X11; Linux x86_64; rv:80.0) Gecko/20100101 Firefox/80.0"
127.0.0.1 - - [31/Aug/2020:00:01:36 +0000] "GET /api/v1/about HTTP/1.1" 404 299 "-" "GuzzleHttp/6.5.5 curl/7.64.0 PHP/7.4.8"
172.17.0.1 - - [31/Aug/2020:00:01:36 +0000] "GET /token HTTP/1.1" 200 2160 "http://127.0.0.1:8082/" "Mozilla/5.0 (X11; Linux x86_64; rv:80.0) Gecko/20100101 Firefox/80.0"
172.17.0.1 - - [31/Aug/2020:00:01:36 +0000] "GET /js/popper.min.js?version=2.0.5 HTTP/1.1" 200 7847 "http://127.0.0.1:8082/token" "Mozilla/5.0 (X11; Linux x86_64; rv:80.0) Gecko/20100101 Firefox/80.0"
172.17.0.1 - - [31/Aug/2020:00:01:36 +0000] "GET /js/bootstrap.min.js?version=2.0.5 HTTP/1.1" 200 15790 "http://127.0.0.1:8082/token" "Mozilla/5.0 (X11; Linux x86_64; rv:80.0) Gecko/20100101 Firefox/80.0"
172.17.0.1 - - [31/Aug/2020:00:01:36 +0000] "GET /js/jquery-3.4.1.min.js?version=2.0.5 HTTP/1.1" 200 31030 "http://127.0.0.1:8082/token" "Mozilla/5.0 (X11; Linux x86_64; rv:80.0) Gecko/20100101 Firefox/80.0"
```

**Bonus points**

- I have read the FAQ at https://bit.ly/FF3-FAQ
- I added a screenshot
- I added log files

**Comment by JC5** [comment]
127.0.0.1 won't work

https://firefly-iii.gitbook.io/firefly-iii-csv-importer/installing-and-running/configure

**Comment by azzamsa** [comment]
Thank you.
