### ISSUE TITLE
Not null violation error when first login

### ISSUE THREAD

**Issue by JacksonHub2** [firefly-iii/firefly-iii#3809]
**Bug description**
I am running Firefly III version 5.3.3, current latest branch in **docker**, and my problem is:

I have a **LDAP** server, and firefly has configured LDAP-related variables in docker env.
After first login, it comes out error: 
> SQLSTATE[23502]: Not null violation: 7 ERROR: null value in column "email" of relation "users" violates not-null constraint

![Screenshot_](https://user-images.githubusercontent.com/71587680/93708195-e7a7ef00-fb66-11ea-80d0-de88fa11099a.png)

Obviously, firefly could retrieve info from LDAP server, but failed to utilize it.

I'm pretty sure the _mail_ item is exist in the LDAP entry. And I've tried to clear the database table that firefly use, and re-run the docker app recreation, but the same error is there.

**Extra info**
In debug mode, firefly returns follow info during this login attempt:

[slapd trace]
```
conn=1083 fd=12 ACCEPT from IP=X.X.X.X
conn=1083 op=0 BIND dn="cn=admin,dc=XX,dc=com" method=128
conn=1083 op=0 BIND dn="cn=admin,dc=XX,dc=com" mech=SIMPLE ssf=0
conn=1083 op=0 RESULT tag=97 err=0 text=
conn=1083 op=1 SRCH base="dc=XX,dc=com" scope=2 deref=0 filter="(&(objectClass=inetOrgPerson)(objectClass=person)(uid=*)(uid=ABC))"
conn=1083 op=1 SRCH attr=* entryuuid
conn=1083 op=1 SEARCH RESULT tag=101 err=0 nentries=1 text=
conn=1083 op=2 BIND anonymous mech=implicit ssf=0
conn=1083 op=2 BIND dn="uid=ABC,ou=GROUP,dc=XX,dc=com" method=128
conn=1083 op=2 BIND dn="uid=ABC,ou=GROUP,dc=XX,dc=com" mech=SIMPLE ssf=0
conn=1083 op=2 RESULT tag=97 err=0 text=
conn=1083 op=3 BIND anonymous mech=implicit ssf=0
conn=1083 op=3 BIND dn="cn=admin,dc=XX,dc=com" method=128
conn=1083 op=3 BIND dn="cn=admin,dc=XX,dc=com" mech=SIMPLE ssf=0
conn=1083 op=3 RESULT tag=97 err=0 text=
conn=1083 op=4 UNBIND
conn=1083 fd=12 closed
conn=1084 fd=12 ACCEPT from IP=x.x.x.x
conn=1084 op=0 BIND dn="cn=admin,dc=XX,dc=com" method=128
conn=1084 op=0 BIND dn="cn=admin,dc=XX,dc=com" mech=SIMPLE ssf=0
conn=1084 op=0 RESULT tag=97 err=0 text=
conn=1084 op=1 SRCH base="dc=XX,dc=com" scope=2 deref=0 filter="(&(objectClass=*)(cn=*))"
conn=1084 op=1 SRCH attr=dn
conn=1084 op=1 SEARCH RESULT tag=101 err=0 nentries=3 text=
```
[firefly-iii trace]
```
[2020-09-20 11:45:58] local.INFO: Configured DB version (15) equals expected DB version (15)  
[2020-09-20 11:45:58] local.INFO: Installed Firefly III version (5.3.3) equals expected Firefly III version (5.3.3)  
[2020-09-20 11:45:58] local.INFO: User is trying to login.  
[2020-09-20 11:45:58] local.INFO: User 'ABC' has been successfully found for authentication.  
[2020-09-20 11:45:58] local.INFO: User 'ABC' is being imported.  
[2020-09-20 11:45:58] local.INFO: User 'ABC' is being synchronized.  
[2020-09-20 11:45:58] local.INFO: User 'ABC' has been successfully synchronized.  
[2020-09-20 11:45:58] local.INFO: User 'ABC' is authenticating with username: 'uid=ABC,ou=GROUP,dc=XX,dc=com'  
[2020-09-20 11:45:58] local.INFO: User 'ABC' has successfully passed LDAP authentication.  
[2020-09-20 11:45:58] local.ERROR: SQLSTATE[23502]: Not null violation: 7 ERROR:  null value in column "email" of relation "users" violates not-null constraint
DETAIL:  Failing row contains (14, 2020-09-20 11:45:58, 2020-09-20 11:45:58, null, HASH_VALUE, null, null, 0, null, ENTRYUUID, null). (SQL: insert into "users" ("objectguid", "email", "password", "updated_at", "created_at") values (ENTRYUUID, ?, HASH_VALUE, 2020-09-20 11:45:58, 2020-09-20 11:45:58) returning "id") {"exception":"[object] (Illuminate\\Database\\QueryException(code: 23502): SQLSTATE[23502]: Not null violation: 7 ERROR:  null value in column \"email\" of relation \"users\" violates not-null constraint
DETAIL:  Failing row contains (14, 2020-09-20 11:45:58, 2020-09-20 11:45:58, null, HASH_VALUE, null, null, 0, null, ENTRYUUID, null). (SQL: insert into \"users\" (\"objectguid\", \"email\", \"password\", \"updated_at\", \"created_at\") values (ENTRYUUID, ?, HASH_VALUE, 2020-09-20 11:45:58, 2020-09-20 11:45:58) returning \"id\") at /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Database/Connection.php:671)
[stacktrace]
```

**Comment by JC5** [comment]
Thanks for letting me know. I'll dive into the details and try to find out which value Firefly III tries to save to the database. I might need your help to verify it's there or not. Either way, a more userfriendly error will follow.

**Comment by JacksonHub2** [comment]
Okay I'll assist if you need any help here :(

BTW, there is actually another completely different warning when I using another firefly docker image: **_develop_**.

![Screenshot_2](https://user-images.githubusercontent.com/71587680/93712155-927bd580-fb86-11ea-902e-0df9ece04860.png)

Error code: 
> Using external identity provider. Cannot continue.

Note that other docker startup configuration has not been changed since last issue addressed.

When I switching back to _**latest**_ branch, login window prompt out, when get login, still failed, as [3809](https://github.com/firefly-iii/firefly-iii/issues/3809) previously talked about.

[trace details]
```
Stack trace
#0 [internal function]: FireflyIII\Http\Controllers\Auth\LoginController->__construct()
#1 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(849): ReflectionClass->newInstanceArgs()
#2 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(691): Illuminate\Container\Container->build()
#3 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(796): Illuminate\Container\Container->resolve()
#4 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(637): Illuminate\Foundation\Application->resolve()
#5 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(781): Illuminate\Container\Container->make()
#6 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Route.php(253): Illuminate\Foundation\Application->make()
#7 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Route.php(970): Illuminate\Routing\Route->getController()
#8 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Route.php(931): Illuminate\Routing\Route->controllerMiddleware()
#9 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(702): Illuminate\Routing\Route->gatherMiddleware()
#10 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(678): Illuminate\Routing\Router->gatherRouteMiddleware()
#11 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(662): Illuminate\Routing\Router->runRouteWithinStack()
#12 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(628): Illuminate\Routing\Router->runRoute()
#13 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(617): Illuminate\Routing\Router->dispatchToRoute()
#14 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(165): Illuminate\Routing\Router->dispatch()
#15 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}()
#16 /var/www/html/app/Http/Middleware/InstallationId.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#17 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): FireflyIII\Http\Middleware\InstallationId->handle()
#18 /var/www/html/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#19 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Fideloper\Proxy\TrustProxies->handle()
#20 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#21 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle()
#22 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#23 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle()
#24 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#25 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Foundation\Http\Middleware\ValidatePostSize->handle()
#26 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(63): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#27 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle()
#28 /var/www/html/app/Http/Middleware/SecureHeaders.php(51): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#29 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): FireflyIII\Http\Middleware\SecureHeaders->handle()
#30 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#31 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(140): Illuminate\Pipeline\Pipeline->then()
#32 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(109): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter()
#33 /var/www/html/public/index.php(76): Illuminate\Foundation\Http\Kernel->handle()
#34 {main}
```

**Comment by JC5** [comment]
Thanks. That bug should be fixed! If you download the `develop` tag again it should work.

What value did you set the `ADLDAP_SYNC_FIELD` variable?

**Comment by JacksonHub2** [comment]
Thanks for your mention, after add `ADLDAP_SYNC_FIELD=uid` to env, login succeed! (with `5.3.3`, not today's latest release)

However, when I use `5.4.0` or develop branch, under the same startup config, the error come up with:

![Screenshot_3](https://user-images.githubusercontent.com/71587680/93769448-5e1f1c80-fc4d-11ea-835e-432924c85a6a.png)

Error code:
> This error occured in file /var/www/html/app/Http/Controllers/Auth/LoginController.php on line 134 with code 0.

[Stack Trace]
```
#0 [internal function]: FireflyIII\Http\Controllers\Auth\LoginController->showLoginForm()
#1 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): call_user_func_array()
#2 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\Routing\Controller->callAction()
#3 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Route.php(239): Illuminate\Routing\ControllerDispatcher->dispatch()
#4 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Route.php(196): Illuminate\Routing\Route->runController()
#5 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(685): Illuminate\Routing\Route->run()
#6 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\Routing\Router->Illuminate\Routing\{closure}()
#7 /var/www/html/app/Http/Controllers/Controller.php(108): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#8 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): FireflyIII\Http\Controllers\Controller->FireflyIII\Http\Controllers\{closure}()
#9 /var/www/html/app/Http/Middleware/RedirectIfAuthenticated.php(51): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#10 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): FireflyIII\Http\Middleware\RedirectIfAuthenticated->handle()
#11 /var/www/html/app/Http/Middleware/Binder.php(79): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#12 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): FireflyIII\Http\Middleware\Binder->handle()
#13 /var/www/html/app/Http/Middleware/Installer.php(81): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#14 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): FireflyIII\Http\Middleware\Installer->handle()
#15 /var/www/html/vendor/laravel/passport/src/Http/Middleware/CreateFreshApiToken.php(50): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#16 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Laravel\Passport\Http\Middleware\CreateFreshApiToken->handle()
#17 /var/www/html/vendor/laravel/framework/src/Illuminate/Session/Middleware/AuthenticateSession.php(39): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#18 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Session\Middleware\AuthenticateSession->handle()
#19 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(77): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#20 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Foundation\Http\Middleware\VerifyCsrfToken->handle()
#21 /var/www/html/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#22 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\View\Middleware\ShareErrorsFromSession->handle()
#23 /var/www/html/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(116): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#24 /var/www/html/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(62): Illuminate\Session\Middleware\StartSession->handleStatefulRequest()
#25 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Session\Middleware\StartSession->handle()
#26 /var/www/html/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#27 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle()
#28 /var/www/html/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(67): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#29 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Cookie\Middleware\EncryptCookies->handle()
#30 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#31 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(687): Illuminate\Pipeline\Pipeline->then()
#32 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(662): Illuminate\Routing\Router->runRouteWithinStack()
#33 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(628): Illuminate\Routing\Router->runRoute()
#34 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(617): Illuminate\Routing\Router->dispatchToRoute()
#35 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(165): Illuminate\Routing\Router->dispatch()
#36 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}()
#37 /var/www/html/app/Http/Middleware/InstallationId.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#38 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): FireflyIII\Http\Middleware\InstallationId->handle()
#39 /var/www/html/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#40 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Fideloper\Proxy\TrustProxies->handle()
#41 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#42 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle()
#43 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#44 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle()
#45 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#46 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Foundation\Http\Middleware\ValidatePostSize->handle()
#47 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(63): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#48 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle()
#49 /var/www/html/app/Http/Middleware/SecureHeaders.php(51): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#50 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): FireflyIII\Http\Middleware\SecureHeaders->handle()
#51 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#52 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(140): Illuminate\Pipeline\Pipeline->then()
#53 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(109): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter()
#54 /var/www/html/public/index.php(76): Illuminate\Foundation\Http\Kernel->handle()
#55 {main}
```

So I'd prefer stay at 5.3.3 now :P

**Comment by JC5** [comment]
Yep, that's a bug. Depending on what comes up later this week, wait for 5.4.1 between now and Friday.

**Comment by JacksonHub2** [comment]
Okay I'll wait.

BTW, after successful login, when I tried to change password, it comes up with `This action is not available when Firefly III isn't responsible for user management or authentication handling. `

Could we add a feature to this? It's a direct way to self-manage the account.

**Comment by JC5** [comment]
Nope, that's kind of the point of offloading that stuff.

**Comment by JC5** [comment]
I'll make sure the button disappears.

**Comment by JC5** [comment]
Wait that button should be gone. Could you share the output of /debug please?

**Comment by JacksonHub2** [comment]
Sure:

Debug information generated at 2020-09-21 17:54:14 Asia/Shanghai for Firefly III version **5.3.3**.

| Scope | Version |
| --- | --- |
| Firefly III | 5.3.3 |
| Firefly III API | 1.3.0 |
| PHP | 7.4.8 |
| Host | Linux |

| System info | Value |
| --- | --- |
| Installation ID | a70cc307-b65d-4ed2-93eb-ebe76a4d5b26 |
| Using docker? | true |
| Telemetry | false |
| Layout |  |
| App environment | local |
| App debug mode | true |
| App cache driver | file |
| App logging | info, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Interface | apache2handler |
| Default language | en_US |
| Default locale | equal |
| BCscale | 12 |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | pgsql |
| Login provider | ldap  |
| Trusted proxies (.env) | ** |

| User info | Value |
| --- | --- |
| Session start | 2020-09-01 00:00:00 |
| Session end | 2020-09-30 23:59:59 |
| Session first | 2020-01-01 00:00:00 |
| User ID | 1 |
| User language | en_US |
| User locale | en_US |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| User agent | Mozilla/5.0 (X11; Linux x86_64; rv:79.0) Gecko/20100101 Firefox/79.0 |

**Comment by JC5** [comment]
Thanks. Weird. Final check. If you go to `/flush`, and then back to `/profile`, does that remove some options?

**Comment by JacksonHub2** [comment]
Nope, still there:

![Screenshot_4](https://user-images.githubusercontent.com/71587680/93776145-d8ec3580-fc55-11ea-9333-6159c5ce3c78.png)

**Comment by JC5** [comment]
Weird. So LDAP works perfectly fine, right? But the profile options keep insisting you're a local user. All I can do for now is add some debug messages to see what's happening. If you're up for it, switch to the `develop` tag, [turn on debug mode](https://docs.firefly-iii.org/faq/other#how-do-i-enable-debug-mode) and let me know what happens when you visit `/profile`.

Thanks in advance; it's tricky to debug this.

**Comment by JacksonHub2** [comment]
Okay please let me know when it's ready, I'll do the test.

**Comment by JC5** [comment]
It's here. Issue was auto-closed.

**Comment by JC5** [comment]
5.4.1 should fix this, I hope.

**Comment by JacksonHub2** [comment]
Confirmed on fix:
![Screenshot_5](https://user-images.githubusercontent.com/71587680/93895717-b70cb480-fd22-11ea-9ec6-1780e068df55.png)

BTW, in Administration -> All users page, user's password seems to be editable by users (actually it could not change, I've tried). Maybe it's better to remove?

**Comment by JC5** [comment]
Indeed. Thanks. The admin pages still kind of ignore the LDAP / external authentication settings. I'll put it on my list!

**Comment by JC5** [comment]
#3828
