### ISSUE TITLE
An error in the script or an incorrect release update?

### ISSUE THREAD

**Issue by nloshka** [firefly-iii/firefly-iii#3918]
Debug information generated at 2020-10-08 19:55:25 Europe/Amsterdam for Firefly III version **5.4.3**.

| Scope | Version |
| --- | --- |
| Firefly III | 5.4.3 |
| Firefly III API | 1.4.0 |
| PHP | 7.4.11 |
| Host | Linux |

| System info | Value |
| --- | --- |
| Installation ID | 28629bf3-d0fb-404b-a873-af978b1c355d |
| Using docker? | false |
| Telemetry | false |
| Layout |  |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | notice, daily |
| Display errors | Off |
| Error reporting | ALL errors |
| Interface | fpm-fcgi |
| Default language | en_US |
| Default locale | equal |
| BCscale | 12 |
| DB drivers | mysql, sqlite |
| Current driver | mysql |
| DB version | 15 (exp. 15) |
| Login provider | eloquent  |
| Trusted proxies (.env) |  |

| User info | Value |
| --- | --- |
| Session start | 2020-10-01 00:00:00 |
| Session end | 2020-10-31 23:59:59 |
| Session first | 2018-12-08 00:00:00 |
| User ID | 1 |
| User language | ru_RU |
| User locale | ru |
| Attempt at "ru.utf8" | false |
| Attempt at "ru.UTF-8" | false |
| User agent | Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.97 Safari/537.36 |

After update.
When creating a new transaction, it gives an error: Ошибка! Internal Firefly III Exception: Class 'Gdbots\QueryParser\QueryParser' not found

and it is impossible to transfer from one account to another account:
Could not find a valid destination account when looking for ID "11" or the name "savings account with Sberbank (Piggy bank) initial balance".

The following information is also displayed: Incorrect server configuration: Firefly III cannot provide the correct format for monetary amounts, because your server does not have the necessary packages. Follow the instructions explaining how to install them.

what needs to be done to eliminate these errors?
Thanks.

**Comment by nloshka** [comment]
the transaction is entered, but there is an error, but the transfer is not entered, it just gives an error

**Comment by JC5** [comment]
Let's see.

- Make sure you run `composer install` to fix the missing class.
- It seems you've selected the wrong account when making the transfer. The initial balance account will be hidden in a future release.
- Follow the instructions ;)

**Comment by nloshka** [comment]
Implemented recommendations
The transfer from one account to another is still not performed

**Comment by JC5** [comment]
A transaction between an asset account an an "initial balance" account will always fail I'm afraid.

**Comment by nloshka** [comment]
```
Truncated from this point <----|owableError(code: 0): Class 'Gdbots\\QueryParser\\QueryParser' not found at /var/www/buh.1admin.name/firefly-iii/app/Support/Search/OperatorQuerySearch.php:164)
[stacktrace]
#0 /var/www/buh.1admin.name/firefly-iii/app/TransactionRules/Engine/SearchRuleEngine.php(265): FireflyIII\\Support\\Search\\OperatorQuerySearch->parseQuery()
#1 /var/www/buh.1admin.name/firefly-iii/app/TransactionRules/Engine/SearchRuleEngine.php(207): FireflyIII\\TransactionRules\\Engine\\SearchRuleEngine->findStrictRule()
#2 /var/www/buh.1admin.name/firefly-iii/app/TransactionRules/Engine/SearchRuleEngine.php(131): FireflyIII\\TransactionRules\\Engine\\SearchRuleEngine->fireStrictRule()
#3 /var/www/buh.1admin.name/firefly-iii/app/TransactionRules/Engine/SearchRuleEngine.php(97): FireflyIII\\TransactionRules\\Engine\\SearchRuleEngine->fireRule()
#4 /var/www/buh.1admin.name/firefly-iii/app/Handlers/Events/StoredGroupEventHandler.php(70): FireflyIII\\TransactionRules\\Engine\\SearchRuleEngine->fire()
#5 [internal function]: FireflyIII\\Handlers\\Events\\StoredGroupEventHandler->processRules()
#6 /var/www/buh.1admin.name/firefly-iii/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(388): call_user_func_array()
#7 /var/www/buh.1admin.name/firefly-iii/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(218): Illuminate\\Events\\Dispatcher->Illuminate\\Events\\{closure}()
#8 /var/www/buh.1admin.name/firefly-iii/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php(477): Illuminate\\Events\\Dispatcher->dispatch()
#9 /var/www/buh.1admin.name/firefly-iii/app/Api/V1/Controllers/TransactionController.php(331): event()
#10 [internal function]: FireflyIII\\Api\\V1\\Controllers\\TransactionController->store()
#11 /var/www/buh.1admin.name/firefly-iii/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): call_user_func_array()
#12 /var/www/buh.1admin.name/firefly-iii/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\\Routing\\Controller->callAction()
#13 /var/www/buh.1admin.name/firefly-iii/vendor/laravel/framework/src/Illuminate/Routing/Route.php(219): Illuminate\\Routing\\ControllerDispatcher->dispatch()
#14 /var/www/buh.1admin.name/firefly-iii/vendor/laravel/framework/src/Illuminate/Routing/Route.php(176): Illuminate\\Routing\\Route->runController()
#15 /var/www/buh.1admin.name/firefly-iii/vendor/laravel/framework/src/Illuminate/Routing/Router.php(681): Illuminate\\Routing\\Route->run()
#16 /var/www/buh.1admin.name/firefly-iii/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(130): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}()
#17 /var/www/buh.1admin.name/firefly-iii/app/Api/V1/Controllers/TransactionController.php(85): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#18 /var/www/buh.1admin.name/firefly-iii/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(153): FireflyIII\\Api\\V1\\Controllers\\TransactionController->FireflyIII\\Api\\V1\\Controllers\\{closure}()
#19 /var/www/buh.1admin.name/firefly-iii/app/Api/V1/Controllers/Controller.php(63): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#20 /var/www/buh.1admin.name/firefly-iii/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(153): FireflyIII\\Api\\V1\\Controllers\\Controller->FireflyIII\\Api\\V1\\Controllers\\{closure}()
#21 /var/www/buh.1admin.name/firefly-iii/app/Http/Middleware/Binder.php(79): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#22 /var/www/buh.1admin.name/firefly-iii/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): FireflyIII\\Http\\Middleware\\Binder->handle()
#23 /var/www/buh.1admin.name/firefly-iii/app/Http/Middleware/Authenticate.php(74): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#24 /var/www/buh.1admin.name/firefly-iii/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): FireflyIII\\Http\\Middleware\\Authenticate->handle()
#25 /var/www/buh.1admin.name/firefly-iii/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(105): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#26 /var/www/buh.1admin.name/firefly-iii/vendor/laravel/framework/src/Illuminate/Routing/Router.php(683): Illuminate\\Pipeline\\Pipeline->then()
#27 /var/www/buh.1admin.name/firefly-iii/vendor/laravel/framework/src/Illuminate/Routing/Router.php(658): Illuminate\\Routing\\Router->runRouteWithinStack()
#28 /var/www/buh.1admin.name/firefly-iii/vendor/laravel/framework/src/Illuminate/Routing/Router.php(624): Illuminate\\Routing\\Router->runRoute()
#29 /var/www/buh.1admin.name/firefly-iii/vendor/laravel/framework/src/Illuminate/Routing/Router.php(613): Illuminate\\Routing\\Router->dispatchToRoute()
#30 /var/www/buh.1admin.name/firefly-iii/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(170): Illuminate\\Routing\\Router->dispatch()
#31 /var/www/buh.1admin.name/firefly-iii/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(130): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}()
#32 /var/www/buh.1admin.name/firefly-iii/app/Http/Middleware/InstallationId.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#33 /var/www/buh.1admin.name/firefly-iii/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): FireflyIII\\Http\\Middleware\\InstallationId->handle()
#34 /var/www/buh.1admin.name/firefly-iii/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#35 /var/www/buh.1admin.name/firefly-iii/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Fideloper\\Proxy\\TrustProxies->handle()
#36 /var/www/buh.1admin.name/firefly-iii/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#37 /var/www/buh.1admin.name/firefly-iii/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#38 /var/www/buh.1admin.name/firefly-iii/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#39 /var/www/buh.1admin.name/firefly-iii/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#40 /var/www/buh.1admin.name/firefly-iii/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#41 /var/www/buh.1admin.name/firefly-iii/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle()
#42 /var/www/buh.1admin.name/firefly-iii/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(63): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#43 /var/www/buh.1admin.name/firefly-iii/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode->handle()
#44 /var/www/buh.1admin.name/firefly-iii/app/Http/Middleware/SecureHeaders.php(51): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#45 /var/www/buh.1admin.name/firefly-iii/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): FireflyIII\\Http\\Middleware\\SecureHeaders->handle()
#46 /var/www/buh.1admin.name/firefly-iii/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(105): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#47 /var/www/buh.1admin.name/firefly-iii/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(145): Illuminate\\Pipeline\\Pipeline->then()
#48 /var/www/buh.1admin.name/firefly-iii/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(110): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter()
#49 /var/www/buh.1admin.name/firefly-iii/public/index.php(76): Illuminate\\Foundation\\Http\\Kernel->handle()
#50 {main}
"} 

```

**Comment by nloshka** [comment]
I don't quite understand, it worked before
What now the accounts need to be made of the same type and transferred between the same type of accounts?

**Comment by nloshka** [comment]
do i need to re-create accounts?

**Comment by JC5** [comment]
No, and no.

The error with GdParser only happens when you haven't run `composer install` yet.
