### ISSUE TITLE
Participation in Hacktoberfest

### ISSUE THREAD

**Issue by Dainius14** [firefly-iii/firefly-iii#3920]
There is this celebration of OSS happening - [Hacktoberfest](https://hacktoberfest.digitalocean.com/), which encourages developers to contribute to projects like these! Maybe you'd like to participate with your repo? Some people might chime in to help with some tasks you're not in the mood to do :)

**Comment by JC5** [comment]
Hey, that's a nice idea. I'll check it out! There's enough to do in the [sonarcloud.io](https://sonarcloud.io/dashboard?id=firefly-iii_firefly-iii) repo.

**Comment by Dainius14** [comment]
I see you're working on v2 ui. As I'm not much of php guy, I could actually offer some help on that. Atm I see that simply enabling the v2 UI in .env file doesn't work though.

**Comment by JC5** [comment]
Setting `FIREFLY_III_LAYOUT=v2` should result in something like this:

![Uploading Screenshot 2020-10-11 at 17.01.19.png…]()


Although most other pages don't work yet ;)

**Comment by Dainius14** [comment]
For me it results in `500 internal server error` :D  restarted php, nginx and that didn't help. Will try it out in docker.

**Comment by JC5** [comment]
Let me know what the error is exactly, I can pick it up ^^

**Comment by Dainius14** [comment]
```
[2020-10-11 18:12:00] local.ERROR: Argument 1 passed to FireflyIII\Support\Twig\Breadcrumbs::FireflyIII\Support\Twig\{closure}() must be of the type array, null given, called in /var/www/firefly/storage/framework/views/twig/9a/9ae98ff8076e57f7af2faf921b2998957f18f67a00229d728b1c52c2991745fe.php on line 137 {"userId":1,"exception":"[object] (TypeError(code: 0): Argument 1 passed to FireflyIII\\Support\\Twig\\Breadcrumbs::FireflyIII\\Support\\Twig\\{closure}() must be of the type array, null given, called in /var/www/firefly/storage/framework/views/twig/9a/9ae98ff8076e57f7af2faf921b2998957f18f67a00229d728b1c52c2991745fe.php on line 137 at /var/www/firefly/app/Support/Twig/Breadcrumbs.php:52)
[stacktrace]
#0 /var/www/firefly/storage/framework/views/twig/9a/9ae98ff8076e57f7af2faf921b2998957f18f67a00229d728b1c52c2991745fe.php(137): FireflyIII\\Support\\Twig\\Breadcrumbs::FireflyIII\\Support\\Twig\\{closure}()
#1 /var/www/firefly/vendor/twig/twig/src/Template.php(405): __TwigTemplate_ffdc8839bdacfc4231aa238602e0e850c033f82b4877c6b5148d29788e24ed74->doDisplay()
#2 /var/www/firefly/vendor/twig/twig/src/Template.php(378): Twig\\Template->displayWithErrorHandling()
#3 /var/www/firefly/vendor/rcrowe/twigbridge/src/Twig/Template.php(41): Twig\\Template->display()
#4 /var/www/firefly/storage/framework/views/twig/f0/f018ecef10cc7ebb3fa6daecff5243eff3a7fb173b1223a33caae4b152b96aa2.php(44): TwigBridge\\Twig\\Template->display()
#5 /var/www/firefly/vendor/twig/twig/src/Template.php(405): __TwigTemplate_767f6ee8a017485384ef4ad637908a452c44ac031ea32a757f4d127e65b684b4->doDisplay()
#6 /var/www/firefly/vendor/twig/twig/src/Template.php(378): Twig\\Template->displayWithErrorHandling()
#7 /var/www/firefly/vendor/rcrowe/twigbridge/src/Twig/Template.php(41): Twig\\Template->display()
#8 /var/www/firefly/vendor/twig/twig/src/Template.php(390): TwigBridge\\Twig\\Template->display()
#9 /var/www/firefly/vendor/rcrowe/twigbridge/src/Engine/Twig.php(92): Twig\\Template->render()
#10 /var/www/firefly/vendor/laravel/framework/src/Illuminate/View/View.php(139): TwigBridge\\Engine\\Twig->get()
#11 /var/www/firefly/vendor/laravel/framework/src/Illuminate/View/View.php(122): Illuminate\\View\\View->getContents()
#12 /var/www/firefly/vendor/laravel/framework/src/Illuminate/View/View.php(91): Illuminate\\View\\View->renderContents()
```
followed by a lot of errors about some cache issues

```
[2020-10-11 17:18:56] local.ERROR: Please provide a valid cache path. {"userId":1,"exception":"[object] (InvalidArgumentException(code: 0): Please provide a valid cache path. at /var/www/firefly/vendor/laravel/framework/src/Illuminate/View/Compilers/Compiler.php:36)
```

**Comment by JC5** [comment]
Thx. Not sure what the cache error is about but the other one should be fixed in the develop branch already.
