### ISSUE TITLE
/api/v1/data/destroy endpoint can't handle object ""

### ISSUE THREAD

**Issue by IceflowRE** [firefly-iii/firefly-iii#3942]
**Bug description**
I am running Firefly III version 5.4.3, and my problem is:

I tried to use the endpoint `/api/v1/data/destroy?objects=budgets`.
I used the Python Client from here https://github.com/ms32035/firefly-iii-client.
But added another class to get access to the data endpoint.

**Note**: this error does not appear when sending correct input. Iam just leaving that here as it seems that wrong input leads to an exception and not an error response.

```python
import six

from firefly_iii_client.api_client import ApiClient
from firefly_iii_client.exceptions import (
    ApiTypeError,
    ApiValueError
)


class DataApi(object):
    def __init__(self, api_client=None):
        if api_client is None:
            api_client = ApiClient()
        self.api_client = api_client

    def delete_data(self, objects, **kwargs):  # noqa: E501
        allowed_values = ["budgets", "bills", "piggy_banks", "rules", "recurring", "categories", "tags", "object_groups", "accounts", "asset_accounts",
                          "expense_accounts", "revenue_accounts", "liabilities", "transactions", "withdrawals", "deposits", "transfers"]  # noqa: E501
        if objects not in allowed_values:
            raise ValueError(f"Invalid value for `type` ({objects}), must be one of {allowed_values}")

        kwargs['_return_http_data_only'] = True
        local_var_params = locals()

        all_params = ['objects', 'async_req', '_return_http_data_only', '_preload_content', '_request_timeout']  # noqa: E501

        for key, val in six.iteritems(local_var_params['kwargs']):
            if key not in all_params:
                raise ApiTypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method delete_data" % key
                )
            local_var_params[key] = val
        del local_var_params['kwargs']
        # verify the required parameter 'objects' is set
        if 'objects' not in local_var_params or local_var_params['objects'] is None:
            raise ApiValueError("Missing the required parameter `objects` when calling `delete_data`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'objects' in local_var_params:
            path_params['objects'] = local_var_params['objects']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # Authentication setting
        auth_settings = ['firefly_iii_auth']  # noqa: E501

        return self.api_client.call_api(
            '/api/v1/data/destroy', 'DELETE',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type=None,  # noqa: E501
            auth_settings=auth_settings,
            async_req=local_var_params.get('async_req'),
            _return_http_data_only=local_var_params.get('_return_http_data_only'),  # noqa: E501
            _preload_content=local_var_params.get('_preload_content', True),
            _request_timeout=local_var_params.get('_request_timeout'),
            collection_formats=collection_formats)

```

```
fireflyiii_1 | [2020-10-15 17:11:44] local.ERROR: Exception is: {"class":"FireflyIII\\Exceptions\\FireflyException","errorMessage":"This endpoint can't handle object \"\"","time":"Thu, 15 Oct 2020 17:11:44 +0200","file":"\/var\/www\/html\/app\/Api\/V1\/Controllers\/Data\/DestroyController.php","line":63,"code":0,"version":"5.4.3","url":"http:\/\/localhost\/api\/v1\/data\/destroy","userAgent":"OpenAPI-Generator\/1.2.0\/python","json":true}
fireflyiii_1 | [2020-10-15 17:11:44] local.ERROR: This endpoint can't handle object "" {"userId":1,"exception":"[object] (FireflyIII\\Exceptions\\FireflyException(code: 0): This endpoint can't handle object \"\" at /var/www/html/app/Api/V1/Controllers/Data/DestroyController.php:63)
fireflyiii_1 | [stacktrace]
fireflyiii_1 | #0 [internal function]: FireflyIII\\Api\\V1\\Controllers\\Data\\DestroyController->destroy()
fireflyiii_1 | #1 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): call_user_func_array()
fireflyiii_1 | #2 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\\Routing\\Controller->callAction()
fireflyiii_1 | #3 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Route.php(239): Illuminate\\Routing\\ControllerDispatcher->dispatch()
fireflyiii_1 | #4 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Route.php(196): Illuminate\\Routing\\Route->runController()
fireflyiii_1 | #5 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(685): Illuminate\\Routing\\Route->run()
fireflyiii_1 | #6 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}()
fireflyiii_1 | #7 /var/www/html/app/Api/V1/Controllers/Controller.php(63): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
fireflyiii_1 | #8 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): FireflyIII\\Api\\V1\\Controllers\\Controller->FireflyIII\\Api\\V1\\Controllers\\{closure}()
fireflyiii_1 | #9 /var/www/html/app/Http/Middleware/Binder.php(79): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
fireflyiii_1 | #10 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): FireflyIII\\Http\\Middleware\\Binder->handle()
fireflyiii_1 | #11 /var/www/html/app/Http/Middleware/Authenticate.php(74): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
fireflyiii_1 | #12 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): FireflyIII\\Http\\Middleware\\Authenticate->handle()
fireflyiii_1 | #13 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
fireflyiii_1 | #14 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(687): Illuminate\\Pipeline\\Pipeline->then()
fireflyiii_1 | #15 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(662): Illuminate\\Routing\\Router->runRouteWithinStack()
fireflyiii_1 | #16 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(628): Illuminate\\Routing\\Router->runRoute()
fireflyiii_1 | #17 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(617): Illuminate\\Routing\\Router->dispatchToRoute()
fireflyiii_1 | #18 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(165): Illuminate\\Routing\\Router->dispatch()
fireflyiii_1 | #19 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}()
fireflyiii_1 | #20 /var/www/html/app/Http/Middleware/InstallationId.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
fireflyiii_1 | #21 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): FireflyIII\\Http\\Middleware\\InstallationId->handle()
fireflyiii_1 | #22 /var/www/html/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
fireflyiii_1 | #23 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Fideloper\\Proxy\\TrustProxies->handle()
fireflyiii_1 | #24 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
fireflyiii_1 | #25 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
fireflyiii_1 | #26 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
fireflyiii_1 | #27 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
fireflyiii_1 | #28 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
fireflyiii_1 | #29 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle()
fireflyiii_1 | #30 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(63): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
fireflyiii_1 | #31 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode->handle()
fireflyiii_1 | #32 /var/www/html/app/Http/Middleware/SecureHeaders.php(51): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
fireflyiii_1 | #33 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): FireflyIII\\Http\\Middleware\\SecureHeaders->handle()
fireflyiii_1 | #34 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
fireflyiii_1 | #35 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(140): Illuminate\\Pipeline\\Pipeline->then()
fireflyiii_1 | #36 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(109): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter()
fireflyiii_1 | #37 /var/www/html/public/index.php(76): Illuminate\\Foundation\\Http\\Kernel->handle()
fireflyiii_1 | #38 {main}
fireflyiii_1 | "}
fireflyiii_1 | 172.18.0.1 - - [15/Oct/2020:17:11:44 +0200] "DELETE /api/v1/data/destroy HTTP/1.1" 500 4621 "-" "OpenAPI-Generator/1.2.0/python"
```

**Comment by JC5** [comment]
Thanks for letting me know! It's a validation error that shouldn't give you an exception, like you said.
