### ISSUE TITLE
Not possible to edit some transactions

### ISSUE THREAD

**Issue by daften** [firefly-iii/firefly-iii#3991]
**Bug description**
I am running Firefly III version 5.4.4, and my problem is:

I can no longer edit transactions. The edit screen only shows the bottom fieldset:
<img width="703" alt="Screen Shot 2020-10-26 at 01 51 53" src="https://user-images.githubusercontent.com/1221024/97123824-d9cd2700-172d-11eb-9e71-9f73f2bcedfa.png">

**Steps to reproduce**

Honestly, no idea. It doesn't happen on all my transactions and adding new transactions seems to work fine.

I do see this in the logs:
```
today at 1:51 AM [2020-10-26 01:51:38] local.ERROR: Call to a member function toAtomString() on null {"userId":1,"exception":"[object] (Error(code: 0): Call to a member function toAtomString() on null at /var/www/html/app/Transformers/TransactionGroupTransformer.php:572)
today at 1:51 AM [stacktrace]
today at 1:51 AM #0 /var/www/html/app/Transformers/TransactionGroupTransformer.php(523): FireflyIII\\Transformers\\TransactionGroupTransformer->dateFromArray()
today at 1:51 AM #1 /var/www/html/app/Transformers/TransactionGroupTransformer.php(433): FireflyIII\\Transformers\\TransactionGroupTransformer->transformTransaction()
today at 1:51 AM #2 /var/www/html/app/Transformers/TransactionGroupTransformer.php(85): FireflyIII\\Transformers\\TransactionGroupTransformer->transformTransactions()
today at 1:51 AM #3 /var/www/html/vendor/league/fractal/src/Scope.php(419): FireflyIII\\Transformers\\TransactionGroupTransformer->transform()
today at 1:51 AM #4 /var/www/html/vendor/league/fractal/src/Scope.php(358): League\\Fractal\\Scope->fireTransformer()
today at 1:51 AM #5 /var/www/html/vendor/league/fractal/src/Scope.php(235): League\\Fractal\\Scope->executeResourceTransformers()
today at 1:51 AM #6 /var/www/html/app/Api/V1/Controllers/TransactionController.php(283): League\\Fractal\\Scope->toArray()
today at 1:51 AM #7 [internal function]: FireflyIII\\Api\\V1\\Controllers\\TransactionController->show()
today at 1:51 AM #8 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): call_user_func_array()
today at 1:51 AM #9 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\\Routing\\Controller->callAction()
today at 1:51 AM #10 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Route.php(239): Illuminate\\Routing\\ControllerDispatcher->dispatch()
today at 1:51 AM #11 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Route.php(196): Illuminate\\Routing\\Route->runController()
today at 1:51 AM #12 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(685): Illuminate\\Routing\\Route->run()
today at 1:51 AM #13 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}()
today at 1:51 AM #14 /var/www/html/app/Api/V1/Controllers/TransactionController.php(86): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
today at 1:51 AM #15 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): FireflyIII\\Api\\V1\\Controllers\\TransactionController->FireflyIII\\Api\\V1\\Controllers\\{closure}()
today at 1:51 AM #16 /var/www/html/app/Api/V1/Controllers/Controller.php(64): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
today at 1:51 AM #17 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): FireflyIII\\Api\\V1\\Controllers\\Controller->FireflyIII\\Api\\V1\\Controllers\\{closure}()
today at 1:51 AM #18 /var/www/html/app/Http/Middleware/Binder.php(79): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
today at 1:51 AM #19 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): FireflyIII\\Http\\Middleware\\Binder->handle()
today at 1:51 AM #20 /var/www/html/app/Http/Middleware/Authenticate.php(74): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
today at 1:51 AM #21 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): FireflyIII\\Http\\Middleware\\Authenticate->handle()
today at 1:51 AM #22 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
today at 1:51 AM #23 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(687): Illuminate\\Pipeline\\Pipeline->then()
today at 1:51 AM #24 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(662): Illuminate\\Routing\\Router->runRouteWithinStack()
today at 1:51 AM #25 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(628): Illuminate\\Routing\\Router->runRoute()
today at 1:51 AM #26 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(617): Illuminate\\Routing\\Router->dispatchToRoute()
today at 1:51 AM #27 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(165): Illuminate\\Routing\\Router->dispatch()
today at 1:51 AM #28 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}()
today at 1:51 AM #29 /var/www/html/app/Http/Middleware/InstallationId.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
today at 1:51 AM #30 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): FireflyIII\\Http\\Middleware\\InstallationId->handle()
today at 1:51 AM #31 /var/www/html/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
today at 1:51 AM #32 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Fideloper\\Proxy\\TrustProxies->handle()
today at 1:51 AM #33 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
today at 1:51 AM #34 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
today at 1:51 AM #35 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
today at 1:51 AM #36 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
today at 1:51 AM #37 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
today at 1:51 AM #38 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle()
today at 1:51 AM #39 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(63): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
today at 1:51 AM #40 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode->handle()
today at 1:51 AM #41 /var/www/html/app/Http/Middleware/SecureHeaders.php(51): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
today at 1:51 AM #42 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): FireflyIII\\Http\\Middleware\\SecureHeaders->handle()
today at 1:51 AM #43 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
today at 1:51 AM #44 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(140): Illuminate\\Pipeline\\Pipeline->then()
today at 1:51 AM #45 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(109): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter()
today at 1:51 AM #46 /var/www/html/public/index.php(76): Illuminate\\Foundation\\Http\\Kernel->handle()
today at 1:51 AM #47 {main}
today at 1:51 AM "}
```

**Extra info**
I use the docker image. I have watchtower running so docker images are updated automatically to the latest version.

**Bonus points**

- I searched and nobody reported this bug before
- I have added a stack trace from my log files 
- I have added a screenshot.
- I was able to replicate it on the demo site https://demo.firefly-iii.org/

**Comment by daften** [comment]
It seems to affect my current credit cards, but changing the asset account type does not help.

**Comment by daften** [comment]
Digging into the code, it seems to be the dateFromString function where 'interest_date' is hardcoded instead of using $key.
Change is here: https://github.com/firefly-iii/firefly-iii/commit/198c79c0485544c18bd35b4e8ed4e00de83110e9

**Comment by JC5** [comment]
Thanks, that's a sloppy bug. Will be fixed in the next release.

**Comment by edwinludik** [comment]
What is the ETA till the next release (usually) ? love the program tx!

**Comment by JC5** [comment]
If you want it now, please switch to the develop branch or image.

**Comment by edwinludik** [comment]
I just checked the tags, and I see it varies: https://github.com/firefly-iii/firefly-iii/tags 
Thank you for the suggestion, for now I can wait :-)

**Comment by MadWalnut** [comment]
Is this the same bug I am running into with the CSV importer here? I can't import a CSV file at all without running into these errors:

![Screenshot_1](https://user-images.githubusercontent.com/33835479/97505311-0032d280-1979-11eb-9a34-2dd2d3391305.png)

The transactions seem to import fine though, I can see them in Firefly-III despite all those errors. Can I just ignore the messages?
