### ISSUE TITLE
Unable to reach Firefly across docker hostname resolution

### ISSUE THREAD

**Issue by jhelbig** [firefly-iii/firefly-iii#4069]
**Bug description**
I am unable to use both the public domain name for Firefly AND the docker-compose provided hostname to connect the csv-importer.  This is important because application communication between two containers should be done across a private connection within the docker managed network and never route outside into the public domain.  This also cuts down on the amount of bandwidth and latency across public interfaces since all of the traffic takes place within the docker managed network.

![image](https://user-images.githubusercontent.com/11377461/99227962-93f60280-27b1-11eb-834e-7dde63847cf3.png)

The lines in black represent existing calls that are fine, and work without any issues.  The lines in green represent ones that would work with my proposal below.  The lines in red represent the existing problem that needs attention.

I noticed there's two different URI env vars:

- FIREFLY_III_URI
- VANITY_URI

I propose that `VANITY_URI` is used for any public network based communication(like redirects/hardlinking) and that `FIREFLY_III_URI` can be used for any other communication(like inter-container communications).

Without this change I wouldn't be able to run the csv-import service without some new domain and port routing that would break current conventions.  I also believe that it improves security since most if not all of the communication that will take place over the API will be container-to-container and will completely remove any need to communicate over the public domain.

| Scope | Version |
| --- | --- |
| Firefly III | 5.4.6 |
| Firefly III API | 1.4.0 |
| PHP | 7.4.11 |
| Host | Linux |
| Docker | 19.03.13 |
| Docker-Compose | 1.25.4 |

**Steps to reproduce**
Here is a simplified version of my docker-compose file that should have everything in it to replicate.  You may need to add a local DNS or local host records for `firefly.home.net` and `fireimp.home.net`

#### docker-compose.yml
```
version: "3.6"
services:
  proxy:
    image: nginx:stable
    restart: on-failure
    ports:
      - "80:80"
    networks:
      - pubnet
  
# firefly.home.net
  firefly:
    image: "jc5x/firefly-iii:latest"
    networks:
      - pubnet
      - pvtnet
    environment:
      - DB_HOST=firefly_db
      - DB_DATABASE=${FIREFLY_DB_NAME}
      - DB_USERNAME=${FIREFLY_DB_USER}
      - DB_PASSWORD=${FIREFLY_DB_PASSWORD}
      - DB_PORT=3306
      - DB_CONNECTION=mysql
      - APP_KEY=${FIREFLY_APP_KEY}
      - APP_ENV=local
      - APP_URL=http://firefly.home.net
      - TRUSTED_PROXIES=**

#fireimp.home.net
  firefly_imp:
    image: "fireflyiii/csv-importer:latest"
    networks:
      - pubnet
      - pvtnet
    environment:
      - FIREFLY_III_CLIENT_ID=${FIREFLY_IMPORT_CID}
      - FIREFLY_III_URI=http://firefly:8080
      - VANITY_URI=http://firefly.home.net
  
  firefly_db:
    image: "mariadb:latest"
    networks:
      - pvtnet
    environment:
      - MYSQL_DATABASE=${FIREFLY_DB_NAME}
      - MYSQL_USER=${FIREFLY_DB_USER}
      - MYSQL_PASSWORD=${FIREFLY_DB_PASSWORD}
      - MYSQL_RANDOM_ROOT_PASSWORD=yes

networks:
  pubnet:
    ipam:
      driver: default
      config:
        - 
          subnet: 200.205.10.0/24
  pvtnet:
    internal: true
    ipam:
      driver: default
      config:
        - 
          subnet: 200.205.11.0/24
```

#### firefly.conf (nginx virtual host)
```
server {
    listen       80;
    server_name  firefly.home.net;
    add_header Referrer-Policy "no-referrer";

    #access_log  /var/log/nginx/log/host.access.log  main;

    location / {
        proxy_pass http://firefly:8080;
        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_buffering off;
    }
}
```

#### fireimp.conf (nginx virtual host)
```
server {
    listen       80;
    server_name  fireimp.home.net;
    add_header Referrer-Policy "no-referrer";

    #access_log  /var/log/nginx/log/host.access.log  main;

    location / {
        proxy_pass http://firefly_imp:8080;
        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_buffering off;
    }
}
```

**Extra info**
Here is the output from the csv-importer container when it fails
```
[2020-11-16 02:59:32] production.DEBUG: Now at App\Http\Controllers\TokenController::callback  
[2020-11-16 02:59:32] production.DEBUG: State is valid!  
[2020-11-16 02:59:32] production.DEBUG: Params for access token {"form_params":{"grant_type":"authorization_code","client_id":{{REDACT}},"redirect_uri":"http://fireimp.home.net/callback","code_verifier":"{{REDACT}}","code":"{{REDACT}}"}} 
[2020-11-16 02:59:32] production.DEBUG: Will contact "http://firefly.home.net/oauth/token" for a token.  
[2020-11-16 02:59:32] production.ERROR: cURL error 7: Failed to connect to firefly.home.net port 80: Connection refused (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for http://firefly.home.net/oauth/token {"exception":"[object] (GuzzleHttp\\Exception\\ConnectException(code: 0): cURL error 7: Failed to connect to firefly.home.net port 80: Connection refused (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for http://firefly.home.net/oauth/token at /var/www/html/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php:210)
[stacktrace]
#0 /var/www/html/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(158): GuzzleHttp\\Handler\\CurlFactory::createRejection()
#1 /var/www/html/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(110): GuzzleHttp\\Handler\\CurlFactory::finishError()
#2 /var/www/html/vendor/guzzlehttp/guzzle/src/Handler/CurlHandler.php(47): GuzzleHttp\\Handler\\CurlFactory::finish()
#3 /var/www/html/vendor/guzzlehttp/guzzle/src/Handler/Proxy.php(28): GuzzleHttp\\Handler\\CurlHandler->__invoke()
#4 /var/www/html/vendor/guzzlehttp/guzzle/src/Handler/Proxy.php(48): GuzzleHttp\\Handler\\Proxy::GuzzleHttp\\Handler\\{closure}()
#5 /var/www/html/vendor/guzzlehttp/guzzle/src/PrepareBodyMiddleware.php(64): GuzzleHttp\\Handler\\Proxy::GuzzleHttp\\Handler\\{closure}()
#6 /var/www/html/vendor/guzzlehttp/guzzle/src/Middleware.php(31): GuzzleHttp\\PrepareBodyMiddleware->__invoke()
#7 /var/www/html/vendor/guzzlehttp/guzzle/src/RedirectMiddleware.php(71): GuzzleHttp\\Middleware::GuzzleHttp\\{closure}()
#8 /var/www/html/vendor/guzzlehttp/guzzle/src/Middleware.php(63): GuzzleHttp\\RedirectMiddleware->__invoke()
#9 /var/www/html/vendor/guzzlehttp/guzzle/src/HandlerStack.php(75): GuzzleHttp\\Middleware::GuzzleHttp\\{closure}()
#10 /var/www/html/vendor/guzzlehttp/guzzle/src/Client.php(331): GuzzleHttp\\HandlerStack->__invoke()
#11 /var/www/html/vendor/guzzlehttp/guzzle/src/Client.php(168): GuzzleHttp\\Client->transfer()
#12 /var/www/html/vendor/guzzlehttp/guzzle/src/Client.php(187): GuzzleHttp\\Client->requestAsync()
#13 /var/www/html/vendor/guzzlehttp/guzzle/src/ClientTrait.php(95): GuzzleHttp\\Client->request()
#14 /var/www/html/app/Http/Controllers/TokenController.php(200): GuzzleHttp\\Client->post()
#15 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): App\\Http\\Controllers\\TokenController->callback()
#16 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\\Routing\\Controller->callAction()
#17 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Route.php(255): Illuminate\\Routing\\ControllerDispatcher->dispatch()
#18 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Route.php(197): Illuminate\\Routing\\Route->runController()
#19 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(691): Illuminate\\Routing\\Route->run()
#20 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}()
#21 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(41): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#22 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle()
#23 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(77): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#24 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle()
#25 /var/www/html/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#26 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle()
#27 /var/www/html/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(121): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#28 /var/www/html/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(63): Illuminate\\Session\\Middleware\\StartSession->handleStatefulRequest()
#29 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Session\\Middleware\\StartSession->handle()
#30 /var/www/html/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#31 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle()
#32 /var/www/html/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(67): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#33 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle()
#34 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#35 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(693): Illuminate\\Pipeline\\Pipeline->then()
#36 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(668): Illuminate\\Routing\\Router->runRouteWithinStack()
#37 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(634): Illuminate\\Routing\\Router->runRoute()
#38 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(623): Illuminate\\Routing\\Router->dispatchToRoute()
#39 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(166): Illuminate\\Routing\\Router->dispatch()
#40 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}()
#41 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#42 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#43 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#44 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#45 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#46 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle()
#47 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(87): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#48 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance->handle()
#49 /var/www/html/vendor/fruitcake/laravel-cors/src/HandleCors.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#50 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Fruitcake\\Cors\\HandleCors->handle()
#51 /var/www/html/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#52 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Fideloper\\Proxy\\TrustProxies->handle()
#53 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#54 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(141): Illuminate\\Pipeline\\Pipeline->then()
#55 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(110): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter()
#56 /var/www/html/public/index.php(99): Illuminate\\Foundation\\Http\\Kernel->handle()
#57 {main}
"} 
200.205.10.14 - - [16/Nov/2020:02:59:31 -0600] "GET /callback?code={{REDACT}}&state={{REDACT}} HTTP/1.0" 500 7697 "-" "Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:82.0) Gecko/20100101 Firefox/82.0"
200.205.10.14 - - [16/Nov/2020:02:59:32 -0600] "GET /favicon.ico HTTP/1.0" 200 243 "http://fireimp.home.net/callback?code={{REDACT}}&state={{REDACT}}" "Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:82.0) Gecko/20100101 Firefox/82.0"
```

**Bonus points**

- I searched and nobody reported this bug before
- I have added a stack trace from my log files 
- I have added a screenshot.

**Comment by JC5** [comment]
The vanity URL is necessary when you can't use the FIREFLY_III_URL. It is only used for redirecting you to Firefly III. You are redirected to the vanity URL when permission is needed [here](https://github.com/firefly-iii/csv-importer/blob/main/app/Http/Controllers/TokenController.php#L86) and [here](https://github.com/firefly-iii/csv-importer/blob/main/app/Http/Controllers/TokenController.php#L128).

If you want an internal redirect instead of an external one, I suggest you stop using VANITY_URI.

**Comment by jhelbig** [comment]
Both of those work exactly as expected from what I can see.  It's still necessary to use both the vanity and firefly URLs though.  From what I can see these are the steps that are taking place.

- The user visits fireimp.home.net
- User accepts auth request and is redirected to firefly.home.net via browser for authorization
- The user is then sent back to the fireimp.home.net/callback url
- The csv-importer service then attempts to request an oauth token to the vanity url(should be the Firefly III url)
- Upon successful authentication csv-service makes subsequent API calls with oauth token

The problem seems to be happening when the csv-importer is requesting for an oauth token [here](https://github.com/firefly-iii/csv-importer/blob/main/app/Http/Controllers/TokenController.php#L200).

I'm not sure at what point, but it somehow flips to be the vanity URL instead of the Firefly III URL.  In the original post I may not have included enough of the log, but this is one I have just generated without the stacktrace, but it is the same.

From the debug output it looks like the base URL is being set to firefly:8080, but at some point(maybe where the ?????? is) it's being set to be firefly.home.net.

```
[2020-11-16 20:37:34] production.DEBUG: Now at App\Http\Controllers\IndexController::index  
>>>>>> [2020-11-16 20:37:34] production.DEBUG: Base URL: ""  
[2020-11-16 20:37:34] production.DEBUG: No access token cookie, redirect to token.index  
200.205.10.14 - - [16/Nov/2020:20:37:34 -0600] "GET / HTTP/1.0" 302 1520 "-" "Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:82.0) Gecko/20100101 Firefox/82.0"
[2020-11-16 20:37:35] production.DEBUG: Now at App\Http\Controllers\TokenController::index  
[2020-11-16 20:37:35] production.INFO: The following configuration information was found:  
[2020-11-16 20:37:35] production.INFO: Personal Access Token: "". (limited to 25 chars if present)  
[2020-11-16 20:37:35] production.INFO: Client ID            : {{REDACT}}.  
>>>>>> [2020-11-16 20:37:35] production.INFO: Base URL             : "http://firefly:8080".  
[2020-11-16 20:37:35] production.DEBUG: Found client ID {{REDACT}} + URL "http://firefly:8080" in config, redirect to Firefly III for permission.  
[2020-11-16 20:37:35] production.DEBUG: Query parameters are {"client_id":{{REDACT}},"redirect_uri":"http://fireimp.home.net/callback","response_type":"code","scope":"","state":"{{REDACT}}","code_challenge":"{{REDACT}}","code_challenge_method":"S256"} 
?????? [2020-11-16 20:37:35] production.DEBUG: Now redirecting to "http://firefly.home.net/oauth/authorize?" (params omitted)  
200.205.10.14 - - [16/Nov/2020:20:37:35 -0600] "GET /token HTTP/1.0" 302 2817 "-" "Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:82.0) Gecko/20100101 Firefox/82.0"
[2020-11-16 20:37:59] production.DEBUG: Now at App\Http\Controllers\TokenController::callback  
[2020-11-16 20:37:59] production.DEBUG: State is valid!  
[2020-11-16 20:37:59] production.DEBUG: Params for access token {"form_params":{"grant_type":"authorization_code","client_id":{{REDACT}},"redirect_uri":"http://fireimp.home.net/callback","code_verifier":"{{REDACT}}","code":"{{REDACT}}"}} 
>>>>>> [2020-11-16 20:37:59] production.DEBUG: Will contact "http://firefly.home.net/oauth/token" for a token.  
>>>>>> [2020-11-16 20:37:59] production.ERROR: cURL error 7: Failed to connect to firefly.home.net port 80: Connection refused (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for http://firefly.home.net/oauth/token {"exception":"[object] (GuzzleHttp\\Exception\\ConnectException(code: 0): cURL error 7: Failed to connect to firefly.home.net port 80: Connection refused (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for http://firefly.home.net/oauth/token at /var/www/html/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php:210)
[stacktrace]
```

By the way thanks for the fast response!

**Comment by JC5** [comment]
I see what you mean, I'll pick it up!

**Comment by JC5** [comment]
Could you check if the `develop` tag solves this issue?

**Comment by jhelbig** [comment]
Sorry I didn't get back yet, this almost works.  It looks like a typo [here](https://github.com/firefly-iii/csv-importer/blob/develop/app/Http/Controllers/TokenController.php#L244) is setting the token_url to be the base_url instead.  Once I made the change locally the following logs happened.

```
[2020-11-19 23:58:33] production.DEBUG: Now at App\Http\Controllers\TokenController::callback  
[2020-11-19 23:58:33] production.DEBUG: State is valid!  
[2020-11-19 23:58:33] production.DEBUG: Params for access token {"form_params":{"grant_type":"authorization_code","client_id":{{REDACT}},"redirect_uri":"http://fireimp.home.net/callback","code_verifier":"{{REDACT}}","code":"{{REDACT}}"}} 
[2020-11-19 23:58:33] production.DEBUG: Will contact "http://firefly:8080/oauth/token" for a token.  
[2020-11-19 23:58:34] production.DEBUG: Response {"token_type":"Bearer","expires_in":1209600,"access_token":"{{REDACT}}","refresh_token":"{{REDACT}}"} 
[2020-11-19 23:58:34] production.DEBUG: Return redirect with cookies to "http://fireimp.home.net"  
200.205.10.5 - - [19/Nov/2020:23:58:32 -0600] "GET /callback?code={{REDACT}}&state={{REDACT}} HTTP/1.0" 302 5410 "-" "Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:82.0) Gecko/20100101 Firefox/82.0"
200.205.10.5 - - [19/Nov/2020:23:58:35 -0600] "GET /favicon.ico HTTP/1.0" 200 243 "http://fireimp.home.net/callback?code={{REDACT}}&state={{REDACT}}" "Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:82.0) Gecko/20100101 Firefox/82.0"
```

I'm getting a 502 now so there's some debugging on my proxy I'll need to dig into, but from the application side it looks good after the adjustment.

Thanks for the help!

**Comment by JC5** [comment]
Whoops, nicely spotted.

**Comment by JC5** [comment]
New release is out :+1:

**Comment by evanre** [comment]
Hi, @jhelbig could you please, provide your working configs for nginx and docker-compose. I'm trying to set up similar env (docker + nginx revers proxy + money.site.com(firefly) + money-csv.site.com or money.site.com/csv). 

I can't make csv importer working (subdomain fails while auth, subfolder doesn't work at all, wrong redirect to /token instead of /csv/token)
