### ISSUE TITLE
Fireflycsv - Could not connect to Firefly III auto-import, 500 error when authorizing

### ISSUE THREAD

**Issue by bartekd123** [firefly-iii/firefly-iii#4116]
**Bug description**
I am running Firefly III version 5.4.6, fireflycsv 2.3.1 , and my problem is:

I had fireflycsv working, and when I updated it, it stopped working. When I do the auto-upload, I get the following error:

```
Could not connect to Firefly III: cURL error 3:  (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for /api/v1/about
Could not connect to your local Firefly III instance.

```

When I connect to the webpage, and try to authenticate, I get a 500 error (with the logs below). I tried re-creating the oauth client and set it up again, but it doesn't want to work.

Any help is appreciated.

**Steps to reproduce**
Connect to the fireflycsv website, and authenticate - 500 error
using auto-import using command line gives the above error

**Extra info**

firefly docker logs (replacing part of the code, and my URL):

```
10.150.3.5 - - [02/Dec/2020:18:18:23 -0500] "GET /oauth/authorize?client_id=64&redirect_uri=http%3A%2F%2F10.150.3.38%3A8080%2Fcallback&response_type=code&scope=&state=dHKJmxv----------KO5dNznm&code_challenge=KO7cq----------mZw&code_challenge_method=S256 HTTP/1.1" 200 3441 "http://10.150.3.38:8080/token" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.1 Safari/605.1.15"
10.150.3.5 - - [02/Dec/2020:18:18:23 -0500] "GET /v1/lib/fa/css/font-awesome.min.css?v= HTTP/1.1" 200 7319 "https://firefly.HostnameRedacted/oauth/authorize?client_id=64&redirect_uri=http%3A%2F%2F10.150.3.38%3A8080%2Fcallback&response_type=code&scope=&state=dHKJmxv----------KO5dNznm&code_challenge=KO7cq----------mZw&code_challenge_method=S256" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.1 Safari/605.1.15"
10.150.3.5 - - [02/Dec/2020:18:18:23 -0500] "GET /v1/lib/adminlte/css/skins/skin-blue-light.min.css?v= HTTP/1.1" 200 1067 "https://firefly.HostnameRedacted/oauth/authorize?client_id=64&redirect_uri=http%3A%2F%2F10.150.3.38%3A8080%2Fcallback&response_type=code&scope=&state=dHKJmxv----------KO5dNznm&code_challenge=KO7cq----------mZw&code_challenge_method=S256" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.1 Safari/605.1.15"
10.150.3.5 - - [02/Dec/2020:18:18:23 -0500] "GET /v1/css/firefly.css?v= HTTP/1.1" 200 2437 "https://firefly.HostnameRedacted/oauth/authorize?client_id=64&redirect_uri=http%3A%2F%2F10.150.3.38%3A8080%2Fcallback&response_type=code&scope=&state=dHKJmxv----------KO5dNznm&code_challenge=KO7cq----------mZw&code_challenge_method=S256" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.1 Safari/605.1.15"
10.150.3.5 - - [02/Dec/2020:18:18:23 -0500] "GET /v1/lib/adminlte/css/AdminLTE.min.css?v= HTTP/1.1" 200 15269 "https://firefly.HostnameRedacted/oauth/authorize?client_id=64&redirect_uri=http%3A%2F%2F10.150.3.38%3A8080%2Fcallback&response_type=code&scope=&state=dHKJmxv----------KO5dNznm&code_challenge=KO7cq----------mZw&code_challenge_method=S256" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.1 Safari/605.1.15"
10.150.3.5 - - [02/Dec/2020:18:18:23 -0500] "GET /v1/lib/bs/css/bootstrap.min.css?v= HTTP/1.1" 200 20012 "https://firefly.HostnameRedacted/oauth/authorize?client_id=64&redirect_uri=http%3A%2F%2F10.150.3.38%3A8080%2Fcallback&response_type=code&scope=&state=dHKJmxv----------KO5dNznm&code_challenge=KO7cq----------mZw&code_challenge_method=S256" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.1 Safari/605.1.15"
10.150.3.5 - - [02/Dec/2020:18:18:23 -0500] "GET /v1/css/gf-source.css HTTP/1.1" 200 695 "https://firefly.HostnameRedacted/oauth/authorize?client_id=64&redirect_uri=http%3A%2F%2F10.150.3.38%3A8080%2Fcallback&response_type=code&scope=&state=dHKJmxv----------KO5dNznm&code_challenge=KO7cq----------mZw&code_challenge_method=S256" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.1 Safari/605.1.15"
10.150.3.5 - - [02/Dec/2020:18:18:23 -0500] "GET /v1/fonts/source-sans-pro-v13-greek_cyrillic-ext_vietnamese_greek-ext_latin-ext_cyrillic_latin-regular.woff2 HTTP/1.1" 200 62905 "https://firefly.HostnameRedacted/oauth/authorize?client_id=64&redirect_uri=http%3A%2F%2F10.150.3.38%3A8080%2Fcallback&response_type=code&scope=&state=dHKJmxv----------KO5dNznm&code_challenge=KO7cq----------mZw&code_challenge_method=S256" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.1 Safari/605.1.15"
10.150.3.5 - - [02/Dec/2020:18:18:23 -0500] "GET /v1/fonts/source-sans-pro-v13-greek_cyrillic-ext_vietnamese_greek-ext_latin-ext_cyrillic_latin-700.woff2 HTTP/1.1" 200 61741 "https://firefly.HostnameRedacted/oauth/authorize?client_id=64&redirect_uri=http%3A%2F%2F10.150.3.38%3A8080%2Fcallback&response_type=code&scope=&state=dHKJmxv----------KO5dNznm&code_challenge=KO7cq----------mZw&code_challenge_method=S256" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.1 Safari/605.1.15"
10.150.3.5 - - [02/Dec/2020:18:18:26 -0500] "POST /oauth/authorize HTTP/1.1" 302 2607 "https://firefly.HostnameRedacted/oauth/authorize?client_id=64&redirect_uri=http%3A%2F%2F10.150.3.38%3A8080%2Fcallback&response_type=code&scope=&state=dHKJmxv----------KO5dNznm&code_challenge=KO7cq----------mZw&code_challenge_method=S256" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.1 Safari/605.1.15"

```

Fireflycsv logs

```
10.150.1.178 - - [02/Dec/2020:18:18:23 -0500] "POST /token/client_id HTTP/1.1" 302 2851 "http://10.150.3.38:8080/token" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.1 Safari/605.1.15"
[2020-12-03 00:18:26] production.DEBUG: Now at App\Http\Controllers\TokenController::callback  
[2020-12-03 00:18:26] production.DEBUG: State is valid!  
[2020-12-03 00:18:26] production.DEBUG: Params for access token {"form_params":{"grant_type":"authorization_code","client_id":64,"redirect_uri":"http://10.150.3.38:8080/callback","code_verifier":"jDaiHxZpLFkZgqVg3LkKMQNZYPeY0g2vVI7cqaa2HX8jMxMrv749p0nOJZWBrKAdjSAglav3ozHlhvho51pkSVmjjK2KEyX8h1S3DDDbwalKi8TqLuqmTGFOqtgddvNL","code":"def502008272798adb60c15597884c3203d128fdcdd84ab31db586d0519bb35b83a0b900472b303b33afcddf9c43ae991831a0aa7cb7650d503de22207316de3c06bcc40ad662937cd249ab262dba----------5e303e7c5802"}} 
[2020-12-03 00:18:26] production.DEBUG: Will contact "/oauth/token" for a token.  
[2020-12-03 00:18:26] production.ERROR: cURL error 3:  (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for /oauth/token {"exception":"[object] (GuzzleHttp\\Exception\\RequestException(code: 0): cURL error 3:  (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for /oauth/token at /var/www/html/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php:211)
[stacktrace]
#0 /var/www/html/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(158): GuzzleHttp\\Handler\\CurlFactory::createRejection()
#1 /var/www/html/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(110): GuzzleHttp\\Handler\\CurlFactory::finishError()
#2 /var/www/html/vendor/guzzlehttp/guzzle/src/Handler/CurlHandler.php(47): GuzzleHttp\\Handler\\CurlFactory::finish()
#3 /var/www/html/vendor/guzzlehttp/guzzle/src/Handler/Proxy.php(28): GuzzleHttp\\Handler\\CurlHandler->__invoke()
#4 /var/www/html/vendor/guzzlehttp/guzzle/src/Handler/Proxy.php(48): GuzzleHttp\\Handler\\Proxy::GuzzleHttp\\Handler\\{closure}()
#5 /var/www/html/vendor/guzzlehttp/guzzle/src/PrepareBodyMiddleware.php(64): GuzzleHttp\\Handler\\Proxy::GuzzleHttp\\Handler\\{closure}()
#6 /var/www/html/vendor/guzzlehttp/guzzle/src/Middleware.php(31): GuzzleHttp\\PrepareBodyMiddleware->__invoke()
#7 /var/www/html/vendor/guzzlehttp/guzzle/src/RedirectMiddleware.php(71): GuzzleHttp\\Middleware::GuzzleHttp\\{closure}()
#8 /var/www/html/vendor/guzzlehttp/guzzle/src/Middleware.php(63): GuzzleHttp\\RedirectMiddleware->__invoke()
#9 /var/www/html/vendor/guzzlehttp/guzzle/src/HandlerStack.php(75): GuzzleHttp\\Middleware::GuzzleHttp\\{closure}()
#10 /var/www/html/vendor/guzzlehttp/guzzle/src/Client.php(331): GuzzleHttp\\HandlerStack->__invoke()
#11 /var/www/html/vendor/guzzlehttp/guzzle/src/Client.php(168): GuzzleHttp\\Client->transfer()
#12 /var/www/html/vendor/guzzlehttp/guzzle/src/Client.php(187): GuzzleHttp\\Client->requestAsync()
#13 /var/www/html/vendor/guzzlehttp/guzzle/src/ClientTrait.php(95): GuzzleHttp\\Client->request()
#14 /var/www/html/app/Http/Controllers/TokenController.php(207): GuzzleHttp\\Client->post()
#15 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): App\\Http\\Controllers\\TokenController->callback()
#16 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\\Routing\\Controller->callAction()
#17 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Route.php(254): Illuminate\\Routing\\ControllerDispatcher->dispatch()
#18 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Route.php(197): Illuminate\\Routing\\Route->runController()
#19 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(692): Illuminate\\Routing\\Route->run()
#20 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}()
#21 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(41): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#22 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle()
#23 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(77): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#24 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle()
#25 /var/www/html/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#26 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle()
#27 /var/www/html/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(121): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#28 /var/www/html/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(63): Illuminate\\Session\\Middleware\\StartSession->handleStatefulRequest()
#29 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Session\\Middleware\\StartSession->handle()
#30 /var/www/html/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#31 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle()
#32 /var/www/html/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(67): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#33 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle()
#34 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#35 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(694): Illuminate\\Pipeline\\Pipeline->then()
#36 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(669): Illuminate\\Routing\\Router->runRouteWithinStack()
#37 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(635): Illuminate\\Routing\\Router->runRoute()
#38 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(624): Illuminate\\Routing\\Router->dispatchToRoute()
#39 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(166): Illuminate\\Routing\\Router->dispatch()
#40 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}()
#41 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#42 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#43 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#44 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#45 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#46 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle()
#47 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(87): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#48 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance->handle()
#49 /var/www/html/vendor/fruitcake/laravel-cors/src/HandleCors.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#50 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Fruitcake\\Cors\\HandleCors->handle()
#51 /var/www/html/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#52 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Fideloper\\Proxy\\TrustProxies->handle()
#53 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#54 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(141): Illuminate\\Pipeline\\Pipeline->then()
#55 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(110): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter()
#56 /var/www/html/public/index.php(99): Illuminate\\Foundation\\Http\\Kernel->handle()
#57 {main}
"} 
10.150.1.178 - - [02/Dec/2020:18:18:26 -0500] "GET /callback?code=de----------0b900472b303b33afcddf9c43ae991831a0aa7cb7650d503de22207316de3c06bcc40ad662937cd249ab262dba----------5e303e7c5802&state=dHKJmxvVm8----------dNznm HTTP/1.1" 500 7666 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.1 Safari/605.1.15"
10.150.1.178 - - [02/Dec/2020:18:18:26 -0500] "GET /favicon.ico HTTP/1.1" 304 163 "http://10.150.3.38:8080/callback?code=def502008272798adb60c15597884c3203d128fdcdd84ab31db586d0519bb35b83a0b900472b303b33afcddf9c43ae991831a0aa7cb7650d503de22207316de3c06bcc40ad662937cd249ab262dba----------5e303e7c5802&state=dHKJmxvVm8----------dNznm" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.1 Safari/605.1.15"
```

**Comment by JC5** [comment]
> [2020-12-03 00:18:26] production.DEBUG: Will contact "/oauth/token" for a token.  

You edited this so I can't tell. Is this the correct URL from the perspective of the CSV importer Docker container?

**Comment by sftman18** [comment]
@bartekd123
Check the script that you used to launch the CSV importer.  I got the same error, and I needed to change the environment variable name from:
FIREFLY_III_URI
to:
FIREFLY_III_URL

**Comment by bartekd123** [comment]
Thanks @JC5 , but it was the docker attribute name that was changed.

Thanks @sftman18 that was it. I updated it from URI to URL and it works now.
