### ISSUE TITLE
Failed to open stream: No such file or directory during importing

### ISSUE THREAD

**Issue by nicolazilio** [firefly-iii/firefly-iii#4125]
I am running Firefly III version 5.4.6.

**Description**
While importing data using firefly-iii-fints-importer, which was proceeding fine, I got this error

Fatal error: Uncaught GrumpyDictator\FFIIIApiSupport\Exceptions\ApiHttpException: Status code is 500: {"message":"Internal Firefly III Exception: file_put_contents(\/mnt\/sdcard\/home\/admin\/www\/firefly-iii\/storage\/framework\/cache\/data\/22\/19\/2219d739ab8bc7ef3ab90d9e1ce281626ed89675): failed to open stream: No such file or directory","exception":"ErrorException"} in /mnt/sdcard/home/admin/www/firefly-iii-fints-importer/vendor/firefly-iii/api-support-classes/src/Request/PostTransactionRequest.php:70 Stack trace: #0 /mnt/sdcard/home/admin/www/firefly-iii-fints-importer/app/TransactionsToFireflySender.php(90): GrumpyDictator\FFIIIApiSupport\Request\PostTransactionRequest->post() #1 /mnt/sdcard/home/admin/www/firefly-iii-fints-importer/app/index.php(260): App\TransactionsToFireflySender->send_transactions() #2 {main} thrown in /mnt/sdcard/home/admin/www/firefly-iii-fints-importer/vendor/firefly-iii/api-support-classes/src/Request/PostTransactionRequest.php on line 70

`file_put_contents(/mnt/sdcard/home/admin/www/firefly-iii/storage/framework/cache/data/22/19/2219d739ab8bc7ef3ab90d9e1ce281626ed89675): failed to open stream: No such file or directory`

And now I cannot access Firefly III because `Whoops! An error occurred. Unfortunately, this error was not recoverable :(. Firefly III broke`

Any ideas how to prevent this error in the future? And also how to recover from it? Shall I just drop the DB and create a new one?

Thank you in advance

Nicola

**Extra info**
Debug information generated at 2020-12-05 17:25:22 Europe/Amsterdam for Firefly III version **5.4.6**.

| Scope | Version |
| --- | --- |
| Firefly III | 5.4.6 |
| Firefly III API | 1.4.0 |
| PHP | 7.4.13 |
| Host | Linux |

| System info | Value |
| --- | --- |
| Installation ID | 6f9a9ce3-7c88-448c-89e4-19b22b7e7892 |
| Using docker? | false |
| Telemetry | false |
| Layout | v1 |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | notice, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Interface | fpm-fcgi |
| Default language | en_US |
| Default locale | equal |
| BCscale | 12 |
| DB drivers | mysql, sqlite |
| Current driver | mysql |
| DB version | 15 (exp. 15) |
| Login provider | eloquent  |
| Trusted proxies (.env) | ** |

| User info | Value |
| --- | --- |
| Session start | 2020-12-01 00:00:00 |
| Session end | 2020-12-31 23:59:59 |
| Session first | 2020-12-05 15:39:28 |
| User ID | 1 |
| User language | en_GB |
| User locale | en_GB |
| Attempt at "en_GB.utf8" | 'en_GB.utf8' |
| Attempt at "en_GB.UTF-8" | 'en_GB.UTF-8' |
| User agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.67 Safari/537.36 Edg/87.0.664.52 |

```
Truncated from this point <----|pport/Amount.php(282): FireflyIII\\Support\\Amount->getDefaultCurrencyByUser()
#10 /mnt/sdcard/home/admin/www/firefly-iii/app/Http/Middleware/Range.php(98): FireflyIII\\Support\\Amount->getDefaultCurrency()
#11 /mnt/sdcard/home/admin/www/firefly-iii/app/Http/Middleware/Range.php(54): FireflyIII\\Http\\Middleware\\Range->configureView()
#12 /mnt/sdcard/home/admin/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): FireflyIII\\Http\\Middleware\\Range->handle()
#13 /mnt/sdcard/home/admin/www/firefly-iii/vendor/jc5/google2fa-laravel/src/Middleware.php(29): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#14 /mnt/sdcard/home/admin/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): PragmaRX\\Google2FALaravel\\Middleware->handle()
#15 /mnt/sdcard/home/admin/www/firefly-iii/app/Http/Middleware/Authenticate.php(74): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#16 /mnt/sdcard/home/admin/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): FireflyIII\\Http\\Middleware\\Authenticate->handle()
#17 /mnt/sdcard/home/admin/www/firefly-iii/vendor/laravel/passport/src/Http/Middleware/CreateFreshApiToken.php(50): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#18 /mnt/sdcard/home/admin/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Laravel\\Passport\\Http\\Middleware\\CreateFreshApiToken->handle()
#19 /mnt/sdcard/home/admin/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Session/Middleware/AuthenticateSession.php(58): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#20 /mnt/sdcard/home/admin/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Session\\Middleware\\AuthenticateSession->handle()
#21 /mnt/sdcard/home/admin/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(77): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#22 /mnt/sdcard/home/admin/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle()
#23 /mnt/sdcard/home/admin/www/firefly-iii/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#24 /mnt/sdcard/home/admin/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle()
#25 /mnt/sdcard/home/admin/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(121): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#26 /mnt/sdcard/home/admin/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(63): Illuminate\\Session\\Middleware\\StartSession->handleStatefulRequest()
#27 /mnt/sdcard/home/admin/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Session\\Middleware\\StartSession->handle()
#28 /mnt/sdcard/home/admin/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#29 /mnt/sdcard/home/admin/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle()
#30 /mnt/sdcard/home/admin/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(67): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#31 /mnt/sdcard/home/admin/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle()
#32 /mnt/sdcard/home/admin/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#33 /mnt/sdcard/home/admin/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Routing/Router.php(693): Illuminate\\Pipeline\\Pipeline->then()
#34 /mnt/sdcard/home/admin/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Routing/Router.php(668): Illuminate\\Routing\\Router->runRouteWithinStack()
#35 /mnt/sdcard/home/admin/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Routing/Router.php(634): Illuminate\\Routing\\Router->runRoute()
#36 /mnt/sdcard/home/admin/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Routing/Router.php(623): Illuminate\\Routing\\Router->dispatchToRoute()
#37 /mnt/sdcard/home/admin/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(166): Illuminate\\Routing\\Router->dispatch()
#38 /mnt/sdcard/home/admin/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}()
#39 /mnt/sdcard/home/admin/www/firefly-iii/app/Http/Middleware/InstallationId.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#40 /mnt/sdcard/home/admin/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): FireflyIII\\Http\\Middleware\\InstallationId->handle()
#41 /mnt/sdcard/home/admin/www/firefly-iii/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#42 /mnt/sdcard/home/admin/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Fideloper\\Proxy\\TrustProxies->handle()
#43 /mnt/sdcard/home/admin/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#44 /mnt/sdcard/home/admin/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#45 /mnt/sdcard/home/admin/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#46 /mnt/sdcard/home/admin/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#47 /mnt/sdcard/home/admin/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#48 /mnt/sdcard/home/admin/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle()
#49 /mnt/sdcard/home/admin/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(87): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#50 /mnt/sdcard/home/admin/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance->handle()
#51 /mnt/sdcard/home/admin/www/firefly-iii/app/Http/Middleware/SecureHeaders.php(51): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#52 /mnt/sdcard/home/admin/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): FireflyIII\\Http\\Middleware\\SecureHeaders->handle()
#53 /mnt/sdcard/home/admin/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#54 /mnt/sdcard/home/admin/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(141): Illuminate\\Pipeline\\Pipeline->then()
#55 /mnt/sdcard/home/admin/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(110): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter()
#56 /mnt/sdcard/home/admin/www/firefly-iii/public/index.php(76): Illuminate\\Foundation\\Http\\Kernel->handle()
#57 {main}
"} 

```

**Comment by JC5** [comment]
Try browsing to `/flush`. If that doesn't work, just delete the container and restart it again.

**Comment by nicolazilio** [comment]
Yes, that did it! Maybe it would be good to mention this possible solution in the error 404 page. Thanks a lot again.
