### ISSUE TITLE
Unfortunately, this error was not recoverable :(. Firefly III broke. The error is:  fwrite(): write of 552 bytes failed with errno=9 Bad file descriptor

### ISSUE THREAD

**Issue by jglassonnz** [firefly-iii/firefly-iii#4131]
I am running Firefly III version 5.4.6
I have both PHP v7.4 and v8.0 Non Thread Safe installed.

I am attempting to install Firefly III on a Windows IIS Server, install went smoothly but after seeding the data base and attempting to load into firefly I get the following issue.

```
Whoops! An error occurred.
Unfortunately, this error was not recoverable :(. Firefly III broke. The error is:

fwrite(): write of 552 bytes failed with errno=9 Bad file descriptor

Error
This error occured in file C:\inetpub\clientmanager\firefly-iii\vendor\monolog\monolog\src\Monolog\Handler\StreamHandler.php on line 134 with code 0.

Stack trace
#0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError()
#1 C:\inetpub\clientmanager\firefly-iii\vendor\monolog\monolog\src\Monolog\Handler\StreamHandler.php(134): fwrite()
#2 C:\inetpub\clientmanager\firefly-iii\vendor\monolog\monolog\src\Monolog\Handler\StreamHandler.php(120): Monolog\Handler\StreamHandler->streamWrite()
#3 C:\inetpub\clientmanager\firefly-iii\vendor\monolog\monolog\src\Monolog\Handler\AbstractProcessingHandler.php(42): Monolog\Handler\StreamHandler->write()
#4 C:\inetpub\clientmanager\firefly-iii\vendor\monolog\monolog\src\Monolog\Logger.php(325): Monolog\Handler\AbstractProcessingHandler->handle()
#5 C:\inetpub\clientmanager\firefly-iii\vendor\monolog\monolog\src\Monolog\Logger.php(543): Monolog\Logger->addRecord()
#6 C:\inetpub\clientmanager\firefly-iii\vendor\laravel\framework\src\Illuminate\Log\Logger.php(174): Monolog\Logger->error()
#7 C:\inetpub\clientmanager\firefly-iii\vendor\laravel\framework\src\Illuminate\Log\Logger.php(87): Illuminate\Log\Logger->writeLog()
#8 C:\inetpub\clientmanager\firefly-iii\vendor\laravel\framework\src\Illuminate\Log\LogManager.php(547): Illuminate\Log\Logger->error()
#9 C:\inetpub\clientmanager\firefly-iii\vendor\laravel\framework\src\Illuminate\Support\Facades\Facade.php(261): Illuminate\Log\LogManager->error()
#10 C:\inetpub\clientmanager\firefly-iii\app\Jobs\MailError.php(67): Illuminate\Support\Facades\Facade::__callStatic()
#11 C:\inetpub\clientmanager\firefly-iii\app\Exceptions\Handler.php(153): FireflyIII\Jobs\MailError->__construct()
#12 C:\inetpub\clientmanager\firefly-iii\vendor\laravel\framework\src\Illuminate\Foundation\Bootstrap\HandleExceptions.php(88): FireflyIII\Exceptions\Handler->report()
#13 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleException()
#14 {main}
```

**Comment by JC5** [comment]
See #3646

**Comment by jglassonnz** [comment]
Thank you for the quick response. 
I have tried both the non thread safe and thread safe versions of PHP 7.4 and 8.0 and it is making no difference.

**Comment by Moc** [comment]
@jglassonnz I just upgraded to PHP 8 and got the same issue with the NTS version. TS works without the error. I prefer NTS but for Firefly I'll switch to TS when I need it.
