### ISSUE TITLE
Bug: change email not working

### ISSUE THREAD

**Issue by lastlink** [firefly-iii/firefly-iii#4145]
**Bug description**
I am running Firefly III version 5.4.0, and my problem is:

change email is not working. Gives 500 page. Forgot email works using smtp and gmail provider.

**Steps to reproduce**
Try to change email and end up on 500 page

**Extra info**
log
```txt
[2020-12-12 15:23:00] local.ERROR: Method FireflyIII\Http\Requests\EmailFormRequest::string does not exist. {"userId":2,"exception":"[object] (BadMethodCallException(code: 0): Method FireflyIII\\Http\\Requests\\EmailFormRequest::string does not exist. at C:\\Users\\test\\firefly-iii\\vendor\\laravel\\framework\\src\\Illuminate\\Support\\Traits\\Macroable.php:103)
[stacktrace]
#0 C:\\Users\\test\\firefly-iii\\app\\Http\\Controllers\\ProfileController.php(410): Illuminate\\Http\\Request->__call()
#1 [internal function]: FireflyIII\\Http\\Controllers\\ProfileController->postChangeEmail()
#2 C:\\Users\\test\\firefly-iii\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Controller.php(54): call_user_func_array()
#3 C:\\Users\\test\\firefly-iii\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\ControllerDispatcher.php(45): Illuminate\\Routing\\Controller->callAction()
#4 C:\\Users\\test\\firefly-iii\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Route.php(239): Illuminate\\Routing\\ControllerDispatcher->dispatch()
#5 C:\\Users\\test\\firefly-iii\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Route.php(196): Illuminate\\Routing\\Route->runController()
#6 C:\\Users\\test\\firefly-iii\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(685): Illuminate\\Routing\\Route->run()
#7 C:\\Users\\test\\firefly-iii\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(128): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}()
#8 C:\\Users\\test\\firefly-iii\\app\\Http\\Middleware\\IsDemoUser.php(66): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#9 C:\\Users\\test\\firefly-iii\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): FireflyIII\\Http\\Middleware\\IsDemoUser->handle()
#10 C:\\Users\\test\\firefly-iii\\app\\Http\\Controllers\\ProfileController.php(79): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#11 C:\\Users\\test\\firefly-iii\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(149): FireflyIII\\Http\\Controllers\\ProfileController::FireflyIII\\Http\\Controllers\\{closure}()
#12 C:\\Users\\test\\firefly-iii\\app\\Http\\Controllers\\Controller.php(108): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#13 C:\\Users\\test\\firefly-iii\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(149): FireflyIII\\Http\\Controllers\\Controller->FireflyIII\\Http\\Controllers\\{closure}()
#14 C:\\Users\\test\\firefly-iii\\app\\Http\\Middleware\\InterestingMessage.php(58): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#15 C:\\Users\\test\\firefly-iii\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): FireflyIII\\Http\\Middleware\\InterestingMessage->handle()
#16 C:\\Users\\test\\firefly-iii\\app\\Http\\Middleware\\Binder.php(79): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#17 C:\\Users\\test\\firefly-iii\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): FireflyIII\\Http\\Middleware\\Binder->handle()
#18 C:\\Users\\test\\firefly-iii\\app\\Http\\Middleware\\Range.php(61): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#19 C:\\Users\\test\\firefly-iii\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): FireflyIII\\Http\\Middleware\\Range->handle()
#20 C:\\Users\\test\\firefly-iii\\vendor\\jc5\\google2fa-laravel\\src\\Middleware.php(29): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#21 C:\\Users\\test\\firefly-iii\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): PragmaRX\\Google2FALaravel\\Middleware->handle()
#22 C:\\Users\\test\\firefly-iii\\app\\Http\\Middleware\\Authenticate.php(74): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#23 C:\\Users\\test\\firefly-iii\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): FireflyIII\\Http\\Middleware\\Authenticate->handle()
#24 C:\\Users\\test\\firefly-iii\\vendor\\laravel\\passport\\src\\Http\\Middleware\\CreateFreshApiToken.php(50): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#25 C:\\Users\\test\\firefly-iii\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): Laravel\\Passport\\Http\\Middleware\\CreateFreshApiToken->handle()
#26 C:\\Users\\test\\firefly-iii\\vendor\\laravel\\framework\\src\\Illuminate\\Session\\Middleware\\AuthenticateSession.php(58): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#27 C:\\Users\\test\\firefly-iii\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): Illuminate\\Session\\Middleware\\AuthenticateSession->handle()
#28 C:\\Users\\test\\firefly-iii\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken.php(77): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#29 C:\\Users\\test\\firefly-iii\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle()
#30 C:\\Users\\test\\firefly-iii\\vendor\\laravel\\framework\\src\\Illuminate\\View\\Middleware\\ShareErrorsFromSession.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#31 C:\\Users\\test\\firefly-iii\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle()
#32 C:\\Users\\test\\firefly-iii\\vendor\\laravel\\framework\\src\\Illuminate\\Session\\Middleware\\StartSession.php(116): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#33 C:\\Users\\test\\firefly-iii\\vendor\\laravel\\framework\\src\\Illuminate\\Session\\Middleware\\StartSession.php(62): Illuminate\\Session\\Middleware\\StartSession->handleStatefulRequest()
#34 C:\\Users\\test\\firefly-iii\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): Illuminate\\Session\\Middleware\\StartSession->handle()
#35 C:\\Users\\test\\firefly-iii\\vendor\\laravel\\framework\\src\\Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#36 C:\\Users\\test\\firefly-iii\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle()
#37 C:\\Users\\test\\firefly-iii\\vendor\\laravel\\framework\\src\\Illuminate\\Cookie\\Middleware\\EncryptCookies.php(67): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#38 C:\\Users\\test\\firefly-iii\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle()
#39 C:\\Users\\test\\firefly-iii\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#40 C:\\Users\\test\\firefly-iii\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(687): Illuminate\\Pipeline\\Pipeline->then()
#41 C:\\Users\\test\\firefly-iii\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(662): Illuminate\\Routing\\Router->runRouteWithinStack()
#42 C:\\Users\\test\\firefly-iii\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(628): Illuminate\\Routing\\Router->runRoute()
#43 C:\\Users\\test\\firefly-iii\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(617): Illuminate\\Routing\\Router->dispatchToRoute()
#44 C:\\Users\\test\\firefly-iii\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Kernel.php(165): Illuminate\\Routing\\Router->dispatch()
#45 C:\\Users\\test\\firefly-iii\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(128): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}()
#46 C:\\Users\\test\\firefly-iii\\vendor\\barryvdh\\laravel-debugbar\\src\\Middleware\\InjectDebugbar.php(58): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#47 C:\\Users\\test\\firefly-iii\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): Barryvdh\\Debugbar\\Middleware\\InjectDebugbar->handle()
#48 C:\\Users\\test\\firefly-iii\\app\\Http\\Middleware\\InstallationId.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#49 C:\\Users\\test\\firefly-iii\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): FireflyIII\\Http\\Middleware\\InstallationId->handle()
#50 C:\\Users\\test\\firefly-iii\\vendor\\fideloper\\proxy\\src\\TrustProxies.php(57): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#51 C:\\Users\\test\\firefly-iii\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): Fideloper\\Proxy\\TrustProxies->handle()
#52 C:\\Users\\test\\firefly-iii\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#53 C:\\Users\\test\\firefly-iii\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#54 C:\\Users\\test\\firefly-iii\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#55 C:\\Users\\test\\firefly-iii\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#56 C:\\Users\\test\\firefly-iii\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#57 C:\\Users\\test\\firefly-iii\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle()
#58 C:\\Users\\test\\firefly-iii\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode.php(63): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#59 C:\\Users\\test\\firefly-iii\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode->handle()
#60 C:\\Users\\test\\firefly-iii\\app\\Http\\Middleware\\SecureHeaders.php(51): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#61 C:\\Users\\test\\firefly-iii\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): FireflyIII\\Http\\Middleware\\SecureHeaders->handle()
#62 C:\\Users\\test\\firefly-iii\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#63 C:\\Users\\test\\firefly-iii\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Kernel.php(140): Illuminate\\Pipeline\\Pipeline->then()
#64 C:\\Users\\test\\firefly-iii\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Kernel.php(109): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter()
#65 C:\\Users\\test\\firefly-iii\\public\\index.php(76): Illuminate\\Foundation\\Http\\Kernel->handle()
#66 C:\\Users\\test\\firefly-iii\\server.php(42): require_once('C:\\\\Users\\\\theef\\\\...')
#67 {main}
"} 
[2020-12-12 15:27:03] local.ERROR: Method FireflyIII\Http\Requests\EmailFormRequest::string does not exist. {"userId":2,"exception":"[object] (BadMethodCallException(code: 0): Method FireflyIII\\Http\\Requests\\EmailFormRequest::string does not exist. at C:\\Users\\test\\firefly-iii\\vendor\\laravel\\framework\\src\\Illuminate\\Support\\Traits\\Macroable.php:103)
[stacktrace]
#0 C:\\Users\\test\\firefly-iii\\app\\Http\\Controllers\\ProfileController.php(410): Illuminate\\Http\\Request->__call()
#1 [internal function]: FireflyIII\\Http\\Controllers\\ProfileController->postChangeEmail()
#2 C:\\Users\\test\\firefly-iii\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Controller.php(54): call_user_func_array()
#3 C:\\Users\\test\\firefly-iii\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\ControllerDispatcher.php(45): Illuminate\\Routing\\Controller->callAction()
#4 C:\\Users\\test\\firefly-iii\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Route.php(239): Illuminate\\Routing\\ControllerDispatcher->dispatch()
#5 C:\\Users\\test\\firefly-iii\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Route.php(196): Illuminate\\Routing\\Route->runController()
#6 C:\\Users\\test\\firefly-iii\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(685): Illuminate\\Routing\\Route->run()
#7 C:\\Users\\test\\firefly-iii\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(128): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}()
#8 C:\\Users\\test\\firefly-iii\\app\\Http\\Middleware\\IsDemoUser.php(66): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#9 C:\\Users\\test\\firefly-iii\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): FireflyIII\\Http\\Middleware\\IsDemoUser->handle()
#10 C:\\Users\\test\\firefly-iii\\app\\Http\\Controllers\\ProfileController.php(79): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#11 C:\\Users\\test\\firefly-iii\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(149): FireflyIII\\Http\\Controllers\\ProfileController::FireflyIII\\Http\\Controllers\\{closure}()
#12 C:\\Users\\test\\firefly-iii\\app\\Http\\Controllers\\Controller.php(108): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#13 C:\\Users\\test\\firefly-iii\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(149): FireflyIII\\Http\\Controllers\\Controller->FireflyIII\\Http\\Controllers\\{closure}()
#14 C:\\Users\\test\\firefly-iii\\app\\Http\\Middleware\\InterestingMessage.php(58): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#15 C:\\Users\\test\\firefly-iii\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): FireflyIII\\Http\\Middleware\\InterestingMessage->handle()
#16 C:\\Users\\test\\firefly-iii\\app\\Http\\Middleware\\Binder.php(79): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#17 C:\\Users\\test\\firefly-iii\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): FireflyIII\\Http\\Middleware\\Binder->handle()
#18 C:\\Users\\test\\firefly-iii\\app\\Http\\Middleware\\Range.php(61): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#19 C:\\Users\\test\\firefly-iii\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): FireflyIII\\Http\\Middleware\\Range->handle()
#20 C:\\Users\\test\\firefly-iii\\vendor\\jc5\\google2fa-laravel\\src\\Middleware.php(29): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#21 C:\\Users\\test\\firefly-iii\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): PragmaRX\\Google2FALaravel\\Middleware->handle()
#22 C:\\Users\\test\\firefly-iii\\app\\Http\\Middleware\\Authenticate.php(74): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#23 C:\\Users\\test\\firefly-iii\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): FireflyIII\\Http\\Middleware\\Authenticate->handle()
#24 C:\\Users\\test\\firefly-iii\\vendor\\laravel\\passport\\src\\Http\\Middleware\\CreateFreshApiToken.php(50): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#25 C:\\Users\\test\\firefly-iii\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): Laravel\\Passport\\Http\\Middleware\\CreateFreshApiToken->handle()
#26 C:\\Users\\test\\firefly-iii\\vendor\\laravel\\framework\\src\\Illuminate\\Session\\Middleware\\AuthenticateSession.php(58): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#27 C:\\Users\\test\\firefly-iii\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): Illuminate\\Session\\Middleware\\AuthenticateSession->handle()
#28 C:\\Users\\test\\firefly-iii\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken.php(77): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#29 C:\\Users\\test\\firefly-iii\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle()
#30 C:\\Users\\test\\firefly-iii\\vendor\\laravel\\framework\\src\\Illuminate\\View\\Middleware\\ShareErrorsFromSession.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#31 C:\\Users\\test\\firefly-iii\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle()
#32 C:\\Users\\test\\firefly-iii\\vendor\\laravel\\framework\\src\\Illuminate\\Session\\Middleware\\StartSession.php(116): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#33 C:\\Users\\test\\firefly-iii\\vendor\\laravel\\framework\\src\\Illuminate\\Session\\Middleware\\StartSession.php(62): Illuminate\\Session\\Middleware\\StartSession->handleStatefulRequest()
#34 C:\\Users\\test\\firefly-iii\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): Illuminate\\Session\\Middleware\\StartSession->handle()
#35 C:\\Users\\test\\firefly-iii\\vendor\\laravel\\framework\\src\\Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#36 C:\\Users\\test\\firefly-iii\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle()
#37 C:\\Users\\test\\firefly-iii\\vendor\\laravel\\framework\\src\\Illuminate\\Cookie\\Middleware\\EncryptCookies.php(67): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#38 C:\\Users\\test\\firefly-iii\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle()
#39 C:\\Users\\test\\firefly-iii\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#40 C:\\Users\\test\\firefly-iii\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(687): Illuminate\\Pipeline\\Pipeline->then()
#41 C:\\Users\\test\\firefly-iii\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(662): Illuminate\\Routing\\Router->runRouteWithinStack()
#42 C:\\Users\\test\\firefly-iii\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(628): Illuminate\\Routing\\Router->runRoute()
#43 C:\\Users\\test\\firefly-iii\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(617): Illuminate\\Routing\\Router->dispatchToRoute()
#44 C:\\Users\\test\\firefly-iii\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Kernel.php(165): Illuminate\\Routing\\Router->dispatch()
#45 C:\\Users\\test\\firefly-iii\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(128): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}()
#46 C:\\Users\\test\\firefly-iii\\vendor\\barryvdh\\laravel-debugbar\\src\\Middleware\\InjectDebugbar.php(58): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#47 C:\\Users\\test\\firefly-iii\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): Barryvdh\\Debugbar\\Middleware\\InjectDebugbar->handle()
#48 C:\\Users\\test\\firefly-iii\\app\\Http\\Middleware\\InstallationId.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#49 C:\\Users\\test\\firefly-iii\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): FireflyIII\\Http\\Middleware\\InstallationId->handle()
#50 C:\\Users\\test\\firefly-iii\\vendor\\fideloper\\proxy\\src\\TrustProxies.php(57): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#51 C:\\Users\\test\\firefly-iii\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): Fideloper\\Proxy\\TrustProxies->handle()
#52 C:\\Users\\test\\firefly-iii\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#53 C:\\Users\\test\\firefly-iii\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#54 C:\\Users\\test\\firefly-iii\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#55 C:\\Users\\test\\firefly-iii\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#56 C:\\Users\\test\\firefly-iii\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#57 C:\\Users\\test\\firefly-iii\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle()
#58 C:\\Users\\test\\firefly-iii\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode.php(63): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#59 C:\\Users\\test\\firefly-iii\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode->handle()
#60 C:\\Users\\test\\firefly-iii\\app\\Http\\Middleware\\SecureHeaders.php(51): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#61 C:\\Users\\test\\firefly-iii\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): FireflyIII\\Http\\Middleware\\SecureHeaders->handle()
#62 C:\\Users\\test\\firefly-iii\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#63 C:\\Users\\test\\firefly-iii\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Kernel.php(140): Illuminate\\Pipeline\\Pipeline->then()
#64 C:\\Users\\test\\firefly-iii\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Kernel.php(109): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter()
#65 C:\\Users\\test\\firefly-iii\\public\\index.php(76): Illuminate\\Foundation\\Http\\Kernel->handle()
#66 C:\\Users\\test\\firefly-iii\\server.php(42): require_once('C:\\\\Users\\\\test\\\\...')
#67 {main}
"} 

```

**Comment by JC5** [comment]
That's a bug for sure, I've seem similar issues. Thanks, will pick it up :+1:

**Comment by JC5** [comment]
Should be fixed in the new release.

**Comment by JC5** [comment]
Fixed in the latest beta, I'm closing this for consistency's sake.
