### ISSUE TITLE
404 even after compleate wipe

### ISSUE THREAD

**Issue by Chaoschaot232** [firefly-iii/firefly-iii#4237]
I am running Firefly III version 5.x.x

**Description**
It is the same problem like stated in #4156

I tried it a few times and only the DB is created smoothly and I can not find any errors or problems within the log or what I don't have provided in the mentioned questions/issues already.

I also tried the steps which where described in #4156 at the very end but it didn't helped me (still no user set but log tells "starting as root withn group root") so smth. seems to go horribly wrong but what goes wrong here?

Would be nice to get help at this point and like requested I opend this as a new ticket ;)

**Extra info**
My hole configuration was already posted in #4216

**Comment by JC5** [comment]
1. What's the container's content of `/var/www/html`?
2. Did you build the container yourself or grabbed it from Dockerhub?

**Comment by Chaoschaot232** [comment]
> 1. What's the container's content of `/var/www/html`?

It is an empty directory, having only the folders storage/uploads in it. So there is no data/files from the software itself even if the database was created and I don't know why.

> 2. Did you build the container yourself or grabbed it from Dockerhub?

Like stated in the link problems the image is from Dockerhub. I only edited the .env's to my needs and created the compose file from that what was in the gitlab repro linked as template.

The first start ended up in a HTTP 500 because I seted the loadbalancer port to 80 instead to 8080 but after this I only get this 404.

I am not sure where the main files should be, but I found nothing related to them and I searched in every accessable folder for them.

**Comment by JC5** [comment]
Everything should be in /var/www/html. 

I will double check the image on Docker Hub but frankly if it was broken I would have 100 tickets to deal with, not just 1. 

Is anything mounted to /var/www/html

**Comment by JC5** [comment]
If you have access to the docker engine on your host, the following command could be interesting:

```
docker create --name="tempff" jc5x/firefly-iii:latest && docker export tempff > image-fs.tar && docker rm tempff
```

It will create a Firefly III image and export the entire filesystem into a TAR file. When I do this with either develop or latest, the `/var/www/html` directory contains the Firefly III installation.

**Comment by Chaoschaot232** [comment]
I'll run you cmd just right now but for now I have this as my logfile:

```
Now in entrypoint.sh for Firefly III,
Entrypoint script version is 1.0.12 (2020-12-16),
Running as 'root' in group 'root'.,
Current working dir is '/var/www/html',
Now parsing _FILE variables.,
done!,
Dump auto load...,
Discover packages...,
Current working dir is '/var/www/html',
Wait for the database.,
wait-for-it.sh: waiting 60 seconds for fireflydb:3306,
wait-for-it.sh: fireflydb:3306 is available after 14 seconds,
DB is up. Time to execute artisan commands.,
Current working dir is '/var/www/html',
Run various artisan commands...,
Running migration commands...,
Could not open input file: artisan,
Could not open input file: artisan,
Could not open input file: artisan,
Current working dir is '/var/www/html',
Running upgrade commands...,
Could not open input file: artisan,
Could not open input file: artisan,
Could not open input file: artisan,
Could not open input file: artisan,
Could not open input file: artisan,
Could not open input file: artisan,
Could not open input file: artisan,
Could not open input file: artisan,
Could not open input file: artisan,
Could not open input file: artisan,
Could not open input file: artisan,
Could not open input file: artisan,
Could not open input file: artisan,
Running verification commands...,
Could not open input file: artisan,
Could not open input file: artisan,
Could not open input file: artisan,
Could not open input file: artisan,
Could not open input file: artisan,
Could not open input file: artisan,
Could not open input file: artisan,
Could not open input file: artisan,
Could not open input file: artisan,
Could not open input file: artisan,
Could not open input file: artisan,
Could not open input file: artisan,
Could not open input file: artisan,
Could not open input file: artisan,
Could not open input file: artisan,
Could not open input file: artisan,
nning report commands...,
Could not open input file: artisan,
Could not open input file: artisan,
Could not open input file: artisan,
Generating new OAuth keys...,
Could not open input file: artisan,
Could not open input file: artisan,
Could not open input file: artisan,
Go!,
AH00112: Warning: DocumentRoot [/var/www/html/public] does not exist,
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.26.0.3. Set the 'ServerName' directive globally to suppress this message,
AH00112: Warning: DocumentRoot [/var/www/html/public] does not exist,
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.26.0.3. Set the 'ServerName' directive globally to suppress this message,
[Sat Jan 09 16:53:00.021822 2021] [mpm_prefork:notice] [pid 1] AH00163: Apache/2.4.38 (Debian) configured -- resuming normal operations,
[Sat Jan 09 16:53:00.021856 2021] [core:notice] [pid 1] AH00094: Command line: 'apache2 -D FOREGROUND',
```
It tells me, that it has no "public" folder in it's dir which is interesting.

**Comment by Chaoschaot232** [comment]
> If you have access to the docker engine on your host, the following command could be interesting:
> 
> ```
> docker create --name="tempff" jc5x/firefly-iii:latest && docker export tempff > image-fs.tar && docker rm tempff
> ```
> 
> It will create a Firefly III image and export the entire filesystem into a TAR file. When I do this with either develop or latest, the `/var/www/html` directory contains the Firefly III installation.

Yes, the tar is arroung 661 MB in size and all files are there but in my container there is still nothing and I wonder why the files couldn't be copied/generated/... 
Log states that "root" is used so there shouldn't be any problem and I don't know what the cause for it could be 🤔

**Comment by JC5** [comment]
I must have missed that. If you mount a local directory to that source directory and the local directory is empty, the source will become empty. Not the other way around

**Comment by Chaoschaot232** [comment]
What do you mean by this?
I also mount the hole mariaDB installation and I have access to all the files in it.

**Comment by JC5** [comment]
https://docs.docker.com/storage/

**Comment by JC5** [comment]
And just to make this clear. If you mount `/your/local/dir` (a) to `/var/www/html` (b), the content of A will be put in the place of B. If A is empty, B will become empty. If the system (like mariaDB) starts storing files in B, they will be "copied" to A.

But if you map an empty directory to the place where the Firefly III code lives it's not gonna work.

**Comment by Chaoschaot232** [comment]
So this means at start up both folder from the DB are empty and are mounted, then the DB gets installed, created files so it works because B gets filled after it was created through A.

But for the Firefly installation I am overwriting the contents in /var/ww/html am I right? So the mount is my problem.
Is there a way to do a mount after the files where created so that I have full access to them?

Thanks for clarifiation :)

**Comment by JC5** [comment]
Sorry, no clue. But you could copy the files from the image, save them somewhere, and use that as the mount.

**Comment by Chaoschaot232** [comment]
Ok, I mounted now only the storage volume like you stated and here is the result with an 500 HTTP Error:

```#14 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(805): Illuminate\\Session\\SessionServiceProvider->Illuminate\\Session\\{closure}(),
#15 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(691): Illuminate\\Container\\Container->build(),
#16 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(796): Illuminate\\Container\\Container->resolve(),
#17 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(637): Illuminate\\Foundation\\Application->resolve(),
#18 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(781): Illuminate\\Container\\Container->make(),
#19 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(1280): Illuminate\\Foundation\\Application->make(),
#20 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/RoutingServiceProvider.php(118): Illuminate\\Container\\Container->offsetGet(),
#21 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(805): Illuminate\\Routing\\RoutingServiceProvider->Illuminate\\Routing\\{closure}(),
#22 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(691): Illuminate\\Container\\Container->build(),
#23 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(796): Illuminate\\Container\\Container->resolve(),
#24 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(637): Illuminate\\Foundation\\Application->resolve(),
#25 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(781): Illuminate\\Container\\Container->make(),
#26 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(1280): Illuminate\\Foundation\\Application->make(),
#27 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/RoutingServiceProvider.php(168): Illuminate\\Container\\Container->offsetGet(),
#28 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(805): Illuminate\\Routing\\RoutingServiceProvider->Illuminate\\Routing\\{closure}(),
#29 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(691): Illuminate\\Container\\Container->build(),
#30 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(796): Illuminate\\Container\\Container->resolve(),
#31 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(637): Illuminate\\Foundation\\Application->resolve(),
#32 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(781): Illuminate\\Container\\Container->make(),
#33 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php(119): Illuminate\\Foundation\\Application->make(),
#34 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php(683): app(),
#35 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(548): response(),
#36 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(456): Illuminate\\Foundation\\Exceptions\\Handler->renderHttpException(),
#37 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(336): Illuminate\\Foundation\\Exceptions\\Handler->prepareResponse(),
#38 /var/www/html/app/Exceptions/Handler.php(106): Illuminate\\Foundation\\Exceptions\\Handler->render(),
#39 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(51): FireflyIII\\Exceptions\\Handler->render(),
#40 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(172): Illuminate\\Routing\\Pipeline->handleException(),
#41 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(),
#42 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(141): Illuminate\\Pipeline\\Pipeline->then(),
#43 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(110): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(),
#44 /var/www/html/public/index.php(76): Illuminate\\Foundation\\Http\\Kernel->handle(),
#45 {main},
"} ,
[2021-01-10 07:40:31] local.ERROR: The only supported ciphers are AES-128-CBC and AES-256-CBC with the correct key lengths. {"exception":"[object] (RuntimeException(code: 0): The only supported ciphers are AES-128-CBC and AES-256-CBC with the correct key lengths. at /var/www/html/vendor/laravel/framework/src/Illuminate/Encryption/Encrypter.php:43),
[stacktrace],
[Sun Jan 10 07:40:31.438704 2021] [php7:error] [pid 363] [client 172.20.0.6:50358] PHP Fatal error:  Uncaught RuntimeException: The only supported ciphers are AES-128-CBC and AES-256-CBC with the correct key lengths. in /var/www/html/vendor/laravel/framework/src/Illuminate/Encryption/Encrypter.php:43\nStack trace:\n#0 /var/www/html/vendor/laravel/framework/src/Illuminate/Encryption/EncryptionServiceProvider.php(32): Illuminate\\Encryption\\Encrypter->__construct()\n#1 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(805): Illuminate\\Encryption\\EncryptionServiceProvider->Illuminate\\Encryption\\{closure}()\n#2 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(691): Illuminate\\Container\\Container->build()\n#3 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(796): Illuminate\\Container\\Container->resolve()\n#4 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(637): Illuminate\\Foundation\\Application->resolve()\n#5 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(781): Illuminat in /var/www/html/vendor/laravel/framework/src/Illuminate/Encryption/Encrypter.php on line 43,
#0 /var/www/html/vendor/laravel/framework/src/Illuminate/Encryption/EncryptionServiceProvider.php(32): Illuminate\\Encryption\\Encrypter->__construct(),
#1 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(805): Illuminate\\Encryption\\EncryptionServiceProvider->Illuminate\\Encryption\\{closure}(),
#2 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(691): Illuminate\\Container\\Container->build(),
#3 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(796): Illuminate\\Container\\Container->resolve(),
#4 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(637): Illuminate\\Foundation\\Application->resolve(),
#5 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(781): Illuminate\\Container\\Container->make(),
#6 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(1280): Illuminate\\Foundation\\Application->make(),
#7 /var/www/html/vendor/laravel/framework/src/Illuminate/Session/SessionManager.php(201): Illuminate\\Container\\Container->offsetGet(),
#8 /var/www/html/vendor/laravel/framework/src/Illuminate/Session/SessionManager.php(188): Illuminate\\Session\\SessionManager->buildEncryptedSession(),
#9 /var/www/html/vendor/laravel/framework/src/Illuminate/Session/SessionManager.php(74): Illuminate\\Session\\SessionManager->buildSession(),
#10 /var/www/html/vendor/laravel/framework/src/Illuminate/Session/SessionManager.php(61): Illuminate\\Session\\SessionManager->createNativeDriver(),
#11 /var/www/html/vendor/laravel/framework/src/Illuminate/Support/Manager.php(105): Illuminate\\Session\\SessionManager->createFileDriver(),
#12 /var/www/html/vendor/laravel/framework/src/Illuminate/Support/Manager.php(80): Illuminate\\Support\\Manager->createDriver(),
#13 /var/www/html/vendor/laravel/framework/src/Illuminate/Session/SessionServiceProvider.php(52): Illuminate\\Support\\Manager->driver(),
#14 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(805): Illuminate\\Session\\SessionServiceProvider->Illuminate\\Session\\{closure}(),
#15 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(691): Illuminate\\Container\\Container->build(),
#16 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(796): Illuminate\\Container\\Container->resolve(),
#17 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(637): Illuminate\\Foundation\\Application->resolve(),
#18 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(781): Illuminate\\Container\\Container->make(),
#19 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(1280): Illuminate\\Foundation\\Application->make(),
#20 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/RoutingServiceProvider.php(118): Illuminate\\Container\\Container->offsetGet(),
#21 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(805): Illuminate\\Routing\\RoutingServiceProvider->Illuminate\\Routing\\{closure}(),
#22 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(691): Illuminate\\Container\\Container->build(),
#23 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(796): Illuminate\\Container\\Container->resolve(),
#24 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(637): Illuminate\\Foundation\\Application->resolve(),
#25 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(781): Illuminate\\Container\\Container->make(),
#26 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(1280): Illuminate\\Foundation\\Application->make(),
#27 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/RoutingServiceProvider.php(168): Illuminate\\Container\\Container->offsetGet(),
#28 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(805): Illuminate\\Routing\\RoutingServiceProvider->Illuminate\\Routing\\{closure}(),
#29 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(691): Illuminate\\Container\\Container->build(),
#30 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(796): Illuminate\\Container\\Container->resolve(),
#31 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(637): Illuminate\\Foundation\\Application->resolve(),
#32 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(781): Illuminate\\Container\\Container->make(),
#33 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php(119): Illuminate\\Foundation\\Application->make(),
#34 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php(683): app(),
#35 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(548): response(),
#36 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(456): Illuminate\\Foundation\\Exceptions\\Handler->renderHttpException(),
#37 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(336): Illuminate\\Foundation\\Exceptions\\Handler->prepareResponse(),
#38 /var/www/html/app/Exceptions/Handler.php(106): Illuminate\\Foundation\\Exceptions\\Handler->render(),
#39 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(416): FireflyIII\\Exceptions\\Handler->render(),
#40 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(114): Illuminate\\Foundation\\Http\\Kernel->renderException(),
#41 /var/www/html/public/index.php(76): Illuminate\\Foundation\\Http\\Kernel->handle(),
#42 {main},
"} ,
[2021-01-10 07:40:31] local.ERROR: Uncaught RuntimeException: The only supported ciphers are AES-128-CBC and AES-256-CBC with the correct key lengths. in /var/www/html/vendor/laravel/framework/src/Illuminate/Encryption/Encrypter.php:43,
Stack trace:,
#0 /var/www/html/vendor/laravel/framework/src/Illuminate/Encryption/EncryptionServiceProvider.php(32): Illuminate\Encryption\Encrypter->__construct(),
#1 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(805): Illuminate\Encryption\EncryptionServiceProvider->Illuminate\Encryption\{closure}(),
#2 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(691): Illuminate\Container\Container->build(),
#3 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(796): Illuminate\Container\Container->resolve(),
#4 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(637): Illuminate\Foundation\Application->resolve(),
#5 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(781): Illuminat {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Uncaught RuntimeException: The only supported ciphers are AES-128-CBC and AES-256-CBC with the correct key lengths. in /var/www/html/vendor/laravel/framework/src/Illuminate/Encryption/Encrypter.php:43,
Stack trace:,
#0 /var/www/html/vendor/laravel/framework/src/Illuminate/Encryption/EncryptionServiceProvider.php(32): Illuminate\\Encryption\\Encrypter->__construct(),
#1 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(805): Illuminate\\Encryption\\EncryptionServiceProvider->Illuminate\\Encryption\\{closure}(),
#2 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(691): Illuminate\\Container\\Container->build(),
#3 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(796): Illuminate\\Container\\Container->resolve(),
#4 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(637): Illuminate\\Foundation\\Application->resolve(),
#5 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(781): Illuminat at /var/www/html/vendor/laravel/framework/src/Illuminate/Encryption/Encrypter.php:43),
[stacktrace],,
},
"} ,
[Sun Jan 10 07:40:31.439126 2021] [php7:error] [pid 363] [client 172.20.0.6:50358] PHP Fatal error:  Uncaught RuntimeException: The only supported ciphers are AES-128-CBC and AES-256-CBC with the correct key lengths. in /var/www/html/vendor/laravel/framework/src/Illuminate/Encryption/Encrypter.php:43\nStack trace:\n#0 /var/www/html/vendor/laravel/framework/src/Illuminate/Encryption/EncryptionServiceProvider.php(32): Illuminate\\Encryption\\Encrypter->__construct()\n#1 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(805): Illuminate\\Encryption\\EncryptionServiceProvider->Illuminate\\Encryption\\{closure}()\n#2 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(691): Illuminate\\Container\\Container->build()\n#3 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(796): Illuminate\\Container\\Container->resolve()\n#4 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(637): Illuminate\\Foundation\\Application->resolve()\n#5 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(781): Illuminat in /var/www/html/vendor/laravel/framework/src/Illuminate/Encryption/Encrypter.php on line 43,
172.20.0.6 - - [10/Jan/2021:07:40:31 +0100] "GET / HTTP/1.1" 500 169 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.141 Safari/537.36",```

**Comment by Chaoschaot232** [comment]
It complains about used Cipheres and I don't know what the problem here

**Comment by Chaoschaot232** [comment]
Do you use an internal Let's Encrypt or similar for HTTPS? If so, it must be disabled due to our proxy is doing this for us.

**Comment by JC5** [comment]
I don't use internal let's encrypt.

**Comment by Chaoschaot232** [comment]
So what is causing then this encryption/decryption problem? My generated app key over `openssl rand -base64 32`?

**Comment by JC5** [comment]
I don't know. You're pretty much hacking your way into Narnia here so you're on your own.

**Comment by Chaoschaot232** [comment]
Well, does the App Key accepts special chars or only alpha-numeric ones? Maybe this is the problem? Will test it out.

**Comment by Chaoschaot232** [comment]
Ok, it is the APP_KEY which is the problem so I try to fix this.

**Comment by Chaoschaot232** [comment]
It is working now but how can I change the max. pasword length? Maybe in the conf file 🤔
