### ISSUE TITLE
Setting up Firefly III and CSV importer via reverse-proxy

### ISSUE THREAD

**Issue by evanre** [firefly-iii/firefly-iii#4275]
I am running Firefly III version 5.4.6, CSV import version 2.3.3

**Description**
Hello there, thanks for the great app! I really spent a lot of time to make it work properly. You is my last hope =) The problem is that I can't make Firefly III and CSV importer work together via reverse proxy (nginx).  Firefly III itself works just fine on the link `https://money.mysite.com`, but when it comes to CSV importer (on the `https://money-import.mysite.com`) is not working properly, I've set up the public OAuth client ID 13 and `https://money-import.mysite.com/callback`. CSV importer's link opens, redirects to main site and it asks for authorisation, but after approving I'm getting the 502 error from nginx.

Please, consider my configs, I'd really appreciate your help with fixing this. Thanks. All the information listed below:

**docker-compose:***
```
# .......linuxserver.io's swag reverse proxy and many other apps
  firefly:
    image: jc5x/firefly-iii
    container_name: firefly
    environment:
      - APP_ENV=local
      - APP_KEY=F8EQv8*************CjJNioj
      - TRUSTED_PROXIES=**
      - DB_CONNECTION=mysql
      - DB_HOST=mariadb
      - DB_PORT=3306
      - DB_DATABASE=firefly
      - DB_USERNAME=*****
      - DB_PASSWORD=bt************kFa
      - TZ=America/New_York
    volumes:
      - ./firefly:/var/www/html/storage/upload
    restart: unless-stopped

  fireimp:
    image: fireflyiii/csv-importer
    container_name: fireimp
    environment:
      - FIREFLY_III_URL=http://firefly:8080
      - FIREFLY_III_CLIENT_ID=13
      - VANITY_URL=https://money.mysite.com
      - TRUSTED_PROXIES=**
      - TZ=America/New_York
    restart: unless-stopped
```

**nginx config:**
```
server {
    listen 443 ssl;
    listen [::]:443 ssl;

    server_name money.*;

    include /config/nginx/ssl.conf;

    client_max_body_size 0;
    location / {
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $host;

        proxy_set_header X-Forwarded-Server $host;
        proxy_set_header X-Forwarded-Proto $scheme;

        resolver 127.0.0.11 valid=30s;
        set $upstream_app firefly;
        set $upstream_port 8080;
        set $upstream_proto http;
        proxy_pass $upstream_proto://$upstream_app:$upstream_port;
    }
}
server {
    listen 443 ssl;
    listen [::]:443 ssl;

    server_name money-import.*;

    include /config/nginx/ssl.conf;

    client_max_body_size 0;
    location / {
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $host;

        proxy_set_header X-Forwarded-Server $host;
        proxy_set_header X-Forwarded-Proto $scheme;

        resolver 127.0.0.11 valid=30s;
        set $upstream_app fireimp;
        set $upstream_port 8080;
        set $upstream_proto http;
        proxy_pass $upstream_proto://$upstream_app:$upstream_port;
    }
}
```

**Extra info**
Debug information generated at 2021-01-16 19:20:21 America/New_York for Firefly III version **5.4.6**.

| Scope | Version |
| --- | --- |
| Firefly III | 5.4.6 |
| Firefly III API | 1.4.0 |
| PHP | 7.4.13 |
| Host | Linux |

| System info | Value |
| --- | --- |
| Installation ID | 52f6270c-*************-608e1b1848f7 |
| Using docker? | true |
| Telemetry | false |
| Layout |  |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | info, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Interface | apache2handler |
| Default language | en_US |
| Default locale | equal |
| BCscale | 12 |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | mysql |
| DB version | 15 (exp. 15) |
| Login provider | eloquent  |
| Trusted proxies (.env) | ** |

| User info | Value |
| --- | --- |
| Session start | 2021-01-01 00:00:00 |
| Session end | 2021-01-31 23:59:59 |
| Session first | 2021-01-13 15:27:03 |
| User ID | 1 |
| User language | ru_RU |
| User locale | ru_RU |
| Attempt at "ru_RU.utf8" | 'ru_RU.utf8' |
| Attempt at "ru_RU.UTF-8" | 'ru_RU.UTF-8' |
| User agent | Mozilla/5.0 (Macintosh; Intel Mac OS X 11_1_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.107 Safari/537.36 |

**Firely's debug log**
```
Truncated from this point <----|Kernel.php(110): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter()
#55 /var/www/html/public/index.php(76): Illuminate\Foundation\Http\Kernel->handle()
#56 {main}  
[2021-01-16 19:16:41] local.ERROR: Connection could not be established with host  :stream_socket_client(): php_network_getaddresses: getaddrinfo failed: Name or service not known  
[2021-01-16 19:16:41] local.ERROR: #0 [internal function]: Swift_Transport_StreamBuffer->{closure}()
#1 /var/www/html/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/StreamBuffer.php(272): stream_socket_client()
#2 /var/www/html/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/StreamBuffer.php(58): Swift_Transport_StreamBuffer->establishSocketConnection()
#3 /var/www/html/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php(143): Swift_Transport_StreamBuffer->initialize()
#4 /var/www/html/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mailer.php(65): Swift_Transport_AbstractSmtpTransport->start()
#5 /var/www/html/vendor/laravel/framework/src/Illuminate/Mail/Mailer.php(521): Swift_Mailer->send()
#6 /var/www/html/vendor/laravel/framework/src/Illuminate/Mail/Mailer.php(288): Illuminate\Mail\Mailer->sendSwiftMessage()
#7 /var/www/html/vendor/laravel/framework/src/Illuminate/Mail/Mailable.php(177): Illuminate\Mail\Mailer->send()
#8 /var/www/html/vendor/laravel/framework/src/Illuminate/Support/Traits/Localizable.php(19): Illuminate\Mail\Mailable->Illuminate\Mail\{closure}()
#9 /var/www/html/vendor/laravel/framework/src/Illuminate/Mail/Mailable.php(178): Illuminate\Mail\Mailable->withLocale()
#10 /var/www/html/vendor/laravel/framework/src/Illuminate/Mail/Mailer.php(304): Illuminate\Mail\Mailable->send()
#11 /var/www/html/vendor/laravel/framework/src/Illuminate/Mail/Mailer.php(258): Illuminate\Mail\Mailer->sendMailable()
#12 /var/www/html/vendor/laravel/framework/src/Illuminate/Mail/PendingMail.php(122): Illuminate\Mail\Mailer->send()
#13 /var/www/html/app/Handlers/Events/APIEventHandler.php(72): Illuminate\Mail\PendingMail->send()
#14 /var/www/html/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(411): FireflyIII\Handlers\Events\APIEventHandler->accessTokenCreated()
#15 /var/www/html/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(236): Illuminate\Events\Dispatcher->Illuminate\Events\{closure}()
#16 /var/www/html/vendor/laravel/passport/src/Bridge/AccessTokenRepository.php(71): Illuminate\Events\Dispatcher->dispatch()
#17 /var/www/html/vendor/league/oauth2-server/src/Grant/AbstractGrant.php(442): Laravel\Passport\Bridge\AccessTokenRepository->persistNewAccessToken()
#18 /var/www/html/vendor/league/oauth2-server/src/Grant/AuthCodeGrant.php(164): League\OAuth2\Server\Grant\AbstractGrant->issueAccessToken()
#19 /var/www/html/vendor/league/oauth2-server/src/AuthorizationServer.php(198): League\OAuth2\Server\Grant\AuthCodeGrant->respondToAccessTokenRequest()
#20 /var/www/html/vendor/laravel/passport/src/Http/Controllers/AccessTokenController.php(63): League\OAuth2\Server\AuthorizationServer->respondToAccessTokenRequest()
#21 /var/www/html/vendor/laravel/passport/src/Http/Controllers/HandlesOAuthErrors.php(24): Laravel\Passport\Http\Controllers\AccessTokenController->Laravel\Passport\Http\Controllers\{closure}()
#22 /var/www/html/vendor/laravel/passport/src/Http/Controllers/AccessTokenController.php(65): Laravel\Passport\Http\Controllers\AccessTokenController->withErrorHandling()
#23 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(48): Laravel\Passport\Http\Controllers\AccessTokenController->issueToken()
#24 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Route.php(255): Illuminate\Routing\ControllerDispatcher->dispatch()
#25 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Route.php(197): Illuminate\Routing\Route->runController()
#26 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(691): Illuminate\Routing\Route->run()
#27 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\Routing\Router->Illuminate\Routing\{closure}()
#28 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Middleware/ThrottleRequests.php(127): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#29 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Middleware/ThrottleRequests.php(63): Illuminate\Routing\Middleware\ThrottleRequests->handleRequest()
#30 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Routing\Middleware\ThrottleRequests->handle()
#31 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#32 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(693): Illuminate\Pipeline\Pipeline->then()
#33 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(668): Illuminate\Routing\Router->runRouteWithinStack()
#34 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(634): Illuminate\Routing\Router->runRoute()
#35 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(623): Illuminate\Routing\Router->dispatchToRoute()
#36 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(166): Illuminate\Routing\Router->dispatch()
#37 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}()
#38 /var/www/html/app/Http/Middleware/InstallationId.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#39 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): FireflyIII\Http\Middleware\InstallationId->handle()
#40 /var/www/html/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#41 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Fideloper\Proxy\TrustProxies->handle()
#42 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#43 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle()
#44 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#45 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle()
#46 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#47 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Foundation\Http\Middleware\ValidatePostSize->handle()
#48 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(87): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#49 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Foundation\Http\Middleware\PreventRequestsDuringMaintenance->handle()
#50 /var/www/html/app/Http/Middleware/SecureHeaders.php(51): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#51 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): FireflyIII\Http\Middleware\SecureHeaders->handle()
#52 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#53 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(141): Illuminate\Pipeline\Pipeline->then()
#54 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(110): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter()
#55 /var/www/html/public/index.php(76): Illuminate\Foundation\Http\Kernel->handle()
#56 {main}  
```
**Importer's debug log**
```
[16/Jan/2021:19:48:40 -0500] "GET /fa/webfonts/fa-regular-400.woff2 HTTP/1.0" 200 13820 "https://money-import.mysite.com/token" "Mozilla/5.0 (Macintosh; Intel Mac OS X 11_1_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.107 Safari/537.36"
2021-01-17T00:55:39.355164196Z [2021-01-16 19:55:39] production.DEBUG: Now at App\Http\Controllers\TokenController::index  
2021-01-17T00:55:39.357094728Z [2021-01-16 19:55:39] production.INFO: The following configuration information was found:  
2021-01-17T00:55:39.360938862Z [2021-01-16 19:55:39] production.INFO: Personal Access Token: "". (limited to 25 chars if present)  
2021-01-17T00:55:39.360964794Z [2021-01-16 19:55:39] production.INFO: Client ID            : "0".  
2021-01-17T00:55:39.360969195Z [2021-01-16 19:55:39] production.INFO: Base URL             : "http://firefly:8080".  
2021-01-17T00:55:39.360972477Z [2021-01-16 19:55:39] production.INFO: Token URL            : "http://firefly:8080".  
2021-01-17T00:55:39.369072891Z 172.22.0.6 - - [16/Jan/2021:19:55:39 -0500] "GET /token HTTP/1.0" 200 2514 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 11_1_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.107 Safari/537.36"
2021-01-17T00:55:47.591416512Z [2021-01-16 19:55:47] production.DEBUG: Now at App\Http\Controllers\TokenController::submitClientId  
2021-01-17T00:55:47.620359915Z [2021-01-16 19:55:47] production.DEBUG: Submitted data:  {"client_id":"13"} 
2021-01-17T00:55:47.625157856Z [2021-01-16 19:55:47] production.DEBUG: Now in App\Http\Controllers\TokenController::redirectForPermission(request, "https://money.mysite.com", "http://firefly:8080", 13)  
2021-01-17T00:55:47.626197719Z [2021-01-16 19:55:47] production.DEBUG: Query parameters are {"client_id":13,"redirect_uri":"https://money-import.mysite.com/callback","response_type":"code","scope":"","state":"FZVwh43Ou1QH1UmtkEMAEEmQq3ktFfWelJPxECzg","code_challenge":"SjBdq0EnhYD39gd3Q54YuGHs29U8rPliBkY8H6rHr_U","code_challenge_method":"S256"} 
2021-01-17T00:55:47.626803939Z [2021-01-16 19:55:47] production.DEBUG: Now redirecting to "https://money.mysite.com/oauth/authorize?" (params omitted)  
2021-01-17T00:55:47.628779248Z 172.22.0.6 - - [16/Jan/2021:19:55:47 -0500] "POST /token/client_id HTTP/1.0" 302 2827 "https://money-import.mysite.com/token" "Mozilla/5.0 (Macintosh; Intel Mac OS X 11_1_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.107 Safari/537.36"
2021-01-17T00:55:50.966159131Z [2021-01-16 19:55:50] production.DEBUG: Now at App\Http\Controllers\TokenController::callback  
2021-01-17T00:55:50.967296340Z [2021-01-16 19:55:50] production.DEBUG: State is valid!  
2021-01-17T00:55:50.967975372Z [2021-01-16 19:55:50] production.DEBUG: Params for access token {"form_params":{"grant_type":"authorization_code","client_id":13,"redirect_uri":"https://money-import.mysite.com/callback","code_verifier":"FdjVSx*truncated*zeahD5n","code":"def50*truncated*b1fe7"}} 
2021-01-17T00:55:50.968661118Z [2021-01-16 19:55:50] production.DEBUG: Will contact "http://firefly:8080/oauth/token" for a token.  
2021-01-17T00:55:51.470515942Z [2021-01-16 19:55:51] production.DEBUG: Response {"token_type":"Bearer","expires_in":1209600,"access_token":"eyJ*truncated*DA","refresh_token":"def502*truncated*6e0"} 
2021-01-17T00:55:51.471886151Z [2021-01-16 19:55:51] production.DEBUG: Return redirect with cookies to "https://money-import.mysite.com"  
2021-01-17T00:55:51.475360027Z 172.22.0.6 - - [16/Jan/2021:19:55:50 -0500] "GET /callback?code=def502*truncated*e7&state=FZVwh43Ou1QH1UmtkEMAEEmQq3ktFfWelJPxECzg HTTP/1.0" 302 5089 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 11_1_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.107 Safari/537.36"
```

**Comment by evanre** [comment]
Hello @JC5, can I ask you for help with this nginx settings? :)

**Comment by JC5** [comment]
I'm sorry, I'm really not good enough with these configs :(

**Comment by ragnarkarlsson** [comment]
Hi, I had the exact same issue just now after upgrading from 2.2.1 to 2.3.4 of the importer. Key difference, I am not running the docker instances but rather composer builds.

@evanre if you check your nginx error log, do you see lines like "upstream sent too big header while reading response header from upstream"?

For me I added the following to my primary location block

```
        fastcgi_buffers 16 32k;
        fastcgi_buffer_size 64k;
        fastcgi_busy_buffers_size 64k;
```

It may be you can use proxy_buffering / proxy_buffer_size to resolve your issue.
