### ISSUE TITLE
docker-compose up error: Could not poll the database: SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Temporary failure in name resolution 

### ISSUE THREAD

**Issue by cowpig** [firefly-iii/firefly-iii#4277]
Just tried to get firefly-iii working locally with `docker-compose`. I am on Ubuntu 20.04.1 LTS

Following the instructions [here](https://docs.firefly-iii.org/firefly-iii/installation/docker/) :

 * installed docker and docker-compose 
 * saved the [docker-compose file](https://raw.githubusercontent.com/firefly-iii/docker/main/docker-compose.yml) to a folder
 * saved the [env file](https://raw.githubusercontent.com/firefly-iii/firefly-iii/main/.env.example) to the same folder and renamed it `.env`
 * ran `docker-compose -f docker-compose.yml up -d` from inside that folder
 * waited for it to do its thing and navigated in my browser to `localhost`

I noticed a few closed issues with this error message, but they involved different installation procedures, and I figure I should file this separately since this kind of thing probably shouldn't be happening on a clean `docker-compose` install?

excerpt from log:

```
[previous exception] [object] (PDOException(code: 0): PDO::__construct(): php_network_getaddresses: getaddrinfo failed: Temporary failure in name resolution at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:38)
[stacktrace]
#0 /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php(38): PDO->__construct()
#1 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connectors/Connector.php(67): Doctrine\\DBAL\\Driver\\PDOConnection->__construct()
#2 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connectors/Connector.php(46): Illuminate\\Database\\Connectors\\Connector->createPdoConnection()
#3 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connectors/MySqlConnector.php(24): Illuminate\\Database\\Connectors\\Connector->createConnection()
#4 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connectors/ConnectionFactory.php(184): Illuminate\\Database\\Connectors\\MySqlConnector->connect()
#5 [internal function]: Illuminate\\Database\\Connectors\\ConnectionFactory->Illuminate\\Database\\Connectors\\{closure}()
#6 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php(926): call_user_func()
#7 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php(458): Illuminate\\Database\\Connection->getPdo()
#8 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php(664): Illuminate\\Database\\Connection->Illuminate\\Database\\{closure}()
#9 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php(631): Illuminate\\Database\\Connection->runQueryCallback()
#10 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php(465): Illuminate\\Database\\Connection->run()
#11 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php(417): Illuminate\\Database\\Connection->statement()
#12 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Query/Processors/Processor.php(32): Illuminate\\Database\\Connection->insert()
#13 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2872): Illuminate\\Database\\Query\\Processors\\Processor->processInsertGetId()
#14 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(1508): Illuminate\\Database\\Query\\Builder->insertGetId()
#15 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1051): Illuminate\\Database\\Eloquent\\Builder->__call()
#16 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1016): Illuminate\\Database\\Eloquent\\Model->insertAndSetId()
#17 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(857): Illuminate\\Database\\Eloquent\\Model->performInsert()
#18 /var/www/html/vendor/laravel/passport/src/ClientRepository.php(153): Illuminate\\Database\\Eloquent\\Model->save()
#19 /var/www/html/vendor/laravel/passport/src/ClientRepository.php(168): Laravel\\Passport\\ClientRepository->create()
#20 /var/www/html/vendor/laravel/passport/src/Console/ClientCommand.php(67): Laravel\\Passport\\ClientRepository->createPersonalAccessClient()
#21 /var/www/html/vendor/laravel/passport/src/Console/ClientCommand.php(43): Laravel\\Passport\\Console\\ClientCommand->createPersonalClient()
#22 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Laravel\\Passport\\Console\\ClientCommand->handle()
#23 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Util.php(40): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#24 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure()
#25 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\\Container\\BoundMethod::callBoundMethod()
#26 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(596): Illuminate\\Container\\BoundMethod::call()
#27 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(136): Illuminate\\Container\\Container->call()
#28 /var/www/html/vendor/symfony/console/Command/Command.php(258): Illuminate\\Console\\Command->execute()
#29 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(121): Symfony\\Component\\Console\\Command\\Command->run()
#30 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Concerns/CallsCommands.php(56): Illuminate\\Console\\Command->run()
#31 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Concerns/CallsCommands.php(28): Illuminate\\Console\\Command->runCommand()
#32 /var/www/html/vendor/laravel/passport/src/Console/InstallCommand.php(42): Illuminate\\Console\\Command->call()
#33 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Laravel\\Passport\\Console\\InstallCommand->handle()
#34 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Util.php(40): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#35 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure()
#36 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\\Container\\BoundMethod::callBoundMethod()
#37 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(596): Illuminate\\Container\\BoundMethod::call()
#38 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(136): Illuminate\\Container\\Container->call()
#39 /var/www/html/vendor/symfony/console/Command/Command.php(258): Illuminate\\Console\\Command->execute()
#40 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(121): Symfony\\Component\\Console\\Command\\Command->run()
#41 /var/www/html/vendor/symfony/console/Application.php(920): Illuminate\\Console\\Command->run()
#42 /var/www/html/vendor/symfony/console/Application.php(266): Symfony\\Component\\Console\\Application->doRunCommand()
#43 /var/www/html/vendor/symfony/console/Application.php(142): Symfony\\Component\\Console\\Application->doRun()
#44 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Application.php(93): Symfony\\Component\\Console\\Application->run()
#45 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(129): Illuminate\\Console\\Application->run()
#46 /var/www/html/artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle()
#47 {main}
"} 

In Connection.php line 671:
                                                                               
  SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Tempor  
  ary failure in name resolution (SQL: insert into `oauth_clients` (`user_id`  
  , `name`, `secret`, `provider`, `redirect`, `personal_access_client`, `pass  
  word_client`, `revoked`, `updated_at`, `created_at`) values (?, FireflyIII   
  Personal Access Client, ToPWY0tPvrSkJevYWHrD70Cku94IWP8iTSduPggn, ?, http:/  
  /localhost, 1, 0, 0, 2021-01-17 17:17:54, 2021-01-17 17:17:54))              
                                                                               

In Exception.php line 18:
                                                                               
  SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Tempor  
  ary failure in name resolution                                               
                                                                               

In PDOConnection.php line 38:
                                                                               
  SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Tempor  
  ary failure in name resolution                                               
                                                                               

In PDOConnection.php line 38:
                                                                               
  PDO::__construct(): php_network_getaddresses: getaddrinfo failed: Temporary  
   failure in name resolution                                                  
                                                                               

Updated version.
+------------------------------------------------------------------------------+
|                                                                              |
| Thank you for installing Firefly III, v5.4.6!                                |
|                                                                              |
|                                                                              |
+------------------------------------------------------------------------------+
Go!
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.19.0.3. Set the 'ServerName' directive globally to suppress this message
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.19.0.3. Set the 'ServerName' directive globally to suppress this message
[Sun Jan 17 17:17:55.648679 2021] [mpm_prefork:notice] [pid 1] AH00163: Apache/2.4.38 (Debian) configured -- resuming normal operations
[Sun Jan 17 17:17:55.648742 2021] [core:notice] [pid 1] AH00094: Command line: 'apache2 -D FOREGROUND'
[2021-01-17 17:18:52] local.ERROR: Exception is: {"class":"FireflyIII\\Exceptions\\FireflyException","errorMessage":"Could not poll the database: SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Temporary failure in name resolution (SQL: select `id`, `name`, `data` from `configuration` where `name` = is_demo_site and `configuration`.`deleted_at` is null limit 1)","time":"Sun, 17 Jan 2021 17:18:52 +0100","file":"\/var\/www\/html\/app\/Support\/FireflyConfig.php","line":90,"code":0,"version":"5.4.6","url":"http:\/\/0.0.0.0","userAgent":"Mozilla\/5.0 (X11; Ubuntu; Linux x86_64; rv:84.0) Gecko\/20100101 Firefox\/84.0","json":true}  
[2021-01-17 17:18:52] local.ERROR: Could not poll the database: SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Temporary failure in name resolution (SQL: select `id`, `name`, `data` from `configuration` where `name` = is_demo_site and `configuration`.`deleted_at` is null limit 1) {"exception":"[object] (FireflyIII\\Exceptions\\FireflyException(code: 0): Could not poll the database: SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Temporary failure in name resolution (SQL: select `id`, `name`, `data` from `configuration` where `name` = is_demo_site and `configuration`.`deleted_at` is null limit 1) at /var/www/html/app/Support/FireflyConfig.php:90)
[stacktrace]
#0 /var/www/html/app/Http/Controllers/Controller.php(58): FireflyIII\\Support\\FireflyConfig->get()
#1 /var/www/html/app/Http/Controllers/HomeController.php(55): FireflyIII\\Http\\Controllers\\Controller->__construct()
#2 [internal function]: FireflyIII\\Http\\Controllers\\HomeController->__construct()
#3 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(849): ReflectionClass->newInstanceArgs()
#4 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(691): Illuminate\\Container\\Container->build()
#5 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(796): Illuminate\\Container\\Container->resolve()
#6 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(637): Illuminate\\Foundation\\Application->resolve()
#7 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(781): Illuminate\\Container\\Container->make()
#8 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Route.php(269): Illuminate\\Foundation\\Application->make()
#9 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Route.php(990): Illuminate\\Routing\\Route->getController()
#10 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Route.php(951): Illuminate\\Routing\\Route->controllerMiddleware()
#11 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(708): Illuminate\\Routing\\Route->gatherMiddleware()
#12 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(684): Illuminate\\Routing\\Router->gatherRouteMiddleware()
#13 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(668): Illuminate\\Routing\\Router->runRouteWithinStack()
#14 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(634): Illuminate\\Routing\\Router->runRoute()
#15 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(623): Illuminate\\Routing\\Router->dispatchToRoute()
#16 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(166): Illuminate\\Routing\\Router->dispatch()
#17 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}()
#18 /var/www/html/app/Http/Middleware/InstallationId.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#19 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): FireflyIII\\Http\\Middleware\\InstallationId->handle()
#20 /var/www/html/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#21 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Fideloper\\Proxy\\TrustProxies->handle()
#22 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#23 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#24 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#25 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#26 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#27 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle()
#28 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(87): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#29 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance->handle()
#30 /var/www/html/app/Http/Middleware/SecureHeaders.php(51): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#31 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): FireflyIII\\Http\\Middleware\\SecureHeaders->handle()
#32 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#33 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(141): Illuminate\\Pipeline\\Pipeline->then()
#34 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(110): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter()
#35 /var/www/html/public/index.php(76): Illuminate\\Foundation\\Http\\Kernel->handle()
#36 {main}
"} 
172.19.0.1 - - [17/Jan/2021:17:18:52 +0100] "GET / HTTP/1.1" 500 4768 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:84.0) Gecko/20100101 Firefox/84.0"
172.19.0.1 - - [17/Jan/2021:17:18:52 +0100] "GET /v1/css/error.css?v= HTTP/1.1" 404 3676 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:84.0) Gecko/20100101 Firefox/84.0"
[2021-01-17 17:24:45] local.ERROR: Exception is: {"class":"FireflyIII\\Exceptions\\FireflyException","errorMessage":"Could not poll the database: SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Temporary failure in name resolution (SQL: select `id`, `name`, `data` from `configuration` where `name` = is_demo_site and `configuration`.`deleted_at` is null limit 1)","time":"Sun, 17 Jan 2021 17:24:45 +0100","file":"\/var\/www\/html\/app\/Support\/FireflyConfig.php","line":90,"code":0,"version":"5.4.6","url":"http:\/\/localhost","userAgent":"Mozilla\/5.0 (X11; Ubuntu; Linux x86_64; rv:84.0) Gecko\/20100101 Firefox\/84.0","json":true}  
[2021-01-17 17:24:45] local.ERROR: Could not poll the database: SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Temporary failure in name resolution (SQL: select `id`, `name`, `data` from `configuration` where `name` = is_demo_site and `configuration`.`deleted_at` is null limit 1) {"exception":"[object] (FireflyIII\\Exceptions\\FireflyException(code: 0): Could not poll the database: SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Temporary failure in name resolution (SQL: select `id`, `name`, `data` from `configuration` where `name` = is_demo_site and `configuration`.`deleted_at` is null limit 1) at /var/www/html/app/Support/FireflyConfig.php:90)
[stacktrace]
```

**Comment by JC5** [comment]
Unfortunately I have no focal VM ready to try this, but a local attempt (MacOS) works fine. Nothing has changed in either file since the release of this version, 3 weeks ago.

Could you share the start of the logs please? And what happens when you remove and retry?

**Comment by cowpig** [comment]
nice of you to reply so quickly!

here's the full log:
[fireflyiii.log](https://github.com/firefly-iii/firefly-iii/files/5826639/fireflyiii.log)

and after `docker-compose rm` and `docker-compose -f docker-compose.yml up -d` again (same problem occurs):
[fireflyiii-retry.log](https://github.com/firefly-iii/firefly-iii/files/5826641/fireflyiii-retry.log)

**Comment by JC5** [comment]
Thanks. No clue though, I'm afraid.

**Comment by JC5** [comment]
Looking into this, some solutions can be Googled. Did you try those already?
