### ISSUE TITLE
Argument 2 passed to FireflyIII\Support\Twig\AmountFormat::FireflyIII\Support\Twig\{closure}() must be of the type string, null given

### ISSUE THREAD

**Issue by momoKB** [firefly-iii/firefly-iii#4347]
**Bug description**
I am running Firefly III version 5.4.6, and my problem is:

Trying to run an overview of all incoming transactions resulting on URL
https://firefly.foo.bar/transactions/deposit/all

Running this gives error:

```
Error:
Argument 2 passed to FireflyIII\Support\Twig\AmountFormat::FireflyIII\Support\Twig\{closure}() must be of the type string, null given, called in /var/www/firefly-iii/storage/framework/views/twig/e8/e8808c356779383345189bb096369d854e4820720273ccaf9538e7432c381e67.php on line 429 

```
**Steps to reproduce**
Open Firefly
Go to "Transactions" > Revenue/Income
Click on Show everything 

**Extra info**
Debug information generated at 2021-02-05 11:28:56 Europe/Amsterdam for Firefly III version **5.4.6**.

| Scope | Version |
| --- | --- |
| Firefly III | 5.4.6 |
| Firefly III API | 1.4.0 |
| PHP | 7.4.3 |
| Host | Linux |

| System info | Value |
| --- | --- |
| Installation ID | 1d9ecbbf-6730-453d-b178-d36781614f7f |
| Using docker? | false |
| Telemetry | false |
| Layout | v1 |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | notice, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Interface | fpm-fcgi |
| Default language | en_US |
| Default locale | equal |
| BCscale | 12 |
| DB drivers | mysql |
| Current driver | mysql |
| DB version | 15 (exp. 15) |
| Login provider | eloquent  |
| Trusted proxies (.env) |  |

| User info | Value |
| --- | --- |
| Session start | 2021-02-01 00:00:00 |
| Session end | 2021-02-28 00:00:00 |
| Session first | 2021-01-01 00:00:00 |
| User ID | 1 |
| User language | nl_NL |
| User locale | nl_NL |
| Attempt at "nl_NL.utf8" | 'nl_NL.utf8' |
| Attempt at "nl_NL.UTF-8" | 'nl_NL.UTF-8' |
| User agent | Mozilla/5.0 (Windows NT 10.0; rv:78.0) Gecko/20100101 Firefox/78.0 |
-->
```
Truncated from this point <----|minate/Pipeline/Pipeline.php(149): FireflyIII\\Http\\Controllers\\Transaction\\IndexController->FireflyIII\\Http\\Controllers\\Transaction\\{closure}()
#27 /var/www/firefly-iii/app/Http/Controllers/Controller.php(115): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#28 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): FireflyIII\\Http\\Controllers\\Controller->FireflyIII\\Http\\Controllers\\{closure}()
#29 /var/www/firefly-iii/app/Http/Middleware/InterestingMessage.php(58): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#30 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): FireflyIII\\Http\\Middleware\\InterestingMessage->handle()
#31 /var/www/firefly-iii/app/Http/Middleware/Binder.php(79): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#32 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): FireflyIII\\Http\\Middleware\\Binder->handle()
#33 /var/www/firefly-iii/app/Http/Middleware/Range.php(61): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#34 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): FireflyIII\\Http\\Middleware\\Range->handle()
#35 /var/www/firefly-iii/vendor/jc5/google2fa-laravel/src/Middleware.php(29): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#36 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): PragmaRX\\Google2FALaravel\\Middleware->handle()
#37 /var/www/firefly-iii/app/Http/Middleware/Authenticate.php(74): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#38 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): FireflyIII\\Http\\Middleware\\Authenticate->handle()
#39 /var/www/firefly-iii/vendor/laravel/passport/src/Http/Middleware/CreateFreshApiToken.php(50): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#40 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Laravel\\Passport\\Http\\Middleware\\CreateFreshApiToken->handle()
#41 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Session/Middleware/AuthenticateSession.php(58): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#42 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Session\\Middleware\\AuthenticateSession->handle()
#43 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(77): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#44 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle()
#45 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#46 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle()
#47 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(121): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#48 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(63): Illuminate\\Session\\Middleware\\StartSession->handleStatefulRequest()
#49 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Session\\Middleware\\StartSession->handle()
#50 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#51 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle()
#52 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(67): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#53 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle()
#54 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#55 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Routing/Router.php(693): Illuminate\\Pipeline\\Pipeline->then()
#56 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Routing/Router.php(668): Illuminate\\Routing\\Router->runRouteWithinStack()
#57 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Routing/Router.php(634): Illuminate\\Routing\\Router->runRoute()
#58 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Routing/Router.php(623): Illuminate\\Routing\\Router->dispatchToRoute()
#59 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(166): Illuminate\\Routing\\Router->dispatch()
#60 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}()
#61 /var/www/firefly-iii/app/Http/Middleware/InstallationId.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#62 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): FireflyIII\\Http\\Middleware\\InstallationId->handle()
#63 /var/www/firefly-iii/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#64 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Fideloper\\Proxy\\TrustProxies->handle()
#65 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#66 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#67 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#68 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#69 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#70 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle()
#71 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(87): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#72 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance->handle()
#73 /var/www/firefly-iii/app/Http/Middleware/SecureHeaders.php(51): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#74 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): FireflyIII\\Http\\Middleware\\SecureHeaders->handle()
#75 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#76 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(141): Illuminate\\Pipeline\\Pipeline->then()
#77 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(110): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter()
#78 /var/www/firefly-iii/public/index.php(76): Illuminate\\Foundation\\Http\\Kernel->handle()
#79 {main}
"} 

```

**Bonus points**

- I searched and count not find this bug
- I was NOT able to replicate it on the demo site https://demo.firefly-iii.org/

**Comment by momoKB** [comment]
Additionally, this now happens when making a new income transaction. After the error when I return to the dashboard page the transaction IS made (green box tells me this).

**Comment by JC5** [comment]
What did you change in your currencies?

**Comment by momoKB** [comment]
I removed all non- euro currencies. Nothing else changed.

Also I'm the same guy you helped on tweakers with the issue   
regarding https://github.com/firefly-iii/firefly-iii/issues/4055

So perhaps that is of influence?

I just found out this only happens to new transactions that are posted in the past. If I make a transaction for today, or in the future, I do not get this error when trying to make a new transaction.

**Comment by JC5** [comment]
Ah thx for the pointer 😁 

Regarding the error, could you do me a favor?

> called in /var/www/firefly-iii/storage/framework/views/twig/e8/e8808c356779383345189bb096369d854e4820720273ccaf9538e7432c381e67.php on line 429 

If you do this:

`sed -n 420,430p /var/www/firefly-iii/storage/framework/views/twig/e8/e8808c356779383345189bb096369d854e4820720273ccaf9538e7432c381e67.php on line 429 `

You should see reference to lines (something like `<!-- line x -->` or `/* line x*/`

Let me know which lines so I can see in the original templates what's happening.

**Comment by momoKB** [comment]
`                <td style=\" ";
                // line 138
                echo ($context["style"] ?? null);
                echo "\">
                    ";
                // line 139
                if ((TwigBridge\Node\GetAttrNode::attribute($this->env, $this->source, $context["transaction"], "transaction_type_type", [], "any", false, false, false, 139) == "Deposit")) {
                    // line 140
                    echo "                        ";
                    echo call_user_func_array($this->env->getFunction('formatAmountBySymbol')->getCallable(), [(TwigBridge\Node\GetAttrNode::attribute($this->env, $this->source, $context["transaction"], "amount", [], "any", false, false, false, 140) *  -1), TwigBridge\Node\GetAttrNode::attribute($this->env, $this->source, $context["transaction"], "currency_symbol", [], "any", false, false, false, 140), TwigBridge\Node\GetAttrNode::attribute($this->env, $this->source, $context["transaction"], "currency_decimal_places", [], "any", false, false, false, 140)]);
                    echo "`

**Comment by JC5** [comment]
No that happens when people physically delete everything from the DB. Then act surprised it doesn't work.

I'll dive into the issue!

**Comment by JC5** [comment]
I'm having a hard time replicating this. Can you run some command line things for me, from the directory of Firefly III?

```
php artisan firefly-iii:correct-database
```

The output will contain plenty of private things so there's no need to share it. 

Also interesting. Can you narrow down the date range in this URL until you know which transaction(s) are the offending ones?

https://firefly.foo.bar/transactions/deposit/2021-01-01/2021-01-31

We can do some DB checking to see what's going on.

**Comment by momoKB** [comment]
`php artisan firefly-iii:correct-database`

That actually fixed the issue.

**Comment by JC5** [comment]
Alright well I’m glad to hear that apparently I have the gift of prescience and was able to fix this back last year. 😁
