### ISSUE TITLE
Crontab Error

### ISSUE THREAD

**Issue by Cryptec** [firefly-iii/firefly-iii#4407]
**Bug description**
From one Day to another, i can´t issue manually cronjobs for reccuring transactions in the firefly-iii foler.

**what happened:** 
root@Firefly-III:/var/www/firefly-iii# php artisan firefly:cron

The recurring transaction cron job did not fire.
The auto budget cron job did not fire.
More feedback on the cron jobs can be found in the log files.

here is the log: 

[2021-02-18 03:00:13] local.ERROR: Exception is: {"class":"ErrorException","errorMessage":"file_put_contents(\/var\/www\/firefly-iii\/storage\/framework\/cache\/data\/57\/6b\/576b7e9aa5dea67a25617c7fc324294d7>[2021-02-18 03:00:14] local.ERROR: file_put_contents(/var/www/firefly-iii/storage/framework/cache/data/57/6b/576b7e9aa5dea67a25617c7fc324294d7c1cb251): failed to open stream: Permission denied {"exception":"[>[stacktrace]

the above line from 03:00:13 is a view hours older then i did the manual php artisan
```
#0 [internal function]: Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError()
#1 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php(185): file_put_contents()
#2 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Cache/FileStore.php(74): Illuminate\\Filesystem\\Filesystem->put()
#3 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Cache/FileStore.php(152): Illuminate\\Cache\\FileStore->put()
#4 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Cache/Repository.php(355): Illuminate\\Cache\\FileStore->forever()
#5 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Cache/CacheManager.php(396): Illuminate\\Cache\\Repository->forever()
#6 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(261): Illuminate\\Cache\\CacheManager->__call()
#7 /var/www/firefly-iii/app/Support/FireflyConfig.php(94): Illuminate\\Support\\Facades\\Facade::__callStatic()
#8 /var/www/firefly-iii/app/Support/Cronjobs/AutoBudgetCronjob.php(45): FireflyIII\\Support\\FireflyConfig->get()
#9 /var/www/firefly-iii/app/Console/Commands/Tools/Cron.php(130): FireflyIII\\Support\\Cronjobs\\AutoBudgetCronjob->fire()
#10 /var/www/firefly-iii/app/Console/Commands/Tools/Cron.php(90): FireflyIII\\Console\\Commands\\Tools\\Cron->autoBudgetCronJob()
#11 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): FireflyIII\\Console\\Commands\\Tools\\Cron->handle()
#12 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Container/Util.php(40): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#13 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure()
#14 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\\Container\\BoundMethod::callBoundMethod()
#15 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Container/Container.php(596): Illuminate\\Container\\BoundMethod::call()
#16 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Console/Command.php(136): Illuminate\\Container\\Container->call()
#17 /var/www/firefly-iii/vendor/symfony/console/Command/Command.php(258): Illuminate\\Console\\Command->execute()
#18 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Console/Command.php(121): Symfony\\Component\\Console\\Command\\Command->run()
#19 /var/www/firefly-iii/vendor/symfony/console/Application.php(920): Illuminate\\Console\\Command->run()
#20 /var/www/firefly-iii/vendor/symfony/console/Application.php(266): Symfony\\Component\\Console\\Application->doRunCommand()
#21 /var/www/firefly-iii/vendor/symfony/console/Application.php(142): Symfony\\Component\\Console\\Application->doRun()
#22 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Console/Application.php(93): Symfony\\Component\\Console\\Application->run()
#23 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(129): Illuminate\\Console\\Application->run()
#24 /var/www/firefly-iii/artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle()
#25 {main}
"}```

**Comment by JC5** [comment]
- https://docs.firefly-iii.org/firefly-iii/faq/self_hosted/#unable-to-write-to-cache-directory
- https://docs.firefly-iii.org/firefly-iii/faq/docker/#i-get-permission-denied-errors-on-the-cache-folder
