### ISSUE TITLE
POST /api/v1/accounts LiabilityType capitalized in Response Model (loan --> Loan)

### ISSUE THREAD

**Issue by rummens** [firefly-iii/firefly-iii#4426]
**Bug description**
I am running Firefly III version 5.5.0-beta.1, and my problem is: Response Model of Accounts API puts liability_type as e.g. "loan" but API actually return "Loan" causing the response verification of the Swagger Client to fail. Using Python but should be the same on other platforms as well. 

Solution either adapt [OpenAPI](https://api-docs.firefly-iii.org/#/accounts/storeAccount) or fix Response from API to match documented model. 

**Steps to reproduce**
Create a new account with API, with account_type = liability and set any liability_type

**Extra info**
Debug information generated at 2021-02-23 21:16:55 Europe/Amsterdam for Firefly III version **5.5.0-beta.1**.

| Scope | Version |
| --- | --- |
| Firefly III | 5.5.0-beta.1 |
| Firefly III API | 1.5.0 |
| PHP | 7.4.14 |
| Host | Linux |

| System info | Value |
| --- | --- |
| Installation ID | a9ecd381-cbaa-4678-910b-cd127bb7b67d |
| Using docker? | true |
| Telemetry | false |
| Layout | v1 |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | notice, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Interface | apache2handler |
| Default language | en_US |
| Default locale | equal |
| BCscale | 12 |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | mysql |
| DB version | 15 (exp. 15) |
| Login provider | eloquent  |
| Trusted proxies (.env) |  |

| User info | Value |
| --- | --- |
| Session start | 2020-01-01 00:00:00 |
| Session end | 2021-02-23 00:00:00 |
| Session first | 2019-12-30 00:00:00 |
| User ID | 1 |
| User language | en_US |
| User locale | en_US |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| User agent | Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.3 Safari/605.1.15 |

-->

**Bonus points**
`Traceback (most recent call last):
  File "/Users/marcel/PycharmProjects/banking/main.py", line 39, in <module>
    from parse_banking_data import parse_bookings, combine_tranfers
  File "/Users/marcel/PycharmProjects/banking/parse_banking_data.py", line 5, in <module>
    from definitions import *
  File "/Users/marcel/PycharmProjects/banking/definitions.py", line 20, in <module>
    ing_tesla_credit = BankAccount(name="ING_Tesla_Kredit", account_type=AccountType.liability,
  File "/Users/marcel/PycharmProjects/banking/classes/BankAccount.py", line 56, in __init__
    self.__create_account()
  File "/Users/marcel/PycharmProjects/banking/classes/BankAccount.py", line 130, in __create_account
    account: AccountRead = BankAccount.api_instance.store_account(account_create).data
  File "/Users/marcel/PycharmProjects/banking/firefly_iii_client/api/accounts_api.py", line 789, in store_account
    return self.store_account_with_http_info(account, **kwargs)  # noqa: E501
  File "/Users/marcel/PycharmProjects/banking/firefly_iii_client/api/accounts_api.py", line 868, in store_account_with_http_info
    return self.api_client.call_api(
  File "/Users/marcel/PycharmProjects/banking/firefly_iii_client/api_client.py", line 365, in call_api
    return self.__call_api(resource_path, method,
  File "/Users/marcel/PycharmProjects/banking/firefly_iii_client/api_client.py", line 209, in __call_api
    return_data = self.deserialize(response_data, response_type)
  File "/Users/marcel/PycharmProjects/banking/firefly_iii_client/api_client.py", line 281, in deserialize
    return self.__deserialize(data, response_type)
  File "/Users/marcel/PycharmProjects/banking/firefly_iii_client/api_client.py", line 320, in __deserialize
    return self.__deserialize_model(data, klass)
  File "/Users/marcel/PycharmProjects/banking/firefly_iii_client/api_client.py", line 659, in __deserialize_model
    kwargs[attr] = self.__deserialize(value, attr_type)
  File "/Users/marcel/PycharmProjects/banking/firefly_iii_client/api_client.py", line 320, in __deserialize
    return self.__deserialize_model(data, klass)
  File "/Users/marcel/PycharmProjects/banking/firefly_iii_client/api_client.py", line 659, in __deserialize_model
    kwargs[attr] = self.__deserialize(value, attr_type)
  File "/Users/marcel/PycharmProjects/banking/firefly_iii_client/api_client.py", line 320, in __deserialize
    return self.__deserialize_model(data, klass)
  File "/Users/marcel/PycharmProjects/banking/firefly_iii_client/api_client.py", line 661, in __deserialize_model
    instance = klass(**kwargs)
  File "/Users/marcel/PycharmProjects/banking/firefly_iii_client/models/account.py", line 170, in __init__
    self.liability_type = liability_type
  File "/Users/marcel/PycharmProjects/banking/firefly_iii_client/models/account.py", line 625, in liability_type
    raise ValueError(
ValueError: Invalid value for `liability_type` (Loan), must be one of ['loan', 'debt', 'mortgage']`

**Comment by JC5** [comment]
Nice find, will be fixed in the next release.

**Comment by rummens** [comment]
Thanks, for everyone else in the meantime please find a workaround attached. It's not very clean but but does the job. Simply re-generate the client with this openapi and it should fix the problem temporarily...

[openapi.log](https://github.com/firefly-iii/firefly-iii/files/6033973/openapi.log)
