### ISSUE TITLE
Login via ldap not working on 5.5.1

### ISSUE THREAD

**Issue by vcrazyV** [firefly-iii/firefly-iii#4573]
Hi, i have a little issue after updating from version 5.4.6 to 5.5.1.  When i trying to open login or main page i get error (error.png). This behavior i see on my "prod" stand and docker-compose test stand. I dont know how fix this, can you help me? 

**Description**

Steps to reproduce:

1. configure app to login via ldap:
  ```
LOGIN_PROVIDER=ldap
ADLDAP_CONNECTION_SCHEME=OpenLDAP
ADLDAP_AUTO_CONNECT=true

ADLDAP_CONTROLLERS=host
ADLDAP_PORT=389
ADLDAP_TIMEOUT=5
ADLDAP_BASEDN="your_dn"
ADLDAP_FOLLOW_REFFERALS=false

  ```
2. install or update app to 5.5.1
3. open login page

**Extra info**

My test docker compose file
```
version: '3.3'

services:
  fireflyiii:
    image: jc5x/firefly-iii:latest
    volumes:
      - firefly_iii_upload:/var/www/html/storage/upload
    env_file: ./env_prod
    ports:
      - 9090:8080
    depends_on:
      - fireflyiiidb
  fireflyiiidb:
    image: postgres
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=test
    volumes:
      - firefly_iii_db:/var/lib/postgresql/data
volumes:
  firefly_iii_upload:
  firefly_iii_db:
```

file `env_prod` is default `env` file with configured ldap and db.

part of logs from test stand, when app is started
```
All meta fields are correct.
Renamed meta fields in 0.02 seconds
Going to verify 0 opening balance transactions.
There was nothing to fix in the opening balance transactions.
Verified all transaction group and journal title lengths.
Took 0.02 seconds.
[2021-03-31 22:34:28] local.ERROR: Authentication user provider [ldap] is not defined. {"exception":"[object] (InvalidArgumentException(code: 0): Authentication user provider [ldap] is not defined. at /var/www/html/vendor/laravel/framework/src/Illuminate/Auth/CreatesUserProviders.php:42)
[stacktrace]
#0 /var/www/html/vendor/laravel/framework/src/Illuminate/Auth/AuthManager.php(123): Illuminate\\Auth\\AuthManager->createUserProvider()
#1 /var/www/html/vendor/laravel/framework/src/Illuminate/Auth/AuthManager.php(94): Illuminate\\Auth\\AuthManager->createSessionDriver()
#2 /var/www/html/vendor/laravel/framework/src/Illuminate/Auth/AuthManager.php(68): Illuminate\\Auth\\AuthManager->resolve()
#3 /var/www/html/vendor/laravel/framework/src/Illuminate/Auth/AuthManager.php(307): Illuminate\\Auth\\AuthManager->guard()
#4 /var/www/html/app/Providers/RecurringServiceProvider.php(54): Illuminate\\Auth\\AuthManager->__call()
#5 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(829): FireflyIII\\Providers\\RecurringServiceProvider->FireflyIII\\Providers\\{closure}()
#6 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(714): Illuminate\\Container\\Container->build()
#7 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(841): Illuminate\\Container\\Container->resolve()
#8 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(652): Illuminate\\Foundation\\Application->resolve()
#9 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(826): Illuminate\\Container\\Container->make()
#10 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php(119): Illuminate\\Foundation\\Application->make()
#11 /var/www/html/app/Console/Commands/Correction/FixRecurringTransactions.php(82): app()
#12 /var/www/html/app/Console/Commands/Correction/FixRecurringTransactions.php(65): FireflyIII\\Console\\Commands\\Correction\\FixRecurringTransactions->stupidLaravel()
#13 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): FireflyIII\\Console\\Commands\\Correction\\FixRecurringTransactions->handle()
#14 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Util.php(40): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#15 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure()
#16 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\\Container\\BoundMethod::callBoundMethod()
#17 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(611): Illuminate\\Container\\BoundMethod::call()
#18 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(136): Illuminate\\Container\\Container->call()
#19 /var/www/html/vendor/symfony/console/Command/Command.php(256): Illuminate\\Console\\Command->execute()
#20 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(121): Symfony\\Component\\Console\\Command\\Command->run()
#21 /var/www/html/vendor/symfony/console/Application.php(971): Illuminate\\Console\\Command->run()
#22 /var/www/html/vendor/symfony/console/Application.php(290): Symfony\\Component\\Console\\Application->doRunCommand()
#23 /var/www/html/vendor/symfony/console/Application.php(166): Symfony\\Component\\Console\\Application->doRun()
#24 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Application.php(92): Symfony\\Component\\Console\\Application->run()
#25 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(129): Illuminate\\Console\\Application->run()
#26 /var/www/html/artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle()
#27 {main}
"} 

In CreatesUserProviders.php line 42:
                                                       
  Authentication user provider [ldap] is not defined.  
                                                       

Running report commands...
Report on empty objects finished in 0.04 seconds
Report on total sum finished in 0.02 seconds
Restored OAuth keys from database.
Generating new OAuth keys...
Encryption keys already exist. Use the --force option to overwrite them.
Personal access client created successfully.
Client ID: 7
Client secret: HmxVkUg1uBKtokTQrxpOzeyBzFzKq1mgbC77rDib
Password grant client created successfully.
Client ID: 8
Client secret: l4zQtg73rS7tITpQKb1blPnWsqgh3eTLHkGrLMCI
Updated version.
+------------------------------------------------------------------------------+
|                                                                              |
| Thank you for installing Firefly III, v5.5.1!                                |
|                                                                              |
|                                                                              |
+------------------------------------------------------------------------------+
Go!
```
[full.log](https://github.com/firefly-iii/firefly-iii/files/6239039/full.log)

![error](https://user-images.githubusercontent.com/1951212/113201434-26370880-9272-11eb-881d-f4c0a51d2a13.png)

**Comment by JC5** [comment]
https://github.com/firefly-iii/firefly-iii/issues/4557
