### ISSUE TITLE
Error 500 in /bills

### ISSUE THREAD

**Issue by sephrat** [firefly-iii/firefly-iii#4586]
**Bug description**
I am running Firefly III version 5.5.2 and my problem is:
https://demo.firefly-iii.org/bills return an error 500.

```
fireflyiii | [2021-04-03 11:04:35] local.ERROR: Trailing data {"userId":1,"exception":"[object] (Carbon\\Exceptions\\InvalidFormatException(code: 0): Traili                                                             ng data at /var/www/html/vendor/nesbot/carbon/src/Carbon/Traits/Creator.php:643)
fireflyiii | [stacktrace]
fireflyiii | #0 /var/www/html/vendor/nesbot/carbon/src/Carbon/Traits/Creator.php(665): Carbon\\Carbon::rawCreateFromFormat()
fireflyiii | #1 /var/www/html/app/Http/Controllers/Bill/IndexController.php(119): Carbon\\Carbon::createFromFormat()

```

Also, I thought an error 500 would send an automatic notification with the stacktrace? I did not receive any although the test email works fine.

**Comment by JC5** [comment]
That's a sloppy one :(. 5.5.3 tonight.

I'll check out the mesage too.
