### ISSUE TITLE
Pl locales Unable to choose a translation

### ISSUE THREAD

**Issue by machond** [firefly-iii/firefly-iii#4724]
When running cron for reccuring i reciving such error. I am using PL locales.

```
[2021-04-29 17:01:23] local.ERROR: Exception is: {"class":"Symfony\\Component\\Translation\\Exception\\InvalidArgumentException","errorMessage":"Unable to choose a translation for \":count r|:count l\" with locale \"pl_PL\" for value \"51\". Double check that this translation has the correct plural options (e.g. \"There is one apple|There are %count% apples\").","time":"Thu, 29 Apr 2021 17:01:23 +0200","file":"\/var\/www\/html\/vendor\/symfony\/translation-contracts\/TranslatorTrait.php","line":125,"code":0,"version":"5.5.9","url":"https:\/\/bilans.machon.net","userAgent":"Symfony","json":true}  
[2021-04-29 17:01:23] local.ERROR: Exception when mailing: Connection could not be established with host  :stream_socket_client(): php_network_getaddresses: getaddrinfo failed: Name or service not known  
[2021-04-29 17:01:23] local.ERROR: Unable to choose a translation for ":count r|:count l" with locale "pl_PL" for value "51". Double check that this translation has the correct plural options (e.g. "There is one apple|There are %count% apples"). {"exception":"[object] (Symfony\\Component\\Translation\\Exception\\InvalidArgumentException(code: 0): Unable to choose a translation for \":count r|:count l\" with locale \"pl_PL\" for value \"51\". Double check that this translation has the correct plural options (e.g. \"There is one apple|There are %count% apples\"). at /var/www/html/vendor/symfony/translation-contracts/TranslatorTrait.php:125
```

**Comment by JC5** [comment]
Which Firefly III version?

**Comment by tomasz-lasko** [comment]
Hello I have the same issue when running cron:

5.5.12Firefly III on Ubuntu 20.04 LTS with this command:
apt install language-pack-pl-base && locale-gen

Here is an output (I removed the URL)

`php artisan firefly-iii:cron
[2021-08-02 14:20:03] local.ERROR: Exception is: {"class":"Symfony\\Component\\Translation\\Exception\\InvalidArgumentException","errorMessage":"Unable to choose a translation for \":count r|:count l\" with locale \"pl_PL\" for value \"51\". Double check that this translation has the correct plural options (e.g. \"There is one apple|There are %count% apples\").","time":"Mon, 02 Aug 2021 14:20:03 +0200","file":"/firefly-iii\/vendor\/symfony\/translation-contracts\/TranslatorTrait.php","line":125,"code":0,"version":"5.5.12","url":"https:\/\/......","userAgent":"Symfony","json":true}
[2021-08-02 14:20:04] local.ERROR: Unable to choose a translation for ":count r|:count l" with locale "pl_PL" for value "51". Double check that this translation has the correct plural options (e.g. "There is one apple|There are %count% apples"). {"exception":"[object] (Symfony\\Component\\Translation\\Exception\\InvalidArgumentException(code: 0): Unable to choose a translation for \":count r|:count l\" with locale \"pl_PL\" for value \"51\". Double check that this translation has the correct plural options (e.g. \"There is one apple|There are %count% apples\"). at /firefly-iii/vendor/symfony/translation-contracts/TranslatorTrait.php:125)
[stacktrace]
#0 /firefly-iii/vendor/symfony/translation/Formatter/MessageFormatter.php(43): Symfony\\Component\\Translation\\IdentityTranslator->trans()
#1 /firefly-iii/vendor/symfony/translation/Translator.php(225): Symfony\\Component\\Translation\\Formatter\\MessageFormatter->format()
#2 /firefly-iii/vendor/nesbot/carbon/src/Carbon/Translator.php(172): Symfony\\Component\\Translation\\Translator->trans()
#3 /firefly-iii/vendor/nesbot/carbon/src/Carbon/Traits/Localization.php(230): Carbon\\Translator->trans()
#4 /firefly-iii/vendor/nesbot/carbon/src/Carbon/Traits/Localization.php(249): Carbon\\CarbonInterval::translateWith()
#5 /firefly-iii/vendor/nesbot/carbon/src/Carbon/CarbonInterval.php(1576): Carbon\\CarbonInterval->translate()
#6 /firefly-iii/vendor/nesbot/carbon/src/Carbon/CarbonInterval.php(1620): Carbon\\CarbonInterval->Carbon\\{closure}()
#7 /firefly-iii/vendor/nesbot/carbon/src/Carbon/CarbonInterval.php(1645): Carbon\\CarbonInterval->Carbon\\{closure}()
#8 /firefly-iii/vendor/nesbot/carbon/src/Carbon/Traits/Difference.php(813): Carbon\\CarbonInterval->forHumans()
#9 /firefly-iii/app/Support/Cronjobs/RecurringCronjob.php(47): Carbon\\Carbon->diffForHumans()
#10 /firefly-iii/app/Console/Commands/Tools/Cron.php(129): FireflyIII\\Support\\Cronjobs\\RecurringCronjob->fire()
#11 /firefly-iii/app/Console/Commands/Tools/Cron.php(77): FireflyIII\\Console\\Commands\\Tools\\Cron->recurringCronJob()
#12 /firefly-iii/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): FireflyIII\\Console\\Commands\\Tools\\Cron->handle()
#13 /firefly-iii/vendor/laravel/framework/src/Illuminate/Container/Util.php(40): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#14 /firefly-iii/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure()
#15 /firefly-iii/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\\Container\\BoundMethod::callBoundMethod()
#16 /firefly-iii/vendor/laravel/framework/src/Illuminate/Container/Container.php(611): Illuminate\\Container\\BoundMethod::call()
#17 /firefly-iii/vendor/laravel/framework/src/Illuminate/Console/Command.php(136): Illuminate\\Container\\Container->call()
#18 /firefly-iii/vendor/symfony/console/Command/Command.php(256): Illuminate\\Console\\Command->execute()
#19 /firefly-iii/vendor/laravel/framework/src/Illuminate/Console/Command.php(121): Symfony\\Component\\Console\\Command\\Command->run()
#20 /firefly-iii/vendor/symfony/console/Application.php(971): Illuminate\\Console\\Command->run()
#21 /firefly-iii/vendor/symfony/console/Application.php(290): Symfony\\Component\\Console\\Application->doRunCommand()
#22 /firefly-iii/vendor/symfony/console/Application.php(166): Symfony\\Component\\Console\\Application->doRun()
#23 /firefly-iii/vendor/laravel/framework/src/Illuminate/Console/Application.php(92): Symfony\\Component\\Console\\Application->run()
#24 /firefly-iii/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(129): Illuminate\\Console\\Application->run()
#25 /firefly-iii/artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle()
#26 {main}
"}

In TranslatorTrait.php line 125:

  Unable to choose a translation for ":count r|:count l" with locale "pl_PL" for value "51". Double check that this translation has the correct plural options (e.g. "There is one apple|There are %count% apples").

`

**Comment by JC5** [comment]
https://github.com/firefly-iii/firefly-iii/issues/4845
