### ISSUE TITLE
[CSV importer] CSV files started failing on isValidIban

### ISSUE THREAD

**Issue by daften** [firefly-iii/firefly-iii#4840]
**Bug description**
I am running Firefly III version 5.5.12 and CSV importer 2.5.2, and my problem is:

Since now or a bit ago a specific monthly transaction (CC payment) fails. It contains an account number where the IBAN nr should go, and it fails on the bcmod check because it's not considered valid. The number is basically an old belgian account nr: 3 numbers, a dash, 9 numbers, a dash and 2 numbers.

This type of account nr in the IBAN column worked at least until about a month ago. I can't see anything in the CSV importer code changes causing this, so I'm guessing it's maybe a PHP upgrade in the container that became more strict. A simple fix would be to add an additional replace to have - replaced by an empty string too, if that's possible?

**Steps to reproduce**

Use an account number like 666-0000004-87 (made up, so bcmod will fail here)

**Extra info**
Using the docker containers, auto-updated through watchtower.

**Comment by JC5** [comment]
Could you share the exact error please?

**Comment by daften** [comment]
I get this:
```
2021-06-06T18:11:31.101915748Z [2021-06-06 20:11:31] production.ERROR: bcmod(): Argument #1 ($num1) is not well-formed {"exception":"[object] (ValueError(code: 0): bcmod(): Argument #1 ($num1) is not well-formed at /var/www/html/app/Services/CSV/Converter/Iban.php:77)
2021-06-06T18:11:31.102069842Z [stacktrace]
2021-06-06T18:11:31.102101553Z #0 /var/www/html/app/Services/CSV/Converter/Iban.php(77): bcmod()
2021-06-06T18:11:31.102133454Z #1 /var/www/html/app/Services/CSV/Converter/Iban.php(45): App\\Services\\CSV\\Converter\\Iban->isValidIban()
2021-06-06T18:11:31.102169882Z #2 /var/www/html/app/Services/CSV/Converter/ConverterService.php(54): App\\Services\\CSV\\Converter\\Iban->convert()
2021-06-06T18:11:31.102210250Z #3 /var/www/html/app/Services/Import/ColumnValue.php(125): App\\Services\\CSV\\Converter\\ConverterService::convert()
2021-06-06T18:11:31.102246277Z #4 /var/www/html/app/Services/Import/Routine/ColumnValueConverter.php(123): App\\Services\\Import\\ColumnValue->getParsedValue()
2021-06-06T18:11:31.102282401Z #5 /var/www/html/app/Services/Import/Routine/ColumnValueConverter.php(72): App\\Services\\Import\\Routine\\ColumnValueConverter->processValueArray()
2021-06-06T18:11:31.102319932Z #6 /var/www/html/app/Services/Import/ImportRoutineManager.php(184): App\\Services\\Import\\Routine\\ColumnValueConverter->processValueArrays()
2021-06-06T18:11:31.102355068Z #7 /var/www/html/app/Http/Controllers/Import/RunController.php(115): App\\Services\\Import\\ImportRoutineManager->start()
2021-06-06T18:11:31.102399479Z #8 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): App\\Http\\Controllers\\Import\\RunController->start()
2021-06-06T18:11:31.102442999Z #9 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\\Routing\\Controller->callAction()
2021-06-06T18:11:31.102479151Z #10 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Route.php(254): Illuminate\\Routing\\ControllerDispatcher->dispatch()
2021-06-06T18:11:31.102531914Z #11 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Route.php(197): Illuminate\\Routing\\Route->runController()
2021-06-06T18:11:31.102567775Z #12 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(695): Illuminate\\Routing\\Route->run()
2021-06-06T18:11:31.102602077Z #13 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}()
2021-06-06T18:11:31.102640277Z #14 /var/www/html/app/Http/Middleware/ReadyForImport.php(47): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
2021-06-06T18:11:31.102681691Z #15 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): App\\Http\\Middleware\\ReadyForImport->handle()
2021-06-06T18:11:31.102718743Z #16 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(50): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()

```

**Comment by JC5** [comment]
Will be fixed in the next release.
