### ISSUE TITLE
PL translation error on cron job execution

### ISSUE THREAD

**Issue by maszczyn** [firefly-iii/firefly-iii#4845]
I use my own instance of FF3 running in a docker container using official image. I've set up a cron job for it (according to [these instructions](https://docs.firefly-iii.org/firefly-iii/advanced-installation/cron/#call-the-cron-job-from-the-host-system)), which executes the following command in the container:

```sh
/usr/local/bin/php /var/www/html/artisan firefly-iii:cron
```

Unfortunately, the above command results in error. This is the content of an email I received after issuing the command:

```
Firefly III v5.5.12 napotkał błąd: Unable to choose a translation for ":count r|:count l" with locale "pl_PL" for value "51". Double check that this translation has the correct plural options (e.g. "There is one apple|There are %count% apples")..

Błąd był typu "Symfony\Component\Translation\Exception\InvalidArgumentException".

Błąd wystąpił o: Sun, 06 Jun 2021 05:12:36 +0000.

Błąd wystąpił w pliku "/var/www/html/vendor/symfony/translation-contracts/TranslatorTrait.php" linia 125 z kodem 0.

Dla tego błędu nie znaleziono zalogowanego użytkownika lub nie wykryto żadnego użytkownika.

Adres IP związany z tym błędem to: 127.0.0.1 (info)
Adres URL to: [REDACTED]
Agent użytkownika: Symfony

Pełny opis błędu znajduje się poniżej. Jeśli uważasz, że jest to błąd w Firefly III, możesz przesłać tę wiadomość do james@[REDACTED]. To może pomóc naprawić napotkany właśnie błąd.

Jeśli wolisz, możesz również otworzyć nowy problem na GitHub.

Pełny opis błędu znajduje się poniżej:

#0 /var/www/html/vendor/symfony/translation/Formatter/MessageFormatter.php(43): Symfony\Component\Translation\IdentityTranslator->trans()
#1 /var/www/html/vendor/symfony/translation/Translator.php(225): Symfony\Component\Translation\Formatter\MessageFormatter->format()
#2 /var/www/html/vendor/nesbot/carbon/src/Carbon/Translator.php(172): Symfony\Component\Translation\Translator->trans()
#3 /var/www/html/vendor/nesbot/carbon/src/Carbon/Traits/Localization.php(230): Carbon\Translator->trans()
#4 /var/www/html/vendor/nesbot/carbon/src/Carbon/Traits/Localization.php(249): Carbon\CarbonInterval::translateWith()
#5 /var/www/html/vendor/nesbot/carbon/src/Carbon/CarbonInterval.php(1576): Carbon\CarbonInterval->translate()
#6 /var/www/html/vendor/nesbot/carbon/src/Carbon/CarbonInterval.php(1620): Carbon\CarbonInterval->Carbon\{closure}()
#7 /var/www/html/vendor/nesbot/carbon/src/Carbon/CarbonInterval.php(1645): Carbon\CarbonInterval->Carbon\{closure}()
#8 /var/www/html/vendor/nesbot/carbon/src/Carbon/Traits/Difference.php(813): Carbon\CarbonInterval->forHumans()
#9 /var/www/html/app/Support/Cronjobs/RecurringCronjob.php(47): Carbon\Carbon->diffForHumans()
#10 /var/www/html/app/Console/Commands/Tools/Cron.php(129): FireflyIII\Support\Cronjobs\RecurringCronjob->fire()
#11 /var/www/html/app/Console/Commands/Tools/Cron.php(77): FireflyIII\Console\Commands\Tools\Cron->recurringCronJob()
#12 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): FireflyIII\Console\Commands\Tools\Cron->handle()
#13 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Util.php(40): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#14 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\Container\Util::unwrapIfClosure()
#15 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\Container\BoundMethod::callBoundMethod()
#16 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(611): Illuminate\Container\BoundMethod::call()
#17 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(136): Illuminate\Container\Container->call()
#18 /var/www/html/vendor/symfony/console/Command/Command.php(256): Illuminate\Console\Command->execute()
#19 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(121): Symfony\Component\Console\Command\Command->run()
#20 /var/www/html/vendor/symfony/console/Application.php(971): Illuminate\Console\Command->run()
#21 /var/www/html/vendor/symfony/console/Application.php(290): Symfony\Component\Console\Application->doRunCommand()
#22 /var/www/html/vendor/symfony/console/Application.php(166): Symfony\Component\Console\Application->doRun()
#23 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Application.php(92): Symfony\Component\Console\Application->run()
#24 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(129): Illuminate\Console\Application->run()
#25 /var/www/html/artisan(37): Illuminate\Foundation\Console\Kernel->handle()
#26 {main}
```

After a bit of debugging, I found out that the issue is related to polish translations and can be fixed with the following patch applied in the container:

```patch
--- /var/www/html/vendor/nesbot/carbon/src/Carbon/Lang/pl.php 2021-06-06 05:40:03.279674918 +0000
+++ /var/www/html/vendor/nesbot/carbon/src/Carbon/Lang/pl.php 2021-06-06 05:38:04.763178921 +0000
@@ -29,7 +29,7 @@
 return [
     'year' => ':count rok|:count lata|:count lat',
     'a_year' => 'rok|:count lata|:count lat',
-    'y' => ':count r|:count l',
+    'y' => ':count r|:count l|:count l',
     'month' => ':count miesiąc|:count miesiące|:count miesięcy',
     'a_month' => 'miesiąc|:count miesiące|:count miesięcy',
     'm' => ':count mies.',
```

And yes - variants 2 & 3 should be the same IMO.

I don't really know PHP nor its packaging system, but as far as I understand, the issue is not in FF3's code itself - I think it's caused by some library it uses. Nevertheless I decided to report this bug in here as 1) I don't know where the bug belongs and 2) wouldn't be able to provide a reproduction steps without FF3 in a reasonable amount of time.

**Comment by JC5** [comment]
Submit a PR on the following file, and refer to this issue. I will have to update Firefly III to make this happen for everybody, but that's not the issue:

https://github.com/briannesbitt/Carbon/blob/master/src/Carbon/Lang/pl.php#L32

**Comment by maszczyn** [comment]
just bumping the issue so it wouldn't close...
The fix is merged into Carbon's master, waiting to be released & only then it can be used in FF.

**Comment by JC5** [comment]
I saw it, thanks!

**Comment by maszczyn** [comment]
seems the issue got closed anyway...

Carbon has been released a couple days ago and the new version includes the fix. @JC5 could you please make a change in FF to use this newer version of Carbon?

**Comment by JC5** [comment]
Already done :+1:

```
  - Downloading nesbot/carbon (2.50.0)
  - ```

**Comment by tomasz-lasko** [comment]
Hello @JC5 , I have installed a fresh 5.5.13 release (Ubuntu 20.04, PHP 7.4.3, composer freshly downloaded with the command from your docs) and it shows:

  - Downloading nesbot/carbon (2.47.0)

Oh... now I see, you put the change in 739d01efe4e9098219f91a48e16547d3a336e3b2 for  5.6.0-alpha.1

**Would it be a problem to add this slight change of carbon to 5.5 (another hotfix .e.g. 5.5.14)?** I mean I'm not sure if it would be much work for you, but probably would not make much diff conflict during any branch merges? 

But if yes, then OK, I will have wait I guess a couple of weeks until I start using cron. Or is there any workaround (just from the tip of your head, without thinking too long)?

Best regards!

**Comment by JC5** [comment]
`composer update` should work for the time being. :+1:
