### ISSUE TITLE
isValidIban still failing in container

### ISSUE THREAD

**Issue by daften** [firefly-iii/firefly-iii#4931]
**Bug description**
I am running Firefly III version 5.5.12 and CSV importer 2.5.4, and my problem is:

The issue reported in #4840 is still there or more likely, back. When checking the logs and outputting some data, I notice old account nr's for belgium get converted to something with a dash at  the end (the first 4 characters are put at the end, and that includes a dash).

I tried checking further on how to catch this, but added a catch on Exception or Error did not help:
```
        try {
            Log::debug(sprintf('Iban: %s', $iban));
            $checksum = bcmod($iban, '97');
        } catch (ValueError $e) {
            Log::error(sprintf('Bad IBAN (%s): %s', $iban, $e->getMessage()));
            $checksum = 2;
        } catch (Exception $e) {
            Log::error(sprintf('Fuck me: %s', $iban));
            $checksum = 2;
        } catch (Error $e) {
            Log::error(sprintf('Error: %s', $iban));
            $checksum = 2;
        }
```

The error wasn't there on docker image 2.5.3 and I'm guessing it has to do with the revert to PHP7.4 for that container, since PHP7 doesn't contain ValueError yet, which was the change introduced through firefly-iii/csv-importer@af96336

**Steps to reproduce**

Use an account number as described in #4840.

**Extra info**

Firefly CSV importer log output (from docker container)

```
today at 23:12:03 [2021-07-22 23:12:03] production.ERROR: bcmod(): bcmath function argument is not well-formed  
today at 23:12:03 [2021-07-22 23:12:03] production.ERROR: #0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError()
today at 23:12:03 #1 /var/www/html/app/Services/CSV/Converter/Iban.php(79): bcmod()
today at 23:12:03 #2 /var/www/html/app/Services/CSV/Converter/Iban.php(46): App\Services\CSV\Converter\Iban->isValidIban()
today at 23:12:03 #3 /var/www/html/app/Services/CSV/Converter/ConverterService.php(54): App\Services\CSV\Converter\Iban->convert()
today at 23:12:03 #4 /var/www/html/app/Services/Import/ColumnValue.php(125): App\Services\CSV\Converter\ConverterService::convert()
today at 23:12:03 #5 /var/www/html/app/Services/Import/Routine/ColumnValueConverter.php(123): App\Services\Import\ColumnValue->getParsedValue()
today at 23:12:03 #6 /var/www/html/app/Services/Import/Routine/ColumnValueConverter.php(72): App\Services\Import\Routine\ColumnValueConverter->processValueArray()
today at 23:12:03 #7 /var/www/html/app/Services/Import/ImportRoutineManager.php(184): App\Services\Import\Routine\ColumnValueConverter->processValueArrays()
today at 23:12:03 #8 /var/www/html/app/Http/Controllers/Import/RunController.php(115): App\Services\Import\ImportRoutineManager->start()
today at 23:12:03 #9 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): App\Http\Controllers\Import\RunController->start()
today at 23:12:03 #10 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\Routing\Controller->callAction()
today at 23:12:03 #11 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Route.php(254): Illuminate\Routing\ControllerDispatcher->dispatch()
today at 23:12:03 #12 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Route.php(197): Illuminate\Routing\Route->runController()
today at 23:12:03 #13 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(695): Illuminate\Routing\Route->run()
today at 23:12:03 #14 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\Routing\Router->Illuminate\Routing\{closure}()
today at 23:12:03 #15 /var/www/html/app/Http/Middleware/ReadyForImport.php(47): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
today at 23:12:03 #16 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): App\Http\Middleware\ReadyForImport->handle()
today at 23:12:03 #17 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(50): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
today at 23:12:03 #18 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Routing\Middleware\SubstituteBindings->handle()
today at 23:12:03 #19 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(78): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
today at 23:12:03 #20 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Foundation\Http\Middleware\VerifyCsrfToken->handle()
today at 23:12:03 #21 /var/www/html/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
today at 23:12:03 #22 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\View\Middleware\ShareErrorsFromSession->handle()
today at 23:12:03 #23 /var/www/html/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(121): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
today at 23:12:03 #24 /var/www/html/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(64): Illuminate\Session\Middleware\StartSession->handleStatefulRequest()
today at 23:12:03 #25 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Session\Middleware\StartSession->handle()
today at 23:12:03 #26 /var/www/html/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
today at 23:12:03 #27 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle()
today at 23:12:03 #28 /var/www/html/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(67): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
today at 23:12:03 #29 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Cookie\Middleware\EncryptCookies->handle()
today at 23:12:03 #30 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
today at 23:12:03 #31 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(697): Illuminate\Pipeline\Pipeline->then()
today at 23:12:03 #32 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(672): Illuminate\Routing\Router->runRouteWithinStack()
today at 23:12:03 #33 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(636): Illuminate\Routing\Router->runRoute()
today at 23:12:03 #34 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(625): Illuminate\Routing\Router->dispatchToRoute()
today at 23:12:03 #35 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(166): Illuminate\Routing\Router->dispatch()
today at 23:12:03 #36 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}()
today at 23:12:03 #37 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
today at 23:12:03 #38 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.php(31): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle()
today at 23:12:03 #39 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Foundation\Http\Middleware\ConvertEmptyStringsToNull->handle()
today at 23:12:03 #40 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
today at 23:12:03 #41 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php(40): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle()
today at 23:12:03 #42 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Foundation\Http\Middleware\TrimStrings->handle()
today at 23:12:03 #43 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
today at 23:12:03 #44 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Foundation\Http\Middleware\ValidatePostSize->handle()
today at 23:12:03 #45 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(86): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
today at 23:12:03 #46 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Foundation\Http\Middleware\PreventRequestsDuringMaintenance->handle()
today at 23:12:03 #47 /var/www/html/vendor/fruitcake/laravel-cors/src/HandleCors.php(38): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
today at 23:12:03 #48 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Fruitcake\Cors\HandleCors->handle()
today at 23:12:03 #49 /var/www/html/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
today at 23:12:03 #50 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Fideloper\Proxy\TrustProxies->handle()
today at 23:12:03 #51 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
today at 23:12:03 #52 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(141): Illuminate\Pipeline\Pipeline->then()
today at 23:12:03 #53 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(110): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter()
today at 23:12:03 #54 /var/www/html/public/index.php(99): Illuminate\Foundation\Http\Kernel->handle()
today at 23:12:03 #55 {main}  
today at 23:12:03 [2021-07-22 23:12:03] production.DEBUG: Add error on index #0 (line no. 1): Internal error: bcmod(): bcmath function argument is not well-formed in file /var/www/html/app/Services/CSV/Converter/Iban.php:79  
```

**Comment by JC5** [comment]
Thanks for letting me know. I can rebuild the new release on 8.0 and that should fix it.

**Comment by JC5** [comment]
Done!

**Comment by daften** [comment]
Can't test it right now, but I'll re-report or re-open should it still be an error, which I'm not expecting. Thanks!
