### ISSUE TITLE
SQL error on editing multiple transactions (PostgreSQL)

### ISSUE THREAD

**Issue by AlexFullmoon** [firefly-iii/firefly-iii#4955]
**Bug description**
Firefly III version 5.5.13 (Docker :latest), database PostgreSQL 13.3 (migrated from MariaDB some time ago)

Attempting to edit multiple transaction result in SQLERROR:

SQLSTATE[42703]: Undefined column: 7 ERROR: column tags.zoomLevel does not exist
LINE 1: ...latitude", "tags"."longitude" as "tag_longitude", "tags"."zo...
^
HINT: Perhaps you meant to reference the column "tags.zoomlevel". (SQL: select "transaction_groups"."id" as "transaction_group_id", "transaction_groups"."user_id" as "user_id", "transaction_groups"."created_at" as "created_at", "transaction_groups"."updated_at" as "updated_at", "transaction_groups"."title" as "transaction_group_title", "transaction_journals"."id" as "transaction_journal_id", "transaction_journals"."transaction_type_id", "transaction_journals"."description", "transaction_journals"."date", "transaction_journals"."order", "transaction_types"."type" as "transaction_type_type", "source"."id" as "source_transaction_id", "source"."account_id" as "source_account_id", "source"."reconciled", "source"."amount" as "amount", "source"."transaction_currency_id" as "currency_id", "currency"."code" as "currency_code", "currency"."name" as "currency_name", "currency"."symbol" as "currency_symbol", "currency"."decimal_places" as "currency_decimal_places", "source"."foreign_amount" as "foreign_amount", "source"."foreign_currency_id" as "foreign_currency_id", "foreign_currency"."code" as "foreign_currency_code", "foreign_currency"."name" as "foreign_currency_name", "foreign_currency"."symbol" as "foreign_currency_symbol", "foreign_currency"."decimal_places" as "foreign_currency_decimal_places", "destination"."account_id" as "destination_account_id", "categories"."id" as "category_id", "categories"."name" as "category_name", "budgets"."id" as "budget_id", "budgets"."name" as "budget_name", "tags"."id" as "tag_id", "tags"."tag" as "tag_name", "tags"."date" as "tag_date", "tags"."description" as "tag_description", "tags"."latitude" as "tag_latitude", "tags"."longitude" as "tag_longitude", "tags"."zoomLevel" as "tag_zoom_level", "source_account"."name" as "source_account_name", "source_account"."iban" as "source_account_iban", "source_account_type"."type" as "source_account_type", "dest_account"."name" as "destination_account_name", "dest_account"."iban" as "destination_account_iban", "dest_account_type"."type" as "destination_account_type" from "transaction_journals" left join "transaction_groups" on "transaction_journals"."transaction_group_id" = "transaction_groups"."id" left join "transactions" as "source" on "source"."transaction_journal_id" = "transaction_journals"."id" and "source"."amount" < 0 left join "transactions" as "destination" on "destination"."transaction_journal_id" = "transaction_journals"."id" and "destination"."amount" > 0 left join "transaction_types" on "transaction_types"."id" = "transaction_journals"."transaction_type_id" left join "transaction_currencies" as "currency" on "currency"."id" = "source"."transaction_currency_id" left join "transaction_currencies" as "foreign_currency" on "foreign_currency"."id" = "source"."foreign_currency_id" left join "category_transaction_journal" on "category_transaction_journal"."transaction_journal_id" = "transaction_journals"."id" left join "categories" on "category_transaction_journal"."category_id" = "categories"."id" left join "budget_transaction_journal" on "budget_transaction_journal"."transaction_journal_id" = "transaction_journals"."id" left join "budgets" on "budget_transaction_journal"."budget_id" = "budgets"."id" left join "tag_transaction_journal" on "tag_transaction_journal"."transaction_journal_id" = "transaction_journals"."id" left join "tags" on "tag_transaction_journal"."tag_id" = "tags"."id" left join "accounts" as "source_account" on "source_account"."id" = "source"."account_id" left join "account_types" as "source_account_type" on "source_account_type"."id" = "source_account"."account_type_id" left join "accounts" as "dest_account" on "dest_account"."id" = "destination"."account_id" left join "account_types" as "dest_account_type" on "dest_account_type"."id" = "dest_account"."account_type_id" where "transaction_journals"."user_id" = 1 and "transaction_journals"."user_id" is not null and "transaction_groups"."deleted_at" is null and "transaction_journals"."deleted_at" is null and "source"."deleted_at" is null and "destination"."deleted_at" is null and "transaction_types"."type" in (Withdrawal, Deposit, Transfer, Reconciliation) and "transaction_journals"."id" in (417, 381, 380, 379, 378) and "transaction_journals"."deleted_at" is null order by "transaction_journals"."date" desc, "transaction_journals"."order" asc, "transaction_journals"."id" desc, "transaction_journals"."description" desc, "source"."amount" desc)

As it _seems_ (I don't know SQL all that much) FIII queries hardcoded 'zoomLevel' column name, while it probably was created as 'zoomlevel' and this discrepancy was ignored in case-insensitive MariaDB.

**Steps to reproduce**

No idea honestly. Maybe create database in MariaDB, add several transactions, migrate to PostgreSQL (I used pgloader) and try group editing those transactions?

I migrated several months ago, updated several times, and until today never used group transaction edit, so not sure when it broke.

**Extra info**
Firefox 90, Windows.
Debug information generated at 2021-07-30 16:29:35 Europe/Simferopol for Firefly III version **5.5.13**.

| Scope | Version |
| --- | --- |
| Firefly III | 5.5.13 |
| Firefly III API | 1.5.2 |
| PHP | 8.0.8 |
| Host | Linux |

| System info | Value |
| --- | --- |
| Installation ID | 12798811-65d9-4d4b-8fb0-4ce78e5a97d7 |
| Using docker? | true |
| Telemetry | false |
| Layout |  |
| System TZ | Europe/Simferopol |
| Browser TZ | Europe/Moscow |
| App environment | local |
| App debug mode | true |
| App cache driver | redis |
| App logging | debug, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Interface | apache2handler |
| Default language | en_US |
| Default locale | equal |
| BCscale | 24 |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | pgsql |
| DB version | 16 (exp. 16) |
| Login provider | eloquent  |
| Trusted proxies (.env) | ** |

| User info | Value |
| --- | --- |
| Session start | 2021-07-01 00:00:00 |
| Session end | 2021-07-31 23:59:59 |
| Session first | 2020-08-01 00:00:00 |
| User ID | 1 |
| User language | ru_RU |
| User locale | ru_RU |
| Attempt at "ru_RU.utf8" | 'ru_RU.utf8' |
| Attempt at "ru_RU.UTF-8" | 'ru_RU.UTF-8' |
| User agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:90.0) Gecko/20100101 Firefox/90.0 |

```
ERROR:  column tags.zoomLevel does not exist
LINE 1: ...latitude\", \"tags\".\"longitude\" as \"tag_longitude\", \"tags\".\"zo...
                                                             ^
HINT:  Perhaps you meant to reference the column \"tags.zoomlevel\". (SQL: select \"transaction_groups\".\"id\" as \"transaction_group_id\", \"transaction_groups\".\"user_id\" as \"user_id\", \"transaction_groups\".\"created_at\" as \"created_at\", \"transaction_groups\".\"updated_at\" as \"updated_at\", \"transaction_groups\".\"title\" as \"transaction_group_title\", \"transaction_journals\".\"id\" as \"transaction_journal_id\", \"transaction_journals\".\"transaction_type_id\", \"transaction_journals\".\"description\", \"transaction_journals\".\"date\", \"transaction_journals\".\"order\", \"transaction_types\".\"type\" as \"transaction_type_type\", \"source\".\"id\" as \"source_transaction_id\", \"source\".\"account_id\" as \"source_account_id\", \"source\".\"reconciled\", \"source\".\"amount\" as \"amount\", \"source\".\"transaction_currency_id\" as \"currency_id\", \"currency\".\"code\" as \"currency_code\", \"currency\".\"name\" as \"currency_name\", \"currency\".\"symbol\" as \"currency_symbol\", \"currency\".\"decimal_places\" as \"currency_decimal_places\", \"source\".\"foreign_amount\" as \"foreign_amount\", \"source\".\"foreign_currency_id\" as \"foreign_currency_id\", \"foreign_currency\".\"code\" as \"foreign_currency_code\", \"foreign_currency\".\"name\" as \"foreign_currency_name\", \"foreign_currency\".\"symbol\" as \"foreign_currency_symbol\", \"foreign_currency\".\"decimal_places\" as \"foreign_currency_decimal_places\", \"destination\".\"account_id\" as \"destination_account_id\", \"categories\".\"id\" as \"category_id\", \"categories\".\"name\" as \"category_name\", \"budgets\".\"id\" as \"budget_id\", \"budgets\".\"name\" as \"budget_name\", \"tags\".\"id\" as \"tag_id\", \"tags\".\"tag\" as \"tag_name\", \"tags\".\"date\" as \"tag_date\", \"tags\".\"description\" as \"tag_description\", \"tags\".\"latitude\" as \"tag_latitude\", \"tags\".\"longitude\" as \"tag_longitude\", \"tags\".\"zoomLevel\" as \"tag_zoom_level\", \"source_account\".\"name\" as \"source_account_name\", \"source_account\".\"iban\" as \"source_account_iban\", \"source_account_type\".\"type\" as \"source_account_type\", \"dest_account\".\"name\" as \"destination_account_name\", \"dest_account\".\"iban\" as \"destination_account_iban\", \"dest_account_type\".\"type\" as \"destination_account_type\" from \"transaction_journals\" left join \"transaction_groups\" on \"transaction_journals\".\"transaction_group_id\" = \"transaction_groups\".\"id\" left join \"transactions\" as \"source\" on \"source\".\"transaction_journal_id\" = \"transaction_journals\".\"id\" and \"source\".\"amount\" < 0 left join \"transactions\" as \"destination\" on \"destination\".\"transaction_journal_id\" = \"transaction_journals\".\"id\" and \"destination\".\"amount\" > 0 left join \"transaction_types\" on \"transaction_types\".\"id\" = \"transaction_journals\".\"transaction_type_id\" left join \"transaction_currencies\" as \"currency\" on \"currency\".\"id\" = \"source\".\"transaction_currency_id\" left join \"transaction_currencies\" as \"foreign_currency\" on \"foreign_currency\".\"id\" = \"source\".\"foreign_currency_id\" left join \"category_transaction_journal\" on \"category_transaction_journal\".\"transaction_journal_id\" = \"transaction_journals\".\"id\" left join \"categories\" on \"category_transaction_journal\".\"category_id\" = \"categories\".\"id\" left join \"budget_transaction_journal\" on \"budget_transaction_journal\".\"transaction_journal_id\" = \"transaction_journals\".\"id\" left join \"budgets\" on \"budget_transaction_journal\".\"budget_id\" = \"budgets\".\"id\" left join \"tag_transaction_journal\" on \"tag_transaction_journal\".\"transaction_journal_id\" = \"transaction_journals\".\"id\" left join \"tags\" on \"tag_transaction_journal\".\"tag_id\" = \"tags\".\"id\" left join \"accounts\" as \"source_account\" on \"source_account\".\"id\" = \"source\".\"account_id\" left join \"account_types\" as \"source_account_type\" on \"source_account_type\".\"id\" = \"source_account\".\"account_type_id\" left join \"accounts\" as \"dest_account\" on \"dest_account\".\"id\" = \"destination\".\"account_id\" left join \"account_types\" as \"dest_account_type\" on \"dest_account_type\".\"id\" = \"dest_account\".\"account_type_id\" where \"transaction_journals\".\"user_id\" = 1 and \"transaction_journals\".\"user_id\" is not null and \"transaction_groups\".\"deleted_at\" is null and \"transaction_journals\".\"deleted_at\" is null and \"source\".\"deleted_at\" is null and \"destination\".\"deleted_at\" is null and \"transaction_types\".\"type\" in (Withdrawal, Deposit, Transfer, Reconciliation) and \"transaction_journals\".\"id\" in (417, 381, 380, 379, 378) and \"transaction_journals\".\"deleted_at\" is null order by \"transaction_journals\".\"date\" desc, \"transaction_journals\".\"order\" asc, \"transaction_journals\".\"id\" desc, \"transaction_journals\".\"description\" desc, \"source\".\"amount\" desc) at /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php:678)
[stacktrace]
#0 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php(638): Illuminate\\Database\\Connection->runQueryCallback()
#1 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php(346): Illuminate\\Database\\Connection->run()
#2 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2313): Illuminate\\Database\\Connection->select()
#3 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2301): Illuminate\\Database\\Query\\Builder->runSelect()
#4 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2796): Illuminate\\Database\\Query\\Builder->Illuminate\\Database\\Query\\{closure}()
#5 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2302): Illuminate\\Database\\Query\\Builder->onceWithColumns()
#6 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(588): Illuminate\\Database\\Query\\Builder->get()
#7 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(572): Illuminate\\Database\\Eloquent\\Builder->getModels()
#8 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Relations/Relation.php(188): Illuminate\\Database\\Eloquent\\Builder->get()
#9 /var/www/html/app/Helpers/Collector/GroupCollector.php(241): Illuminate\\Database\\Eloquent\\Relations\\Relation->get()
#10 /var/www/html/app/Helpers/Collector/GroupCollector.php(208): FireflyIII\\Helpers\\Collector\\GroupCollector->getGroups()
#11 /var/www/html/app/Support/Binder/JournalList.php(54): FireflyIII\\Helpers\\Collector\\GroupCollector->getExtractedJournals()
#12 /var/www/html/app/Http/Middleware/Binder.php(94): FireflyIII\\Support\\Binder\\JournalList::routeBinder()
#13 /var/www/html/app/Http/Middleware/Binder.php(73): FireflyIII\\Http\\Middleware\\Binder->performBinding()
#14 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): FireflyIII\\Http\\Middleware\\Binder->handle()
#15 /var/www/html/app/Http/Middleware/Range.php(62): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#16 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): FireflyIII\\Http\\Middleware\\Range->handle()
#17 /var/www/html/vendor/jc5/google2fa-laravel/src/Middleware.php(29): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#18 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): PragmaRX\\Google2FALaravel\\Middleware->handle()
#19 /var/www/html/app/Http/Middleware/Authenticate.php(75): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#20 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): FireflyIII\\Http\\Middleware\\Authenticate->handle()
#21 /var/www/html/vendor/laravel/passport/src/Http/Middleware/CreateFreshApiToken.php(50): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#22 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Laravel\\Passport\\Http\\Middleware\\CreateFreshApiToken->handle()
#23 /var/www/html/vendor/laravel/framework/src/Illuminate/Session/Middleware/AuthenticateSession.php(58): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#24 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Session\\Middleware\\AuthenticateSession->handle()
#25 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(78): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#26 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle()
#27 /var/www/html/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#28 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle()
#29 /var/www/html/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(121): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#30 /var/www/html/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(64): Illuminate\\Session\\Middleware\\StartSession->handleStatefulRequest()
#31 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Session\\Middleware\\StartSession->handle()
#32 /var/www/html/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#33 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle()
#34 /var/www/html/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(67): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#35 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle()
#36 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#37 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(697): Illuminate\\Pipeline\\Pipeline->then()
#38 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(672): Illuminate\\Routing\\Router->runRouteWithinStack()
#39 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(636): Illuminate\\Routing\\Router->runRoute()
#40 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(625): Illuminate\\Routing\\Router->dispatchToRoute()
#41 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(166): Illuminate\\Routing\\Router->dispatch()
#42 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}()
#43 /var/www/html/app/Http/Middleware/InstallationId.php(54): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#44 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): FireflyIII\\Http\\Middleware\\InstallationId->handle()
#45 /var/www/html/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#46 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Fideloper\\Proxy\\TrustProxies->handle()
#47 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#48 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.php(31): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#49 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\ConvertEmptyStringsToNull->handle()
#50 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#51 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php(40): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#52 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\TrimStrings->handle()
#53 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#54 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle()
#55 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(86): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#56 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance->handle()
#57 /var/www/html/app/Http/Middleware/SecureHeaders.php(51): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#58 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): FireflyIII\\Http\\Middleware\\SecureHeaders->handle()
#59 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#60 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(141): Illuminate\\Pipeline\\Pipeline->then()
#61 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(110): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter()
#62 /var/www/html/public/index.php(76): Illuminate\\Foundation\\Http\\Kernel->handle()
#63 {main}

```
[ff3-cli.log](https://github.com/firefly-iii/firefly-iii/files/6907978/ff3-cli.log)

**Comment by JC5** [comment]
The column was created as `zoomLevel`. If the migration to pgsql didn't take it into account but it breaks now, all you need to do is (manually) rename the column to `zoomLevel` to fix it.

**Comment by AlexFullmoon** [comment]
Done that, thanks.
