### ISSUE TITLE
Error creating 1st user on fresh installation

### ISSUE THREAD

**Issue by winvan** [firefly-iii/firefly-iii#4993]
Hi!
I just install new fresh installation of firefly iii and can't create a first user
I got these error:
```
Return value of FireflyIII\Support\Amount::getDefaultCurrencyByUser() must be an instance of FireflyIII\Models\TransactionCurrency, null returned
```
I search in issues, but is it not my case: i have properly initialized DB, give all acesses in DB and filsystem, DB is writeable

Info from debug page:
Debug information generated at 2021-08-15 23:50:55 Asia/Novosibirsk for Firefly III version **5.5.13**.

| Scope | Version |
| --- | --- |
| Firefly III | 5.5.13 |
| Firefly III API | 1.5.2 |
| PHP | 7.4.22 |
| Host | Linux |

| System info | Value |
| --- | --- |
| Installation ID | f3e1d5e9-f6db-465b-9158-4b9d95b885bb |
| Using docker? | false |
| Telemetry | false |
| Layout | v1 |
| System TZ | Asia/Novosibirsk |
| Browser TZ | Asia/Novosibirsk |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | notice, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Interface | fpm-fcgi |
| Default language | en_US |
| Default locale | equal |
| BCscale | 24 |
| DB drivers | pgsql |
| Current driver | pgsql |
| DB version | 16 (exp. 16) |
| Login provider | eloquent  |
| Trusted proxies (.env) | ** |

| User info | Value |
| --- | --- |
| Session start | 2021-08-01 00:00:00 |
| Session end | 2021-08-31 23:59:59 |
| Session first | 2021-01-01 00:00:00 |
| User ID | 1 |
| User language | en_US |
| User locale | en_US |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| User agent | Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.101 Safari/537.36 |

```
Truncated from this point <----|15 23:48:29] local.ERROR: Return value of FireflyIII\Support\Amount::getDefaultCurrencyByUser() must be an instance of FireflyIII\Models\TransactionCurrency, null returned {"userId":1,"exception":"[object] (TypeError(code: 0): Return value of FireflyIII\\Support\\Amount::getDefaultCurrencyByUser() must be an instance of FireflyIII\\Models\\TransactionCurrency, null returned at /var/www/firefly-iii/app/Support/Amount.php:175)
[stacktrace]
#0 /var/www/firefly-iii/app/Support/Amount.php(141): FireflyIII\\Support\\Amount->getDefaultCurrencyByUser()
#1 /var/www/firefly-iii/app/Http/Middleware/Range.php(118): FireflyIII\\Support\\Amount->getDefaultCurrency()
#2 /var/www/firefly-iii/app/Http/Middleware/Range.php(55): FireflyIII\\Http\\Middleware\\Range->configureView()
#3 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): FireflyIII\\Http\\Middleware\\Range->handle()
#4 /var/www/firefly-iii/vendor/jc5/google2fa-laravel/src/Middleware.php(29): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#5 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): PragmaRX\\Google2FALaravel\\Middleware->handle()
#6 /var/www/firefly-iii/app/Http/Middleware/Authenticate.php(75): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#7 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): FireflyIII\\Http\\Middleware\\Authenticate->handle()
#8 /var/www/firefly-iii/vendor/laravel/passport/src/Http/Middleware/CreateFreshApiToken.php(50): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#9 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Laravel\\Passport\\Http\\Middleware\\CreateFreshApiToken->handle()
#10 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Session/Middleware/AuthenticateSession.php(58): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#11 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Session\\Middleware\\AuthenticateSession->handle()
#12 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(78): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#13 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle()
#14 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#15 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle()
#16 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(121): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#17 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(64): Illuminate\\Session\\Middleware\\StartSession->handleStatefulRequest()
#18 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Session\\Middleware\\StartSession->handle()
#19 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#20 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle()
#21 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(67): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#22 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle()
#23 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#24 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Routing/Router.php(697): Illuminate\\Pipeline\\Pipeline->then()
#25 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Routing/Router.php(672): Illuminate\\Routing\\Router->runRouteWithinStack()
#26 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Routing/Router.php(636): Illuminate\\Routing\\Router->runRoute()
#27 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Routing/Router.php(625): Illuminate\\Routing\\Router->dispatchToRoute()
#28 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(166): Illuminate\\Routing\\Router->dispatch()
#29 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}()
#30 /var/www/firefly-iii/app/Http/Middleware/InstallationId.php(54): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#31 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): FireflyIII\\Http\\Middleware\\InstallationId->handle()
#32 /var/www/firefly-iii/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#33 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Fideloper\\Proxy\\TrustProxies->handle()
#34 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#35 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.php(31): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#36 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\ConvertEmptyStringsToNull->handle()
#37 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#38 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php(40): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#39 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\TrimStrings->handle()
#40 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#41 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle()
#42 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(86): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#43 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance->handle()
#44 /var/www/firefly-iii/app/Http/Middleware/SecureHeaders.php(51): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#45 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): FireflyIII\\Http\\Middleware\\SecureHeaders->handle()
#46 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#47 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(141): Illuminate\\Pipeline\\Pipeline->then()
#48 /var/www/firefly-iii/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(110): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter()
#49 /var/www/firefly-iii/public/index.php(76): Illuminate\\Foundation\\Http\\Kernel->handle()
#50 {main}
"} 

```
OS: Ubuntu 18.04
PHP: 7.4.22
Postgresql: 13 (from offical repository)
nginx: 1.14
SSL from Let's Encrypt

**Comment by JC5** [comment]
This happens when the migrations haven't run. Check out the installation guide.

**Comment by winvan** [comment]
```
php artisan migrate:refresh --seed
php artisan firefly-iii:upgrade-database
php artisan passport:install
```
i do this several times, but no results

**Comment by winvan** [comment]
table transaction_currencies is not empty:
```
select * from transaction_currencies;
 id |     created_at      |     updated_at      | deleted_at | code |        name        | symbol | decimal_places | enabled 
----+---------------------+---------------------+------------+------+--------------------+--------+----------------+---------
  1 | 2021-08-15 23:36:18 | 2021-08-15 23:36:18 |            | HUF  | Hungarian forint   | Ft     |              2 | f
  2 | 2021-08-15 23:36:18 | 2021-08-15 23:36:18 |            | GBP  | British Pound      | �      |              2 | f
  3 | 2021-08-15 23:36:18 | 2021-08-15 23:36:18 |            | USD  | US Dollar          | $      |              2 | f
  4 | 2021-08-15 23:36:18 | 2021-08-15 23:36:18 |            | BRL  | Brazilian real     | R$     |              2 | f
  5 | 2021-08-15 23:36:18 | 2021-08-15 23:36:18 |            | CAD  | Canadian dollar    | C$     |              2 | f
  6 | 2021-08-15 23:36:18 | 2021-08-15 23:36:18 |            | IDR  | Indonesian rupiah  | Rp     |              2 | f
  7 | 2021-08-15 23:36:18 | 2021-08-15 23:36:18 |            | AUD  | Australian dollar  | A$     |              2 | f
  8 | 2021-08-15 23:36:18 | 2021-08-15 23:36:18 |            | NZD  | New Zealand dollar | NZ$    |              2 | f
  9 | 2021-08-15 23:36:18 | 2021-08-15 23:36:18 |            | EGP  | Egyptian pound     | E�     |              2 | f
 10 | 2021-08-15 23:36:18 | 2021-08-15 23:36:18 |            | MAD  | Moroccan dirham    | DH     |              2 | f
 11 | 2021-08-15 23:36:18 | 2021-08-15 23:36:18 |            | ZAR  | South African rand | R      |              2 | f
 12 | 2021-08-15 23:36:18 | 2021-08-15 23:36:18 |            | JPY  | Japanese yen       | �      |              0 | f
 13 | 2021-08-15 23:36:18 | 2021-08-15 23:36:18 |            | RMB  | Chinese yuan       | �      |              2 | f
 14 | 2021-08-15 23:36:18 | 2021-08-15 23:36:18 |            | CHF  | Swiss franc        | CHF    |              2 | f
 15 | 2021-08-15 23:36:18 | 2021-08-15 23:36:18 |            | HRK  | Croatian kuna      | kn     |              2 | f
(15 rows)
```
