### ISSUE TITLE
Unable to create the cache directory (/var/www/html/storage/framework/views/twig/fb)

### ISSUE THREAD

**Issue by prathikvel** [firefly-iii/firefly-iii#4996]
I am running Firefly III version 5.5.13 on Docker.

**Description**
Recently, I had to reset my server. To transfer Firefly III to my new server installation, I decided to copy my old Firefly III files to a flash drive and then paste them to my new server installation.

It was working fine for the first few days. When I opened Firefly III today, however, I noticed that my net worth and some of the graphs were missing. I went to create a transaction, and the installation broke.

I enabled debug information and got an error with the description: "Unable to create the cache directory (\/var\/www\/html\/storage\/framework\/views\/twig\/fb)."

I'm not really sure what's going on. I looked through the issues on GitHub and found that there were [issues](https://github.com/firefly-iii/firefly-iii/issues/3456) in earlier versions of Firefly III with cache. I tried those steps, to no avail. I also tried [this](https://github.com/firefly-iii/firefly-iii/issues/1243) and [this](https://github.com/firefly-iii/firefly-iii/issues/1235), but nothing fixed the issue. I also checked the permissions of the files in my Firefly III container. They seem to be correctly owned by `www-data`. I'll add all the information I have in the extra information section.

I even recreated my Firefly III container several times, but nothing fixed. As far as I know, my database and uploads are the only persistent information when recreating my container. I'm not sure how my database or uploads could be causing this issue. I'm really stuck as to what happened.

**Extra info**
OS: Debian Buster
Browser: Firefox
Reverse Proxy: Nginx

Docker Compose
```
version: "3.7"

services:
  db:
    image: mariadb
    restart: unless-stopped
    volumes:
      - ./data/db:/var/lib/mysql
    env_file: ./env/db.env

  app:
    image: fireflyiii/core
    restart: unless-stopped
    ports: [3080:8080]
    volumes:
      - ./data/fireflyiii:/var/www/html/storage/upload
    env_file: ./env/fireflyiii.env
    depends_on: [db]
```

Docker Log
```
Now in entrypoint.sh for Firefly III
Entrypoint script version is 1.0.17 (2021-06-11)
Running as 'root' in group 'root'.
Current working dir is '/var/www/html'
Now parsing _FILE variables.
done!
Touch DB file (if SQLite)...
Will not download LDAP packages.
Dump auto load...
Generating optimized autoload files
composer/package-versions-deprecated: Generating version class...
composer/package-versions-deprecated: ...done generating version class
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
Generated optimized autoload files containing 5268 classes
Discover packages...
Discovered Package: diglactic/laravel-breadcrumbs
Discovered Package: fideloper/proxy
Discovered Package: jc5/google2fa-laravel
Discovered Package: laravel/passport
Discovered Package: laravel/ui
Discovered Package: laravelcollective/html
Discovered Package: nesbot/carbon
Discovered Package: rcrowe/twigbridge
Package manifest generated successfully.
Current working dir is '/var/www/html'
Wait for the database.
wait-for-it.sh: waiting 60 seconds for db:3306
wait-for-it.sh: db:3306 is available after 0 seconds
DB is up. Time to execute artisan commands.
Wait another 5 seconds in case the DB needs to boot.
Done waiting for the DB to boot.
Current working dir is '/var/www/html'
Run various artisan commands...
Running migration commands...
Database "firefly" exists.
Nothing to migrate.
Seeding: Database\Seeders\AccountTypeSeeder
Seeded:  Database\Seeders\AccountTypeSeeder (23.59ms)
Seeding: Database\Seeders\TransactionCurrencySeeder
Seeded:  Database\Seeders\TransactionCurrencySeeder (23.08ms)
Seeding: Database\Seeders\TransactionTypeSeeder
Seeded:  Database\Seeders\TransactionTypeSeeder (4.91ms)
Seeding: Database\Seeders\PermissionSeeder
Seeded:  Database\Seeders\PermissionSeeder (2.42ms)
Seeding: Database\Seeders\LinkTypeSeeder
Seeded:  Database\Seeders\LinkTypeSeeder (4.06ms)
Seeding: Database\Seeders\ConfigSeeder
[2021-08-16 20:46:10] local.WARNING: Database entry exists. Update to latest version (16)  
Seeded:  Database\Seeders\ConfigSeeder (7.90ms)
Database seeding completed successfully.
Going to decrypt the database.
No decryption required for table "accounts".
No decryption required for table "attachments".
No decryption required for table "bills".
No decryption required for table "budgets".
No decryption required for table "categories".
No decryption required for table "piggy_banks".
No decryption required for table "preferences".
No decryption required for table "tags".
No decryption required for table "transaction_journals".
No decryption required for table "transactions".
No decryption required for table "journal_links".
Done!
Current working dir is '/var/www/html'
Command executed successfully.
Running upgrade commands...
This command has already been executed.
Database already seems to be migrated.
This command has already been executed.
This command has already been executed.
This command has already been executed.
This command has already been executed.
This command has already been executed.
This command has already been executed.
This command has already been executed.
No incorrectly stored credit card liabilities.
This command has already been executed.
This command has already been executed.
This command has already been executed.
This command has already been executed.
This command has already been executed.
Running verification commands...
All piggy bank events are correct.
Verified the content of 1 piggy bank events in 0.02 seconds.
All link types OK!
Verified link types in 0.01 seconds
All access tokens OK!
Verify access tokens in 0.02 seconds.
All transaction journals have correct bill information.
Verified bills / journals in 0.01 seconds
1 different currencies are currently in use.
All currencies are correctly enabled or disabled.
Verified currencies in 0.04 seconds.
No invalid budget/journal entries.
Verified budget/journals in 0.02 seconds.
Amount integrity OK!
Verified amount integrity in 0.01 seconds
No zero-amount transaction journals.
Verified zero-amount integrity in 0.02 seconds
No orphaned transactions.
No orphaned accounts.
Verified orphans in 0.01 seconds
No uneven transaction journals.
No empty transaction journals.
Verified empty journals in 0 seconds
Verified empty groups in 0.01 seconds
All account types are OK!
Verifying account types took 0.66 seconds
All meta fields are correct.
Renamed meta fields in 0.02 seconds
Going to verify 0 opening balance transactions.
There was nothing to fix in the opening balance transactions.
Verified all transaction group and journal title lengths.
Took 0.02 seconds.
Corrected recurring transactions in 0.02 seconds.
Updated inconsistent transaction groups.
All transaction journals are of the correct transaction type (in 0.08 seconds).
Verifying account preferences took 0.03 seconds
Running report commands...
User #1 (*****@*****.com) has account #11 ("Cash account") which has no transactions.
Report on empty objects finished in 0.02 seconds
Amount integrity OK for user #1
Report on total sum finished in 0.02 seconds
Restored OAuth keys from database.
Generating new OAuth keys...
Encryption keys already exist. Use the --force option to overwrite them.
Personal access client created successfully.
Client ID: **
Client secret: *****
Password grant client created successfully.
Client ID: **
Client secret: *****
Updated version.
+------------------------------------------------------------------------------+
|                                                                              |
| Thank you for installing Firefly III, v5.5.13!                               |
|                                                                              |
|                                                                              |
+------------------------------------------------------------------------------+
Go!
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using ***. Set the 'ServerName' directive globally to suppress this message
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using ***. Set the 'ServerName' directive globally to suppress this message
[Mon Aug 16 20:46:19.648234 2021] [mpm_prefork:notice] [pid 1] AH00163: Apache/2.4.38 (Debian) configured -- resuming normal operations
[Mon Aug 16 20:46:19.648280 2021] [core:notice] [pid 1] AH00094: Command line: 'apache2 -D FOREGROUND'
[2021-08-16 20:46:45] local.ERROR: Exception is: {"class":"ErrorException","errorMessage":"file_put_contents(\/var\/www\/html\/storage\/framework\/cache\/data\/1e\/61\/1e613425200610d3170539bae6fcd5b4e03c359a): Failed to open stream: No such file or directory","time":"Mon, 16 Aug 2021 20:46:45 -0400","file":"\/var\/www\/html\/vendor\/laravel\/framework\/src\/Illuminate\/Filesystem\/Filesystem.php","line":185,"code":0,"version":"5.5.13","url":"https:\/\/*****.com","userAgent":"Mozilla\/5.0 (Macintosh; Intel Mac OS X 10.15; rv:90.0) Gecko\/20100101 Firefox\/90.0","json":true}  
[2021-08-16 20:46:45] local.ERROR: Exception when mailing: Unable to create the cache directory (/var/www/html/storage/framework/views/twig/75).  
[2021-08-16 20:46:45] local.ERROR: file_put_contents(/var/www/html/storage/framework/cache/data/1e/61/1e613425200610d3170539bae6fcd5b4e03c359a): Failed to open stream: No such file or directory {"exception":"[object] (ErrorException(code: 0): file_put_contents(/var/www/html/storage/framework/cache/data/1e/61/1e613425200610d3170539bae6fcd5b4e03c359a): Failed to open stream: No such file or directory at /var/www/html/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php:185)
[stacktrace]
#0 [internal function]: Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError()
#1 /var/www/html/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php(185): file_put_contents()
#2 /var/www/html/vendor/laravel/framework/src/Illuminate/Cache/FileStore.php(77): Illuminate\\Filesystem\\Filesystem->put()
#3 /var/www/html/vendor/laravel/framework/src/Illuminate/Cache/FileStore.php(194): Illuminate\\Cache\\FileStore->put()
#4 /var/www/html/vendor/laravel/framework/src/Illuminate/Cache/Repository.php(357): Illuminate\\Cache\\FileStore->forever()
#5 /var/www/html/vendor/laravel/framework/src/Illuminate/Cache/CacheManager.php(418): Illuminate\\Cache\\Repository->forever()
#6 /var/www/html/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(261): Illuminate\\Cache\\CacheManager->__call()
#7 /var/www/html/app/Support/FireflyConfig.php(87): Illuminate\\Support\\Facades\\Facade::__callStatic()
#8 /var/www/html/app/Support/System/GeneratesInstallationId.php(42): FireflyIII\\Support\\FireflyConfig->get()
#9 /var/www/html/app/Http/Middleware/InstallationId.php(52): FireflyIII\\Http\\Middleware\\InstallationId->generateInstallationId()
#10 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): FireflyIII\\Http\\Middleware\\InstallationId->handle()
#11 /var/www/html/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#12 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Fideloper\\Proxy\\TrustProxies->handle()
#13 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#14 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.php(31): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#15 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\ConvertEmptyStringsToNull->handle()
#16 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#17 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php(40): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#18 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\TrimStrings->handle()
#19 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#20 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle()
#21 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(86): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#22 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance->handle()
#23 /var/www/html/app/Http/Middleware/SecureHeaders.php(51): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#24 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): FireflyIII\\Http\\Middleware\\SecureHeaders->handle()
#25 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#26 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(141): Illuminate\\Pipeline\\Pipeline->then()
#27 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(110): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter()
#28 /var/www/html/public/index.php(76): Illuminate\\Foundation\\Http\\Kernel->handle()
#29 {main}
"} 
[2021-08-16 20:46:45] local.ERROR: Exception is: {"class":"RuntimeException","errorMessage":"Unable to create the cache directory (\/var\/www\/html\/storage\/framework\/views\/twig\/fb).","time":"Mon, 16 Aug 2021 20:46:45 -0400","file":"\/var\/www\/html\/vendor\/twig\/twig\/src\/Cache\/FilesystemCache.php","line":57,"code":0,"version":"5.5.13","url":"https:\/\/*****.com","userAgent":"Mozilla\/5.0 (Macintosh; Intel Mac OS X 10.15; rv:90.0) Gecko\/20100101 Firefox\/90.0","json":true}  
[2021-08-16 20:46:45] local.ERROR: Exception when mailing: Unable to create the cache directory (/var/www/html/storage/framework/views/twig/75).  
[2021-08-16 20:46:45] local.ERROR: Unable to create the cache directory (/var/www/html/storage/framework/views/twig/fb). {"exception":"[object] (RuntimeException(code: 0): Unable to create the cache directory (/var/www/html/storage/framework/views/twig/fb). at /var/www/html/vendor/twig/twig/src/Cache/FilesystemCache.php:57)
[stacktrace]
#0 /var/www/html/vendor/twig/twig/src/Environment.php(409): Twig\\Cache\\FilesystemCache->write()
#1 /var/www/html/vendor/twig/twig/src/Environment.php(381): Twig\\Environment->loadClass()
#2 /var/www/html/vendor/rcrowe/twigbridge/src/Bridge.php(75): Twig\\Environment->loadTemplate()
#3 /var/www/html/vendor/rcrowe/twigbridge/src/Engine/Compiler.php(99): TwigBridge\\Bridge->loadTemplate()
#4 /var/www/html/vendor/rcrowe/twigbridge/src/Engine/Twig.php(92): TwigBridge\\Engine\\Compiler->load()
#5 /var/www/html/vendor/laravel/framework/src/Illuminate/View/View.php(139): TwigBridge\\Engine\\Twig->get()
#6 /var/www/html/vendor/laravel/framework/src/Illuminate/View/View.php(122): Illuminate\\View\\View->getContents()
#7 /var/www/html/vendor/laravel/framework/src/Illuminate/View/View.php(91): Illuminate\\View\\View->renderContents()
#8 /var/www/html/vendor/laravel/framework/src/Illuminate/Http/Response.php(69): Illuminate\\View\\View->render()
#9 /var/www/html/vendor/laravel/framework/src/Illuminate/Http/Response.php(35): Illuminate\\Http\\Response->setContent()
#10 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/ResponseFactory.php(55): Illuminate\\Http\\Response->__construct()
#11 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/ResponseFactory.php(85): Illuminate\\Routing\\ResponseFactory->make()
#12 /var/www/html/app/Exceptions/Handler.php(121): Illuminate\\Routing\\ResponseFactory->view()
#13 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(51): FireflyIII\\Exceptions\\Handler->render()
#14 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(172): Illuminate\\Routing\\Pipeline->handleException()
#15 /var/www/html/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#16 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Fideloper\\Proxy\\TrustProxies->handle()
#17 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#18 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.php(31): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#19 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\ConvertEmptyStringsToNull->handle()
#20 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#21 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php(40): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#22 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\TrimStrings->handle()
#23 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#24 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle()
#25 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(86): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#26 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance->handle()
#27 /var/www/html/app/Http/Middleware/SecureHeaders.php(51): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#28 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): FireflyIII\\Http\\Middleware\\SecureHeaders->handle()
#29 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#30 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(141): Illuminate\\Pipeline\\Pipeline->then()
#31 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(110): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter()
#32 /var/www/html/public/index.php(76): Illuminate\\Foundation\\Http\\Kernel->handle()
#33 {main}
"} 
***** - - [16/Aug/2021:20:46:45 -0400] "GET / HTTP/1.0" 500 246627 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:90.0) Gecko/20100101 Firefox/90.0"
```

File Permissions
```
*****@*****:~/fireflyiii$ docker exec -it fireflyiii_app_1 ls -l /var/www/html/storage
total 68
drwxrwxr-x 1 www-data www-data 4096 Jul 25 13:49 app
drwxrwxr-x 1 www-data www-data 4096 Jul 25 13:49 build
drwxrwxr-x 1 www-data www-data 4096 Jul 25 13:49 database
drwxrwxr-x 1 www-data www-data 4096 Jul 25 13:49 debugbar
drwxrwxr-x 1 www-data www-data 4096 Jul 25 13:49 export
drwxrwxr-x 1 www-data www-data 4096 Jul 25 13:49 framework
drwxrwxr-x 1 www-data www-data 4096 Aug 16 21:30 logs
-rwxrwxr-x 1 www-data www-data 3292 Aug 16 21:29 oauth-private.key
-rwxrwxr-x 1 www-data www-data  812 Aug 16 21:29 oauth-public.key
drwxrwxr-x 2 www-data www-data 4096 Aug 16 20:07 upload
*****@*****:~/fireflyiii$ docker exec -it fireflyiii_app_1 ls -l /var/www/html/storage/framework/cache
total 8
drwxrwxr-x 1 www-data www-data 4096 Aug 16 21:30 data
```

Nginx (not sure if it's relevant)
```
server {
    listen 80;
    listen [::]:80;
    server_name *****.com;
    server_tokens off;

    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;
    server_name *****.com;
    server_tokens off;

    ssl_certificate /etc/letsencrypt/live/*****.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/*****.com/privkey.pem;
    ssl_session_timeout 1d;
    ssl_session_cache shared:MozSSL:10m;  # about 40000 sessions
    ssl_session_tickets off;

    # modern configuration
    ssl_protocols TLSv1.3;
    ssl_prefer_server_ciphers off;

    # HSTS (ngx_http_headers_module is required) (63072000 seconds)
    add_header Strict-Transport-Security "max-age=63072000" always;

    # OCSP stapling
    ssl_stapling on;
    ssl_stapling_verify on;

    # verify chain of trust of OCSP response using Root CA and Intermediate certs
    ssl_trusted_certificate /etc/letsencrypt/live/*****.com/chain.pem

    client_max_body_size 128M;

    location / {
        proxy_pass http://127.0.0.1:3080;
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-Server $host;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $host;
    }
}
```

**Bonus points**
- [x] I have read the FAQ at https://bit.ly/FF3-FAQ
- [ ] I added a screenshot
- [x] I added log files 
- [ ] I was able to replicate the issue on the demo site.

**Comment by JC5** [comment]
https://docs.firefly-iii.org/firefly-iii/faq/self_hosted/#unable-to-write-to-cache-directory

**Comment by prathikvel** [comment]
I followed the FAQ earlier, but it didn't fix the issue for me. As per your suggestion, however, I tried it again.

I tried:
```
*****@*****:~$ docker exec -it fireflyiii_app_1 chown -R www-data:www-data /var/www/firefly-iii/storage
chown: cannot access '/var/www/firefly-iii/storage': No such file or directory
```

I presume the correct folder was supposed to be "html", so I tried:
```
*****@*****:~$ docker exec -it fireflyiii_app_1 chown -R www-data:www-data /var/www/html/storage
```

Neither of those fixed the issue. It still says "Unable to create the cache directory (/var/www/html/storage/framework/views/twig/fb)" when I visit my instance of Firefly III.

I also tried to emulate the self-hosting troubleshooting in Docker:
```
*****@*****:~$ docker exec -it fireflyiii_app_1 chmod -R 775 /var/www/html
```

This also didn't fix any issue. I'm still lost as to what to do. Thanks for your quick response and please let me know if there is anything else I can do or any other information I can provide.
