### ISSUE TITLE
HTTP 500 when creating Personal Access Token or OAuth Client

### ISSUE THREAD

**Issue by FieldofClay** [firefly-iii/firefly-iii#5042]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

When attempting to create a new Personal Access Token or OAuth Client token, Firefly-iii throws a HTTP 500 and does not provide the details of the token.

### Expected behaviour

Upon clicking create, the new token should appear. 

### Actual behaviour

Upon clicking create, nothing happens. Checking devtools indicates /oauth/personal-access-tokens threw a HTTP 500.

### Steps to reproduce

1. Profile
2. OAuth
3. Create new token | Create New Client
4. Fill in form
5. Click create

### Debug information

Debug information generated at 2021-09-04 15:16:03 Australia/Sydney for Firefly III version **5.5.13**.

| Scope | Version |
| --- | --- |
| Firefly III | 5.5.13 |
| Firefly III API | 1.5.2 |
| PHP | 8.0.8 |
| Host | Linux |

| System info | Value |
| --- | --- |
| Installation ID | 467bf9b4-f563-4166-80ba-f31191b08d6f |
| Using docker? | true |
| Telemetry | false |
| Layout |  |
| System TZ | Australia/Sydney |
| Browser TZ | Australia/Sydney |
| App environment | local |
| App debug mode | true |
| App cache driver | file |
| App logging | info, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Interface | apache2handler |
| Default language | en_US |
| Default locale | equal |
| BCscale | 24 |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | mysql |
| DB version | 16 (exp. 16) |
| Login provider | ldap  |
| Trusted proxies (.env) | ** |

| User info | Value |
| --- | --- |
| Session start | 2021-09-01 00:00:00 |
| Session end | 2021-09-30 23:59:59 |
| Session first | 2020-01-27 00:00:00 |
| User ID | 1 |
| User language | en_US |
| User locale | en_US |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| User agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:91.0) Gecko/20100101 Firefox/91.0 |

### Additional info

I am using the docker container behind an nginx reverse proxy and mariadb. LDAP is configured, but not used. AUTHENTICATION_GUARD is set to remote_user_guard.

Output of debug logging:
```

[2021-09-04 15:08:58] local.ERROR: Exception is: {"class":"ErrorException","errorMessage":"Array to string conversion","time":"Sat, 04 Sep 2021 15:08:58 +1000","file":"\/var\/www\/html\/app\/Handlers\/Events\/APIEventHandler.php","line":68,"code":0,"version":"5.5.13","url":"https:\/\/my.server.domain\/oauth\/personal-access-tokens","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64; rv:91.0) Gecko\/20100101 Firefox\/91.0","json":true}  
[2021-09-04 15:08:58] local.ERROR: Exception when mailing: Address in mailbox given [] does not comply with RFC 2822, 3.6.2.  
[2021-09-04 15:08:58] local.ERROR: Array to string conversion {"userId":{"FireflyIII\\User":{"id":1,"objectguid":null,"created_at":"2020-04-30T16:41:49.000000Z","updated_at":"2020-04-30T16:44:59.000000Z","email":"user@my.server.domain","reset":null,"blocked":false,"blocked_code":null,"mfa_secret":null}},"exception":"[object] (ErrorException(code: 0): Array to string conversion at /var/www/html/app/Handlers/Events/APIEventHandler.php:68)
2021-09-04 15:08:58.977	[stacktrace]
2021-09-04 15:08:58.977	#0 [internal function]: Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError()
2021-09-04 15:08:58.977	#1 /var/www/html/app/Handlers/Events/APIEventHandler.php(68): sprintf()
2021-09-04 15:08:58.977	#2 /var/www/html/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(412): FireflyIII\\Handlers\\Events\\APIEventHandler->accessTokenCreated()
2021-09-04 15:08:58.977	#3 /var/www/html/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(237): Illuminate\\Events\\Dispatcher->Illuminate\\Events\\{closure}()
2021-09-04 15:08:58.977	#4 /var/www/html/vendor/laravel/passport/src/Bridge/AccessTokenRepository.php(71): Illuminate\\Events\\Dispatcher->dispatch()
2021-09-04 15:08:58.977	#5 /var/www/html/vendor/league/oauth2-server/src/Grant/AbstractGrant.php(442): Laravel\\Passport\\Bridge\\AccessTokenRepository->persistNewAccessToken()
2021-09-04 15:08:58.977	#6 /var/www/html/vendor/laravel/passport/src/Bridge/PersonalAccessGrant.php(29): League\\OAuth2\\Server\\Grant\\AbstractGrant->issueAccessToken()
2021-09-04 15:08:58.977	#7 /var/www/html/vendor/league/oauth2-server/src/AuthorizationServer.php(198): Laravel\\Passport\\Bridge\\PersonalAccessGrant->respondToAccessTokenRequest()
2021-09-04 15:08:58.977	#8 /var/www/html/vendor/laravel/passport/src/PersonalAccessTokenFactory.php(119): League\\OAuth2\\Server\\AuthorizationServer->respondToAccessTokenRequest()
2021-09-04 15:08:58.977	#9 /var/www/html/vendor/laravel/passport/src/PersonalAccessTokenFactory.php(74): Laravel\\Passport\\PersonalAccessTokenFactory->dispatchRequestToAuthorizationServer()
2021-09-04 15:08:58.977	#10 /var/www/html/vendor/laravel/passport/src/HasApiTokens.php(67): Laravel\\Passport\\PersonalAccessTokenFactory->make()
2021-09-04 15:08:58.977	#11 /var/www/html/vendor/laravel/passport/src/Http/Controllers/PersonalAccessTokenController.php(69): FireflyIII\\User->createToken()
2021-09-04 15:08:58.977	#12 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(48): Laravel\\Passport\\Http\\Controllers\\PersonalAccessTokenController->store()
2021-09-04 15:08:58.977	#13 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Route.php(254): Illuminate\\Routing\\ControllerDispatcher->dispatch()
2021-09-04 15:08:58.977	#14 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Route.php(197): Illuminate\\Routing\\Route->runController()
2021-09-04 15:08:58.977	#15 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(695): Illuminate\\Routing\\Route->run()
2021-09-04 15:08:58.977	#16 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}()
2021-09-04 15:08:58.977	#17 /var/www/html/app/Http/Middleware/Authenticate.php(75): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
2021-09-04 15:08:58.977	#18 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): FireflyIII\\Http\\Middleware\\Authenticate->handle()
2021-09-04 15:08:58.977	#19 /var/www/html/vendor/laravel/passport/src/Http/Middleware/CreateFreshApiToken.php(50): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
2021-09-04 15:08:58.977	#20 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Laravel\\Passport\\Http\\Middleware\\CreateFreshApiToken->handle()
2021-09-04 15:08:58.977	#21 /var/www/html/vendor/laravel/framework/src/Illuminate/Session/Middleware/AuthenticateSession.php(39): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
2021-09-04 15:08:58.977	#22 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Session\\Middleware\\AuthenticateSession->handle()
2021-09-04 15:08:58.977	#23 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(78): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
2021-09-04 15:08:58.977	#24 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle()
2021-09-04 15:08:58.977	#25 /var/www/html/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
2021-09-04 15:08:58.977	#26 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle()
2021-09-04 15:08:58.977	#27 /var/www/html/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(121): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
2021-09-04 15:08:58.977	#28 /var/www/html/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(64): Illuminate\\Session\\Middleware\\StartSession->handleStatefulRequest()
2021-09-04 15:08:58.977	#29 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Session\\Middleware\\StartSession->handle()
2021-09-04 15:08:58.977	#30 /var/www/html/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
2021-09-04 15:08:58.977	#31 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle()
2021-09-04 15:08:58.977	#32 /var/www/html/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(67): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
2021-09-04 15:08:58.977	#33 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle()
2021-09-04 15:08:58.977	#34 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
2021-09-04 15:08:58.977	#35 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(697): Illuminate\\Pipeline\\Pipeline->then()
2021-09-04 15:08:58.977	#36 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(672): Illuminate\\Routing\\Router->runRouteWithinStack()
2021-09-04 15:08:58.977	#37 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(636): Illuminate\\Routing\\Router->runRoute()
2021-09-04 15:08:58.977	#38 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(625): Illuminate\\Routing\\Router->dispatchToRoute()
2021-09-04 15:08:58.977	#39 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(166): Illuminate\\Routing\\Router->dispatch()
2021-09-04 15:08:58.977	#40 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}()
2021-09-04 15:08:58.977	#41 /var/www/html/app/Http/Middleware/InstallationId.php(54): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
2021-09-04 15:08:58.977	#42 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): FireflyIII\\Http\\Middleware\\InstallationId->handle()
2021-09-04 15:08:58.977	#43 /var/www/html/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
2021-09-04 15:08:58.977	#44 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Fideloper\\Proxy\\TrustProxies->handle()
2021-09-04 15:08:58.977	#45 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
2021-09-04 15:08:58.977	#46 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.php(31): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
2021-09-04 15:08:58.977	#47 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\ConvertEmptyStringsToNull->handle()
2021-09-04 15:08:58.977	#48 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
2021-09-04 15:08:58.977	#49 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php(40): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
2021-09-04 15:08:58.977	#50 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\TrimStrings->handle()
2021-09-04 15:08:58.977	#51 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
2021-09-04 15:08:58.977	#52 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle()
2021-09-04 15:08:58.977	#53 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(86): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
2021-09-04 15:08:58.977	#54 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance->handle()
2021-09-04 15:08:58.977	#55 /var/www/html/app/Http/Middleware/SecureHeaders.php(51): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
2021-09-04 15:08:58.977	#56 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): FireflyIII\\Http\\Middleware\\SecureHeaders->handle()
2021-09-04 15:08:58.977	#57 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
2021-09-04 15:08:58.977	#58 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(141): Illuminate\\Pipeline\\Pipeline->then()
2021-09-04 15:08:58.977	#59 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(110): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter()
2021-09-04 15:08:58.977	#60 /var/www/html/public/index.php(76): Illuminate\\Foundation\\Http\\Kernel->handle()
2021-09-04 15:08:58.977	#61 {main}
2021-09-04 15:08:58.977	"} 
2021-09-04 15:08:58.980	192.168.XXX.XXX - - [04/Sep/2021:15:08:58 +1000] "POST /oauth/personal-access-tokens HTTP/1.1" 500 14235 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:91.0) Gecko/20100101 Firefox/91.0"
```

**Comment by JC5** [comment]
Thanks for letting me know. That's a bug! I'll pick it up for the next release.
