### ISSUE TITLE
Nordigen importer: Cannot assign array to property remittanceInformationStructuredArray of type string

### ISSUE THREAD

**Issue by rasmus-saks** [firefly-iii/firefly-iii#5267]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

When importing transactions from my local bank account using the Nordigen importer, the job appears to get stuck and the following error message is displayed in the console:
```
[2021-11-10 17:42:48] production.ERROR: Cannot assign array to property App\Services\Nordigen\Model\Transaction::$remittanceInformationStructuredArray of type string {"exception":"[object] (TypeError(code: 0): Cannot assign array to property App\\Services\\Nordigen\\Model\\Transaction::$remittanceInformationStructuredArray of type string at /var/www/html/app/Services/Nordigen/Model/Transaction.php:108)
[stacktrace]
#0 /var/www/html/app/Services/Nordigen/Response/GetTransactionsResponse.php(46): App\\Services\\Nordigen\\Model\\Transaction::fromArray()
#1 /var/www/html/app/Services/Nordigen/Request/GetTransactionsRequest.php(77): App\\Services\\Nordigen\\Response\\GetTransactionsResponse->__construct()
#2 /var/www/html/app/Services/Nordigen/Download/TransactionProcessor.php(72): App\\Services\\Nordigen\\Request\\GetTransactionsRequest->get()
#3 /var/www/html/app/Services/Nordigen/Download/RoutineManager.php(141): App\\Services\\Nordigen\\Download\\TransactionProcessor->download()
#4 /var/www/html/app/Http/Controllers/Import/DownloadController.php(107): App\\Services\\Nordigen\\Download\\RoutineManager->start()
#5 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): App\\Http\\Controllers\\Import\\DownloadController->start()
#6 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\\Routing\\Controller->callAction()
#7 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Route.php(262): Illuminate\\Routing\\ControllerDispatcher->dispatch()
#8 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Route.php(205): Illuminate\\Routing\\Route->runController()
#9 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(695): Illuminate\\Routing\\Route->run()
#10 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}()
#11 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(50): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#12 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle()
#13 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(78): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#14 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle()
#15 /var/www/html/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#16 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle()
#17 /var/www/html/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(121): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#18 /var/www/html/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(64): Illuminate\\Session\\Middleware\\StartSession->handleStatefulRequest()
#19 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Session\\Middleware\\StartSession->handle()
#20 /var/www/html/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#21 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle()
#22 /var/www/html/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(67): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#23 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle()
#24 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#25 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(697): Illuminate\\Pipeline\\Pipeline->then()
#26 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(672): Illuminate\\Routing\\Router->runRouteWithinStack()
#27 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(636): Illuminate\\Routing\\Router->runRoute()
#28 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(625): Illuminate\\Routing\\Router->dispatchToRoute()
#29 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(167): Illuminate\\Routing\\Router->dispatch()
#30 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}()
#31 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#32 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.php(31): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#33 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\ConvertEmptyStringsToNull->handle()
#34 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
```

### Expected behaviour

The import should complete successfully

### Debug information

Debug information generated at 2021-11-10 18:08:26 Europe/Tallinn for Firefly III version **5.6.2**.

| Scope | Version |
| --- | --- |
| Firefly III | 5.6.2 |
| Firefly III API | 1.5.4 |
| PHP | 8.0.10 |
| Host | Linux |

| System info | Value |
| --- | --- |
| Installation ID | d9af8649-7694-4e5c-a624-623520e587b6 |
| Using docker? | true |
| Telemetry | false |
| Layout |  |
| System TZ | Europe/Tallinn |
| Browser TZ | Europe/Tallinn |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | info, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Interface | apache2handler |
| Default language | en_US |
| Default locale | equal |
| BCscale | 24 |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | mysql |
| DB version | 18 (exp. 18) |
| Login provider | eloquent  |
| Trusted proxies (.env) | ** |

| User info | Value |
| --- | --- |
| Session start | 2021-01-01 00:00:00 |
| Session end | 2021-11-10 00:00:00 |
| Session first | 2021-01-01 00:00:00 |
| User ID | 1 |
| User language | en_US |
| User locale | en_US |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| User agent | Mozilla/5.0 (X11; Linux x86_64; rv:94.0) Gecko/20100101 Firefox/94.0 |

### Steps to reproduce

1. Open Nordigen importer page
2. Select bank, connect, select account(s)
3. Start the import job
4. (the job gets stuck infinitely)

### Additional info

Here is an example transaction which includes this `remittanceInformationStructuredArray` property.
```json
{
    "bookingDate": "2021-11-10",
    "creditorAccount": {
        "iban": "XXX"
    },
    "creditorName": "XXX",
    "entryReference": "16365249953619680113",
    "purposeCode": "IVPT",
    "remittanceInformationStructuredArray": [
        "50068190096",
        "SCOR"
    ],
    "remittanceInformationUnstructured": "XXX",
    "transactionAmount": {
        "amount": "-25.0",
        "currency": "EUR"
    },
    "transactionId": "3124563760",
    "valueDate": "2021-11-10"
}
```

**Comment by JC5** [comment]
Nice find, and thanks for the extra information! This will be fixed in the next release :+1:

**Comment by hitokiri8x** [comment]
just runned docker image, :latest still point to 0.2, had to point to :develop for getting fix
