### ISSUE TITLE
Login with ldap failing after upgrade

### ISSUE THREAD

**Issue by mic05** [firefly-iii/firefly-iii#5319]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

I updated my Firefly III docker container from version from 5.5.13 to 5.6.4. I also changed the LDAP env variables. Sadly, I can not login due to a 500 error after clicking login on the login page.
At the login page, I get:
```
FireflyIII\Ldap\AttributeHandler::handle(): Argument #1 ($ldap) must be of type LdapRecord\Models\OpenLDAP\User, LdapRecord\Models\ActiveDirectory\User given, called in /var/www/html/vendor/directorytree/ldaprecord-laravel/src/Import/Hydrators/AttributeHydrator.php on line 18
```
Am I doing something wrong or is this a bug?

### Expected behaviour

After clicking the login button, the user is logged in.

### Debug information

I can't display information here because debug page isn't displayed due to not being logged in.

### Additional info

Here is the log according to the error. I think the entry at 2021-11-24 12:53:03 seems to be the problem but i don't understand why. According to the documentation, I've set everything correctly. My env-variables are:
```
AUTHENTICATION_GUARD=ldap
LDAP_HOST=activedirectory
LDAP_PORT=389
LDAP_TIMEOUT=5
LDAP_SSL=false
LDAP_TLS=false
LDAP_BASE_DN=DC=sub,DC=domain,DC=de  
LDAP_USERNAME=CN=FireflyIII,OU=Orgaunit,OU=Company,DC=sub,DC=domain,DC=de 
LDAP_PASSWORD=strongpassword
LDAP_AUTH_FIELD=userPrincipalName
```
I also tried it with `LDAP_DIALECT=ActiveDirectory` but I got the same error.
Log:
```
2021-11-24 12:53:03] local.INFO: User is trying to login.  

[2021-11-24 12:53:03] local.INFO: LDAP (ldap://activedirectory:389) - Operation: Binding - Username: CN=FireflyIII,OU=Orgaunit,OU=Company,DC=sub,DC=domain,DC=de  

[2021-11-24 12:53:03] local.INFO: LDAP (ldap://activedirectory:389) - Operation: Bound - Username: CN=FireflyIII,OU=Orgaunit,OU=Company,DC=sub,DC=domain,DC=de  

[2021-11-24 12:53:03] local.INFO: LDAP (ldap://activedirectory:389) - Operation: Search - Base DN: DC=sub,DC=domain,DC=de - Filter: (&(objectclass=\74\6f\70)(objectclass=\70\65\72\73\6f\6e)(objectclass=\6f\72\67\61\6e\69\7a\61\74\69\6f\6e\61\6c\70\65\72\73\6f\6e)(objectclass=\75\73\65\72)(userPrincipalName=\6d\62\40\64\65\6c\74\61\6f\66\66\69\63\65\2e\64\65)(!(objectclass=\63\6f\6d\70\75\74\65\72))) - Selected: (objectguid,*) - Time Elapsed: 13.1  

[2021-11-24 12:53:03] local.INFO: User [John Doe] has been successfully discovered for authentication.  

[2021-11-24 12:53:03] local.INFO: Object with name [John Doe] is being synchronized.  

[2021-11-24 12:53:03] local.ERROR: Exception is: {"class":"TypeError","errorMessage":"FireflyIII\\Ldap\\AttributeHandler::handle(): Argument #1 ($ldap) must be of type LdapRecord\\Models\\OpenLDAP\\User, LdapRecord\\Models\\ActiveDirectory\\User given, called in \/var\/www\/html\/vendor\/directorytree\/ldaprecord-laravel\/src\/Import\/Hydrators\/AttributeHydrator.php on line 18","time":"Wed, 24 Nov 2021 12:53:03 +0100","file":"\/var\/www\/html\/app\/Ldap\/AttributeHandler.php","line":39,"code":0,"version":"5.6.4","url":"https:\/\/fireflyiii.somedomain.de\/login","userAgent":"Mozilla\/5.0 (X11; Linux x86_64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/96.0.4664.45 Safari\/537.36","json":true}  

[2021-11-24 12:53:03] local.ERROR: Exception when mailing: Connection could not be established with host  :stream_socket_client(): php_network_getaddresses: getaddrinfo failed: Name or service not known  

[2021-11-24 12:53:03] local.ERROR: FireflyIII\Ldap\AttributeHandler::handle(): Argument #1 ($ldap) must be of type LdapRecord\Models\OpenLDAP\User, LdapRecord\Models\ActiveDirectory\User given, called in /var/www/html/vendor/directorytree/ldaprecord-laravel/src/Import/Hydrators/AttributeHydrator.php on line 18 {"exception":"[object] (TypeError(code: 0): FireflyIII\\Ldap\\AttributeHandler::handle(): Argument #1 ($ldap) must be of type LdapRecord\\Models\\OpenLDAP\\User, LdapRecord\\Models\\ActiveDirectory\\User given, called in /var/www/html/vendor/directorytree/ldaprecord-laravel/src/Import/Hydrators/AttributeHydrator.php on line 18 at /var/www/html/app/Ldap/AttributeHandler.php:39)

[stacktrace]

#0 /var/www/html/vendor/directorytree/ldaprecord-laravel/src/Import/Hydrators/AttributeHydrator.php(18): FireflyIII\\Ldap\\AttributeHandler->handle()

#1 /var/www/html/vendor/directorytree/ldaprecord-laravel/src/Import/EloquentHydrator.php(70): LdapRecord\\Laravel\\Import\\Hydrators\\AttributeHydrator->hydrate()

#2 /var/www/html/vendor/directorytree/ldaprecord-laravel/src/Import/Synchronizer.php(147): LdapRecord\\Laravel\\Import\\EloquentHydrator->hydrate()

#3 /var/www/html/vendor/directorytree/ldaprecord-laravel/src/Import/Synchronizer.php(97): LdapRecord\\Laravel\\Import\\Synchronizer->hydrate()

#4 /var/www/html/vendor/directorytree/ldaprecord-laravel/src/Import/Synchronizer.php(72): LdapRecord\\Laravel\\Import\\Synchronizer->synchronize()

#5 /var/www/html/vendor/directorytree/ldaprecord-laravel/src/Auth/DatabaseUserProvider.php(187): LdapRecord\\Laravel\\Import\\Synchronizer->run()

#6 /var/www/html/vendor/laravel/framework/src/Illuminate/Auth/SessionGuard.php(366): LdapRecord\\Laravel\\Auth\\DatabaseUserProvider->retrieveByCredentials()

#7 /var/www/html/vendor/laravel/ui/auth-backend/AuthenticatesUsers.php(87): Illuminate\\Auth\\SessionGuard->attempt()

#8 /var/www/html/app/Http/Controllers/Auth/LoginController.php(117): FireflyIII\\Http\\Controllers\\Auth\\LoginController->attemptLogin()

#9 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): FireflyIII\\Http\\Controllers\\Auth\\LoginController->login()

#10 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\\Routing\\Controller->callAction()

#11 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Route.php(262): Illuminate\\Routing\\ControllerDispatcher->dispatch()

#12 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Route.php(205): Illuminate\\Routing\\Route->runController()

#13 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(695): Illuminate\\Routing\\Route->run()

#14 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}()

#15 /var/www/html/app/Http/Controllers/Controller.php(112): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()

#16 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): FireflyIII\\Http\\Controllers\\Controller->FireflyIII\\Http\\Controllers\\{closure}()

#17 /var/www/html/app/Http/Middleware/RedirectIfAuthenticated.php(51): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()

#18 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): FireflyIII\\Http\\Middleware\\RedirectIfAuthenticated->handle()

#19 /var/www/html/app/Http/Middleware/Binder.php(78): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()

#20 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): FireflyIII\\Http\\Middleware\\Binder->handle()

#21 /var/www/html/app/Http/Middleware/Installer.php(79): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()

#22 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): FireflyIII\\Http\\Middleware\\Installer->handle()

#23 /var/www/html/vendor/laravel/passport/src/Http/Middleware/CreateFreshApiToken.php(50): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()

#24 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Laravel\\Passport\\Http\\Middleware\\CreateFreshApiToken->handle()

#25 /var/www/html/vendor/laravel/framework/src/Illuminate/Session/Middleware/AuthenticateSession.php(39): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()

#26 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Session\\Middleware\\AuthenticateSession->handle()

#27 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(78): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()

#28 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle()

#29 /var/www/html/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()

#30 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle()

#31 /var/www/html/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(121): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()

#32 /var/www/html/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(64): Illuminate\\Session\\Middleware\\StartSession->handleStatefulRequest()

#33 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Session\\Middleware\\StartSession->handle()

#34 /var/www/html/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()

#35 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle()

#36 /var/www/html/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(67): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()

#37 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle()

#38 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()

#39 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(697): Illuminate\\Pipeline\\Pipeline->then()

#40 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(672): Illuminate\\Routing\\Router->runRouteWithinStack()

#41 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(636): Illuminate\\Routing\\Router->runRoute()

#42 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(625): Illuminate\\Routing\\Router->dispatchToRoute()

#43 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(167): Illuminate\\Routing\\Router->dispatch()

#44 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}()

#45 /var/www/html/app/Http/Middleware/InstallationId.php(52): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()

#46 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): FireflyIII\\Http\\Middleware\\InstallationId->handle()

#47 /var/www/html/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()

#48 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Fideloper\\Proxy\\TrustProxies->handle()

#49 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()

#50 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.php(31): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()

#51 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\ConvertEmptyStringsToNull->handle()

#52 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()

#53 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php(40): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()

#54 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\TrimStrings->handle()

#55 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()

#56 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle()

#57 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(86): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()

#58 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance->handle()

#59 /var/www/html/app/Http/Middleware/SecureHeaders.php(51): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()

#60 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): FireflyIII\\Http\\Middleware\\SecureHeaders->handle()

#61 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()

#62 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(142): Illuminate\\Pipeline\\Pipeline->then()

#63 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(111): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter()

#64 /var/www/html/public/index.php(76): Illuminate\\Foundation\\Http\\Kernel->handle()

#65 {main}

"}
```

**Comment by JC5** [comment]
Thanks for letting me know, I found something similar indeed. Will be fixed!

**Comment by JC5** [comment]
I'm going to assume this is fixed in the new release, but please open a new ticket if it's not.
