### ISSUE TITLE
Data importer: SimpleFIN

### ISSUE THREAD

**Issue by marcusds** [firefly-iii/firefly-iii#5396]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
- [X] My request is not listed as [a very good idea, but unfortunately...](https://docs.firefly-iii.org/firefly-iii/about-firefly-iii/what-its-not/)
- [X] I've used [the search](https://github.com/firefly-iii/firefly-iii/issues?q=is%3Aissue) and this has not been discussed before.

### Description

It would be great to see the Data Importer support SimpleFIN (https://beta-bridge.simplefin.org/), it offers a service similar to Specter or Nordigen, but offers a lot more options. Particularly for NA banks.

### Solution

Another data import option including more banks.

**Comment by JC5** [comment]
Sure, it's on the list 👍

**Comment by pastorjack** [comment]
I would love to have this so I can use Firefly with my bank. https://beta-bridge.simplefin.org/info/developers

From the above actions it seems like you are no longer considering it. Is it still going to be added?

Thanks!

**Comment by JC5** [comment]
If I didn't, the issue would be closed.

**Comment by pastorjack** [comment]
OK! Thanks for your work on this!

**Comment by ghzgod** [comment]
Any updates or any data we can provide to get this implemented?  I'm willing to donate to the cause

**Comment by MFYDev** [comment]
I need this function as well and will hugely appreciate

**Comment by bpmich** [comment]
I switched to actualbudget/actual as it seems development of this feature has stalled. Many users like me are looking for replacements for Intuit Mint. Live bank sync is a non-negotiable feature in that regard. Other projects provide this feature.

**Comment by MFYDev** [comment]
Exactly, same as me, I switched to Actual Budget and it is working so well. Without US bank importer stopped me from using it.

**Comment by alexsalex** [comment]
any update on implementation?

**Comment by JC5** [comment]
If you come across this issue, please be aware there is NO need to reply with "+1" or "me too" or "I need this too" or whatever. Such comments are not helpful, and do not influence [the roadmap](https://roadmap.firefly-iii.org/). Your comment may be :skull: deleted. You can subscribe to this issue to get updates.

**Comment by Normanras** [comment]
Just wanted to say thanks to you, @JC5 for keeping this enhancement open! Appreciate all your hard work on this amazing service.

**Comment by cbrandonmiller** [comment]
@JC5 I recently came across this, and I am very interested in it. I have looked at Actual Budget, but I don't really like the envelope model, I am more interested in just tracking my expenses, which seems like Firefly III will do well. I am in the US, so I am hopeful for SimpleFIN support. I am a software developer, is it something that I can contribute to? I do have some experience with using API calls, as well as some Cold Fusion and C#/.NET development. I can't promise any particular amount of time as I have 3 young kids at home and a full time job, but I would be interested in trying to add support for SimpleFIN (if only for selfish reasons because it would benefit me, and I'm sure others would appreciate it being added).

**Comment by JC5** [comment]
No that's alright, thanks for the offer. It needs integration into the data importer and I've got the basics up and running already. Once that works, I'll release it and I can work on all the edge cases. I have no ETA yet but I've not forgotten this!

**Comment by JC5** [comment]
Hello all,

Please check out the `develop`-tag of the data importer where you will find the first version of the SimpleFIN importer. Built not by me but by user 'skell', who shall receive all our thanks of course.

Bugs and issues can be reported in this issue up until the actual release of the new version. If nothing serious comes up, this will be some time this week.

**Comment by aarondvail** [comment]
do you want bugs/issues reported here in this thread or open a new issue?

**Comment by JC5** [comment]
Since we're still experimenting, feel free to put them here. Once the new release hits I'll ask you to open separate tickets.

**Comment by aarondvail** [comment]
OK.

First it states that CORS login is optional.... but won't let you leave it blank.....
When I use my internal IP (haven't set up the FQDN Proxy yet) I get the following error:

Connection Error: Failed to connect to SimpleFIN: SimpleFIN claim URL exchange failed (403 Forbidden): Forbidden 



Do I need an external (with ssl) FQDN for the CORS?

Oh and for giggles, I tested in both Firefox and Chrome (I discovered a bug on VitaminShoppe.com today, but only in Chrome), and got the same results.... testing with FQDN soon

**Comment by aarondvail** [comment]
UPDATE:

FQDN w/ SSL for CORS is allowing me to connect....

But When I get to the start import, I get:

The conversion could not be started, or failed due to an error. Please check the log files. Sorry about this :( 

Container Logs:
[2025-06-24 04:24:16] production.DEBUG: Now at App\Http\Controllers\Import\ConversionController::status(2GydWkMZaD3TPmMi)  
[2025-06-24 04:24:16] production.DEBUG: Now in startOrFindConversion(2GydWkMZaD3TPmMi)  
[2025-06-24 04:24:16] production.DEBUG: Conversion status is "conv_errored"

**Comment by JC5** [comment]
Without the actual error, I have no idea.

**Comment by aarondvail** [comment]
This was all I could find.... If you could point me to some logs that are meaningful, that might help.

**Comment by JC5** [comment]
Earlier in the run, there may be more. But it's hard to point out for me where exactly.

**Comment by tehniemer** [comment]
I got an error message when I tried an initial import

```
Whoops! 500 :(
Sorry, the Firefly III Data Importer broke down.

Error message
cURL error 28: Operation timed out after 30001 milliseconds with 0 bytes received (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://01C935E0AAA935468D49F75F4D01931C4BFE90102CA53F7893B8C7D654A57D5E:***@beta-bridge.simplefin.org/simplefin/accounts?start-date=946684800&pending=0

More information
The error occurred in /var/www/html/app/Services/SimpleFIN/Request/SimpleFINRequest.php:116.
```

Debug information generated at 2025-06-24 09:01:06 America/Chicago for Firefly III Data Importer version **develop/2025-06-23**.

<table><tr><th colspan="2">System information</th></tr><tr><th>Item</th><th>Value</th></tr><tr><td>Version</td><td>develop/2025-06-23</td></tr><tr><td>System</td><td>PHP 8.4.7, Linux, fpm-fcgi</td></tr></table><table><tr><th colspan="2">App information</th></tr><tr><th>Item</th><th>Value</th></tr><tr><td>Timezone</td><td>America/Chicago, America/Chicago</td></tr><tr><td>Environment</td><td>local</td></tr><tr><td>Debug mode</td><td>false, cache 'file'</td></tr><tr><td>Log level</td><td>debug, stack</td></tr><tr><td>Display errors</td><td>Off, ALL errors</td></tr><tr><td>BCscale</td><td>12</td></tr><tr><td>Trusted proxies</td><td>**</td></tr></table><table><tr><th colspan="2">User information</th></tr><tr><th>Item</th><th>Value</th></tr><tr><td>User agent</td><td>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/137.0.0.0 Safari/537.36 Edg/137.0.0.0</td></tr></table>

I also have the extra info, but it said to not share lightly, so I can provide that another way if needed.

**Comment by JC5** [comment]
Send it to james@firefly-iii.org please :)

**Comment by tehniemer** [comment]
> Send it to [james@firefly-iii.org](mailto:james@firefly-iii.org) please :)

Done!

**Comment by aarondvail** [comment]
I disconnected and went to reconnect and I got the same error (SimpleFINRequest.php:116) as tehniemer.

I didn't send an email to save the duplicate...

**Comment by JC5** [comment]
Timeouts aren't something I can fix, unfortunately.

**Comment by JC5** [comment]
> Connection Error: Failed to connect to SimpleFIN: SimpleFIN claim URL exchange failed (403 Forbidden): Forbidden

Also not something I can fix, the 403 is generated by the other side.

**Comment by aarondvail** [comment]
i think I see what's happening.... SimpleFin is slow to process.... when I create a key and get the error SimpleFin comes back saying it's unclaimed.... after a few minutes that changes.... and I think once it's claimed you can't start over on the Data Importer side....

I'm going to generate a new token and wait 5 minutes to put it into the data importer and see what that does for us....

**Comment by aarondvail** [comment]
I actually waited 7 minutes (the oven wasn't available for me to make lunch right away)....
Everything worked... all the way through....
Almost.... it Imports 764 items and then "stops".... no error other than :

The submission routine has finished 🎉. Errors and messages can be seen below.

found this at the debug screen
App\Http\Controllers\Import\SubmitController::status(submission-LOtSFQmM6gpK)  
[2025-06-24 18:43:31] production.DEBUG: Now in startOrFindJob(submission-LOtSFQmM6gpK)  
[2025-06-24 18:43:31] production.DEBUG: Try to see if file exists for job submission-LOtSFQmM6gpK.  
[2025-06-24 18:43:31] production.DEBUG: Status file exists for job submission-LOtSFQmM6gpK.  
[2025-06-24 18:43:31] production.DEBUG: Status: submission_done  
[2025-06-24 18:43:31] production.DEBUG: Messages: 764, warnings: 0, errors: 0  

and at the home page of Data Importer
under Import from SimpleFIN 

Please set a valid APP_KEY to use the SimpleFIN importer

**Comment by JC5** [comment]
I'm not sure what you're trying to say, sorry.

**Comment by aarondvail** [comment]
OK. I get that sometimes....

Basically I found a workaround for the timeout/403 issue.... create the key in SimpleFIN, wait 5 minutes, then enter the key into Data Importer....

Once there, it appears that I can add my accounts and it will only import 764 records.... and stops there with no way to go anywhere from there. If the button "return to previous screen" is clicked, it will try to reload the 764 records....

Opening up the Data Importer on a new tab/browser will display the "error" Please set a valid APP_KEY to use the SimpleFIN importer. The only button option is "Start Over" (or import CSV)

**Comment by JC5** [comment]
> Once there, it appears that I can add my accounts and it will only import 764 records.... and stops there with no way to go anywhere from there. If the button "return to previous screen" is clicked, it will try to reload the 764 records....

That would make it seem like only 764 records are available.

> Opening up the Data Importer on a new tab/browser will display the "error" Please set a valid APP_KEY to use the SimpleFIN importer. The only button option is "Start Over" (or import CSV)

Do you have a screenshot of this one, please?

**Comment by tehniemer** [comment]
I get the same "error"

![Image](https://github.com/user-attachments/assets/1f7b3ca8-5fa9-45af-982b-33848f844baa)

**Comment by JC5** [comment]
Could you tell me more about how you run the data importer? The APP_KEY is hard coded into the data importer, you literally cannot set an invalid one.

**Comment by JC5** [comment]
What happens when you press "Start over"?

**Comment by tehniemer** [comment]
I just filled out the minimum requirements in the .env file and entered the setup token generated by SimpleFIN as well as the CORS Origin URL when asked in the data importer dialog.

**Comment by tehniemer** [comment]
> What happens when you press "Start over"?

Just that, I have to start over from scratch. Sometimes it connects, but most of the time I get a 403 error.

**Comment by aarondvail** [comment]
I'm in containers.... how do I set up an env file?

**Comment by JC5** [comment]
Try pulling the data importer again. I've changed some code.

**Comment by aarondvail** [comment]
now I can't connect to it, and the container is flagged unhealthy

**Comment by tehniemer** [comment]
> Try pulling the data importer again. I've changed some code.

Got this now

![Image](https://github.com/user-attachments/assets/3ea6f34b-5d60-4023-bc1d-456edff03396)

I have debug logs that I can send, but I'm not totally sure the best way to sanitize them.

**Comment by aarondvail** [comment]
I get the same

**Comment by JC5** [comment]
I would be helped a lot with the actual error, other data can be censored.

**Comment by aarondvail** [comment]
Email sent with what I could find.... It's not much....

Let me know if I need to "reconnect" with a set of instructions.... "click here", "screenshot there", "pat head, rub belly, and chew bubble gum" sorta thing :D

**Comment by JC5** [comment]
I've found this issue, and I fixed some others. I hope without introducing new ones.

- Debug buffer is larger, so more logs should appear in the box.
- Fixed the "APP_KEY" warning.
- Various code cleanup.

Once again, available as `develop` tag (please pull it again).

Let me know, and thanks again for your time.

**Comment by aarondvail** [comment]
email sent with new error

**Comment by JC5** [comment]
Darn, that was sloppy. Sorry, fixed.

**Comment by aarondvail** [comment]
![Image](https://github.com/user-attachments/assets/13c5a144-5f68-44f3-a848-71409311970e)

Debug information generated at 2025-06-25 05:13:49 Europe/Amsterdam for Firefly III Data Importer version **develop/2025-06-24**.

<table><tr><th colspan="2">System information</th></tr><tr><th>Item</th><th>Value</th></tr><tr><td>Version</td><td>develop/2025-06-24</td></tr><tr><td>Build</td><td><span>#</span>1035, base <span>#</span>314</td></tr><tr><td>System</td><td>PHP 8.4.7, Linux, fpm-fcgi</td></tr></table><table><tr><th colspan="2">App information</th></tr><tr><th>Item</th><th>Value</th></tr><tr><td>Timezone</td><td>Europe/Amsterdam, America/New_York</td></tr><tr><td>Environment</td><td>production</td></tr><tr><td>Debug mode</td><td>false, cache 'file'</td></tr><tr><td>Log level</td><td>debug, stack</td></tr><tr><td>Display errors</td><td>Off, ALL errors</td></tr><tr><td>BCscale</td><td>12</td></tr><tr><td>Trusted proxies</td><td></td></tr></table><table><tr><th colspan="2">User information</th></tr><tr><th>Item</th><th>Value</th></tr><tr><td>User agent</td><td>Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:139.0) Gecko/20100101 Firefox/139.0</td></tr></table>


```
[2025-06-25 17:33:15] production.ERROR: isReadyForSimpleFINStep: Cannot handle SimpleFIN step "service-validation" {"exception":"[object] (App\\Exceptions\\ImporterErrorException(code: 0): isReadyForSimpleFINStep: Cannot handle SimpleFIN step \"service-validation\" at /var/www/html/app/Http/Middleware/IsReadyForStep.php:338)
      
[stacktrace]
#0 /var/www/html/app/Http/Middleware/IsReadyForStep.php(78): App\\Http\\Middleware\\ServiceControllerMiddleware->isReadyForSimpleFINStep()
#1 /var/www/html/app/Http/Middleware/IsReadyForStep.php(43): App\\Http\\Middleware\\ServiceControllerMiddleware->isReadyForStep()
#2 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(209): App\\Http\\Middleware\\ServiceControllerMiddleware->handle()
#3 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(51): Illuminate\\Pipeline\\Pipeline->{closure:{closure:Illuminate\\Pipeline\\Pipeline::carry():184}:185}()
#4 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(209): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle()
#5 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(88): Illuminate\\Pipeline\\Pipeline->{closure:{closure:Illuminate\\Pipeline\\Pipeline::carry():184}:185}()
#6 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(209): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle()
#7 /var/www/html/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Pipeline\\Pipeline->{closure:{closure:Illuminate\\Pipeline\\Pipeline::carry():184}:185}()
#8 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(209): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle()
#9 /var/www/html/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(121): Illuminate\\Pipeline\\Pipeline->{closure:{closure:Illuminate\\Pipeline\\Pipeline::carry():184}:185}()
#10 /var/www/html/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(64): Illuminate\\Session\\Middleware\\StartSession->handleStatefulRequest()
#11 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(209): Illuminate\\Session\\Middleware\\StartSession->handle()
#12 /var/www/html/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Pipeline\\Pipeline->{closure:{closure:Illuminate\\Pipeline\\Pipeline::carry():184}:185}()
#13 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(209): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle()
#14 /var/www/html/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(75): Illuminate\\Pipeline\\Pipeline->{closure:{closure:Illuminate\\Pipeline\\Pipeline::carry():184}:185}()
#15 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(209): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle()
#16 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(127): Illuminate\\Pipeline\\Pipeline->{closure:{closure:Illuminate\\Pipeline\\Pipeline::carry():184}:185}()
#17 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(807): Illuminate\\Pipeline\\Pipeline->then()
#18 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(786): Illuminate\\Routing\\Router->runRouteWithinStack()
#19 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(750): Illuminate\\Routing\\Router->runRoute()
#20 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(739): Illuminate\\Routing\\Router->dispatchToRoute()
#21 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(201): Illuminate\\Routing\\Router->dispatch()
#22 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(170): Illuminate\\Foundation\\Http\\Kernel->{closure:Illuminate\\Foundation\\Http\\Kernel::dispatchToRouter():198}()
#23 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->{closure:Illuminate\\Pipeline\\Pipeline::prepareDestination():168}()
#24 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.php(31): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#25 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(209): Illuminate\\Foundation\\Http\\Middleware\\ConvertEmptyStringsToNull->handle()
#26 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->{closure:{closure:Illuminate\\Pipeline\\Pipeline::carry():184}:185}()
#27 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php(51): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#28 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(209): Illuminate\\Foundation\\Http\\Middleware\\TrimStrings->handle()
#29 /var/www/html/vendor/laravel/framework/src/Illuminate/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->{closure:{closure:Illuminate\\Pipeline\\Pipeline::carry():184}:185}()
#30 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(209): Illuminate\\Http\\Middleware\\ValidatePostSize->handle()
#31 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(110): Illuminate\\Pipeline\\Pipeline->{closure:{closure:Illuminate\\Pipeline\\Pipeline::carry():184}:185}()
#32 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(209): Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance->handle()
#33 /var/www/html/vendor/laravel/framework/src/Illuminate/Http/Middleware/HandleCors.php(49): Illuminate\\Pipeline\\Pipeline->{closure:{closure:Illuminate\\Pipeline\\Pipeline::carry():184}:185}()
#34 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(209): Illuminate\\Http\\Middleware\\HandleCors->handle()
#35 /var/www/html/vendor/laravel/framework/src/Illuminate/Http/Middleware/TrustProxies.php(58): Illuminate\\Pipeline\\Pipeline->{closure:{closure:Illuminate\\Pipeline\\Pipeline::carry():184}:185}()
#36 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(209): Illuminate\\Http\\Middleware\\TrustProxies->handle()
#37 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(127): Illuminate\\Pipeline\\Pipeline->{closure:{closure:Illuminate\\Pipeline\\Pipeline::carry():184}:185}()
#38 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(176): Illuminate\\Pipeline\\Pipeline->then()
#39 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(145): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter()
#40 /var/www/html/public/index.php(76): Illuminate\\Foundation\\Http\\Kernel->handle()
#41 {main}
"} 
```

**Comment by JC5** [comment]
For this one I would like to receive the entire log, thanks.

**Comment by aarondvail** [comment]
log emailed

**Comment by JC5** [comment]
Found and fixed. See the new `develop` release. Root cause was something else.

**Comment by aarondvail** [comment]
getting that

Class "App\Services\SimpleFIN\Validation\ValidationResult" not found  error again....

![Image](https://github.com/user-attachments/assets/0fd848c9-5eb7-4e2d-8701-dbdbfc83a8e1)

**Comment by JC5** [comment]
Pull it again please. One of the builds borked. Build 1039 should work as expected.

**Comment by aarondvail** [comment]
so far so good.... pulling 120 of 847!!!!

**Comment by tehniemer** [comment]
Mine puked.

![Image](https://github.com/user-attachments/assets/fb7386f9-e8b3-4c3c-92df-4fc0883b87be)

I'll email you logs, but I believe the reason was because of the way the accounts were imported with a few having the same name by default. 

`[2025-06-25 13:17:33] local.ERROR: Failed to create account "AMERIPRISE BROKERAGE": {"name":["This account name is already in use."]}`

If this is the case, can the importer automatically apply a unique identifier to accounts that would otherwise import with the same name?

**Comment by tehniemer** [comment]
Looks like it also broke Firefly-III in the process.

![Image](https://github.com/user-attachments/assets/b487fd18-fe04-41ac-8dce-09fb6d76c91a)

**Comment by aarondvail** [comment]
if it's the same account, where it says create a new one click that and select to existing account..... otherwise click the pencil next to the name to give it a unique name.... I appended my name to my cards and my wife names to her cards that were with the same establishment...

mine looked like it was erroring out, but there was a new message about if there's a lot of transactions for new accounts it could take up to 20 minutes right in the middle of the error... same thing about the time out..... I get it....

What I liked seeing in the debugger is:
[2025-06-25 20:35:47] production.DEBUG: Messages: 847, warnings: 0, errors: 0

but given this:

![Image](https://github.com/user-attachments/assets/869b4e00-923f-4864-875c-4023b659623a)

do I need to start over when I want to import?

**Comment by JC5** [comment]
> Looks like it also broke Firefly-III in the process.

This means that the asset account in your frontpage preferences no longer exists. The data importer can't do that. Check out your `/preferences` page. Save your preferences, without changing anything.

> If this is the case, can the importer automatically apply a unique identifier to accounts that would otherwise import with the same name?

Absolutely not. I'd rather it dealt with the error. I'll look into it.

> do I need to start over when I want to import?

Yes. But the data importer is no longer capable of crapping out like that, are you sure you're running the latest `develop` version?

**Comment by aarondvail** [comment]
I am.... pulling fireflyiii/data-importer:develop

**Comment by tehniemer** [comment]
I got it to start the import after giving each account a unique name, but after about ~273/3164 transactions I got the following error message:

![Image](https://github.com/user-attachments/assets/8779525c-3c1f-4cc6-a84e-f3c7d9829b57)

However, looking at the container logs, it seems the import is still running fine.

**Comment by aarondvail** [comment]
is there a way I can save or pass the SimpleFIN settings without having to input them every time?

**Comment by JC5** [comment]
> I got it to start the import after giving each account a unique name, but after about ~273/3164 transactions I got the following error message:
> 
> ![Image](https://github.com/user-attachments/assets/8779525c-3c1f-4cc6-a84e-f3c7d9829b57)
> 
> However, looking at the container logs, it seems the import is still running fine.

Yes, that will often happen with very long imports. Can't always be helped, but I always try to improve it. 



> is there a way I can save or pass the SimpleFIN settings without having to input them every time?

Not yet, this is an improvement for the future. Since these settings are security sensitive, I have nowhere to save them.

**Comment by aarondvail** [comment]
> Not yet, this is an improvement for the future. Since these settings are security sensitive, I have nowhere to save them.

this could be a record in the DB.... or better yet an ENV (environment variable) that I could pass @ the docker run.

**Comment by aarondvail** [comment]
Going through my data.... it didn't do the transfers, it just did Debits and Credits per account

**Comment by JC5** [comment]
> this could be a record in the DB.... or better yet an ENV (environment variable) that I could pass @ the docker run.

Good point, this will be in place for the next release.

> Going through my data.... it didn't do the transfers, it just did Debits and Credits per account

OK. Sorry but there's nothing I can do with a statement like that. Be a little bit more specific please.

**Comment by JC5** [comment]
Data Importer v1.7.0 is now out. Please open new tickets for issues you may run into.
