### ISSUE TITLE
Nordigen - ($ownerAddressUnstructured) must be of type string, array given

### ISSUE THREAD

**Issue by sohowaty** [firefly-iii/firefly-iii#5507]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely me, not you](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

Nordigen (or my bank) passes array instead of string for account address. It's not exactly related to the Ff3 Data Importer but the address is not important and/or necessary for data processing and could be skipped entirely if it's not provided in correct form.
Data Importer is running on Docker on RPi4, bank account set in mBank Retail (Poland).

### Expected behaviour

Unimportant data in incorrect type should be converted or skipped entirely.

### Debug information

```192.168.1.20 - - [07/Jan/2022:22:12:07 +0000] "GET /import/configure HTTP/1.1" 500 7720 "http://malina.lan:8081/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36"
[2022-01-07 23:13:00] production.DEBUG: Now in App\Http\Controllers\IndexController::index  
[2022-01-07 23:13:00] production.DEBUG: App\Services\Shared\Authentication\SecretManager::hasValidSecrets  
192.168.1.20 - - [07/Jan/2022:22:13:00 +0000] "GET / HTTP/1.1" 200 3214 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36"
[2022-01-07 23:13:02] production.DEBUG: Now in App\Http\Controllers\IndexController::postIndex  
[2022-01-07 23:13:02] production.DEBUG: nordigen is a valid flow, redirect to authenticate.  
192.168.1.20 - - [07/Jan/2022:22:13:02 +0000] "POST / HTTP/1.1" 302 1900 "http://malina.lan:8081/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36"
[2022-01-07 23:13:02] production.DEBUG: Now in AuthenticateController, calling middleware.  
[2022-01-07 23:13:02] production.DEBUG: isReadyForNordigenStep("authenticate")  
[2022-01-07 23:13:02] production.DEBUG: isReadyForNordigenStep: Return true  
[2022-01-07 23:13:02] production.DEBUG: Now at App\Services\Nordigen\AuthenticationValidator::validate  
[2022-01-07 23:13:02] production.DEBUG: No Nordigen ID in hasId(), will return config variable.  
[2022-01-07 23:13:02] production.DEBUG: No Nordigen key in hasKey(), will return config variable.  
[2022-01-07 23:13:02] production.DEBUG: Now at App\Services\Nordigen\TokenManager::hasValidRefreshToken  
[2022-01-07 23:13:02] production.DEBUG: Now at App\Services\Nordigen\TokenManager::hasValidAccessToken  
[2022-01-07 23:13:02] production.DEBUG: Nordigen token is valid until 2022-01-08 23:11:19  
[2022-01-07 23:13:02] production.DEBUG: Nordigen token is valid.  
192.168.1.20 - - [07/Jan/2022:22:13:02 +0000] "GET /authenticate HTTP/1.1" 302 1527 "http://malina.lan:8081/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36"
[2022-01-07 23:13:02] production.DEBUG: isReadyForNordigenStep("upload-files")  
[2022-01-07 23:13:02] production.DEBUG: isReadyForNordigenStep: Return false  
[2022-01-07 23:13:02] production.DEBUG: redirectToCorrectNordigenStep("upload-files")  
[2022-01-07 23:13:02] production.DEBUG: Return redirect to "http://malina.lan:8081/import/selection"  
192.168.1.20 - - [07/Jan/2022:22:13:02 +0000] "GET /upload HTTP/1.1" 302 1577 "http://malina.lan:8081/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36"
[2022-01-07 23:13:02] production.DEBUG: isReadyForNordigenStep("nordigen-selection")  
[2022-01-07 23:13:02] production.DEBUG: isReadyForNordigenStep: Return true  
[2022-01-07 23:13:02] production.DEBUG: Now at App\Http\Controllers\Import\Nordigen\SelectionController::index  
192.168.1.20 - - [07/Jan/2022:22:13:02 +0000] "GET /import/selection HTTP/1.1" 302 1627 "http://malina.lan:8081/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36"
[2022-01-07 23:13:02] production.DEBUG: isReadyForNordigenStep("nordigen-link")  
[2022-01-07 23:13:02] production.DEBUG: isReadyForNordigenStep: Return true  
[2022-01-07 23:13:02] production.DEBUG: Now at App\Http\Controllers\Import\Nordigen\LinkController::build  
[2022-01-07 23:13:02] production.DEBUG: Now at App\Services\Nordigen\TokenManager::validateAllTokens  
[2022-01-07 23:13:02] production.DEBUG: Now at App\Services\Nordigen\TokenManager::hasValidRefreshToken  
[2022-01-07 23:13:02] production.DEBUG: Now at App\Services\Nordigen\TokenManager::hasValidAccessToken  
[2022-01-07 23:13:02] production.DEBUG: Nordigen token is valid until 2022-01-08 23:11:19  
[2022-01-07 23:13:02] production.DEBUG: Nordigen token is valid.  
[2022-01-07 23:13:02] production.DEBUG: Now at App\Services\Nordigen\TokenManager::getAccessToken  
[2022-01-07 23:13:02] production.DEBUG: Now at App\Services\Nordigen\TokenManager::validateAllTokens  
[2022-01-07 23:13:02] production.DEBUG: Now at App\Services\Nordigen\TokenManager::hasValidRefreshToken  
[2022-01-07 23:13:02] production.DEBUG: Now at App\Services\Nordigen\TokenManager::hasValidAccessToken  
[2022-01-07 23:13:02] production.DEBUG: Nordigen token is valid until 2022-01-08 23:11:19  
[2022-01-07 23:13:02] production.DEBUG: Nordigen token is valid.  
[2022-01-07 23:13:02] production.DEBUG: Request parameters will be set to:   
[2022-01-07 23:13:02] production.DEBUG: authenticatedGet(https://ob.nordigen.com/api/v2/requisitions/[deleted]?)  
[2022-01-07 23:13:02] production.DEBUG: Return JSON result of authenticatedGet  
192.168.1.20 - - [07/Jan/2022:22:13:02 +0000] "GET /import/link-nordigen/build HTTP/1.1" 302 1577 "http://malina.lan:8081/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36"
[2022-01-07 23:13:02] production.DEBUG: isReadyForNordigenStep("configuration")  
[2022-01-07 23:13:02] production.DEBUG: isReadyForNordigenStep: Return true  
[2022-01-07 23:13:02] production.DEBUG: Now at App\Http\Controllers\Import\ConfigurationController::index  
[2022-01-07 23:13:03] production.DEBUG: Now in App\Http\Controllers\Import\ConfigurationController::getNordigenAccounts  
[2022-01-07 23:13:03] production.DEBUG: Now at App\Services\Nordigen\TokenManager::getAccessToken  
[2022-01-07 23:13:03] production.DEBUG: Now at App\Services\Nordigen\TokenManager::validateAllTokens  
[2022-01-07 23:13:03] production.DEBUG: Now at App\Services\Nordigen\TokenManager::hasValidRefreshToken  
[2022-01-07 23:13:03] production.DEBUG: Now at App\Services\Nordigen\TokenManager::hasValidAccessToken  
[2022-01-07 23:13:03] production.DEBUG: Nordigen token is valid until 2022-01-08 23:11:19  
[2022-01-07 23:13:03] production.DEBUG: Nordigen token is valid.  
[2022-01-07 23:13:03] production.DEBUG: Request parameters will be set to:   
[2022-01-07 23:13:03] production.DEBUG: authenticatedGet(https://ob.nordigen.com/api/v2/requisitions/[deleted]/?)  
[2022-01-07 23:13:03] production.DEBUG: Return JSON result of authenticatedGet  
[2022-01-07 23:13:03] production.DEBUG: Found 1 accounts.  
[2022-01-07 23:13:03] production.DEBUG: [1/1] Now collecting information for account [deleted] {"identifier":"[deleted]","bban":"","bic":"","cash_account_type":"","currency":"","details":"","display_name":"","iban":"","linked_accounts":"","msisdn":"","name":"","owner_address_unstructured":"","owner_name":"","product":"","resource_id":"","status":"","usage":"","balances":[]} 
[2022-01-07 23:13:03] production.DEBUG: Now in App\Services\Nordigen\Services\AccountInformationCollector::collectInformation  
[2022-01-07 23:13:03] production.DEBUG: Now in App\Services\Nordigen\Services\AccountInformationCollector::getAccountDetails([deleted])  
[2022-01-07 23:13:03] production.DEBUG: Now at App\Services\Nordigen\TokenManager::getAccessToken  
[2022-01-07 23:13:03] production.DEBUG: Now at App\Services\Nordigen\TokenManager::validateAllTokens  
[2022-01-07 23:13:03] production.DEBUG: Now at App\Services\Nordigen\TokenManager::hasValidRefreshToken  
[2022-01-07 23:13:03] production.DEBUG: Now at App\Services\Nordigen\TokenManager::hasValidAccessToken  
[2022-01-07 23:13:03] production.DEBUG: Nordigen token is valid until 2022-01-08 23:11:19  
[2022-01-07 23:13:03] production.DEBUG: Nordigen token is valid.  
[2022-01-07 23:13:03] production.DEBUG: Request parameters will be set to:   
[2022-01-07 23:13:03] production.DEBUG: authenticatedGet(https://ob.nordigen.com/api/v2/accounts/[deleted]/details/?)  
[2022-01-07 23:13:04] production.DEBUG: Return JSON result of authenticatedGet  
[2022-01-07 23:13:04] production.DEBUG: Collected information for account {"iban":"[deleted]","currency":"PLN","ownerName":"[deleted]","displayName":"[deleted]","product":"[deleted]","usage":"PRIV","ownerAddressUnstructured":["POL","UL. [deleted] ","00-000 WARSZAWA"]} 
[2022-01-07 23:13:04] production.ERROR: App\Services\Nordigen\Model\Account::setOwnerAddressUnstructured(): Argument #1 ($ownerAddressUnstructured) must be of type string, array given, called in /var/www/html/app/Services/Nordigen/Services/AccountInformationCollector.php on line 117 {"exception":"[object] (TypeError(code: 0): App\\Services\\Nordigen\\Model\\Account::setOwnerAddressUnstructured(): Argument #1 ($ownerAddressUnstructured) must be of type string, array given, called in /var/www/html/app/Services/Nordigen/Services/AccountInformationCollector.php on line 117 at /var/www/html/app/Services/Nordigen/Model/Account.php:359)
[stacktrace]
#0 /var/www/html/app/Services/Nordigen/Services/AccountInformationCollector.php(117): App\\Services\\Nordigen\\Model\\Account->setOwnerAddressUnstructured()
#1 /var/www/html/app/Services/Nordigen/Services/AccountInformationCollector.php(55): App\\Services\\Nordigen\\Services\\AccountInformationCollector::getAccountDetails()
#2 /var/www/html/app/Http/Controllers/Import/ConfigurationController.php(219): App\\Services\\Nordigen\\Services\\AccountInformationCollector::collectInformation()
#3 /var/www/html/app/Http/Controllers/Import/ConfigurationController.php(160): App\\Http\\Controllers\\Import\\ConfigurationController->getNordigenAccounts()
#4 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): App\\Http\\Controllers\\Import\\ConfigurationController->index()
#5 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\\Routing\\Controller->callAction()
#6 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Route.php(262): Illuminate\\Routing\\ControllerDispatcher->dispatch()
#7 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Route.php(205): Illuminate\\Routing\\Route->runController()
#8 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(695): Illuminate\\Routing\\Route->run()
#9 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}()
#10 /var/www/html/app/Http/Middleware/IsReadyForStep.php(54): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#11 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): App\\Http\\Middleware\\ConfigurationControllerMiddleware->handle()
#12 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(50): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#13 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle()
#14 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(78): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#15 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle()
#16 /var/www/html/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#17 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle()
#18 /var/www/html/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(121): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#19 /var/www/html/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(64): Illuminate\\Session\\Middleware\\StartSession->handleStatefulRequest()
#20 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Session\\Middleware\\StartSession->handle()
#21 /var/www/html/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#22 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle()
#23 /var/www/html/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(67): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#24 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle()
#25 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#26 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(697): Illuminate\\Pipeline\\Pipeline->then()
#27 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(672): Illuminate\\Routing\\Router->runRouteWithinStack()
#28 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(636): Illuminate\\Routing\\Router->runRoute()
#29 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(625): Illuminate\\Routing\\Router->dispatchToRoute()
#30 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(167): Illuminate\\Routing\\Router->dispatch()
#31 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}()
#32 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#33 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.php(31): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#34 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\ConvertEmptyStringsToNull->handle()
#35 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#36 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php(40): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#37 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\TrimStrings->handle()
#38 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#39 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle()
#40 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(86): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#41 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance->handle()
#42 /var/www/html/vendor/fruitcake/laravel-cors/src/HandleCors.php(38): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#43 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Fruitcake\\Cors\\HandleCors->handle()
#44 /var/www/html/vendor/laravel/framework/src/Illuminate/Http/Middleware/TrustProxies.php(39): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#45 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Http\\Middleware\\TrustProxies->handle()
#46 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#47 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(142): Illuminate\\Pipeline\\Pipeline->then()
#48 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(111): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter()
#49 /var/www/html/public/index.php(77): Illuminate\\Foundation\\Http\\Kernel->handle()
#50 {main}
"} 
192.168.1.20 - - [07/Jan/2022:22:13:02 +0000] "GET /import/configure HTTP/1.1" 500 7720 "http://malina.lan:8081/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36"```

### Steps to reproduce

_No response_

### Additional info

_No response_

**Comment by JC5** [comment]
Thanks for letting me know. This will be fixed in the next release of the data importer. In the mean time, you can use the `develop` version.
