### ISSUE TITLE
4.3.5 - artisan: Method forceSchema does not exist

### ISSUE THREAD

**Issue by xpfgsyb** [firefly-iii/firefly-iii#578]
Hi,
I tried to upgrade my test instance from 4.3.4 to 4.3.5 but the artisan steps does only give the following error:
> [BadMethodCallException]
> Method forceSchema does not exist.

Visiting Firefly with a web browser shows this error: Whoops, looks like something went wrong.

A look into the log shows the following error:
```
[2017-02-19 21:20:27] production.ERROR: BadMethodCallException: Method forceSchema does not exist. in /var/www/html/test-firefly-iii/vendor/laravel/framework/src/Illuminate/Support/Traits/Macroable.php:74
Stack trace:
#0 /var/www/html/test-firefly-iii/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(221): Illuminate\Routing\UrlGenerator->__call('forceSchema', Array)
#1 /var/www/html/test-firefly-iii/app/Providers/AppServiceProvider.php(42): Illuminate\Support\Facades\Facade::__callStatic('forceSchema', Array)
#2 [internal function]: FireflyIII\Providers\AppServiceProvider->boot()
#3 /var/www/html/test-firefly-iii/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(28): call_user_func_array(Array, Array)
#4 /var/www/html/test-firefly-iii/vendor/laravel/framework/src/Illuminate/Support/helpers.php(912): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#5 /var/www/html/test-firefly-iii/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(86): value(Object(Closure))
#6 /var/www/html/test-firefly-iii/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(30): Illuminate\Container\BoundMethod::callBoundMethod(Object(Illuminate\Foundation\Application), Array, Object(Closure))
#7 /var/www/html/test-firefly-iii/vendor/laravel/framework/src/Illuminate/Container/Container.php(524): Illuminate\Container\BoundMethod::call(Object(Illuminate\Foundation\Application), Array, Array, NULL)
#8 /var/www/html/test-firefly-iii/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(762): Illuminate\Container\Container->call(Array)
#9 /var/www/html/test-firefly-iii/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(745): Illuminate\Foundation\Application->bootProvider(Object(FireflyIII\Providers\AppServiceProvider))
#10 [internal function]: Illuminate\Foundation\Application->Illuminate\Foundation\{closure}(Object(FireflyIII\Providers\AppServiceProvider), 15)
#11 /var/www/html/test-firefly-iii/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(746): array_walk(Array, Object(Closure))
#12 /var/www/html/test-firefly-iii/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/BootProviders.php(17): Illuminate\Foundation\Application->boot()
#13 /var/www/html/test-firefly-iii/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(208): Illuminate\Foundation\Bootstrap\BootProviders->bootstrap(Object(Illuminate\Foundation\Application))
#14 /var/www/html/test-firefly-iii/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(160): Illuminate\Foundation\Application->bootstrapWith(Array)
#15 /var/www/html/test-firefly-iii/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(144): Illuminate\Foundation\Http\Kernel->bootstrap()
#16 /var/www/html/test-firefly-iii/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(116): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#17 /var/www/html/test-firefly-iii/public/index.php(57): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#18 {main} 
```

That happened when I tried an upgrade with the old GIT alternative method. I tried it again after restoring the backup from yesterday, unfortunately with the same result. So I tried the new create-project way to do an upgrade, but it gives me the same errors. Do you have an idea what the problem could be? Do you need more information?

**Comment by JC5** [comment]
You're right, I messed this one up! I've released 4.3.6 which should be picked up by Packagist in about an hour.
