### ISSUE TITLE
Nordigen Import Error causes 500 Server Error

### ISSUE THREAD

**Issue by benjylxwang** [firefly-iii/firefly-iii#5954]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely me, not you](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

When using the Nordigen data importer, with some accounts (Starling Bank UK) after successful authentication with the bank, I am returned to the Firefly III data importer page with a 500 Server Error.  This occurred on multiple accounts, although they were all with the same bank.

Relevant log line: 
`[2022-04-02 15:37:04] production.ERROR: Undefined array key "account" {"exception":"[object] (ErrorException(code: 0): Undefined array key \"account\" at /var/www/html/app/Services/Nordigen/Services/AccountInformationCollector.php:102)`

Seems like there should be a check in [here](https://github.com/firefly-iii/data-importer/blob/e97850701e53ee79d72b24a0341f542cc83eb87d/app/Services/Nordigen/Services/AccountInformationCollector.php#L102) to see if the Nordigen request succeeded or not, and then display the Nordigen error if it failed.

### Expected behaviour

After authenticating with nordigen, Firefly III should show either the normal data import page or a more descriptive error message if there was a problem connecting with Nordigen.

### Debug information

Debug information generated at 2022-04-02 15:46:22 Europe/London for Firefly III Data Importer version **0.9.2**.

| Scope | Version |
| --- | --- |
| FIDI | 0.9.2 |
| Build | 108, 02-04-2022 14:05:32 CEST |
| PHP | 8.0.17 |
| Host | Linux |

| System info | Value |
| --- | --- |
| Using docker? | true |
| System TZ | Europe/London |
| Browser TZ | Europe/London |
| App environment | production |
| App debug mode | false |
| App cache driver | file |
| App logging | debug, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Interface | apache2handler |
| BCscale | 12 |
| Trusted proxies (.env) |  |

| User info | Value |
| --- | --- |
| User agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.84 Safari/537.36 |

**Comment by JC5** [comment]
What’s the error?

**Comment by benjylxwang** [comment]
As in what does firefly show me? This is what I see: 
![image](https://user-images.githubusercontent.com/8894223/161392616-c14fca8f-7518-4acd-8004-b4e7d8dc3946.png)

**Comment by JC5** [comment]
I am looking for the error before the missing key thing.

**Comment by benjylxwang** [comment]
Hmm... I'm not exactly sure if what you're looking for is there. Here's more of the context around it and the stacktrace (ids replaced with Xs):

```
[2022-04-02 17:39:13] production.DEBUG: Now in App\Services\Nordigen\Services\AccountInformationCollector::collectInformation
[2022-04-02 17:39:13] production.DEBUG: Now in App\Services\Nordigen\Services\AccountInformationCollector::getAccountDetails(XXXXXXXXX)
[2022-04-02 17:39:13] production.DEBUG: Now at App\Services\Nordigen\TokenManager::getAccessToken
[2022-04-02 17:39:13] production.DEBUG: Now at App\Services\Nordigen\TokenManager::validateAllTokens
[2022-04-02 17:39:13] production.DEBUG: Now at App\Services\Nordigen\TokenManager::hasValidRefreshToken
[2022-04-02 17:39:13] production.DEBUG: Now at App\Services\Nordigen\TokenManager::hasValidAccessToken
[2022-04-02 17:39:13] production.DEBUG: Nordigen token is valid until 2022-04-03 15:35:25
[2022-04-02 17:39:13] production.DEBUG: Nordigen token is valid.
[2022-04-02 17:39:13] production.DEBUG: Request parameters will be set to:
[2022-04-02 17:39:13] production.DEBUG: authenticatedGet(https://ob.nordigen.com/api/v2/accounts/XXXXXX/details/?)
[2022-04-02 17:39:14] production.DEBUG: Return JSON result of authenticatedGet
[2022-04-02 17:39:14] production.ERROR: Undefined array key "account" {"exception":"[object] (ErrorException(code: 0): Undefined array key \"account\" at /var/www/html/app/Services/Nordigen/Services/AccountInformationCollector.php:102)

[stacktrace]
#0 /var/www/html/app/Services/Nordigen/Services/AccountInformationCollector.php(102): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError()
#1 /var/www/html/app/Services/Nordigen/Services/AccountInformationCollector.php(58): App\\Services\\Nordigen\\Services\\AccountInformationCollector::getAccountDetails()
#2 /var/www/html/app/Http/Controllers/Import/ConfigurationController.php(221): App\\Services\\Nordigen\\Services\\AccountInformationCollector::collectInformation()
#3 /var/www/html/app/Http/Controllers/Import/ConfigurationController.php(162): App\\Http\\Controllers\\Import\\ConfigurationController->getNordigenAccounts()
#4 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): App\\Http\\Controllers\\Import\\ConfigurationController->index()

#5 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\\Routing\\Controller->callAction()

#6 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Route.php(262): Illuminate\\Routing\\ControllerDispatcher->dispatch()
#7 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Route.php(205): Illuminate\\Routing\\Route->runController()
#8 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(721): Illuminate\\Routing\\Route->run()
#9 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}()
#10 /var/www/html/app/Http/Middleware/IsReadyForStep.php(54): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#11 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): App\\Http\\Middleware\\ConfigurationControllerMiddleware->handle()
#12 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(50): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#13 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle()
#14 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(78): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#15 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle()
#16 /var/www/html/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#17 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle()
#18 /var/www/html/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(121): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#19 /var/www/html/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(64): Illuminate\\Session\\Middleware\\StartSession->handleStatefulRequest()
#20 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Session\\Middleware\\StartSession->handle()
#21 /var/www/html/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#22 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle()
#23 /var/www/html/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(67): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#24 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle()
#25 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#26 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(723): Illuminate\\Pipeline\\Pipeline->then()
#27 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(698): Illuminate\\Routing\\Router->runRouteWithinStack()
#28 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(662): Illuminate\\Routing\\Router->runRoute()
#29 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(651): Illuminate\\Routing\\Router->dispatchToRoute()
#30 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(167): Illuminate\\Routing\\Router->dispatch()
#31 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}()
#32 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#33 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.php(31): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#34 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\ConvertEmptyStringsToNull->handle()
#35 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#36 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php(40): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#37 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\TrimStrings->handle()
#38 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#39 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle()
#40 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(86): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#41 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance->handle()
#42 /var/www/html/vendor/fruitcake/laravel-cors/src/HandleCors.php(38): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#43 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Fruitcake\\Cors\\HandleCors->handle()
#44 /var/www/html/vendor/laravel/framework/src/Illuminate/Http/Middleware/TrustProxies.php(39): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#45 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Http\\Middleware\\TrustProxies->handle()
#46 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#47 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(142): Illuminate\\Pipeline\\Pipeline->then()
#48 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(111): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter()
#49 /var/www/html/public/index.php(77): Illuminate\\Foundation\\Http\\Kernel->handle()
#50 {main}
"}
```

**Comment by JC5** [comment]
Thanks, I’ll check it out 👍

**Comment by JC5** [comment]
This should be fixed in the next release :+1:
