### ISSUE TITLE
[FIDI] GetSearchAccountRequest::$query must not be accessed before initialization

### ISSUE THREAD

**Issue by wouterdt** [firefly-iii/firefly-iii#5982]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [ ] ... it's [definitely me, not you](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

I cannot get a csv to import using FIDI, the convert process ends in error
` The conversion could not be started, or failed due to an error. Please check the log files. Sorry about this :(`
I'm running on the `develop` container.
I've tried running on a simplified version of the csv, with 1 entry as per [the documentation](https://docs.firefly-iii.org/data-importer/usage/importing_transfers/
) but that fails as well.

Debug information generated at 2022-04-10 08:23:25 UTC for Firefly III version **5.7.1**.

| Scope | Version |
| --- | --- |
| Firefly III | 5.7.1 |
| Firefly III API | 1.5.6 |
| Build | 154, 08-04-2022 19:32:39 CEST |
| DB version | 18 (exp. 18) |
| PHP | `8.0.17` |
| Host | `Linux` |

| System info | Value |
| --- | --- |
| System TZ |  |
| Browser TZ | Europe/Brussels |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | info, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Interface | apache2handler |
| Default language | en_US |
| Default locale | equal |
| BCscale | 24 |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | mysql |
| Trusted proxies (.env) | `` |

| User info | Value |
| --- | --- |
| Login provider | eloquent  |
| User guard | web  |
| Headers | N/A, N/A  |
| Stateful domains |  |
| Session start | 2022-04-01 00:00:00 |
| Session end | 2022-04-30 23:59:59 |
| Session first | 2020-12-31 00:00:00 |
| User ID | 1 |
| User language | en_US |
| User locale | en_US |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| User agent | Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:98.0) Gecko/20100101 Firefox/98.0 |

### Expected behaviour

No system error

### Debug information

[root@localhost ~]# docker pull fireflyiii/data-importer:develop
Trying to pull repository docker.io/fireflyiii/data-importer ...
develop: Pulling from docker.io/fireflyiii/data-importer
*omitted*
Digest: sha256:8fbf09a79581b940c01f447f202602450adee9c5febc515284c16008656e9b73

docker run --rm -e FIREFLY_III_ACCESS_TOKEN=*removed* -e FIREFLY_III_URL=192.168.2.132 -e APP_LOG_LEVEL=debug -e  MAIL_DRIVER=log -p 81:8080 fireflyiii/data-importer:develop

[2022-04-10 10:21:25] production.DEBUG: Now running task App\Services\CSV\Conversion\Task\Tags
[2022-04-10 10:21:25] production.DEBUG: Now running task App\Services\CSV\Conversion\Task\Currency
[2022-04-10 10:21:25] production.DEBUG: Now running task App\Services\CSV\Conversion\Task\Accounts
[2022-04-10 10:21:25] production.DEBUG: Now in Accounts::process()
[2022-04-10 10:21:25] production.DEBUG: Now processing transaction 1 of 1
[2022-04-10 10:21:25] production.DEBUG: Now in Accounts::processTransaction()
[2022-04-10 10:21:25] production.DEBUG: Now in findAccount {"transaction_type":"deposit","id":null,"name":null,"iban":"*removed*","number":null,"bic":null,"direction":"source"}
[2022-04-10 10:21:25] production.DEBUG: Default account is #3 (" *removed*")
[2022-04-10 10:21:25] production.DEBUG: Find by IBAN.
[2022-04-10 10:21:25] production.DEBUG: Going to search account with IBAN "*removed*"
[2022-04-10 10:21:25] production.ERROR: Typed property GrumpyDictator\FFIIIApiSupport\Request\GetSearchAccountRequest::$query must not be accessed before initialization {"exception":"[object] (Error(code: 0): Typed property GrumpyDictator\\FFIIIApiSupport\\Request\\GetSearchAccountRequest::$query must not be accessed before initialization at /var/www/html/vendor/firefly-iii/api-support-classes/src/Request/GetSearchAccountRequest.php:103)
[stacktrace]
#0 /var/www/html/vendor/firefly-iii/api-support-classes/src/Request/GetSearchAccountRequest.php(95): GrumpyDictator\\FFIIIApiSupport\\Request\\GetSearchAccountRequest->getQuery()
#1 /var/www/html/app/Services/CSV/Conversion/Task/Accounts.php(385): GrumpyDictator\\FFIIIApiSupport\\Request\\GetSearchAccountRequest->setField()
#2 /var/www/html/app/Services/CSV/Conversion/Task/Accounts.php(261): App\\Services\\CSV\\Conversion\\Task\\Accounts->findByIban()
#3 /var/www/html/app/Services/CSV/Conversion/Task/Accounts.php(80): App\\Services\\CSV\\Conversion\\Task\\Accounts->findAccount()

### Steps to reproduce

1. `docker pull fireflyiii/data-importer:develop`
2. run importer container
3. import csv with presaved config

### Additional info

wondering if this is similar to #5981 i've pulled the latest version so that fix should be included

**Comment by JC5** [comment]
My bad, I've been messing this up. The latest :develop image should not have this problem.
