### ISSUE TITLE
Data Importer Error: redirectToCorrectSpectreStep: Cannot handle basic step "submit"

### ISSUE THREAD

**Issue by lorenzschmid** [firefly-iii/firefly-iii#6024]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely me, not you](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

When using the data importer (as a docker container) to import transaction from Spectre, the data importer fails with an error 500 after the import has been started. No new transactions are imported. Previously the data importer was working and successfully imported transaction via the same, existing connection from Spectre.

Looking at the logs it seems that there is an issue in the import routine: `redirectToCorrectSpectreStep: Cannot handle basic step \"submit\" at /var/www/html/app/Http/Middleware/IsReadyForStep.php:453`. For completeness I include the entire log from starting the import until the error appears (shown at the very bottom):

```
[2022-04-23 14:16:25] production.DEBUG: Now in App\Http\Controllers\IndexController::index
[2022-04-23 14:16:25] production.DEBUG: App\Services\Shared\Authentication\SecretManager::hasValidSecrets
redacted_ip - - [23/Apr/2022:12:16:23 +0000] "GET / HTTP/1.1" 200 3178 "-" "Mozilla/5.0"
[2022-04-23 14:16:25] production.DEBUG: Now at App\Http\Controllers\TokenController::doValidate
[2022-04-23 14:16:26] production.DEBUG: isReadyForSpectreStep("service-validation")
[2022-04-23 14:16:26] production.DEBUG: isReadyForSpectreStep: Return true
[2022-04-23 14:16:26] production.DEBUG: isReadyForSpectreStep("service-validation")
[2022-04-23 14:16:26] production.DEBUG: isReadyForSpectreStep: Return true
[2022-04-23 14:16:26] production.DEBUG: Now at App\Services\Spectre\AuthenticationValidator::validate
[2022-04-23 14:16:26] production.DEBUG: No Spectre App ID in hasAppId(), will return config variable.
[2022-04-23 14:16:26] production.DEBUG: No Spectre secret in hasSecret(), will return config variable.
[2022-04-23 14:16:26] production.DEBUG: setParameters
[2022-04-23 14:16:26] production.DEBUG: Now at App\Services\Nordigen\AuthenticationValidator::validate
[2022-04-23 14:16:26] production.DEBUG: No Nordigen ID in hasId(), will return config variable.
[2022-04-23 14:16:26] production.DEBUG: No Nordigen key in hasKey(), will return config variable.
redacted_ip - - [23/Apr/2022:12:16:26 +0000] "GET /validate/nordigen HTTP/1.1" 200 1073 "https://import.firefly.example.com/" "Mozilla/5.0"
redacted_ip - - [23/Apr/2022:12:16:26 +0000] "GET /validate/spectre HTTP/1.1" 200 1069 "https://import.firefly.example.com/" "Mozilla/5.0"
[2022-04-23 14:16:28] production.DEBUG: Now in App\Http\Controllers\IndexController::postIndex
[2022-04-23 14:16:28] production.DEBUG: spectre is a valid flow, redirect to authenticate.
redacted_ip - - [23/Apr/2022:12:16:28 +0000] "POST / HTTP/1.1" 302 1940 "https://import.firefly.example.com/" "Mozilla/5.0"
[2022-04-23 14:16:28] production.DEBUG: Now in AuthenticateController, calling middleware.
[2022-04-23 14:16:28] production.DEBUG: isReadyForSpectreStep("authenticate")
[2022-04-23 14:16:28] production.DEBUG: isReadyForSpectreStep: Return true
[2022-04-23 14:16:28] production.DEBUG: Now at App\Services\Spectre\AuthenticationValidator::validate
[2022-04-23 14:16:28] production.DEBUG: No Spectre App ID in hasAppId(), will return config variable.
[2022-04-23 14:16:28] production.DEBUG: No Spectre secret in hasSecret(), will return config variable.
[2022-04-23 14:16:28] production.DEBUG: setParameters
redacted_ip - - [23/Apr/2022:12:16:28 +0000] "GET /authenticate HTTP/1.1" 302 1559 "https://import.firefly.example.com/" "Mozilla/5.0"
[2022-04-23 14:16:29] production.DEBUG: isReadyForSpectreStep("upload-files")
[2022-04-23 14:16:29] production.DEBUG: isReadyForSpectreStep: Return false
[2022-04-23 14:16:29] production.DEBUG: redirectToCorrectSpectreStep("upload-files")
[2022-04-23 14:16:29] production.DEBUG: Return redirect to "https://import.firefly.example.com/import/spectre-connections"
redacted_ip - - [23/Apr/2022:12:16:29 +0000] "GET /upload HTTP/1.1" 302 1659 "https://import.firefly.example.com/" "Mozilla/5.0"
[2022-04-23 14:16:29] production.DEBUG: isReadyForSpectreStep("select-connection")
[2022-04-23 14:16:29] production.DEBUG: isReadyForSpectreStep: Return true
[2022-04-23 14:16:29] production.DEBUG: No Spectre App ID in hasAppId(), will return config variable.
[2022-04-23 14:16:29] production.DEBUG: No Spectre secret in hasSecret(), will return config variable.
[2022-04-23 14:16:29] production.DEBUG: setParameters
[2022-04-23 14:16:29] production.DEBUG: Result is {"result":"OK","message":null}
redacted_ip - - [23/Apr/2022:12:16:25 +0000] "GET /token/validate HTTP/1.1" 200 1084 "https://import.firefly.example.com/" "Mozilla/5.0"
[2022-04-23 14:16:29] production.DEBUG: storeContent: Stored 836 bytes in file "6c91c0a5060d25f7003db31ed21418bbe87387f131017bf82c806fc393a9e533"
[2022-04-23 14:16:29] production.DEBUG: About to get connections.
[2022-04-23 14:16:29] production.DEBUG: ListConnectionsRequest::get()
[2022-04-23 14:16:29] production.DEBUG: setParameters {"customer_id":"redacted_id"}
redacted_ip - - [23/Apr/2022:12:16:29 +0000] "GET /import/spectre-connections HTTP/1.1" 200 2684 "https://import.firefly.example.com/" "Mozilla/5.0"
[2022-04-23 14:16:32] production.DEBUG: isReadyForSpectreStep("select-connection")
[2022-04-23 14:16:32] production.DEBUG: isReadyForSpectreStep: Return true
[2022-04-23 14:16:32] production.DEBUG: storeContent: Stored 836 bytes in file "2693412d53d4965d1cc1674686f7c6f8f6f99b0523dd12cfb0331c8d2fd7c71d"
redacted_ip - - [23/Apr/2022:12:16:32 +0000] "POST /import/spectre-connections/submit HTTP/1.1" 302 1609 "https://import.firefly.example.com/import/spectre-connections" "Mozilla/5.0"
[2022-04-23 14:16:32] production.DEBUG: isReadyForSpectreStep("configuration")
[2022-04-23 14:16:32] production.DEBUG: isReadyForSpectreStep: Return true
[2022-04-23 14:16:32] production.DEBUG: Now at App\Http\Controllers\Import\ConfigurationController::index
[2022-04-23 14:16:33] production.DEBUG: No Spectre App ID in hasAppId(), will return config variable.
[2022-04-23 14:16:33] production.DEBUG: No Spectre secret in hasSecret(), will return config variable.
[2022-04-23 14:16:33] production.DEBUG: GetAccountsRequest::get()
[2022-04-23 14:16:33] production.DEBUG: setParameters {"connection_id":"redacted_id1"}
[2022-04-23 14:16:34] production.DEBUG: Now creating Spectre account lists.
[2022-04-23 14:16:34] production.DEBUG: Now working on Spectre account "redacted_iban": "redacted_id2"
[2022-04-23 14:16:34] production.DEBUG: This account (redacted_iban) has a single Firefly III counter part (#182, "redacted_name", same IBAN), so will use that one.
[2022-04-23 14:16:34] production.DEBUG: Now working on Spectre account "reducted_account_nbr": "redacted_id3"
[2022-04-23 14:16:34] production.DEBUG: Found 0 accounts with the same IBAN ("")
[2022-04-23 14:16:34] production.DEBUG: This account (CHF) has some Firefly III counter parts with the same currency so will only use those.
redacted_ip - - [23/Apr/2022:12:16:32 +0000] "GET /import/configure HTTP/1.1" 200 5734 "https://import.firefly.example.com/import/spectre-connections" "Mozilla/5.0"
[2022-04-23 14:16:34] production.DEBUG: isReadyForSpectreStep("configuration")
[2022-04-23 14:16:34] production.DEBUG: isReadyForSpectreStep: Return true
[2022-04-23 14:16:34] production.DEBUG: Method App\Http\Controllers\Import\ConfigurationController::phpDate
redacted_ip - - [23/Apr/2022:12:16:34 +0000] "GET /import/php_date HTTP/1.1" 200 1077 "https://import.firefly.example.com/import/configure" "Mozilla/5.0"
[2022-04-23 14:16:39] production.DEBUG: isReadyForSpectreStep("configuration")
[2022-04-23 14:16:39] production.DEBUG: isReadyForSpectreStep: Return true
[2022-04-23 14:16:39] production.DEBUG: Now running App\Http\Controllers\Import\ConfigurationController::postIndex
[2022-04-23 14:16:39] production.DEBUG: Now in updateDateRange()
[2022-04-23 14:16:39] production.DEBUG: Range is partial, after is NULL, dateNotBefore will be calculated.
[2022-04-23 14:16:39] production.DEBUG: dateNotBefore is now "2022-03-17"
[2022-04-23 14:16:39] production.DEBUG: storeContent: Stored 1066 bytes in file "6bc9c19c5566654e3b5afdc38e005fcca76593e899f88ff14fe8d23b410f837b"
[2022-04-23 14:16:39] production.DEBUG: Configuration debug: Connection ID is "redacted_id1"
redacted_ip - - [23/Apr/2022:12:16:39 +0000] "POST /import/configure HTTP/1.1" 302 1589 "https://import.firefly.example.com/import/configure" "Mozilla/5.0"
[2022-04-23 14:16:39] production.DEBUG: isReadyForSpectreStep("define-roles")
[2022-04-23 14:16:39] production.DEBUG: isReadyForSpectreStep: Return false
[2022-04-23 14:16:39] production.DEBUG: redirectToCorrectSpectreStep("define-roles")
[2022-04-23 14:16:39] production.DEBUG: Return redirect to "https://import.firefly.example.com/import/mapping"
redacted_ip - - [23/Apr/2022:12:16:39 +0000] "GET /import/roles HTTP/1.1" 302 1599 "https://import.firefly.example.com/import/configure" "Mozilla/5.0"
[2022-04-23 14:16:39] production.DEBUG: isReadyForSpectreStep("map")
[2022-04-23 14:16:39] production.DEBUG: Spectre: Return false, not yet ready for step [2].
[2022-04-23 14:16:39] production.DEBUG: isReadyForSpectreStep: Return false
[2022-04-23 14:16:39] production.DEBUG: redirectToCorrectSpectreStep("map")
[2022-04-23 14:16:39] production.DEBUG: Spectre: Is ready for conversion, so send to conversion.
[2022-04-23 14:16:39] production.DEBUG: Spectre: Return redirect to "https://import.firefly.example.com/import/convert"
redacted_ip - - [23/Apr/2022:12:16:39 +0000] "GET /import/mapping HTTP/1.1" 302 1599 "https://import.firefly.example.com/import/configure" "Mozilla/5.0"
[2022-04-23 14:16:39] production.DEBUG: isReadyForSpectreStep("conversion")
[2022-04-23 14:16:39] production.DEBUG: isReadyForSpectreStep: Return true
[2022-04-23 14:16:39] production.DEBUG: Now in App\Http\Controllers\Import\ConversionController::index
[2022-04-23 14:16:39] production.DEBUG: Will now verify configuration content.
[2022-04-23 14:16:39] production.DEBUG: Pressing "back" will send you to mapping.
[2022-04-23 14:16:39] production.DEBUG: Will redirect to submission after conversion.
[2022-04-23 14:16:39] production.DEBUG: Create Spectre routine manager.
[2022-04-23 14:16:39] production.DEBUG: Conversion routine manager identifier is "conv-re590yHgki5g"
[2022-04-23 14:16:39] production.DEBUG: Stored "conv-re590yHgki5g" under "conversion_job_id"
redacted_ip - - [23/Apr/2022:12:16:39 +0000] "GET /import/convert HTTP/1.1" 200 2354 "https://import.firefly.example.com/import/configure" "Mozilla/5.0"
[2022-04-23 14:16:39] production.DEBUG: isReadyForSpectreStep("conversion")
[2022-04-23 14:16:39] production.DEBUG: isReadyForSpectreStep: Return true
[2022-04-23 14:16:39] production.DEBUG: Now at App\Http\Controllers\Import\ConversionController::status
[2022-04-23 14:16:39] production.DEBUG: Now at App\Http\Controllers\Import\ConversionController::status(conv-re590yHgki5g)
[2022-04-23 14:16:39] production.DEBUG: Now in startOrFindConversion(conv-re590yHgki5g)
[2022-04-23 14:16:39] production.DEBUG: Conversion status is "conv_done"
redacted_ip - - [23/Apr/2022:12:16:39 +0000] "GET /import/convert/status?identifier=conv-re590yHgki5g HTTP/1.1" 200 1198 "https://import.firefly.example.com/import/convert" "Mozilla/5.0"
[2022-04-23 14:16:42] production.DEBUG: isReadyForSpectreStep("submit")
[2022-04-23 14:16:42] production.DEBUG: isReadyForSpectreStep: Return false
[2022-04-23 14:16:42] production.DEBUG: redirectToCorrectSpectreStep("submit")
[2022-04-23 14:16:43] production.ERROR: redirectToCorrectSpectreStep: Cannot handle basic step "submit" {"exception":"[object] (App\\Exceptions\\ImporterErrorException(code: 0): redirectToCorrectSpectreStep: Cannot handle basic step \"submit\" at /var/www/html/app/Http/Middleware/IsReadyForStep.php:453)
[stacktrace]
#0 /var/www/html/app/Http/Middleware/IsReadyForStep.php(335): App\\Http\\Middleware\\SubmitControllerMiddleware->redirectToCorrectSpectreStep()
#1 /var/www/html/app/Http/Middleware/IsReadyForStep.php(57): App\\Http\\Middleware\\SubmitControllerMiddleware->redirectToCorrectStep()
#2 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): App\\Http\\Middleware\\SubmitControllerMiddleware->handle()
#3 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(50): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#4 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle()
#5 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(78): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#6 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle()
#7 /var/www/html/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#8 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle()
#9 /var/www/html/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(121): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#10 /var/www/html/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(64): Illuminate\\Session\\Middleware\\StartSession->handleStatefulRequest()
#11 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Session\\Middleware\\StartSession->handle()
#12 /var/www/html/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#13 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle()
#14 /var/www/html/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(67): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#15 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle()
#16 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#17 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(723): Illuminate\\Pipeline\\Pipeline->then()
#18 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(698): Illuminate\\Routing\\Router->runRouteWithinStack()
#19 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(662): Illuminate\\Routing\\Router->runRoute()
#20 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(651): Illuminate\\Routing\\Router->dispatchToRoute()
#21 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(167): Illuminate\\Routing\\Router->dispatch()
#22 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}()
#23 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#24 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.php(31): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#25 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\ConvertEmptyStringsToNull->handle()
#26 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#27 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php(40): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#28 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\TrimStrings->handle()
#29 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#30 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle()
#31 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(86): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#32 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance->handle()
#33 /var/www/html/vendor/fruitcake/laravel-cors/src/HandleCors.php(38): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#34 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Fruitcake\\Cors\\HandleCors->handle()
#35 /var/www/html/vendor/laravel/framework/src/Illuminate/Http/Middleware/TrustProxies.php(39): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#36 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Http\\Middleware\\TrustProxies->handle()
#37 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#38 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(142): Illuminate\\Pipeline\\Pipeline->then()
#39 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(111): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter()
#40 /var/www/html/public/index.php(77): Illuminate\\Foundation\\Http\\Kernel->handle()
#41 {main}
"}
```

### Expected behaviour

Data importer finishes its import without an error.

### Debug information

Debug information generated at 2022-04-23 14:35:04 Europe/Amsterdam for Firefly III Data Importer version **0.9.8**.

| Scope | Version |
| --- | --- |
| FIDI | 0.9.8 |
| Build | 129, 12-04-2022 20:42:23 CEST |
| PHP | 8.0.17 |
| Host | Linux |

| System info | Value |
| --- | --- |
| Using docker? | true |
| System TZ |  |
| Browser TZ | Europe/Zurich |
| App environment | production |
| App debug mode | false |
| App cache driver | file |
| App logging | debug, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Interface | apache2handler |
| BCscale | 12 |
| Trusted proxies (.env) | ** |

| User info | Value |
| --- | --- |
| User agent | Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.1 Safari/605.1.15 |

**Comment by JC5** [comment]
What happens if you browse to /flush before you try it?

**Comment by lorenzschmid** [comment]
This did indeed the trick. Sorry for the noise.
