### ISSUE TITLE
Account virtual_balance cannot be updated with the API

### ISSUE THREAD

**Issue by a1ex4** [firefly-iii/firefly-iii#6053]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely me, not you](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

Updating an account's fields does not work [as expected by the API](https://api-docs.firefly-iii.org/#/accounts/updateAccount), a PUT request will only return current values. I can only confirm that this is the case with the `virtual_balance`:

```
r=$(curl -s -X PUT \
  'http://127.0.0.1:8000/api/v1/accounts/220' \
  -H "Authorization: Bearer $ff_token" \
  -H "Content-Type: application/json" \
  -H "Accept: application/json" \
  -d '{
    "virtual_balance":"1752.07", \
  }'
)
echo $r | jq '.data.attributes.virtual_balance'
```

`"1655.07"`

Even if I pass all the fields as they currently are, the virtual_balance is not updated. The result of the request is all the fields describing the account in json, and the status code is 200.

### Expected behaviour

Following the API PUT call with only the "virtual_balance" as data, the specified account is updated.

### Debug information

Debug information generated at 2022-05-03 21:51:57 Europe/Paris for Firefly III version **5.7.4**.

| Scope | Version |
| --- | --- |
| Firefly III | 5.7.4 |
| Firefly III API | 1.5.6 |
| Build | 174, 02-05-2022 19:49:26 CEST |
| DB version | 18 (exp. 18) |
| PHP | `8.0.17` |
| Host | `Linux` |

| System info | Value |
| --- | --- |
| System TZ | Europe/Paris |
| Browser TZ | Europe/Paris |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | info, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Interface | apache2handler |
| Default language | en_US |
| Default locale | equal |
| BCscale | 24 |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | pgsql |
| Trusted proxies (.env) | `**` |

| User info | Value |
| --- | --- |
| Login provider | eloquent  |
| User guard | web  |
| Headers | N/A, N/A  |
| Stateful domains |  |
| Session start | 2022-05-01 00:00:00 |
| Session end | 2022-05-31 23:59:59 |
| Session first | 2016-09-10 00:00:00 |
| User ID | 1 |
| User language | en_US |
| User locale | en_US |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| User agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:100.0) Gecko/20100101 Firefox/100.0 |

### Additional info

Thanks in advance!

**Comment by JC5** [comment]
I'll check it out, thanks!

**Comment by JC5** [comment]
Although I'm seeing some other bugs in 5.7.4, I was able to update the virtual_balance just fine.

**Comment by JC5** [comment]
This request for example, works fine on the demo site. You'll have to generate your own token.

```
curl --location --request PUT 'https://demo.firefly-iii.org/api/v1/accounts/1' \
--header 'Accept: application/json' \
--header 'Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOi' \
--header 'Content-Type: application/json' \
--data-raw '{
    "virtual_balance": "111114.56"
}'
```

**Comment by a1ex4** [comment]
Thanks for checking it out! So the command definitely works on the demo, but the exact same command throws a 500 on my instance:
<details>

```
[2022-05-04 23:31:42] local.DEBUG: Constructed UniqueAccountNumber  
[2022-05-04 23:31:42] local.DEBUG: Expected type is ""  
[2022-05-04 23:31:42] local.DEBUG: Now in FireflyIII\Api\V1\Controllers\Models\Account\UpdateController::update  
[2022-05-04 23:31:42] local.DEBUG: Now in appendLocationData("") {"virtual_balance":{"Illuminate\\Support\\Stringable":"111114.56"}} 
[2022-05-04 23:31:42] local.DEBUG: Now in isValidPOST()  
[2022-05-04 23:31:42] local.DEBUG: Fields not present  
[2022-05-04 23:31:42] local.DEBUG: Now in isValidPUT()  
[2022-05-04 23:31:42] local.DEBUG: Fields not present  
[2022-05-04 23:31:42] local.DEBUG: Method is PUT and all fields present and NULL.  
[2022-05-04 23:31:42] local.DEBUG: Returning longitude: "", latitude: "", zoom level: ""  
[2022-05-04 23:31:42] local.DEBUG: Returning actions: store: false, update: false, delete: true  
[2022-05-04 23:31:42] local.DEBUG: Now in FireflyIII\Services\Internal\Update\AccountUpdateService::update  
[2022-05-04 23:31:42] local.ERROR: Exception is: {"class":"TypeError","errorMessage":"trim(): Argument #1 ($string) must be of type string, Illuminate\\Support\\Stringable given","time":"Wed, 04 May 2022 23:31:42 +0200","file":"\/var\/www\/html\/app\/Services\/Internal\/Update\/AccountUpdateService.php","line":159,"code":0,"version":"5.7.4","url":"http:\/\/127.0.0.1:8000\/api\/v1\/accounts\/220","userAgent":"curl\/7.74.0","json":true,"method":"PUT"}  
[2022-05-04 23:31:42] local.ERROR: trim(): Argument #1 ($string) must be of type string, Illuminate\Support\Stringable given {"userId":1,"exception":"[object] (TypeError(code: 0): trim(): Argument #1 ($string) must be of type string, Illuminate\\Support\\Stringable given at /var/www/html/app/Services/Internal/Update/AccountUpdateService.php:159)
[stacktrace]
#0 /var/www/html/app/Services/Internal/Update/AccountUpdateService.php(159): trim()
#1 /var/www/html/app/Services/Internal/Update/AccountUpdateService.php(87): FireflyIII\\Services\\Internal\\Update\\AccountUpdateService->updateAccount()
#2 /var/www/html/app/Repositories/Account/AccountRepository.php(781): FireflyIII\\Services\\Internal\\Update\\AccountUpdateService->update()
#3 /var/www/html/app/Api/V1/Controllers/Models/Account/UpdateController.php(79): FireflyIII\\Repositories\\Account\\AccountRepository->update()
#4 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): FireflyIII\\Api\\V1\\Controllers\\Models\\Account\\UpdateController->update()
#5 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\\Routing\\Controller->callAction()
#6 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Route.php(261): Illuminate\\Routing\\ControllerDispatcher->dispatch()
#7 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Route.php(204): Illuminate\\Routing\\Route->runController()
#8 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(725): Illuminate\\Routing\\Route->run()
#9 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}()
#10 /var/www/html/app/Api/V1/Controllers/Models/Account/UpdateController.php(58): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#11 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(162): FireflyIII\\Api\\V1\\Controllers\\Models\\Account\\UpdateController->FireflyIII\\Api\\V1\\Controllers\\Models\\Account\\{closure}()
#12 /var/www/html/app/Api/V1/Controllers/Controller.php(69): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#13 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(162): FireflyIII\\Api\\V1\\Controllers\\Controller->FireflyIII\\Api\\V1\\Controllers\\{closure}()
#14 /var/www/html/app/Http/Middleware/Binder.php(78): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#15 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): FireflyIII\\Http\\Middleware\\Binder->handle()
#16 /var/www/html/app/Http/Middleware/Authenticate.php(75): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#17 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): FireflyIII\\Http\\Middleware\\Authenticate->handle()
#18 /var/www/html/vendor/laravel/sanctum/src/Http/Middleware/EnsureFrontendRequestsAreStateful.php(33): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#19 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Laravel\\Sanctum\\Http\\Middleware\\EnsureFrontendRequestsAreStateful->Laravel\\Sanctum\\Http\\Middleware\\{closure}()
#20 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#21 /var/www/html/vendor/laravel/sanctum/src/Http/Middleware/EnsureFrontendRequestsAreStateful.php(34): Illuminate\\Pipeline\\Pipeline->then()
#22 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Laravel\\Sanctum\\Http\\Middleware\\EnsureFrontendRequestsAreStateful->handle()
#23 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#24 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(726): Illuminate\\Pipeline\\Pipeline->then()
#25 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(703): Illuminate\\Routing\\Router->runRouteWithinStack()
#26 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(667): Illuminate\\Routing\\Router->runRoute()
#27 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(656): Illuminate\\Routing\\Router->dispatchToRoute()
#28 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(167): Illuminate\\Routing\\Router->dispatch()
#29 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}()
#30 /var/www/html/app/Http/Middleware/InstallationId.php(52): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#31 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): FireflyIII\\Http\\Middleware\\InstallationId->handle()
#32 /var/www/html/vendor/laravel/framework/src/Illuminate/Http/Middleware/TrustProxies.php(39): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#33 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Http\\Middleware\\TrustProxies->handle()
#34 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#35 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.php(31): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#36 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\ConvertEmptyStringsToNull->handle()
#37 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#38 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php(40): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#39 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\TrimStrings->handle()
#40 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#41 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle()
#42 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(86): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#43 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance->handle()
#44 /var/www/html/app/Http/Middleware/SecureHeaders.php(51): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#45 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): FireflyIII\\Http\\Middleware\\SecureHeaders->handle()
#46 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#47 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(142): Illuminate\\Pipeline\\Pipeline->then()
#48 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(111): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter()
#49 /var/www/html/public/index.php(76): Illuminate\\Foundation\\Http\\Kernel->handle()
#50 {main}
"} 
172.18.0.1 - - [04/May/2022:23:31:42 +0200] "PUT /api/v1/accounts/220 HTTP/1.1" 500 11300 "-" "curl/7.74.0"
```

</details>

It's really weird that the value is incorrectly passed on my instance... I'm using the latest docker image, the only difference I could find with the demo instance is that it's running php 8.0.18, while it's 8.0.17 in the image, though I don't expect it to be the cause.

Anyway, I don't expect you to spend more time on this, I'll eventually figure it out, unless you see something obvious 🙂

**Comment by a1ex4** [comment]
Ok it works now with 5.7.5, good news! Also I realized that my curl command in the original post is wrong, there's a backslash in the data packet... But now everything works, thanks again for keeping up with Firefly !
