### ISSUE TITLE
[data importer] Error when aftering client ID and app url in importer

### ISSUE THREAD

**Issue by zjean** [firefly-iii/firefly-iii#6083]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely me, not you](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

I tried to import a csv of my bank account. Had to reauthenticate in the data importer.
That didn't work, I got an error on submitting the form. The buttons (CSV Import, Spectre / Nordigen import) didn't show up.

### Expected behaviour

Being able to click the CSV import button.

### Debug information

Debug information generated at 2022-05-18 12:04:14 Europe/Amsterdam for Firefly III version **5.7.5**.

| Scope | Version |
| --- | --- |
| Firefly III | 5.7.5 |
| Firefly III API | 1.5.6 |
| Build | 180, 05-05-2022 06:05:01 CEST |
| DB version | 18 (exp. 18) |
| PHP | `8.1.5` |
| Host | `Linux` |

| System info | Value |
| --- | --- |
| System TZ | Europe/Amsterdam |
| Browser TZ | Europe/Amsterdam |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | notice, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Interface | apache2handler |
| Default language | nl_NL |
| Default locale | equal |
| BCscale | 24 |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | mysql |
| Trusted proxies (.env) | `**` |

| User info | Value |
| --- | --- |
| Login provider | eloquent  |
| User guard | web  |
| Headers | N/A, N/A  |
| Stateful domains |  |
| Session start | 2022-05-01 00:00:00 |
| Session end | 2022-05-31 23:59:59 |
| Session first | 2014-12-31 00:00:00 |
| User ID | 1 |
| User language | nl_NL |
| User locale | nl_NL |
| Attempt at "nl_NL.utf8" | 'nl_NL.utf8' |
| Attempt at "nl_NL.UTF-8" | 'nl_NL.UTF-8' |
| User agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.67 Safari/537.36 |

### Steps to reproduce

1. Open Data importer to import CSV
2. Go to the reset page
3. Enter firefly base url (https://firefly.domain.local)
4. Enter client id
5. Submit
6. Boom

### Additional info

```
[2022-05-18 11:56:26] production.DEBUG: Now at App\Http\Controllers\IndexController::reset  
[reacted-ip] - - [18/May/2022:09:56:26 +0000] "GET /reset HTTP/1.1" 302 2674 "https://data-import.[redacted]/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.67 Safari/537.36"
[2022-05-18 11:56:26] production.DEBUG: Now in App\Http\Controllers\IndexController::index  
[2022-05-18 11:56:26] production.DEBUG: App\Services\Shared\Authentication\SecretManager::hasValidSecrets  
[2022-05-18 11:56:26] production.DEBUG: No valid secrets, redirect to token.index  
[reacted-ip] - - [18/May/2022:09:56:26 +0000] "GET / HTTP/1.1" 302 1489 "https://data-import.[redacted]/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.67 Safari/537.36"
[2022-05-18 11:56:26] production.DEBUG: Now at App\Http\Controllers\TokenController::index  
[2022-05-18 11:56:26] production.DEBUG: No access token in hasAccessToken(), will return config variable.  
[2022-05-18 11:56:26] production.DEBUG: No client id in hasClientId(), will return config variable.  
[2022-05-18 11:56:26] production.DEBUG: No base url in getBaseUrl(), will return config variable.  
[2022-05-18 11:56:26] production.INFO: The following configuration information was found:  
[2022-05-18 11:56:26] production.INFO: Personal Access Token: "" (limited to 25 chars if present)  
[2022-05-18 11:56:26] production.INFO: Client ID            : "0"  
[2022-05-18 11:56:26] production.INFO: Base URL             : "https://[redacted]"  
[2022-05-18 11:56:26] production.INFO: Vanity URL           : "https://[redacted]"  
[reacted-ip] - - [18/May/2022:09:56:26 +0000] "GET /token HTTP/1.1" 200 2676 "https://data-import.[redacted]/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.67 Safari/537.36"
[reacted-ip] - - [18/May/2022:09:56:26 +0000] "GET /js/popper.min.js.map HTTP/1.1" 404 6803 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.67 Safari/537.36"
[reacted-ip] - - [18/May/2022:09:56:26 +0000] "GET /js/bootstrap.min.js.map HTTP/1.1" 200 55136 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.67 Safari/537.36"
[2022-05-18 11:56:35] production.DEBUG: Now at App\Http\Controllers\TokenController::submitClientId  
[2022-05-18 11:56:35] production.DEBUG: Submitted data:  {"client_id":"45","base_url":"https://[redacted]"} 
[2022-05-18 11:56:35] production.DEBUG: Base URL is "https://[redacted]"  
[2022-05-18 11:56:35] production.DEBUG: Vanity URL is now "https://[redacted]"  
[2022-05-18 11:56:35] production.DEBUG: Base URL is now "https://[redacted]"  
[2022-05-18 11:56:35] production.DEBUG: Now in App\Http\Controllers\TokenController::redirectForPermission(request, "https://[redacted]", "https://[redacted]", 45)  
[2022-05-18 11:56:35] production.DEBUG: Query parameters are {"client_id":45,"redirect_uri":"https://data-import.[redacted]/callback","response_type":"code","scope":"","state":"[redacted]","code_challenge":"[redacted]","code_challenge_method":"S256"} 
[2022-05-18 11:56:35] production.DEBUG: Now redirecting to "https://[redacted]/oauth/authorize?" (params omitted)  
[reacted-ip] - - [18/May/2022:09:56:35 +0000] "POST /token/client_id HTTP/1.1" 302 2761 "https://data-import.[redacted]/token" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.67 Safari/537.36"
[2022-05-18 11:56:35] production.DEBUG: Now at App\Http\Controllers\TokenController::callback  
[2022-05-18 11:56:35] production.DEBUG: State is valid!  
[2022-05-18 11:56:35] production.DEBUG: Params for access token {"form_params":{"grant_type":"authorization_code","client_id":45,"redirect_uri":"https://data-import.[redacted]/callback","code_verifier":"[redacted]","code":"[redacted]"}} 
[2022-05-18 11:56:35] production.DEBUG: Will contact "https://[redacted]/oauth/token" for a token.  
[2022-05-18 11:56:35] production.DEBUG: Response {"token_type":"Bearer","expires_in":1209600,"access_token":"[redacted]","refresh_token":"[redacted]"} 
[2022-05-18 11:56:35] production.DEBUG: Return redirect with cookies to "https://data-import.[redacted]"  
[reacted-ip] - - [18/May/2022:09:56:35 +0000] "GET /callback?code=[redacted]&state=[redacted] HTTP/1.1" 302 5808 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.67 Safari/537.36"
[2022-05-18 11:56:35] production.DEBUG: Now in App\Http\Controllers\IndexController::index  
[2022-05-18 11:56:35] production.DEBUG: App\Services\Shared\Authentication\SecretManager::hasValidSecrets  
[reacted-ip] - - [18/May/2022:09:56:35 +0000] "GET / HTTP/1.1" 200 3150 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.67 Safari/537.36"
[2022-05-18 11:56:36] production.DEBUG: Now at App\Http\Controllers\TokenController::doValidate  
[2022-05-18 11:56:36] production.DEBUG: isReadyForBasicStep("service-validation")  
[2022-05-18 11:56:36] production.DEBUG: Now at App\Services\Nordigen\AuthenticationValidator::validate  
[2022-05-18 11:56:36] production.DEBUG: No Nordigen ID in hasId(), will return config variable.  
[2022-05-18 11:56:36] production.DEBUG: No Nordigen key in hasKey(), will return config variable.  
[2022-05-18 11:56:36] production.ERROR: GrumpyDictator\FFIIIApiSupport\Request\Request::setVerify(): Argument #1 ($verify) must be of type bool, string given, called in /var/www/html/app/Http/Controllers/TokenController.php on line 147 {"exception":"[object] (TypeError(code: 0): GrumpyDictator\\FFIIIApiSupport\\Request\\Request::setVerify(): Argument #1 ($verify) must be of type bool, string given, called in /var/www/html/app/Http/Controllers/TokenController.php on line 147 at /var/www/html/vendor/firefly-iii/api-support-classes/src/Request/Request.php:53)
      
[stacktrace]
#0 /var/www/html/app/Http/Controllers/TokenController.php(147): GrumpyDictator\\FFIIIApiSupport\\Request\\Request->setVerify()
#1 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): App\\Http\\Controllers\\TokenController->doValidate()
#2 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\\Routing\\Controller->callAction()
#3 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Route.php(262): Illuminate\\Routing\\ControllerDispatcher->dispatch()
#4 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Route.php(205): Illuminate\\Routing\\Route->runController()
#5 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(721): Illuminate\\Routing\\Route->run()
#6 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}()
#7 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(50): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#8 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle()
#9 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(78): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#10 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle()
#11 /var/www/html/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#12 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle()
#13 /var/www/html/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(121): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#14 /var/www/html/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(64): Illuminate\\Session\\Middleware\\StartSession->handleStatefulRequest()
#15 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Session\\Middleware\\StartSession->handle()
#16 /var/www/html/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#17 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle()
#18 /var/www/html/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(67): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#19 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle()
#20 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#21 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(723): Illuminate\\Pipeline\\Pipeline->then()
#22 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(698): Illuminate\\Routing\\Router->runRouteWithinStack()
#23 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(662): Illuminate\\Routing\\Router->runRoute()
#24 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(651): Illuminate\\Routing\\Router->dispatchToRoute()
#25 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(167): Illuminate\\Routing\\Router->dispatch()
#26 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}()
#27 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#28 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.php(31): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#29 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\ConvertEmptyStringsToNull->handle()
#30 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#31 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php(40): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#32 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\TrimStrings->handle()
#33 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#34 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle()
#35 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(86): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#36 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance->handle()
#37 /var/www/html/vendor/fruitcake/laravel-cors/src/HandleCors.php(38): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#38 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Fruitcake\\Cors\\HandleCors->handle()
#39 /var/www/html/vendor/laravel/framework/src/Illuminate/Http/Middleware/TrustProxies.php(39): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#40 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Http\\Middleware\\TrustProxies->handle()
#41 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#42 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(142): Illuminate\\Pipeline\\Pipeline->then()
#43 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(111): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter()
#44 /var/www/html/public/index.php(77): Illuminate\\Foundation\\Http\\Kernel->handle()
#45 {main}
"} 
[2022-05-18 11:56:36] production.DEBUG: isReadyForBasicStep("service-validation")  
[2022-05-18 11:56:36] production.DEBUG: Now at App\Services\Spectre\AuthenticationValidator::validate  
[2022-05-18 11:56:36] production.DEBUG: No Spectre App ID in hasAppId(), will return config variable.  
[2022-05-18 11:56:36] production.DEBUG: No Spectre secret in hasSecret(), will return config variable.  
[reacted-ip] - - [18/May/2022:09:56:36 +0000] "GET /token/validate HTTP/1.1" 500 1125 "https://data-import.[redacted]/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.67 Safari/537.36"
[reacted-ip] - - [18/May/2022:09:56:36 +0000] "GET /validate/nordigen HTTP/1.1" 200 1073 "https://data-import.[redacted]/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.67 Safari/537.36"
[reacted-ip] - - [18/May/2022:09:56:36 +0000] "GET /validate/spectre HTTP/1.1" 200 1073 "https://data-import.[redacted]/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.67 Safari/537.36"
[reacted-ip] - - [18/May/2022:09:56:36 +0000] "GET /js/popper.min.js.map HTTP/1.1" 404 6803 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.67 Safari/537.36"
[reacted-ip] - - [18/May/2022:09:56:36 +0000] "GET /js/bootstrap.min.js.map HTTP/1.1" 200 55136 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.67 Safari/537.36"
```

**Comment by JC5** [comment]
That looks like a bug, thanks!

**Comment by zjean** [comment]
Hi,
I load my self signed (by Caddy v2 ) root certificate via a docker mount in to the data importer container like this:

.env:
`
VERIFY_TLS_SECURITY=/var/www/root.pem
`

docker-compose.yml
`
....
    volumes:
      - ../../../config/firefly-iii/data-importer/root.pem:/var/www/root.pem:ro
....
`

I also bashed into the container, and see the root.pem file in the /var/www folder, readable by all users.
This exact config has been working before.

**Comment by JC5** [comment]
Thanks, I see what you mean. I think the value is used badly somewhere in my code. I'll check it out!

**Comment by zjean** [comment]
Thanks! 😃

**Comment by zjean** [comment]
Is there anything I can do to help fix / test this?

**Comment by zjean** [comment]
I just pulled the data importers develop image, and it works 🎉
