### ISSUE TITLE
Data importer conversion fails due to: Cannot assign float to property ... TransactionExtra

### ISSUE THREAD

**Issue by soraxas** [firefly-iii/firefly-iii#6152]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [ ] ... it's [definitely me, not you](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

After the import procedure begins in Spectre (and begins the conversion), the app crashes. After checking the log, from the line `Cannot assign float to property... TransactionExtra` it seems like it's mis-match of data type from float to string (log attached).

### Expected behaviour

it works

### Debug information

```
[2022-06-10 04:46:14] production.DEBUG: isReadyForSpectreStep("conversion")  
[2022-06-10 04:46:14] production.DEBUG: isReadyForSpectreStep: Return true  
[2022-06-10 04:46:14] production.DEBUG: Now at App\Http\Controllers\Import\ConversionController::status  
[2022-06-10 04:46:14] production.DEBUG: Now at App\Http\Controllers\Import\ConversionController::status(conv-e94MG0ttdOtF)  
[2022-06-10 04:46:14] production.DEBUG: Now in startOrFindConversion(conv-e94MG0ttdOtF)  
[2022-06-10 04:46:14] production.DEBUG: Conversion status is "conv_running"  
172.17.0.1 - - [10/Jun/2022:02:46:14 +0000] "GET /import/convert/status?identifier=XXXXXXXXXXXXX HTTP/1.1" 200 1174 "http://localhost:8082/import/convert" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.0.0 Safari/537.36"
[2022-06-10 04:46:14] production.ALERT: Could not refresh connection.  
[2022-06-10 04:46:14] production.ALERT: ConnectionCannotBeRefreshed: Connection cannot be refreshed.  
[2022-06-10 04:46:14] production.DEBUG: Now in download()  
[2022-06-10 04:46:14] production.DEBUG: Found 2 accounts to download from.  
[2022-06-10 04:46:14] production.DEBUG: Going to download transactions for account #XXXXXXXXXXXXX  
[2022-06-10 04:46:14] production.DEBUG: No Spectre App ID in hasAppId(), will return config variable.  
[2022-06-10 04:46:14] production.DEBUG: No Spectre secret in hasSecret(), will return config variable.  
[2022-06-10 04:46:14] production.DEBUG: Now calling GetTransactionsRequest for next_id 0  
[2022-06-10 04:46:14] production.DEBUG: setParameters {"connection_id":"XXXXXXXXXXXXX","account_id":"XXXXXXXXXXXXX","from_id":0} 
[2022-06-10 04:46:15] production.DEBUG: isReadyForSpectreStep("conversion")  
[2022-06-10 04:46:15] production.DEBUG: isReadyForSpectreStep: Return true  
[2022-06-10 04:46:15] production.DEBUG: Now at App\Http\Controllers\Import\ConversionController::status  
[2022-06-10 04:46:15] production.DEBUG: Now at App\Http\Controllers\Import\ConversionController::status(conv-e94MG0ttdOtF)  
[2022-06-10 04:46:15] production.DEBUG: Now in startOrFindConversion(conv-e94MG0ttdOtF)  
[2022-06-10 04:46:15] production.DEBUG: Conversion status is "conv_running"  
172.17.0.1 - - [10/Jun/2022:02:46:15 +0000] "GET /import/convert/status?identifier=XXXXXXXXXXXXX HTTP/1.1" 200 1174 "http://localhost:8082/import/convert" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.0.0 Safari/537.36"
[2022-06-10 04:46:16] production.DEBUG: Found 100 entries in data-array  
[2022-06-10 04:46:16] production.DEBUG: Next ID is now XXXXXXXXXXXXX.  
[2022-06-10 04:46:16] production.DEBUG: Now calling GetTransactionsRequest for next_id XXXXXXXXXXXXX  
[2022-06-10 04:46:16] production.DEBUG: setParameters {"connection_id":"XXXXXXXXXXXXX","account_id":"XXXXXXXXXXXXX","from_id":"XXXXXXXXXXXXX"} 
[2022-06-10 04:46:16] production.DEBUG: isReadyForSpectreStep("conversion")  
[2022-06-10 04:46:16] production.DEBUG: isReadyForSpectreStep: Return true  
[2022-06-10 04:46:16] production.DEBUG: Now at App\Http\Controllers\Import\ConversionController::status  
[2022-06-10 04:46:16] production.DEBUG: Now at App\Http\Controllers\Import\ConversionController::status(conv-e94MG0ttdOtF)  
[2022-06-10 04:46:16] production.DEBUG: Now in startOrFindConversion(XXXXXXXXXXXXX)  
[2022-06-10 04:46:16] production.DEBUG: Conversion status is "conv_running"  
172.17.0.1 - - [10/Jun/2022:02:46:16 +0000] "GET /import/convert/status?identifier=conv-e94MG0ttdOtF HTTP/1.1" 200 1174 "http://localhost:8082/import/convert" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.0.0 Safari/537.36"
[2022-06-10 04:46:17] production.DEBUG: isReadyForSpectreStep("conversion")  
[2022-06-10 04:46:17] production.DEBUG: isReadyForSpectreStep: Return true  
[2022-06-10 04:46:17] production.DEBUG: Now at App\Http\Controllers\Import\ConversionController::status  
[2022-06-10 04:46:17] production.DEBUG: Now at App\Http\Controllers\Import\ConversionController::status(conv-e94MG0ttdOtF)  
[2022-06-10 04:46:17] production.DEBUG: Now in startOrFindConversion(conv-e94MG0ttdOtF)  
[2022-06-10 04:46:17] production.DEBUG: Conversion status is "conv_running"  
172.17.0.1 - - [10/Jun/2022:02:46:17 +0000] "GET /import/convert/status?identifier=conv-e94MG0ttdOtF HTTP/1.1" 200 1174 "http://localhost:8082/import/convert" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.0.0 Safari/537.36"
[2022-06-10 04:46:17] production.DEBUG: Found 70 entries in data-array  
[2022-06-10 04:46:17] production.ERROR: Cannot assign float to property App\Services\Spectre\Model\TransactionExtra::$units of type ?string {"exception":"[object] (TypeError(code: 0): Cannot assign float to property App\\Services\\Spectre\\Model\\TransactionExtra::$units of type ?string at /var/www/html/app/Services/Spectre/Model/TransactionExtra.php:103)
[stacktrace]
#0 /var/www/html/app/Services/Spectre/Model/Transaction.php(74): App\\Services\\Spectre\\Model\\TransactionExtra::fromArray()
#1 /var/www/html/app/Services/Spectre/Response/GetTransactionsResponse.php(49): App\\Services\\Spectre\\Model\\Transaction::fromArray()
#2 /var/www/html/app/Services/Spectre/Request/GetTransactionsRequest.php(91): App\\Services\\Spectre\\Response\\GetTransactionsResponse->__construct()
#3 /var/www/html/app/Services/Spectre/Conversion/Routine/TransactionProcessor.php(81): App\\Services\\Spectre\\Request\\GetTransactionsRequest->get()
#4 /var/www/html/app/Services/Spectre/Conversion/RoutineManager.php(93): App\\Services\\Spectre\\Conversion\\Routine\\TransactionProcessor->download()
#5 /var/www/html/app/Http/Controllers/Import/ConversionController.php(168): App\\Services\\Spectre\\Conversion\\RoutineManager->start()
#6 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): App\\Http\\Controllers\\Import\\ConversionController->start()
#7 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\\Routing\\Controller->callAction()
#8 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Route.php(262): Illuminate\\Routing\\ControllerDispatcher->dispatch()
#9 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Route.php(205): Illuminate\\Routing\\Route->runController()
#10 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(721): Illuminate\\Routing\\Route->run()
#11 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}()
#12 /var/www/html/app/Http/Middleware/IsReadyForStep.php(54): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#13 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): App\\Http\\Middleware\\ConversionControllerMiddleware->handle()
#14 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(50): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#15 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle()
#16 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(78): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#17 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle()
#18 /var/www/html/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#19 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle()
#20 /var/www/html/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(121): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#21 /var/www/html/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(64): Illuminate\\Session\\Middleware\\StartSession->handleStatefulRequest()
#22 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Session\\Middleware\\StartSession->handle()
#23 /var/www/html/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#24 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle()
#25 /var/www/html/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(67): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#26 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle()
#27 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#28 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(723): Illuminate\\Pipeline\\Pipeline->then()
#29 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(698): Illuminate\\Routing\\Router->runRouteWithinStack()
#30 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(662): Illuminate\\Routing\\Router->runRoute()
#31 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(651): Illuminate\\Routing\\Router->dispatchToRoute()
#32 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(167): Illuminate\\Routing\\Router->dispatch()
#33 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}()
#34 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#35 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.php(31): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#36 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\ConvertEmptyStringsToNull->handle()
#37 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#38 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php(40): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#39 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\TrimStrings->handle()
#40 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#41 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle()
#42 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(86): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#43 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance->handle()
#44 /var/www/html/vendor/fruitcake/laravel-cors/src/HandleCors.php(38): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#45 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Fruitcake\\Cors\\HandleCors->handle()
#46 /var/www/html/vendor/laravel/framework/src/Illuminate/Http/Middleware/TrustProxies.php(39): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#47 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Http\\Middleware\\TrustProxies->handle()
#48 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#49 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(142): Illuminate\\Pipeline\\Pipeline->then()
#50 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(111): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter()
#51 /var/www/html/public/index.php(77): Illuminate\\Foundation\\Http\\Kernel->handle()
#52 {main}
"} 
172.17.0.1 - - [10/Jun/2022:02:46:13 +0000] "POST /import/convert/start?identifier=conv-e94MG0ttdOtF HTTP/1.1" 500 1125 "http://localhost:8082/import/convert" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.0.0 Safari/537.36"
[2022-06-10 04:46:18] production.DEBUG: isReadyForSpectreStep("conversion")  
[2022-06-10 04:46:18] production.DEBUG: isReadyForSpectreStep: Return true  
[2022-06-10 04:46:18] production.DEBUG: Now at App\Http\Controllers\Import\ConversionController::status  
[2022-06-10 04:46:18] production.DEBUG: Now at App\Http\Controllers\Import\ConversionController::status(conv-e94MG0ttdOtF)  
[2022-06-10 04:46:18] production.DEBUG: Now in startOrFindConversion(conv-e94MG0ttdOtF)  
[2022-06-10 04:46:18] production.DEBUG: Conversion status is "conv_running"  
```

### Additional info

I'm running `fireflyiii/data-importer:develop` and `fireflyiii/core:version-5.7.9`

**Comment by JC5** [comment]
Thanks, that could be a bug. I'll check it out!

**Comment by rogersau** [comment]
I am now receiving this error on import from salt edge. I rolled back to fireflyiii/data-importer:version-0.9.12 and it fixed the import.

Version info (when receiving error):
`fireflyiii/core:latest` and `fireflyiii/data-importer:latest`

Debug info:

```
[2022-07-20 10:05:51] local.DEBUG: Found 69 entries in data-array
[2022-07-20 10:05:51] local.ERROR: Undefined array key "units" {"exception":"[object] (ErrorException(code: 0): Undefined array key \"units\" at /var/www/html/app/Services/Spectre/Model/TransactionExtra.php:103)
[stacktrace]
#0 /var/www/html/app/Services/Spectre/Model/TransactionExtra.php(103): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError()
#1 /var/www/html/app/Services/Spectre/Model/Transaction.php(74): App\\Services\\Spectre\\Model\\TransactionExtra::fromArray()
#2 /var/www/html/app/Services/Spectre/Response/GetTransactionsResponse.php(49): App\\Services\\Spectre\\Model\\Transaction::fromArray()
#3 /var/www/html/app/Services/Spectre/Request/GetTransactionsRequest.php(91): App\\Services\\Spectre\\Response\\GetTransactionsResponse->__construct()
#4 /var/www/html/app/Services/Spectre/Conversion/Routine/TransactionProcessor.php(81): App\\Services\\Spectre\\Request\\GetTransactionsRequest->get()
#5 /var/www/html/app/Services/Spectre/Conversion/RoutineManager.php(93): App\\Services\\Spectre\\Conversion\\Routine\\TransactionProcessor->download()
#6 /var/www/html/app/Http/Controllers/Import/ConversionController.php(168): App\\Services\\Spectre\\Conversion\\RoutineManager->start()
#7 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): App\\Http\\Controllers\\Import\\ConversionController->start()
#8 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\\Routing\\Controller->callAction()
#9 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Route.php(262): Illuminate\\Routing\\ControllerDispatcher->dispatch()
#10 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Route.php(205): Illuminate\\Routing\\Route->runController()
#11 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(721): Illuminate\\Routing\\Route->run()
#12 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}()
#13 /var/www/html/app/Http/Middleware/IsReadyForStep.php(54): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#14 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): App\\Http\\Middleware\\ConversionControllerMiddleware->handle()
#15 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(50): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#16 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle()
#17 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(78): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#18 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle()
#19 /var/www/html/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#20 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle()
#21 /var/www/html/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(121): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#22 /var/www/html/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(64): Illuminate\\Session\\Middleware\\StartSession->handleStatefulRequest()
#23 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Session\\Middleware\\StartSession->handle()
#24 /var/www/html/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#25 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle()
#26 /var/www/html/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(67): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#27 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle()
#28 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#29 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(723): Illuminate\\Pipeline\\Pipeline->then()
#30 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(698): Illuminate\\Routing\\Router->runRouteWithinStack()
#31 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(662): Illuminate\\Routing\\Router->runRoute()
#32 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(651): Illuminate\\Routing\\Router->dispatchToRoute()
#33 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(167): Illuminate\\Routing\\Router->dispatch()
#34 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}()
#35 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#36 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.php(31): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#37 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\ConvertEmptyStringsToNull->handle()
#38 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#39 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php(40): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#40 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\TrimStrings->handle()
#41 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#42 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle()
#43 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(86): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#44 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance->handle()
#45 /var/www/html/vendor/fruitcake/laravel-cors/src/HandleCors.php(38): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#46 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Fruitcake\\Cors\\HandleCors->handle()
#47 /var/www/html/vendor/laravel/framework/src/Illuminate/Http/Middleware/TrustProxies.php(39): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#48 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Http\\Middleware\\TrustProxies->handle()
#49 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#50 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(142): Illuminate\\Pipeline\\Pipeline->then()
#51 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(111): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter()
#52 /var/www/html/public/index.php(77): Illuminate\\Foundation\\Http\\Kernel->handle()
#53 {main}
"}
```

**Comment by JC5** [comment]
I've fixed this one, thanks for letting me know. :+1: 

Since I often unsubscribe to closed issues, make sure you open a new ticket if you run into something else. Otherwise, I may miss it.
