### ISSUE TITLE
Nordigen import fails - End user agreement problem

### ISSUE THREAD

**Issue by kuhlivisj** [firefly-iii/firefly-iii#6275]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely me, not you](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

Nordigen import fails and gives a 500 server error. Checking the logs it has something to do with the End User agreement which is expired.

### Expected behaviour

I expect to get a way to accept the End User agreement again and after that be able to import data again.

### Debug information

Debug information generated at 2022-07-31 19:57:33 Europe/Berlin for Firefly III Data Importer version **0.9.15**.

| Scope | Version |
| --- | --- |
| FIDI | 0.9.15 |
| Build | 162, 23-07-2022 08:37:42 CEST |
| PHP | 8.1.8 |
| Host | Linux |

| System info | Value |
| --- | --- |
| Using docker? | true |
| System TZ | Europe/Berlin |
| Browser TZ | Europe/Amsterdam |
| App environment | production |
| App debug mode | false |
| App cache driver | file |
| App logging | debug, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Interface | apache2handler |
| BCscale | 12 |
| Trusted proxies (.env) |  |

| User info | Value |
| --- | --- |
| User agent | Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.0.0 Safari/537.36 |

```
Truncated from this point <----|ml/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle()
#24 /var/www/html/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(67): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#25 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle()
#26 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#27 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(726): Illuminate\\Pipeline\\Pipeline->then()
#28 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(703): Illuminate\\Routing\\Router->runRouteWithinStack()
#29 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(667): Illuminate\\Routing\\Router->runRoute()
#30 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(656): Illuminate\\Routing\\Router->dispatchToRoute()
#31 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(167): Illuminate\\Routing\\Router->dispatch()
#32 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}()
#33 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#34 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.php(31): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#35 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\ConvertEmptyStringsToNull->handle()
#36 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#37 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php(40): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#38 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\TrimStrings->handle()
#39 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#40 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle()
#41 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(86): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#42 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance->handle()
#43 /var/www/html/vendor/fruitcake/laravel-cors/src/HandleCors.php(38): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#44 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Fruitcake\\Cors\\HandleCors->handle()
#45 /var/www/html/vendor/laravel/framework/src/Illuminate/Http/Middleware/TrustProxies.php(39): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#46 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Http\\Middleware\\TrustProxies->handle()
#47 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#48 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(142): Illuminate\\Pipeline\\Pipeline->then()
#49 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(111): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter()
#50 /var/www/html/public/index.php(77): Illuminate\\Foundation\\Http\\Kernel->handle()
#51 {main}
"} 
[2022-07-31 18:58:27] production.DEBUG: Now in App\Http\Controllers\IndexController::index  
[2022-07-31 18:58:27] production.DEBUG: App\Services\Shared\Authentication\SecretManager::hasValidSecrets  
[2022-07-31 18:58:27] production.DEBUG: No valid secrets, redirect to token.index  
[2022-07-31 19:03:27] production.DEBUG: Now in App\Http\Controllers\IndexController::index  
[2022-07-31 19:03:27] production.DEBUG: App\Services\Shared\Authentication\SecretManager::hasValidSecrets  
[2022-07-31 19:03:27] production.DEBUG: No valid secrets, redirect to token.index  
[2022-07-31 19:08:27] production.DEBUG: Now in App\Http\Controllers\IndexController::index  
[2022-07-31 19:08:27] production.DEBUG: App\Services\Shared\Authentication\SecretManager::hasValidSecrets  
[2022-07-31 19:08:27] production.DEBUG: No valid secrets, redirect to token.index  
[2022-07-31 19:13:27] production.DEBUG: Now in App\Http\Controllers\IndexController::index  
[2022-07-31 19:13:27] production.DEBUG: App\Services\Shared\Authentication\SecretManager::hasValidSecrets  
[2022-07-31 19:13:27] production.DEBUG: No valid secrets, redirect to token.index  
[2022-07-31 19:18:28] production.DEBUG: Now in App\Http\Controllers\IndexController::index  
[2022-07-31 19:18:28] production.DEBUG: App\Services\Shared\Authentication\SecretManager::hasValidSecrets  
[2022-07-31 19:18:28] production.DEBUG: No valid secrets, redirect to token.index  
[2022-07-31 19:23:28] production.DEBUG: Now in App\Http\Controllers\IndexController::index  
[2022-07-31 19:23:28] production.DEBUG: App\Services\Shared\Authentication\SecretManager::hasValidSecrets  
[2022-07-31 19:23:28] production.DEBUG: No valid secrets, redirect to token.index  
[2022-07-31 19:28:28] production.DEBUG: Now in App\Http\Controllers\IndexController::index  
[2022-07-31 19:28:28] production.DEBUG: App\Services\Shared\Authentication\SecretManager::hasValidSecrets  
[2022-07-31 19:28:28] production.DEBUG: No valid secrets, redirect to token.index  
[2022-07-31 19:33:28] production.DEBUG: Now in App\Http\Controllers\IndexController::index  
[2022-07-31 19:33:28] production.DEBUG: App\Services\Shared\Authentication\SecretManager::hasValidSecrets  
[2022-07-31 19:33:28] production.DEBUG: No valid secrets, redirect to token.index  
[2022-07-31 19:38:28] production.DEBUG: Now in App\Http\Controllers\IndexController::index  
[2022-07-31 19:38:28] production.DEBUG: App\Services\Shared\Authentication\SecretManager::hasValidSecrets  
[2022-07-31 19:38:28] production.DEBUG: No valid secrets, redirect to token.index  
[2022-07-31 19:43:28] production.DEBUG: Now in App\Http\Controllers\IndexController::index  
[2022-07-31 19:43:28] production.DEBUG: App\Services\Shared\Authentication\SecretManager::hasValidSecrets  
[2022-07-31 19:43:28] production.DEBUG: No valid secrets, redirect to token.index  
[2022-07-31 19:48:28] production.DEBUG: Now in App\Http\Controllers\IndexController::index  
[2022-07-31 19:48:28] production.DEBUG: App\Services\Shared\Authentication\SecretManager::hasValidSecrets  
[2022-07-31 19:48:28] production.DEBUG: No valid secrets, redirect to token.index  
[2022-07-31 19:53:29] production.DEBUG: Now in App\Http\Controllers\IndexController::index  
[2022-07-31 19:53:29] production.DEBUG: App\Services\Shared\Authentication\SecretManager::hasValidSecrets  
[2022-07-31 19:53:29] production.DEBUG: No valid secrets, redirect to token.index  
[2022-07-31 19:57:33] production.EMERGENCY: I am a EMERGENCY message.  
[2022-07-31 19:57:33] production.ALERT: I am a ALERT message.  
[2022-07-31 19:57:33] production.CRITICAL: I am a CRITICAL message.  
[2022-07-31 19:57:33] production.ERROR: I am a ERROR message.  
[2022-07-31 19:57:33] production.WARNING: I am a WARNING message.  
[2022-07-31 19:57:33] production.NOTICE: I am a NOTICE message.  
[2022-07-31 19:57:33] production.INFO: I am a INFO message.  
[2022-07-31 19:57:33] production.DEBUG: I am a DEBUG message.  

```

### Additional info

This is part of the docker log, I removed some of the id's from the log:

```
[2022-07-31 18:57:40] production.DEBUG: Nordigen token is valid until 2022-08-01 18:57:33  
[2022-07-31 18:57:40] production.DEBUG: Nordigen token is valid.  
[2022-07-31 18:57:40] production.DEBUG: Request parameters will be set to:   
[2022-07-31 18:57:40] production.DEBUG: authenticatedGet(https://ob.nordigen.com/api/v2/accounts/<some id>/details/?)  
[2022-07-31 18:57:40] production.ERROR: TransferException: Client error: `GET https://ob.nordigen.com/api/v2/accounts/<some id>/details/` resulted in a `400 Bad Request` response:
{"summary":"End User Agreement (EUA) <soome id> has expired","detail":"EUA was valid for 90 da (truncated...)
  
[2022-07-31 18:57:40] production.ERROR:  {"exception":"[object] (App\\Exceptions\\AgreementExpiredException(code: 0):  at /var/www/html/app/Services/Nordigen/Request/Request.php:136)
[stacktrace]
#0 /var/www/html/app/Services/Nordigen/Request/GetAccountInformationRequest.php(78): App\\Services\\Nordigen\\Request\\Request->authenticatedGet()
#1 /var/www/html/app/Services/Nordigen/Services/AccountInformationCollector.php(101): App\\Services\\Nordigen\\Request\\GetAccountInformationRequest->get()
#2 /var/www/html/app/Services/Nordigen/Services/AccountInformationCollector.php(58): App\\Services\\Nordigen\\Services\\AccountInformationCollector::getAccountDetails()
#3 /var/www/html/app/Http/Controllers/Import/ConfigurationController.php(221): App\\Services\\Nordigen\\Services\\AccountInformationCollector::collectInformation()
#4 /var/www/html/app/Http/Controllers/Import/ConfigurationController.php(162): App\\Http\\Controllers\\Import\\ConfigurationController->getNordigenAccounts()
#5 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): App\\Http\\Controllers\\Import\\ConfigurationController->index()
#6 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\\Routing\\Controller->callAction()
#7 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Route.php(261): Illuminate\\Routing\\ControllerDispatcher->dispatch()
#8 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Route.php(204): Illuminate\\Routing\\Route->runController()
#9 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(725): Illuminate\\Routing\\Route->run()
#10 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}()
#11 /var/www/html/app/Http/Middleware/IsReadyForStep.php(54): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#12 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): App\\Http\\Middleware\\ConfigurationControllerMiddleware->handle()
#13 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(50): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#14 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle()
#15 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(78): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#16 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle()
#17 /var/www/html/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#18 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle()
#19 /var/www/html/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(121): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#20 /var/www/html/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(64): Illuminate\\Session\\Middleware\\StartSession->handleStatefulRequest()
#21 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Session\\Middleware\\StartSession->handle()
#22 /var/www/html/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#23 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle()
#24 /var/www/html/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(67): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#25 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle()
#26 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#27 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(726): Illuminate\\Pipeline\\Pipeline->then()
#28 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(703): Illuminate\\Routing\\Router->runRouteWithinStack()
#29 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(667): Illuminate\\Routing\\Router->runRoute()
#30 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(656): Illuminate\\Routing\\Router->dispatchToRoute()
#31 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(167): Illuminate\\Routing\\Router->dispatch()
#32 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}()
#33 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#34 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.php(31): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#35 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\ConvertEmptyStringsToNull->handle()
#36 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#37 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php(40): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#38 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\TrimStrings->handle()
#39 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#40 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle()
#41 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(86): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#42 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance->handle()
#43 /var/www/html/vendor/fruitcake/laravel-cors/src/HandleCors.php(38): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#44 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Fruitcake\\Cors\\HandleCors->handle()
#45 /var/www/html/vendor/laravel/framework/src/Illuminate/Http/Middleware/TrustProxies.php(39): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#46 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Http\\Middleware\\TrustProxies->handle()
#47 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#48 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(142): Illuminate\\Pipeline\\Pipeline->then()
#49 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(111): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter()
#50 /var/www/html/public/index.php(77): Illuminate\\Foundation\\Http\\Kernel->handle()
#51 {main}
"} 
10.0.1.213 - - [31/Jul/2022:18:57:39 +0200] "GET /import/configure HTTP/1.1" 500 7715 "http://10.0.1.23:8080/upload" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.0.0 Safari/537.36"
```

**Comment by JC5** [comment]
I know about the issue, it's on the list!

**Comment by diamant-x** [comment]
I got the same issue, and could fix it by relinking with Nordigen.
Just proceed without any previous .conf file as if it was the first time, re-set the PSD2 bank authentication, and use the newly generate .conf file.
At least that worked for me.

**Comment by Fivefold** [comment]
> I got the same issue, and could fix it by relinking with Nordigen. Just proceed without any previous .conf file as if it was the first time, re-set the PSD2 bank authentication, and use the newly generate .conf file. At least that worked for me.

This works, but only if I deselect "map data". With it selected, I'm getting a redirection loop at the step `The conversion routine has finished 🎉. Please wait to be redirected!
`

Maybe an unrelated problem but mapping was working a few months ago (the last time I tried).

**Comment by cenjui** [comment]
I just wanted to add some notes in case google brings anyone else here when they are lost :) My install is not through docker but installed direct onto a virtual machine. My install uses a cron job to auto import the last 5 days at 9am each morning from my accounts into firefly.

I had the same issue and couldn't figure out how to get round it, also for some reason fidi was showing a 500 server error. 

To fix the 500 server error I moved the log file /var/www/html/data-importer/storage/logs/todays_date.log to /var/www/html/data-importer/storage/logs/todays_date.log.old. This let me back into fidi.

To work around the end user agreement problem once I was back in fidi I selected an Nordigen import but didnt supply a file so it prompted me to create a new account sync. I re-authed with the banks and saved the config files over the old ones to replace the user agreement timeout with a new one thats valid for another 90 days.

Firefly worked perfectly picking up duplicates for all my accounts apart from Pulse, but Pulse seem determined to span me with duplicate transactions since the Amazon / New Day card ended so that's not Firefly's problem!

For fixing the actual issue I had a look at the Noridgen API and I don't think you can prompt a new approval on a currently authed synchronisation with the free / personal edition - the API took the calls ok but kept replying that I didn't have the correct account type to do this. Given that Nordigen offer this service for free I am not going to annoy their support team with it - someone more knowledgeable than me can probably either confirm or disprove this and then contact Nordigen if required.

@JC5 - James, thanks for producing Firefly - its brilliant!

**Comment by JC5** [comment]
See also: https://github.com/firefly-iii/firefly-iii/issues/6770
