### ISSUE TITLE
Upgrade from 4.3.8 to 4.4.3 fails

### ISSUE THREAD

**Issue by skibbipl** [firefly-iii/firefly-iii#644]
When trying to upgrade from 4.3.8 to 4.4.3 version following error appears after executing `php artisan firefly:upgrade-database`:
```
[2017-05-07 14:41:49] production.ERROR: PDOException: SQLSTATE[42883]: Undefined function: 7 ERROR:  operator does not exist: integer <> text
LINE 1: ... "transaction_journals"."transaction_currency_id" != account...
                                                             ^
HINT:  No operator matches the given name and argument type(s). You might need to add explicit type casts. in /var/www/firefly-dev/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:91
Stack trace:
#0 /var/www/firefly-dev/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php(91): PDOStatement->execute(NULL)
#1 /var/www/firefly-dev/vendor/laravel/framework/src/Illuminate/Database/Connection.php(323): Doctrine\DBAL\Driver\PDOStatement->execute()
#2 /var/www/firefly-dev/vendor/laravel/framework/src/Illuminate/Database/Connection.php(640): Illuminate\Database\Connection->Illuminate\Database\{closure}('select "transac...', Array)
#3 /var/www/firefly-dev/vendor/laravel/framework/src/Illuminate/Database/Connection.php(607): Illuminate\Database\Connection->runQueryCallback('select "transac...', Array, Object(Closure))
#4 /var/www/firefly-dev/vendor/laravel/framework/src/Illuminate/Database/Connection.php(326): Illuminate\Database\Connection->run('select "transac...', Array, Object(Closure))
#5 /var/www/firefly-dev/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(1709): Illuminate\Database\Connection->select('select "transac...', Array, true)
#6 /var/www/firefly-dev/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(1694): Illuminate\Database\Query\Builder->runSelect()
#7 /var/www/firefly-dev/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(452): Illuminate\Database\Query\Builder->get(Array)
#8 /var/www/firefly-dev/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(436): Illuminate\Database\Eloquent\Builder->getModels(Array)
#9 /var/www/firefly-dev/app/Console/Commands/UpgradeDatabase.php(285): Illuminate\Database\Eloquent\Builder->get(Array)
#10 /var/www/firefly-dev/app/Console/Commands/UpgradeDatabase.php(74): FireflyIII\Console\Commands\UpgradeDatabase->updateJournalCurrencies()
#11 [internal function]: FireflyIII\Console\Commands\UpgradeDatabase->handle()
#12 /var/www/firefly-dev/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(29): call_user_func_array(Array, Array)
#13 /var/www/firefly-dev/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(87): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#14 /var/www/firefly-dev/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(31): Illuminate\Container\BoundMethod::callBoundMethod(Object(Illuminate\Foundation\Application), Array, Object(Closure))
#15 /var/www/firefly-dev/vendor/laravel/framework/src/Illuminate/Container/Container.php(531): Illuminate\Container\BoundMethod::call(Object(Illuminate\Foundation\Application), Array, Array, NULL)
#16 /var/www/firefly-dev/vendor/laravel/framework/src/Illuminate/Console/Command.php(182): Illuminate\Container\Container->call(Array)
#17 /var/www/firefly-dev/vendor/symfony/console/Command/Command.php(264): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#18 /var/www/firefly-dev/vendor/laravel/framework/src/Illuminate/Console/Command.php(167): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#19 /var/www/firefly-dev/vendor/symfony/console/Application.php(835): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#20 /var/www/firefly-dev/vendor/symfony/console/Application.php(200): Symfony\Component\Console\Application->doRunCommand(Object(FireflyIII\Console\Commands\UpgradeDatabase), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#21 /var/www/firefly-dev/vendor/symfony/console/Application.php(124): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#22 /var/www/firefly-dev/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(122): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#23 /var/www/firefly-dev/artisan(35): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#24 {main}

Next Doctrine\DBAL\Driver\PDOException: SQLSTATE[42883]: Undefined function: 7 ERROR:  operator does not exist: integer <> text
LINE 1: ... "transaction_journals"."transaction_currency_id" != account...
                                                             ^
HINT:  No operator matches the given name and argument type(s). You might need to add explicit type casts. in /var/www/firefly-dev/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:93
Stack trace:
#0 /var/www/firefly-dev/vendor/laravel/framework/src/Illuminate/Database/Connection.php(323): Doctrine\DBAL\Driver\PDOStatement->execute()
#1 /var/www/firefly-dev/vendor/laravel/framework/src/Illuminate/Database/Connection.php(640): Illuminate\Database\Connection->Illuminate\Database\{closure}('select "transac...', Array)
#2 /var/www/firefly-dev/vendor/laravel/framework/src/Illuminate/Database/Connection.php(607): Illuminate\Database\Connection->runQueryCallback('select "transac...', Array, Object(Closure))
#3 /var/www/firefly-dev/vendor/laravel/framework/src/Illuminate/Database/Connection.php(326): Illuminate\Database\Connection->run('select "transac...', Array, Object(Closure))
#4 /var/www/firefly-dev/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(1709): Illuminate\Database\Connection->select('select "transac...', Array, true)
#5 /var/www/firefly-dev/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(1694): Illuminate\Database\Query\Builder->runSelect()
#6 /var/www/firefly-dev/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(452): Illuminate\Database\Query\Builder->get(Array)
#7 /var/www/firefly-dev/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(436): Illuminate\Database\Eloquent\Builder->getModels(Array)
#8 /var/www/firefly-dev/app/Console/Commands/UpgradeDatabase.php(285): Illuminate\Database\Eloquent\Builder->get(Array)
#9 /var/www/firefly-dev/app/Console/Commands/UpgradeDatabase.php(74): FireflyIII\Console\Commands\UpgradeDatabase->updateJournalCurrencies()
#10 [internal function]: FireflyIII\Console\Commands\UpgradeDatabase->handle()
#11 /var/www/firefly-dev/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(29): call_user_func_array(Array, Array)
#12 /var/www/firefly-dev/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(87): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#13 /var/www/firefly-dev/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(31): Illuminate\Container\BoundMethod::callBoundMethod(Object(Illuminate\Foundation\Application), Array, Object(Closure))
#14 /var/www/firefly-dev/vendor/laravel/framework/src/Illuminate/Container/Container.php(531): Illuminate\Container\BoundMethod::call(Object(Illuminate\Foundation\Application), Array, Array, NULL)
#15 /var/www/firefly-dev/vendor/laravel/framework/src/Illuminate/Console/Command.php(182): Illuminate\Container\Container->call(Array)
#16 /var/www/firefly-dev/vendor/symfony/console/Command/Command.php(264): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#17 /var/www/firefly-dev/vendor/laravel/framework/src/Illuminate/Console/Command.php(167): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#18 /var/www/firefly-dev/vendor/symfony/console/Application.php(835): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#19 /var/www/firefly-dev/vendor/symfony/console/Application.php(200): Symfony\Component\Console\Application->doRunCommand(Object(FireflyIII\Console\Commands\UpgradeDatabase), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#20 /var/www/firefly-dev/vendor/symfony/console/Application.php(124): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#21 /var/www/firefly-dev/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(122): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#22 /var/www/firefly-dev/artisan(35): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#23 {main}
Next Illuminate\Database\QueryException: SQLSTATE[42883]: Undefined function: 7 ERROR:  operator does not exist: integer <> text
LINE 1: ... "transaction_journals"."transaction_currency_id" != account...
                                                             ^
HINT:  No operator matches the given name and argument type(s). You might need to add explicit type casts. (SQL: select "transaction_journals".*, "account_meta"."data" as "expected_currency_id", "transactions"."amount" as "transaction_amount" from "transaction_journals" left join "transaction_types" on "transaction_types"."id" = "transaction_journals"."transaction_type_id" left join "transactions" on "transaction_journals"."id" = "transactions"."transaction_journal_id" and "transactions"."amount" < 0 left join "accounts" on "accounts"."id" = "transactions"."account_id" left join "account_meta" on "account_meta"."account_id" = "accounts"."id" where "transaction_types"."type" = Withdrawal and "account_meta"."name" = currency_id and "transaction_journals"."transaction_currency_id" != account_meta.data and "transaction_journals"."deleted_at" is null) in /var/www/firefly-dev/vendor/laravel/framework/src/Illuminate/Database/Connection.php:647
Stack trace:
#0 /var/www/firefly-dev/vendor/laravel/framework/src/Illuminate/Database/Connection.php(607): Illuminate\Database\Connection->runQueryCallback('select "transac...', Array, Object(Closure))
#1 /var/www/firefly-dev/vendor/laravel/framework/src/Illuminate/Database/Connection.php(326): Illuminate\Database\Connection->run('select "transac...', Array, Object(Closure))
#2 /var/www/firefly-dev/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(1709): Illuminate\Database\Connection->select('select "transac...', Array, true)
#3 /var/www/firefly-dev/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(1694): Illuminate\Database\Query\Builder->runSelect()
#4 /var/www/firefly-dev/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(452): Illuminate\Database\Query\Builder->get(Array)
#5 /var/www/firefly-dev/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(436): Illuminate\Database\Eloquent\Builder->getModels(Array)
#6 /var/www/firefly-dev/app/Console/Commands/UpgradeDatabase.php(285): Illuminate\Database\Eloquent\Builder->get(Array)
#7 /var/www/firefly-dev/app/Console/Commands/UpgradeDatabase.php(74): FireflyIII\Console\Commands\UpgradeDatabase->updateJournalCurrencies()
#8 [internal function]: FireflyIII\Console\Commands\UpgradeDatabase->handle()
#9 /var/www/firefly-dev/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(29): call_user_func_array(Array, Array)
#10 /var/www/firefly-dev/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(87): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#11 /var/www/firefly-dev/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(31): Illuminate\Container\BoundMethod::callBoundMethod(Object(Illuminate\Foundation\Application), Array, Object(Closure))
#12 /var/www/firefly-dev/vendor/laravel/framework/src/Illuminate/Container/Container.php(531): Illuminate\Container\BoundMethod::call(Object(Illuminate\Foundation\Application), Array, Array, NULL)
#13 /var/www/firefly-dev/vendor/laravel/framework/src/Illuminate/Console/Command.php(182): Illuminate\Container\Container->call(Array)
#14 /var/www/firefly-dev/vendor/symfony/console/Command/Command.php(264): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#15 /var/www/firefly-dev/vendor/laravel/framework/src/Illuminate/Console/Command.php(167): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#16 /var/www/firefly-dev/vendor/symfony/console/Application.php(835): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#17 /var/www/firefly-dev/vendor/symfony/console/Application.php(200): Symfony\Component\Console\Application->doRunCommand(Object(FireflyIII\Console\Commands\UpgradeDatabase), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#18 /var/www/firefly-dev/vendor/symfony/console/Application.php(124): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#19 /var/www/firefly-dev/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(122): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#20 /var/www/firefly-dev/artisan(35): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#21 {main}

  [Illuminate\Database\QueryException]
  SQLSTATE[42883]: Undefined function: 7 ERROR:  operator does not exist: integer <> text
  LINE 1: ... "transaction_journals"."transaction_currency_id" != account...
                                                               ^
  HINT:  No operator matches the given name and argument type(s). You might need to add explicit type casts. (SQL: select "transaction_journals".*, "account_meta"."data" as "expected_currency_id", "transactions"."amount" as "transaction_amount" from "transaction_journals" left join "transaction_types" on "transaction_types"."id" = "transaction_journals"."tra
  nsaction_type_id" left join "transactions" on "transaction_journals"."id" = "transactions"."transaction_journal_id" and "transactions"."amount" < 0 left join "accounts" on "accounts"."id" = "transactions"."account_id" left join "account_meta" on "account_meta"."account_id" = "accounts"."id" where "transaction_types"."type" = Withdrawal and "account_meta"."
  name" = currency_id and "transaction_journals"."transaction_currency_id" != account_meta.data and "transaction_journals"."deleted_at" is null)

  [Doctrine\DBAL\Driver\PDOException]
  SQLSTATE[42883]: Undefined function: 7 ERROR:  operator does not exist: integer <> text
  LINE 1: ... "transaction_journals"."transaction_currency_id" != account...
                                                               ^
  HINT:  No operator matches the given name and argument type(s). You might need to add explicit type casts.

  [PDOException]
  SQLSTATE[42883]: Undefined function: 7 ERROR:  operator does not exist: integer <> text
  LINE 1: ... "transaction_journals"."transaction_currency_id" != account...
                                                               ^
  HINT:  No operator matches the given name and argument type(s). You might need to add explicit type casts.
```
I use postgresql as a DB backend.

**Comment by JC5** [comment]
Ah yes, I have to look into that. The query is very specific and it seems postgresql isn't keen on matching text with numbers.

**Comment by JC5** [comment]
I've added a postgresql specific fix that should resolve this problem in the next release.
