### ISSUE TITLE
Tag autofill doesn't work. Sends "caught an error in Firefly III" email

### ISSUE THREAD

**Issue by zero-thermo** [firefly-iii/firefly-iii#6545]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely me, not you](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

Upgraded from 5.5.1 to 5.7.13 with Docker. When typing a tag in a transaction, autofill does not show any matches. Instead, Firefly sends "caught an error in Firefly III" email. No obvious errors in logs.

Tag autofill worked fine in 5.5.1.

### Expected behaviour

When typing a tag in a transaction, autofill shows matching results for easier completion with no error emails sent.

### Debug information

Debug information generated at 2022-10-17 21:55:31 America/Vancouver for Firefly III version **5.7.13**.

| Scope | Version |
| --- | --- |
| Firefly III | 5.7.13 |
| Firefly III API | 1.5.6 |
| Build | 284, 16-10-2022 16:14:10 CEST |
| DB version | 18 (exp. 18) |
| PHP | `8.1.11` |
| Host | `Linux` |

| System info | Value |
| --- | --- |
| System TZ | UTC |
| Browser TZ | UTC |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | notice, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Interface | apache2handler |
| Default language | en_US |
| Default locale | equal |
| BCscale | 24 |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | mysql |
| Trusted proxies (.env) | `` |

| User info | Value |
| --- | --- |
| Login provider | eloquent  |
| User guard | web  |
| Headers | N/A, N/A  |
| Stateful domains |  |
| Session start | 2022-10-01 00:00:00 |
| Session end | 2022-10-31 23:59:59 |
| Session first | 2021-04-01 00:00:00 |
| User ID | 1 |
| User language | en_US |
| User locale | en_US |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| User agent | Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:105.0) Gecko/20100101 Firefox/105.0 |

### Steps to reproduce

1. Create a new transaction
2. Start typing a tag
3. Instead of autofill showing matching results, Firefly III sends error email

### Additional info

Hi there,

Firefly III v5.7.13 ran into an error: The MAC is invalid..

The error was of type "Illuminate\Contracts\Encryption\DecryptException".

The error occurred on/at: Mon, 17 Oct 2022 22:01:25 -0700.

This error occurred in file "/var/www/html/vendor/laravel/framework/src/Illuminate/Encryption/Encrypter.php" on line 218 with code 0.

There was no user logged in for this error or no user was detected.

The IP address related to this error is: 192.168.1.14 ([info](https://ipinfo.io/192.168.1.14/json?token=))
GET URL is: http://192.168.1.15:8083/api/v1/autocomplete/tags?query=expensive
The full stacktrace is below. If you think this is a bug in Firefly III, you can forward this message to [james@firefly-iii.org](mailto:james@firefly-iii.org?subject=BUG!). This can help fix the bug you just encountered.

If you prefer, you can also open a new issue on [GitHub](https://github.com/firefly-iii/firefly-iii/issues).

The full stacktrace is below:

```
#0 /var/www/html/vendor/laravel/framework/src/Illuminate/Encryption/Encrypter.php(151): Illuminate\Encryption\Encrypter->getJsonPayload()
#1 /var/www/html/vendor/laravel/passport/src/Guards/TokenGuard.php(329): Illuminate\Encryption\Encrypter->decrypt()
#2 /var/www/html/vendor/laravel/passport/src/Guards/TokenGuard.php(314): Laravel\Passport\Guards\TokenGuard->getTokenFromRequest()
#3 /var/www/html/vendor/laravel/passport/src/Guards/TokenGuard.php(282): Laravel\Passport\Guards\TokenGuard->validCsrf()
#4 /var/www/html/vendor/laravel/passport/src/Guards/TokenGuard.php(250): Laravel\Passport\Guards\TokenGuard->getTokenViaCookie()
#5 /var/www/html/vendor/laravel/passport/src/Guards/TokenGuard.php(122): Laravel\Passport\Guards\TokenGuard->authenticateViaCookie()
#6 /var/www/html/vendor/laravel/framework/src/Illuminate/Auth/GuardHelpers.php(60): Laravel\Passport\Guards\TokenGuard->user()
#7 /var/www/html/app/Http/Middleware/Authenticate.php(130): Laravel\Passport\Guards\TokenGuard->check()
#8 /var/www/html/app/Http/Middleware/Authenticate.php(73): FireflyIII\Http\Middleware\Authenticate->authenticate()
#9 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): FireflyIII\Http\Middleware\Authenticate->handle()
#10 /var/www/html/vendor/laravel/sanctum/src/Http/Middleware/EnsureFrontendRequestsAreStateful.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#11 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Laravel\Sanctum\Http\Middleware\EnsureFrontendRequestsAreStateful->Laravel\Sanctum\Http\Middleware\{closure}()
#12 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#13 /var/www/html/vendor/laravel/sanctum/src/Http/Middleware/EnsureFrontendRequestsAreStateful.php(34): Illuminate\Pipeline\Pipeline->then()
#14 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Laravel\Sanctum\Http\Middleware\EnsureFrontendRequestsAreStateful->handle()
#15 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#16 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(726): Illuminate\Pipeline\Pipeline->then()
#17 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(703): Illuminate\Routing\Router->runRouteWithinStack()
#18 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(667): Illuminate\Routing\Router->runRoute()
#19 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(656): Illuminate\Routing\Router->dispatchToRoute()
#20 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(190): Illuminate\Routing\Router->dispatch()
#21 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}()
#22 /var/www/html/app/Http/Middleware/InstallationId.php(52): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#23 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): FireflyIII\Http\Middleware\InstallationId->handle()
#24 /var/www/html/vendor/laravel/framework/src/Illuminate/Http/Middleware/TrustProxies.php(39): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#25 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Http\Middleware\TrustProxies->handle()
#26 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#27 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.php(31): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle()
#28 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Foundation\Http\Middleware\ConvertEmptyStringsToNull->handle()
#29 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#30 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php(40): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle()
#31 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Foundation\Http\Middleware\TrimStrings->handle()
#32 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#33 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Foundation\Http\Middleware\ValidatePostSize->handle()
#34 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(86): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#35 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Foundation\Http\Middleware\PreventRequestsDuringMaintenance->handle()
#36 /var/www/html/app/Http/Middleware/SecureHeaders.php(51): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#37 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): FireflyIII\Http\Middleware\SecureHeaders->handle()
#38 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#39 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(165): Illuminate\Pipeline\Pipeline->then()
#40 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(134): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter()
#41 /var/www/html/public/index.php(75): Illuminate\Foundation\Http\Kernel->handle()
#42 {main}
```

The following headers may also be relevant:

```
- host: 192.168.1.15:8083
- user-agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:105.0) Gecko/20100101 Firefox/105.0
- accept: application/json, text/plain, */*
- accept-language: en-US,en;q=0.5
- accept-encoding: gzip, deflate
- dnt: 1
- connection: keep-alive
- sec-gpc: 1
```

Beep boop,

The Firefly III Mail Robot

**Comment by JC5** [comment]
Looks like a cookie / authentication error. Does it work in another browser?

**Comment by zero-thermo** [comment]
Thank you for the prompt reply. You were right -- I tried Chrome and tag autofill works.

How do I fix this cookie / authentication error in Firefox? I've tried clearing cookies + site data and logging out. Do I need to reset something on the Firefly III side?

I tried going to the `/flush` page in my installation and running `php artisan cache:clear` inside the container, but tag autofill still has the same errors.

**Comment by zero-thermo** [comment]
Figured it out. For anyone else that runs into this error, [clear cookies and cache + Firefox startup cache](https://support.mozilla.org/en-US/kb/troubleshoot-and-diagnose-firefox-problems#w_2-clear-your-cookies-and-cache) to fix it.

Thanks again, @JC5. Love what you're doing with the project and am glad to continue supporting.
