### ISSUE TITLE
Cannot import from csv (currency id field is required) 

### ISSUE THREAD

**Issue by uchti** [firefly-iii/firefly-iii#669]
Version : 4.5 
Log Error Message: production.ERROR: Could not create transaction 1. ["The transaction currency id field is required."]

test file for import
[test.csv.txt](https://github.com/firefly-iii/firefly-iii/files/1064281/test.csv.txt)

import configuration
[import-configuration.txt](https://github.com/firefly-iii/firefly-iii/files/1064276/import-configuration.txt)

**Comment by JC5** [comment]
Yes, I know. An unfortunate oversight on my end. Expect a fix this weekend!

**Comment by JC5** [comment]
I'm giving the import an overhaul, but I hope to push a fix as soon as possible. My apologies for the delay.

**Comment by erikhubers** [comment]
Do you have a quick workaround for now by any chance?

**Comment by erroneousio** [comment]
Some more information for this ticket as I'm having this same issue. Using version 4.5.0.

I have added my own currency (Australian Dollars) and have been using the export csv as a template of sorts for my imports. I manually added in the currency-id field into my CSV (with the id from the URL under Options -> Currencies and the edit button, EG: `/currencies/edit/8`). 

[Test import from export.csv.txt](https://github.com/firefly-iii/firefly-iii/files/1087851/Test.import.from.export.csv.txt)

[currency-id-configuration.json.txt](https://github.com/firefly-iii/firefly-iii/files/1087852/currency-id-configuration.json.txt)

```
[2017-06-20 10:24:39] production.DEBUG: Going to convert using CurrencyId {"value":8} []
[2017-06-20 10:24:39] production.DEBUG: Found currency by ID  {"id":8} []
[2017-06-20 10:24:39] production.DEBUG: Value  {"index":3,"value":"8","role":"currency-id"} []
[2017-06-20 10:24:39] production.DEBUG: Going to import {"role":"currency-id","value":"8","certainty":100} []
[2017-06-20 10:24:39] production.DEBUG: ImportEntry: currency ID is now 8 with certainty 100 [] []
[2017-06-20 10:24:39] production.DEBUG: Going to convert using CurrencyName {"value":"AUD"} []
```

However, once that step occurred happens I get the following exception

```
[2017-06-20 10:24:39] production.ERROR: Exception is: {"class":"ErrorException","errorMessage":"Undefined index: decimal_places","time":"Tue, 20 Jun 2017 10:24:39 +0000","file":"\/sites\/firefly\/firefly-iii\/app\/Repositories\/Currency\/CurrencyRepository.php","line":237,"code":0,"version":"4.5.0"} [] []
[2017-06-20 10:24:41] production.ERROR: ErrorException: Undefined index: decimal_places in /sites/firefly/firefly-iii/app/Repositories/Currency/CurrencyRepository.php:237 Stack trace: #0 /sites/firefly/firefly-iii/app/Repositories/Currency/CurrencyRepository.php(237): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(8, 'Undefined index...', '/sites/firefly/...', 237, Array) #1 /sites/firefly/firefly-iii/app/Import/Converter/CurrencyName.php(73): FireflyIII\Repositories\Currency\CurrencyRepository->store(Array) #2 /sites/firefly/firefly-iii/app/Import/Importer/CsvImporter.php(160): FireflyIII\Import\Converter\CurrencyName->convert('AUD') #3 /sites/firefly/firefly-iii/app/Import/Importer/CsvImporter.php(71): FireflyIII\Import\Importer\CsvImporter->importSingleRow(1, Array) #4 /sites/firefly/firefly-iii/app/Import/ImportProcedure.php(52): FireflyIII\Import\Importer\CsvImporter->createImportEntries() #5 /sites/firefly/firefly-iii/app/Console/Commands/Import.php(79): FireflyIII\Import\ImportProcedure->runImport(Object(FireflyIII\Models\ImportJob)) #6 [internal function]: FireflyIII\Console\Commands\Import->handle() #7 /sites/firefly/firefly-iii/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(29): call_user_func_array(Array, Array) #8 /sites/firefly/firefly-iii/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(87): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}() #9 /sites/firefly/firefly-iii/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(31): Illuminate\Container\BoundMethod::callBoundMethod(Object(Illuminate\Foundation\Application), Array, Object(Closure)) #10 /sites/firefly/firefly-iii/vendor/laravel/framework/src/Illuminate/Container/Container.php(539): Illuminate\Container\BoundMethod::call(Object(Illuminate\Foundation\Application), Array, Array, NULL) #11 /sites/firefly/firefly-iii/vendor/laravel/framework/src/Illuminate/Console/Command.php(182): Illuminate\Container\Container->call(Array) #12 /sites/firefly/firefly-iii/vendor/symfony/console/Command/Command.php(264): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle)) #13 /sites/firefly/firefly-iii/vendor/laravel/framework/src/Illuminate/Console/Command.php(167): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle)) #14 /sites/firefly/firefly-iii/vendor/symfony/console/Application.php(869): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #15 /sites/firefly/firefly-iii/vendor/symfony/console/Application.php(223): Symfony\Component\Console\Application->doRunCommand(Object(FireflyIII\Console\Commands\Import), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #16 /sites/firefly/firefly-iii/vendor/symfony/console/Application.php(130): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #17 /sites/firefly/firefly-iii/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(122): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #18 /sites/firefly/firefly-iii/artisan(35): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #19 {main} [] []
```

Removing the currency-id field and mapping goes back to the previous error that @uchti stated. As it's mentioning decimal places, I ensured that the amount matched the two decimal places as well as made it a string by wrapping it in quotations. Still no luck.

**Comment by JC5** [comment]
Thanks for the extra information, @erroneousio!

The issue has been located and fixed in the upcoming release.

**Comment by JC5** [comment]
With the next release on the way, I'm closing this one.
