### ISSUE TITLE
Import from Nordigen fails because of missing opposing accounts

### ISSUE THREAD

**Issue by mzeising** [firefly-iii/firefly-iii#6735]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely me, not you](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

The import from Nordigen fails with *Argument #1 ($value) must be of type string, null given at /var/www/html/app/Http/Controllers/Import/MapController.php:271*

### Expected behaviour

The import completes

### Debug information

- the issue is in https://github.com/firefly-iii/data-importer/blob/main/app/Http/Controllers/Import/MapController.php#L271
- `$row['destination_name']` or `$row['source_name']` seems to be `null` so that
- `array_filter()` fails

```
fidi_1      | [2022-12-22 10:06:59] local.DEBUG: isReadyForNordigenStep("map")
fidi_1      | [2022-12-22 10:06:59] local.DEBUG: Return true, ready for step [4].
fidi_1      | [2022-12-22 10:06:59] local.DEBUG: isReadyForNordigenStep: Return true
fidi_1      | [2022-12-22 10:06:59] local.DEBUG: Now in mapController index
fidi_1      | [2022-12-22 10:06:59] local.DEBUG: Get mapping data for nordigen and spectre
fidi_1      | [2022-12-22 10:06:59] local.DEBUG: Now in App\Http\Controllers\Import\MapController::getOpposingAccounts
fidi_1      | [2022-12-22 10:06:59] local.DEBUG: [1/780] Parsing transaction (1)
...
fidi_1      | [2022-12-22 10:06:59] local.DEBUG: [780/780] Parsing transaction (1)
fidi_1      | [2022-12-22 10:06:59] local.ERROR: App\Http\Controllers\Import\MapController::App\Http\Controllers\Import\{closure}(): Argument #1 ($value) must be of type string, null given {"exception":"[object] (TypeError(code: 0): App\\Http\\Controllers\\Import\\MapController::App\\Http\\Controllers\\Import\\{closure}(): Argument #1 ($value) must be of type string, null given at /var/www/html/app/Http/Controllers/Import/MapController.php:271)
fidi_1      | [stacktrace]
fidi_1      | #0 [internal function]: App\\Http\\Controllers\\Import\\MapController::App\\Http\\Controllers\\Import\\{closure}()
fidi_1      | #1 /var/www/html/app/Http/Controllers/Import/MapController.php(273): array_filter()
fidi_1      | #2 /var/www/html/app/Http/Controllers/Import/MapController.php(197): App\\Http\\Controllers\\Import\\MapController->getOpposingAccounts()
fidi_1      | #3 /var/www/html/app/Http/Controllers/Import/MapController.php(91): App\\Http\\Controllers\\Import\\MapController->getImporterMapInformation()
fidi_1      | #4 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): App\\Http\\Controllers\\Import\\MapController->index()
fidi_1      | #5 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(43): Illuminate\\Routing\\Controller->callAction()
fidi_1      | #6 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Route.php(260): Illuminate\\Routing\\ControllerDispatcher->dispatch()
fidi_1      | #7 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Route.php(205): Illuminate\\Routing\\Route->runController()
fidi_1      | #8 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(725): Illuminate\\Routing\\Route->run()
fidi_1      | #9 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}()
fidi_1      | #10 /var/www/html/app/Http/Middleware/IsReadyForStep.php(54): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
fidi_1      | #11 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): App\\Http\\Middleware\\MapControllerMiddleware->handle()
fidi_1      | #12 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(50): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
fidi_1      | #13 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle()
fidi_1      | #14 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(78): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
fidi_1      | #15 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle()
fidi_1      | #16 /var/www/html/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
fidi_1      | #17 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle()
fidi_1      | #18 /var/www/html/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(121): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
fidi_1      | #19 /var/www/html/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(64): Illuminate\\Session\\Middleware\\StartSession->handleStatefulRequest()
fidi_1      | #20 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Session\\Middleware\\StartSession->handle()
fidi_1      | #21 /var/www/html/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
fidi_1      | #22 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle()
fidi_1      | #23 /var/www/html/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(67): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
fidi_1      | #24 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle()
fidi_1      | #25 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
fidi_1      | #26 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(726): Illuminate\\Pipeline\\Pipeline->then()
fidi_1      | #27 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(703): Illuminate\\Routing\\Router->runRouteWithinStack()
fidi_1      | #28 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(667): Illuminate\\Routing\\Router->runRoute()
fidi_1      | #29 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(656): Illuminate\\Routing\\Router->dispatchToRoute()
fidi_1      | #30 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(190): Illuminate\\Routing\\Router->dispatch()
fidi_1      | #31 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}()
fidi_1      | #32 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
fidi_1      | #33 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.php(31): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
fidi_1      | #34 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\ConvertEmptyStringsToNull->handle()
fidi_1      | #35 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
fidi_1      | #36 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php(40): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
fidi_1      | #37 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\TrimStrings->handle()
fidi_1      | #38 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
fidi_1      | #39 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle()
fidi_1      | #40 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(86): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
fidi_1      | #41 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance->handle()
fidi_1      | #42 /var/www/html/vendor/fruitcake/laravel-cors/src/HandleCors.php(38): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
fidi_1      | #43 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Fruitcake\\Cors\\HandleCors->handle()
fidi_1      | #44 /var/www/html/vendor/laravel/framework/src/Illuminate/Http/Middleware/TrustProxies.php(39): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
fidi_1      | #45 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Http\\Middleware\\TrustProxies->handle()
fidi_1      | #46 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
fidi_1      | #47 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(165): Illuminate\\Pipeline\\Pipeline->then()
fidi_1      | #48 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(134): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter()
fidi_1      | #49 /var/www/html/public/index.php(77): Illuminate\\Foundation\\Http\\Kernel->handle()
fidi_1      | #50 {main}
fidi_1      | "}
```

### Steps to reproduce

1. connect FIDI to Nordigen
2. run the import

**Comment by JC5** [comment]
That's weird. The method right before that should return strings only, it specifically casts strings.

Could you share some more logs over email? james@firefly-iii.org

**Comment by mzeising** [comment]
Thanks for the quick reply 👍 I'm sorry, I can't reproduce the exception anymore... but the code before line 271 will not fail on `null` values as PHP will not fail on a cast of `null` to `string`. The following code will work without any error:

```php
$a = null;
$b = (string) $a;
```

So, maybe there should be a check for `null`s somewhere before.
