### ISSUE TITLE
AccountTransformer.php#L118: bcround(): Argument #1 ($number) must be of type ?string, int given

### ISSUE THREAD

**Issue by Blogshot** [firefly-iii/firefly-iii#6804]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely me, not you](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

I'm trying to import data from ING DE into Firefly via the data importer. However, after uploading the CSV I am shown the error page with error 500.

This happens wether I'm using Nordigen or CSV, so I guess this is either related to some ING-specific formatting or something in the software itself.

The detailed error message in the logs is: [Quicklink to the line in question](https://github.com/firefly-iii/firefly-iii/blob/29bd3a280412139337cc70b800500e5f2859d67c/app/Transformers/AccountTransformer.php#L118)
```
Truncated from this point <----|:3473\/api\/v1\/accounts?limit=250&page=1&type=asset","userAgent":"GuzzleHttp\/7","json":true,"method":"GET"}  
[2023-01-05 21:05:07] local.ERROR: FireflyIII\Support\Steam::bcround(): Argument #1 ($number) must be of type ?string, int given, called in /var/www/html/app/Transformers/AccountTransformer.php on line 118 {"userId":1,"exception":"[object] (TypeError(code: 0): FireflyIII\\Support\\Steam::bcround(): Argument #1 ($number) must be of type ?string, int given, called in /var/www/html/app/Transformers/AccountTransformer.php on line 118 at /var/www/html/app/Support/Steam.php:106)
[stacktrace]
#0 /var/www/html/app/Transformers/AccountTransformer.php(118): FireflyIII\\Support\\Steam->bcround()
#1 /var/www/html/vendor/league/fractal/src/Scope.php(357): FireflyIII\\Transformers\\AccountTransformer->transform()
#2 /var/www/html/vendor/league/fractal/src/Scope.php(295): League\\Fractal\\Scope->fireTransformer()
#3 /var/www/html/vendor/league/fractal/src/Scope.php(173): League\\Fractal\\Scope->executeResourceTransformers()
#4 /var/www/html/app/Api/V1/Controllers/Models/Account/ShowController.php(111): League\\Fractal\\Scope->toArray()
#5 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): FireflyIII\\Api\\V1\\Controllers\\Models\\Account\\ShowController->index()
#6 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(43): Illuminate\\Routing\\Controller->callAction()
#7 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Route.php(260): Illuminate\\Routing\\ControllerDispatcher->dispatch()
#8 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Route.php(205): Illuminate\\Routing\\Route->runController()
#9 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(798): Illuminate\\Routing\\Route->run()
#10 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}()
#11 /var/www/html/app/Api/V1/Controllers/Models/Account/ShowController.php(63): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#12 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(162): FireflyIII\\Api\\V1\\Controllers\\Models\\Account\\ShowController->FireflyIII\\Api\\V1\\Controllers\\Models\\Account\\{closure}()
#13 /var/www/html/app/Api/V1/Controllers/Controller.php(69): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#14 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(162): FireflyIII\\Api\\V1\\Controllers\\Controller->FireflyIII\\Api\\V1\\Controllers\\{closure}()
#15 /var/www/html/app/Http/Middleware/Binder.php(78): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#16 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): FireflyIII\\Http\\Middleware\\Binder->handle()
#17 /var/www/html/app/Http/Middleware/Authenticate.php(75): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#18 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): FireflyIII\\Http\\Middleware\\Authenticate->handle()
#19 /var/www/html/vendor/laravel/sanctum/src/Http/Middleware/EnsureFrontendRequestsAreStateful.php(33): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#20 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Laravel\\Sanctum\\Http\\Middleware\\EnsureFrontendRequestsAreStateful->Laravel\\Sanctum\\Http\\Middleware\\{closure}()
#21 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#22 /var/www/html/vendor/laravel/sanctum/src/Http/Middleware/EnsureFrontendRequestsAreStateful.php(34): Illuminate\\Pipeline\\Pipeline->then()
#23 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Laravel\\Sanctum\\Http\\Middleware\\EnsureFrontendRequestsAreStateful->handle()
#24 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#25 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(799): Illuminate\\Pipeline\\Pipeline->then()
#26 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(776): Illuminate\\Routing\\Router->runRouteWithinStack()
#27 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(740): Illuminate\\Routing\\Router->runRoute()
#28 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(729): Illuminate\\Routing\\Router->dispatchToRoute()
#29 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(190): Illuminate\\Routing\\Router->dispatch()
#30 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}()
#31 /var/www/html/app/Http/Middleware/InstallationId.php(52): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#32 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): FireflyIII\\Http\\Middleware\\InstallationId->handle()
#33 /var/www/html/vendor/laravel/framework/src/Illuminate/Http/Middleware/TrustProxies.php(39): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#34 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Http\\Middleware\\TrustProxies->handle()
#35 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#36 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.php(31): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#37 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\ConvertEmptyStringsToNull->handle()
#38 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#39 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php(40): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#40 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\TrimStrings->handle()
#41 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#42 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle()
#43 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(86): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#44 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance->handle()
#45 /var/www/html/app/Http/Middleware/SecureHeaders.php(51): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#46 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): FireflyIII\\Http\\Middleware\\SecureHeaders->handle()
#47 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#48 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(165): Illuminate\\Pipeline\\Pipeline->then()
#49 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(134): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter()
#50 /var/www/html/public/index.php(75): Illuminate\\Foundation\\Http\\Kernel->handle()
#51 {main}
"} 
[2023-01-05 21:05:46] local.INFO: Update check is not enabled.  
[2023-01-05 21:08:53] local.INFO: Update check is not enabled.  

```

The CSV I provided is formatted like this:
| Buchung    | Valuta     | Auftraggeber/Empf�nger | Buchungstext | Verwendungszweck | Saldo | W�hrung | Betrag | W�hrung |    |     |   |   |   |   |
|------------|------------|------------------------|--------------|------------------|-------|---------|--------|---------|----|-----|---|---|---|---|
| 03.01.2023 | 03.01.2023 | VISA -redacted-        | Lastschrift  | Transaction-Text | 2433  | 67      | EUR    | -8      | 2  | EUR |   |   |   |   |
| 03.01.2023 | 03.01.2023 | VISA -redacted-        | Lastschrift  | Transaction-Text | 2441  | 69      | EUR    | -7      | 83 | EUR |   |   |   |   |
| 03.01.2023 | 03.01.2023 | VISA -redacted-        | Lastschrift  | Transaction-Text | 2449  | 52      | EUR    | -21     | 20 | EUR |   |   |   |   |
| 03.01.2023 | 03.01.2023 | VISA -redacted-        | Lastschrift  | Transaction-Text | 2470  | 72      | EUR    | -4      | 47 | EUR |   |   |   |   |

I noticed that the decimal divider is a comma instead of a dot, but a modified file produced the same error.

### Expected behaviour

A valid import of my data into Firefly 3.

### Debug information

Debug information generated at 2023-01-05 21:08:58 Europe/Berlin for Firefly III version **5.7.17**.

| Scope | Version |
| --- | --- |
| Firefly III | 5.7.17 |
| Firefly III API | 1.5.6 |
| Build | 333, 29-12-2022 19:46:14 CET |
| DB version | 18 (exp. 18) |
| PHP | `8.1.13` |
| Host | `Linux` |

| System info | Value |
| --- | --- |
| System TZ | Europe/Berlin |
| Browser TZ | Europe/Berlin |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | info, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Interface | apache2handler |
| Default language | en_US |
| Default locale | equal |
| BCscale | 24 |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | sqlite |
| Trusted proxies (.env) | `**` |

| User info | Value |
| --- | --- |
| Login provider | eloquent  |
| User guard | web  |
| Headers | N/A, N/A  |
| Stateful domains |  |
| Session start | 2023-01-01 00:00:00 |
| Session end | 2023-01-31 23:59:59 |
| Session first | 2021-11-22 00:00:00 |
| User ID | 1 |
| User language | de_DE |
| User locale | de_DE |
| Attempt at "de_DE.utf8" | 'de_DE.utf8' |
| Attempt at "de_DE.UTF-8" | 'de_DE.UTF-8' |
| User agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:108.0) Gecko/20100101 Firefox/108.0 |

### Steps to reproduce

1. Select `Import File`
2. Upload a CSV (see example above) without configuration file or selecting a pre-made configuration file
3. Click `Next`

### Additional info

I'm running Firefly and the importer as HomeAssistant addons, which are basically Docker containers.

On November 22nd I was able to import a CSV, so this might have been introduced in 5.7.16. I couldn't find the configuration file anymore, so I expected the manual configuration options to appear next.

**Comment by JC5** [comment]
Please use the search. This issue has been reported multiple times and has already been fixed in the latest release.
