### ISSUE TITLE
Duplicate hash error on a deleted transaction

### ISSUE THREAD

**Issue by adyanth** [firefly-iii/firefly-iii#6807]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely me, not you](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

Creating a transaction using the API, deleting it from the web UI and creating the same transaction again with error_if_duplicate_hash=true causes a 500 response.

### Expected behaviour

Accept the new transaction since there is no duplicate hash after deleting the transaction.

### Debug information

Debug information generated at 2023-01-06 00:23:02 America/Los_Angeles for Firefly III version **5.7.15**.

| Scope | Version |
| --- | --- |
| Firefly III | 5.7.15 |
| Firefly III API | 1.5.6 |
| Build | 298, 02-11-2022 05:00:04 CET |
| DB version | 18 (exp. 18) |
| PHP | `8.1.11` |
| Host | `Linux` |

| System info | Value |
| --- | --- |
| System TZ | America/Los_Angeles |
| Browser TZ | America/Los_Angeles |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | notice, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Interface | apache2handler |
| Default language | en_US |
| Default locale | equal |
| BCscale | 24 |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | sqlite |
| Trusted proxies (.env) | `**` |

| User info | Value |
| --- | --- |
| Login provider | eloquent  |
| User guard | web  |
| Headers | N/A, N/A  |
| Stateful domains |  |
| Session start | 2023-01-01 00:00:00 |
| Session end | 2023-01-31 23:59:59 |
| Session first | 2022-07-27 04:43:10 |
| User ID | 1 |
| User language | en_US |
| User locale | en_US |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| User agent | Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.2 Safari/605.1.15 |

### Steps to reproduce

1. Create a transaction using API
```json
{
    "error_if_duplicate_hash": true,
    "group_title": "title",
    "transactions": [{...}]
}
```
2. Delete the created transaction from the UI
3. Create the same transaction again

### Additional info

```
[2023-01-06 00:18:06] local.WARNING: Found a duplicate in errorIfDuplicate because hash c3c3a89204bb50a7de6a1f78b68965273def9b0adc27d5761b94be192ea33f80 is not unique!  
[2023-01-06 00:18:06] local.WARNING: TransactionJournalFactory::create() caught a duplicate journal in createJournal()  
[2023-01-06 00:18:06] local.ERROR: Duplicate of transaction #261.  
[2023-01-06 00:18:06] local.ERROR: #0 /var/www/html/app/Factory/TransactionJournalFactory.php(157): FireflyIII\Factory\TransactionJournalFactory->errorIfDuplicate()
```

```
404 Client Error: Not Found for url: https://firefly.domain/api/v1/transactions/261
```

**Comment by adyanth** [comment]
<details>
  <summary>Full stacktrace</summary>

```
[2023-01-06T00:38:05.549602-08:00] local.INFO: AUDIT: Store new transaction over API. (10.42.1.0 (me@domain) -> POST:https://firefly.domain/api/v1/transactions) {"group_title":"Pizza","error_if_duplicate_hash":true,"apply_rules":true,"fire_webhooks":true,"transactions":[{"type":"withdrawal","date":"2023-01-06T03:58:56+00:00","order":null,"currency_id":null,"currency_code":"USD","foreign_currency_id":null,"foreign_currency_code":"","amount":"13.21","foreign_amount":"","description":"Pizza","source_id":null,"source_name":"Amex","source_iban":"","source_number":"","source_bic":"","destination_id":null,"destination_name":"Regents","destination_iban":"","destination_number":"","destination_bic":"","budget_id":null,"budget_name":"","category_id":null,"category_name":"Dining","bill_id":null,"bill_name":"","piggy_bank_id":null,"piggy_bank_name":"","reconciled":false,"notes":"","tags":null,"internal_reference":"","external_id":"","original_source":"ff3-v5.7.15|api-v1.5.6","recurrence_id":null,"bunq_payment_id":"","external_url":"https://secure.splitwise.com/expenses/123","sepa_cc":"","sepa_ct_op":"","sepa_ct_id":"","sepa_db":"","sepa_country":"","sepa_ep":"","sepa_ci":"","sepa_batch_id":"","interest_date":null,"book_date":null,"process_date":null,"due_date":null,"payment_date":"2023-01-06T03:58:20+00:00","invoice_date":null}],"user":1} []
[2023-01-06 00:38:05] local.WARNING: Found a duplicate in errorIfDuplicate because hash c3c3a89204bb50a7de6a1f78b68965273def9b0adc27d5761b94be192ea33f80 is not unique!  
[2023-01-06 00:38:05] local.WARNING: TransactionJournalFactory::create() caught a duplicate journal in createJournal()  
[2023-01-06 00:38:05] local.ERROR: Duplicate of transaction #261.  
[2023-01-06 00:38:05] local.ERROR: #0 /var/www/html/app/Factory/TransactionJournalFactory.php(157): FireflyIII\Factory\TransactionJournalFactory->errorIfDuplicate()
#1 /var/www/html/app/Factory/TransactionJournalFactory.php(120): FireflyIII\Factory\TransactionJournalFactory->createJournal()
#2 /var/www/html/app/Factory/TransactionGroupFactory.php(66): FireflyIII\Factory\TransactionJournalFactory->create()
#3 /var/www/html/app/Repositories/TransactionGroup/TransactionGroupRepository.php(482): FireflyIII\Factory\TransactionGroupFactory->create()
#4 /var/www/html/app/Api/V1/Controllers/Models/Transaction/StoreController.php(94): FireflyIII\Repositories\TransactionGroup\TransactionGroupRepository->store()
#5 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): FireflyIII\Api\V1\Controllers\Models\Transaction\StoreController->store()
#6 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(43): Illuminate\Routing\Controller->callAction()
#7 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Route.php(260): Illuminate\Routing\ControllerDispatcher->dispatch()
#8 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Route.php(205): Illuminate\Routing\Route->runController()
#9 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(725): Illuminate\Routing\Route->run()
#10 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\Routing\Router->Illuminate\Routing\{closure}()
#11 /var/www/html/app/Api/V1/Controllers/Models/Transaction/StoreController.php(68): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#12 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(162): FireflyIII\Api\V1\Controllers\Models\Transaction\StoreController->FireflyIII\Api\V1\Controllers\Models\Transaction\{closure}()
#13 /var/www/html/app/Api/V1/Controllers/Controller.php(69): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#14 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(162): FireflyIII\Api\V1\Controllers\Controller->FireflyIII\Api\V1\Controllers\{closure}()
#15 /var/www/html/app/Http/Middleware/Binder.php(78): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#16 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): FireflyIII\Http\Middleware\Binder->handle()
#17 /var/www/html/app/Http/Middleware/Authenticate.php(75): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#18 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): FireflyIII\Http\Middleware\Authenticate->handle()
#19 /var/www/html/vendor/laravel/sanctum/src/Http/Middleware/EnsureFrontendRequestsAreStateful.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#20 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Laravel\Sanctum\Http\Middleware\EnsureFrontendRequestsAreStateful->Laravel\Sanctum\Http\Middleware\{closure}()
#21 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#22 /var/www/html/vendor/laravel/sanctum/src/Http/Middleware/EnsureFrontendRequestsAreStateful.php(34): Illuminate\Pipeline\Pipeline->then()
#23 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Laravel\Sanctum\Http\Middleware\EnsureFrontendRequestsAreStateful->handle()
#24 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#25 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(726): Illuminate\Pipeline\Pipeline->then()
#26 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(703): Illuminate\Routing\Router->runRouteWithinStack()
#27 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(667): Illuminate\Routing\Router->runRoute()
#28 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(656): Illuminate\Routing\Router->dispatchToRoute()
#29 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(190): Illuminate\Routing\Router->dispatch()
#30 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}()
#31 /var/www/html/app/Http/Middleware/InstallationId.php(52): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#32 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): FireflyIII\Http\Middleware\InstallationId->handle()
#33 /var/www/html/vendor/laravel/framework/src/Illuminate/Http/Middleware/TrustProxies.php(39): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#34 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Http\Middleware\TrustProxies->handle()
#35 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#36 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.php(31): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle()
#37 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Foundation\Http\Middleware\ConvertEmptyStringsToNull->handle()
#38 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#39 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php(40): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle()
#40 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Foundation\Http\Middleware\TrimStrings->handle()
#41 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#42 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Foundation\Http\Middleware\ValidatePostSize->handle()
#43 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(86): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#44 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Foundation\Http\Middleware\PreventRequestsDuringMaintenance->handle()
#45 /var/www/html/app/Http/Middleware/SecureHeaders.php(51): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#46 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): FireflyIII\Http\Middleware\SecureHeaders->handle()
#47 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#48 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(165): Illuminate\Pipeline\Pipeline->then()
#49 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(134): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter()
#50 /var/www/html/public/index.php(75): Illuminate\Foundation\Http\Kernel->handle()
#51 {main}  
[2023-01-06 00:38:05] local.WARNING: GroupFactory::create() caught journalFactory::create() with a duplicate!  
[2023-01-06 00:38:05] local.WARNING: Group repository caught group factory with a duplicate exception!  
[2023-01-06 00:38:05] local.WARNING: Caught a duplicate transaction. Return error message.  
[2023-01-06 00:38:05] local.ERROR: Exception is: {"class":"TypeError","errorMessage":"Illegal offset type","time":"Fri, 06 Jan 2023 00:38:05 -0800","file":"\/var\/www\/html\/vendor\/laravel\/framework\/src\/Illuminate\/Support\/ViewErrorBag.php","line":61,"code":0,"version":"5.7.15","url":"https:\/\/firefly.domain\/api\/v1\/transactions","userAgent":"python-requests\/2.28.1","json":true,"method":"POST"}  
[2023-01-06 00:38:05] local.ERROR: Illegal offset type {"userId":1,"exception":"[object] (TypeError(code: 0): Illegal offset type at /var/www/html/vendor/laravel/framework/src/Illuminate/Support/ViewErrorBag.php:61)
[stacktrace]
#0 /var/www/html/vendor/laravel/framework/src/Illuminate/Http/RedirectResponse.php(142): Illuminate\\Support\\ViewErrorBag->put()
#1 /var/www/html/app/Exceptions/Handler.php(220): Illuminate\\Http\\RedirectResponse->withErrors()
#2 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(481): FireflyIII\\Exceptions\\Handler->invalid()
#3 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(365): Illuminate\\Foundation\\Exceptions\\Handler->convertValidationExceptionToResponse()
#4 /var/www/html/app/Exceptions/Handler.php(130): Illuminate\\Foundation\\Exceptions\\Handler->render()
#5 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(51): FireflyIII\\Exceptions\\Handler->render()
#6 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(143): Illuminate\\Routing\\Pipeline->handleException()
#7 /var/www/html/app/Api/V1/Controllers/Models/Transaction/StoreController.php(68): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#8 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(162): FireflyIII\\Api\\V1\\Controllers\\Models\\Transaction\\StoreController->FireflyIII\\Api\\V1\\Controllers\\Models\\Transaction\\{closure}()
#9 /var/www/html/app/Api/V1/Controllers/Controller.php(69): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#10 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(162): FireflyIII\\Api\\V1\\Controllers\\Controller->FireflyIII\\Api\\V1\\Controllers\\{closure}()
#11 /var/www/html/app/Http/Middleware/Binder.php(78): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#12 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): FireflyIII\\Http\\Middleware\\Binder->handle()
#13 /var/www/html/app/Http/Middleware/Authenticate.php(75): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#14 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): FireflyIII\\Http\\Middleware\\Authenticate->handle()
#15 /var/www/html/vendor/laravel/sanctum/src/Http/Middleware/EnsureFrontendRequestsAreStateful.php(33): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#16 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Laravel\\Sanctum\\Http\\Middleware\\EnsureFrontendRequestsAreStateful->Laravel\\Sanctum\\Http\\Middleware\\{closure}()
#17 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#18 /var/www/html/vendor/laravel/sanctum/src/Http/Middleware/EnsureFrontendRequestsAreStateful.php(34): Illuminate\\Pipeline\\Pipeline->then()
#19 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Laravel\\Sanctum\\Http\\Middleware\\EnsureFrontendRequestsAreStateful->handle()
#20 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#21 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(726): Illuminate\\Pipeline\\Pipeline->then()
#22 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(703): Illuminate\\Routing\\Router->runRouteWithinStack()
#23 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(667): Illuminate\\Routing\\Router->runRoute()
#24 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(656): Illuminate\\Routing\\Router->dispatchToRoute()
#25 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(190): Illuminate\\Routing\\Router->dispatch()
#26 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}()
#27 /var/www/html/app/Http/Middleware/InstallationId.php(52): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#28 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): FireflyIII\\Http\\Middleware\\InstallationId->handle()
#29 /var/www/html/vendor/laravel/framework/src/Illuminate/Http/Middleware/TrustProxies.php(39): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#30 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Http\\Middleware\\TrustProxies->handle()
#31 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#32 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.php(31): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#33 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\ConvertEmptyStringsToNull->handle()
#34 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#35 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php(40): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#36 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\TrimStrings->handle()
#37 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#38 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle()
#39 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(86): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#40 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance->handle()
#41 /var/www/html/app/Http/Middleware/SecureHeaders.php(51): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#42 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): FireflyIII\\Http\\Middleware\\SecureHeaders->handle()
#43 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#44 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(165): Illuminate\\Pipeline\\Pipeline->then()
#45 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(134): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter()
#46 /var/www/html/public/index.php(75): Illuminate\\Foundation\\Http\\Kernel->handle()
#47 {main}
"} 
10.42.2.64 - - [06/Jan/2023:00:38:05 -0800] "POST /api/v1/transactions HTTP/1.1" 500 4695 "-" "python-requests/2.28.1"
```
</details>

**Comment by JC5** [comment]
https://docs.firefly-iii.org/data-importer/help/faq/#why-cant-i-import-duplicate-transactions

**Comment by adyanth** [comment]
Thanks for the quick reply!

The link you pointed to is of the FIDI. The database it talks about is of FIDI or Firefly?

If Firefly, why is it not a good idea to immediately remove the transaction from the DB since the warning while deleting says that Firefly permanently deletes the entry?

**Comment by adyanth** [comment]
Also, the documentation calls out v5.8.0 on Oct 22, but that is not released, correct? I will try to delete the entries from the DB. It would be nice to include an SQL statement/table name to look out for in the FAQ.
