### ISSUE TITLE
Data conversion failes since last update of Data Importer

### ISSUE THREAD

**Issue by rel-thanu** [firefly-iii/firefly-iii#7207]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

I updated firefly iii and data importer to the newest versions available to verify if the issue #7138 got fixed. 

Now I'm running in to an error during the conversion process of the data importer (/import/convert):

`The conversion could not be started, or failed due to an error. Please check the log files. Sorry about this :( `

See logs below in Additional info, the most important one is probably this: 

`2023-03-12 09:13:37 [2023-03-12 09:13:37] local.ERROR: Undefined array key "foreign_currency_code" {"exception":"[object] (ErrorException(code: 0): Undefined array key \"foreign_currency_code\" at /var/www/html/app/Services/CSV/Conversion/Task/Accounts.php:685)`

I checked the following cases:
- Withdrawal with same currency: Works fine.
- Transfer from / to different currency: Failure

Sample files: [sample.zip](https://github.com/firefly-iii/firefly-iii/files/10950309/sample.zip)

### Debug information

Debug information generated at 2023-03-12 09:08:13 Europe/Amsterdam for Firefly III Data Importer version **1.1.0**.

| Scope | Version |
| --- | --- |
| FIDI | 1.1.0 |
| Build | 196, 11-03-2023 18:07:11 CET |
| PHP | 8.2.3 |
| Host | Linux |

| System info | Value |
| --- | --- |
| Using docker? | true |
| System TZ | Europe/Amsterdam |
| Browser TZ | Europe/Zurich |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | debug, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Interface | apache2handler |
| BCscale | 12 |
| Trusted proxies (.env) |  |

| User info | Value |
| --- | --- |
| User agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/110.0 |

### Expected behaviour

No error :)

### Additional info

```
2023-03-12 09:13:37 [2023-03-12 09:13:37] local.INFO: Converting 4 lines into transactions.  
2023-03-12 09:13:37 [2023-03-12 09:13:37] local.INFO: Now processing line 1/4.  
2023-03-12 09:13:37 [2023-03-12 09:13:37] local.DEBUG: Now in App\Services\CSV\Conversion\Routine\PseudoTransactionProcessor::processPseudoLine  
2023-03-12 09:13:37 [2023-03-12 09:13:37] local.DEBUG: Now running task App\Services\CSV\Conversion\Task\Amount  
2023-03-12 09:13:37 [2023-03-12 09:13:37] local.DEBUG: Now at the start of processAmount("")  
2023-03-12 09:13:37 [2023-03-12 09:13:37] local.DEBUG: Transaction["amount_credit"] value is not NULL ("5556.45"), assume this is the correct value.  
2023-03-12 09:13:37 [2023-03-12 09:13:37] local.DEBUG: Amount is now 5556.450000000000.  
2023-03-12 09:13:37 [2023-03-12 09:13:37] local.DEBUG: FOREIGN amount is now 5200.000000000000.  
2023-03-12 09:13:37 [2023-03-12 09:13:37] local.DEBUG: Amount 5556.450000000000 is positive, so this is probably a deposit.  
2023-03-12 09:13:37 [2023-03-12 09:13:37] local.DEBUG: Now running task App\Services\CSV\Conversion\Task\Tags  
2023-03-12 09:13:37 [2023-03-12 09:13:37] local.DEBUG: Now running task App\Services\CSV\Conversion\Task\Currency  
2023-03-12 09:13:37 [2023-03-12 09:13:37] local.DEBUG: Now running task App\Services\CSV\Conversion\Task\Accounts  
2023-03-12 09:13:37 [2023-03-12 09:13:37] local.DEBUG: Now in Accounts::process()  
2023-03-12 09:13:37 [2023-03-12 09:13:37] local.DEBUG: Now processing transaction 1 of 1  
2023-03-12 09:13:37 [2023-03-12 09:13:37] local.DEBUG: Now in Accounts::processTransaction()  
2023-03-12 09:13:37 [2023-03-12 09:13:37] local.DEBUG: Now in findAccount {"transaction_type":"deposit","id":null,"name":null,"iban":null,"number":null,"bic":null,"direction":"source"} 
2023-03-12 09:13:37 [2023-03-12 09:13:37] local.DEBUG: Default account is #5 ("Bank (USD)")  
2023-03-12 09:13:37 [2023-03-12 09:13:37] local.DEBUG: Found no account or haven't searched for one.  
2023-03-12 09:13:37 [2023-03-12 09:13:37] local.DEBUG: Default account is not null, so will return: {"id":5,"name":"Bank (USD)","type":"asset","iban":"","number":null,"bic":null,"currency_code":"USD"} 
2023-03-12 09:13:37 [2023-03-12 09:13:37] local.DEBUG: Now in findAccount {"transaction_type":"deposit","id":1,"name":null,"iban":null,"number":null,"bic":null,"direction":"destination"} 
2023-03-12 09:13:37 [2023-03-12 09:13:37] local.DEBUG: findAccount() default account is NULL.  
2023-03-12 09:13:37 [2023-03-12 09:13:37] local.DEBUG: Find by ID field.  
2023-03-12 09:13:37 [2023-03-12 09:13:37] local.DEBUG: Going to search account with ID "1"  
2023-03-12 09:13:37 [2023-03-12 09:13:37] local.DEBUG: [a] Found asset account #1 based on ID "1"  
2023-03-12 09:13:37 [2023-03-12 09:13:37] local.DEBUG: Result of findById is not null, returning: {"id":1,"name":"Bank (CHF)","type":"asset","iban":"","number":null,"bic":null,"currency_code":"CHF"} 
2023-03-12 09:13:37 [2023-03-12 09:13:37] local.DEBUG: Now in determineType::determineType("asset", "asset")  
2023-03-12 09:13:37 [2023-03-12 09:13:37] local.DEBUG: Check config for "transaction_types.account_to_transaction.asset.asset" and found "transfer". Returning "transfer"  
2023-03-12 09:13:37 [2023-03-12 09:13:37] local.DEBUG: Transaction type is set to "transfer"  
2023-03-12 09:13:37 [2023-03-12 09:13:37] local.DEBUG: Source is now: {"id":5,"name":"Bank (USD)","type":"asset","iban":"","number":null,"bic":null,"currency_code":"USD"} 
2023-03-12 09:13:37 [2023-03-12 09:13:37] local.DEBUG: Destination is now: {"id":1,"name":"Bank (CHF)","type":"asset","iban":"","number":null,"bic":null,"currency_code":"CHF"} 
2023-03-12 09:13:37 [2023-03-12 09:13:37] local.DEBUG: Transaction is a transfer, and amount is positive, will switch accounts.  
2023-03-12 09:13:37 [2023-03-12 09:13:37] local.DEBUG: Source is now: {"id":1,"name":"Bank (CHF)","type":"asset","iban":"","number":null,"bic":null,"currency_code":"CHF"} 
2023-03-12 09:13:37 [2023-03-12 09:13:37] local.DEBUG: Destination is now: {"id":5,"name":"Bank (USD)","type":"asset","iban":"","number":null,"bic":null,"currency_code":"USD"}
2023-03-12 09:13:37 [2023-03-12 09:13:37] local.ERROR: Undefined array key "foreign_currency_code" {"exception":"[object] (ErrorException(code: 0): Undefined array key \"foreign_currency_code\" at /var/www/html/app/Services/CSV/Conversion/Task/Accounts.php:685)
2023-03-12 09:13:37 [stacktrace]
2023-03-12 09:13:37 #0 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(250): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError()
2023-03-12 09:13:37 #1 /var/www/html/app/Services/CSV/Conversion/Task/Accounts.php(685): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->Illuminate\\Foundation\\Bootstrap\\{closure}()
2023-03-12 09:13:37 #2 /var/www/html/app/Services/CSV/Conversion/Task/Accounts.php(230): App\\Services\\CSV\\Conversion\\Task\\Accounts->hasAllCurrencies()
2023-03-12 09:13:37 #3 /var/www/html/app/Services/CSV/Conversion/Task/Accounts.php(55): App\\Services\\CSV\\Conversion\\Task\\Accounts->processTransaction()
2023-03-12 09:13:37 #4 /var/www/html/app/Services/CSV/Conversion/Routine/PseudoTransactionProcessor.php(169): App\\Services\\CSV\\Conversion\\Task\\Accounts->process()
2023-03-12 09:13:37 #5 /var/www/html/app/Services/CSV/Conversion/Routine/PseudoTransactionProcessor.php(141): App\\Services\\CSV\\Conversion\\Routine\\PseudoTransactionProcessor->processPseudoLine()
2023-03-12 09:13:37 #6 /var/www/html/app/Services/CSV/Conversion/RoutineManager.php(156): App\\Services\\CSV\\Conversion\\Routine\\PseudoTransactionProcessor->processPseudo()
2023-03-12 09:13:37 #7 /var/www/html/app/Http/Controllers/Import/ConversionController.php(167): App\\Services\\CSV\\Conversion\\RoutineManager->start()
2023-03-12 09:13:37 #8 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): App\\Http\\Controllers\\Import\\ConversionController->start()
2023-03-12 09:13:37 #9 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(43): Illuminate\\Routing\\Controller->callAction()
2023-03-12 09:13:37 #10 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Route.php(259): Illuminate\\Routing\\ControllerDispatcher->dispatch()
2023-03-12 09:13:37 #11 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Route.php(205): Illuminate\\Routing\\Route->runController()
2023-03-12 09:13:37 #12 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(798): Illuminate\\Routing\\Route->run()
2023-03-12 09:13:37 #13 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}()
2023-03-12 09:13:37 #14 /var/www/html/app/Http/Middleware/IsReadyForStep.php(54): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
2023-03-12 09:13:37 #15 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): App\\Http\\Middleware\\ConversionControllerMiddleware->handle()
2023-03-12 09:13:37 #16 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(50): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
2023-03-12 09:13:37 #17 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle()
2023-03-12 09:13:37 #18 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(78): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
2023-03-12 09:13:37 #19 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle()
2023-03-12 09:13:37 #20 /var/www/html/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
2023-03-12 09:13:37 #21 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle()
2023-03-12 09:13:37 #22 /var/www/html/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(121): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
2023-03-12 09:13:37 #23 /var/www/html/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(64): Illuminate\\Session\\Middleware\\StartSession->handleStatefulRequest()
2023-03-12 09:13:37 #24 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Session\\Middleware\\StartSession->handle()
2023-03-12 09:13:37 #25 /var/www/html/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
2023-03-12 09:13:37 #26 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle()
2023-03-12 09:13:37 #27 /var/www/html/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(67): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
2023-03-12 09:13:37 #28 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle()
2023-03-12 09:13:37 #29 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
2023-03-12 09:13:37 #30 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(797): Illuminate\\Pipeline\\Pipeline->then()
2023-03-12 09:13:37 #31 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(776): Illuminate\\Routing\\Router->runRouteWithinStack()
2023-03-12 09:13:37 #32 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(740): Illuminate\\Routing\\Router->runRoute()
2023-03-12 09:13:37 #33 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(729): Illuminate\\Routing\\Router->dispatchToRoute()
2023-03-12 09:13:37 #34 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(200): Illuminate\\Routing\\Router->dispatch()
2023-03-12 09:13:37 #35 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}()
2023-03-12 09:13:37 #36 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
2023-03-12 09:13:37 #37 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.php(31): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
2023-03-12 09:13:37 #38 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\ConvertEmptyStringsToNull->handle()
2023-03-12 09:13:37 #39 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
2023-03-12 09:13:37 #40 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php(40): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
2023-03-12 09:13:37 #41 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\TrimStrings->handle()
2023-03-12 09:13:37 #42 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
2023-03-12 09:13:37 #43 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle()
2023-03-12 09:13:37 #44 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(86): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
2023-03-12 09:13:37 #45 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance->handle()
2023-03-12 09:13:37 #46 /var/www/html/vendor/laravel/framework/src/Illuminate/Http/Middleware/HandleCors.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
2023-03-12 09:13:37 #47 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Http\\Middleware\\HandleCors->handle()
2023-03-12 09:13:37 #48 /var/www/html/vendor/laravel/framework/src/Illuminate/Http/Middleware/TrustProxies.php(39): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
2023-03-12 09:13:37 #49 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Http\\Middleware\\TrustProxies->handle()
2023-03-12 09:13:37 #50 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
2023-03-12 09:13:37 #51 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(175): Illuminate\\Pipeline\\Pipeline->then()
2023-03-12 09:13:37 #52 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(144): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter()
2023-03-12 09:13:37 #53 /var/www/html/public/index.php(76): Illuminate\\Foundation\\Http\\Kernel->handle()
2023-03-12 09:13:37 #54 {main}
2023-03-12 09:13:37 "}
```

**Comment by JC5** [comment]
Nice find! I'll pick it up for the next release.
