### ISSUE TITLE
Data-Importer unable to send emails in 1.2.1

### ISSUE THREAD

**Issue by MacPaille** [firefly-iii/firefly-iii#7225]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

Upgraded FF to 6.0.4 and DI to 1.2.1 (develop branch). Import is working fine but unable to send the emails with the summary.
Getting this error
```
[2023-03-13 19:06:39] production.ERROR: Cannot assign null to property App\Mail\ImportReportMail::$url of type string {"exception":"[object] (TypeError(code: 0): Cannot assign null to property App\\Mail\\ImportReportMail::$url of type string at /var/www/html/app/Mail/ImportReportMail.php:55)
[stacktrace]
#0 /var/www/html/app/Handlers/Events/ImportedTransactionsEventHandler.php(70): App\\Mail\\ImportReportMail->__construct()
#1 /var/www/html/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(441): App\\Handlers\\Events\\ImportedTransactionsEventHandler->sendReportOverMail()
#2 /var/www/html/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(249): Illuminate\\Events\\Dispatcher->Illuminate\\Events\\{closure}()
#3 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php(435): Illuminate\\Events\\Dispatcher->dispatch()
#4 /var/www/html/app/Console/AutoImports.php(213): event()
#5 /var/www/html/app/Console/AutoImports.php(158): App\\Console\\Commands\\AutoImport->importFile()
#6 /var/www/html/app/Console/Commands/AutoImport.php(88): App\\Console\\Commands\\AutoImport->importFiles()
#7 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): App\\Console\\Commands\\AutoImport->handle()
#8 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#9 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure()
#10 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(35): Illuminate\\Container\\BoundMethod::callBoundMethod()
#11 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(661): Illuminate\\Container\\BoundMethod::call()
#12 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(194): Illuminate\\Container\\Container->call()
#13 /var/www/html/vendor/symfony/console/Command/Command.php(312): Illuminate\\Console\\Command->execute()
#14 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(163): Symfony\\Component\\Console\\Command\\Command->run()
#15 /var/www/html/vendor/symfony/console/Application.php(1022): Illuminate\\Console\\Command->run()
#16 /var/www/html/vendor/symfony/console/Application.php(314): Symfony\\Component\\Console\\Application->doRunCommand()
#17 /var/www/html/vendor/symfony/console/Application.php(168): Symfony\\Component\\Console\\Application->doRun()
#18 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Application.php(102): Symfony\\Component\\Console\\Application->run()
#19 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(155): Illuminate\\Console\\Application->run()
#20 /var/www/html/artisan(35): Illuminate\\Foundation\\Console\\Kernel->handle()
#21 {main}
"} 
In ImportReportMail.php line 55:
                                                                               
  Cannot assign null to property App\Mail\ImportReportMail::$url of type stri  
  ng
```

### Debug information

No debug page available as I'm using DI without the web interface. But logs are set in debug

### Expected behaviour

Send my email :)

**Comment by JC5** [comment]
Nice find, will be fixed in the next release :+1:

**Comment by MacPaille** [comment]
Thanks for the quick fix again! I still love your tools :)

**Comment by MacPaille** [comment]
@JC5 I did update my container with the dev branch but still same error on emails...

**Comment by JC5** [comment]
I'm not sure if I added this to the build yet, try again in like 10 minutes.

**Comment by MacPaille** [comment]
I confirm working as expected now :) Thanks a lot!
