### ISSUE TITLE
Data-Importer crashing when mail server auth failed

### ISSUE THREAD

**Issue by MacPaille** [firefly-iii/firefly-iii#7264]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

Today my container crashed after my first account import as apparently it failed to auth on gmail (see logs below):

```
[2023-03-21 19:08:32] production.ERROR: Failed to authenticate on SMTP server with username "c.goset@gmail.com" using the following authenticators: "LOGIN", "PLAIN", "XOAUTH2". Authenticator "LOGIN" returned "Connection to "smtp.gmail.com:587" timed out.". Authenticator "PLAIN" returned "Expected response code "235" but got code "250", with message "250 2.1.5 Flushed h13-20020a5d430d000000b002d75ef32032sm4936560wrq.68 - gsmtp".". Authenticator "XOAUTH2" returned "Expected response code "235" but got code "250", with message "250 2.1.5 Flushed h13-20020a5d430d000000b002d75ef32032sm4936560wrq.68 - gsmtp".". {"exception":"[object] (Symfony\\Component\\Mailer\\Exception\\TransportException(code: 250): Failed to authenticate on SMTP server with username \"c.goset@gmail.com\" using the following authenticators: \"LOGIN\", \"PLAIN\", \"XOAUTH2\". Authenticator \"LOGIN\" returned \"Connection to \"smtp.gmail.com:587\" timed out.\". Authenticator \"PLAIN\" returned \"Expected response code \"235\" but got code \"250\", with message \"250 2.1.5 Flushed h13-20020a5d430d000000b002d75ef32032sm4936560wrq.68 - gsmtp\".\". Authenticator \"XOAUTH2\" returned \"Expected response code \"235\" but got code \"250\", with message \"250 2.1.5 Flushed h13-20020a5d430d000000b002d75ef32032sm4936560wrq.68 - gsmtp\".\". at /var/www/html/vendor/symfony/mailer/Transport/Smtp/EsmtpTransport.php:212)
[stacktrace]
#0 /var/www/html/vendor/symfony/mailer/Transport/Smtp/EsmtpTransport.php(148): Symfony\\Component\\Mailer\\Transport\\Smtp\\EsmtpTransport->handleAuth()
#1 /var/www/html/vendor/symfony/mailer/Transport/Smtp/EsmtpTransport.php(105): Symfony\\Component\\Mailer\\Transport\\Smtp\\EsmtpTransport->doEhloCommand()
#2 /var/www/html/vendor/symfony/mailer/Transport/Smtp/SmtpTransport.php(254): Symfony\\Component\\Mailer\\Transport\\Smtp\\EsmtpTransport->executeCommand()
#3 /var/www/html/vendor/symfony/mailer/Transport/Smtp/SmtpTransport.php(277): Symfony\\Component\\Mailer\\Transport\\Smtp\\SmtpTransport->doHeloCommand()
#4 /var/www/html/vendor/symfony/mailer/Transport/Smtp/SmtpTransport.php(213): Symfony\\Component\\Mailer\\Transport\\Smtp\\SmtpTransport->start()
#5 /var/www/html/vendor/symfony/mailer/Transport/AbstractTransport.php(69): Symfony\\Component\\Mailer\\Transport\\Smtp\\SmtpTransport->doSend()
#6 /var/www/html/vendor/symfony/mailer/Transport/Smtp/SmtpTransport.php(137): Symfony\\Component\\Mailer\\Transport\\AbstractTransport->send()
#7 /var/www/html/vendor/laravel/framework/src/Illuminate/Mail/Mailer.php(539): Symfony\\Component\\Mailer\\Transport\\Smtp\\SmtpTransport->send()
#8 /var/www/html/vendor/laravel/framework/src/Illuminate/Mail/Mailer.php(303): Illuminate\\Mail\\Mailer->sendSymfonyMessage()
#9 /var/www/html/vendor/laravel/framework/src/Illuminate/Mail/Mailable.php(205): Illuminate\\Mail\\Mailer->send()
#10 /var/www/html/vendor/laravel/framework/src/Illuminate/Support/Traits/Localizable.php(19): Illuminate\\Mail\\Mailable->Illuminate\\Mail\\{closure}()
#11 /var/www/html/vendor/laravel/framework/src/Illuminate/Mail/Mailable.php(198): Illuminate\\Mail\\Mailable->withLocale()
#12 /var/www/html/vendor/laravel/framework/src/Illuminate/Mail/Mailer.php(325): Illuminate\\Mail\\Mailable->send()
#13 /var/www/html/vendor/laravel/framework/src/Illuminate/Mail/Mailer.php(269): Illuminate\\Mail\\Mailer->sendMailable()
#14 /var/www/html/vendor/laravel/framework/src/Illuminate/Mail/PendingMail.php(124): Illuminate\\Mail\\Mailer->send()
#15 /var/www/html/app/Handlers/Events/ImportedTransactionsEventHandler.php(70): Illuminate\\Mail\\PendingMail->send()
#16 /var/www/html/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(441): App\\Handlers\\Events\\ImportedTransactionsEventHandler->sendReportOverMail()
#17 /var/www/html/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(249): Illuminate\\Events\\Dispatcher->Illuminate\\Events\\{closure}()
#18 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php(435): Illuminate\\Events\\Dispatcher->dispatch()
#19 /var/www/html/app/Console/AutoImports.php(213): event()
#20 /var/www/html/app/Console/AutoImports.php(158): App\\Console\\Commands\\AutoImport->importFile()
#21 /var/www/html/app/Console/Commands/AutoImport.php(88): App\\Console\\Commands\\AutoImport->importFiles()
#22 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): App\\Console\\Commands\\AutoImport->handle()
#23 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#24 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure()
#25 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(35): Illuminate\\Container\\BoundMethod::callBoundMethod()
#26 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(661): Illuminate\\Container\\BoundMethod::call()
#27 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(194): Illuminate\\Container\\Container->call()
#28 /var/www/html/vendor/symfony/console/Command/Command.php(312): Illuminate\\Console\\Command->execute()
#29 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(163): Symfony\\Component\\Console\\Command\\Command->run()
#30 /var/www/html/vendor/symfony/console/Application.php(1022): Illuminate\\Console\\Command->run()
#31 /var/www/html/vendor/symfony/console/Application.php(314): Symfony\\Component\\Console\\Application->doRunCommand()
#32 /var/www/html/vendor/symfony/console/Application.php(168): Symfony\\Component\\Console\\Application->doRun()
#33 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Application.php(102): Symfony\\Component\\Console\\Application->run()
#34 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(155): Illuminate\\Console\\Application->run()
#35 /var/www/html/artisan(35): Illuminate\\Foundation\\Console\\Kernel->handle()
#36 {main}
"} 
In EsmtpTransport.php line 212:
                                                                               
  Failed to authenticate on SMTP server with username "c.goset@gmail.com" usi  
  ng the following authenticators: "LOGIN", "PLAIN", "XOAUTH2". Authenticator  
   "LOGIN" returned "Connection to "smtp.gmail.com:587" timed out.". Authenti  
  cator "PLAIN" returned "Expected response code "235" but got code "250", wi  
  th message "250 2.1.5 Flushed h13-20020a5d430d000000b002d75ef32032sm4936560  
  wrq.68 - gsmtp".". Authenticator "XOAUTH2" returned "Expected response code  
   "235" but got code "250", with message "250 2.1.5 Flushed h13-20020a5d430d  
  000000b002d75ef32032sm4936560wrq.68 - gsmtp".".
```

### Debug information

None available as running in cli mode (without web interface) but logs provided are in debug

### Expected behaviour

Failed auth is an issue for sure but exception should be handled and application should not crash 😄 

Also if handled correctly it would be nice to write a message at the end of the logs right before it stops itself as I have multiple accounts and looking at all the lines in debug mode to see what was wrong (on a regular day I have 12K+ lines in the logs...)

**Comment by MacPaille** [comment]
FYI it should have been a temporary issue as I started again my container and now I receive the emails

**Comment by JC5** [comment]
Thx! Which version of the data importer?

**Comment by MacPaille** [comment]
Indeed totally forgot to provide it... I always use the dev branch.

Build number:  204
Build date:    18-03-2023 14:55:12 CET
Firefly III data importer v1.2.2

**Comment by JC5** [comment]
This should be fixed in build 205 :+1:

**Comment by MacPaille** [comment]
Thanks a lot! Can't really test it as it's the first time I got a timeout with google 😄
