### ISSUE TITLE
Error : Traits cannot have constants 

### ISSUE THREAD

**Issue by vimalrajks** [firefly-iii/firefly-iii#7270]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

Whoops! An error occurred.

Unfortunately, this error was not recoverable :(. Firefly III broke. The error is:

Traits cannot have constants
More information 

### Debug information

```
Truncated from this point <----|\xampp\\htdocs\\firefly-iii-6.0.5\\app\\Http\\Middleware\\SecureHeaders.php(51): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#45 E:\\xampp\\htdocs\\firefly-iii-6.0.5\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(180): FireflyIII\\Http\\Middleware\\SecureHeaders->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#46 E:\\xampp\\htdocs\\firefly-iii-6.0.5\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(116): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#47 E:\\xampp\\htdocs\\firefly-iii-6.0.5\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Kernel.php(175): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#48 E:\\xampp\\htdocs\\firefly-iii-6.0.5\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Kernel.php(144): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#49 E:\\xampp\\htdocs\\firefly-iii-6.0.5\\public\\index.php(74): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#50 {main}
"} 
[2023-03-24 04:28:59] local.ERROR: Exception is: {"class":"Symfony\\Component\\ErrorHandler\\Error\\FatalError","errorMessage":"Traits cannot have constants","time":"Fri, 24 Mar 2023 04:28:59 +0530","file":"E:\\xampp\\htdocs\\firefly-iii-6.0.5\\app\\Helpers\\Collector\\Extensions\\CollectorProperties.php","line":35,"code":0,"version":"6.0.5","url":"http:\/\/localhost\/firefly-iii-6.0.5\/public","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko\/20100101 Firefox\/111.0","json":true,"method":"GET"}  
[2023-03-24 04:29:00] local.WARNING: [Bcc] Could not email or log the error. Please validate your email settings, use the .env.example file as a guide.  
[2023-03-24 04:29:00] local.ERROR: Traits cannot have constants {"userId":1,"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Traits cannot have constants at E:\\xampp\\htdocs\\firefly-iii-6.0.5\\app\\Helpers\\Collector\\Extensions\\CollectorProperties.php:35)
[stacktrace]
#0 {main}
"} 
[2023-03-24 04:29:46] local.ERROR: Exception is: {"class":"Symfony\\Component\\ErrorHandler\\Error\\FatalError","errorMessage":"Traits cannot have constants","time":"Fri, 24 Mar 2023 04:29:46 +0530","file":"E:\\xampp\\htdocs\\firefly-iii-6.0.5\\app\\Helpers\\Collector\\Extensions\\CollectorProperties.php","line":35,"code":0,"version":"6.0.5","url":"http:\/\/localhost\/firefly-iii-6.0.5\/public","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko\/20100101 Firefox\/111.0","json":true,"method":"GET"}  
[2023-03-24 04:29:46] local.WARNING: [Bcc] Could not email or log the error. Please validate your email settings, use the .env.example file as a guide.  
[2023-03-24 04:29:46] local.ERROR: Traits cannot have constants {"userId":1,"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Traits cannot have constants at E:\\xampp\\htdocs\\firefly-iii-6.0.5\\app\\Helpers\\Collector\\Extensions\\CollectorProperties.php:35)
[stacktrace]
#0 {main}
"} 
[2023-03-24 04:33:29] local.ERROR: Exception is: {"class":"Symfony\\Component\\ErrorHandler\\Error\\FatalError","errorMessage":"Traits cannot have constants","time":"Fri, 24 Mar 2023 04:33:29 +0530","file":"E:\\xampp\\htdocs\\firefly-iii-6.0.5\\app\\Helpers\\Collector\\Extensions\\CollectorProperties.php","line":35,"code":0,"version":"6.0.5","url":"http:\/\/localhost\/firefly-iii-6.0.5\/public","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko\/20100101 Firefox\/111.0","json":true,"method":"GET"}  
[2023-03-24 04:33:30] local.WARNING: [Bcc] Could not email or log the error. Please validate your email settings, use the .env.example file as a guide.  
[2023-03-24 04:33:30] local.ERROR: Traits cannot have constants {"userId":1,"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Traits cannot have constants at E:\\xampp\\htdocs\\firefly-iii-6.0.5\\app\\Helpers\\Collector\\Extensions\\CollectorProperties.php:35)
[stacktrace]
#0 {main}
"} 
[2023-03-24 04:36:06] local.ERROR: Exception is: {"class":"Symfony\\Component\\ErrorHandler\\Error\\FatalError","errorMessage":"Traits cannot have constants","time":"Fri, 24 Mar 2023 04:36:06 +0530","file":"E:\\xampp\\htdocs\\firefly-iii-6.0.5\\app\\Helpers\\Collector\\Extensions\\CollectorProperties.php","line":35,"code":0,"version":"6.0.5","url":"http:\/\/localhost\/firefly-iii-6.0.5\/public","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko\/20100101 Firefox\/111.0","json":true,"method":"GET"}  
[2023-03-24 04:36:06] local.WARNING: [Bcc] Could not email or log the error. Please validate your email settings, use the .env.example file as a guide.  
[2023-03-24 04:36:06] local.ERROR: Traits cannot have constants {"userId":1,"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Traits cannot have constants at E:\\xampp\\htdocs\\firefly-iii-6.0.5\\app\\Helpers\\Collector\\Extensions\\CollectorProperties.php:35)
[stacktrace]
#0 {main}
"} 
[2023-03-24 04:36:27] local.ERROR: Exception is: {"class":"Symfony\\Component\\ErrorHandler\\Error\\FatalError","errorMessage":"Traits cannot have constants","time":"Fri, 24 Mar 2023 04:36:27 +0530","file":"E:\\xampp\\htdocs\\firefly-iii-6.0.5\\app\\Helpers\\Collector\\Extensions\\CollectorProperties.php","line":35,"code":0,"version":"6.0.5","url":"http:\/\/localhost\/firefly-iii-6.0.5\/public","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko\/20100101 Firefox\/111.0","json":true,"method":"GET"}  
[2023-03-24 04:36:27] local.WARNING: [Bcc] Could not email or log the error. Please validate your email settings, use the .env.example file as a guide.  
[2023-03-24 04:36:27] local.ERROR: Traits cannot have constants {"userId":1,"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Traits cannot have constants at E:\\xampp\\htdocs\\firefly-iii-6.0.5\\app\\Helpers\\Collector\\Extensions\\CollectorProperties.php:35)
[stacktrace]
#0 {main}
"} 
[2023-03-24 04:39:17] local.ERROR: Exception is: {"class":"Symfony\\Component\\ErrorHandler\\Error\\FatalError","errorMessage":"Traits cannot have constants","time":"Fri, 24 Mar 2023 04:39:17 +0530","file":"E:\\xampp\\htdocs\\firefly-iii-6.0.5\\app\\Helpers\\Collector\\Extensions\\CollectorProperties.php","line":35,"code":0,"version":"6.0.5","url":"http:\/\/localhost\/firefly-iii-6.0.5\/public","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko\/20100101 Firefox\/111.0","json":true,"method":"GET"}  
[2023-03-24 04:39:17] local.WARNING: [Bcc] Could not email or log the error. Please validate your email settings, use the .env.example file as a guide.  
[2023-03-24 04:39:17] local.ERROR: Traits cannot have constants {"userId":1,"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Traits cannot have constants at E:\\xampp\\htdocs\\firefly-iii-6.0.5\\app\\Helpers\\Collector\\Extensions\\CollectorProperties.php:35)
[stacktrace]
#0 {main}
"} 
[2023-03-24 04:39:19] local.ERROR: Exception is: {"class":"Symfony\\Component\\ErrorHandler\\Error\\FatalError","errorMessage":"Traits cannot have constants","time":"Fri, 24 Mar 2023 04:39:19 +0530","file":"E:\\xampp\\htdocs\\firefly-iii-6.0.5\\app\\Helpers\\Collector\\Extensions\\CollectorProperties.php","line":35,"code":0,"version":"6.0.5","url":"http:\/\/localhost\/firefly-iii-6.0.5\/public","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko\/20100101 Firefox\/111.0","json":true,"method":"GET"}  
[2023-03-24 04:39:19] local.WARNING: [Bcc] Could not email or log the error. Please validate your email settings, use the .env.example file as a guide.  
[2023-03-24 04:39:19] local.ERROR: Traits cannot have constants {"userId":1,"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Traits cannot have constants at E:\\xampp\\htdocs\\firefly-iii-6.0.5\\app\\Helpers\\Collector\\Extensions\\CollectorProperties.php:35)
[stacktrace]
#0 {main}
"} 

```

**Comment by JC5** [comment]
Please upgrade to PHP 8.2.
