### ISSUE TITLE
Import data fails: `Time out while waiting for job to finish.`

### ISSUE THREAD

**Issue by tterpelle** [firefly-iii/firefly-iii#752]
When I try to import my bank statements in .csv format via the web page, I get the following error:

```
A fatal error occurred
A fatal error occurred, which the import-routine cannot recover from. Please see the explanation in red below.

Time out while waiting for job to finish.

If the error is a time-out, the import will have stopped half-way. For some server configurations, it is merely the server that stopped while the import keeps running in the background. To verify this, check out the log files. If the problem persists, consider importing over the command line instead.
```

If I run the import on the command line with the command provided by the import wizard, it fails with

```
root@php7:/var/www/html/firefly-iii# php artisan firefly:start-import abYtFkebLplM
Going to import job with key "abYtFkebLplM" of type "csv"
[2017-08-11 22:14:24] production.ERROR: Exception is: {"class":"Symfony\\Component\\Debug\\Exception\\FatalThrowableError","errorMessage":"Type error: hash() expects parameter 2 to be string, boolean given","time":"Fri, 11 Aug 2017 22:14:24 +0000","file":"\/var\/www\/html\/firefly-iii\/app\/Import\/FileProcessor\/CsvProcessor.php","line":168,"code":0,"version":"4.6.3.1"} [] []
[2017-08-11 22:14:24] production.ERROR: Symfony\Component\Debug\Exception\FatalThrowableError: Type error: hash() expects parameter 2 to be string, boolean given in /var/www/html/firefly-iii/app/Import/FileProcessor/CsvProcessor.php:168 Stack trace: #0 /var/www/html/firefly-iii/app/Import/FileProcessor/CsvProcessor.php(168): hash('sha256', false) #1 /var/www/html/firefly-iii/app/Import/FileProcessor/CsvProcessor.php(81): FireflyIII\Import\FileProcessor\CsvProcessor->importRow(23, Array) #2 /var/www/html/firefly-iii/app/Import/Routine/ImportRoutine.php(116): FireflyIII\Import\FileProcessor\CsvProcessor->run() #3 /var/www/html/firefly-iii/app/Import/Routine/ImportRoutine.php(60): FireflyIII\Import\Routine\ImportRoutine->getImportObjects() #4 /var/www/html/firefly-iii/app/Console/Commands/Import.php(81): FireflyIII\Import\Routine\ImportRoutine->run() #5 [internal function]: FireflyIII\Console\Commands\Import->handle() #6 /var/www/html/firefly-iii/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(29): call_user_func_array(Array, Array) #7 /var/www/html/firefly-iii/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(87): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}() #8 /var/www/html/firefly-iii/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(31): Illuminate\Container\BoundMethod::callBoundMethod(Object(Illuminate\Foundation\Application), Array, Object(Closure)) #9 /var/www/html/firefly-iii/vendor/laravel/framework/src/Illuminate/Container/Container.php(539): Illuminate\Container\BoundMethod::call(Object(Illuminate\Foundation\Application), Array, Array, NULL) #10 /var/www/html/firefly-iii/vendor/laravel/framework/src/Illuminate/Console/Command.php(182): Illuminate\Container\Container->call(Array) #11 /var/www/html/firefly-iii/vendor/symfony/console/Command/Command.php(264): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle)) #12 /var/www/html/firefly-iii/vendor/laravel/framework/src/Illuminate/Console/Command.php(167): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle)) #13 /var/www/html/firefly-iii/vendor/symfony/console/Application.php(869): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #14 /var/www/html/firefly-iii/vendor/symfony/console/Application.php(223): Symfony\Component\Console\Application->doRunCommand(Object(FireflyIII\Console\Commands\Import), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #15 /var/www/html/firefly-iii/vendor/symfony/console/Application.php(130): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #16 /var/www/html/firefly-iii/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(122): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #17 /var/www/html/firefly-iii/artisan(35): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #18 {main} [] []

                                                                      
  [Symfony\Component\Debug\Exception\FatalThrowableError]             
  Type error: hash() expects parameter 2 to be string, boolean given  
                                                                      

root@php7:/var/www/html/firefly-iii# 
root@php7:/var/www/html/firefly-iii#  Download configuration  Start the import
-su: Download: command not found
root@php7:/var/www/html/firefly-iii# 
```

# Steps to reproduce

- `Import and export`
- `Import data`
- `Import file` -> select .csv with bank statements
- `Configuration file` -> select config file with settings for import
- `Start importing`

# System info

`firefly-4.6.3.1`

```
Distributor ID:	Debian
Description:	Debian GNU/Linux 9.0 (stretch)
Release:	9.0
Codename:	stretch
```

```
PHP 7.0.19-1 (cli) (built: May 11 2017 14:04:47) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.0.19-1, Copyright (c) 1999-2017, by Zend Technologies
```

**Comment by JC5** [comment]
This happens when the current row (from your CSV file) can't be properly encoded into JSON, which is a step in the import process to prevent duplicates.

I will add an error check for the JSON routine but the root cause is something in the file you're trying to import. Is the CSV file UTF-8 encoded?

**Comment by tterpelle** [comment]
I wrote a Python script to parse the .csv files with statements provided by my bank. They're quite horrible.

I made sure the output generated from my script was UTF-8, and now the import succeeds! Thanks for the tip!

Relevant .py:

```
#!/usr/bin/env python

import io
...
# open output file
with io.open(outputFile, 'w', encoding='utf-8') as o:
...
  # write a line to the output file
  outputLine = 'field1;field2;field3;field4;'
  o.write(unicode(outputLine + "\n", 'utf-8', errors='replace'))
...
```
