### ISSUE TITLE
Installation problem - Uncaught ReflectionException: Class auth does not exist

### ISSUE THREAD

**Issue by jasonhunt148** [firefly-iii/firefly-iii#758]
I'm getting this error when running a fresh install:

> Fatal error: Uncaught ReflectionException: Class auth does not exist in /usr/local/www/nginx/firefly-iii/vendor/laravel/framework/src/Illuminate/Container/Container.php:729

I found issue #332 with same error but they fixed it with a fresh install. Searching on the web hasn't given me any good clues.  Any suggestions?

```
root@web:/usr/local/www/nginx # rm -rf firefly-iii/
root@web:/usr/local/www/nginx # composer clear-cache
Cache directory does not exist (cache-vcs-dir): 
Clearing cache (cache-repo-dir): /root/.composer/cache/repo
Clearing cache (cache-files-dir): /root/.composer/cache/files
Clearing cache (cache-dir): /root/.composer/cache
All caches cleared.
root@web:/usr/local/www/nginx # composer create-project grumpydictator/firefly-iii --no-dev --prefer-dist firefly-iii
Installing grumpydictator/firefly-iii (4.6.3.1)
  - Installing grumpydictator/firefly-iii (4.6.3.1): Downloading (100%)         
Created project in firefly-iii
> php -r "file_exists('.env') || copy('.env.example', '.env');"
Loading composer repositories with package information
Installing dependencies from lock file
Package operations: 44 installs, 0 updates, 0 removals
  - Installing bacon/bacon-qr-code (1.0.1): Downloading (100%)         
  - Installing vlucas/phpdotenv (v2.4.0): Downloading (100%)         
  - Installing symfony/css-selector (v3.1.10): Downloading (100%)         
  - Installing tijsverkoyen/css-to-inline-styles (2.2.0): Downloading (100%)         
  - Installing symfony/polyfill-mbstring (v1.4.0): Downloading (100%)         
  - Installing symfony/var-dumper (v3.3.5): Downloading (100%)         
  - Installing symfony/routing (v3.3.5): Downloading (100%)         
  - Installing symfony/process (v3.3.5): Downloading (100%)         
  - Installing symfony/http-foundation (v3.3.5): Downloading (100%)         
  - Installing symfony/event-dispatcher (v2.8.25): Downloading (100%)         
  - Installing psr/log (1.0.2): Downloading (100%)         
  - Installing symfony/debug (v3.3.5): Downloading (100%)         
  - Installing symfony/http-kernel (v3.3.0): Downloading (100%)         
  - Installing symfony/finder (v3.3.5): Downloading (100%)         
  - Installing symfony/console (v3.3.5): Downloading (100%)         
  - Installing swiftmailer/swiftmailer (v5.4.8): Downloading (100%)         
  - Installing paragonie/random_compat (v2.0.10): Downloading (100%)         
  - Installing ramsey/uuid (3.6.1): Downloading (100%)         
  - Installing symfony/translation (v3.3.5): Downloading (100%)         
  - Installing nesbot/carbon (1.22.1): Downloading (100%)         
  - Installing mtdowling/cron-expression (v1.2.0): Downloading (100%)         
  - Installing monolog/monolog (1.23.0): Downloading (100%)         
  - Installing league/flysystem (1.0.40): Downloading (100%)         
  - Installing erusev/parsedown (1.6.3): Downloading (100%)         
  - Installing doctrine/inflector (v1.2.0): Downloading (100%)         
  - Installing laravel/framework (v5.4.30): Downloading (100%)         
  - Installing davejamesmiller/laravel-breadcrumbs (3.0.3): Downloading (100%)         
  - Installing doctrine/lexer (v1.0.1): Downloading (100%)         
  - Installing doctrine/annotations (v1.4.0): Downloading (100%)         
  - Installing doctrine/cache (v1.6.2): Downloading (100%)         
  - Installing doctrine/collections (v1.4.0): Downloading (100%)         
  - Installing doctrine/common (v2.7.3): Downloading (100%)         
  - Installing doctrine/dbal (v2.5.13): Downloading (100%)         
  - Installing laravelcollective/html (v5.4.8): Downloading (100%)         
  - Installing league/commonmark (0.15.4): Downloading (100%)         
  - Installing league/csv (8.2.2): Downloading (100%)         
  - Installing symfony/polyfill-util (v1.4.0): Downloading (100%)         
  - Installing symfony/polyfill-php56 (v1.4.0): Downloading (100%)         
  - Installing christian-riesen/base32 (1.3.1): Downloading (100%)         
  - Installing pragmarx/google2fa (v1.0.1): Downloading (100%)         
  - Installing twig/twig (v1.30.0): Downloading (100%)         
  - Installing rcrowe/twigbridge (v0.9.4): Downloading (100%)         
  - Installing rmccue/requests (v1.7.0): Downloading (100%)         
  - Installing watson/validating (3.0.1): Downloading (100%)         
Generating autoload files
> Illuminate\Foundation\ComposerScripts::postInstall
> php artisan optimize

Fatal error: Uncaught ReflectionException: Class auth does not exist in /usr/local/www/nginx/firefly-iii/vendor/laravel/framework/src/Illuminate/Container/Container.php:729
Stack trace:
#0 /usr/local/www/nginx/firefly-iii/vendor/laravel/framework/src/Illuminate/Container/Container.php(729): ReflectionClass->__construct('auth')
#1 /usr/local/www/nginx/firefly-iii/vendor/laravel/framework/src/Illuminate/Container/Container.php(608): Illuminate\Container\Container->build('auth')
#2 /usr/local/www/nginx/firefly-iii/vendor/laravel/framework/src/Illuminate/Container/Container.php(575): Illuminate\Container\Container->resolve('auth')
#3 /usr/local/www/nginx/firefly-iii/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(728): Illuminate\Container\Container->make('auth')
#4 /usr/local/www/nginx/firefly-iii/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php(106): Illuminate\Foundation\Application->make('auth')
#5 /usr/local/www/nginx/firefly-iii/vendor/laravel/framework/src/Illuminate/Foundation/helpers. in /usr/local/www/nginx/firefly-iii/vendor/laravel/framework/src/Illuminate/Container/Container.php on line 729
Script php artisan optimize handling the post-install-cmd event returned with error code 255
```

**Comment by jasonhunt148** [comment]
I finally figured it out; I had the PHP mysqli extension installed, not the regular mysql one. Installed the mysql extension and all is good now.

Looking forward to trying out firefly
