### ISSUE TITLE
Country flag emoji won't work in asset account name

### ISSUE THREAD

**Issue by marcusique** [firefly-iii/firefly-iii#7722]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

Hi there,

I use many currencies and to simplify the asset account view I want to add country flags to account names. For example, I have one Revolut bank account with two currencies – Danish krone and Swedish krona.
The current account names I use are

```
Revolut Dkr
Revolut Skr
```
and would like to change that to
```
Revolut 🇩🇰
Revolut 🇸🇪
```
When I change `Revolut Dkr `to `Revolut 🇩🇰` everything works fine, but when after that I rename `Revolut Skr` to `Revolut 🇸🇪` then Firefly throws an error `This account name is already in use.`
<img width="477" alt="Screenshot 2023-07-05 at 17 01 16" src="https://github.com/firefly-iii/firefly-iii/assets/23212368/6f47f4d8-173a-4ceb-8acb-8b1f951be6a3">

Whenever I use any other emoji (other than country flags that it), then it works just fine.

### Debug information

Debug information generated at 2023-07-05 16:56:47 Europe/Copenhagen for Firefly III version **6.0.16**.

| Scope | Version |
| --- | --- |
| Firefly III | 6.0.16 |
| Firefly III API | 2.0.4 |
| Build | 506, 27-06-2023 13:09:05 UTC |
| Base Build | 10, 21-06-2023 21:55:03 CEST |
| DB version | 19 (exp. 19) |
| PHP | `8.2.7` |
| Host | `Linux` |

| System info | Value |
| --- | --- |
| System TZ | Europe/Copenhagen |
| Browser TZ | Europe/Stockholm |
| App environment | local |
| App debug mode | false |
| App cache driver | file |
| App logging | info, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Max upload | 67108864 (64 MB) |
| Interface | apache2handler |
| Default language | en_US |
| Default locale | equal |
| BCscale | 12 |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | mysql |
| Trusted proxies (.env) | `**` |

| User info | Value |
| --- | --- |
| Login provider | eloquent  |
| User guard | web  |
| Headers | N/A, N/A  |
| Stateful domains |  |
| Session start | 2023-07-01 00:00:00 |
| Session end | 2023-07-05 23:59:59 |
| Session first | 2020-07-27 00:00:00 |
| User ID | 1 |
| User language | en_US |
| User locale | en_US |
| Attempt at "en_US.utf8" | 'en_US.utf8' |
| Attempt at "en_US.UTF-8" | 'en_US.UTF-8' |
| User agent | Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.5.1 Safari/605.1.15 |

### Expected behaviour

Accounts with the same alphanumeric name but different country flags are created successfully.

### Steps to reproduce

1. Open Accounts -> Asset accounts
2. Create new account
3. Enter name (e.g. My Bank 🇸🇪), save
4. Create another asset account
5. Enter name (e.g. My Bank 🇩🇰), save

### Additional info

```
Truncated from this point <----|e\\Pipeline\\{closure}()
#49 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Http\\Middleware\\TrustProxies->handle()
#50 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#51 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.php(31): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#52 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\ConvertEmptyStringsToNull->handle()
#53 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#54 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php(40): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#55 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\TrimStrings->handle()
#56 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#57 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle()
#58 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(86): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#59 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance->handle()
#60 /var/www/html/app/Http/Middleware/SecureHeaders.php(51): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#61 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): FireflyIII\\Http\\Middleware\\SecureHeaders->handle()
#62 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#63 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(175): Illuminate\\Pipeline\\Pipeline->then()
#64 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(144): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter()
#65 /var/www/html/public/index.php(73): Illuminate\\Foundation\\Http\\Kernel->handle()
#66 {main}
"} 
[2023-07-05 08:08:45] local.INFO: Ignore search operator "user_action"  
[2023-07-05 08:08:45] local.INFO: Ignore search operator "user_action"  
[2023-07-05 08:08:45] local.INFO: Ignore search operator "user_action"  
[2023-07-05 08:08:45] local.INFO: Ignore search operator "user_action"  
[2023-07-05 08:08:45] local.INFO: Ignore search operator "user_action"  
[2023-07-05 08:10:12] local.INFO: Ignore search operator "user_action"  
[2023-07-05 08:10:12] local.INFO: Ignore search operator "user_action"  
[2023-07-05 08:10:12] local.INFO: Ignore search operator "user_action"  
[2023-07-05 08:10:12] local.INFO: Ignore search operator "user_action"  
[2023-07-05 08:10:12] local.INFO: Ignore search operator "user_action"  
[2023-07-05 15:39:31] local.INFO: User is trying to login.  
[2023-07-05 16:08:20] local.INFO: User is trying to login.  
[2023-07-05 16:09:14] local.INFO: Detected invalid IBAN (""). Return NULL instead.  
[2023-07-05 16:11:20] local.INFO: Ignore search operator "user_action"  
[2023-07-05 16:11:20] local.INFO: Ignore search operator "user_action"  
[2023-07-05 16:11:20] local.INFO: Ignore search operator "user_action"  
[2023-07-05 16:11:20] local.INFO: Ignore search operator "user_action"  
[2023-07-05 16:11:20] local.INFO: Ignore search operator "user_action"  
[2023-07-05 16:12:28] local.INFO: Ignore search operator "user_action"  
[2023-07-05 16:12:28] local.INFO: Ignore search operator "user_action"  
[2023-07-05 16:12:28] local.INFO: Ignore search operator "user_action"  
[2023-07-05 16:12:28] local.INFO: Ignore search operator "user_action"  
[2023-07-05 16:12:28] local.INFO: Ignore search operator "user_action"  
[2023-07-05 16:13:03] local.INFO: Account info is valid, now update.  
[2023-07-05 16:13:03] local.INFO: Not enough info to update foreign currency info.  
[2023-07-05 16:13:55] local.INFO: Ignore search operator "user_action"  
[2023-07-05 16:13:55] local.INFO: Ignore search operator "user_action"  
[2023-07-05 16:13:55] local.INFO: Ignore search operator "user_action"  
[2023-07-05 16:13:55] local.INFO: Ignore search operator "user_action"  
[2023-07-05 16:13:55] local.INFO: Ignore search operator "user_action"  
[2023-07-05 16:14:42] local.INFO: Ignore search operator "user_action"  
[2023-07-05 16:14:42] local.INFO: Ignore search operator "user_action"  
[2023-07-05 16:14:42] local.INFO: Ignore search operator "user_action"  
[2023-07-05 16:14:42] local.INFO: Ignore search operator "user_action"  
[2023-07-05 16:14:42] local.INFO: Ignore search operator "user_action"  
[2023-07-05 16:15:44] local.INFO: Ignore search operator "user_action"  
[2023-07-05 16:15:44] local.INFO: Ignore search operator "user_action"  
[2023-07-05 16:15:44] local.INFO: Ignore search operator "user_action"  
[2023-07-05 16:15:44] local.INFO: Ignore search operator "user_action"  
[2023-07-05 16:15:44] local.INFO: Ignore search operator "user_action"  
[2023-07-05 16:16:20] local.INFO: Ignore search operator "user_action"  
[2023-07-05 16:16:21] local.INFO: Ignore search operator "user_action"  
[2023-07-05 16:16:21] local.INFO: Ignore search operator "user_action"  
[2023-07-05 16:16:21] local.INFO: Ignore search operator "user_action"  
[2023-07-05 16:16:21] local.INFO: Ignore search operator "user_action"  
[2023-07-05 16:17:00] local.INFO: Account info is valid, now update.  
[2023-07-05 16:17:00] local.INFO: Not enough info to update foreign currency info.  
[2023-07-05 16:18:01] local.INFO: Ignore search operator "user_action"  
[2023-07-05 16:18:01] local.INFO: Ignore search operator "user_action"  
[2023-07-05 16:18:01] local.INFO: Ignore search operator "user_action"  
[2023-07-05 16:18:01] local.INFO: Ignore search operator "user_action"  
[2023-07-05 16:18:01] local.INFO: Ignore search operator "user_action"  
[2023-07-05 16:18:48] local.INFO: Ignore search operator "user_action"  
[2023-07-05 16:18:48] local.INFO: Ignore search operator "user_action"  
[2023-07-05 16:18:48] local.INFO: Ignore search operator "user_action"  
[2023-07-05 16:18:49] local.INFO: Ignore search operator "user_action"  
[2023-07-05 16:18:49] local.INFO: Ignore search operator "user_action"  
[2023-07-05 16:19:22] local.INFO: Ignore search operator "user_action"  
[2023-07-05 16:19:22] local.INFO: Ignore search operator "user_action"  
[2023-07-05 16:19:22] local.INFO: Ignore search operator "user_action"  
[2023-07-05 16:19:22] local.INFO: Ignore search operator "user_action"  
[2023-07-05 16:19:22] local.INFO: Ignore search operator "user_action"  
[2023-07-05 16:20:05] local.INFO: Ignore search operator "user_action"  
[2023-07-05 16:20:05] local.INFO: Ignore search operator "user_action"  
[2023-07-05 16:20:05] local.INFO: Ignore search operator "user_action"  
[2023-07-05 16:20:05] local.INFO: Ignore search operator "user_action"  
[2023-07-05 16:20:05] local.INFO: Ignore search operator "user_action"  
[2023-07-05 16:21:14] local.INFO: Account info is valid, now update.  
[2023-07-05 16:22:00] local.INFO: Detected invalid IBAN (""). Return NULL instead.  
[2023-07-05 16:25:29] local.INFO: Account info is valid, now update.  
[2023-07-05 16:25:29] local.INFO: Not enough info to update foreign currency info.  
[2023-07-05 16:25:42] local.INFO: Account info is valid, now update.  
[2023-07-05 16:25:42] local.INFO: Not enough info to update foreign currency info.  
[2023-07-05 16:49:35] local.INFO: User is trying to login.  
[2023-07-05 16:52:23] local.INFO: User is trying to login.  

```

**Comment by JC5** [comment]
Ah nice find. I expect it's an overzealous filter somewhere. I'll pick it up!

**Comment by JC5** [comment]
Same root cause as https://github.com/firefly-iii/firefly-iii/issues/7549

I can't fix this easily unfortunately.
