### ISSUE TITLE
ERROR: duplicate key value violates unique constraint 

### ISSUE THREAD

**Issue by canoine** [firefly-iii/firefly-iii#7787]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

I received this email while creating an expense :

```
Hello,

Firefly III v6.0.18 a rencontré une erreur : SQLSTATE[23505]: Unique violation: 7 ERROR: duplicate key value violates unique constraint "tag_transaction_journal_tag_id_transaction_journal_id_unique" DETAIL: Key (tag_id, transaction_journal_id)=(53, 2364) already exists. (Connection: pgsql, SQL: insert into "tag_transaction_journal" ("tag_id", "transaction_journal_id") values (53, 2364)).

L'erreur était de type "Illuminate\Database\QueryException".

L'erreur s'est produite le/à: Thu, 27 Jul 2023 11:51:45 +0200.

Cette erreur est survenue dans le fichier "/<<_xxxxx_>>/v6.0.18/vendor/laravel/framework/src/Illuminate/Database/Connection.php" à la ligne 795 avec le code 23505.

L'erreur a été rencontrée par l'utilisateur n°2, <<_xxxxx_>>.

L'adresse IP liée à cette erreur est : 172.<<_xxxxx_>> (info)
PUT L'URL est : https://<<_xxxxx_>>/api/v1/transactions/2100?_token=QJA6Kaf9Q2VHKerjA2Uk4XiX8YIp5pTNwKKyTIpi

La stacktrace complète se trouve plus bas. Si vous pensez qu'il s'agit d'un bogue dans Firefly III, vous pouvez transmettre ce message à james@firefly-iii.org (en anglais). Cela peut aider à corriger le bogue que vous venez de rencontrer.

Si vous le préférez, vous pouvez également ouvrir un nouveau ticket sur GitHub (en anglais).

La stacktrace complète se trouve ci-dessous :

#0 /<<_xxxxx_>>/v6.0.18/vendor/laravel/framework/src/Illuminate/Database/Connection.php(755): Illuminate\Database\Connection->runQueryCallback()
#1 /<<_xxxxx_>>/v6.0.18/vendor/laravel/framework/src/Illuminate/Database/Connection.php(569): Illuminate\Database\Connection->run()
#2 /<<_xxxxx_>>/v6.0.18/vendor/laravel/framework/src/Illuminate/Database/Connection.php(533): Illuminate\Database\Connection->statement()
#3 /<<_xxxxx_>>/v6.0.18/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(3332): Illuminate\Database\Connection->insert()
#4 /<<_xxxxx_>>/v6.0.18/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Relations/Concerns/InteractsWithPivotTable.php(271): Illuminate\Database\Query\Builder->insert()
#5 /<<_xxxxx_>>/v6.0.18/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Relations/Concerns/InteractsWithPivotTable.php(178): Illuminate\Database\Eloquent\Relations\BelongsToMany->attach()
#6 /<<_xxxxx_>>/v6.0.18/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Relations/Concerns/InteractsWithPivotTable.php(114): Illuminate\Database\Eloquent\Relations\BelongsToMany->attachNew()
#7 /<<_xxxxx_>>/v6.0.18/app/Services/Internal/Support/JournalServiceTrait.php(502): Illuminate\Database\Eloquent\Relations\BelongsToMany->sync()
#8 /<<_xxxxx_>>/v6.0.18/app/Services/Internal/Update/JournalUpdateService.php(603): FireflyIII\Services\Internal\Update\JournalUpdateService->storeTags()
#9 /<<_xxxxx_>>/v6.0.18/app/Services/Internal/Update/JournalUpdateService.php(172): FireflyIII\Services\Internal\Update\JournalUpdateService->updateTags()
#10 /<<_xxxxx_>>/v6.0.18/app/Services/Internal/Update/GroupUpdateService.php(152): FireflyIII\Services\Internal\Update\JournalUpdateService->update()
#11 /<<_xxxxx_>>/v6.0.18/app/Services/Internal/Update/GroupUpdateService.php(88): FireflyIII\Services\Internal\Update\GroupUpdateService->updateTransactionJournal()
#12 /<<_xxxxx_>>/v6.0.18/app/Repositories/TransactionGroup/TransactionGroupRepository.php(507): FireflyIII\Services\Internal\Update\GroupUpdateService->update()
#13 /<<_xxxxx_>>/v6.0.18/app/Api/V1/Controllers/Models/Transaction/UpdateController.php(82): FireflyIII\Repositories\TransactionGroup\TransactionGroupRepository->update()
#14 /<<_xxxxx_>>/v6.0.18/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): FireflyIII\Api\V1\Controllers\Models\Transaction\UpdateController->update()
#15 /<<_xxxxx_>>/v6.0.18/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(43): Illuminate\Routing\Controller->callAction()
#16 /<<_xxxxx_>>/v6.0.18/vendor/laravel/framework/src/Illuminate/Routing/Route.php(259): Illuminate\Routing\ControllerDispatcher->dispatch()
#17 /<<_xxxxx_>>/v6.0.18/vendor/laravel/framework/src/Illuminate/Routing/Route.php(205): Illuminate\Routing\Route->runController()
#18 /<<_xxxxx_>>/v6.0.18/vendor/laravel/framework/src/Illuminate/Routing/Router.php(799): Illuminate\Routing\Route->run()
#19 /<<_xxxxx_>>/v6.0.18/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\Routing\Router->Illuminate\Routing\{closure}()
#20 /<<_xxxxx_>>/v6.0.18/app/Api/V1/Controllers/Models/Transaction/UpdateController.php(62): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#21 /<<_xxxxx_>>/v6.0.18/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(162): FireflyIII\Api\V1\Controllers\Models\Transaction\UpdateController->FireflyIII\Api\V1\Controllers\Models\Transaction\{closure}()
#22 /<<_xxxxx_>>/v6.0.18/app/Api/V1/Controllers/Controller.php(72): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#23 /<<_xxxxx_>>/v6.0.18/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(162): FireflyIII\Api\V1\Controllers\Controller->FireflyIII\Api\V1\Controllers\{closure}()
#24 /<<_xxxxx_>>/v6.0.18/app/Http/Middleware/Binder.php(79): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#25 /<<_xxxxx_>>/v6.0.18/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): FireflyIII\Http\Middleware\Binder->handle()
#26 /<<_xxxxx_>>/v6.0.18/app/Http/Middleware/Authenticate.php(75): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#27 /<<_xxxxx_>>/v6.0.18/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): FireflyIII\Http\Middleware\Authenticate->handle()
#28 /<<_xxxxx_>>/v6.0.18/vendor/laravel/sanctum/src/Http/Middleware/EnsureFrontendRequestsAreStateful.php(25): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#29 /<<_xxxxx_>>/v6.0.18/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Laravel\Sanctum\Http\Middleware\EnsureFrontendRequestsAreStateful->Laravel\Sanctum\Http\Middleware\{closure}()
#30 /<<_xxxxx_>>/v6.0.18/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#31 /<<_xxxxx_>>/v6.0.18/vendor/laravel/sanctum/src/Http/Middleware/EnsureFrontendRequestsAreStateful.php(24): Illuminate\Pipeline\Pipeline->then()
#32 /<<_xxxxx_>>/v6.0.18/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Laravel\Sanctum\Http\Middleware\EnsureFrontendRequestsAreStateful->handle()
#33 /<<_xxxxx_>>/v6.0.18/app/Http/Middleware/AcceptHeaders.php(76): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#34 /<<_xxxxx_>>/v6.0.18/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): FireflyIII\Http\Middleware\AcceptHeaders->handle()
#35 /<<_xxxxx_>>/v6.0.18/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#36 /<<_xxxxx_>>/v6.0.18/vendor/laravel/framework/src/Illuminate/Routing/Router.php(798): Illuminate\Pipeline\Pipeline->then()
#37 /<<_xxxxx_>>/v6.0.18/vendor/laravel/framework/src/Illuminate/Routing/Router.php(777): Illuminate\Routing\Router->runRouteWithinStack()
#38 /<<_xxxxx_>>/v6.0.18/vendor/laravel/framework/src/Illuminate/Routing/Router.php(741): Illuminate\Routing\Router->runRoute()
#39 /<<_xxxxx_>>/v6.0.18/vendor/laravel/framework/src/Illuminate/Routing/Router.php(730): Illuminate\Routing\Router->dispatchToRoute()
#40 /<<_xxxxx_>>/v6.0.18/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(200): Illuminate\Routing\Router->dispatch()
#41 /<<_xxxxx_>>/v6.0.18/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}()
#42 /<<_xxxxx_>>/v6.0.18/app/Http/Middleware/InstallationId.php(52): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#43 /<<_xxxxx_>>/v6.0.18/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): FireflyIII\Http\Middleware\InstallationId->handle()
#44 /<<_xxxxx_>>/v6.0.18/vendor/laravel/framework/src/Illuminate/Http/Middleware/TrustProxies.php(39): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#45 /<<_xxxxx_>>/v6.0.18/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Http\Middleware\TrustProxies->handle()
#46 /<<_xxxxx_>>/v6.0.18/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#47 /<<_xxxxx_>>/v6.0.18/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.php(31): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle()
#48 /<<_xxxxx_>>/v6.0.18/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Foundation\Http\Middleware\ConvertEmptyStringsToNull->handle()
#49 /<<_xxxxx_>>/v6.0.18/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#50 /<<_xxxxx_>>/v6.0.18/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php(40): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle()
#51 /<<_xxxxx_>>/v6.0.18/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Foundation\Http\Middleware\TrimStrings->handle()
#52 /<<_xxxxx_>>/v6.0.18/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#53 /<<_xxxxx_>>/v6.0.18/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Foundation\Http\Middleware\ValidatePostSize->handle()
#54 /<<_xxxxx_>>/v6.0.18/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(86): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#55 /<<_xxxxx_>>/v6.0.18/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Foundation\Http\Middleware\PreventRequestsDuringMaintenance->handle()
#56 /<<_xxxxx_>>/v6.0.18/app/Http/Middleware/SecureHeaders.php(51): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#57 /<<_xxxxx_>>/v6.0.18/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): FireflyIII\Http\Middleware\SecureHeaders->handle()
#58 /<<_xxxxx_>>/v6.0.18/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#59 /<<_xxxxx_>>/v6.0.18/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(175): Illuminate\Pipeline\Pipeline->then()
#60 /<<_xxxxx_>>/v6.0.18/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(144): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter()
#61 /<<_xxxxx_>>/v6.0.18/public/index.php(73): Illuminate\Foundation\Http\Kernel->handle()
#62 {main}

Les en-têtes suivants peuvent également être pertinents :

- sec-gpc: 1
- sec-fetch-site: same-origin
- sec-fetch-mode: cors
- sec-fetch-dest: empty
- dnt: 1
- origin: https://<<_xxxxx_>>
- content-type: application/json
- x-csrf-token: QJA6Kaf9Q2VHKerjA2Uk4XiX8YIp5pTNwKKyTIpi
- x-requested-with: XMLHttpRequest
- accept-encoding: gzip, deflate, br
- accept-language: fr,fr-FR;q=0.8,en-US;q=0.5,en;q=0.3
- accept: application/json, text/plain, */*
- user-agent: Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/115.0
- content-length: 615
- connection: close
- host: <<_xxxxx_>>
- x-forwarded-for: 172.<<_xxxxx_>>
- x-forwarded-proto: https
- x-forwarded-host: <<_xxxxx_>>

Pøuì Poû Põuì,

Le Robot de Firefly III
```

The expense exists and seems to be OK.

### Debug information

Debug information generated at 2023-07-27 12:10:02 Europe/Paris for Firefly III version **6.0.18**.

| Scope | Version |
| --- | --- |
| Firefly III | 6.0.18 |
| Firefly III API | 2.0.4 |
| DB version | 19 (exp. 19) |
| Docker | No |
| PHP | `8.2.7` |
| Host | `Linux` |

| System info | Value |
| --- | --- |
| System TZ | Europe/Paris |
| Browser TZ | Europe/Paris |
| App environment | local |
| App debug mode | false |
| App cache driver | redis |
| App logging | notice, syslog |
| Display errors | Off |
| Error reporting | ALL errors |
| Max upload | 8388608 (8 MB) |
| Interface | fpm-fcgi |
| Default language | fr_FR |
| Default locale | equal |
| BCscale | 12 |
| DB drivers | pgsql, sqlite |
| Current driver | pgsql |
| Trusted proxies (.env) | `**` |

| User info | Value |
| --- | --- |
| Login provider | eloquent  |
| User guard | web  |
| Headers | N/A, N/A  |
| Stateful domains |  |
| Session start | 2023-07-01 00:00:00 |
| Session end | 2023-12-31 23:59:59 |
| Session first | 2020-07-31 00:00:00 |
| User ID | 2 |
| User language | fr_FR |
| User locale | fr_FR |
| Attempt at "fr_FR.utf8" | 'fr_FR.utf8' |
| Attempt at "fr_FR.UTF-8" | 'fr_FR.UTF-8' |
| User agent | Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/115.0 |

**Comment by JC5** [comment]
Thanks. Let me know if it happens more often, it could be a fluke. I'll investigate regardless.

**Comment by canoine** [comment]
That's the first time I met this error ever, and the lonely one until now. As the expense is good, I suppose that's not really important.
I preferred reporting it anyway, just in case.

**Comment by JC5** [comment]
Of course, and I appreciate it! I know which code could be the culprit and I hope to try to replicate it this weekend 👍
