### ISSUE TITLE
Possible error when adding a rule

### ISSUE THREAD

**Issue by Dinth** [firefly-iii/firefly-iii#7833]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

I have tried to add a rule:
Trigger (strict)
- Transaction description is...
- Destination account is...
Action:
- Delete the transaction

### Debug information

![image](https://github.com/firefly-iii/firefly-iii/assets/313674/76d2f205-50a4-4758-841c-286edf2cd98e)
```
172.17.0.1 - - [08/Aug/2023:07:53:34 +0100] "GET /recurring HTTP/1.1" 200 7322 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/115.0"

172.17.0.1 - - [08/Aug/2023:07:53:35 +0100] "GET /v1/jscript/variables?ext=.js&v=6.0.19 HTTP/1.1" 200 3983 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/115.0"

172.17.0.1 - - [08/Aug/2023:07:53:39 +0100] "GET /favicon.ico HTTP/1.1" 200 15336 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/115.0"

172.17.0.1 - - [08/Aug/2023:07:53:40 +0100] "GET /recurring HTTP/1.1" 200 7320 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/115.0"

172.17.0.1 - - [08/Aug/2023:07:53:41 +0100] "GET /v1/jscript/variables?ext=.js&v=6.0.19 HTTP/1.1" 200 3983 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/115.0"

172.17.0.1 - - [08/Aug/2023:07:53:43 +0100] "GET /transactions/deposit HTTP/1.1" 200 9795 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/115.0"

172.17.0.1 - - [08/Aug/2023:07:53:44 +0100] "GET /v1/jscript/variables?ext=.js&v=6.0.19 HTTP/1.1" 200 3983 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/115.0"

172.17.0.1 - - [08/Aug/2023:07:53:45 +0100] "GET /chart/transactions/categories/deposit/2023-08-01/2023-08-31 HTTP/1.1" 200 3003 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/115.0"

172.17.0.1 - - [08/Aug/2023:07:53:45 +0100] "GET /chart/transactions/destinationAccounts/deposit/2023-08-01/2023-08-31 HTTP/1.1" 200 3003 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/115.0"

172.17.0.1 - - [08/Aug/2023:07:53:45 +0100] "GET /chart/transactions/sourceAccounts/deposit/2023-08-01/2023-08-31 HTTP/1.1" 200 2998 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/115.0"

172.17.0.1 - - [08/Aug/2023:07:53:46 +0100] "GET /transactions/deposit/all HTTP/1.1" 200 14907 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/115.0"

172.17.0.1 - - [08/Aug/2023:07:53:47 +0100] "GET /v1/jscript/variables?ext=.js&v=6.0.19 HTTP/1.1" 200 3983 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/115.0"

172.17.0.1 - - [08/Aug/2023:07:54:04 +0100] "GET /rules HTTP/1.1" 200 23085 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/115.0"

172.17.0.1 - - [08/Aug/2023:07:54:05 +0100] "GET /v1/jscript/variables?ext=.js&v=6.0.19 HTTP/1.1" 200 3983 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/115.0"

172.17.0.1 - - [08/Aug/2023:07:54:07 +0100] "GET /rule-groups/create HTTP/1.1" 200 7291 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/115.0"

172.17.0.1 - - [08/Aug/2023:07:54:07 +0100] "GET /v1/js/ff/rule-groups/create.js?v=6.0.19 HTTP/1.1" 200 903 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/115.0"

172.17.0.1 - - [08/Aug/2023:07:54:07 +0100] "GET /v1/jscript/variables?ext=.js&v=6.0.19 HTTP/1.1" 200 3983 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/115.0"

127.0.0.1 - - [08/Aug/2023:07:54:08 +0100] "GET /health HTTP/1.1" 200 1776 "-" "Firefly III Health Checker/2.0"

172.17.0.1 - - [08/Aug/2023:07:54:12 +0100] "GET /rules/create/1 HTTP/1.1" 200 8273 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/115.0"

172.17.0.1 - - [08/Aug/2023:07:54:12 +0100] "GET /v1/jscript/variables?ext=.js&v=6.0.19 HTTP/1.1" 200 3983 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/115.0"

172.17.0.1 - - [08/Aug/2023:07:54:12 +0100] "GET /json/action?count=1 HTTP/1.1" 200 7357 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/115.0"

172.17.0.1 - - [08/Aug/2023:07:54:12 +0100] "GET /json/trigger?count=1 HTTP/1.1" 200 27300 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/115.0"

172.17.0.1 - - [08/Aug/2023:07:54:12 +0100] "GET /api/v1/autocomplete/piggy-banks?uid=3783dc69d584 HTTP/1.1" 200 918 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/115.0"

172.17.0.1 - - [08/Aug/2023:07:54:27 +0100] "GET /api/v1/autocomplete/transactions?query=%20%09PAYMENT%20RECEIVED%20--%20THANK%20YOU%20&uid=3783dc69d584 HTTP/1.1" 200 1047 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/115.0"

172.17.0.1 - - [08/Aug/2023:07:54:31 +0100] "GET /rules/test?strict=1&triggers%5B1%5D%5Btype%5D=description_is&triggers%5B1%5D%5Bvalue%5D=PAYMENT%20RECEIVED%20--%20THANK%20YOU%20 HTTP/1.1" 200 5256 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/115.0"

172.17.0.1 - - [08/Aug/2023:07:54:34 +0100] "GET /json/trigger?count=2 HTTP/1.1" 200 27300 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/115.0"

172.17.0.1 - - [08/Aug/2023:07:54:51 +0100] "GET /api/v1/autocomplete/accounts?uid=3783dc69d584 HTTP/1.1" 200 3167 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/115.0"

172.17.0.1 - - [08/Aug/2023:07:54:53 +0100] "GET /api/v1/autocomplete/accounts?query=Capi&uid=3783dc69d584 HTTP/1.1" 200 1428 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/115.0"

172.17.0.1 - - [08/Aug/2023:07:54:55 +0100] "GET /rules/test?strict=1&triggers%5B1%5D%5Btype%5D=description_is&triggers%5B1%5D%5Bvalue%5D=PAYMENT%20RECEIVED%20--%20THANK%20YOU%20&triggers%5B2%5D%5Btype%5D=destination_account_is&triggers%5B2%5D%5Bvalue%5D=Capital%20One HTTP/1.1" 200 5256 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/115.0"

172.17.0.1 - - [08/Aug/2023:07:55:04 +0100] "POST /rules/store HTTP/1.1" 302 2616 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/115.0"

[2023-08-08 07:55:05] local.ERROR: #0 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(254): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError()

#1 /var/www/html/app/Support/Http/Controllers/RuleManagement.php(57): Illuminate\Foundation\Bootstrap\HandleExceptions->Illuminate\Foundation\Bootstrap\{closure}()

#2 /var/www/html/app/Http/Controllers/Rule/CreateController.php(109): FireflyIII\Http\Controllers\Rule\CreateController->getPreviousActions()

#3 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): FireflyIII\Http\Controllers\Rule\CreateController->create()

#4 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(43): Illuminate\Routing\Controller->callAction()

#5 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Route.php(259): Illuminate\Routing\ControllerDispatcher->dispatch()

#6 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Route.php(205): Illuminate\Routing\Route->runController()

#7 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(799): Illuminate\Routing\Route->run()

#8 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\Routing\Router->Illuminate\Routing\{closure}()

#9 /var/www/html/app/Http/Controllers/Rule/CreateController.php(69): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()

#10 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(162): FireflyIII\Http\Controllers\Rule\CreateController->FireflyIII\Http\Controllers\Rule\{closure}()

#11 /var/www/html/app/Http/Controllers/Controller.php(119): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()

#12 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(162): FireflyIII\Http\Controllers\Controller->FireflyIII\Http\Controllers\{closure}()

#13 /var/www/html/app/Http/Middleware/InterestingMessage.php(72): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()

#14 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): FireflyIII\Http\Middleware\InterestingMessage->handle()

#15 /var/www/html/app/Http/Middleware/Binder.php(79): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()

#16 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): FireflyIII\Http\Middleware\Binder->handle()

#17 /var/www/html/app/Http/Middleware/Range.php(62): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()

#18 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): FireflyIII\Http\Middleware\Range->handle()

#19 /var/www/html/vendor/jc5/google2fa-laravel/src/Middleware.php(29): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()

#20 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): PragmaRX\Google2FALaravel\Middleware->handle()

#21 /var/www/html/app/Http/Middleware/Authenticate.php(75): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()

#22 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): FireflyIII\Http\Middleware\Authenticate->handle()

#23 /var/www/html/vendor/laravel/passport/src/Http/Middleware/CreateFreshApiToken.php(50): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()

#24 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Laravel\Passport\Http\Middleware\CreateFreshApiToken->handle()

#25 /var/www/html/vendor/laravel/framework/src/Illuminate/Session/Middleware/AuthenticateSession.php(60): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()

#26 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Session\Middleware\AuthenticateSession->handle()

#27 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(78): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()

#28 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Foundation\Http\Middleware\VerifyCsrfToken->handle()

#29 /var/www/html/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()

#30 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\View\Middleware\ShareErrorsFromSession->handle()

#31 /var/www/html/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(121): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()

#32 /var/www/html/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(64): Illuminate\Session\Middleware\StartSession->handleStatefulRequest()

#33 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Session\Middleware\StartSession->handle()

#34 /var/www/html/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()

#35 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle()

#36 /var/www/html/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(67): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()

#37 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Cookie\Middleware\EncryptCookies->handle()

#38 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()

#39 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(798): Illuminate\Pipeline\Pipeline->then()

#40 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(777): Illuminate\Routing\Router->runRouteWithinStack()

#41 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(741): Illuminate\Routing\Router->runRoute()

#42 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(730): Illuminate\Routing\Router->dispatchToRoute()

#43 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(200): Illuminate\Routing\Router->dispatch()

#44 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}()

#45 /var/www/html/app/Http/Middleware/InstallationId.php(52): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()

#46 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): FireflyIII\Http\Middleware\InstallationId->handle()

#47 /var/www/html/vendor/laravel/framework/src/Illuminate/Http/Middleware/TrustProxies.php(39): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()

#48 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Http\Middleware\TrustProxies->handle()

#49 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()

#50 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.php(31): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle()

#51 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Foundation\Http\Middleware\ConvertEmptyStringsToNull->handle()

#52 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()

#53 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php(40): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle()

#54 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Foundation\Http\Middleware\TrimStrings->handle()

#55 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()

#56 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Foundation\Http\Middleware\ValidatePostSize->handle()

#57 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(86): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()

#58 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Foundation\Http\Middleware\PreventRequestsDuringMaintenance->handle()

#59 /var/www/html/app/Http/Middleware/SecureHeaders.php(51): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()

#60 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): FireflyIII\Http\Middleware\SecureHeaders->handle()

#61 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()

#62 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(175): Illuminate\Pipeline\Pipeline->then()

#63 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(144): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter()

#64 /var/www/html/public/index.php(73): Illuminate\Foundation\Http\Kernel->handle()


```

### Steps to reproduce

I have tried to reproduce the error but the transaction was created without an issue.

**Comment by JC5** [comment]
Which version of Firefly III are you running?
