### ISSUE TITLE
Import Nordigen - Transaction "2023000790" has no source account name information

### ISSUE THREAD

**Issue by jlauwers** [firefly-iii/firefly-iii#7973]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

Hi,
One transaction is not created from the import of nordigen.

I'm using docker with those version:
Firefly III v6.0.24
Firefly III data importer, v1.3.8

### Debug information

```
[2023-09-18 16:13:48] production.DEBUG: Nordigen transaction from array {"transactionId":"2023000790","endToEndId":"NOTPROVIDED","bookingDate":"2023-09-18","valueDate":"2023-09-18","transactionAmount":{"amount":"****","currency":"EUR"},"debtorAccount":{"iban":"BE60796550300970","bban":"796550300970"},"remittanceInformationUnstructured":"Virement en euros (SEPA)
De: MUTUALITE CHRETIENNE - BE60796550300970
Communication: /B/ INDEMNITE 24.07.23  AU 27.08.23840723 208M4...
Info personnelle: 20230915222154000-6056840723 208M41
","proprietaryBankTransactionCode":"Other","internalTransactionId":"8a989c37ef7199176ae73dc2ca58f169","key":"booked"}
[2023-09-18 16:13:48] production.DEBUG: Create Balance from array
[2023-09-18 16:13:48] production.DEBUG: Downloaded transaction with ID "2023000790"
```
```
[2023-09-18 16:13:49] production.DEBUG: [2/33] Parsing transaction (3)
[2023-09-18 16:13:49] production.DEBUG: Description is now remittanceInformationUnstructured
[2023-09-18 16:13:49] production.DEBUG: Nordigen transaction: "Virement en euros (SEPA)
De: MUTUALITE CHRETIENNE - BE60796550300970
Communication: /B/ INDEMNITE 24.07.23  AU 27.08.23840723 208M4...
Info personnelle: 20230915222154000-6056840723 208M41" with amount EUR ****
[2023-09-18 16:13:49] production.DEBUG: Returning value date for getValueDate
[2023-09-18 16:13:49] production.DEBUG: Returning book date
[2023-09-18 16:13:49] production.DEBUG: Returning book date
[2023-09-18 16:13:49] production.DEBUG: Description is now remittanceInformationUnstructured
[2023-09-18 16:13:49] production.DEBUG: Amount is positive: assume transfer or deposit.
[2023-09-18 16:13:49] production.DEBUG: Destination ID is now #1, which should be a Firefly III asset account.
[2023-09-18 16:13:49] production.DEBUG: Now in App\Services\Nordigen\Conversion\Routine\GenerateTransactions::appendAccountFields($transaction, $entry, "source")
[2023-09-18 16:13:49] production.DEBUG: App\Services\Nordigen\Model\Transaction::getSourceIban
[2023-09-18 16:13:49] production.DEBUG: isValidIBAN("BE60796550300970")
[2023-09-18 16:13:49] production.DEBUG: Trim: isValidIBAN("BE60796550300970")
[2023-09-18 16:13:49] production.DEBUG: Source IBAN is "BE60796550300970" (debtor)
[2023-09-18 16:13:49] production.DEBUG: App\Services\Nordigen\Model\Transaction::getSourceNumber
[2023-09-18 16:13:49] production.DEBUG: Source BBAN is "796550300970" (debtor)
[2023-09-18 16:13:49] production.DEBUG: App\Services\Nordigen\Model\Transaction::getSourceName
[2023-09-18 16:13:49] production.WARNING: Transaction "2023000790" has no source account name information.
[2023-09-18 16:13:49] production.DEBUG: Done collecting account numbers and names
[2023-09-18 16:13:49] production.DEBUG: "BE60796550300970" is not a valid IBAN OR not recognized as Firefly III asset account so submitted as-is.
[2023-09-18 16:13:49] production.DEBUG: IBAN is "BE60796550300970", so leave field "source_iban" empty.
[2023-09-18 16:13:49] production.DEBUG: Field "source_name" will  be set to "(unknown source account)".
[2023-09-18 16:13:49] production.DEBUG: Set field "source_iban" to "BE60796550300970".
[2023-09-18 16:13:49] production.DEBUG: "796550300970" is not a valid account nr OR not recognized as Firefly III asset account so submitted as-is.
[2023-09-18 16:13:49] production.DEBUG: Account number is "796550300970", so leave field "source_number" empty.
[2023-09-18 16:13:49] production.DEBUG: Field "source_name" will  be set to "(unknown source account)".
[2023-09-18 16:13:49] production.DEBUG: Set field "source_number" to "796550300970".
[2023-09-18 16:13:49] production.DEBUG: End of App\Services\Nordigen\Conversion\Routine\GenerateTransactions::appendAccountFields
[2023-09-18 16:13:49] production.DEBUG: Check if "(unknown source account)" is mapped to an account by the user.
[2023-09-18 16:13:49] production.DEBUG: Its not mapped by the user.
[2023-09-18 16:13:49] production.DEBUG: Parsed Nordigen transaction "2023000790". {"type":"deposit","date":"2023-09-18","datetime":"2023-09-18T00:00:00+02:00","amount":"****","description":"Virement en euros (SEPA)
De: MUTUALITE CHRETIENNE - BE60796550300970
Communication: /B/ INDEMNITE 24.07.23  AU 27.08.23840723 208M4...
Info personnelle: 20230915222154000-6056840723 208M41","payment_date":"2023-09-18","order":0,"currency_code":"EUR","tags":[],"category_name":null,"category_id":null,"notes":"","external_id":"2023000790","internal_reference":"","additional-information":"","destination_id":1,"source_name":"(unknown source account)","source_iban":"BE60796550300970","source_number":"796550300970"}
[2023-09-18 16:13:49] production.DEBUG: [2/33] Done parsing transaction.
```
```
[2023-09-18 16:13:53] production.DEBUG: Now submitting transaction 2/33
[2023-09-18 16:13:53] production.DEBUG: Going to search for external_id:2023000790 using query external_id:"2023000790"
[2023-09-18 16:13:53] production.DEBUG: No base url in getBaseUrl(), will return config variable.
[2023-09-18 16:13:53] production.DEBUG: No access token in hasAccessToken(), will return config variable.
[2023-09-18 16:13:53] production.DEBUG: Looks like field "external_id" with value "2023000790" is unique, return false.
[2023-09-18 16:13:53] production.DEBUG: Transaction #2 is unique.
[2023-09-18 16:13:53] production.DEBUG: Going to map data for this line.
[2023-09-18 16:13:53] production.DEBUG: No base url in getBaseUrl(), will return config variable.
[2023-09-18 16:13:53] production.DEBUG: No access token in hasAccessToken(), will return config variable.
[2023-09-18 16:13:53] production.DEBUG: Submitting to Firefly III: {"apply_rules":true,"error_if_duplicate_hash":false,"transactions":[{"type":"deposit","date":"2023-09-18","amount":"****","description":"Virement en euros (SEPA)\nDe: MUTUALITE CHRETIENNE - BE60796550300970 \nCommunication: \/B\/ INDEMNITE 24.07.23  AU 27.08.23840723 208M4... \nInfo personnelle: 20230915222154000-6056840723 208M41","payment_date":"2023-09-18","order":0,"currency_code":"EUR","tags":[],"category_name":null,"category_id":null,"notes":"","external_id":"2023000790","internal_reference":"","additional-information":"","destination_id":1,"source_name":"(unknown source account)","source_iban":"BE60796550300970","source_number":"796550300970"}]}
[2023-09-18 16:13:53] production.ERROR: Status code is 500: {"message":"Internal Firefly III Exception: Attempt to read property \"accountType\" on null","exception":"ErrorException"}
```
```
[2023-09-18 17:10:25] local.ERROR: Exception is: {"class":"ErrorException","errorMessage":"Attempt to read property \"accountType\" on null","time":"Mon, 18 Sep 2023 17:10:25 +0200","file":"\/var\/www\/html\/app\/Validation\/AccountValidator.php","line":280,"code":0,"version":"6.0.24","url":"http:\/\/192.168.0.3:8009\/api\/v1\/transactions","userAgent":"GuzzleHttp\/7","json":true,"method":"POST"}
[2023-09-18 17:10:25] local.ERROR: Attempt to read property "accountType" on null {"userId":1,"exception":"[object] (ErrorException(code: 0): Attempt to read property \"accountType\" on null at /var/www/html/app/Validation/AccountValidator.php:280)
[stacktrace]
#0 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(254): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError()
#1 /var/www/html/app/Validation/AccountValidator.php(280): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->Illuminate\\Foundation\\Bootstrap\\{closure}()
#2 /var/www/html/app/Validation/Account/DepositValidation.php(132): FireflyIII\\Validation\\AccountValidator->findExistingAccount()
#3 /var/www/html/app/Validation/AccountValidator.php(193): FireflyIII\\Validation\\AccountValidator->validateDepositSource()
#4 /var/www/html/app/Validation/TransactionValidation.php(124): FireflyIII\\Validation\\AccountValidator->validateSource()
#5 /var/www/html/app/Validation/TransactionValidation.php(67): FireflyIII\\Api\\V1\\Requests\\Models\\Transaction\\StoreRequest->validateSingleAccount()
#6 /var/www/html/app/Api/V1/Requests/Models/Transaction/StoreRequest.php(287): FireflyIII\\Api\\V1\\Requests\\Models\\Transaction\\StoreRequest->validateAccountInformation()
#7 /var/www/html/vendor/laravel/framework/src/Illuminate/Validation/Validator.php(406): FireflyIII\\Api\\V1\\Requests\\Models\\Transaction\\StoreRequest->FireflyIII\\Api\\V1\\Requests\\Models\\Transaction\\{closure}()
#8 /var/www/html/vendor/laravel/framework/src/Illuminate/Validation/Validator.php(459): Illuminate\\Validation\\Validator->Illuminate\\Validation\\{closure}()
#9 /var/www/html/vendor/laravel/framework/src/Illuminate/Validation/Validator.php(472): Illuminate\\Validation\\Validator->passes()
#10 /var/www/html/vendor/laravel/framework/src/Illuminate/Validation/ValidatesWhenResolvedTrait.php(31): Illuminate\\Validation\\Validator->fails()
#11 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Providers/FormRequestServiceProvider.php(30): Illuminate\\Foundation\\Http\\FormRequest->validateResolved()
#12 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(1302): Illuminate\\Foundation\\Providers\\FormRequestServiceProvider->Illuminate\\Foundation\\Providers\\{closure}()
#13 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(1266): Illuminate\\Container\\Container->fireCallbackArray()
#14 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(1252): Illuminate\\Container\\Container->fireAfterResolvingCallbacks()
#15 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(813): Illuminate\\Container\\Container->fireResolvingCallbacks()
#16 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(937): Illuminate\\Container\\Container->resolve()
#17 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(731): Illuminate\\Foundation\\Application->resolve()
#18 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(922): Illuminate\\Container\\Container->make()
#19 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/ResolvesRouteDependencies.php(85): Illuminate\\Foundation\\Application->make()
#20 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/ResolvesRouteDependencies.php(50): Illuminate\\Routing\\ControllerDispatcher->transformDependency()
#21 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/ResolvesRouteDependencies.php(29): Illuminate\\Routing\\ControllerDispatcher->resolveMethodDependencies()
#22 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(59): Illuminate\\Routing\\ControllerDispatcher->resolveClassMethodDependencies()
#23 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(40): Illuminate\\Routing\\ControllerDispatcher->resolveParameters()
#24 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Route.php(259): Illuminate\\Routing\\ControllerDispatcher->dispatch()
#25 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Route.php(205): Illuminate\\Routing\\Route->runController()
#26 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(799): Illuminate\\Routing\\Route->run()
#27 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}()
#28 /var/www/html/app/Api/V1/Controllers/Models/Transaction/StoreController.php(68): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#29 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(162): FireflyIII\\Api\\V1\\Controllers\\Models\\Transaction\\StoreController->FireflyIII\\Api\\V1\\Controllers\\Models\\Transaction\\{closure}()
#30 /var/www/html/app/Api/V1/Controllers/Controller.php(72): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#31 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(162): FireflyIII\\Api\\V1\\Controllers\\Controller->FireflyIII\\Api\\V1\\Controllers\\{closure}()
#32 /var/www/html/app/Http/Middleware/Binder.php(79): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#33 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): FireflyIII\\Http\\Middleware\\Binder->handle()
#34 /var/www/html/app/Http/Middleware/Authenticate.php(75): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#35 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): FireflyIII\\Http\\Middleware\\Authenticate->handle()
#36 /var/www/html/vendor/laravel/sanctum/src/Http/Middleware/EnsureFrontendRequestsAreStateful.php(25): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#37 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Laravel\\Sanctum\\Http\\Middleware\\EnsureFrontendRequestsAreStateful->Laravel\\Sanctum\\Http\\Middleware\\{closure}()
#38 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#39 /var/www/html/vendor/laravel/sanctum/src/Http/Middleware/EnsureFrontendRequestsAreStateful.php(24): Illuminate\\Pipeline\\Pipeline->then()
#40 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Laravel\\Sanctum\\Http\\Middleware\\EnsureFrontendRequestsAreStateful->handle()
#41 /var/www/html/app/Http/Middleware/AcceptHeaders.php(76): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#42 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): FireflyIII\\Http\\Middleware\\AcceptHeaders->handle()
#43 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#44 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(798): Illuminate\\Pipeline\\Pipeline->then()
#45 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(777): Illuminate\\Routing\\Router->runRouteWithinStack()
#46 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(741): Illuminate\\Routing\\Router->runRoute()
#47 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(730): Illuminate\\Routing\\Router->dispatchToRoute()
#48 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(200): Illuminate\\Routing\\Router->dispatch()
#49 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}()
#50 /var/www/html/app/Http/Middleware/InstallationId.php(52): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#51 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): FireflyIII\\Http\\Middleware\\InstallationId->handle()
#52 /var/www/html/vendor/laravel/framework/src/Illuminate/Http/Middleware/TrustProxies.php(39): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#53 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Http\\Middleware\\TrustProxies->handle()
#54 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#55 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.php(31): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#56 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\ConvertEmptyStringsToNull->handle()
#57 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#58 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php(40): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#59 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\TrimStrings->handle()
#60 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#61 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle()
#62 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(89): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#63 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance->handle()
#64 /var/www/html/app/Http/Middleware/SecureHeaders.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#65 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): FireflyIII\\Http\\Middleware\\SecureHeaders->handle()
#66 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#67 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(175): Illuminate\\Pipeline\\Pipeline->then()
#68 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(144): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter()
#69 /var/www/html/public/index.php(73): Illuminate\\Foundation\\Http\\Kernel->handle()
#70 {main}
"}
```

### Expected behaviour

Transaction should be imported.

**Comment by JC5** [comment]
Nice find, that's a bug in Firefly III. It will be fixed in the next release. In the mean time, you can use the `develop` branch or Docker tag of Firefly III.

**Comment by jlauwers** [comment]
Glad to help :)
