### ISSUE TITLE
Class "finfo" not found error when taking "Edit" action on asset account

### ISSUE THREAD

**Issue by masonmanley** [firefly-iii/firefly-iii#8114]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

When viewing account list and clicking action menu on account then clicking edit..."Whoops" page is displayed / error: class "finfo" not found

### Debug information

Debug information generated at 2023-11-01 04:44:26 for Firefly III version **v6.0.30**.

<table><thead><tr><th colspan="2">System information</th></tr><tr><th>Item</th><th>Value</th></tr></thead><tbody><tr><td>Firefly III</td><td>v6.0.30 / v2.0.11 / 21 (exp. 21)</td></tr><tr><td>PHP version</td><td>8.2.11 / litespeed / Linux</td></tr><tr><td>BCscale</td><td>12</td></tr><tr><td>Error reporting</td><td>Display: Off, reporting: ALL errors</td></tr><tr><td>Max upload</td><td>2097152 (2 MB)</td></tr><tr><td>Database drivers</td><td><strong>*mysql*</strong>, sqlite, </td></tr></tbody></table><table><thead><tr><th colspan="2">Firefly III information</th></tr><tr><th>Item</th><th>Value</th></tr></thead><tbody><tr><td>Timezone</td><td>Europe/Amsterdam + America/New_York</td></tr><tr><td>App environment</td><td>local, debug: false</td></tr><tr><td>Layout</td><td>v1</td></tr><tr><td>Logging</td><td>notice, daily / (empty)</td></tr><tr><td>Cache driver</td><td>file</td></tr><tr><td>Default language and locale</td><td>en_US + equal</td></tr><tr><td>Trusted proxies</td><td></td></tr><tr><td>Login provider & user guard</td><td>eloquent / web</td></tr><tr><td>Login headers</td><td>N/A + N/A</td></tr><tr><td>Stateful domains</td><td></td></tr><tr><td>Last cron job</td><td>never (never)</td></tr><tr><td>Mailer</td><td>log</td></tr></tbody></table><table><thead><tr><th colspan="2">User-specific information</th></tr><tr><th>Item</th><th>Value</th></tr></thead><tbody><tr><td>User</td><td><span>#</span>1 of 1</td></tr><tr><td>User flags</td><td></td></tr><tr><td>Session start</td><td>2023-11-01 00:00:00</td></tr><tr><td>Session end</td><td>2023-11-30 23:59:59</td></tr><tr><td>View range</td><td>1M</td></tr><tr><td>User language</td><td>en_US</td></tr><tr><td>User locale</td><td>en_US</td></tr><tr><td>Locale(s) supported</td><td>en_US.utf8: :white_check_mark:<br>en_US.UTF-8: :white_check_mark:<br></td></tr><tr><td>User agent</td><td>Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/118.0</td></tr></tbody></table>

### Expected behaviour

Edit page to be displayed

### Steps to reproduce

1. Navigate to asset account list
2. Open action drop down for an account
3. Select edit
4. Error displayed

### Additional info

Log info:
```
[2023-11-01`` 04:46:35] local.ERROR: Exception is: {"class":"Error","errorMessage":"Class \"finfo\" not found","time":"Wed, 01 Nov 2023 04:46:35 +0100","file":"\/data0\/masonmanley.com\/public_html\/firefly.masonmanley.com\/vendor\/league\/mime-type-detection\/src\/FinfoMimeTypeDetector.php","line":48,"code":0,"version":"6.0.30","url":"https:\/\/firefly.masonmanley.com\/public\/accounts\/edit\/9","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko\/20100101 Firefox\/118.0","json":true,"method":"GET"}  
[2023-11-01 04:46:35] local.WARNING: [Bcc] Could not email or log the error. Please validate your email settings, use the .env.example file as a guide.  
[2023-11-01 04:46:35] local.ERROR: Class "finfo" not found {"userId":1,"exception":"[object] (Error(code: 0): Class \"finfo\" not found at /data0/masonmanley.com/public_html/firefly.masonmanley.com/vendor/league/mime-type-detection/src/FinfoMimeTypeDetector.php:48)
[stacktrace]
#0 /data0/masonmanley.com/public_html/firefly.masonmanley.com/vendor/league/flysystem-local/LocalFilesystemAdapter.php(84): League\\MimeTypeDetection\\FinfoMimeTypeDetector->__construct()
#1 /data0/masonmanley.com/public_html/firefly.masonmanley.com/vendor/laravel/framework/src/Illuminate/Filesystem/FilesystemManager.php(183): League\\Flysystem\\Local\\LocalFilesystemAdapter->__construct()
#2 /data0/masonmanley.com/public_html/firefly.masonmanley.com/vendor/laravel/framework/src/Illuminate/Filesystem/FilesystemManager.php(152): Illuminate\\Filesystem\\FilesystemManager->createLocalDriver()
#3 /data0/masonmanley.com/public_html/firefly.masonmanley.com/vendor/laravel/framework/src/Illuminate/Filesystem/FilesystemManager.php(120): Illuminate\\Filesystem\\FilesystemManager->resolve()
#4 /data0/masonmanley.com/public_html/firefly.masonmanley.com/vendor/laravel/framework/src/Illuminate/Filesystem/FilesystemManager.php(83): Illuminate\\Filesystem\\FilesystemManager->get()
#5 /data0/masonmanley.com/public_html/firefly.masonmanley.com/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(353): Illuminate\\Filesystem\\FilesystemManager->disk()
#6 /data0/masonmanley.com/public_html/firefly.masonmanley.com/app/Helpers/Attachments/AttachmentHelper.php(66): Illuminate\\Support\\Facades\\Facade::__callStatic()
#7 [internal function]: FireflyIII\\Helpers\\Attachments\\AttachmentHelper->__construct()
#8 /data0/masonmanley.com/public_html/firefly.masonmanley.com/vendor/laravel/framework/src/Illuminate/Container/Container.php(952): ReflectionClass->newInstanceArgs()
#9 /data0/masonmanley.com/public_html/firefly.masonmanley.com/vendor/laravel/framework/src/Illuminate/Container/Container.php(795): Illuminate\\Container\\Container->build()
#10 /data0/masonmanley.com/public_html/firefly.masonmanley.com/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(955): Illuminate\\Container\\Container->resolve()
#11 /data0/masonmanley.com/public_html/firefly.masonmanley.com/vendor/laravel/framework/src/Illuminate/Container/Container.php(296): Illuminate\\Foundation\\Application->resolve()
#12 /data0/masonmanley.com/public_html/firefly.masonmanley.com/vendor/laravel/framework/src/Illuminate/Container/Container.php(908): Illuminate\\Container\\Container->Illuminate\\Container\\{closure}()
#13 /data0/masonmanley.com/public_html/firefly.masonmanley.com/vendor/laravel/framework/src/Illuminate/Container/Container.php(795): Illuminate\\Container\\Container->build()
#14 /data0/masonmanley.com/public_html/firefly.masonmanley.com/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(955): Illuminate\\Container\\Container->resolve()
#15 /data0/masonmanley.com/public_html/firefly.masonmanley.com/vendor/laravel/framework/src/Illuminate/Container/Container.php(731): Illuminate\\Foundation\\Application->resolve()
#16 /data0/masonmanley.com/public_html/firefly.masonmanley.com/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(940): Illuminate\\Container\\Container->make()
#17 /data0/masonmanley.com/public_html/firefly.masonmanley.com/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php(120): Illuminate\\Foundation\\Application->make()
#18 /data0/masonmanley.com/public_html/firefly.masonmanley.com/app/Http/Controllers/Account/EditController.php(63): app()
#19 /data0/masonmanley.com/public_html/firefly.masonmanley.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(162): FireflyIII\\Http\\Controllers\\Account\\EditController->FireflyIII\\Http\\Controllers\\Account\\{closure}()
#20 /data0/masonmanley.com/public_html/firefly.masonmanley.com/app/Http/Controllers/Controller.php(119): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#21 /data0/masonmanley.com/public_html/firefly.masonmanley.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(162): FireflyIII\\Http\\Controllers\\Controller->FireflyIII\\Http\\Controllers\\{closure}()
#22 /data0/masonmanley.com/public_html/firefly.masonmanley.com/app/Http/Middleware/InterestingMessage.php(77): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#23 /data0/masonmanley.com/public_html/firefly.masonmanley.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): FireflyIII\\Http\\Middleware\\InterestingMessage->handle()
#24 /data0/masonmanley.com/public_html/firefly.masonmanley.com/app/Http/Middleware/Binder.php(79): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#25 /data0/masonmanley.com/public_html/firefly.masonmanley.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): FireflyIII\\Http\\Middleware\\Binder->handle()
#26 /data0/masonmanley.com/public_html/firefly.masonmanley.com/app/Http/Middleware/Range.php(62): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#27 /data0/masonmanley.com/public_html/firefly.masonmanley.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): FireflyIII\\Http\\Middleware\\Range->handle()
#28 /data0/masonmanley.com/public_html/firefly.masonmanley.com/vendor/jc5/google2fa-laravel/src/Middleware.php(29): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#29 /data0/masonmanley.com/public_html/firefly.masonmanley.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): PragmaRX\\Google2FALaravel\\Middleware->handle()
#30 /data0/masonmanley.com/public_html/firefly.masonmanley.com/app/Http/Middleware/Authenticate.php(75): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#31 /data0/masonmanley.com/public_html/firefly.masonmanley.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): FireflyIII\\Http\\Middleware\\Authenticate->handle()
#32 /data0/masonmanley.com/public_html/firefly.masonmanley.com/vendor/laravel/passport/src/Http/Middleware/CreateFreshApiToken.php(50): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#33 /data0/masonmanley.com/public_html/firefly.masonmanley.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Laravel\\Passport\\Http\\Middleware\\CreateFreshApiToken->handle()
#34 /data0/masonmanley.com/public_html/firefly.masonmanley.com/vendor/laravel/framework/src/Illuminate/Session/Middleware/AuthenticateSession.php(60): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#35 /data0/masonmanley.com/public_html/firefly.masonmanley.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Session\\Middleware\\AuthenticateSession->handle()
#36 /data0/masonmanley.com/public_html/firefly.masonmanley.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(78): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#37 /data0/masonmanley.com/public_html/firefly.masonmanley.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle()
#38 /data0/masonmanley.com/public_html/firefly.masonmanley.com/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#39 /data0/masonmanley.com/public_html/firefly.masonmanley.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle()
#40 /data0/masonmanley.com/public_html/firefly.masonmanley.com/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(121): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#41 /data0/masonmanley.com/public_html/firefly.masonmanley.com/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(64): Illuminate\\Session\\Middleware\\StartSession->handleStatefulRequest()
#42 /data0/masonmanley.com/public_html/firefly.masonmanley.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Session\\Middleware\\StartSession->handle()
#43 /data0/masonmanley.com/public_html/firefly.masonmanley.com/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#44 /data0/masonmanley.com/public_html/firefly.masonmanley.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle()
#45 /data0/masonmanley.com/public_html/firefly.masonmanley.com/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(67): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#46 /data0/masonmanley.com/public_html/firefly.masonmanley.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle()
#47 /data0/masonmanley.com/public_html/firefly.masonmanley.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#48 /data0/masonmanley.com/public_html/firefly.masonmanley.com/vendor/laravel/framework/src/Illuminate/Routing/Router.php(798): Illuminate\\Pipeline\\Pipeline->then()
#49 /data0/masonmanley.com/public_html/firefly.masonmanley.com/vendor/laravel/framework/src/Illuminate/Routing/Router.php(777): Illuminate\\Routing\\Router->runRouteWithinStack()
#50 /data0/masonmanley.com/public_html/firefly.masonmanley.com/vendor/laravel/framework/src/Illuminate/Routing/Router.php(741): Illuminate\\Routing\\Router->runRoute()
#51 /data0/masonmanley.com/public_html/firefly.masonmanley.com/vendor/laravel/framework/src/Illuminate/Routing/Router.php(730): Illuminate\\Routing\\Router->dispatchToRoute()
#52 /data0/masonmanley.com/public_html/firefly.masonmanley.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(200): Illuminate\\Routing\\Router->dispatch()
#53 /data0/masonmanley.com/public_html/firefly.masonmanley.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}()
#54 /data0/masonmanley.com/public_html/firefly.masonmanley.com/app/Http/Middleware/InstallationId.php(52): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#55 /data0/masonmanley.com/public_html/firefly.masonmanley.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): FireflyIII\\Http\\Middleware\\InstallationId->handle()
#56 /data0/masonmanley.com/public_html/firefly.masonmanley.com/vendor/laravel/framework/src/Illuminate/Http/Middleware/TrustProxies.php(39): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#57 /data0/masonmanley.com/public_html/firefly.masonmanley.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Http\\Middleware\\TrustProxies->handle()
#58 /data0/masonmanley.com/public_html/firefly.masonmanley.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#59 /data0/masonmanley.com/public_html/firefly.masonmanley.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.php(31): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#60 /data0/masonmanley.com/public_html/firefly.masonmanley.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\ConvertEmptyStringsToNull->handle()
#61 /data0/masonmanley.com/public_html/firefly.masonmanley.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#62 /data0/masonmanley.com/public_html/firefly.masonmanley.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php(40): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#63 /data0/masonmanley.com/public_html/firefly.masonmanley.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\TrimStrings->handle()
#64 /data0/masonmanley.com/public_html/firefly.masonmanley.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#65 /data0/masonmanley.com/public_html/firefly.masonmanley.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle()
#66 /data0/masonmanley.com/public_html/firefly.masonmanley.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(99): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#67 /data0/masonmanley.com/public_html/firefly.masonmanley.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance->handle()
#68 /data0/masonmanley.com/public_html/firefly.masonmanley.com/app/Http/Middleware/SecureHeaders.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#69 /data0/masonmanley.com/public_html/firefly.masonmanley.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): FireflyIII\\Http\\Middleware\\SecureHeaders->handle()
#70 /data0/masonmanley.com/public_html/firefly.masonmanley.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#71 /data0/masonmanley.com/public_html/firefly.masonmanley.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(175): Illuminate\\Pipeline\\Pipeline->then()
#72 /data0/masonmanley.com/public_html/firefly.masonmanley.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(144): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter()
#73 /data0/masonmanley.com/public_html/firefly.masonmanley.com/public/index.php(73): Illuminate\\Foundation\\Http\\Kernel->handle()
#74 {main}
"}
```

**Comment by masonmanley** [comment]
Fixed! Enabled File Info extension for PHP. Recommend this extension/class is added to initial install check when installing through Softaculous - I was able to install without this package.
