### ISSUE TITLE
Data-importer: Spectre import crash - $originalIban is null

### ISSUE THREAD

**Issue by v-niskala** [firefly-iii/firefly-iii#8158]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

I've been running the spectre import through docker once a week for a long time now, and about a week ago it started crashing. I haven't updates any settings or the import config recently, so I don't know why this started happening

### Debug information

```
[2023-11-15 09:23:11] production.DEBUG: Original Spectre transaction {"id":"redacted-id","account_id":"redacted-account-id","made_on":"2023-11-07T00:00:00+08:00","created_at":"2023-11-10T00:31:44+00:00","updated_at":"2023-11-10T00:31:44+00:00","mode":"transfer","status":"posted","amount":"5500","currency_code":"MYR","description":"TRANSFER CREDIT","category":"transfer","duplicated":false,"extra":{"id":null,"time":"","posting_date":"","posting_time":"","record_number":null,"information":null,"account_number":null,"original_amount":null,"original_currency_code":null,"asset_code":null,"asset_amount":null,"original_category":null,"original_subcategory":null,"customer_category_code":null,"customer_category_name":null,"possible_duplicate":null,"tags":null,"mcc":null,"payee":null,"payee_information":null,"payer":null,"payer_information":null,"type":null,"check_number":null,"units":null,"additional":null,"unit_price":null,"account_balance_snapshot":"1234567.89","categorization_confidence":"1"}} 
[2023-11-15 09:23:11] production.DEBUG: Get getAccountId(): "redacted-account-id"  
[2023-11-15 09:23:11] production.DEBUG: Get getAccountId(): "redacted-account-id"  
[2023-11-15 09:23:11] production.DEBUG: Remove Spectre categories and tags.  
[2023-11-15 09:23:11] production.DEBUG: Amount is positive: assume transfer or deposit.  
[2023-11-15 09:23:11] production.DEBUG: getPayer()  
[2023-11-15 09:23:11] production.DEBUG: isValidIBAN("")  
[2023-11-15 09:23:11] production.DEBUG: Trim: isValidIBAN("")  
[2023-11-15 09:23:11] production.DEBUG: Payer is "", payer info is "", return payer.  
[2023-11-15 09:23:11] production.DEBUG: getPayerIban()  
[2023-11-15 09:23:11] production.DEBUG: isValidIBAN("")  
[2023-11-15 09:23:11] production.DEBUG: Trim: isValidIBAN("")  
[2023-11-15 09:23:11] production.DEBUG: isValidIBAN("")  
[2023-11-15 09:23:11] production.DEBUG: Trim: isValidIBAN("")  
[2023-11-15 09:23:11] production.DEBUG: Payer IBAN is "" (empty fallback), return NULL  
[2023-11-15 09:23:11] production.DEBUG: processPositiveTransaction: source_name = "", source_iban = ""  
[2023-11-15 09:23:11] production.DEBUG: Found account type "unknown" for IBAN ""  
[2023-11-15 09:23:11] production.DEBUG: getPayer()  
[2023-11-15 09:23:11] production.DEBUG: isValidIBAN("")  
[2023-11-15 09:23:11] production.DEBUG: Trim: isValidIBAN("")  
[2023-11-15 09:23:11] production.DEBUG: Payer is "", payer info is "", return payer.  
[2023-11-15 09:23:11] production.DEBUG: getPayerIban()  
[2023-11-15 09:23:11] production.DEBUG: isValidIBAN("")  
[2023-11-15 09:23:11] production.DEBUG: Trim: isValidIBAN("")  
[2023-11-15 09:23:11] production.DEBUG: isValidIBAN("")  
[2023-11-15 09:23:11] production.DEBUG: Trim: isValidIBAN("")  
[2023-11-15 09:23:11] production.DEBUG: Payer IBAN is "" (empty fallback), return NULL  
[2023-11-15 09:23:11] production.ERROR: App\Services\Spectre\Conversion\Routine\GenerateTransactions::positiveTransactionSafetyCatch(): Argument #3 ($originalIban) must be of type string, null given, called in /var/www/html/app/Services/Spectre/Conversion/Routine/GenerateTransactions.php on line 200 {"exception":"[object] (TypeError(code: 0): App\\Services\\Spectre\\Conversion\\Routine\\GenerateTransactions::positiveTransactionSafetyCatch(): Argument #3 ($originalIban) must be of type string, null given, called in /var/www/html/app/Services/Spectre/Conversion/Routine/GenerateTransactions.php on line 200 at /var/www/html/app/Support/Internal/DuplicateSafetyCatch.php:37)
[stacktrace]
#0 /var/www/html/app/Services/Spectre/Conversion/Routine/GenerateTransactions.php(200): App\\Services\\Spectre\\Conversion\\Routine\\GenerateTransactions->positiveTransactionSafetyCatch()
#1 /var/www/html/app/Services/Spectre/Conversion/Routine/GenerateTransactions.php(142): App\\Services\\Spectre\\Conversion\\Routine\\GenerateTransactions->processPositiveTransaction()
#2 /var/www/html/app/Services/Spectre/Conversion/Routine/GenerateTransactions.php(85): App\\Services\\Spectre\\Conversion\\Routine\\GenerateTransactions->generateTransaction()
#3 /var/www/html/app/Services/Spectre/Conversion/RoutineManager.php(125): App\\Services\\Spectre\\Conversion\\Routine\\GenerateTransactions->getTransactions()
#4 /var/www/html/app/Console/AutoImports.php(392): App\\Services\\Spectre\\Conversion\\RoutineManager->start()
#5 /var/www/html/app/Console/AutoImports.php(220): App\\Console\\Commands\\AutoImport->startConversion()
#6 /var/www/html/app/Console/AutoImports.php(111): App\\Console\\Commands\\AutoImport->importFile()
#7 /var/www/html/app/Console/Commands/AutoImport.php(88): App\\Console\\Commands\\AutoImport->importFiles()
#8 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): App\\Console\\Commands\\AutoImport->handle()
#9 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#10 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure()
#11 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(35): Illuminate\\Container\\BoundMethod::callBoundMethod()
#12 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(662): Illuminate\\Container\\BoundMethod::call()
#13 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(211): Illuminate\\Container\\Container->call()
#14 /var/www/html/vendor/symfony/console/Command/Command.php(326): Illuminate\\Console\\Command->execute()
#15 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(180): Symfony\\Component\\Console\\Command\\Command->run()
#16 /var/www/html/vendor/symfony/console/Application.php(1081): Illuminate\\Console\\Command->run()
#17 /var/www/html/vendor/symfony/console/Application.php(320): Symfony\\Component\\Console\\Application->doRunCommand()
#18 /var/www/html/vendor/symfony/console/Application.php(174): Symfony\\Component\\Console\\Application->doRun()
#19 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(201): Symfony\\Component\\Console\\Application->run()
#20 /var/www/html/artisan(35): Illuminate\\Foundation\\Console\\Kernel->handle()
#21 {main}
"} 

In DuplicateSafetyCatch.php line 37:
                                                                               
  App\Services\Spectre\Conversion\Routine\GenerateTransactions::positiveTrans  
  actionSafetyCatch(): Argument #3 ($originalIban) must be of type string, nu  
  ll given, called in /var/www/html/app/Services/Spectre/Conversion/Routine/G  
  enerateTransactions.php on line 200                                          
```                                 

### Steps to reproduce

```sh
docker run \
--rm \
-v $PWD/spectre:/import \
-e FIREFLY_III_ACCESS_TOKEN=XXX \
-e FIREFLY_III_URL=XXX:XXX \
-e IMPORT_DIR_ALLOWLIST=/import \
-e WEB_SERVER=false \
-e SPECTRE_APP_ID=XXX \
-e SPECTRE_SECRET=XXX \
-e TZ=Asia/Kuala_Lumpur \
fireflyiii/data-importer:latest
```

Config:
```json
{
    "version": 3,
    "source": "fidi-0.9.9",
    "created_at": "2022-06-30T14:59:05+02:00",
    "date": "",
    "default_account": 1,
    "delimiter": "comma",
    "headers": false,
    "rules": true,
    "skip_form": false,
    "add_import_tag": true,
    "roles": [],
    "do_mapping": [],
    "mapping": [],
    "duplicate_detection_method": "cell",
    "ignore_duplicate_lines": false,
    "unique_column_index": 0,
    "unique_column_type": "external-id",
    "flow": "spectre",
    "identifier": "XXX",
    "connection": "XXX",
    "ignore_spectre_categories": true,
    "map_all_data": true,
    "accounts": {
        "account1": 1,
        "account2": 2,
	"account3": 236
    },
    "date_range": "partial",
    "date_range_number": 10,
    "date_range_unit": "d",
    "date_not_before": "2022-05-30",
    "date_not_after": "",
    "nordigen_country": "",
    "nordigen_bank": "",
    "nordigen_requisitions": [],
    "nordigen_max_days": "30",
    "conversion": false,
    "ignore_duplicate_transactions": false
}
```

**Comment by JC5** [comment]
Try running the `develop` version. Somebody reported this issue earlier on Gitter and I think I fixed it already. Let me know!

**Comment by v-niskala** [comment]
I get a slightly different error this time. It passes a few transactions and then crashes. Looks like `positiveTransactionSafetyCatch` passes, but `negativeTransactionSafetyCatch` crashes.

```
[2023-11-16 11:12:22] production.ERROR: App\Services\Spectre\Conversion\Routine\GenerateTransactions::negativeTransactionSafetyCatch(): Argument #3 ($originalIban) must be of type string, null given, called in /var/www/html/app/Services/Spectre/Conversion/Routine/GenerateTransactions.php on line 247 {"exception":"[object] (TypeError(code: 0): App\\Services\\Spectre\\Conversion\\Routine\\GenerateTransactions::negativeTransactionSafetyCatch(): Argument #3 ($originalIban) must be of type string, null given, called in /var/www/html/app/Services/Spectre/Conversion/Routine/GenerateTransactions.php on line 247 at /var/www/html/app/Support/Internal/DuplicateSafetyCatch.php:80)
[stacktrace]
#0 /var/www/html/app/Services/Spectre/Conversion/Routine/GenerateTransactions.php(247): App\\Services\\Spectre\\Conversion\\Routine\\GenerateTransactions->negativeTransactionSafetyCatch()
#1 /var/www/html/app/Services/Spectre/Conversion/Routine/GenerateTransactions.php(147): App\\Services\\Spectre\\Conversion\\Routine\\GenerateTransactions->processNegativeTransaction()
#2 /var/www/html/app/Services/Spectre/Conversion/Routine/GenerateTransactions.php(85): App\\Services\\Spectre\\Conversion\\Routine\\GenerateTransactions->generateTransaction()
#3 /var/www/html/app/Services/Spectre/Conversion/RoutineManager.php(125): App\\Services\\Spectre\\Conversion\\Routine\\GenerateTransactions->getTransactions()
#4 /var/www/html/app/Console/AutoImports.php(409): App\\Services\\Spectre\\Conversion\\RoutineManager->start()
#5 /var/www/html/app/Console/AutoImports.php(220): App\\Console\\Commands\\AutoImport->startConversion()
#6 /var/www/html/app/Console/AutoImports.php(111): App\\Console\\Commands\\AutoImport->importFile()
#7 /var/www/html/app/Console/Commands/AutoImport.php(88): App\\Console\\Commands\\AutoImport->importFiles()
#8 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): App\\Console\\Commands\\AutoImport->handle()
#9 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#10 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure()
#11 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(35): Illuminate\\Container\\BoundMethod::callBoundMethod()
#12 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(662): Illuminate\\Container\\BoundMethod::call()
#13 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(211): Illuminate\\Container\\Container->call()
#14 /var/www/html/vendor/symfony/console/Command/Command.php(326): Illuminate\\Console\\Command->execute()
#15 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(180): Symfony\\Component\\Console\\Command\\Command->run()
#16 /var/www/html/vendor/symfony/console/Application.php(1081): Illuminate\\Console\\Command->run()
#17 /var/www/html/vendor/symfony/console/Application.php(320): Symfony\\Component\\Console\\Application->doRunCommand()
#18 /var/www/html/vendor/symfony/console/Application.php(174): Symfony\\Component\\Console\\Application->doRun()
#19 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(201): Symfony\\Component\\Console\\Application->run()
#20 /var/www/html/artisan(35): Illuminate\\Foundation\\Console\\Kernel->handle()
#21 {main}
"} 

In DuplicateSafetyCatch.php line 80:
                                                                               
  App\Services\Spectre\Conversion\Routine\GenerateTransactions::negativeTrans  
  actionSafetyCatch(): Argument #3 ($originalIban) must be of type string, nu  
  ll given, called in /var/www/html/app/Services/Spectre/Conversion/Routine/G  
  enerateTransactions.php on line 247     
```

**Comment by JC5** [comment]
Lol should have seen that one coming. Try the `develop` tag again, I've refreshed it.

**Comment by v-niskala** [comment]
Works fine now, thanks!

**Comment by JC5** [comment]
Great!
