### ISSUE TITLE
4.6.5 upgrade-database trying to get property of non-object

### ISSUE THREAD

**Issue by gazben** [firefly-iii/firefly-iii#822]
Hi

If I run ``` php artisan firefly:upgrade-database ``` in the latest release I get the following error.

Stack trace:
```
[2017-09-09 09:44:03] production.ERROR: ErrorException: Trying to get property of non-object in /var/www/firefly-iii-updated/app/Console/Commands/UpgradeDatabase.php:214
Stack trace:
#0 /var/www/firefly-iii-updated/app/Console/Commands/UpgradeDatabase.php(214): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(8, 'Trying to get p...', '/var/www/firefl...', 214, Array)
#1 /var/www/firefly-iii-updated/vendor/laravel/framework/src/Illuminate/Support/Collection.php(287): FireflyIII\Console\Commands\UpgradeDatabase->FireflyIII\Console\Commands\{closure}(Object(FireflyIII\Models\TransactionJournal), 0)
#2 /var/www/firefly-iii-updated/app/Console/Commands/UpgradeDatabase.php(236): Illuminate\Support\Collection->each(Object(Closure))
#3 /var/www/firefly-iii-updated/app/Console/Commands/UpgradeDatabase.php(76): FireflyIII\Console\Commands\UpgradeDatabase->updateOtherCurrencies()
#4 [internal function]: FireflyIII\Console\Commands\UpgradeDatabase->handle()
#5 /var/www/firefly-iii-updated/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(29): call_user_func_array(Array, Array)
#6 /var/www/firefly-iii-updated/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(87): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#7 /var/www/firefly-iii-updated/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(31): Illuminate\Container\BoundMethod::callBoundMethod(Object(Illuminate\Foundation\Application), Array, Object(Closure))
#8 /var/www/firefly-iii-updated/vendor/laravel/framework/src/Illuminate/Container/Container.php(539): Illuminate\Container\BoundMethod::call(Object(Illuminate\Foundation\Application), Array, Array, NULL)
#9 /var/www/firefly-iii-updated/vendor/laravel/framework/src/Illuminate/Console/Command.php(182): Illuminate\Container\Container->call(Array)
#10 /var/www/firefly-iii-updated/vendor/symfony/console/Command/Command.php(264): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#11 /var/www/firefly-iii-updated/vendor/laravel/framework/src/Illuminate/Console/Command.php(167): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#12 /var/www/firefly-iii-updated/vendor/symfony/console/Application.php(888): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#13 /var/www/firefly-iii-updated/vendor/symfony/console/Application.php(224): Symfony\Component\Console\Application->doRunCommand(Object(FireflyIII\Console\Commands\UpgradeDatabase), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#14 /var/www/firefly-iii-updated/vendor/symfony/console/Application.php(125): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#15 /var/www/firefly-iii-updated/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(122): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#16 /var/www/firefly-iii-updated/artisan(35): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#17 {main}
```

**Comment by JC5** [comment]
What happens when you run `php artisan firefly:verify`?

**Comment by gazben** [comment]
@JC5 

```User #1 (XXX@gmail.com) has category #2 ("XYC") which has no transactions.```
This goes on for a while. Then errors pop up:

```
Error: Journal #3 has zero transactions. Open table "transaction_journals" and delete the entry with id #3
Error: Journal #4 has zero transactions. Open table "transaction_journals" and delete the entry with id #4
Error: Journal #5 has zero transactions. Open table "transaction_journals" and delete the entry with id #5
Error: Journal #6 has zero transactions. Open table "transaction_journals" and delete the entry with id #6
Error: Journal #7 has zero transactions. Open table "transaction_journals" and delete the entry with id #7
Error: Journal #8 has zero transactions. Open table "transaction_journals" and delete the entry with id #8
Error: Journal #9 has zero transactions. Open table "transaction_journals" and delete the entry with id #9
```

**Comment by JC5** [comment]
Delete those rows from your database, then the upgrade should continue just fine. I'll make sure the upgrade will ignore such entries in the future.

**Comment by JC5** [comment]
Closed to clean the list of issues.
