### ISSUE TITLE
Budget still showing up after getting removed

### ISSUE THREAD

**Issue by githubsanic** [firefly-iii/firefly-iii#8251]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [ ] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

First of all, thank you so much for Firefly-iii!
I'm a real beginner who installed Firefly-III on an Ubuntu server just to try it out. 

I have the following problem:

I created a budget, which I removed, but it still shows up. 
It does not necessarily have to be the fault of Firefly, I am self-hosted but not via Docker but manual installation. 
I am experiencing a lot of problems, but otherwise everything is running pretty smoothly. 
It's also my first report on Github, so if I didn't follow certain rules, I apologize for that. 

![image](https://github.com/firefly-iii/firefly-iii/assets/153089435/5f779c4d-71b2-4544-9053-6982b19cac05)
It's still somehow showing up but I can't interact with it. 

![image](https://github.com/firefly-iii/firefly-iii/assets/153089435/87ee51c0-7d61-4c7b-9ad2-b748973fd2e9)

### Debug information

```
Truncated from this point <----|esponseFactory->make()
#11 /home/sanic/web/************.de/public_html/firefly-iii/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(723): Illuminate\\Routing\\ResponseFactory->view()
#12 /home/sanic/web/finance.************.de/public_html/firefly-iii/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(650): Illuminate\\Foundation\\Exceptions\\Handler->renderHttpException()
#13 /home/sanic/web/finance.************.de/public_html/firefly-iii/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(556): Illuminate\\Foundation\\Exceptions\\Handler->prepareResponse()
#14 /home/sanic/web/finance.************.de/public_html/firefly-iii/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(473): Illuminate\\Foundation\\Exceptions\\Handler->renderExceptionResponse()
#15 /home/sanic/web/finance.************.de/public_html/firefly-iii/app/Exceptions/Handler.php(173): Illuminate\\Foundation\\Exceptions\\Handler->render()
#16 /home/sanic/web/finance.************.de/public_html/firefly-iii/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(51): FireflyIII\\Exceptions\\Handler->render()
#17 /home/sanic/web/finance.************.de/public_html/firefly-iii/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(185): Illuminate\\Routing\\Pipeline->handleException()
#18 /home/sanic/web/finance.************.de/public_html/firefly-iii/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#19 /home/sanic/web/finance.************.de/public_html/firefly-iii/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.php(31): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#20 /home/sanic/web/finance.************.de/public_html/firefly-iii/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\ConvertEmptyStringsToNull->handle()
#21 /home/sanic/web/finance.************.de/public_html/firefly-iii/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#22 /home/sanic/web/finance.************.de/public_html/firefly-iii/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php(40): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#23 /home/sanic/web/finance.************.de/public_html/firefly-iii/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\TrimStrings->handle()
#24 /home/sanic/web/finance.************.de/public_html/firefly-iii/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#25 /home/sanic/web/finance.************.de/public_html/firefly-iii/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle()
#26 /home/sanic/web/finance.************.de/public_html/firefly-iii/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(99): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#27 /home/sanic/web/finance.************.de/public_html/firefly-iii/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance->handle()
#28 /home/sanic/web/finance.************.de/public_html/firefly-iii/app/Http/Middleware/SecureHeaders.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#29 /home/sanic/web/finance.************.de/public_html/firefly-iii/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): FireflyIII\\Http\\Middleware\\SecureHeaders->handle()
#30 /home/sanic/web/finance.************.de/public_html/firefly-iii/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#31 /home/sanic/web/finance.************.de/public_html/firefly-iii/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(175): Illuminate\\Pipeline\\Pipeline->then()
#32 /home/sanic/web/finance.************.de/public_html/firefly-iii/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(144): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter()
#33 /home/sanic/web/finance.************.de/public_html/firefly-iii/public/index.php(73): Illuminate\\Foundation\\Http\\Kernel->handle()
#34 {main}
"} 
[2023-12-11 12:16:15] local.ERROR: Could not set locale. The following array doesnt work:  ["de_DE.utf8","de_DE.UTF-8"] 
[2023-12-11 12:16:15] local.ERROR: Could not set locale. The following array doesnt work:  ["de_DE.utf8","de_DE.UTF-8"] 
[2023-12-11 12:16:15] local.ERROR: Could not set locale. The following array doesnt work:  ["de_DE.utf8","de_DE.UTF-8"] 
[2023-12-11 12:17:43] local.ERROR: Could not set locale. The following array doesnt work:  ["de_DE.utf8","de_DE.UTF-8"] 
[2023-12-11 12:17:44] local.ERROR: Could not set locale. The following array doesnt work:  ["de_DE.utf8","de_DE.UTF-8"] 
[2023-12-11 12:17:44] local.ERROR: Could not set locale. The following array doesnt work:  ["de_DE.utf8","de_DE.UTF-8"] 
[2023-12-11 12:17:46] local.ERROR: Could not set locale. The following array doesnt work:  ["de_DE.utf8","de_DE.UTF-8"] 
[2023-12-11 12:17:46] local.ERROR: Could not set locale. The following array doesnt work:  ["de_DE.utf8","de_DE.UTF-8"] 
[2023-12-11 12:20:55] local.ERROR: Could not set locale. The following array doesnt work:  ["de_DE.utf8","de_DE.UTF-8"] 
[2023-12-11 12:20:55] local.ERROR: Could not set locale. The following array doesnt work:  ["de_DE.utf8","de_DE.UTF-8"] 
[2023-12-11 12:20:57] local.ERROR: Could not set locale. The following array doesnt work:  ["de_DE.utf8","de_DE.UTF-8"] 
[2023-12-11 12:20:57] local.ERROR: Could not set locale. The following array doesnt work:  ["de_DE.utf8","de_DE.UTF-8"] 
[2023-12-11 12:20:58] local.ERROR: Could not set locale. The following array doesnt work:  ["de_DE.utf8","de_DE.UTF-8"] 
[2023-12-11 12:20:58] local.ERROR: Could not set locale. The following array doesnt work:  ["de_DE.utf8","de_DE.UTF-8"] 
[2023-12-11 12:23:43] local.ERROR: Could not set locale. The following array doesnt work:  ["de_DE.utf8","de_DE.UTF-8"] 
[2023-12-11 12:23:44] local.ERROR: Could not set locale. The following array doesnt work:  ["de_DE.utf8","de_DE.UTF-8"] 
[2023-12-11 12:23:44] local.ERROR: Could not set locale. The following array doesnt work:  ["de_DE.utf8","de_DE.UTF-8"] 
[2023-12-11 12:23:45] local.ERROR: Could not set locale. The following array doesnt work:  ["de_DE.utf8","de_DE.UTF-8"] 
[2023-12-11 12:23:45] local.ERROR: Could not set locale. The following array doesnt work:  ["de_DE.utf8","de_DE.UTF-8"] 
[2023-12-11 12:23:45] local.ERROR: Could not set locale. The following array doesnt work:  ["de_DE.utf8","de_DE.UTF-8"] 
[2023-12-11 12:23:46] local.ERROR: Could not set locale. The following array doesnt work:  ["de_DE.utf8","de_DE.UTF-8"] 
[2023-12-11 12:23:46] local.ERROR: Could not set locale. The following array doesnt work:  ["de_DE.utf8","de_DE.UTF-8"] 
[2023-12-11 12:24:42] local.ERROR: Could not set locale. The following array doesnt work:  ["de_DE.utf8","de_DE.UTF-8"] 
[2023-12-11 12:24:42] local.ERROR: Could not set locale. The following array doesnt work:  ["de_DE.utf8","de_DE.UTF-8"] 
[2023-12-11 12:24:43] local.ERROR: Could not set locale. The following array doesnt work:  ["de_DE.utf8","de_DE.UTF-8"] 
[2023-12-11 12:24:48] local.ERROR: Could not set locale. The following array doesnt work:  ["de_DE.utf8","de_DE.UTF-8"] 
[2023-12-11 12:24:48] local.ERROR: Could not set locale. The following array doesnt work:  ["de_DE.utf8","de_DE.UTF-8"] 
[2023-12-11 12:24:49] local.ERROR: Could not set locale. The following array doesnt work:  ["de_DE.utf8","de_DE.UTF-8"] 
[2023-12-11 12:24:49] local.ERROR: Could not set locale. The following array doesnt work:  ["de_DE.utf8","de_DE.UTF-8"] 
[2023-12-11 12:24:49] local.ERROR: Could not set locale. The following array doesnt work:  ["de_DE.utf8","de_DE.UTF-8"] 
[2023-12-11 12:24:49] local.ERROR: Could not set locale. The following array doesnt work:  ["de_DE.utf8","de_DE.UTF-8"] 
[2023-12-11 12:24:50] local.ERROR: Could not set locale. The following array doesnt work:  ["de_DE.utf8","de_DE.UTF-8"] 
[2023-12-11 12:24:50] local.ERROR: Could not set locale. The following array doesnt work:  ["de_DE.utf8","de_DE.UTF-8"] 
[2023-12-11 12:24:52] local.ERROR: Could not set locale. The following array doesnt work:  ["de_DE.utf8","de_DE.UTF-8"] 
[2023-12-11 12:24:52] local.ERROR: Could not set locale. The following array doesnt work:  ["de_DE.utf8","de_DE.UTF-8"] 
[2023-12-11 12:24:52] local.ERROR: Could not set locale. The following array doesnt work:  ["de_DE.utf8","de_DE.UTF-8"] 
[2023-12-11 12:25:31] local.ERROR: Could not set locale. The following array doesnt work:  ["de_DE.utf8","de_DE.UTF-8"] 
[2023-12-11 12:25:32] local.ERROR: Could not set locale. The following array doesnt work:  ["de_DE.utf8","de_DE.UTF-8"] 
[2023-12-11 12:25:32] local.ERROR: Could not set locale. The following array doesnt work:  ["de_DE.utf8","de_DE.UTF-8"] 
[2023-12-11 12:25:32] local.ERROR: Could not set locale. The following array doesnt work:  ["de_DE.utf8","de_DE.UTF-8"] 
[2023-12-11 12:25:38] local.ERROR: Could not set locale. The following array doesnt work:  ["de_DE.utf8","de_DE.UTF-8"] 
[2023-12-11 12:25:38] local.ERROR: Could not set locale. The following array doesnt work:  ["de_DE.utf8","de_DE.UTF-8"] 
[2023-12-11 12:25:39] local.ERROR: Could not set locale. The following array doesnt work:  ["de_DE.utf8","de_DE.UTF-8"] 
[2023-12-11 12:26:15] local.ERROR: Could not set locale. The following array doesnt work:  ["de_DE.utf8","de_DE.UTF-8"] 
[2023-12-11 12:26:16] local.ERROR: Could not set locale. The following array doesnt work:  ["de_DE.utf8","de_DE.UTF-8"] 
[2023-12-11 12:26:16] local.ERROR: Could not set locale. The following array doesnt work:  ["de_DE.utf8","de_DE.UTF-8"] 
[2023-12-11 12:29:52] local.ERROR: Could not set locale. The following array doesnt work:  ["de_DE.utf8","de_DE.UTF-8"] 
[2023-12-11 12:29:53] local.ERROR: Could not set locale. The following array doesnt work:  ["de_DE.utf8","de_DE.UTF-8"] 
[2023-12-11 12:34:22] local.ERROR: Could not set locale. The following array doesnt work:  ["de_DE.utf8","de_DE.UTF-8"] 
[2023-12-11 12:34:22] local.ERROR: Could not set locale. The following array doesnt work:  ["de_DE.utf8","de_DE.UTF-8"] 
[2023-12-11 12:34:23] local.ERROR: Could not set locale. The following array doesnt work:  ["de_DE.utf8","de_DE.UTF-8"] 
[2023-12-11 12:34:23] local.ERROR: Could not set locale. The following array doesnt work:  ["de_DE.utf8","de_DE.UTF-8"] 
[2023-12-11 12:34:24] local.ERROR: Could not set locale. The following array doesnt work:  ["de_DE.utf8","de_DE.UTF-8"] 
[2023-12-11 12:34:24] local.ERROR: Could not set locale. The following array doesnt work:  ["de_DE.utf8","de_DE.UTF-8"] 
[2023-12-11 12:44:59] local.ERROR: Could not set locale. The following array doesnt work:  ["de_DE.utf8","de_DE.UTF-8"] 
[2023-12-11 12:44:59] local.ERROR: Could not set locale. The following array doesnt work:  ["de_DE.utf8","de_DE.UTF-8"] 
[2023-12-11 12:45:20] local.ERROR: Could not set locale. The following array doesnt work:  ["de_DE.utf8","de_DE.UTF-8"] 
[2023-12-11 12:45:20] local.ERROR: Could not set locale. The following array doesnt work:  ["de_DE.utf8","de_DE.UTF-8"] 
[2023-12-11 12:45:20] local.ERROR: Could not set locale. The following array doesnt work:  ["de_DE.utf8","de_DE.UTF-8"] 
[2023-12-11 12:45:20] local.ERROR: Could not set locale. The following array doesnt work:  ["de_DE.utf8","de_DE.UTF-8"] 
[2023-12-11 12:45:20] local.ERROR: Could not set locale. The following array doesnt work:  ["de_DE.utf8","de_DE.UTF-8"] 
[2023-12-11 12:45:21] local.ERROR: Could not set locale. The following array doesnt work:  ["de_DE.utf8","de_DE.UTF-8"] 
[2023-12-11 12:45:21] local.ERROR: Could not set locale. The following array doesnt work:  ["de_DE.utf8","de_DE.UTF-8"] 
[2023-12-11 12:45:21] local.ERROR: Could not set locale. The following array doesnt work:  ["de_DE.utf8","de_DE.UTF-8"] 
[2023-12-11 12:45:21] local.ERROR: Could not set locale. The following array doesnt work:  ["de_DE.utf8","de_DE.UTF-8"] 
[2023-12-11 12:45:21] local.ERROR: Could not set locale. The following array doesnt work:  ["de_DE.utf8","de_DE.UTF-8"] 
[2023-12-11 12:45:21] local.ERROR: Could not set locale. The following array doesnt work:  ["de_DE.utf8","de_DE.UTF-8"] 
[2023-12-11 12:45:21] local.ERROR: Could not set locale. The following array doesnt work:  ["de_DE.utf8","de_DE.UTF-8"] 
[2023-12-11 12:45:21] local.ERROR: Could not set locale. The following array doesnt work:  ["de_DE.utf8","de_DE.UTF-8"] 
[2023-12-11 12:45:22] local.ERROR: Could not set locale. The following array doesnt work:  ["de_DE.utf8","de_DE.UTF-8"] 
[2023-12-11 12:45:22] local.ERROR: Could not set locale. The following array doesnt work:  ["de_DE.utf8","de_DE.UTF-8"] 
[2023-12-11 12:45:22] local.ERROR: Could not set locale. The following array doesnt work:  ["de_DE.utf8","de_DE.UTF-8"] 
[2023-12-11 12:45:24] local.ERROR: Could not set locale. The following array doesnt work:  ["de_DE.utf8","de_DE.UTF-8"] 
[2023-12-11 12:45:24] local.ERROR: Could not set locale. The following array doesnt work:  ["de_DE.utf8","de_DE.UTF-8"] 
[2023-12-11 12:45:25] local.ERROR: Could not set locale. The following array doesnt work:  ["de_DE.utf8","de_DE.UTF-8"] 
[2023-12-11 12:45:25] local.ERROR: Could not set locale. The following array doesnt work:  ["de_DE.utf8","de_DE.UTF-8"] 
[2023-12-11 12:45:26] local.ERROR: Could not set locale. The following array doesnt work:  ["de_DE.utf8","de_DE.UTF-8"] 
[2023-12-11 12:45:26] local.ERROR: Could not set locale. The following array doesnt work:  ["de_DE.utf8","de_DE.UTF-8"] 
[2023-12-11 12:48:34] local.ERROR: Could not set locale. The following array doesnt work:  ["de_DE.utf8","de_DE.UTF-8"] 
[2023-12-11 12:48:34] local.ERROR: Could not set locale. The following array doesnt work:  ["de_DE.utf8","de_DE.UTF-8"] 
[2023-12-11 12:48:35] local.ERROR: Could not set locale. The following array doesnt work:  ["de_DE.utf8","de_DE.UTF-8"] 
[2023-12-11 12:48:35] local.ERROR: Could not set locale. The following array doesnt work:  ["de_DE.utf8","de_DE.UTF-8"] 
[2023-12-11 12:48:36] local.ERROR: Could not set locale. The following array doesnt work:  ["de_DE.utf8","de_DE.UTF-8"] 
[2023-12-11 12:48:36] local.ERROR: Could not set locale. The following array doesnt work:  ["de_DE.utf8","de_DE.UTF-8"] 
[2023-12-11 12:48:36] local.ERROR: Could not set locale. The following array doesnt work:  ["de_DE.utf8","de_DE.UTF-8"] 
[2023-12-11 12:48:37] local.ERROR: Could not set locale. The following array doesnt work:  ["de_DE.utf8","de_DE.UTF-8"] 
[2023-12-11 12:48:37] local.ERROR: Could not set locale. The following array doesnt work:  ["de_DE.utf8","de_DE.UTF-8"] 
[2023-12-11 12:48:37] local.ERROR: Could not set locale. The following array doesnt work:  ["de_DE.utf8","de_DE.UTF-8"] 
[2023-12-11 12:48:37] local.ERROR: Could not set locale. The following array doesnt work:  ["de_DE.utf8","de_DE.UTF-8"] 
[2023-12-11 19:48:43] local.WARNING: Login attempt failed.  
[2023-12-11 19:48:49] local.WARNING: Login attempt failed.  
[2023-12-11 21:24:28] local.ERROR: Set is not an array! ""  
[2023-12-11 21:29:47] local.WARNING: file_exists(): open_basedir restriction in effect. File(/var/www/counter-main.txt) is not within the allowed path(s): (/home/sanic/.composer:/home/sanic/web/finance.************.de/public_html:/home/sanic/web/finance.************.de/private:/home/sanic/web/finance.************.de/public_shtml:/home/sanic/tmp:/tmp:/bin:/usr/bin:/usr/local/bin:/usr/share:/opt)  
[2023-12-11 21:29:47] local.WARNING: file_exists(): open_basedir restriction in effect. File(/var/www/build-date-main.txt) is not within the allowed path(s): (/home/sanic/.composer:/home/sanic/web/finance.************.de/public_html:/home/sanic/web/finance.team************sanic.de/private:/home/sanic/web/finance.************.de/public_shtml:/home/sanic/tmp:/tmp:/bin:/usr/bin:/usr/local/bin:/usr/share:/opt)  

```

**Comment by JC5** [comment]
Which version are you running?

**Comment by githubsanic** [comment]
I'm on 6.0.30

Am Di., 12. Dez. 2023 um 05:48 Uhr schrieb James Cole <
***@***.***>:

**Comment by JC5** [comment]
Thanks, I see what you mean, I'll pick it up!
