### ISSUE TITLE
The "phpiredis" extension is required by this connection backend

### ISSUE THREAD

**Issue by rizlas** [firefly-iii/firefly-iii#8373]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

I'm setting redis as CACHE_DRIVER and SESSION_DRIVER. Firefly starts up with an error saying this:

`The "phpiredis" extension is required by this connection backend. `

### Debug information

With debug enabled I get this

```
[2024-01-11 09:32:51] local.ERROR: The "phpiredis" extension is required by this connection backend. {"exception":"[object] (Predis\\NotSupportedException(code: 0): The \"phpiredis\" extension is required by this connection backend. at /var/www/html/vendor/predis/predis/src/Connection/WebdisConnection.php:108)
[stacktrace]
#0 /var/www/html/vendor/predis/predis/src/Connection/WebdisConnection.php(61): Predis\\Connection\\WebdisConnection->assertExtensions()
#1 /var/www/html/vendor/predis/predis/src/Connection/Factory.php(100): Predis\\Connection\\WebdisConnection->__construct()
#2 /var/www/html/vendor/predis/predis/src/Client.php(133): Predis\\Connection\\Factory->create()
#3 /var/www/html/vendor/predis/predis/src/Client.php(74): Predis\\Client::createConnection()
#4 /var/www/html/vendor/laravel/framework/src/Illuminate/Redis/Connectors/PredisConnector.php(30): Predis\\Client->__construct()
#5 /var/www/html/vendor/laravel/framework/src/Illuminate/Redis/RedisManager.php(110): Illuminate\\Redis\\Connectors\\PredisConnector->connect()
#6 /var/www/html/vendor/laravel/framework/src/Illuminate/Redis/RedisManager.php(91): Illuminate\\Redis\\RedisManager->resolve()
#7 /var/www/html/vendor/laravel/framework/src/Illuminate/Cache/RedisStore.php(330): Illuminate\\Redis\\RedisManager->connection()
#8 /var/www/html/vendor/laravel/framework/src/Illuminate/Cache/RedisStore.php(65): Illuminate\\Cache\\RedisStore->connection()
#9 /var/www/html/vendor/laravel/framework/src/Illuminate/Cache/Repository.php(99): Illuminate\\Cache\\RedisStore->get()
#10 /var/www/html/vendor/laravel/framework/src/Illuminate/Cache/Repository.php(70): Illuminate\\Cache\\Repository->get()
#11 /var/www/html/vendor/laravel/framework/src/Illuminate/Cache/CacheManager.php(429): Illuminate\\Cache\\Repository->has()
#12 /var/www/html/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(355): Illuminate\\Cache\\CacheManager->__call()
#13 /var/www/html/app/Support/FireflyConfig.php(57): Illuminate\\Support\\Facades\\Facade::__callStatic()
#14 /var/www/html/app/Support/System/GeneratesInstallationId.php(38): FireflyIII\\Support\\FireflyConfig->get()
#15 /var/www/html/app/Http/Middleware/InstallationId.php(45): FireflyIII\\Http\\Middleware\\InstallationId->generateInstallationId()
#16 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): FireflyIII\\Http\\Middleware\\InstallationId->handle()
#17 /var/www/html/vendor/laravel/framework/src/Illuminate/Http/Middleware/TrustProxies.php(39): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#18 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Http\\Middleware\\TrustProxies->handle()
#19 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#20 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.php(31): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#21 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Foundation\\Http\\Middleware\\ConvertEmptyStringsToNull->handle()
#22 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#23 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php(40): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#24 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Foundation\\Http\\Middleware\\TrimStrings->handle()
#25 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#26 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle()
#27 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(99): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#28 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance->handle()
#29 /var/www/html/app/Http/Middleware/SecureHeaders.php(48): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#30 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): FireflyIII\\Http\\Middleware\\SecureHeaders->handle()
#31 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(119): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#32 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(175): Illuminate\\Pipeline\\Pipeline->then()
#33 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(144): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter()
#34 /var/www/html/public/index.php(73): Illuminate\\Foundation\\Http\\Kernel->handle()
#35 {main}
"} 
[2024-01-11 09:32:51] local.DEBUG: Now in Handler::render()  
[2024-01-11 09:32:51] local.DEBUG: Error "Predis\NotSupportedException" has no Firefly III treatment, parent will handle.  

```

### Expected behaviour

Firefly running without errors 😅 

### Steps to reproduce

Set this environment vars

```
# If you're looking for performance improvements, you could install memcached or redis
CACHE_DRIVER=redis
SESSION_DRIVER=redis

# If you set either of the options above to 'redis', you might want to update these settings too
# If you use Docker or similar, you can set REDIS_HOST_FILE, REDIS_PASSWORD_FILE or
# REDIS_PORT_FILE to set the value from a file instead of from an environment variable

# can be tcp, unix or http
REDIS_SCHEME=http

# use only when using 'unix' for REDIS_SCHEME. Leave empty otherwise.
REDIS_PATH=

# use only when using 'tcp' or 'http' for REDIS_SCHEME. Leave empty otherwise.
REDIS_HOST=redis
REDIS_PORT=6379

# Use only with Redis 6+ with proper ACL set. Leave empty otherwise.
REDIS_USERNAME=default
REDIS_PASSWORD=supersecretpassword

# always use quotes and make sure redis db "0" and "1" exists. Otherwise change accordingly.
REDIS_DB="0"
REDIS_CACHE_DB="1"
```

(I also tried with empty REDIS_USERNAME)

### Additional info

My setup is docker based.

This is the service for redis, the rest is standard as documentation.

```
  redis:
    image: redis:7.2-alpine
    restart: unless-stopped
    container_name: firefly_iii_redis
    env_file:
      - env/redis.env
    command: /bin/sh -c 'redis-server --appendonly yes --requirepass $${REDIS_PASSWORD}'
    volumes:
      - firefly_iii_redis_cache_data:/data
```

Firefly version:

```
  firefly:
    image: fireflyiii/core:version-6.1
```

Test authentication in redis container, via redis-cli, and it is working fine with both

```
AUTH password
AUTH default password
```

`ACL LIST` appears only after authentication. Default user exists.

**Comment by rizlas** [comment]
Let me know, so I can give you a rapid feedback.

Thanks 😄

**Comment by JC5** [comment]
Should be ready in a few minutes. I'm curious if you run into errors, my own redis-enabled docker setup had no problems all this time.

**Comment by rizlas** [comment]
Still not working for me. Really dunno what is wrong or what I'm doing wrong.

**Comment by JC5** [comment]
Welp, that's too bad then. I'm not able to custom compile extensions into the docker image I'm afraid.

**Comment by rizlas** [comment]
Mmm so why your setup with redis is working? Are you using docker?

**Comment by rizlas** [comment]
Note that the error is saying php`i`redis e not phpredis. Unsure what to use. Installing phpredis doesn't fix the problem:

```Dockerfile
FROM fireflyiii/core:version-6.1

RUN apt-get update && apt-get install -y wget && \
    rm -rf /var/lib/apt/lists/* && \
    wget --no-verbose --show-progress --progress=bar:force:noscroll \
    https://github.com/FriendsOfPHP/pickle/releases/latest/download/pickle.phar && \
    chmod +x pickle.phar && \
    mv pickle.phar /usr/bin/pickle && \
    pickle install redis --no-interaction
```

https://github.com/phpredis/phpredis
https://github.com/nrk/phpiredis

**Comment by JC5** [comment]
I use docker, my redis configuration is literally this:

```
  redis:
    image: redis
```

**Comment by rizlas** [comment]
Ok, I think I've found the problem.

Can you try with:

```env
# can be tcp, unix or http
REDIS_SCHEME=http
```

My problem vanished when I switched to tcp. But if I use http it appears again.

**Comment by JC5** [comment]
Indeed. I'll update the `.env.example` instructions.
