### ISSUE TITLE
Importing camt.053 file fails during conversion step

### ISSUE THREAD

**Issue by ltouroumov** [firefly-iii/firefly-iii#8408]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

When attempting to import a camt.053 file (redacted excerpt below) the /import/convert step fails with the following error message: "The conversion could not be started, or failed due to an error. Please check the log files. Sorry about this :("

```xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Document xsi:schemaLocation="urn:iso:std:iso:20022:tech:xsd:camt.053.001.08 camt.053.001.08.xsd" xmlns="urn:iso:std:iso:20022:tech:xsd:camt.053.001.08" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <BkToCstmrStmt>
        <GrpHdr>
            <MsgId>MSG-C053-240117010511-01</MsgId>
            <CreDtTm>2024-01-17T13:05:11.806+01:00</CreDtTm>
            <AddtlInf>PRODUCTIVE</AddtlInf>
        </GrpHdr>
        <Stmt>
            <Id>STM-C053-240117010511-01</Id>
            <ElctrncSeqNb>3</ElctrncSeqNb>
            <CreDtTm>2024-01-17T13:05:11.806+01:00</CreDtTm>
            <FrToDt>
                <FrDtTm>2023-01-01T00:00:00.000+01:00</FrDtTm>
                <ToDtTm>2023-12-31T23:59:59.999+01:00</ToDtTm>
            </FrToDt>
            <Acct>
                <Id>
                    <IBAN>CH2889144364242373258</IBAN>
                </Id>
                <Ccy>CHF</Ccy>
                <Ownr>
                    <Nm>REDACTED</Nm>
                </Ownr>
                <Svcr>
                    <FinInstnId>
                        <Nm>REDACTED</Nm>
                    </FinInstnId>
                </Svcr>
            </Acct>
            <Bal>
                <Tp>
                    <CdOrPrtry>
                        <Cd>OPBD</Cd>
                    </CdOrPrtry>
                </Tp>
                <Amt Ccy="CHF">0</Amt>
                <CdtDbtInd>CRDT</CdtDbtInd>
                <Dt>
                    <Dt>2023-01-25</Dt>
                </Dt>
            </Bal>
            <Bal>
                <Tp>
                    <CdOrPrtry>
                        <Cd>CLBD</Cd>
                    </CdOrPrtry>
                </Tp>
                <Amt Ccy="CHF">0</Amt>
                <CdtDbtInd>CRDT</CdtDbtInd>
                <Dt>
                    <Dt>2023-12-31</Dt>
                </Dt>
            </Bal>
            <Ntry>
                <Amt Ccy="CHF">11400</Amt>
                <CdtDbtInd>CRDT</CdtDbtInd>
                <RvslInd>false</RvslInd>
                <Sts>
                    <Cd>BOOK</Cd>
                </Sts>
                <BookgDt>
                    <Dt>2023-03-02</Dt>
                </BookgDt>
                <ValDt>
                    <Dt>2023-03-02</Dt>
                </ValDt>
                <AcctSvcrRef>15137857742</AcctSvcrRef>
                <BkTxCd>
                    <Domn>
                        <Cd>PMNT</Cd>
                        <Fmly>
                            <Cd>RCDT</Cd>
                            <SubFmlyCd>BOOK</SubFmlyCd>
                        </Fmly>
                    </Domn>
                    <Prtry>
                        <Cd>1000</Cd>
                    </Prtry>
                </BkTxCd>
                <AmtDtls>
                    <TxAmt>
                        <Amt Ccy="CHF">11400</Amt>
                    </TxAmt>
                </AmtDtls>
                <NtryDtls>
                    <TxDtls>
                        <Refs>
                            <EndToEndId>NOTPROVIDED</EndToEndId>
                            <UETR>919abb58-3205-4d82-b7ff-d5a3c8d3f49c</UETR>
                        </Refs>
                        <Amt Ccy="CHF">11400</Amt>
                        <CdtDbtInd>CRDT</CdtDbtInd>
                        <BkTxCd>
                            <Domn>
                                <Cd>PMNT</Cd>
                                <Fmly>
                                    <Cd>RCDT</Cd>
                                    <SubFmlyCd>BOOK</SubFmlyCd>
                                </Fmly>
                            </Domn>
                        </BkTxCd>
                        <RltdPties>
                            <Dbtr>
                                <Pty>
                                    <Nm>REDACTED</Nm>
                                    <PstlAdr>
                                        <Ctry>CH</Ctry>
                                        <AdrLine>REDACTED</AdrLine>
                                    </PstlAdr>
                                </Pty>
                            </Dbtr>
                            <DbtrAcct>
                                <Id>
                                    <IBAN>CH6289144563478762737</IBAN>
                                </Id>
                            </DbtrAcct>
                            <Cdtr>
                                <Pty>
                                    <Nm>REDACTED</Nm>
                                </Pty>
                            </Cdtr>
                            <CdtrAcct>
                                <Id>
                                    <IBAN>CH2889144364242373258</IBAN>
                                </Id>
                            </CdtrAcct>
                        </RltdPties>
                        <RmtInf>
                            <Ustrd>Buggy Transfer (TX)</Ustrd>
                        </RmtInf>
                    </TxDtls>
                </NtryDtls>
                <AddtlNtryInf>Buggy Transfer (Entry)</AddtlNtryInf>
            </Ntry>
        </Stmt>
    </BkToCstmrStmt>
</Document>
```

### Debug information

Debug information generated at 2024-01-17 13:49:05 Europe/Amsterdam for Firefly III Data Importer version **1.4.1**.

<table><tr><th colspan="2">System information</th></tr><tr><th>Item</th><th>Value</th></tr><tr><td>Version</td><td>1.4.1</td></tr><tr><td>System</td><td>PHP 8.3.2, Linux, fpm-fcgi</td></tr></table><table><tr><th colspan="2">App information</th></tr><tr><th>Item</th><th>Value</th></tr><tr><td>Timezone</td><td>Europe/Amsterdam, Europe/Zurich</td></tr><tr><td>Environment</td><td>local</td></tr><tr><td>Debug mode</td><td>false, cache 'file'</td></tr><tr><td>Log level</td><td>debug, stack</td></tr><tr><td>Display errors</td><td>Off, ALL errors</td></tr><tr><td>BCscale</td><td>12</td></tr><tr><td>Trusted proxies</td><td></td></tr></table><table><tr><th colspan="2">User information</th></tr><tr><th>Item</th><th>Value</th></tr><tr><td>User agent</td><td>Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:121.0) Gecko/20100101 Firefox/121.0</td></tr></table>

```
[2024-01-17 13:53:00] local.DEBUG: Pseudo-transaction is: {"transactions":[{"note":{"data":{"messageId":"MSG-C053-240117010511-01","statementId":"STM-C053-240117010511-01","entryBtcDomainCode":"PMNT","entryBtcSubFamilyCode":"BOOK","entryDetailBtcFamilyCode":"RCDT"},"mapping":[]},"date_process":{"data":{"statementCreationDate":"2024-01-17 13:05:11"},"mapping":[]},"account-iban":{"data":{"statementAccountIban":"CH2889144364242373258"},"mapping":[]},"external-id":{"data":{"entryAccountServicerReference":"15137857742"},"mapping":[]},"description":{"data":{"entryAdditionalInfo":"Buggy Transfer (Entry)","entryDetailRemittanceInformationUnstructuredBlockMessage":"Buggy Transfer (TX)"},"mapping":[]},"amount":{"data":{"entryAmount":"11400.00"},"mapping":[]},"currency-code":{"data":{"entryAmountCurrency":"CHF"},"mapping":[]},"date_payment":{"data":{"entryValueDate":"2023-03-02 00:00:00"},"mapping":[]},"date_book":{"data":{"entryBookingDate":"2023-03-02 00:00:00"},"mapping":[]},"opposing-iban":{"data":{"entryDetailOpposingAccountIban":"CH6289144563478762737"},"mapping":[]},"opposing-name":{"data":{"entryDetailOpposingName":"REDACTED"},"mapping":[]}}],"splits":1}
[2024-01-17 13:53:00] local.DEBUG: [1/1] Now done with transaction.
[2024-01-17 13:53:00] local.DEBUG: Done converting all 1 transactions into pseudo-transactions.
[2024-01-17 13:53:00] local.DEBUG: Now mapping 1 transaction(s)
[2024-01-17 13:53:00] local.DEBUG: [1/1] Now mapping.
[2024-01-17 13:53:00] local.DEBUG: Transaction has 1 split(s)
[2024-01-17 13:53:00] local.DEBUG: Description is "Buggy Transfer (TX)"
[2024-01-17 13:53:00] local.ERROR: abs(): Argument #1 ($num) must be of type int|float, null given {"exception":"[object] (TypeError(code: 0): abs(): Argument #1 ($num) must be of type int|float, null given at /var/www/firefly-importer/app/Services/Camt/Conversion/TransactionMapper.php:516)
[stacktrace]
#0 /var/www/firefly-importer/app/Services/Camt/Conversion/TransactionMapper.php(516): abs()
#1 /var/www/firefly-importer/app/Services/Camt/Conversion/TransactionMapper.php(346): App\\Services\\Camt\\Conversion\\TransactionMapper->mapTransactionJournal()
#2 /var/www/firefly-importer/app/Services/Camt/Conversion/TransactionMapper.php(45): App\\Services\\Camt\\Conversion\\TransactionMapper->mapTransactionGroup()
#3 /var/www/firefly-importer/app/Services/Camt/Conversion/RoutineManager.php(117): App\\Services\\Camt\\Conversion\\TransactionMapper->map()
#4 /var/www/firefly-importer/app/Http/Controllers/Import/ConversionController.php(183): App\\Services\\Camt\\Conversion\\RoutineManager->start()
#5 /var/www/firefly-importer/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): App\\Http\\Controllers\\Import\\ConversionController->start()
#6 /var/www/firefly-importer/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(43): Illuminate\\Routing\\Controller->callAction()
#7 /var/www/firefly-importer/vendor/laravel/framework/src/Illuminate/Routing/Route.php(259): Illuminate\\Routing\\ControllerDispatcher->dispatch()
#8 /var/www/firefly-importer/vendor/laravel/framework/src/Illuminate/Routing/Route.php(205): Illuminate\\Routing\\Route->runController()
#9 /var/www/firefly-importer/vendor/laravel/framework/src/Illuminate/Routing/Router.php(806): Illuminate\\Routing\\Route->run()
#10 /var/www/firefly-importer/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(144): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}()
#11 /var/www/firefly-importer/app/Http/Middleware/IsReadyForStep.php(44): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#12 /var/www/firefly-importer/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): App\\Http\\Middleware\\ConversionControllerMiddleware->handle()
#13 /var/www/firefly-importer/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(50): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#14 /var/www/firefly-importer/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle()
#15 /var/www/firefly-importer/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(78): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#16 /var/www/firefly-importer/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle()
#17 /var/www/firefly-importer/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#18 /var/www/firefly-importer/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle()
#19 /var/www/firefly-importer/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(121): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#20 /var/www/firefly-importer/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(64): Illuminate\\Session\\Middleware\\StartSession->handleStatefulRequest()
#21 /var/www/firefly-importer/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Session\\Middleware\\StartSession->handle()
#22 /var/www/firefly-importer/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#23 /var/www/firefly-importer/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle()
#24 /var/www/firefly-importer/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(67): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#25 /var/www/firefly-importer/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle()
#26 /var/www/firefly-importer/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(119): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#27 /var/www/firefly-importer/vendor/laravel/framework/src/Illuminate/Routing/Router.php(805): Illuminate\\Pipeline\\Pipeline->then()
#28 /var/www/firefly-importer/vendor/laravel/framework/src/Illuminate/Routing/Router.php(784): Illuminate\\Routing\\Router->runRouteWithinStack()
#29 /var/www/firefly-importer/vendor/laravel/framework/src/Illuminate/Routing/Router.php(748): Illuminate\\Routing\\Router->runRoute()
#30 /var/www/firefly-importer/vendor/laravel/framework/src/Illuminate/Routing/Router.php(737): Illuminate\\Routing\\Router->dispatchToRoute()
#31 /var/www/firefly-importer/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(200): Illuminate\\Routing\\Router->dispatch()
#32 /var/www/firefly-importer/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(144): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}()
#33 /var/www/firefly-importer/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#34 /var/www/firefly-importer/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.php(31): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#35 /var/www/firefly-importer/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Foundation\\Http\\Middleware\\ConvertEmptyStringsToNull->handle()
#36 /var/www/firefly-importer/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#37 /var/www/firefly-importer/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php(40): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#38 /var/www/firefly-importer/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Foundation\\Http\\Middleware\\TrimStrings->handle()
#39 /var/www/firefly-importer/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#40 /var/www/firefly-importer/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle()
#41 /var/www/firefly-importer/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(99): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#42 /var/www/firefly-importer/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance->handle()
#43 /var/www/firefly-importer/vendor/laravel/framework/src/Illuminate/Http/Middleware/HandleCors.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#44 /var/www/firefly-importer/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Http\\Middleware\\HandleCors->handle()
#45 /var/www/firefly-importer/vendor/laravel/framework/src/Illuminate/Http/Middleware/TrustProxies.php(39): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#46 /var/www/firefly-importer/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Http\\Middleware\\TrustProxies->handle()
#47 /var/www/firefly-importer/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(119): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#48 /var/www/firefly-importer/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(175): Illuminate\\Pipeline\\Pipeline->then()
#49 /var/www/firefly-importer/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(144): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter()
#50 /var/www/firefly-importer/public/index.php(76): Illuminate\\Foundation\\Http\\Kernel->handle()
#51 {main}
"}
```

### Expected behaviour

The conversion shouldn't fail.

### Steps to reproduce

1. Attempt to import the file provided above.

**Comment by JC5** [comment]
Hi there! Thanks for reporting!

This issue was reported earlier this week and should be fixed in the next Data Importer release. In the mean time, you can use `:develop`. Thanks for your patience!

https://github.com/orgs/firefly-iii/discussions/8367
