### ISSUE TITLE
Triggering rule-group trough API not working

### ISSUE THREAD

**Issue by Sceptorrh** [firefly-iii/firefly-iii#8493]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

I am trying to trigger a rule-group from the API using:

/v1/rule-groups/{id}/trigger

When using this I get the output as seen in de DEBUG section of this post.

I also tried to add the accounts array to the request. This results in an empty response: ""
And the rulegroup has not fired

### Debug information

Return from postman:

{
    "message": "Internal Firefly III Exception: FireflyIII\\Api\\V1\\Requests\\Models\\RuleGroup\\TriggerRequest::getAccounts(): Return value must be of type array, null returned",
    "exception": "TypeError"
}

Log output from FireFly:
```
[2024-02-02 10:40:47] local.ERROR: Exception is: {"class":"TypeError","errorMessage":"FireflyIII\\Api\\V1\\Requests\\Models\\RuleGroup\\TriggerRequest::getAccounts(): Return value must be of type array, null returned","time":"Fri, 02 Feb 2024 10:40:47 +0100","file":"\/var\/www\/html\/app\/Api\/V1\/Requests\/Models\/RuleGroup\/TriggerRequest.php","line":74,"code":0,"version":"6.1.7","url":"http:\/\/mydomain.nl\/api\/v1\/rule-groups\/3\/trigger","userAgent":"PostmanRuntime\/7.29.2","json":true,"method":"POST","post":"[]"}  
[2024-02-02 10:40:47] local.ERROR: FireflyIII\Api\V1\Requests\Models\RuleGroup\TriggerRequest::getAccounts(): Return value must be of type array, null returned {"userId":1,"exception":"[object] (TypeError(code: 0): FireflyIII\\Api\\V1\\Requests\\Models\\RuleGroup\\TriggerRequest::getAccounts(): Return value must be of type array, null returned at /var/www/html/app/Api/V1/Requests/Models/RuleGroup/TriggerRequest.php:74)
[stacktrace]
#0 /var/www/html/app/Api/V1/Requests/Models/RuleGroup/TriggerRequest.php(45): FireflyIII\\Api\\V1\\Requests\\Models\\RuleGroup\\TriggerRequest->getAccounts()
#1 /var/www/html/app/Api/V1/Controllers/Models/RuleGroup/TriggerController.php(134): FireflyIII\\Api\\V1\\Requests\\Models\\RuleGroup\\TriggerRequest->getTriggerParameters()
#2 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): FireflyIII\\Api\\V1\\Controllers\\Models\\RuleGroup\\TriggerController->triggerGroup()
#3 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(43): Illuminate\\Routing\\Controller->callAction()
#4 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Route.php(259): Illuminate\\Routing\\ControllerDispatcher->dispatch()
#5 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Route.php(205): Illuminate\\Routing\\Route->runController()
#6 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(806): Illuminate\\Routing\\Route->run()
#7 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(144): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}()
#8 /var/www/html/app/Api/V1/Controllers/Models/RuleGroup/TriggerController.php(61): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#9 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(165): FireflyIII\\Api\\V1\\Controllers\\Models\\RuleGroup\\TriggerController->FireflyIII\\Api\\V1\\Controllers\\Models\\RuleGroup\\{closure}()
#10 /var/www/html/app/Api/V1/Controllers/Controller.php(74): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#11 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(165): FireflyIII\\Api\\V1\\Controllers\\Controller->FireflyIII\\Api\\V1\\Controllers\\{closure}()
#12 /var/www/html/app/Http/Middleware/Binder.php(75): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#13 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): FireflyIII\\Http\\Middleware\\Binder->handle()
#14 /var/www/html/app/Http/Middleware/Authenticate.php(66): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#15 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): FireflyIII\\Http\\Middleware\\Authenticate->handle()
#16 /var/www/html/vendor/laravel/sanctum/src/Http/Middleware/EnsureFrontendRequestsAreStateful.php(25): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#17 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(144): Laravel\\Sanctum\\Http\\Middleware\\EnsureFrontendRequestsAreStateful->Laravel\\Sanctum\\Http\\Middleware\\{closure}()
#18 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(119): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#19 /var/www/html/vendor/laravel/sanctum/src/Http/Middleware/EnsureFrontendRequestsAreStateful.php(24): Illuminate\\Pipeline\\Pipeline->then()
#20 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Laravel\\Sanctum\\Http\\Middleware\\EnsureFrontendRequestsAreStateful->handle()
#21 /var/www/html/app/Http/Middleware/AcceptHeaders.php(72): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#22 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): FireflyIII\\Http\\Middleware\\AcceptHeaders->handle()
#23 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(119): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#24 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(805): Illuminate\\Pipeline\\Pipeline->then()
#25 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(784): Illuminate\\Routing\\Router->runRouteWithinStack()
#26 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(748): Illuminate\\Routing\\Router->runRoute()
#27 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(737): Illuminate\\Routing\\Router->dispatchToRoute()
#28 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(200): Illuminate\\Routing\\Router->dispatch()
#29 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(144): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}()
#30 /var/www/html/app/Http/Middleware/InstallationId.php(47): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#31 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): FireflyIII\\Http\\Middleware\\InstallationId->handle()
#32 /var/www/html/vendor/laravel/framework/src/Illuminate/Http/Middleware/TrustProxies.php(39): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#33 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Http\\Middleware\\TrustProxies->handle()
#34 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#35 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.php(31): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#36 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Foundation\\Http\\Middleware\\ConvertEmptyStringsToNull->handle()
#37 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#38 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php(40): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#39 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Foundation\\Http\\Middleware\\TrimStrings->handle()
#40 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#41 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle()
#42 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(99): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#43 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance->handle()
#44 /var/www/html/app/Http/Middleware/SecureHeaders.php(48): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#45 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): FireflyIII\\Http\\Middleware\\SecureHeaders->handle()
#46 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(119): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#47 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(175): Illuminate\\Pipeline\\Pipeline->then()
#48 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(144): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter()
#49 /var/www/html/public/index.php(73): Illuminate\\Foundation\\Http\\Kernel->handle()
#50 {main}
"} 
172.17.0.1 - - [02/Feb/2024:10:40:47 +0100] "POST /api/v1/rule-groups/3/trigger HTTP/1.1" 500 1157 "-" "PostmanRuntime/7.29.2"
```
### Expected behaviour

I would expect the rulegroup to fire.  (And if succesfull get an code 2xx in the response)
OR
That there would be an error code saying what is wrong.

### Steps to reproduce

1. In postman set the Request to POST: https://mydomain.nl/api/v1/rule-groups/3/trigger (3 is the id of the rulegroup I want to trigger)
2. set the headers:

- Content-Type: application/json
- Accept: */*

3. set the authorisation: Oauth2.0 with the required token
4. Test and see the output

**Comment by JC5** [comment]
Nice, I'll check it out!
