### ISSUE TITLE
Firefly new install keep on prompting cannot poll database errror

### ISSUE THREAD

**Issue by sathy1dev** [firefly-iii/firefly-iii#8568]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [ ] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [ ] ... there are no open or closed issues that are related to my problem
- [ ] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

![Screenshot 2024-02-21 114004](https://github.com/firefly-iii/firefly-iii/assets/41166030/341d5218-561b-43ef-91b4-d26c28bac3e2)

I have installed a clear install of firefly and the error is still coming. 
. I haven't changed anything. I copied the default compose file and env files

### Debug information

I also created a new server and freshly installed everything , still the issue is coming

**Comment by JC5** [comment]
#8546

**Comment by cabe1214** [comment]
Hi @JC5, I'm afraid I'm facing the same error but it seems not to be related to the importer.
Here the log where I see the problem seems to be between the app and the db.

```
app_1         |   [✓] Done waiting for the DB to boot.
app_1         |       DSN is mysql:host=db;port=3306;charset=utf8mb4
db_1          | 2024-02-21 13:18:11 4 [Warning] Aborted connection 4 to db: 'unconnected' user: 'unauthenticated' host: '172.21.0.4' (This connection closed normally without authentication)
app_1         |   [x]  Error when connecting to DB: SQLSTATE[HY000] [2054] Server sent charset (0) unknown to the client. Please, report to the developers
db_1          | 2024-02-21 13:18:11 5 [Warning] Aborted connection 5 to db: 'unconnected' user: 'unauthenticated' host: '172.21.0.4' (This connection closed normally without authentication)
app_1         | [2024-02-21 14:18:11] local.ERROR: Exception is: {"class":"Illuminate\\Database\\QueryException","errorMessage":"SQLSTATE[HY000] [2054] Server sent charset (0) unknown to the client. Please, report to the developers (Connection: mysql, SQL: select table_name as `name`, (data_length + index_length) as `size`, table_comment as `comment`, engine as `engine`, table_collation as `collation` from information_schema.tables where table_schema = 'firefly' and table_type in ('BASE TABLE', 'SYSTEM VERSIONED') order by table_name)","time":"Wed, 21 Feb 2024 14:18:11 +0100","file":"\/var\/www\/html\/vendor\/laravel\/framework\/src\/Illuminate\/Database\/Connection.php","line":829,"code":2054,"version":"6.1.9","url":"http:\/\/localhost","userAgent":"Symfony","json":true,"method":"GET","post":""}  
app_1         | [2024-02-21 14:18:11] local.ERROR: SQLSTATE[HY000] [2054] Server sent charset (0) unknown to the client. Please, report to the developers (Connection: mysql, SQL: select table_name as `name`, (data_length + index_length) as `size`, table_comment as `comment`, engine as `engine`, table_collation as `collation` from information_schema.tables where table_schema = 'firefly' and table_type in ('BASE TABLE', 'SYSTEM VERSIONED') order by table_name) {"exception":"[object] (Illuminate\\Database\\QueryException(code: 2054): SQLSTATE[HY000] [2054] Server sent charset (0) unknown to the client. Please, report to the developers (Connection: mysql, SQL: select table_name as `name`, (data_length + index_length) as `size`, table_comment as `comment`, engine as `engine`, table_collation as `collation` from information_schema.tables where table_schema = 'firefly' and table_type in ('BASE TABLE', 'SYSTEM VERSIONED') order by table_name) at /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php:829)
app_1         | [stacktrace]
app_1         | #0 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php(783): Illuminate\\Database\\Connection->runQueryCallback()
app_1         | #1 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php(414): Illuminate\\Database\\Connection->run()
app_1         | #2 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php(401): Illuminate\\Database\\Connection->select()
app_1         | #3 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Schema/MySqlBuilder.php(41): Illuminate\\Database\\Connection->selectFromWriteConnection()
app_1         | #4 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Schema/Builder.php(165): Illuminate\\Database\\Schema\\MySqlBuilder->getTables()
app_1         | #5 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Migrations/DatabaseMigrationRepository.php(184): Illuminate\\Database\\Schema\\Builder->hasTable()
app_1         | #6 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php(700): Illuminate\\Database\\Migrations\\DatabaseMigrationRepository->repositoryExists()
app_1         | #7 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Console/Migrations/MigrateCommand.php(140): Illuminate\\Database\\Migrations\\Migrator->repositoryExists()
app_1         | #8 /var/www/html/vendor/laravel/framework/src/Illuminate/Support/helpers.php(248): Illuminate\\Database\\Console\\Migrations\\MigrateCommand->Illuminate\\Database\\Console\\Migrations\\{closure}()
app_1         | #9 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Console/Migrations/MigrateCommand.php(140): retry()
app_1         | #10 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Console/Migrations/MigrateCommand.php(116): Illuminate\\Database\\Console\\Migrations\\MigrateCommand->repositoryExists()
app_1         | #11 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Console/Migrations/MigrateCommand.php(84): Illuminate\\Database\\Console\\Migrations\\MigrateCommand->prepareDatabase()
app_1         | #12 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php(633): Illuminate\\Database\\Console\\Migrations\\MigrateCommand->Illuminate\\Database\\Console\\Migrations\\{closure}()
app_1         | #13 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Console/Migrations/MigrateCommand.php(83): Illuminate\\Database\\Migrations\\Migrator->usingConnection()
app_1         | #14 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Illuminate\\Database\\Console\\Migrations\\MigrateCommand->handle()
app_1         | #15 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
app_1         | #16 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure()
app_1         | #17 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(35): Illuminate\\Container\\BoundMethod::callBoundMethod()
app_1         | #18 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(662): Illuminate\\Container\\BoundMethod::call()
app_1         | #19 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(211): Illuminate\\Container\\Container->call()
app_1         | #20 /var/www/html/vendor/symfony/console/Command/Command.php(326): Illuminate\\Console\\Command->execute()
app_1         | #21 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(180): Symfony\\Component\\Console\\Command\\Command->run()
app_1         | #22 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Concerns/CallsCommands.php(67): Illuminate\\Console\\Command->run()
app_1         | #23 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Concerns/CallsCommands.php(28): Illuminate\\Console\\Command->runCommand()
app_1         | #24 /var/www/html/app/Console/Commands/Upgrade/UpgradeDatabase.php(90): Illuminate\\Console\\Command->call()
app_1         | #25 /var/www/html/app/Console/Commands/Upgrade/UpgradeDatabase.php(46): FireflyIII\\Console\\Commands\\Upgrade\\UpgradeDatabase->callInitialCommands()
app_1         | #26 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): FireflyIII\\Console\\Commands\\Upgrade\\UpgradeDatabase->handle()
app_1         | #27 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
app_1         | #28 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure()
app_1         | #29 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(35): Illuminate\\Container\\BoundMethod::callBoundMethod()
app_1         | #30 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(662): Illuminate\\Container\\BoundMethod::call()
app_1         | #31 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(211): Illuminate\\Container\\Container->call()
app_1         | #32 /var/www/html/vendor/symfony/console/Command/Command.php(326): Illuminate\\Console\\Command->execute()
app_1         | #33 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(180): Symfony\\Component\\Console\\Command\\Command->run()
app_1         | #34 /var/www/html/vendor/symfony/console/Application.php(1096): Illuminate\\Console\\Command->run()
app_1         | #35 /var/www/html/vendor/symfony/console/Application.php(324): Symfony\\Component\\Console\\Application->doRunCommand()
app_1         | #36 /var/www/html/vendor/symfony/console/Application.php(175): Symfony\\Component\\Console\\Application->doRun()
app_1         | #37 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(201): Symfony\\Component\\Console\\Application->run()
app_1         | #38 /var/www/html/artisan(35): Illuminate\\Foundation\\Console\\Kernel->handle()
app_1         | #39 {main}
app_1         | 
app_1         | [previous exception] [object] (PDOException(code: 2054): SQLSTATE[HY000] [2054] Server sent charset (0) unknown to the client. Please, report to the developers at /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connectors/Connector.php:65)
app_1         | [stacktrace]
app_1         | #0 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connectors/Connector.php(65): PDO->__construct()
app_1         | #1 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connectors/Connector.php(44): Illuminate\\Database\\Connectors\\Connector->createPdoConnection()
app_1         | #2 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connectors/MySqlConnector.php(24): Illuminate\\Database\\Connectors\\Connector->createConnection()
app_1         | #3 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connectors/ConnectionFactory.php(184): Illuminate\\Database\\Connectors\\MySqlConnector->connect()
app_1         | #4 [internal function]: Illuminate\\Database\\Connectors\\ConnectionFactory->Illuminate\\Database\\Connectors\\{closure}()
app_1         | #5 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php(1339): call_user_func()
app_1         | #6 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php(528): Illuminate\\Database\\Connection->getPdo()
app_1         | #7 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php(423): Illuminate\\Database\\Connection->getPdoForSelect()
app_1         | #8 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php(816): Illuminate\\Database\\Connection->Illuminate\\Database\\{closure}()
app_1         | #9 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php(783): Illuminate\\Database\\Connection->runQueryCallback()
app_1         | #10 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php(414): Illuminate\\Database\\Connection->run()
app_1         | #11 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php(401): Illuminate\\Database\\Connection->select()
app_1         | #12 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Schema/MySqlBuilder.php(41): Illuminate\\Database\\Connection->selectFromWriteConnection()
app_1         | #13 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Schema/Builder.php(165): Illuminate\\Database\\Schema\\MySqlBuilder->getTables()
app_1         | #14 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Migrations/DatabaseMigrationRepository.php(184): Illuminate\\Database\\Schema\\Builder->hasTable()
app_1         | #15 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php(700): Illuminate\\Database\\Migrations\\DatabaseMigrationRepository->repositoryExists()
app_1         | #16 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Console/Migrations/MigrateCommand.php(140): Illuminate\\Database\\Migrations\\Migrator->repositoryExists()
app_1         | #17 /var/www/html/vendor/laravel/framework/src/Illuminate/Support/helpers.php(248): Illuminate\\Database\\Console\\Migrations\\MigrateCommand->Illuminate\\Database\\Console\\Migrations\\{closure}()
app_1         | #18 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Console/Migrations/MigrateCommand.php(140): retry()
app_1         | #19 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Console/Migrations/MigrateCommand.php(116): Illuminate\\Database\\Console\\Migrations\\MigrateCommand->repositoryExists()
app_1         | #20 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Console/Migrations/MigrateCommand.php(84): Illuminate\\Database\\Console\\Migrations\\MigrateCommand->prepareDatabase()
app_1         | #21 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php(633): Illuminate\\Database\\Console\\Migrations\\MigrateCommand->Illuminate\\Database\\Console\\Migrations\\{closure}()
app_1         | #22 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Console/Migrations/MigrateCommand.php(83): Illuminate\\Database\\Migrations\\Migrator->usingConnection()
app_1         | #23 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Illuminate\\Database\\Console\\Migrations\\MigrateCommand->handle()
app_1         | #24 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
app_1         | #25 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure()
app_1         | #26 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(35): Illuminate\\Container\\BoundMethod::callBoundMethod()
app_1         | #27 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(662): Illuminate\\Container\\BoundMethod::call()
app_1         | #28 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(211): Illuminate\\Container\\Container->call()
app_1         | #29 /var/www/html/vendor/symfony/console/Command/Command.php(326): Illuminate\\Console\\Command->execute()
app_1         | #30 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(180): Symfony\\Component\\Console\\Command\\Command->run()
app_1         | #31 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Concerns/CallsCommands.php(67): Illuminate\\Console\\Command->run()
app_1         | #32 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Concerns/CallsCommands.php(28): Illuminate\\Console\\Command->runCommand()
app_1         | #33 /var/www/html/app/Console/Commands/Upgrade/UpgradeDatabase.php(90): Illuminate\\Console\\Command->call()
app_1         | #34 /var/www/html/app/Console/Commands/Upgrade/UpgradeDatabase.php(46): FireflyIII\\Console\\Commands\\Upgrade\\UpgradeDatabase->callInitialCommands()
app_1         | #35 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): FireflyIII\\Console\\Commands\\Upgrade\\UpgradeDatabase->handle()
app_1         | #36 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
app_1         | #37 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure()
app_1         | #38 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(35): Illuminate\\Container\\BoundMethod::callBoundMethod()
app_1         | #39 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(662): Illuminate\\Container\\BoundMethod::call()
app_1         | #40 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(211): Illuminate\\Container\\Container->call()
app_1         | #41 /var/www/html/vendor/symfony/console/Command/Command.php(326): Illuminate\\Console\\Command->execute()
app_1         | #42 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(180): Symfony\\Component\\Console\\Command\\Command->run()
app_1         | #43 /var/www/html/vendor/symfony/console/Application.php(1096): Illuminate\\Console\\Command->run()
app_1         | #44 /var/www/html/vendor/symfony/console/Application.php(324): Symfony\\Component\\Console\\Application->doRunCommand()
app_1         | #45 /var/www/html/vendor/symfony/console/Application.php(175): Symfony\\Component\\Console\\Application->doRun()
app_1         | #46 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(201): Symfony\\Component\\Console\\Application->run()
app_1         | #47 /var/www/html/artisan(35): Illuminate\\Foundation\\Console\\Kernel->handle()
app_1         | #48 {main}
app_1         | "} 
app_1         | 
app_1         |    Illuminate\Database\QueryException 
app_1         | 
app_1         |   SQLSTATE[HY000] [2054] Server sent charset (0) unknown to the client. Please, report to the developers (Connection: mysql, SQL: select table_name as `name`, (data_length + index_length) as `size`, table_comment as `comment`, engine as `engine`, table_collation as `collation` from information_schema.tables where table_schema = 'firefly' and table_type in ('BASE TABLE', 'SYSTEM VERSIONED') order by table_name)
app_1         | 
app_1         |   at vendor/laravel/framework/src/Illuminate/Database/Connection.php:829
app_1         |     825▕                     $this->getName(), $query, $this->prepareBindings($bindings), $e
app_1         |     826▕                 );
app_1         |     827▕             }
app_1         |     828▕ 
app_1         |   ➜ 829▕             throw new QueryException(
app_1         |     830▕                 $this->getName(), $query, $this->prepareBindings($bindings), $e
app_1         |     831▕             );
app_1         |     832▕         }
app_1         |     833▕     }
app_1         | 
app_1         |       +34 vendor frames 
app_1         | 
app_1         |   35  app/Console/Commands/Upgrade/UpgradeDatabase.php:90
app_1         |       Illuminate\Console\Command::call()
app_1         | 
app_1         |   36  app/Console/Commands/Upgrade/UpgradeDatabase.php:46
app_1         |       FireflyIII\Console\Commands\Upgrade\UpgradeDatabase::callInitialCommands()
app_1         | 
```

I had set the variables in the .fidi.env file as per the documentation so this may be something else.

**Comment by JC5** [comment]
Sorry, I linked to the wrong issue. You need #8564

**Comment by cabe1214** [comment]
For the next one coming, I added the mariadb version "**:11.2**" as suggested in  #8564 and it worked.

image: mariadb:11.2

**Comment by academo** [comment]
I just had exactly this same issue. I'd be nice if the docker compose has the correct image version it works :)

**Comment by JC5** [comment]
Good idea, just fixed it.

**Comment by academo** [comment]
@JC5 you rock! thanks so much for such a fast fix <3
