### ISSUE TITLE
Importing camt.053 file fails during conversion step 

### ISSUE THREAD

**Issue by laeckerv** [firefly-iii/firefly-iii#8574]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

When im trying to import a camt.053 file the importer stops during the conversion. If needed I can try to get a minimal anonymized example of the xml file...

### Debug information

Debug information generated at 2024-02-22 22:02:46 Europe/Zurich for Firefly III Data Importer version **1.4.4**.

<table><tr><th colspan="2">System information</th></tr><tr><th>Item</th><th>Value</th></tr><tr><td>Version</td><td>1.4.4</td></tr><tr><td>Build</td><td><span>#</span>, base <span>#</span>80</td></tr><tr><td>System</td><td>PHP 8.3.3, Linux, apache2handler</td></tr></table><table><tr><th colspan="2">App information</th></tr><tr><th>Item</th><th>Value</th></tr><tr><td>Timezone</td><td>Europe/Zurich, Europe/Zurich</td></tr><tr><td>Environment</td><td>local</td></tr><tr><td>Debug mode</td><td>true, cache 'file'</td></tr><tr><td>Log level</td><td>debug, stack</td></tr><tr><td>Display errors</td><td>Off, ALL errors</td></tr><tr><td>BCscale</td><td>12</td></tr><tr><td>Trusted proxies</td><td>**</td></tr></table><table><tr><th colspan="2">User information</th></tr><tr><th>Item</th><th>Value</th></tr><tr><td>User agent</td><td>Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:122.0) Gecko/20100101 Firefox/122.0</td></tr></table>

### Expected behaviour

The conversion shouldn't fail.

### Steps to reproduce

1. import the camt.053 file

### Additional info

```
Truncated from this point <----|) must be of type string, null given at /var/www/html/app/Services/Camt/Conversion/TransactionMapper.php:595)
[stacktrace]
#0 /var/www/html/app/Services/Camt/Conversion/TransactionMapper.php(595): bccomp()
#1 /var/www/html/app/Services/Camt/Conversion/TransactionMapper.php(349): App\\Services\\Camt\\Conversion\\TransactionMapper->sanityCheck()
#2 /var/www/html/app/Services/Camt/Conversion/TransactionMapper.php(45): App\\Services\\Camt\\Conversion\\TransactionMapper->mapTransactionGroup()
#3 /var/www/html/app/Services/Camt/Conversion/RoutineManager.php(117): App\\Services\\Camt\\Conversion\\TransactionMapper->map()
#4 /var/www/html/app/Http/Controllers/Import/ConversionController.php(183): App\\Services\\Camt\\Conversion\\RoutineManager->start()
#5 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): App\\Http\\Controllers\\Import\\ConversionController->start()
#6 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(43): Illuminate\\Routing\\Controller->callAction()
#7 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Route.php(259): Illuminate\\Routing\\ControllerDispatcher->dispatch()
#8 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Route.php(205): Illuminate\\Routing\\Route->runController()
#9 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(806): Illuminate\\Routing\\Route->run()
#10 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(144): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}()
#11 /var/www/html/app/Http/Middleware/IsReadyForStep.php(44): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#12 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): App\\Http\\Middleware\\ConversionControllerMiddleware->handle()
#13 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(50): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#14 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle()
#15 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(78): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#16 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle()
#17 /var/www/html/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#18 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle()
#19 /var/www/html/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(121): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#20 /var/www/html/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(64): Illuminate\\Session\\Middleware\\StartSession->handleStatefulRequest()
#21 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Session\\Middleware\\StartSession->handle()
#22 /var/www/html/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#23 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle()
#24 /var/www/html/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(67): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#25 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle()
#26 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(119): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#27 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(805): Illuminate\\Pipeline\\Pipeline->then()
#28 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(784): Illuminate\\Routing\\Router->runRouteWithinStack()
#29 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(748): Illuminate\\Routing\\Router->runRoute()
#30 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(737): Illuminate\\Routing\\Router->dispatchToRoute()
#31 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(200): Illuminate\\Routing\\Router->dispatch()
#32 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(144): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}()
#33 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#34 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.php(31): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#35 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Foundation\\Http\\Middleware\\ConvertEmptyStringsToNull->handle()
#36 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#37 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php(40): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#38 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Foundation\\Http\\Middleware\\TrimStrings->handle()
#39 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#40 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle()
#41 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(99): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#42 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance->handle()
#43 /var/www/html/vendor/laravel/framework/src/Illuminate/Http/Middleware/HandleCors.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#44 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Http\\Middleware\\HandleCors->handle()
#45 /var/www/html/vendor/laravel/framework/src/Illuminate/Http/Middleware/TrustProxies.php(39): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#46 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Http\\Middleware\\TrustProxies->handle()
#47 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(119): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#48 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(175): Illuminate\\Pipeline\\Pipeline->then()
#49 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(144): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter()
#50 /var/www/html/public/index.php(76): Illuminate\\Foundation\\Http\\Kernel->handle()
#51 {main}
"} 
[2024-02-22 22:02:37] local.DEBUG: isReadyForFileStep("conversion")  
[2024-02-22 22:02:37] local.DEBUG: isReadyForFileStep: Return true  
[2024-02-22 22:02:37] local.DEBUG: Now at App\Http\Controllers\Import\ConversionController::status(conversion-cgFL4DOAYywv)  
[2024-02-22 22:02:37] local.DEBUG: Now in startOrFindConversion(conversion-cgFL4DOAYywv)  
[2024-02-22 22:02:37] local.DEBUG: Conversion status is "conv_running"  

```

**Comment by laeckerv** [comment]
Here is a minimal example that fails for me on `:develop`. 

```
<?xml version="1.0" encoding="UTF-8"?>
<Document
    xmlns="urn:iso:std:iso:20022:tech:xsd:camt.053.001.04"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <BkToCstmrStmt>
        <GrpHdr>
            <MsgId>M/3322163396/CAM</MsgId>
            <CreDtTm>2024-02-22T19:36:31+01:00</CreDtTm>
            <MsgPgntn>
                <PgNb>1</PgNb>
                <LastPgInd>true</LastPgInd>
            </MsgPgntn>
            <AddtlInf>Prod</AddtlInf>
        </GrpHdr>
        <Stmt>
            <Id>M/3322163396/CAM</Id>
            <ElctrncSeqNb>2</ElctrncSeqNb>
            <CreDtTm>2024-02-22T17:27:50+01:00</CreDtTm>
            <FrToDt>
                <FrDtTm>2001-01-01T00:00:00+01:00</FrDtTm>
                <ToDtTm>2024-01-31T00:00:00+01:00</ToDtTm>
            </FrToDt>
            <Acct>
                <Id>
                    <IBAN>CH5604835012345678009</IBAN>
                </Id>
                <Ccy>CHF</Ccy>
                <Ownr>
                    <Nm>Lastname Firstname</Nm>
                </Ownr>
            </Acct>
            <Bal>
                <Tp>
                    <CdOrPrtry>
                        <Cd>OPBD</Cd>
                    </CdOrPrtry>
                </Tp>
                <Amt Ccy="CHF">0.00</Amt>
                <CdtDbtInd>CRDT</CdtDbtInd>
                <Dt>
                    <Dt>2001-01-01</Dt>
                </Dt>
            </Bal>
            <Bal>
                <Tp>
                    <CdOrPrtry>
                        <Cd>CLBD</Cd>
                    </CdOrPrtry>
                </Tp>
                <Amt Ccy="CHF">6858.13</Amt>
                <CdtDbtInd>CRDT</CdtDbtInd>
                <Dt>
                    <Dt>2024-01-31</Dt>
                </Dt>
            </Bal>
            <Bal>
                <Tp>
                    <CdOrPrtry>
                        <Cd>CLAV</Cd>
                    </CdOrPrtry>
                </Tp>
                <Amt Ccy="CHF">6858.13</Amt>
                <CdtDbtInd>CRDT</CdtDbtInd>
                <Dt>
                    <Dt>2024-01-31</Dt>
                </Dt>
            </Bal>
            <TxsSummry>
                <TtlNtries>
                    <NbOfNtries>57</NbOfNtries>
                    <Sum>376395.25</Sum>
                    <TtlNetNtry>
                        <Amt>6858.13</Amt>
                        <CdtDbtInd>CRDT</CdtDbtInd>
                    </TtlNetNtry>
                </TtlNtries>
                <TtlCdtNtries>
                    <NbOfNtries>38</NbOfNtries>
                    <Sum>191626.69</Sum>
                </TtlCdtNtries>
                <TtlDbtNtries>
                    <NbOfNtries>19</NbOfNtries>
                    <Sum>184768.56</Sum>
                </TtlDbtNtries>
            </TxsSummry>
            <Ntry>
                <NtryRef>1883128456</NtryRef>
                <Amt Ccy="CHF">0.00</Amt>
                <CdtDbtInd>CRDT</CdtDbtInd>
                <Sts>BOOK</Sts>
                <BookgDt>
                    <Dt>2021-12-01</Dt>
                </BookgDt>
                <ValDt>
                    <Dt>2021-12-01</Dt>
                </ValDt>
                <AcctSvcrRef>O/1883128456</AcctSvcrRef>
                <BkTxCd>
                    <Domn>
                        <Cd>PMNT</Cd>
                        <Fmly>
                            <Cd>NTAV</Cd>
                            <SubFmlyCd>NTAV</SubFmlyCd>
                        </Fmly>
                    </Domn>
                </BkTxCd>
                <NtryDtls>
                    <TxDtls>
                        <Amt Ccy="CHF">0.00</Amt>
                        <CdtDbtInd>CRDT</CdtDbtInd>
                    </TxDtls>
                </NtryDtls>
                <AddtlNtryInf>Technische Buchung Auftragsnummer: 1883128456, 01.12.21
</AddtlNtryInf>
            </Ntry>
        </Stmt>
    </BkToCstmrStmt>
</Document>
```

**Comment by JC5** [comment]
Nice find, thanks for letting me know. I can fix this, but it means this transaction will be skipped, since it has no amount information. Transactions with no amount will not be stored by Firefly III.

**Comment by laeckerv** [comment]
Wow. Thanks for that fast response. Just tested it with `:develop` and the minimal example from above.  Seems like something slipped through. Let me know if you need more information.

``` 
[2024-02-23 09:48:56] local.ERROR: bccomp(): Argument #1 ($num1) must be of type string, null given {"exception":"[object] (TypeError(code: 0): bccomp(): Argument #1 ($num1) must be of type string, null given at /var/www/html/app/Services/Camt/Conversion/TransactionMapper.php:595)
```

**Comment by JC5** [comment]
Not a problem! Thanks for the reminder new develop tag should be up and running.

**Comment by laeckerv** [comment]
Works like a charm. Thank you!
