### ISSUE TITLE
Firefly III v6.1.9 ran into an error: bcsub(): Argument #2 ($num2) is not well-formed.

### ISSUE THREAD

**Issue by DocCyblade** [firefly-iii/firefly-iii#8623]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

During reconciling got email alert 25+ times. 

Firefly III v6.1.9 ran into an error: bcsub(): Argument #2 ($num2) is not well-formed.

The error was of type "ValueError".

The error occurred on/at: Mon, 04 Mar 2024 11:04:02 -0500.

This error occurred in file "/srv/webroot/prod-firefly-iii/app/Http/Controllers/Json/ReconcileController.php" on line 121 with code 0.

### Debug information

Debug information generated at 2024-03-04 15:07:27 for Firefly III version **v6.1.9**.

<table><thead><tr><th colspan="2">System information</th></tr><tr><th>Item</th><th>Value</th></tr></thead><tbody><tr><td>Firefly III</td><td>6.1.9 / v2.0.12 / 22 (exp. 22)</td></tr><tr><td>PHP version</td><td>8.3.3-1+0~20240216.17+debian12~1.gbp87e37b / apache2handler / Linux</td></tr><tr><td>BCscale</td><td>12</td></tr><tr><td>Error reporting</td><td>Display: Off, reporting: ALL errors</td></tr><tr><td>Max upload</td><td>2097152 (2 MB)</td></tr><tr><td>Database drivers</td><td><strong>*pgsql*</strong>, </td></tr></tbody></table><table><thead><tr><th colspan="2">Firefly III information</th></tr><tr><th>Item</th><th>Value</th></tr></thead><tbody><tr><td>Timezone</td><td>America/New_York + America/New_York</td></tr><tr><td>App environment</td><td>local, debug: false</td></tr><tr><td>Layout</td><td>v1</td></tr><tr><td>Logging</td><td>info, stack / (empty)</td></tr><tr><td>Cache driver</td><td>file</td></tr><tr><td>Default language and locale</td><td>en_US + equal</td></tr><tr><td>Trusted proxies</td><td></td></tr><tr><td>Login provider & user guard</td><td>eloquent / web</td></tr><tr><td>Login headers</td><td>N/A + N/A</td></tr><tr><td>Stateful domains</td><td></td></tr><tr><td>Last cron job</td><td>2024-03-04 12:07:01 (3 hours ago)</td></tr><tr><td>Mailer</td><td>smtp</td></tr></tbody></table><table><thead><tr><th colspan="2">User-specific information</th></tr><tr><th>Item</th><th>Value</th></tr></thead><tbody><tr><td>User</td><td><span>#</span>1 of 5</td></tr><tr><td>User flags</td><td></td></tr><tr><td>Session start</td><td>2024-03-01 00:00:00</td></tr><tr><td>Session end</td><td>2024-03-31 23:59:59</td></tr><tr><td>View range</td><td>1M</td></tr><tr><td>User language</td><td>en_US</td></tr><tr><td>User locale</td><td>en_US</td></tr><tr><td>Locale(s) supported</td><td>en_US.utf8: :white_check_mark:<br>en_US.UTF-8: :white_check_mark:<br></td></tr><tr><td>User agent</td><td>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.3.1 Safari/605.1.15</td></tr></tbody></table>

### Expected behaviour

Should be able to change the date and click reconcile. 

### Steps to reproduce

My wife did selected an account, started the reconcile processes then:

1. Selected transactions she wanted
2. Noticed that could not select transactions on the last day of the month (Maybe a diff issue?)
3. Changed the end date to 1st of the following month
4. Changed the ending balance to match the actual ending for the month
5. Clicked Store 

She got no prompt or error would not store

### Additional info

All Info from the email
```
Firefly III v6.1.9 ran into an error: bcsub(): Argument #2 ($num2) is not well-formed.

The error was of type "ValueError".

The error occurred on/at: Mon, 04 Mar 2024 11:04:02 -0500.

This error occurred in file "/srv/webroot/prod-firefly-iii/app/Http/Controllers/Json/ReconcileController.php" on line 121 with code 0.

The error was encountered by user #2, [redacted](mailto:robinson.family@homepost.org).

The IP address related to this error is: redacted ([info](https://ipinfo.io/redacted/json?token=))
GET URL is: https://redacted/accounts/reconcile/18/overview/2024-02-01/2024-03-01?endBalance=NaN&journals%5B0%5D=7164&journals%5B1%5D=7152&journals%5B2%5D=7144&journals%5B3%5D=7143&journals%5B4%5D=7142&journals%5B5%5D=7141&journals%5B6%5D=7140&journals%5B7%5D=7139&journals%5B8%5D=7138&journals%5B9%5D=7137&journals%5B10%5D=7125&journals%5B11%5D=7136&journals%5B12%5D=7134&journals%5B13%5D=7133&journals%5B14%5D=7132&journals%5B15%5D=7131&journals%5B16%5D=7130&journals%5B17%5D=7129&journals%5B18%5D=7128&journals%5B19%5D=7117&journals%5B20%5D=7116&journals%5B21%5D=7115&journals%5B22%5D=7114&journals%5B23%5D=7106&journals%5B24%5D=7113&journals%5B25%5D=7112&journals%5B26%5D=7111&journals%5B27%5D=7110&journals%5B28%5D=7109&journals%5B29%5D=7108&journals%5B30%5D=7098&journals%5B31%5D=7101&journals%5B32%5D=7100&journals%5B33%5D=7099&journals%5B34%5D=7085&journals%5B35%5D=7090&journals%5B36%5D=7084&journals%5B37%5D=7089&journals%5B38%5D=7088&journals%5B39%5D=7087&journals%5B40%5D=7086&journals%5B41%5D=7080&journals%5B42%5D=7079&journals%5B43%5D=7078&journals%5B44%5D=7077&journals%5B45%5D=7076&journals%5B46%5D=7075&journals%5B47%5D=7070&journals%5B48%5D=7056&journals%5B49%5D=7055&journals%5B50%5D=7053&journals%5B51%5D=6969&startBalance=-5478.5&startDate=2024-02-01&startEnd=2024-03-01

The full stacktrace is below:

#0 /srv/webroot/prod-firefly-iii/app/Http/Controllers/Json/ReconcileController.php(121): bcsub()
#1 /srv/webroot/prod-firefly-iii/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): FireflyIII\Http\Controllers\Json\ReconcileController->overview()
#2 /srv/webroot/prod-firefly-iii/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(43): Illuminate\Routing\Controller->callAction()
#3 /srv/webroot/prod-firefly-iii/vendor/laravel/framework/src/Illuminate/Routing/Route.php(259): Illuminate\Routing\ControllerDispatcher->dispatch()
#4 /srv/webroot/prod-firefly-iii/vendor/laravel/framework/src/Illuminate/Routing/Route.php(205): Illuminate\Routing\Route->runController()
#5 /srv/webroot/prod-firefly-iii/vendor/laravel/framework/src/Illuminate/Routing/Router.php(806): Illuminate\Routing\Route->run()
#6 /srv/webroot/prod-firefly-iii/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(144): Illuminate\Routing\Router->Illuminate\Routing\{closure}()
#7 /srv/webroot/prod-firefly-iii/app/Http/Controllers/Json/ReconcileController.php(59): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#8 /srv/webroot/prod-firefly-iii/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(165): FireflyIII\Http\Controllers\Json\ReconcileController->FireflyIII\Http\Controllers\Json\{closure}()
#9 /srv/webroot/prod-firefly-iii/app/Http/Controllers/Controller.php(118): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#10 /srv/webroot/prod-firefly-iii/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(165): FireflyIII\Http\Controllers\Controller->FireflyIII\Http\Controllers\{closure}()
#11 /srv/webroot/prod-firefly-iii/app/Http/Middleware/InterestingMessage.php(71): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#12 /srv/webroot/prod-firefly-iii/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): FireflyIII\Http\Middleware\InterestingMessage->handle()
#13 /srv/webroot/prod-firefly-iii/app/Http/Middleware/Binder.php(75): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#14 /srv/webroot/prod-firefly-iii/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): FireflyIII\Http\Middleware\Binder->handle()
#15 /srv/webroot/prod-firefly-iii/app/Http/Middleware/Range.php(56): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#16 /srv/webroot/prod-firefly-iii/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): FireflyIII\Http\Middleware\Range->handle()
#17 /srv/webroot/prod-firefly-iii/vendor/jc5/google2fa-laravel/src/Middleware.php(29): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#18 /srv/webroot/prod-firefly-iii/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): PragmaRX\Google2FALaravel\Middleware->handle()
#19 /srv/webroot/prod-firefly-iii/app/Http/Middleware/Authenticate.php(66): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#20 /srv/webroot/prod-firefly-iii/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): FireflyIII\Http\Middleware\Authenticate->handle()
#21 /srv/webroot/prod-firefly-iii/vendor/laravel/passport/src/Http/Middleware/CreateFreshApiToken.php(63): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#22 /srv/webroot/prod-firefly-iii/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Laravel\Passport\Http\Middleware\CreateFreshApiToken->handle()
#23 /srv/webroot/prod-firefly-iii/vendor/laravel/framework/src/Illuminate/Session/Middleware/AuthenticateSession.php(60): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#24 /srv/webroot/prod-firefly-iii/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\Session\Middleware\AuthenticateSession->handle()
#25 /srv/webroot/prod-firefly-iii/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(78): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#26 /srv/webroot/prod-firefly-iii/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\Foundation\Http\Middleware\VerifyCsrfToken->handle()
#27 /srv/webroot/prod-firefly-iii/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#28 /srv/webroot/prod-firefly-iii/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\View\Middleware\ShareErrorsFromSession->handle()
#29 /srv/webroot/prod-firefly-iii/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(121): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#30 /srv/webroot/prod-firefly-iii/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(64): Illuminate\Session\Middleware\StartSession->handleStatefulRequest()
#31 /srv/webroot/prod-firefly-iii/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\Session\Middleware\StartSession->handle()
#32 /srv/webroot/prod-firefly-iii/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#33 /srv/webroot/prod-firefly-iii/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle()
#34 /srv/webroot/prod-firefly-iii/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(67): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#35 /srv/webroot/prod-firefly-iii/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\Cookie\Middleware\EncryptCookies->handle()
#36 /srv/webroot/prod-firefly-iii/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(119): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#37 /srv/webroot/prod-firefly-iii/vendor/laravel/framework/src/Illuminate/Routing/Router.php(805): Illuminate\Pipeline\Pipeline->then()
#38 /srv/webroot/prod-firefly-iii/vendor/laravel/framework/src/Illuminate/Routing/Router.php(784): Illuminate\Routing\Router->runRouteWithinStack()
#39 /srv/webroot/prod-firefly-iii/vendor/laravel/framework/src/Illuminate/Routing/Router.php(748): Illuminate\Routing\Router->runRoute()
#40 /srv/webroot/prod-firefly-iii/vendor/laravel/framework/src/Illuminate/Routing/Router.php(737): Illuminate\Routing\Router->dispatchToRoute()
#41 /srv/webroot/prod-firefly-iii/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(200): Illuminate\Routing\Router->dispatch()
#42 /srv/webroot/prod-firefly-iii/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(144): Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}()
#43 /srv/webroot/prod-firefly-iii/app/Http/Middleware/InstallationId.php(47): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#44 /srv/webroot/prod-firefly-iii/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): FireflyIII\Http\Middleware\InstallationId->handle()
#45 /srv/webroot/prod-firefly-iii/vendor/laravel/framework/src/Illuminate/Http/Middleware/TrustProxies.php(39): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#46 /srv/webroot/prod-firefly-iii/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\Http\Middleware\TrustProxies->handle()
#47 /srv/webroot/prod-firefly-iii/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#48 /srv/webroot/prod-firefly-iii/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.php(31): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle()
#49 /srv/webroot/prod-firefly-iii/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\Foundation\Http\Middleware\ConvertEmptyStringsToNull->handle()
#50 /srv/webroot/prod-firefly-iii/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#51 /srv/webroot/prod-firefly-iii/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php(40): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle()
#52 /srv/webroot/prod-firefly-iii/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\Foundation\Http\Middleware\TrimStrings->handle()
#53 /srv/webroot/prod-firefly-iii/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#54 /srv/webroot/prod-firefly-iii/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\Foundation\Http\Middleware\ValidatePostSize->handle()
#55 /srv/webroot/prod-firefly-iii/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(99): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#56 /srv/webroot/prod-firefly-iii/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\Foundation\Http\Middleware\PreventRequestsDuringMaintenance->handle()
#57 /srv/webroot/prod-firefly-iii/app/Http/Middleware/SecureHeaders.php(48): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#58 /srv/webroot/prod-firefly-iii/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): FireflyIII\Http\Middleware\SecureHeaders->handle()
#59 /srv/webroot/prod-firefly-iii/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(119): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#60 /srv/webroot/prod-firefly-iii/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(175): Illuminate\Pipeline\Pipeline->then()
#61 /srv/webroot/prod-firefly-iii/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(144): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter()
#62 /srv/webroot/prod-firefly-iii/public/index.php(73): Illuminate\Foundation\Http\Kernel->handle()
#63 {main}

The following headers may also be relevant:

- host: [redacted](http://redacted)
- user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:123.0) Gecko/20100101 Firefox/123.0
- accept: application/json, text/javascript, */*; q=0.01
- accept-language: en-US,en;q=0.5
- accept-encoding: gzip, deflate, br
- x-csrf-token: gOqsTJVLVVKok5A1n4duhhBWWm2agucPVLBgM1vw
- x-requested-with: XMLHttpRequest
- connection: keep-alive
- sec-fetch-dest: empty
- sec-fetch-mode: cors
- sec-fetch-site: same-origin
```

**Comment by DocCyblade** [comment]
Per email conversation I will adding the following in file `/srv/webroot/prod-firefly-iii/app/Http/Controllers/Json/ReconcileController.php.` Will test and get logs posted.

Just above "$difference" on line 121:

        Log::debug(sprintf('Start balance: "%s"', $startBalance));
        Log::debug(sprintf('End balance: "%s"', $endBalance));
        Log::debug(sprintf('Cleared amount: "%s"', $clearedAmount));
        Log::debug(sprintf('Amount: "%s"', $amount));

**Comment by DocCyblade** [comment]
Update, my wife already reconciled the accounts, however I am setting up a test to try and recreate the issue. I have added the debug statements to the controller. See if it happens again. If it does I will post the logs
