### ISSUE TITLE
Base table or view already exists: oauth_auth_codes

### ISSUE THREAD

**Issue by Tealk** [firefly-iii/firefly-iii#8688]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

Automatic error message

### Debug information

Hallo,

Firefly III v6.1.11 ist auf einen Fehler gestoßen: 
```
SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'oauth_auth_codes' already exists (Connection: mysql, SQL: create table `oauth_auth_codes` (`id` varchar(100) not null, `user_id` bigint unsigned not null, `client_id` bigint unsigned not null, `scopes` text null, `revoked` tinyint(1) not null, `expires_at` datetime null, primary key (`id`)) default character set utf8mb4 collate 'utf8mb4_unicode_ci' engine = InnoDB).
```

Der Fehler war vom Typ "Illuminate\Database\QueryException".

Der Fehler trat auf: Tue, 19 Mar 2024 19:22:17 +0100.

Dieser Fehler ist in der Datei "/var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php" in Zeile 813 mit dem Code 42S01 aufgetreten.

Es war kein Benutzer für diesen Fehler eingeloggt oder es wurde kein Benutzer erkannt.

Die IP-Adresse bezogen auf diesen Fehler lautet: 127.0.0.1 ([info](https://ipinfo.io/127.0.0.1/json?token=))
GET URL ist: http://localhost

Der vollständige Stacktrace ist unten. Wenn Sie denken, dass dies ein Fehler in Firefly III ist, können Sie diese Nachricht an [james@firefly-iii weiterleiten. rg](mailto:james@firefly-iii.org?subject=BUG!). Dies kann helfen, den Fehler zu beheben, den Sie gerade gefunden haben.

Wenn Sie es bevorzugen, können Sie auch einen Fehlerbericht auf [GitHub](https://github.com/firefly-iii/firefly-iii/issues) eröffnen.

Der vollständige Stacktrace ist unten:

```
#0 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php(767): Illuminate\Database\Connection->runQueryCallback()
#1 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php(560): Illuminate\Database\Connection->run()
#2 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Schema/Blueprint.php(109): Illuminate\Database\Connection->statement()
#3 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Schema/Builder.php(564): Illuminate\Database\Schema\Blueprint->build()
#4 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Schema/Builder.php(418): Illuminate\Database\Schema\Builder->build()
#5 /var/www/html/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(357): Illuminate\Database\Schema\Builder->create()
#6 /var/www/html/database/migrations/2016_06_01_000001_create_oauth_auth_codes_table.php(14): Illuminate\Support\Facades\Facade::__callStatic()
#7 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php(482): Illuminate\Database\Migrations\Migration@anonymous->up()
#8 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php(408): Illuminate\Database\Migrations\Migrator->runMethod()
#9 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php(417): Illuminate\Database\Migrations\Migrator->Illuminate\Database\Migrations\{closure}()
#10 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php(214): Illuminate\Database\Migrations\Migrator->runMigration()
#11 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/View/Components/Task.php(40): Illuminate\Database\Migrations\Migrator->Illuminate\Database\Migrations\{closure}()
#12 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php(745): Illuminate\Console\View\Components\Task->render()
#13 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php(214): Illuminate\Database\Migrations\Migrator->write()
#14 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php(179): Illuminate\Database\Migrations\Migrator->runUp()
#15 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php(122): Illuminate\Database\Migrations\Migrator->runPending()
#16 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Console/Migrations/MigrateCommand.php(113): Illuminate\Database\Migrations\Migrator->run()
#17 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php(622): Illuminate\Database\Console\Migrations\MigrateCommand->Illuminate\Database\Console\Migrations\{closure}()
#18 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Console/Migrations/MigrateCommand.php(106): Illuminate\Database\Migrations\Migrator->usingConnection()
#19 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Console/Migrations/MigrateCommand.php(85): Illuminate\Database\Console\Migrations\MigrateCommand->runMigrations()
#20 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Illuminate\Database\Console\Migrations\MigrateCommand->handle()
#21 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#22 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\Container\Util::unwrapIfClosure()
#23 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(35): Illuminate\Container\BoundMethod::callBoundMethod()
#24 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(662): Illuminate\Container\BoundMethod::call()
#25 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(212): Illuminate\Container\Container->call()
#26 /var/www/html/vendor/symfony/console/Command/Command.php(279): Illuminate\Console\Command->execute()
#27 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(181): Symfony\Component\Console\Command\Command->run()
#28 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Concerns/CallsCommands.php(67): Illuminate\Console\Command->run()
#29 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Concerns/CallsCommands.php(28): Illuminate\Console\Command->runCommand()
#30 /var/www/html/app/Console/Commands/Upgrade/UpgradeDatabase.php(91): Illuminate\Console\Command->call()
#31 /var/www/html/app/Console/Commands/Upgrade/UpgradeDatabase.php(46): FireflyIII\Console\Commands\Upgrade\UpgradeDatabase->callInitialCommands()
#32 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): FireflyIII\Console\Commands\Upgrade\UpgradeDatabase->handle()
#33 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#34 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\Container\Util::unwrapIfClosure()
#35 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(35): Illuminate\Container\BoundMethod::callBoundMethod()
#36 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(662): Illuminate\Container\BoundMethod::call()
#37 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(212): Illuminate\Container\Container->call()
#38 /var/www/html/vendor/symfony/console/Command/Command.php(279): Illuminate\Console\Command->execute()
#39 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(181): Symfony\Component\Console\Command\Command->run()
#40 /var/www/html/vendor/symfony/console/Application.php(1049): Illuminate\Console\Command->run()
#41 /var/www/html/vendor/symfony/console/Application.php(318): Symfony\Component\Console\Application->doRunCommand()
#42 /var/www/html/vendor/symfony/console/Application.php(169): Symfony\Component\Console\Application->doRun()
#43 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(196): Symfony\Component\Console\Application->run()
#44 /var/www/html/artisan(35): Illuminate\Foundation\Console\Kernel->handle()
#45 {main}
```

Die folgenden Kopfzeilen können ebenfalls von Bedeutung sein:

- host: localhost
- user-agent: Symfony
- accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
- accept-language: en-us,en;q=0.5
- accept-charset: ISO-8859-1,utf-8;q=0.7,*;q=0.7

Piep piep,

Der Firefly III E-Mail-Roboter

### Steps to reproduce

Update dcoker compose container from v6.1.10 to v6.1.11 and cativate v2 theme

**Comment by JC5** [comment]
Could you share your docker-compose file? I can't replicate this.

**Comment by JC5** [comment]
Could you try pulling the image again? I expect it to work as expected then :)

**Comment by Tealk** [comment]
I have pulled the image again, but have not received any further mail.

**Comment by JC5** [comment]
That sounds like it's fixed then, thanks!
