### ISSUE TITLE
Error importing CAMT.053 XML with data-importer

### ISSUE THREAD

**Issue by Gamesh** [firefly-iii/firefly-iii#8736]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

Importing XML CAMT.053 fails with error 500 using data importer  v1.3.8 

### Debug information

```
[2024-03-31 15:48:20] local.DEBUG: getFieldByIndex("entryAmount", 0)
[2024-03-31 15:48:20] local.DEBUG: getFieldByIndex("entryAmountCurrency", 0)
[2024-03-31 15:48:20] local.DEBUG: getFieldByIndex("entryValueDate", 0)
[2024-03-31 15:48:20] local.ERROR: Call to a member function format() on null {"exception":"[object] (Error(code: 0): Call to a member function format() on null at /var/www/data-importer/app/Services/Camt/Transaction.php:171)
[stacktrace]
#0 /var/www/data-importer/app/Services/CSV/Roles/RoleService.php(235): App\\Services\\Camt\\Transaction->getFieldByIndex()
#1 /var/www/data-importer/app/Http/Controllers/Import/File/RoleController.php(141): App\\Services\\CSV\\Roles\\RoleService::getExampleDataFromCamt()
#2 /var/www/data-importer/app/Http/Controllers/Import/File/RoleController.php(93): App\\Http\\Controllers\\Import\\File\\RoleController->camtIndex()
#3 /var/www/data-importer/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): App\\Http\\Controllers\\Import\\File\\RoleController->index()
#4 /var/www/data-importer/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(43): Illuminate\\Routing\\Controller->callAction()
#5 /var/www/data-importer/vendor/laravel/framework/src/Illuminate/Routing/Route.php(259): Illuminate\\Routing\\ControllerDispatcher->dispatch()
#6 /var/www/data-importer/vendor/laravel/framework/src/Illuminate/Routing/Route.php(205): Illuminate\\Routing\\Route->runController()
#7 /var/www/data-importer/vendor/laravel/framework/src/Illuminate/Routing/Router.php(799): Illuminate\\Routing\\Route->run()
#8 /var/www/data-importer/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}()
#9 /var/www/data-importer/app/Http/Middleware/IsReadyForStep.php(54): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#10 /var/www/data-importer/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): App\\Http\\Middleware\\RoleControllerMiddleware->handle()
#11 /var/www/data-importer/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(50): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#12 /var/www/data-importer/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle()
#13 /var/www/data-importer/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(78): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#14 /var/www/data-importer/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle()
#15 /var/www/data-importer/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#16 /var/www/data-importer/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle()
#17 /var/www/data-importer/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(121): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#18 /var/www/data-importer/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(64): Illuminate\\Session\\Middleware\\StartSession->handleStatefulRequest()
#19 /var/www/data-importer/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Session\\Middleware\\StartSession->handle()
#20 /var/www/data-importer/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#21 /var/www/data-importer/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle()
#22 /var/www/data-importer/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(67): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#23 /var/www/data-importer/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle()
#24 /var/www/data-importer/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#25 /var/www/data-importer/vendor/laravel/framework/src/Illuminate/Routing/Router.php(798): Illuminate\\Pipeline\\Pipeline->then()
#26 /var/www/data-importer/vendor/laravel/framework/src/Illuminate/Routing/Router.php(777): Illuminate\\Routing\\Router->runRouteWithinStack()
#27 /var/www/data-importer/vendor/laravel/framework/src/Illuminate/Routing/Router.php(741): Illuminate\\Routing\\Router->runRoute()
#28 /var/www/data-importer/vendor/laravel/framework/src/Illuminate/Routing/Router.php(730): Illuminate\\Routing\\Router->dispatchToRoute()
#29 /var/www/data-importer/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(200): Illuminate\\Routing\\Router->dispatch()
```

### Expected behaviour

import should finish without any errors

### Steps to reproduce

1. Select xml file for import
2. select "How to handle Level-D data": "Create Single booking..."
3. select default import account
4. rules - yes, import tags - yes
5. Detection method: content based
6. click import

### Additional info

Data Importer  v1.3.8

**Comment by JC5** [comment]
Could you upgrade to the latest version of the data importer and report back?

**Comment by Gamesh** [comment]
yup, still fails with the same error:

```
[2024-04-05 22:04:31] local.ERROR: Call to a member function format() on null {"exception":"[object] (Error(code: 0): Call to a member function format() on null at /var/www/data-importer/app/Services/Camt/Transac
tion.php:166)
[stacktrace]
#0 /var/www/data-importer/app/Services/CSV/Roles/RoleService.php(236): App\\Services\\Camt\\Transaction->getFieldByIndex()
#1 /var/www/data-importer/app/Http/Controllers/Import/File/RoleController.php(115): App\\Services\\CSV\\Roles\\RoleService::getExampleDataFromCamt()
```
data importer v1.4.5

in Transaction.php:166 it seems `$this->levelC->getValueDate()` can return null and in my case it does.

adjusting it to
```
return (string)$this->levelC->getValueDate()?->format(self::TIME_FORMAT);
```
fixes the issue, but i don't know much about the logic and camt format, is falling back to empty string ok or it should be something else.
Also the same can be true for line 170, static analysis shows that `$this->levelC->getBookingDate()` can also return null

**Comment by JC5** [comment]
Nice, thanks for the suggested fix!

Could you run the `:develop` tag, and see if it's fixed?
