### ISSUE TITLE
Migration Error when upgrading from `6.0.26` to `6.1.13`

### ISSUE THREAD

**Issue by cachho** [firefly-iii/firefly-iii#8761]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [ ] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

Had trouble upgrading from 6.0.26 before, tried again with the latest version, still getting errors. Deleting the database and starting over really isn't an option in my case. But I have a couple issues with `6.0.26` and before I report them, I want to make sure they aren't fixed in the latest version. Thanks for your help.

### Debug information

Can't get to the debug page.

### Steps to reproduce

php artisan migrate --seed
php artisan firefly-iii:decrypt-all
php artisan cache:clear
php artisan firefly-iii:upgrade-database <--------- error here
php artisan firefly-iii:laravel-passport-keys
php artisan cache:clear

### Additional info

```
root@app:/var/www/html# php artisan firefly:upgrade-database

   INFO  Nothing to migrate.

   INFO  Seeding database.

  Database\Seeders\AccountTypeSeeder ................................. RUNNING
  Database\Seeders\AccountTypeSeeder .............................. 21 ms DONE

  Database\Seeders\TransactionCurrencySeeder ......................... RUNNING
  Database\Seeders\TransactionCurrencySeeder ...................... 20 ms DONE

  Database\Seeders\TransactionTypeSeeder ............................. RUNNING
  Database\Seeders\TransactionTypeSeeder ........................... 8 ms DONE

  Database\Seeders\PermissionSeeder .................................. RUNNING
  Database\Seeders\PermissionSeeder ................................ 4 ms DONE

  Database\Seeders\LinkTypeSeeder .................................... RUNNING
  Database\Seeders\LinkTypeSeeder .................................. 5 ms DONE

  Database\Seeders\ConfigSeeder ...................................... RUNNING
  Database\Seeders\ConfigSeeder .................................... 4 ms DONE

  Database\Seeders\UserRoleSeeder .................................... RUNNING
  Database\Seeders\UserRoleSeeder ................................. 11 ms DONE

  Database\Seeders\ExchangeRateSeeder ................................ RUNNING
  Database\Seeders\ExchangeRateSeeder ............................. 44 ms DONE

  [i] No decryption required for table "accounts".
  [i] No decryption required for table "attachments".
  [i] No decryption required for table "bills".
  [i] No decryption required for table "budgets".
  [i] No decryption required for table "categories".
  [i] No decryption required for table "piggy_banks".
  [i] No decryption required for table "preferences".
  [i] No decryption required for table "tags".
  [i] No decryption required for table "transaction_journals".
  [i] No decryption required for table "transactions".
  [i] No decryption required for table "journal_links".
      Now executing firefly-iii:transaction-identifiers
  [i] This command has already been executed.
      Now executing firefly-iii:migrate-to-groups
  [i] Database is already migrated.
      Now executing firefly-iii:account-currencies
  [i] This command has already been executed.
      Now executing firefly-iii:transfer-currencies
  [i] This command has already been executed.
      Now executing firefly-iii:other-currencies
  [i] This command has already been executed.
      Now executing firefly-iii:migrate-notes
  [i] This command has already been executed.
      Now executing firefly-iii:migrate-attachments
  [i] This command has already been executed.
      Now executing firefly-iii:bills-to-rules
  [i] This command has already been executed.
      Now executing firefly-iii:bl-currency
  [i] This command has already been executed.
      Now executing firefly-iii:cc-liabilities
  [i] This command has already been executed.
      Now executing firefly-iii:back-to-journals
  [i] This command has already been executed.
      Now executing firefly-iii:rename-account-meta
  [i] This command has already been executed.
      Now executing firefly-iii:migrate-recurrence-meta
  [i] This command has already been executed.
      Now executing firefly-iii:migrate-tag-locations
  [i] This command has already been executed.
      Now executing firefly-iii:migrate-recurrence-type
  [i] This command has already been executed.
      Now executing firefly-iii:upgrade-liabilities
  [i] This command has already been executed.
      Now executing firefly-iii:liabilities-600
  [i] This command has already been executed.
      Now executing firefly-iii:budget-limit-periods
  [i] This command has already been executed.
      Now executing firefly-iii:migrate-rule-actions
  [i] Expression engine is not enabled. Nothing to do.
      Now executing firefly-iii:restore-oauth-keys
  [✓] OAuth keys are OK
      Now executing firefly-iii:create-group-memberships
  [✓] Validated group memberships
      Now executing firefly-iii:upgrade-group-information
      Now executing firefly-iii:upgrade-currency-preferences
[2024-04-07 17:26:49] local.ERROR: Exception is: {"class":"Illuminate\\Database\\QueryException","errorMessage":"SQLSTATE[42S02]: Base table or view not found: 1932 Table 'firefly.transaction_currency_user_group' doesn't exist in engine (Connection: mysql, SQL: select * from `transaction_currency_user_group` where `transaction_currency_user_group`.`user_group_id` = 1)","time":"Sun, 07 Apr 2024 17:26:49 +0200","file":"\/var\/www\/html\/vendor\/laravel\/framework\/src\/Illuminate\/Database\/Connection.php","line":813,"code":"42S02","version":"6.1.13","url":"http:\/\/localhost","userAgent":"Symfony","json":true,"method":"GET","post":""}
[2024-04-07 17:26:49] local.WARNING: [Bcc] Could not email or log the error. Please validate your email settings, use the .env.example file as a guide.
[2024-04-07 17:26:49] local.ERROR: SQLSTATE[42S02]: Base table or view not found: 1932 Table 'firefly.transaction_currency_user_group' doesn't exist in engine (Connection: mysql, SQL: select * from `transaction_currency_user_group` where `transaction_currency_user_group`.`user_group_id` = 1) {"exception":"[object] (Illuminate\\Database\\QueryException(code: 42S02): SQLSTATE[42S02]: Base table or view not found: 1932 Table 'firefly.transaction_currency_user_group' doesn't exist in engine (Connection: mysql, SQL: select * from `transaction_currency_user_group` where `transaction_currency_user_group`.`user_group_id` = 1) at /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php:813)
[stacktrace]
#0 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php(767): Illuminate\\Database\\Connection->runQueryCallback()
#1 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php(398): Illuminate\\Database\\Connection->run()
#2 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2899): Illuminate\\Database\\Connection->select()
#3 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2884): Illuminate\\Database\\Query\\Builder->runSelect()
#4 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(3468): Illuminate\\Database\\Query\\Builder->Illuminate\\Database\\Query\\{closure}()
#5 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2883): Illuminate\\Database\\Query\\Builder->onceWithColumns()
#6 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Relations/Concerns/InteractsWithPivotTable.php(500): Illuminate\\Database\\Query\\Builder->get()
#7 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Relations/Concerns/InteractsWithPivotTable.php(93): Illuminate\\Database\\Eloquent\\Relations\\BelongsToMany->getCurrentlyAttachedPivots()
#8 /var/www/html/app/Console/Commands/Upgrade/UpgradeCurrencyPreferences.php(105): Illuminate\\Database\\Eloquent\\Relations\\BelongsToMany->sync()
#9 /var/www/html/app/Console/Commands/Upgrade/UpgradeCurrencyPreferences.php(83): FireflyIII\\Console\\Commands\\Upgrade\\UpgradeCurrencyPreferences->upgradeGroupPreferences()
#10 /var/www/html/app/Console/Commands/Upgrade/UpgradeCurrencyPreferences.php(58): FireflyIII\\Console\\Commands\\Upgrade\\UpgradeCurrencyPreferences->runUpgrade()
#11 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): FireflyIII\\Console\\Commands\\Upgrade\\UpgradeCurrencyPreferences->handle()
#12 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#13 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure()
#14 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(35): Illuminate\\Container\\BoundMethod::callBoundMethod()
#15 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(662): Illuminate\\Container\\BoundMethod::call()
#16 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(212): Illuminate\\Container\\Container->call()
#17 /var/www/html/vendor/symfony/console/Command/Command.php(279): Illuminate\\Console\\Command->execute()
#18 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(181): Symfony\\Component\\Console\\Command\\Command->run()
#19 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Concerns/CallsCommands.php(67): Illuminate\\Console\\Command->run()
#20 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Concerns/CallsCommands.php(28): Illuminate\\Console\\Command->runCommand()
#21 /var/www/html/app/Console/Commands/Upgrade/UpgradeDatabase.php(79): Illuminate\\Console\\Command->call()
#22 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): FireflyIII\\Console\\Commands\\Upgrade\\UpgradeDatabase->handle()
#23 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#24 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure()
#25 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(35): Illuminate\\Container\\BoundMethod::callBoundMethod()
#26 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(662): Illuminate\\Container\\BoundMethod::call()
#27 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(212): Illuminate\\Container\\Container->call()
#28 /var/www/html/vendor/symfony/console/Command/Command.php(279): Illuminate\\Console\\Command->execute()
#29 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(181): Symfony\\Component\\Console\\Command\\Command->run()
#30 /var/www/html/vendor/symfony/console/Application.php(1049): Illuminate\\Console\\Command->run()
#31 /var/www/html/vendor/symfony/console/Application.php(318): Symfony\\Component\\Console\\Application->doRunCommand()
#32 /var/www/html/vendor/symfony/console/Application.php(169): Symfony\\Component\\Console\\Application->doRun()
#33 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(196): Symfony\\Component\\Console\\Application->run()
#34 /var/www/html/artisan(35): Illuminate\\Foundation\\Console\\Kernel->handle()
#35 {main}

[previous exception] [object] (PDOException(code: 42S02): SQLSTATE[42S02]: Base table or view not found: 1932 Table 'firefly.transaction_currency_user_group' doesn't exist in engine at /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php:407)
[stacktrace]
#0 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php(407): PDO->prepare()
#1 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php(800): Illuminate\\Database\\Connection->Illuminate\\Database\\{closure}()
#2 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php(767): Illuminate\\Database\\Connection->runQueryCallback()
#3 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php(398): Illuminate\\Database\\Connection->run()
#4 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2899): Illuminate\\Database\\Connection->select()
#5 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2884): Illuminate\\Database\\Query\\Builder->runSelect()
#6 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(3468): Illuminate\\Database\\Query\\Builder->Illuminate\\Database\\Query\\{closure}()
#7 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2883): Illuminate\\Database\\Query\\Builder->onceWithColumns()
#8 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Relations/Concerns/InteractsWithPivotTable.php(500): Illuminate\\Database\\Query\\Builder->get()
#9 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Relations/Concerns/InteractsWithPivotTable.php(93): Illuminate\\Database\\Eloquent\\Relations\\BelongsToMany->getCurrentlyAttachedPivots()
#10 /var/www/html/app/Console/Commands/Upgrade/UpgradeCurrencyPreferences.php(105): Illuminate\\Database\\Eloquent\\Relations\\BelongsToMany->sync()
#11 /var/www/html/app/Console/Commands/Upgrade/UpgradeCurrencyPreferences.php(83): FireflyIII\\Console\\Commands\\Upgrade\\UpgradeCurrencyPreferences->upgradeGroupPreferences()
#12 /var/www/html/app/Console/Commands/Upgrade/UpgradeCurrencyPreferences.php(58): FireflyIII\\Console\\Commands\\Upgrade\\UpgradeCurrencyPreferences->runUpgrade()
#13 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): FireflyIII\\Console\\Commands\\Upgrade\\UpgradeCurrencyPreferences->handle()
#14 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#15 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure()
#16 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(35): Illuminate\\Container\\BoundMethod::callBoundMethod()
#17 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(662): Illuminate\\Container\\BoundMethod::call()
#18 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(212): Illuminate\\Container\\Container->call()
#19 /var/www/html/vendor/symfony/console/Command/Command.php(279): Illuminate\\Console\\Command->execute()
#20 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(181): Symfony\\Component\\Console\\Command\\Command->run()
#21 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Concerns/CallsCommands.php(67): Illuminate\\Console\\Command->run()
#22 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Concerns/CallsCommands.php(28): Illuminate\\Console\\Command->runCommand()
#23 /var/www/html/app/Console/Commands/Upgrade/UpgradeDatabase.php(79): Illuminate\\Console\\Command->call()
#24 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): FireflyIII\\Console\\Commands\\Upgrade\\UpgradeDatabase->handle()
#25 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#26 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure()
#27 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(35): Illuminate\\Container\\BoundMethod::callBoundMethod()
#28 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(662): Illuminate\\Container\\BoundMethod::call()
#29 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(212): Illuminate\\Container\\Container->call()
#30 /var/www/html/vendor/symfony/console/Command/Command.php(279): Illuminate\\Console\\Command->execute()
#31 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(181): Symfony\\Component\\Console\\Command\\Command->run()
#32 /var/www/html/vendor/symfony/console/Application.php(1049): Illuminate\\Console\\Command->run()
#33 /var/www/html/vendor/symfony/console/Application.php(318): Symfony\\Component\\Console\\Application->doRunCommand()
#34 /var/www/html/vendor/symfony/console/Application.php(169): Symfony\\Component\\Console\\Application->doRun()
#35 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(196): Symfony\\Component\\Console\\Application->run()
#36 /var/www/html/artisan(35): Illuminate\\Foundation\\Console\\Kernel->handle()
#37 {main}
"}

   Illuminate\Database\QueryException

  SQLSTATE[42S02]: Base table or view not found: 1932 Table 'firefly.transaction_currency_user_group' doesn't exist in engine (Connection: mysql, SQL: select * from `transaction_currency_user_group` where `transaction_currency_user_group`.`user_group_id` = 1)

  at vendor/laravel/framework/src/Illuminate/Database/Connection.php:813
    809▕                     $this->getName(), $query, $this->prepareBindings($bindings), $e
    810▕                 );
    811▕             }
    812▕
  ➜ 813▕             throw new QueryException(
    814▕                 $this->getName(), $query, $this->prepareBindings($bindings), $e
    815▕             );
    816▕         }
    817▕     }

  i   A table was not found: You might have forgotten to run your database migrations.
      https://laravel.com/docs/master/migrations#running-migrations

      +11 vendor frames

  12  app/Console/Commands/Upgrade/UpgradeCurrencyPreferences.php:105
      Illuminate\Database\Eloquent\Relations\BelongsToMany::sync()

  13  app/Console/Commands/Upgrade/UpgradeCurrencyPreferences.php:83
      FireflyIII\Console\Commands\Upgrade\UpgradeCurrencyPreferences::upgradeGroupPreferences()
```

**Comment by JC5** [comment]
I’m surprised that it says that there are no migrations to be performed, and yet it crashes because a table can’t be found. Are you aware of any previous errrors?
