### ISSUE TITLE
Login with `AUTHENTICATION_GUARD=remote_user_guard` fails due to missing UserGroup

### ISSUE THREAD

**Issue by nebulade** [firefly-iii/firefly-iii#8812]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

While updating the Cloudron package for 6.1.14 we have encountered an issue upon login throwing the following exception:
```
FireflyIII\\Support\\Amount::getDefaultCurrencyByUserGroup(): Argument #1 ($userGroup) must be of type FireflyIII\\Models\\UserGroup, null given, called in \/app\/code\/app\/Support\/Amount.php on line 100
```
The package uses `AUTHENTICATION_GUARD=remote_user_guard` using local users works as expected. It also works with 6.1.13

Looks like a lot of work has gone into group related changes since then: https://github.com/firefly-iii/firefly-iii/compare/v6.1.13...v6.1.14

Happy to do further debugging, any pointers on where to start would be great! 

### Debug information
```
11:46:39 - [2024-04-23 11:46:39] local.ERROR: Exception is: {"class":"TypeError","errorMessage":"FireflyIII\\Support\\Amount::getDefaultCurrencyByUserGroup(): Argument #1 ($userGroup) must be of type FireflyIII\\Models\\UserGroup, null given, called in \/app\/code\/app\/Support\/Amount.php on line 100","time":"Tue, 23 Apr 2024 11:46:39 +0200","file":"\/app\/code\/app\/Support\/Amount.php","line":103,"code":0,"version":"6.1.14","url":"https:\/\/test.nebulon.space","userAgent":"Mozilla\/5.0 (X11; Linux x86_64; rv:125.0) Gecko\/20100101 Firefox\/125.0","json":true,"method":"GET","post":""}
11:46:39 - [2024-04-23 11:46:39] local.WARNING: [Bcc] Could not email or log the error. Please validate your email settings, use the .env.example file as a guide.
11:46:39 - [2024-04-23 11:46:39] local.ERROR: FireflyIII\Support\Amount::getDefaultCurrencyByUserGroup(): Argument #1 ($userGroup) must be of type FireflyIII\Models\UserGroup, null given, called in /app/code/app/Support/Amount.php on line 100 {"userId":1,"exception":"[object] (TypeError(code: 0): FireflyIII\\Support\\Amount::getDefaultCurrencyByUserGroup(): Argument #1 ($userGroup) must be of type FireflyIII\\Models\\UserGroup, null given, called in /app/code/app/Support/<30>1 2024-04-23T09:46:39Z my.nebulon.space 2f7f57d9-ea4e-4d29-8901-84a4ef840428 1069 2f7f57d9-ea4e-4d29-8901-84a4ef840428 - #3 /app/code/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): FireflyIII\\Http\\Middleware\\Ra<30>1 2024-04-23T09:46:39Z my.nebulon.space 2f7f57d9-ea4e-4d29-8901-84a4ef840428 1069 2f7f57d9-ea4e-4d29-8901-84a4ef840428 - #4 /app/code/vendor/jc5/google2fa-laravel/src/Middleware.php(29): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pip<30>1 2024-04-23T09:46:39Z my.nebulon.space 2f7f57d9-ea4e-4d29-8901-84a4ef840428 1069 2f7f57d9-ea4e-4d29-8901-84a4ef840428 - #5 /app/code/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): PragmaRX\\Google2FALaravel\\Midd<30>1 2024-04-23T09:46:39Z my.nebulon.space 2f7f57d9-ea4e-4d29-8901-84a4ef840428 1069 2f7f57d9-ea4e-4d29-8901-84a4ef840428 - #6 /app/code/app/Http/Middleware/Authenticate.php(66): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{clo<30>1 2024-04-23T09:46:39Z my.nebulon.space 2f7f57d9-ea4e-4d29-8901-84a4ef840428 1069 2f7f57d9-ea4e-4d29-8901-84a4ef840428 - #7 /app/code/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): FireflyIII\\Http\\Middleware\\Au<30>1 2024-04-23T09:46:39Z my.nebulon.space 2f7f57d9-ea4e-4d29-8901-84a4ef840428 1069 2f7f57d9-ea4e-4d29-8901-84a4ef840428 - #8 /app/code/vendor/laravel/passport/src/Http/Middleware/CreateFreshApiToken.php(63): Illuminate\\Pipeline\\Pipel<30>1 2024-04-23T09:46:39Z my.nebulon.space 2f7f57d9-ea4e-4d29-8901-84a4ef840428 1069 2f7f57d9-ea4e-4d29-8901-84a4ef840428 - #9 /app/code/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Laravel\\Passport\\Http\\Middlew<30>1 2024-04-23T09:46:39Z my.nebulon.space 2f7f57d9-ea4e-4d29-8901-84a4ef840428 1069 2f7f57d9-ea4e-4d29-8901-84a4ef840428 - #10 /app/code/vendor/laravel/framework/src/Illuminate/Session/Middleware/AuthenticateSession.php(48): Illuminate\<30>1 2024-04-23T09:46:39Z my.nebulon.space 2f7f57d9-ea4e-4d29-8901-84a4ef840428 1069 2f7f57d9-ea4e-4d29-8901-84a4ef840428 - #11 /app/code/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Session\\Middleware<30>1 2024-04-23T09:46:39Z my.nebulon.space 2f7f57d9-ea4e-4d29-8901-84a4ef840428 1069 2f7f57d9-ea4e-4d29-8901-84a4ef840428 - #12 /app/code/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(88): Illumin<30>1 2024-04-23T09:46:39Z my.nebulon.space 2f7f57d9-ea4e-4d29-8901-84a4ef840428 1069 2f7f57d9-ea4e-4d29-8901-84a4ef840428 - #13 /app/code/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Foundation\\Http\\M<30>1 2024-04-23T09:46:39Z my.nebulon.space 2f7f57d9-ea4e-4d29-8901-84a4ef840428 1069 2f7f57d9-ea4e-4d29-8901-84a4ef840428 - #14 /app/code/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\<30>1 2024-04-23T09:46:39Z my.nebulon.space 2f7f57d9-ea4e-4d29-8901-84a4ef840428 1069 2f7f57d9-ea4e-4d29-8901-84a4ef840428 - #15 /app/code/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle()
<30>1 2024-04-23T09:46:39Z my.nebulon.space 2f7f57d9-ea4e-4d29-8901-84a4ef840428 1069 2f7f57d9-ea4e-4d29-8901-84a4ef840428 - #17 /app/code/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(64): Illuminate\\Sessio<30>1 2024-04-23T09:46:39Z my.nebulon.space 2f7f57d9-ea4e-4d29-8901-84a4ef840428 1069 2f7f57d9-ea4e-4d29-8901-84a4ef840428 - #18 /app/code/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Session\\Middleware<30>1 2024-04-23T09:46:39Z my.nebulon.space 2f7f57d9-ea4e-4d29-8901-84a4ef840428 1069 2f7f57d9-ea4e-4d29-8901-84a4ef840428 - #19 /app/code/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illum<30>1 2024-04-23T09:46:39Z my.nebulon.space 2f7f57d9-ea4e-4d29-8901-84a4ef840428 1069 2f7f57d9-ea4e-4d29-8901-84a4ef840428 - #20 /app/code/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Cookie\\Middleware\<30>1 2024-04-23T09:46:39Z my.nebulon.space 2f7f57d9-ea4e-4d29-8901-84a4ef840428 1069 2f7f57d9-ea4e-4d29-8901-84a4ef840428 - #21 /app/code/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(75): Illuminate\\Pipel<30>1 2024-04-23T09:46:39Z my.nebulon.space 2f7f57d9-ea4e-4d29-8901-84a4ef840428 1069 2f7f57d9-ea4e-4d29-8901-84a4ef840428 - #22 /app/code/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Cookie\\Middleware\<30>1 2024-04-23T09:46:39Z my.nebulon.space 2f7f57d9-ea4e-4d29-8901-84a4ef840428 1069 2f7f57d9-ea4e-4d29-8901-84a4ef840428 - #23 /app/code/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(119): Illuminate\\Pipeline\\Pipeline-<30>1 2024-04-23T09:46:39Z my.nebulon.space 2f7f57d9-ea4e-4d29-8901-84a4ef840428 1069 2f7f57d9-ea4e-4d29-8901-84a4ef840428 - #24 /app/code/vendor/laravel/framework/src/Illuminate/Routing/Router.php(805): Illuminate\\Pipeline\\Pipeline->th<30>1 2024-04-23T09:46:39Z my.nebulon.space 2f7f57d9-ea4e-4d29-8901-84a4ef840428 1069 2f7f57d9-ea4e-4d29-8901-84a4ef840428 - #25 /app/code/vendor/laravel/framework/src/Illuminate/Routing/Router.php(784): Illuminate\\Routing\\Router->runRo<30>1 2024-04-23T09:46:39Z my.nebulon.space 2f7f57d9-ea4e-4d29-8901-84a4ef840428 1069 2f7f57d9-ea4e-4d29-8901-84a4ef840428 - #26 /app/code/vendor/laravel/framework/src/Illuminate/Routing/Router.php(748): Illuminate\\Routing\\Router->runRo<30>1 2024-04-23T09:46:39Z my.nebulon.space 2f7f57d9-ea4e-4d29-8901-84a4ef840428 1069 2f7f57d9-ea4e-4d29-8901-84a4ef840428 - #27 /app/code/vendor/laravel/framework/src/Illuminate/Routing/Router.php(737): Illuminate\\Routing\\Router->dispa<30>1 2024-04-23T09:46:39Z my.nebulon.space 2f7f57d9-ea4e-4d29-8901-84a4ef840428 1069 2f7f57d9-ea4e-4d29-8901-84a4ef840428 - #28 /app/code/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(200): Illuminate\\Routing\\Route<30>1 2024-04-23T09:46:39Z my.nebulon.space 2f7f57d9-ea4e-4d29-8901-84a4ef840428 1069 2f7f57d9-ea4e-4d29-8901-84a4ef840428 - #29 /app/code/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(144): Illuminate\\Foundation\\Http\\K<30>1 2024-04-23T09:46:39Z my.nebulon.space 2f7f57d9-ea4e-4d29-8901-84a4ef840428 1069 2f7f57d9-ea4e-4d29-8901-84a4ef840428 - #30 /app/code/app/Http/Middleware/InstallationId.php(47): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{<30>1 2024-04-23T09:46:39Z my.nebulon.space 2f7f57d9-ea4e-4d29-8901-84a4ef840428 1069 2f7f57d9-ea4e-4d29-8901-84a4ef840428 - #31 /app/code/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): FireflyIII\\Http\\Middleware\\I<30>1 2024-04-23T09:46:39Z my.nebulon.space 2f7f57d9-ea4e-4d29-8901-84a4ef840428 1069 2f7f57d9-ea4e-4d29-8901-84a4ef840428 - #32 /app/code/vendor/laravel/framework/src/Illuminate/Http/Middleware/TrustProxies.php(57): Illuminate\\Pipeline\<30>1 2024-04-23T09:46:39Z my.nebulon.space 2f7f57d9-ea4e-4d29-8901-84a4ef840428 1069 2f7f57d9-ea4e-4d29-8901-84a4ef840428 - #33 /app/code/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Http\\Middleware\\T<30>1 2024-04-23T09:46:39Z my.nebulon.space 2f7f57d9-ea4e-4d29-8901-84a4ef840428 1069 2f7f57d9-ea4e-4d29-8901-84a4ef840428 - #34 /app/code/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illum<30>1 2024-04-23T09:46:39Z my.nebulon.space 2f7f57d9-ea4e-4d29-8901-84a4ef840428 1069 2f7f57d9-ea4e-4d29-8901-84a4ef840428 - #35 /app/code/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.php(31<30>1 2024-04-23T09:46:39Z my.nebulon.space 2f7f57d9-ea4e-4d29-8901-84a4ef840428 1069 2f7f57d9-ea4e-4d29-8901-84a4ef840428 - #36 /app/code/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Foundation\\Http\\M<30>1 2024-04-23T09:46:39Z my.nebulon.space 2f7f57d9-ea4e-4d29-8901-84a4ef840428 1069 2f7f57d9-ea4e-4d29-8901-84a4ef840428 - #37 /app/code/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illum<30>1 2024-04-23T09:46:39Z my.nebulon.space 2f7f57d9-ea4e-4d29-8901-84a4ef840428 1069 2f7f57d9-ea4e-4d29-8901-84a4ef840428 - #38 /app/code/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php(51): Illuminate\<30>1 2024-04-23T09:46:39Z my.nebulon.space 2f7f57d9-ea4e-4d29-8901-84a4ef840428 1069 2f7f57d9-ea4e-4d29-8901-84a4ef840428 - #39 /app/code/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Foundation\\Http\\M<30>1 2024-04-23T09:46:39Z my.nebulon.space 2f7f57d9-ea4e-4d29-8901-84a4ef840428 1069 2f7f57d9-ea4e-4d29-8901-84a4ef840428 - #40 /app/code/vendor/laravel/framework/src/Illuminate/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipel<30>1 2024-04-23T09:46:39Z my.nebulon.space 2f7f57d9-ea4e-4d29-8901-84a4ef840428 1069 2f7f57d9-ea4e-4d29-8901-84a4ef840428 - #41 /app/code/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Http\\Middleware\\V<30>1 2024-04-23T09:46:39Z my.nebulon.space 2f7f57d9-ea4e-4d29-8901-84a4ef840428 1069 2f7f57d9-ea4e-4d29-8901-84a4ef840428 - #42 /app/code/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance<30>1 2024-04-23T09:46:39Z my.nebulon.space 2f7f57d9-ea4e-4d29-8901-84a4ef840428 1069 2f7f57d9-ea4e-4d29-8901-84a4ef840428 - #43 /app/code/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Foundation\\Http\\M<30>1 2024-04-23T09:46:39Z my.nebulon.space 2f7f57d9-ea4e-4d29-8901-84a4ef840428 1069 2f7f57d9-ea4e-4d29-8901-84a4ef840428 - #44 /app/code/app/Http/Middleware/SecureHeaders.php(52): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{c<30>1 2024-04-23T09:46:39Z my.nebulon.space 2f7f57d9-ea4e-4d29-8901-84a4ef840428 1069 2f7f57d9-ea4e-4d29-8901-84a4ef840428 - #45 /app/code/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): FireflyIII\\Http\\Middleware\\S<30>1 2024-04-23T09:46:39Z my.nebulon.space 2f7f57d9-ea4e-4d29-8901-84a4ef840428 1069 2f7f57d9-ea4e-4d29-8901-84a4ef840428 - #46 /app/code/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(119): Illuminate\\Pipeline\\Pipeline-<30>1 2024-04-23T09:46:39Z my.nebulon.space 2f7f57d9-ea4e-4d29-8901-84a4ef840428 1069 2f7f57d9-ea4e-4d29-8901-84a4ef840428 - #47 /app/code/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(175): Illuminate\\Pipeline\\Pipe<30>1 2024-04-23T09:46:39Z my.nebulon.space 2f7f57d9-ea4e-4d29-8901-84a4ef840428 1069 2f7f57d9-ea4e-4d29-8901-84a4ef840428 - #48 /app/code/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(144): Illuminate\\Foundation\\Ht<30>1 2024-04-23T09:46:39Z my.nebulon.space 2f7f57d9-ea4e-4d29-8901-84a4ef840428 1069 2f7f57d9-ea4e-4d29-8901-84a4ef840428 - "}0 {main}ode/public/index.php(73): Illuminate\\Foundation\\Http\\Kernel->handle()
11:46:39 - 188.193.222.83 - - [23/Apr/2024:09:46:39 +0000] "GET / HTTP/1.1" 500 5546 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:125.0) Gecko/20100101 Firefox/125.0"
```

**Comment by JC5** [comment]
Nice find, I'll pick it up!

**Comment by JC5** [comment]
Be sure to open a new issue if 6.1.15 still breaks (it shouldn't, but you never know).

**Comment by nebulade** [comment]
Great and thanks for the super fast fix! I can confirm it works as expected now.
