### ISSUE TITLE
Data Importer: "500 Server Error" with Firefly III v6.1.17

### ISSUE THREAD

**Issue by qtdzz** [firefly-iii/firefly-iii#8977]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

I have the same data-importer configuration in docker-compose with FIREFLY_III_URL and VANITY_URL. It was working fine for v6.1.16 but it throws "500 Server Error" in v6.1.17 when trying to connect the data-importer to the FireflyIII instance. Both containers are in the same network. I tried in different browsers but it didn't work. Reverting to v6.1.16 works. 

Please let me know if you need more information.

Thank you for these amazing softwares  :)
ps:
>⚠️ You can't connect to the Data Importer due to 404's or authentication issues.
> If you run into an issue like this, please start a [discussion](https://github.com/firefly-iii/firefly-iii/discussions) or chat on [Gitter.im](https://gitter.im/firefly-iii/firefly-iii). There's a good chance it's not a bug but something we can fix rather quickly 👍

I've read this but I guess it could be a bug in v6.1.17, hence created an issue instead of a discussion. Please feel free to convert to a dicussion if it's more appropriate.

Log from the importer:

```
[2024-06-16 14:18:16] local.DEBUG: Now in App\Http\Controllers\IndexController::index  
[2024-06-16 14:18:16] local.DEBUG: App\Services\Shared\Authentication\SecretManager::hasValidSecrets  
[2024-06-16 14:18:16] local.DEBUG: No valid secrets, redirect to token.index  
172.16.1.137 - - [16/Jun/2024:14:18:16 +0200] "GET / HTTP/1.1" 302 1506 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:127.0) Gecko/20100101 Firefox/127.0"
[2024-06-16 14:18:16] local.DEBUG: Now at App\Http\Controllers\TokenController::index  
[2024-06-16 14:18:16] local.DEBUG: No access token in hasAccessToken() session, will return config variable.  
[2024-06-16 14:18:16] local.DEBUG: No client id in hasClientId() session, will return config variable.  
[2024-06-16 14:18:16] local.DEBUG: No base url in getBaseUrl() session, will return config variable.  
[2024-06-16 14:18:16] local.DEBUG: No vanity url in getVanityUrl() session, will return config variable.  
[2024-06-16 14:18:16] local.INFO: The following configuration information was found:  
[2024-06-16 14:18:16] local.INFO: Personal Access Token: "" (limited to 25 chars if present)  
[2024-06-16 14:18:16] local.INFO: Client ID            : "0"  
[2024-06-16 14:18:16] local.INFO: Base URL             : "http://fireflyiii:8080"  
[2024-06-16 14:18:16] local.INFO: Vanity URL           : "https://[my_redacted_fireflyIII_url]"  
172.16.1.137 - - [16/Jun/2024:14:18:16 +0200] "GET /token HTTP/1.1" 200 3030 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:127.0) Gecko/20100101 Firefox/127.0"
[2024-06-16 14:18:18] local.DEBUG: Now at App\Http\Controllers\TokenController::submitClientId  
[2024-06-16 14:18:18] local.DEBUG: Query parameters are {"client_id":3,"redirect_uri":"https://[my_redacted_importer_url]/callback","response_type":"code","scope":"","state":"REDACTED","code_challenge":"REDACTED","code_challenge_method":"S256"} 
[2024-06-16 14:18:18] local.DEBUG: Now redirecting to "https://my_redacted_fireflyIII_url/oauth/authorize?" (params omitted)  
172.16.1.137 - - [16/Jun/2024:14:18:18 +0200] "POST /token/client_id HTTP/1.1" 302 2787 "https://my_redacted_importer_url/token" "Mozilla/5.0 (X11; Linux x86_64; rv:127.0) Gecko/20100101 Firefox/127.0"
[2024-06-16 14:18:27] local.DEBUG: Now at App\Http\Controllers\TokenController::callback  
[2024-06-16 14:18:27] local.DEBUG: State is valid!  
[2024-06-16 14:18:27] local.DEBUG: Params for access token {"form_params":{"grant_type":"authorization_code","client_id":3,"redirect_uri":"https://my_redacted_importer_url/callback","code_verifier":"REDACTED"}} 
[2024-06-16 14:18:27] local.DEBUG: Will contact "http://fireflyiii:8080/oauth/token" for a token.  
[2024-06-16 14:18:27] local.ERROR: Client exception when decoding response: Client error: `POST http://fireflyiii:8080/oauth/token` resulted in a `419 unknown status` response:
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width= (truncated...)
  
[2024-06-16 14:18:27] local.ERROR: Response from server: "<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">

    all values are hidden

        <title>Page Expired</title>

    all values are hidden

        <style>
            /*! normalize.css v8.0.1 | MIT License | github.com/necolas/normalize.css */html{line-height:1.15;-webkit-text-size-adjust:100%}body{margin:0}a{background-color:transparent}code{font-family:monospace,monospace;font-size:1em}[hidden]{display:none}html{font-family:system-ui,-apple-system,BlinkMacSystemFont,Segoe UI,Roboto,Helvetica Neue,Arial,Noto Sans,sans-serif,Apple Color Emoji,Segoe UI Emoji,Segoe UI Symbol,Noto Color Emoji;line-height:1.5}*,:after,:before{box-sizing:border-box;border:0 solid #e2e8f0}a{color:inherit;text-decoration:inherit}code{font-family:Menlo,Monaco,Consolas,Liberation Mono,Courier New,monospace}svg,video{display:block;vertical-align:middle}video{max-width:100%;height:auto}.bg-white{--bg-opacity:1;background-color:#fff;background-color:rgba(255,255,255,var(--bg-opacity))}.bg-gray-100{--bg-opacity:1;background-color:#f7fafc;background-color:rgba(247,250,252,var(--bg-opacity))}.border-gray-200{--border-opacity:1;border-color:#edf2f7;border-color:rgba(237,242,247,var(--border-opacity))}.border-gray-400{--border-opacity:1;border-color:#cbd5e0;border-color:rgba(203,213,224,var(--border-opacity))}.border-t{border-top-width:1px}.border-r{border-right-width:1px}.flex{display:flex}.grid{display:grid}.hidden{display:none}.items-center{align-items:center}.justify-center{justify-content:center}.font-semibold{font-weight:600}.h-5{height:1.25rem}.h-8{height:2rem}.h-16{height:4rem}.text-sm{font-size:.875rem}.text-lg{font-size:1.125rem}.leading-7{line-height:1.75rem}.mx-auto{margin-left:auto;margin-right:auto}.ml-1{margin-left:.25rem}.mt-2{margin-top:.5rem}.mr-2{margin-right:.5rem}.ml-2{margin-left:.5rem}.mt-4{margin-top:1rem}.ml-4{margin-left:1rem}.mt-8{margin-top:2rem}.ml-12{margin-left:3rem}.-mt-px{margin-top:-1px}.max-w-xl{max-width:36rem}.max-w-6xl{max-width:72rem}.min-h-screen{min-height:100vh}.overflow-hidden{overflow:hidden}.p-6{padding:1.5rem}.py-4{padding-top:1rem;padding-bottom:1rem}.px-4{padding-left:1rem;padding-right:1rem}.px-6{padding-left:1.5rem;padding-right:1.5rem}.pt-8{padding-top:2rem}.fixed{position:fixed}.relative{position:relative}.top-0{top:0}.right-0{right:0}.shadow{box-shadow:0 1px 3px 0 rgba(0,0,0,.1),0 1px 2px 0 rgba(0,0,0,.06)}.text-center{text-align:center}.text-gray-200{--text-opacity:1;color:#edf2f7;color:rgba(237,242,247,var(--text-opacity))}.text-gray-300{--text-opacity:1;color:#e2e8f0;color:rgba(226,232,240,var(--text-opacity))}.text-gray-400{--text-opacity:1;color:#cbd5e0;color:rgba(203,213,224,var(--text-opacity))}.text-gray-500{--text-opacity:1;color:#a0aec0;color:rgba(160,174,192,var(--text-opacity))}.text-gray-600{--text-opacity:1;color:#718096;color:rgba(113,128,150,var(--text-opacity))}.text-gray-700{--text-opacity:1;color:#4a5568;color:rgba(74,85,104,var(--text-opacity))}.text-gray-900{--text-opacity:1;color:#1a202c;color:rgba(26,32,44,var(--text-opacity))}.uppercase{text-transform:uppercase}.underline{text-decoration:underline}.antialiased{-webkit-font-smoothing:antialiased;-moz-osx-font-smoothing:grayscale}.tracking-wider{letter-spacing:.05em}.w-5{width:1.25rem}.w-8{width:2rem}.w-auto{width:auto}.grid-cols-1{grid-template-columns:repeat(1,minmax(0,1fr))}@-webkit-keyframes spin{0%{transform:rotate(0deg)}to{transform:rotate(1turn)}}@keyframes spin{0%{transform:rotate(0deg)}to{transform:rotate(1turn)}}@-webkit-keyframes ping{0%{transform:scale(1);opacity:1}75%,to{transform:scale(2);opacity:0}}@keyframes ping{0%{transform:scale(1);opacity:1}75%,to{transform:scale(2);opacity:0}}@-webkit-keyframes pulse{0%,to{opacity:1}50%{opacity:.5}}@keyframes pulse{0%,to{opacity:1}50%{opacity:.5}}@-webkit-keyframes bounce{0%,to{transform:translateY(-25%);-webkit-animation-timing-function:cubic-bezier(.8,0,1,1);animation-timing-function:cubic-bezier(.8,0,1,1)}50%{transform:translateY(0);-webkit-animation-timing-function:cubic-bezier(0,0,.2,1);animation-timing-function:cubic-bezier(0,0,.2,1)}}@keyframes bounce{0%,to{transform:translateY(-25%);-webkit-animation-timing-function:cubic-bezier(.8,0,1,1);animation-timing-function:cubic-bezier(.8,0,1,1)}50%{transform:translateY(0);-webkit-animation-timing-function:cubic-bezier(0,0,.2,1);animation-timing-function:cubic-bezier(0,0,.2,1)}}@media (min-width:640px){.sm\:rounded-lg{border-radius:.5rem}.sm\:block{display:block}.sm\:items-center{align-items:center}.sm\:justify-start{justify-content:flex-start}.sm\:justify-between{justify-content:space-between}.sm\:h-20{height:5rem}.sm\:ml-0{margin-left:0}.sm\:px-6{padding-left:1.5rem;padding-right:1.5rem}.sm\:pt-0{padding-top:0}.sm\:text-left{text-align:left}.sm\:text-right{text-align:right}}@media (min-width:768px){.md\:border-t-0{border-top-width:0}.md\:border-l{border-left-width:1px}.md\:grid-cols-2{grid-template-columns:repeat(2,minmax(0,1fr))}}@media (min-width:1024px){.lg\:px-8{padding-left:2rem;padding-right:2rem}}@media (prefers-color-scheme:dark){.dark\:bg-gray-800{--bg-opacity:1;background-color:#2d3748;background-color:rgba(45,55,72,var(--bg-opacity))}.dark\:bg-gray-900{--bg-opacity:1;background-color:#1a202c;background-color:rgba(26,32,44,var(--bg-opacity))}.dark\:border-gray-700{--border-opacity:1;border-color:#4a5568;border-color:rgba(74,85,104,var(--border-opacity))}.dark\:text-white{--text-opacity:1;color:#fff;color:rgba(255,255,255,var(--text-opacity))}.dark\:text-gray-400{--text-opacity:1;color:#cbd5e0;color:rgba(203,213,224,var(--text-opacity))}}
        </style>

    all values are hidden

        <style>
            body {
                font-family: ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, "Noto Sans", sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol", "Noto Color Emoji";
            }
        </style>
    </head>
    <body class="antialiased">
        <div class="relative flex items-top justify-center min-h-screen bg-gray-100 dark:bg-gray-900 sm:items-center sm:pt-0">
            <div class="max-w-xl mx-auto sm:px-6 lg:px-8">
                <div class="flex items-center pt-8 sm:justify-start sm:pt-0">
                    <div class="px-4 text-lg text-gray-500 border-r border-gray-400 tracking-wider">
                        419                    </div>

    all values are hidden

                    <div class="ml-4 text-lg text-gray-500 uppercase tracking-wider">
                        Page Expired                    </div>
                </div>
            </div>
        </div>
    </body>
</html>
"  
[2024-06-16 14:18:27] local.ERROR: View [error] not found. {"exception":"[object] (InvalidArgumentException(code: 0): View [error] not found. at /var/www/html/vendor/laravel/framework/src/Illuminate/View/FileViewFinder.php:139)
[stacktrace]
#0 /var/www/html/vendor/laravel/framework/src/Illuminate/View/FileViewFinder.php(79): Illuminate\\View\\FileViewFinder->findInPaths()
#1 /var/www/html/vendor/laravel/framework/src/Illuminate/View/Factory.php(151): Illuminate\\View\\FileViewFinder->find()
#2 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php(1040): Illuminate\\View\\Factory->make()
#3 /var/www/html/app/Http/Controllers/TokenController.php(104): view()
#4 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): App\\Http\\Controllers\\TokenController->callback()
#5 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(43): Illuminate\\Routing\\Controller->callAction()
#6 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Route.php(260): Illuminate\\Routing\\ControllerDispatcher->dispatch()
#7 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Route.php(206): Illuminate\\Routing\\Route->runController()
#8 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(806): Illuminate\\Routing\\Route->run()
#9 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(144): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}()
#10 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(50): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#11 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle()
#12 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(88): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#13 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle()
#14 /var/www/html/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#15 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle()
#16 /var/www/html/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(121): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#17 /var/www/html/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(64): Illuminate\\Session\\Middleware\\StartSession->handleStatefulRequest()
#18 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Session\\Middleware\\StartSession->handle()
#19 /var/www/html/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#20 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle()
#21 /var/www/html/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(75): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#22 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle()
#23 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(119): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#24 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(805): Illuminate\\Pipeline\\Pipeline->then()
#25 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(784): Illuminate\\Routing\\Router->runRouteWithinStack()
#26 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(748): Illuminate\\Routing\\Router->runRoute()
#27 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(737): Illuminate\\Routing\\Router->dispatchToRoute()
#28 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(200): Illuminate\\Routing\\Router->dispatch()
#29 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(144): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}()
#30 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#31 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.php(31): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#32 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Foundation\\Http\\Middleware\\ConvertEmptyStringsToNull->handle()
#33 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#34 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php(51): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#35 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Foundation\\Http\\Middleware\\TrimStrings->handle()
#36 /var/www/html/vendor/laravel/framework/src/Illuminate/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#37 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Http\\Middleware\\ValidatePostSize->handle()
#38 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(110): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#39 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance->handle()
#40 /var/www/html/vendor/laravel/framework/src/Illuminate/Http/Middleware/HandleCors.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#41 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Http\\Middleware\\HandleCors->handle()
#42 /var/www/html/vendor/laravel/framework/src/Illuminate/Http/Middleware/TrustProxies.php(57): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#43 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Http\\Middleware\\TrustProxies->handle()
#44 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(119): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#45 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(175): Illuminate\\Pipeline\\Pipeline->then()
#46 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(144): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter()
#47 /var/www/html/public/index.php(76): Illuminate\\Foundation\\Http\\Kernel->handle()
#48 {main}
"} 
172.16.1.137 - - [16/Jun/2024:14:18:27 +0200] "GET /callback?code=REDACTED HTTP/1.1" 500 7738 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:127.0) Gecko/20100101 Firefox/127.0"
```

### Debug information

Debug information generated at 2024-06-16 14:25:51 for Firefly III version **v6.1.17**.

<table><thead><tr><th colspan="2">System information</th></tr><tr><th>Item</th><th>Value</th></tr></thead><tbody><tr><td>Firefly III</td><td>6.1.17 / v2.1.0 / 24 (exp. 24)</td></tr><tr><td>PHP version</td><td>8.3.8 (64bits) / apache2handler / Linux x86_64</td></tr><tr><td>BCscale</td><td>12</td></tr><tr><td>Error reporting</td><td>Display: Off, reporting: ALL errors</td></tr><tr><td>Max upload</td><td>67108864 (64 MB)</td></tr><tr><td>Database drivers</td><td><strong>*mysql*</strong>, pgsql, sqlite, </td></tr><tr><td>Docker build</td><td><span>#</span>1099, base <span>#</span>85</td></tr></tbody></table><table><thead><tr><th colspan="2">Firefly III information</th></tr><tr><th>Item</th><th>Value</th></tr></thead><tbody><tr><td>Timezone</td><td>Europe/Paris + Europe/Zurich</td></tr><tr><td>App environment</td><td>local, debug: false</td></tr><tr><td>Layout</td><td>v1</td></tr><tr><td>Logging</td><td>notice, stack / (empty)</td></tr><tr><td>Cache driver</td><td>file</td></tr><tr><td>Default language and locale</td><td>en_US + equal</td></tr><tr><td>Trusted proxies</td><td>**</td></tr><tr><td>Login provider & user guard</td><td>eloquent / web</td></tr><tr><td>Login headers</td><td>N/A + N/A</td></tr><tr><td>Stateful domains</td><td></td></tr><tr><td>Last cron job</td><td>never (never)</td></tr><tr><td>Mailer</td><td>log</td></tr></tbody></table><table><thead><tr><th colspan="2">User-specific information</th></tr><tr><th>Item</th><th>Value</th></tr></thead><tbody><tr><td>User</td><td><span>#</span>1 of 1</td></tr><tr><td>User flags</td><td><span title="Has rules">:wrench:</span> <span title="Has subscriptions">:email:</span></td></tr><tr><td>Session start</td><td>2024-06-01 00:00:00</td></tr><tr><td>Session end</td><td>2024-06-30 23:59:59</td></tr><tr><td>View range</td><td>1M</td></tr><tr><td>User language</td><td>en_US</td></tr><tr><td>User locale</td><td>en_US</td></tr><tr><td>Locale(s) supported</td><td>en_US.utf8: :white_check_mark:<br>en_US.UTF-8: :white_check_mark:<br></td></tr><tr><td>User agent</td><td>Mozilla/5.0 (X11; Linux x86_64; rv:127.0) Gecko/20100101 Firefox/127.0</td></tr></tbody></table>

**Comment by JC5** [comment]
What happens when you refresh the front page of the data importer? Does the session identifier change?

**Comment by qtdzz** [comment]
When it's connected with FireflyIII v6.1.16, refreshing the importer doesn't change the identifier.
Oh, I forgot to include that it's "Firefly III Data Importer, v1.5.2 "

**Comment by JC5** [comment]
What are the logs on the Firefly III side?

**Comment by qtdzz** [comment]
With debug log enabled, there is an error actually (I checked before but didn't enable debug log)
```
172.16.1.137 - - [16/Jun/2024:17:54:31 +0200] "GET /oauth/authorize?client_id=3&redirect_uri=https%3A%2F%2FREDACTED_DOMAIN%2Fcallback&response_type=code&scope=&state=R0Qf9hflLLMxAUp99mG4Qfe4EBqASFNJXsuMOgsP&code_challenge=fSHoIpCr6yfl6QKn3NdxDNV0ZwBKGq2pxgYYO8oh-xA&code_challenge_method=S256 HTTP/1.1" 302 3676 "https://REDACTED_DOMAIN/" "Mozilla/5.0 (X11; Linux x86_64; rv:127.0) Gecko/20100101 Firefox/127.0"
[2024-06-16 17:54:32] local.DEBUG: Now in Handler::render()  
[2024-06-16 17:54:32] local.DEBUG: Error "Illuminate\Session\TokenMismatchException" has no Firefly III treatment, parent will handle.  
172.16.1.150 - - [16/Jun/2024:17:54:32 +0200] "POST /oauth/token HTTP/1.1" 419 7898 "-" "GuzzleHttp/7"
127.0.0.1 - - [16/Jun/2024:17:54:49 +0200] "GET /health HTTP/1.1" 200 1741 "-" "Firefly III Health Checker/2.2"
```

**Comment by JC5** [comment]
Mmm, that's just the error that results in a 419 page. No clue as to the source of the issue.

**Comment by andreashagensjolvsagt** [comment]
I dug around the code a bit as I'm facing the same (or at least very similar) [issue](https://matrix.to/#/!epdtwMcKTscMlFxeBi:gitter.im/$5iZIJ9lP7i5nnMYYAxhvZq7ivPzQ44o5DkZcp5fks3A?via=gitter.im&via=matrix.org&via=tchncs.de). I'm no Laravel expert, but the best thing I could find is that from v6.1.16 to v6.1.17 the routing configuration changed for the OAuth2 module [Passport](https://laravel.com/docs/11.x/passport). [This line](https://github.com/firefly-iii/firefly-iii/blob/6abb74a038a32079fe208f9a9f04c0ee2d56787b/app/Providers/AppServiceProvider.php#L91) was introduced, which I assume removes the default routing config for the module, while [this config](https://github.com/firefly-iii/firefly-iii/blob/6abb74a038a32079fe208f9a9f04c0ee2d56787b/routes/web.php#L37) was introduced, presumably to compensate. Hope this is helpful. :grin: @JC5

**Comment by JC5** [comment]
Yep I know, I made the change 😉 . The thing is though, the middleware and the routes are all the same, just defined in a different place. The routes where there *are* differences, aren't the problem. 

So far, I can't even replicate this myself.

**Comment by andreashagensjolvsagt** [comment]
In the Gitter message I linked above I posted my Docker run commands. They were ran with a nearly clean installation of Firefly, only passing some minimal initial configuration through the web UI. Can you reproduce by running those maybe? Steps to reproduce should be something like:

- Run command to start Firefly.
- Make a public client for data importer.
- Run data importer.
- Browse to data importer. Authorize when redirected to Firefly.
- It should now crash once you are redirected back to data importer.

My Docker commands assume you are accessing through a reverse proxy with the domain names firefly.local and firefly-data-importer.local, so adapt as needed.

**Comment by JC5** [comment]
Managed to replicate it, thanks!

**Comment by JC5** [comment]
I might just have found it. Thanks everybody for your patience, this is a very interesting issue. 

Copying the routes (literally!) from the Laravel Passport source code doesn't work. I had to add an exception to the CSRF check, which isn't necessary when you use Laravel Passport directly. Ask me again why, and I will still have no clue. I can't find the exception in Laravel's code either. Which probably means I'm an idiot, because it should be there somewhere. Or who knows what's going on.

I invite you to try the latest `:develop`-tag, where this should work as expected!

**Comment by andreashagensjolvsagt** [comment]
That seems to have solved my problem at least. Thanks @JC5!

**Comment by qtdzz** [comment]
It fixes my problem as well. Thank you so much @JC5
