### ISSUE TITLE
Error! Internal Firefly III Exception: bcadd(): Argument #2 ($num2) is not well-formed

### ISSUE THREAD

**Issue by el-rhazi** [firefly-iii/firefly-iii#8978]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

Hello everyone,

I've encountered an issue in Firefly III that I'd like to bring to your attention. The problem can be reproduced as follows:

Start with an asset account containing a balance of $100.00.
Attempt to make a transfer or expense that fully depletes this $100.00 balance (leaving the account with $0.00).

Upon doing so, Firefly III returns the following error message:

**Error! Internal Firefly III Exception: bcadd(): Argument #2 ($num2) is not well-formed**

Interestingly, if I conduct a similar transaction but leave only $1.00 in the account, the transaction executes correctly without error.

PS: Additionally, if I adjust the account's initial balance to subtract the remaining $1.00 afterwards, the same error occurs again.

I have tested this behavior in both versions 6.1.16 and 6.1.17 of Firefly III.

Your insights and assistance in addressing this issue would be greatly appreciated.

Thank you!

Best regards,

### Debug information

Debug information generated at 2024-06-16 13:28:42 for Firefly III version **v6.1.17**.

<table><thead><tr><th colspan="2">System information</th></tr><tr><th>Item</th><th>Value</th></tr></thead><tbody><tr><td>Firefly III</td><td>6.1.17 / v2.1.0 / 24 (exp. 24)</td></tr><tr><td>PHP version</td><td>8.3.8 (64bits) / apache2handler / Linux aarch64</td></tr><tr><td>BCscale</td><td>12</td></tr><tr><td>Error reporting</td><td>Display: Off, reporting: ALL errors</td></tr><tr><td>Max upload</td><td>67108864 (64 MB)</td></tr><tr><td>Database drivers</td><td>mysql, pgsql, <strong>*sqlite*</strong>, </td></tr><tr><td>Docker build</td><td><span>#</span>1099, base <span>#</span>85</td></tr></tbody></table><table><thead><tr><th colspan="2">Firefly III information</th></tr><tr><th>Item</th><th>Value</th></tr></thead><tbody><tr><td>Timezone</td><td>UTC + Africa/Casablanca</td></tr><tr><td>App environment</td><td>production, debug: false</td></tr><tr><td>Layout</td><td>v1</td></tr><tr><td>Logging</td><td>info, stack / (empty)</td></tr><tr><td>Cache driver</td><td>file</td></tr><tr><td>Default language and locale</td><td>en_US + equal</td></tr><tr><td>Trusted proxies</td><td></td></tr><tr><td>Login provider & user guard</td><td>eloquent / web</td></tr><tr><td>Login headers</td><td>N/A + N/A</td></tr><tr><td>Stateful domains</td><td></td></tr><tr><td>Last cron job</td><td>2024-07-01 00:00:00 (2 weeks from now)</td></tr><tr><td>Mailer</td><td>log</td></tr></tbody></table><table><thead><tr><th colspan="2">User-specific information</th></tr><tr><th>Item</th><th>Value</th></tr></thead><tbody><tr><td>User</td><td><span>#</span>1 of 1</td></tr><tr><td>User flags</td><td><span title="Has liabilities">:credit_card:</span> <span title="Has piggy banks">:pig:</span> <span title="Has rules">:wrench:</span> <span title="Has recurring transactions">:clock130:</span> <span title="Has object groups">:bookmark_tabs:</span> <span title="Has subscriptions">:email:</span></td></tr><tr><td>Session start</td><td>2024-06-01 00:00:00</td></tr><tr><td>Session end</td><td>2024-06-30 23:59:59</td></tr><tr><td>View range</td><td>1M</td></tr><tr><td>User language</td><td>en_US</td></tr><tr><td>User locale</td><td>en_US</td></tr><tr><td>Locale(s) supported</td><td>en_US.utf8: :white_check_mark:<br>en_US.UTF-8: :white_check_mark:<br></td></tr><tr><td>User agent</td><td>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36</td></tr></tbody></table>

### Expected behaviour

My expectation is that when I attempt to reduce an account balance to $0, I do not encounter the following error message:

**Error! Internal Firefly III Exception: bcadd(): Argument #2 ($num2) is not well-formed**

I believe transactions should execute smoothly without generating this error when depleting the account balance to $0.

### Steps to reproduce

1 - Start with an asset account containing a balance of $100.00 (for exemple).
2 - Attempt to make a transfer or expense that fully depletes this $100.00 balance (leaving the account with $0.00).

**Comment by JC5** [comment]
Thanks, I'll check it out :)

**Comment by JC5** [comment]
I can't replicate this. Could you please add a stack trace?

**Comment by jpelgrom** [comment]
Not the original reporter, but I'm seeing the same error when trying to create a transaction that moves all money from bank account A to B, on Firefly III 6.1.17.

<details>
<summary>Logs and stacktrace</summary>

```
Truncated from this point <----| #1: "A" (Asset account)  
[2024-06-16 19:03:24] production.DEBUG: Valid source!  
[2024-06-16 19:03:24] production.DEBUG: Source seems valid.  
[2024-06-16 19:03:24] production.DEBUG: Now in AccountValidator::validateDestination() {"id":102,"name":"B","iban":"","number":""} 
[2024-06-16 19:03:24] production.DEBUG: Now in validateTransferDestination {"id":102,"name":"B","iban":"","number":""} 
[2024-06-16 19:03:24] production.DEBUG: Now in findExistingAccount {"id":102,"name":"B","iban":"","number":""} 
[2024-06-16 19:03:24] production.DEBUG: The search will be reversed!  
[2024-06-16 19:03:24] production.DEBUG: ID: Found Asset account account #102 ("B", IBAN "x")  
[2024-06-16 19:03:24] production.DEBUG: AccountValidator destination is set to #102: "B" (Asset account)  
[2024-06-16 19:03:24] production.DEBUG: Source info: {"id":1,"name":"A","iban":"","number":"","bic":"","currency_id":1} 
[2024-06-16 19:03:24] production.DEBUG: Destination info: {"id":102,"name":"B","iban":"","number":"","bic":"","currency_id":1} 
[2024-06-16 19:03:24] production.DEBUG: Now in getAccount(source) {"id":1,"name":"A","iban":"","number":"","bic":"","currency_id":1} 
[2024-06-16 19:03:24] production.DEBUG: Transaction = Transfer, source account should be in: Asset account, Loan, Debt, Mortgage. Direction is source.  
[2024-06-16 19:03:24] production.DEBUG: Found "account_id" object: #1, "A" of type Asset account (1)  
[2024-06-16 19:03:24] production.DEBUG: Already have account #1 ("A"), return that.  
[2024-06-16 19:03:24] production.DEBUG: Already have account #1 ("A"), return that.  
[2024-06-16 19:03:24] production.DEBUG: Already have account #1 ("A"), return that.  
[2024-06-16 19:03:24] production.DEBUG: Now in getAccount(destination) {"id":102,"name":"B","iban":"","number":"","bic":"","currency_id":1} 
[2024-06-16 19:03:24] production.DEBUG: Transaction = Transfer, destination account should be in: Asset account, Loan, Debt, Mortgage. Direction is destination.  
[2024-06-16 19:03:24] production.DEBUG: Found "account_id" object: #102, "B" of type Asset account (1)  
[2024-06-16 19:03:24] production.DEBUG: Already have account #102 ("B"), return that.  
[2024-06-16 19:03:24] production.DEBUG: Already have account #102 ("B"), return that.  
[2024-06-16 19:03:24] production.DEBUG: Already have account #102 ("B"), return that.  
[2024-06-16 19:03:24] production.DEBUG: Done with getAccount(2x)  
[2024-06-16 19:03:24] production.DEBUG: Now in getCurrencyByAccount()  
[2024-06-16 19:03:24] production.DEBUG: Now in getCurrency()  
[2024-06-16 19:03:24] production.DEBUG: Currency is now #1 (EUR) because of account #1 (A)  
[2024-06-16 19:03:24] production.DEBUG: Now in getCurrency()  
[2024-06-16 19:03:24] production.DEBUG: Currency is now #1 (EUR) because of account #102 (B)  
[2024-06-16 19:03:24] production.DEBUG: Date: 2024-06-17T00:00:00+02:00 (Europe/Amsterdam)  
[2024-06-16 19:03:24] production.DEBUG: Created new journal #570: "x"  
[2024-06-16 19:03:24] production.DEBUG: Observe "created" of a transaction.  
[2024-06-16 19:03:24] production.DEBUG: Set 1 account balance(s) of account #1 to zero.  
[2024-06-16 19:03:24] production.ERROR: Exception is: {"class":"ValueError","errorMessage":"bcadd(): Argument #2 ($num2) is not well-formed","time":"Sun, 16 Jun 2024 19:03:24 +0200","file":"\/var\/www\/html\/app\/Support\/Models\/AccountBalanceCalculator.php","line":123,"code":0,"version":"6.1.17","url":"https:\/\/x\/api\/v1\/transactions?_token=x","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64; rv:127.0) Gecko\/20100101 Firefox\/127.0","json":true,"method":"POST","post":"{\"apply_rules\":true,\"fire_webhooks\":true,\"transactions\":[{\"type\":\"transfer\",\"date\":\"2024-06-17T00:00\",\"amount\":\"1\",\"description\":\"x\",\"source_id\":\"1\",\"source_name\":\"A\",\"destination_id\":\"102\",\"destination_name\":\"B\",\"category_name\":null,\"interest_date\":null,\"book_date\":null,\"process_date\":null,\"due_date\":null,\"payment_date\":null,\"invoice_date\":null,\"internal_reference\":null,\"notes\":null,\"external_url\":null}],\"_token\":\"x\"}"}  
[2024-06-16 19:03:24] production.DEBUG: reachedLimit()  
[2024-06-16 19:03:24] production.DEBUG: Wrote new file in "/var/www/html/storage/framework/cache/error-count.json"  
[2024-06-16 19:03:24] production.DEBUG: Read file in "/var/www/html/storage/framework/cache/error-count.json"  
[2024-06-16 19:03:24] production.DEBUG: Now checking limit "5m" {"limit":5,"reset":300} 
[2024-06-16 19:03:24] production.DEBUG: Limit "5m" reset to zero, did not exist yet.  
[2024-06-16 19:03:24] production.DEBUG: Now checking limit "1h" {"limit":15,"reset":3600} 
[2024-06-16 19:03:24] production.DEBUG: Limit "1h" reset to zero, did not exist yet.  
[2024-06-16 19:03:24] production.DEBUG: Now checking limit "24h" {"limit":15,"reset":86400} 
[2024-06-16 19:03:24] production.DEBUG: Limit "24h" reset to zero, did not exist yet.  
[2024-06-16 19:03:24] production.DEBUG: No limits reached, return FALSE.  
[2024-06-16 19:03:24] production.ERROR: bcadd(): Argument #2 ($num2) is not well-formed {"userId":1,"exception":"[object] (ValueError(code: 0): bcadd(): Argument #2 ($num2) is not well-formed at /var/www/html/app/Support/Models/AccountBalanceCalculator.php:123)
[stacktrace]
#0 /var/www/html/app/Support/Models/AccountBalanceCalculator.php(123): bcadd()
#1 /var/www/html/app/Support/Models/AccountBalanceCalculator.php(56): FireflyIII\\Support\\Models\\AccountBalanceCalculator->recalculateLatest()
#2 /var/www/html/app/Handlers/Observer/TransactionObserver.php(49): FireflyIII\\Support\\Models\\AccountBalanceCalculator::recalculateForJournal()
#3 /var/www/html/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(478): FireflyIII\\Handlers\\Observer\\TransactionObserver->created()
#4 /var/www/html/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(286): Illuminate\\Events\\Dispatcher->Illuminate\\Events\\{closure}()
#5 /var/www/html/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(266): Illuminate\\Events\\Dispatcher->invokeListeners()
#6 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Concerns/HasEvents.php(215): Illuminate\\Events\\Dispatcher->dispatch()
#7 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1324): Illuminate\\Database\\Eloquent\\Model->fireModelEvent()
#8 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1142): Illuminate\\Database\\Eloquent\\Model->performInsert()
#9 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(1068): Illuminate\\Database\\Eloquent\\Model->save()
#10 /var/www/html/vendor/laravel/framework/src/Illuminate/Support/helpers.php(363): Illuminate\\Database\\Eloquent\\Builder->Illuminate\\Database\\Eloquent\\{closure}()
#11 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(1067): tap()
#12 /var/www/html/vendor/laravel/framework/src/Illuminate/Support/Traits/ForwardsCalls.php(23): Illuminate\\Database\\Eloquent\\Builder->create()
#13 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(2340): Illuminate\\Database\\Eloquent\\Model->forwardCallTo()
#14 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(2352): Illuminate\\Database\\Eloquent\\Model->__call()
#15 /var/www/html/app/Factory/TransactionFactory.php(97): Illuminate\\Database\\Eloquent\\Model::__callStatic()
#16 /var/www/html/app/Factory/TransactionFactory.php(72): FireflyIII\\Factory\\TransactionFactory->create()
#17 /var/www/html/app/Factory/TransactionJournalFactory.php(246): FireflyIII\\Factory\\TransactionFactory->createNegative()
#18 /var/www/html/app/Factory/TransactionJournalFactory.php(117): FireflyIII\\Factory\\TransactionJournalFactory->createJournal()
#19 /var/www/html/app/Factory/TransactionGroupFactory.php(60): FireflyIII\\Factory\\TransactionJournalFactory->create()
#20 /var/www/html/app/Repositories/TransactionGroup/TransactionGroupRepository.php(411): FireflyIII\\Factory\\TransactionGroupFactory->create()
#21 /var/www/html/app/Api/V1/Controllers/Models/Transaction/StoreController.php(89): FireflyIII\\Repositories\\TransactionGroup\\TransactionGroupRepository->store()
#22 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): FireflyIII\\Api\\V1\\Controllers\\Models\\Transaction\\StoreController->store()
#23 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(43): Illuminate\\Routing\\Controller->callAction()
#24 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Route.php(260): Illuminate\\Routing\\ControllerDispatcher->dispatch()
#25 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Route.php(206): Illuminate\\Routing\\Route->runController()
#26 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(806): Illuminate\\Routing\\Route->run()
#27 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(144): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}()
#28 /var/www/html/app/Api/V1/Controllers/Models/Transaction/StoreController.php(65): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#29 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(165): FireflyIII\\Api\\V1\\Controllers\\Models\\Transaction\\StoreController->FireflyIII\\Api\\V1\\Controllers\\Models\\Transaction\\{closure}()
#30 /var/www/html/app/Api/V1/Controllers/Controller.php(74): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#31 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(165): FireflyIII\\Api\\V1\\Controllers\\Controller->FireflyIII\\Api\\V1\\Controllers\\{closure}()
#32 /var/www/html/app/Http/Middleware/Binder.php(75): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#33 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): FireflyIII\\Http\\Middleware\\Binder->handle()
#34 /var/www/html/app/Http/Middleware/Authenticate.php(66): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#35 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): FireflyIII\\Http\\Middleware\\Authenticate->handle()
#36 /var/www/html/vendor/laravel/sanctum/src/Http/Middleware/EnsureFrontendRequestsAreStateful.php(25): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#37 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(144): Laravel\\Sanctum\\Http\\Middleware\\EnsureFrontendRequestsAreStateful->Laravel\\Sanctum\\Http\\Middleware\\{closure}()
#38 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(119): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#39 /var/www/html/vendor/laravel/sanctum/src/Http/Middleware/EnsureFrontendRequestsAreStateful.php(24): Illuminate\\Pipeline\\Pipeline->then()
#40 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Laravel\\Sanctum\\Http\\Middleware\\EnsureFrontendRequestsAreStateful->handle()
#41 /var/www/html/app/Http/Middleware/AcceptHeaders.php(72): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#42 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): FireflyIII\\Http\\Middleware\\AcceptHeaders->handle()
#43 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(119): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#44 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(805): Illuminate\\Pipeline\\Pipeline->then()
#45 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(784): Illuminate\\Routing\\Router->runRouteWithinStack()
#46 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(748): Illuminate\\Routing\\Router->runRoute()
#47 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(737): Illuminate\\Routing\\Router->dispatchToRoute()
#48 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(200): Illuminate\\Routing\\Router->dispatch()
#49 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(144): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}()
#50 /var/www/html/app/Http/Middleware/InstallationId.php(47): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#51 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): FireflyIII\\Http\\Middleware\\InstallationId->handle()
#52 /var/www/html/vendor/laravel/framework/src/Illuminate/Http/Middleware/TrustProxies.php(57): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#53 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Http\\Middleware\\TrustProxies->handle()
#54 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#55 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.php(31): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#56 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Foundation\\Http\\Middleware\\ConvertEmptyStringsToNull->handle()
#57 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#58 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php(51): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#59 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Foundation\\Http\\Middleware\\TrimStrings->handle()
#60 /var/www/html/vendor/laravel/framework/src/Illuminate/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#61 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Http\\Middleware\\ValidatePostSize->handle()
#62 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(110): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#63 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance->handle()
#64 /var/www/html/app/Http/Middleware/SecureHeaders.php(52): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#65 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): FireflyIII\\Http\\Middleware\\SecureHeaders->handle()
#66 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(119): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#67 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(175): Illuminate\\Pipeline\\Pipeline->then()
#68 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(144): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter()
#69 /var/www/html/public/index.php(73): Illuminate\\Foundation\\Http\\Kernel->handle()
#70 {main}
"} 
```
</details>

**Comment by JC5** [comment]
Nice, thanks. Will be fixed in the next release.
