### ISSUE TITLE
bcadd exception while using POST transactions

### ISSUE THREAD

**Issue by dbtdsilva** [firefly-iii/firefly-iii#9078]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

Hello,

I'm using the API to bulk insert some transactions, normally it works just fine, but sometimes I get the exception below.

My script keeps inserting the rest of the transactions just fine (even though that one failed), and if I try to insert again this transaction again later, it allows me just fine, it looks related with setting the current balance as a 0 with the transaction being processed. 

I added the steps on how to reproduce, let me know if you're not able to reproduce like that, and I will reset my database from zero and try to reproduce again.

### Debug information

Debug information generated at 2024-07-23 10:05:09 for Firefly III version **v6.1.19**.

<table><thead><tr><th colspan="2">System information</th></tr><tr><th>Item</th><th>Value</th></tr></thead><tbody><tr><td>Firefly III</td><td>6.1.19 / v2.1.0 / 24 (exp. 24)</td></tr><tr><td>PHP version</td><td>8.3.9 (64bits) / apache2handler / Linux x86_64</td></tr><tr><td>BCscale</td><td>12</td></tr><tr><td>Error reporting</td><td>Display: Off, reporting: ALL errors</td></tr><tr><td>Max upload</td><td>67108864 (64 MB)</td></tr><tr><td>Database drivers</td><td>mysql, pgsql, <strong>*sqlite*</strong>, </td></tr><tr><td>Docker build</td><td><span>#</span>1113, base <span>#</span>86</td></tr></tbody></table><table><thead><tr><th colspan="2">Firefly III information</th></tr><tr><th>Item</th><th>Value</th></tr></thead><tbody><tr><td>Timezone</td><td>Europe/Zurich + Europe/Berlin</td></tr><tr><td>App environment</td><td>local, debug: false</td></tr><tr><td>Layout</td><td>v1</td></tr><tr><td>Logging</td><td>notice, stack / (empty)</td></tr><tr><td>Cache driver</td><td>file</td></tr><tr><td>Default language and locale</td><td>en_US + equal</td></tr><tr><td>Trusted proxies</td><td>**</td></tr><tr><td>Login provider & user guard</td><td>eloquent / web</td></tr><tr><td>Login headers</td><td>N/A + N/A</td></tr><tr><td>Stateful domains</td><td></td></tr><tr><td>Last cron job</td><td>2024-07-22 22:00:00 (10 hours ago)</td></tr><tr><td>Mailer</td><td>log</td></tr></tbody></table><table><thead><tr><th colspan="2">User-specific information</th></tr><tr><th>Item</th><th>Value</th></tr></thead><tbody><tr><td>User</td><td><span>#</span>1 of 1</td></tr><tr><td>User flags</td><td></td></tr><tr><td>Session start</td><td>2023-07-24 00:00:00</td></tr><tr><td>Session end</td><td>2024-07-23 23:59:59</td></tr><tr><td>View range</td><td>last365</td></tr><tr><td>User language</td><td>en_US</td></tr><tr><td>User locale</td><td>en_US</td></tr><tr><td>Locale(s) supported</td><td>en_US.utf8: :white_check_mark:<br>en_US.UTF-8: :white_check_mark:<br></td></tr><tr><td>User agent</td><td>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36</td></tr></tbody></table>

```
Truncated from this point <----|0] local.ERROR: Mime type text/csv is not allowed for API file upload.  
[2024-07-23 10:01:37] local.ERROR: TagOrId: tag not found.  
[2024-07-23 10:01:37] local.ERROR: Mime type text/csv is not allowed for API file upload.  
[2024-07-23 10:04:56] local.ERROR: TagOrId: tag not found.  
[2024-07-23 10:04:56] local.ERROR: Mime type text/csv is not allowed for API file upload.  
[2024-07-23 10:04:57] local.ERROR: [a] Could not add "0" to "-1.1368683772162E-13": bcadd(): Argument #2 ($num2) is not well-formed  
[2024-07-23 10:04:57] local.ERROR: Exception creating negative transaction: [a] Could not add "0" to "-1.1368683772162E-13": bcadd(): Argument #2 ($num2) is not well-formed  
[2024-07-23 10:04:57] local.WARNING: TransactionJournalFactory::create() caught an exception.  
[2024-07-23 10:04:57] local.ERROR: [a] Could not add "0" to "-1.1368683772162E-13": bcadd(): Argument #2 ($num2) is not well-formed  
[2024-07-23 10:04:57] local.ERROR: #0 /var/www/html/app/Factory/TransactionJournalFactory.php(117): FireflyIII\Factory\TransactionJournalFactory->createJournal()
#1 /var/www/html/app/Factory/TransactionGroupFactory.php(60): FireflyIII\Factory\TransactionJournalFactory->create()
#2 /var/www/html/app/Repositories/TransactionGroup/TransactionGroupRepository.php(411): FireflyIII\Factory\TransactionGroupFactory->create()
#3 /var/www/html/app/Api/V1/Controllers/Models/Transaction/StoreController.php(89): FireflyIII\Repositories\TransactionGroup\TransactionGroupRepository->store()
#4 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): FireflyIII\Api\V1\Controllers\Models\Transaction\StoreController->store()
#5 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(43): Illuminate\Routing\Controller->callAction()
#6 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Route.php(260): Illuminate\Routing\ControllerDispatcher->dispatch()
#7 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Route.php(206): Illuminate\Routing\Route->runController()
#8 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(808): Illuminate\Routing\Route->run()
#9 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(144): Illuminate\Routing\Router->Illuminate\Routing\{closure}()
#10 /var/www/html/app/Api/V1/Controllers/Models/Transaction/StoreController.php(65): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#11 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(165): FireflyIII\Api\V1\Controllers\Models\Transaction\StoreController->FireflyIII\Api\V1\Controllers\Models\Transaction\{closure}()
#12 /var/www/html/app/Api/V1/Controllers/Controller.php(74): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#13 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(165): FireflyIII\Api\V1\Controllers\Controller->FireflyIII\Api\V1\Controllers\{closure}()
#14 /var/www/html/app/Http/Middleware/Binder.php(75): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#15 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): FireflyIII\Http\Middleware\Binder->handle()
#16 /var/www/html/app/Http/Middleware/Authenticate.php(66): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#17 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): FireflyIII\Http\Middleware\Authenticate->handle()
#18 /var/www/html/vendor/laravel/sanctum/src/Http/Middleware/EnsureFrontendRequestsAreStateful.php(25): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#19 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(144): Laravel\Sanctum\Http\Middleware\EnsureFrontendRequestsAreStateful->Laravel\Sanctum\Http\Middleware\{closure}()
#20 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(119): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#21 /var/www/html/vendor/laravel/sanctum/src/Http/Middleware/EnsureFrontendRequestsAreStateful.php(24): Illuminate\Pipeline\Pipeline->then()
#22 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Laravel\Sanctum\Http\Middleware\EnsureFrontendRequestsAreStateful->handle()
#23 /var/www/html/app/Http/Middleware/AcceptHeaders.php(72): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#24 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): FireflyIII\Http\Middleware\AcceptHeaders->handle()
#25 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(119): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#26 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(807): Illuminate\Pipeline\Pipeline->then()
#27 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(786): Illuminate\Routing\Router->runRouteWithinStack()
#28 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(750): Illuminate\Routing\Router->runRoute()
#29 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(739): Illuminate\Routing\Router->dispatchToRoute()
#30 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(200): Illuminate\Routing\Router->dispatch()
#31 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(144): Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}()
#32 /var/www/html/app/Http/Middleware/InstallationId.php(47): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#33 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): FireflyIII\Http\Middleware\InstallationId->handle()
#34 /var/www/html/vendor/laravel/framework/src/Illuminate/Http/Middleware/TrustProxies.php(57): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#35 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\Http\Middleware\TrustProxies->handle()
#36 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#37 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.php(31): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle()
#38 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\Foundation\Http\Middleware\ConvertEmptyStringsToNull->handle()
#39 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#40 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php(51): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle()
#41 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\Foundation\Http\Middleware\TrimStrings->handle()
#42 /var/www/html/vendor/laravel/framework/src/Illuminate/Http/Middleware/ValidatePostSize.php(27): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#43 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\Http\Middleware\ValidatePostSize->handle()
#44 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(110): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#45 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\Foundation\Http\Middleware\PreventRequestsDuringMaintenance->handle()
#46 /var/www/html/app/Http/Middleware/SecureHeaders.php(52): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#47 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): FireflyIII\Http\Middleware\SecureHeaders->handle()
#48 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(119): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#49 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(175): Illuminate\Pipeline\Pipeline->then()
#50 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(144): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter()
#51 /var/www/html/public/index.php(73): Illuminate\Foundation\Http\Kernel->handle()
#52 {main}  
[2024-07-23 10:04:57] local.WARNING: Group repository caught group factory with an exception!  
[2024-07-23 10:04:57] local.ERROR: [a] Could not add "0" to "-1.1368683772162E-13": bcadd(): Argument #2 ($num2) is not well-formed  
[2024-07-23 10:04:57] local.ERROR: #0 /var/www/html/app/Factory/TransactionGroupFactory.php(60): FireflyIII\Factory\TransactionJournalFactory->create()
#1 /var/www/html/app/Repositories/TransactionGroup/TransactionGroupRepository.php(411): FireflyIII\Factory\TransactionGroupFactory->create()
#2 /var/www/html/app/Api/V1/Controllers/Models/Transaction/StoreController.php(89): FireflyIII\Repositories\TransactionGroup\TransactionGroupRepository->store()
#3 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): FireflyIII\Api\V1\Controllers\Models\Transaction\StoreController->store()
#4 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(43): Illuminate\Routing\Controller->callAction()
#5 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Route.php(260): Illuminate\Routing\ControllerDispatcher->dispatch()
#6 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Route.php(206): Illuminate\Routing\Route->runController()
#7 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(808): Illuminate\Routing\Route->run()
#8 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(144): Illuminate\Routing\Router->Illuminate\Routing\{closure}()
#9 /var/www/html/app/Api/V1/Controllers/Models/Transaction/StoreController.php(65): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#10 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(165): FireflyIII\Api\V1\Controllers\Models\Transaction\StoreController->FireflyIII\Api\V1\Controllers\Models\Transaction\{closure}()
#11 /var/www/html/app/Api/V1/Controllers/Controller.php(74): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#12 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(165): FireflyIII\Api\V1\Controllers\Controller->FireflyIII\Api\V1\Controllers\{closure}()
#13 /var/www/html/app/Http/Middleware/Binder.php(75): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#14 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): FireflyIII\Http\Middleware\Binder->handle()
#15 /var/www/html/app/Http/Middleware/Authenticate.php(66): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#16 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): FireflyIII\Http\Middleware\Authenticate->handle()
#17 /var/www/html/vendor/laravel/sanctum/src/Http/Middleware/EnsureFrontendRequestsAreStateful.php(25): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#18 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(144): Laravel\Sanctum\Http\Middleware\EnsureFrontendRequestsAreStateful->Laravel\Sanctum\Http\Middleware\{closure}()
#19 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(119): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#20 /var/www/html/vendor/laravel/sanctum/src/Http/Middleware/EnsureFrontendRequestsAreStateful.php(24): Illuminate\Pipeline\Pipeline->then()
#21 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Laravel\Sanctum\Http\Middleware\EnsureFrontendRequestsAreStateful->handle()
#22 /var/www/html/app/Http/Middleware/AcceptHeaders.php(72): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#23 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): FireflyIII\Http\Middleware\AcceptHeaders->handle()
#24 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(119): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#25 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(807): Illuminate\Pipeline\Pipeline->then()
#26 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(786): Illuminate\Routing\Router->runRouteWithinStack()
#27 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(750): Illuminate\Routing\Router->runRoute()
#28 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(739): Illuminate\Routing\Router->dispatchToRoute()
#29 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(200): Illuminate\Routing\Router->dispatch()
#30 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(144): Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}()
#31 /var/www/html/app/Http/Middleware/InstallationId.php(47): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#32 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): FireflyIII\Http\Middleware\InstallationId->handle()
#33 /var/www/html/vendor/laravel/framework/src/Illuminate/Http/Middleware/TrustProxies.php(57): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#34 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\Http\Middleware\TrustProxies->handle()
#35 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#36 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.php(31): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle()
#37 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\Foundation\Http\Middleware\ConvertEmptyStringsToNull->handle()
#38 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#39 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php(51): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle()
#40 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\Foundation\Http\Middleware\TrimStrings->handle()
#41 /var/www/html/vendor/laravel/framework/src/Illuminate/Http/Middleware/ValidatePostSize.php(27): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#42 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\Http\Middleware\ValidatePostSize->handle()
#43 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(110): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#44 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\Foundation\Http\Middleware\PreventRequestsDuringMaintenance->handle()
#45 /var/www/html/app/Http/Middleware/SecureHeaders.php(52): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#46 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): FireflyIII\Http\Middleware\SecureHeaders->handle()
#47 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(119): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#48 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(175): Illuminate\Pipeline\Pipeline->then()
#49 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(144): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter()
#50 /var/www/html/public/index.php(73): Illuminate\Foundation\Http\Kernel->handle()
#51 {main}  
[2024-07-23 10:04:57] local.WARNING: Caught an exception. Return error message.  
[2024-07-23 10:04:57] local.ERROR: [a] Could not add "0" to "-1.1368683772162E-13": bcadd(): Argument #2 ($num2) is not well-formed  

```

### Expected behaviour

I excepted the transaction to be inserted without failing.

### Steps to reproduce

1. Start with a clean account in EUR with balance 0
2. POST to http://firefly:8080/api/v1/transactions with payload `{"group_title":"","error_if_duplicate_hash":false,"apply_rules":true,"fire_webhooks":true,"transactions":[{"type":"deposit","date":"2021-02-26 07:55:00","order":null,"currency_id":null,"currency_code":"EUR","foreign_currency_id":null,"foreign_currency_code":"","amount":"400.14","foreign_amount":"","description":"From Cindy Rodrigues","source_id":null,"source_name":"Unidentified","source_iban":"","source_number":"","source_bic":"","destination_id":null,"destination_name":"Revolut (EUR)","destination_iban":"","destination_number":"","destination_bic":"","budget_id":null,"budget_name":"","category_id":null,"category_name":"","bill_id":null,"bill_name":"","piggy_bank_id":null,"piggy_bank_name":"","reconciled":false,"notes":"","tags":["import_5_20210226_20220620"],"internal_reference":"67a4c86a02c8c36eae894d79e5be1953d01c7019ded4d1d3c88c6669c7c9421c","external_id":"","original_source":"ff3-v6.1.19|api-v2.1.0","recurrence_id":null,"bunq_payment_id":"","external_url":"","sepa_cc":"","sepa_ct_op":"","sepa_ct_id":"","sepa_db":"","sepa_country":"","sepa_ep":"","sepa_ci":"","sepa_batch_id":"","interest_date":null,"book_date":null,"process_date":null,"due_date":null,"payment_date":null,"invoice_date":null}],"user":1}` -> Current balance here is 400.14 EUR
4. POST to http://firefly:8080/api/v1/transactions with payload `{"group_title":"","error_if_duplicate_hash":false,"apply_rules":true,"fire_webhooks":true,"transactions":[{"type":"deposit","date":"2021-02-26 07:56:00","order":null,"currency_id":null,"currency_code":"EUR","foreign_currency_id":null,"foreign_currency_code":"","amount":"521.05","foreign_amount":"","description":"From Cindy Rodrigues","source_id":null,"source_name":"Unidentified","source_iban":"","source_number":"","source_bic":"","destination_id":null,"destination_name":"Revolut (EUR)","destination_iban":"","destination_number":"","destination_bic":"","budget_id":null,"budget_name":"","category_id":null,"category_name":"","bill_id":null,"bill_name":"","piggy_bank_id":null,"piggy_bank_name":"","reconciled":false,"notes":"","tags":["import_5_20210226_20220620"],"internal_reference":"5fd254493d26f7ddcaf48c71d30868443bc5e46dd5ce87b95f742bfc2893e0ac","external_id":"","original_source":"ff3-v6.1.19|api-v2.1.0","recurrence_id":null,"bunq_payment_id":"","external_url":"","sepa_cc":"","sepa_ct_op":"","sepa_ct_id":"","sepa_db":"","sepa_country":"","sepa_ep":"","sepa_ci":"","sepa_batch_id":"","interest_date":null,"book_date":null,"process_date":null,"due_date":null,"payment_date":null,"invoice_date":null}],"user":1}` -> Current balance here is 921.19 EUR
5. POST to http://firefly:8080/api/v1/transactions with payload `{"group_title":"","error_if_duplicate_hash":false,"apply_rules":true,"fire_webhooks":true,"transactions":[{"type":"withdrawal","date":"2022-06-20 10:05:00","order":null,"currency_id":null,"currency_code":"EUR","foreign_currency_id":null,"foreign_currency_code":"","amount":"921.19","foreign_amount":"","description":"To Cindy Rodrigues","source_id":null,"source_name":"Revolut (EUR)","source_iban":"","source_number":"","source_bic":"","destination_id":null,"destination_name":"Unidentified","destination_iban":"","destination_number":"","destination_bic":"","budget_id":null,"budget_name":"","category_id":null,"category_name":"","bill_id":null,"bill_name":"","piggy_bank_id":null,"piggy_bank_name":"","reconciled":false,"notes":"","tags":["import_5_20210226_20220620"],"internal_reference":"253ec2aaeb21c5e62c2a5218c3085340a276de08abdd350b736e7d1bffc9e8b5","external_id":"","original_source":"ff3-v6.1.19|api-v2.1.0","recurrence_id":null,"bunq_payment_id":"","external_url":"","sepa_cc":"","sepa_ct_op":"","sepa_ct_id":"","sepa_db":"","sepa_country":"","sepa_ep":"","sepa_ci":"","sepa_batch_id":"","interest_date":null,"book_date":null,"process_date":null,"due_date":null,"payment_date":null,"invoice_date":null}],"user":1}` -> Current balance here is supposed to be 0 EUR, but fails with an exception.

An error should happen on the fourth transaction, at least that's how I managed to replicate it. I think it's associated with having a transaction that makes the balance 0 (with an account that already had some transactions, in this case, it had two transactions before).

**Comment by JC5** [comment]
I'm curious to learn where this number comes from:

```
[2024-07-23 10:04:57] local.ERROR: [a] Could not add "0" to "-1.1368683772162E-13": bcadd(): Argument #2 ($num2) is not well-formed  
```

I'll check it out, thanks!

**Comment by dbtdsilva** [comment]
> I'm curious to learn where this number comes from:
> 
> ```
> [2024-07-23 10:04:57] local.ERROR: [a] Could not add "0" to "-1.1368683772162E-13": bcadd(): Argument #2 ($num2) is not well-formed  
> ```
> 
> I'll check it out, thanks!

**Maybe some additional information:**

I'm not sure what's actually behind "Delete ALL your transactions", "Delete ALL your tags", "Delete ALL your object groups" and "Purge all deleted records", but I'm used to pressing those a lot (in the sequence mentioned, so I always purge) between the executions of my scripts (and never deleted my accounts) -> Not sure if relevant or not.

Hopefully it helps, and thanks!

**Comment by dbtdsilva** [comment]
Nice, glad to hear that! Thank you!
