### ISSUE TITLE
When importing transaction from GoCardLess i get  "cURL error 56: Recv failure: Connection reset by peer"

### ISSUE THREAD

**Issue by RemssM** [firefly-iii/firefly-iii#9254]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

Signing into my bank using GoCardLess, the screen to link the account show up and after 20-30 seconds i get 500 server error.

### Debug information

Firefly III data importer v1.5.6

PHP: cli 8.3.11 Linux

Will now run Apache web server:

AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.24.0.5. Set the 'ServerName' directive globally to suppress this message

AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.24.0.5. Set the 'ServerName' directive globally to suppress this message

[Sat Sep 21 18:23:27.279385 2024] [mpm_prefork:notice] [pid 1:tid 1] AH00163: Apache/2.4.62 (Debian) configured -- resuming normal operations

[Sat Sep 21 18:23:27.279438 2024] [core:notice] [pid 1:tid 1] AH00094: Command line: 'apache2 -D FOREGROUND'

127.0.0.1 - - [21/Sep/2024:18:23:29 +0200] "GET /health HTTP/1.1" 200 1105 "-" "User-Agent: Firefly III Health Checker/2.2"

127.0.0.1 - - [21/Sep/2024:18:24:29 +0200] "GET /health HTTP/1.1" 200 1105 "-" "User-Agent: Firefly III Health Checker/2.2"

[2024-09-21 18:25:12] local.DEBUG: Now in App\Http\Controllers\IndexController::index  

[2024-09-21 18:25:12] local.DEBUG: App\Services\Shared\Authentication\SecretManager::hasValidSecrets  

192.168.1.14 - - [21/Sep/2024:18:25:12 +0200] "GET / HTTP/1.1" 200 3586 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:130.0) Gecko/20100101 Firefox/130.0"

192.168.1.14 - - [21/Sep/2024:18:25:12 +0200] "GET /build/assets/app-WpqpUyN_.css HTTP/1.1" 200 55262 "http://192.168.1.5:8181/" "Mozilla/5.0 (X11; Linux x86_64; rv:130.0) Gecko/20100101 Firefox/130.0"

192.168.1.14 - - [21/Sep/2024:18:25:12 +0200] "GET /build/assets/vendor-DKF67B6L.js HTTP/1.1" 200 54209 "http://192.168.1.5:8181/" "Mozilla/5.0 (X11; Linux x86_64; rv:130.0) Gecko/20100101 Firefox/130.0"

[2024-09-21 18:25:12] local.DEBUG: Now at App\Http\Controllers\TokenController::doValidate  

[2024-09-21 18:25:12] local.DEBUG: Now trying to authenticate with Firefly III at http://192.168.1.5:8080  

[2024-09-21 18:25:14] local.DEBUG: Result is {"result":"OK","message":null} 

192.168.1.14 - - [21/Sep/2024:18:25:12 +0200] "GET /token/validate HTTP/1.1" 200 1159 "http://192.168.1.5:8181/" "Mozilla/5.0 (X11; Linux x86_64; rv:130.0) Gecko/20100101 Firefox/130.0"

[2024-09-21 18:25:14] local.DEBUG: isReadyForBasicStep("service-validation")  

[2024-09-21 18:25:14] local.DEBUG: isReadyForBasicStep("service-validation")  

[2024-09-21 18:25:14] local.DEBUG: isReadyForBasicStep("service-validation")  

[2024-09-21 18:25:14] local.DEBUG: Now at App\Services\Spectre\AuthenticationValidator::validate  

[2024-09-21 18:25:14] local.DEBUG: Now at App\Services\Nordigen\AuthenticationValidator::validate  

[2024-09-21 18:25:14] local.DEBUG: Now at App\Services\SimpleFIN\AuthenticationValidator::validate  

[2024-09-21 18:25:14] local.DEBUG: No Spectre App ID in hasAppId() session, will return config variable.  

[2024-09-21 18:25:14] local.DEBUG: No Nordigen ID in hasId() session, will return config variable.  

[2024-09-21 18:25:14] local.DEBUG: No Spectre secret in hasSecret(), will return config variable.  

[2024-09-21 18:25:14] local.DEBUG: No Nordigen key in hasKey() session, will return config variable.  

192.168.1.14 - - [21/Sep/2024:18:25:14 +0200] "GET /validate/nordigen HTTP/1.1" 200 1148 "http://192.168.1.5:8181/" "Mozilla/5.0 (X11; Linux x86_64; rv:130.0) Gecko/20100101 Firefox/130.0"

192.168.1.14 - - [21/Sep/2024:18:25:14 +0200] "GET /validate/simplefin HTTP/1.1" 200 1145 "http://192.168.1.5:8181/" "Mozilla/5.0 (X11; Linux x86_64; rv:130.0) Gecko/20100101 Firefox/130.0"

192.168.1.14 - - [21/Sep/2024:18:25:14 +0200] "GET /validate/spectre HTTP/1.1" 200 1147 "http://192.168.1.5:8181/" "Mozilla/5.0 (X11; Linux x86_64; rv:130.0) Gecko/20100101 Firefox/130.0"

[2024-09-21 18:25:16] local.DEBUG: Now in App\Http\Controllers\IndexController::postIndex  

[2024-09-21 18:25:16] local.DEBUG: nordigen is a valid flow, redirect to authenticate.  

192.168.1.14 - - [21/Sep/2024:18:25:16 +0200] "POST / HTTP/1.1" 302 1921 "http://192.168.1.5:8181/" "Mozilla/5.0 (X11; Linux x86_64; rv:130.0) Gecko/20100101 Firefox/130.0"

[2024-09-21 18:25:16] local.DEBUG: Now in AuthenticateController, calling middleware.  

[2024-09-21 18:25:16] local.DEBUG: Now at App\Services\Nordigen\AuthenticationValidator::validate  

[2024-09-21 18:25:16] local.DEBUG: No Nordigen ID in hasId() session, will return config variable.  

[2024-09-21 18:25:16] local.DEBUG: No Nordigen key in hasKey() session, will return config variable.  

[2024-09-21 18:25:16] local.DEBUG: No Nordigen key in hasKey() session, will return config variable.  

[2024-09-21 18:25:16] local.DEBUG: No Nordigen ID in hasId() session, will return config variable.  

192.168.1.14 - - [21/Sep/2024:18:25:16 +0200] "GET /authenticate HTTP/1.1" 200 2893 "http://192.168.1.5:8181/" "Mozilla/5.0 (X11; Linux x86_64; rv:130.0) Gecko/20100101 Firefox/130.0"

127.0.0.1 - - [21/Sep/2024:18:25:29 +0200] "GET /health HTTP/1.1" 200 1105 "-" "User-Agent: Firefly III Health Checker/2.2"

[2024-09-21 18:25:36] local.DEBUG: Now in AuthenticateController, calling middleware.  

192.168.1.14 - - [21/Sep/2024:18:25:36 +0200] "POST /authenticate HTTP/1.1" 302 1579 "http://192.168.1.5:8181/authenticate" "Mozilla/5.0 (X11; Linux x86_64; rv:130.0) Gecko/20100101 Firefox/130.0"

[2024-09-21 18:25:36] local.DEBUG: Now in AuthenticateController, calling middleware.  

[2024-09-21 18:25:36] local.DEBUG: Now at App\Services\Nordigen\AuthenticationValidator::validate  

[2024-09-21 18:25:36] local.DEBUG: Now at App\Services\Nordigen\TokenManager::hasValidRefreshToken  

[2024-09-21 18:25:36] local.DEBUG: No Nordigen refresh token, so return false.  

[2024-09-21 18:25:36] local.DEBUG: No refresh token, so return false.  

[2024-09-21 18:25:36] local.DEBUG: Now at App\Services\Nordigen\TokenManager::getNewTokenSet  

192.168.1.14 - - [21/Sep/2024:18:25:36 +0200] "GET /authenticate HTTP/1.1" 302 1548 "http://192.168.1.5:8181/authenticate" "Mozilla/5.0 (X11; Linux x86_64; rv:130.0) Gecko/20100101 Firefox/130.0"

[2024-09-21 18:25:37] local.DEBUG: Now at App\Http\Controllers\Import\UploadController::index  

[2024-09-21 18:25:37] local.DEBUG: Going to check directory for config files: /var/www/html/storage/configurations  

[2024-09-21 18:25:37] local.DEBUG: List of files:  

192.168.1.14 - - [21/Sep/2024:18:25:37 +0200] "GET /upload HTTP/1.1" 200 3004 "http://192.168.1.5:8181/authenticate" "Mozilla/5.0 (X11; Linux x86_64; rv:130.0) Gecko/20100101 Firefox/130.0"

[2024-09-21 18:25:39] local.DEBUG: Now at App\Http\Controllers\Import\UploadController::upload  

192.168.1.14 - - [21/Sep/2024:18:25:39 +0200] "POST /upload HTTP/1.1" 302 1598 "http://192.168.1.5:8181/upload" "Mozilla/5.0 (X11; Linux x86_64; rv:130.0) Gecko/20100101 Firefox/130.0"

[2024-09-21 18:25:39] local.DEBUG: Now at App\Http\Controllers\Import\Nordigen\SelectionController::index  

[2024-09-21 18:25:39] local.DEBUG: Request parameters will be set to:   

[2024-09-21 18:25:39] local.DEBUG: authenticatedGet(https://bankaccountdata.gocardless.com/api/v2/institutions/)  

[2024-09-21 18:25:40] local.DEBUG: Rate limit: 300  

[2024-09-21 18:25:40] local.DEBUG: Rate limit remaining: 299  

[2024-09-21 18:25:40] local.DEBUG: Rate limit reset: 59  

[2024-09-21 18:25:40] local.DEBUG: Now in pauseForRateLimit  

[2024-09-21 18:25:40] local.DEBUG: Rate limit: 299 requests left, and 59s before the limit resets.  

[2024-09-21 18:25:40] local.DEBUG: Save the account success limits? NO  

192.168.1.14 - - [21/Sep/2024:18:25:39 +0200] "GET /import/selection HTTP/1.1" 200 79884 "http://192.168.1.5:8181/upload" "Mozilla/5.0 (X11; Linux x86_64; rv:130.0) Gecko/20100101 Firefox/130.0"

[2024-09-21 18:25:47] local.DEBUG: Now at App\Http\Controllers\Import\Nordigen\SelectionController::postIndex  

[2024-09-21 18:25:47] local.DEBUG: storeContent: Stored 888 bytes in file "59083caec6283931a2d45e9676f544a99ef2641b2dface589f530f5d27d4de8e"  

192.168.1.14 - - [21/Sep/2024:18:25:47 +0200] "POST /import/selection HTTP/1.1" 302 1649 "http://192.168.1.5:8181/import/selection" "Mozilla/5.0 (X11; Linux x86_64; rv:130.0) Gecko/20100101 Firefox/130.0"

[2024-09-21 18:25:47] local.DEBUG: Now at App\Http\Controllers\Import\Nordigen\LinkController::build  

[2024-09-21 18:25:47] local.DEBUG: Request parameters will be set to:   

[2024-09-21 18:25:47] local.DEBUG: Now at App\Services\Nordigen\Request\PostNewUserAgreement::post  

[2024-09-21 18:25:47] local.DEBUG: Now at App\Services\Nordigen\Request\Request::authenticatedJsonPost  

[2024-09-21 18:25:47] local.DEBUG: Rate limit: 100  

[2024-09-21 18:25:47] local.DEBUG: Rate limit remaining: 99  

[2024-09-21 18:25:47] local.DEBUG: Rate limit reset: 59  

[2024-09-21 18:25:47] local.DEBUG: Now in pauseForRateLimit  

[2024-09-21 18:25:47] local.DEBUG: Rate limit: 99 requests left, and 59s before the limit resets.  

[2024-09-21 18:25:47] local.DEBUG: Save the account success limits? NO  

[2024-09-21 18:25:47] local.DEBUG: Returned from POST:  {"id":"8134910d-de94-432b-8d65-f5315b8f01a6","created":"2024-09-21T16:25:47.603393Z","institution_id":"BOURSORAMA_BOUSFRPP","max_historical_days":90,"access_valid_for_days":90,"access_scope":["balances","details","transactions"],"accepted":null} 

[2024-09-21 18:25:47] local.DEBUG: Request parameters will be set to:   

[2024-09-21 18:25:47] local.DEBUG: Reference is "e9c0ecfb-bcd7-4ad2-b621-18909f803f97"  

[2024-09-21 18:25:47] local.DEBUG: Now at App\Services\Nordigen\Request\PostNewRequisitionRequest::post  

[2024-09-21 18:25:47] local.DEBUG: Now at App\Services\Nordigen\Request\Request::authenticatedJsonPost  

[2024-09-21 18:25:48] local.DEBUG: Rate limit: 100  

[2024-09-21 18:25:48] local.DEBUG: Rate limit remaining: 99  

[2024-09-21 18:25:48] local.DEBUG: Rate limit reset: 59  

[2024-09-21 18:25:48] local.DEBUG: Now in pauseForRateLimit  

[2024-09-21 18:25:48] local.DEBUG: Rate limit: 99 requests left, and 59s before the limit resets.  

[2024-09-21 18:25:48] local.DEBUG: Save the account success limits? NO  

[2024-09-21 18:25:48] local.DEBUG: Returned from POST:  {"id":"72465637-3e64-4eba-8934-4c595bab1b35","created":"2024-09-21T16:25:48.177849Z","redirect":"http://192.168.1.5:8181/import/link-nordigen/callback","status":"CR","institution_id":"BOURSORAMA_BOUSFRPP","agreement":"8134910d-de94-432b-8d65-f5315b8f01a6","reference":"e9c0ecfb-bcd7-4ad2-b621-18909f803f97","accounts":[],"link":"https://ob.gocardless.com/ob-psd2/start/08400b93-b493-4fbb-8d2b-aa9ef84ef074/BOURSORAMA_BOUSFRPP","ssn":null,"account_selection":false,"redirect_immediate":false} 

[2024-09-21 18:25:48] local.DEBUG: Got a new requisition with id "72465637-3e64-4eba-8934-4c595bab1b35"  

[2024-09-21 18:25:48] local.DEBUG: Status: CR, returned reference: "e9c0ecfb-bcd7-4ad2-b621-18909f803f97"  

[2024-09-21 18:25:48] local.DEBUG: Will now redirect the user to https://ob.gocardless.com/ob-psd2/start/08400b93-b493-4fbb-8d2b-aa9ef84ef074/BOURSORAMA_BOUSFRPP  

192.168.1.14 - - [21/Sep/2024:18:25:47 +0200] "GET /import/link-nordigen/build HTTP/1.1" 302 1878 "http://192.168.1.5:8181/import/selection" "Mozilla/5.0 (X11; Linux x86_64; rv:130.0) Gecko/20100101 Firefox/130.0"

[2024-09-21 18:26:26] local.DEBUG: Now at App\Http\Controllers\Import\Nordigen\LinkController::callback  

[2024-09-21 18:26:26] local.DEBUG: Reference is "e9c0ecfb-bcd7-4ad2-b621-18909f803f97"  

192.168.1.14 - - [21/Sep/2024:18:26:26 +0200] "GET /import/link-nordigen/callback?ref=e9c0ecfb-bcd7-4ad2-b621-18909f803f97 HTTP/1.1" 302 1599 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:130.0) Gecko/20100101 Firefox/130.0"

[2024-09-21 18:26:26] local.DEBUG: Now at App\Http\Controllers\Import\ConfigurationController::index  

127.0.0.1 - - [21/Sep/2024:18:26:29 +0200] "GET /health HTTP/1.1" 200 1105 "-" "User-Agent: Firefly III Health Checker/2.2"

[2024-09-21 18:26:49] local.ERROR: cURL error 56: Recv failure: Connection reset by peer (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for http://192.168.1.5:8080/api/v1/accounts?type=liabilities&page=1&limit=250 {"exception":"[object] (GrumpyDictator\\FFIIIApiSupport\\Exceptions\\ApiHttpException(code: 0): cURL error 56: Recv failure: Connection reset by peer (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for http://192.168.1.5:8080/api/v1/accounts?type=liabilities&page=1&limit=250 at /var/www/html/vendor/firefly-iii/api-support-classes/src/Request/Request.php:364)
[stacktrace]

#0 /var/www/html/vendor/firefly-iii/api-support-classes/src/Request/Request.php(204): GrumpyDictator\\FFIIIApiSupport\\Request\\Request->handleException()

#1 /var/www/html/vendor/firefly-iii/api-support-classes/src/Request/GetAccountsRequest.php(80): GrumpyDictator\\FFIIIApiSupport\\Request\\Request->authenticatedGet()

#2 /var/www/html/app/Support/Internal/CollectsAccounts.php(79): GrumpyDictator\\FFIIIApiSupport\\Request\\GetAccountsRequest->get()

#3 /var/www/html/app/Http/Controllers/Import/ConfigurationController.php(93): App\\Http\\Controllers\\Import\\ConfigurationController->getFireflyIIIAccounts()

#4 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): App\\Http\\Controllers\\Import\\ConfigurationController->index()

#5 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(43): Illuminate\\Routing\\Controller->callAction()

#6 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Route.php(262): Illuminate\\Routing\\ControllerDispatcher->dispatch()

#7 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Route.php(208): Illuminate\\Routing\\Route->runController()

#8 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(808): Illuminate\\Routing\\Route->run()

#9 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(144): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}()

#10 /var/www/html/app/Http/Middleware/IsReadyForStep.php(44): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()

#11 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): App\\Http\\Middleware\\ConfigurationControllerMiddleware->handle()

#12 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(51): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()

#13 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle()

#14 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(88): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()

#15 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle()

#16 /var/www/html/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()

#17 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle()

#18 /var/www/html/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(121): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()

#19 /var/www/html/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(64): Illuminate\\Session\\Middleware\\StartSession->handleStatefulRequest()

#20 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Session\\Middleware\\StartSession->handle()

#21 /var/www/html/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()

#22 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle()

#23 /var/www/html/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(75): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()

#24 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle()

#25 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(119): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()

#26 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(807): Illuminate\\Pipeline\\Pipeline->then()

#27 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(786): Illuminate\\Routing\\Router->runRouteWithinStack()

#28 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(750): Illuminate\\Routing\\Router->runRoute()

#29 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(739): Illuminate\\Routing\\Router->dispatchToRoute()

#30 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(201): Illuminate\\Routing\\Router->dispatch()

#31 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(144): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}()

#32 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()

#33 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.php(31): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()

#34 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Foundation\\Http\\Middleware\\ConvertEmptyStringsToNull->handle()

#35 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()

#36 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php(51): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()

#37 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Foundation\\Http\\Middleware\\TrimStrings->handle()

#38 /var/www/html/vendor/laravel/framework/src/Illuminate/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()

#39 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Http\\Middleware\\ValidatePostSize->handle()

#40 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(110): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()

#41 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance->handle()

#42 /var/www/html/vendor/laravel/framework/src/Illuminate/Http/Middleware/HandleCors.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()

#43 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Http\\Middleware\\HandleCors->handle()

#44 /var/www/html/vendor/laravel/framework/src/Illuminate/Http/Middleware/TrustProxies.php(58): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()

#45 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Http\\Middleware\\TrustProxies->handle()

#46 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(119): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()

#47 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(176): Illuminate\\Pipeline\\Pipeline->then()

#48 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(145): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter()

#49 /var/www/html/public/index.php(76): Illuminate\\Foundation\\Http\\Kernel->handle()

#50 {main}

"} 

192.168.1.14 - - [21/Sep/2024:18:26:26 +0200] "GET /import/configure HTTP/1.1" 500 7730 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:130.0) Gecko/20100101 Firefox/130.0"

127.0.0.1 - - [21/Sep/2024:18:27:30 +0200] "GET /health HTTP/1.1" 200 1105 "-" "User-Agent: Firefly III Health Checker/2.2"

127.0.0.1 - - [21/Sep/2024:18:28:30 +0200] "GET /health HTTP/1.1" 200 1105 "-" "User-Agent: Firefly III Health Checker/2.2"

### Additional info

I've used the importer for a year without any issue but now i've moved out and i get this error

**Comment by RemssM** [comment]
Nevermind i'm a dumb dumb, i opened the port 8080 on my router and now it works.
