### ISSUE TITLE
Upgrade to 6.1.21 fails with: Class "GeneaLabs\LaravelModelCaching\EloquentBuilder" not found

### ISSUE THREAD

**Issue by yparitcher** [firefly-iii/firefly-iii#9288]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [X] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem
- [X] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

When running the `artisan firefly-iii:upgrade-database` command after upgrading i get the following error:

```php
cd /firefly; sudo -u http php artisan firefly-iii:upgrade-database

   INFO  Nothing to migrate.  

   INFO  Seeding database.  

  Database\Seeders\AccountTypeSeeder ....................................................................................................... RUNNING  
  Database\Seeders\AccountTypeSeeder ..................................................................................................... 5 ms DONE  

  Database\Seeders\TransactionCurrencySeeder ............................................................................................... RUNNING  
  Database\Seeders\TransactionCurrencySeeder ............................................................................................. 5 ms DONE  

  Database\Seeders\TransactionTypeSeeder ................................................................................................... RUNNING  
  Database\Seeders\TransactionTypeSeeder ................................................................................................. 2 ms DONE  

  Database\Seeders\PermissionSeeder ........................................................................................................ RUNNING  
  Database\Seeders\PermissionSeeder ...................................................................................................... 1 ms DONE  

  Database\Seeders\LinkTypeSeeder .......................................................................................................... RUNNING  
  Database\Seeders\LinkTypeSeeder ........................................................................................................ 1 ms DONE  

  Database\Seeders\ConfigSeeder ............................................................................................................ RUNNING  
  Database\Seeders\ConfigSeeder .......................................................................................................... 1 ms DONE  

  Database\Seeders\UserRoleSeeder .......................................................................................................... RUNNING  
  Database\Seeders\UserRoleSeeder ........................................................................................................ 2 ms DONE  

  Database\Seeders\ExchangeRateSeeder ...................................................................................................... RUNNING  
  Database\Seeders\ExchangeRateSeeder ................................................................................................ 1,591 ms DONE  

  [i] No decryption required for table "accounts".
  [i] No decryption required for table "attachments".
  [i] No decryption required for table "bills".
  [i] No decryption required for table "budgets".
  [i] No decryption required for table "categories".
  [i] No decryption required for table "piggy_banks".
  [i] No decryption required for table "preferences".
  [i] No decryption required for table "tags".
  [i] No decryption required for table "transaction_journals".
  [i] No decryption required for table "transactions".
  [i] No decryption required for table "journal_links".
      Now executing firefly-iii:transaction-identifiers
  [i] This command has already been executed.
      Now executing firefly-iii:migrate-to-groups
  [i] Database is already migrated.
      Now executing firefly-iii:account-currencies
  [i] This command has already been executed.
      Now executing firefly-iii:transfer-currencies
  [i] This command has already been executed.
      Now executing firefly-iii:other-currencies
  [i] This command has already been executed.
      Now executing firefly-iii:migrate-notes
  [i] This command has already been executed.
      Now executing firefly-iii:migrate-attachments
  [i] This command has already been executed.
      Now executing firefly-iii:bills-to-rules
  [i] This command has already been executed.
      Now executing firefly-iii:bl-currency
  [i] This command has already been executed.
      Now executing firefly-iii:cc-liabilities
  [i] This command has already been executed.
      Now executing firefly-iii:back-to-journals
  [i] This command has already been executed.
      Now executing firefly-iii:rename-account-meta
  [i] This command has already been executed.
      Now executing firefly-iii:migrate-recurrence-meta
  [i] This command has already been executed.
      Now executing firefly-iii:migrate-tag-locations
  [i] This command has already been executed.
      Now executing firefly-iii:migrate-recurrence-type
  [i] This command has already been executed.
      Now executing firefly-iii:upgrade-liabilities
  [i] This command has already been executed.
      Now executing firefly-iii:liabilities-600
  [i] This command has already been executed.
      Now executing firefly-iii:budget-limit-periods
  [i] This command has already been executed.
      Now executing firefly-iii:migrate-rule-actions
  [i] All rule actions are up to date.
      Now executing firefly-iii:restore-oauth-keys
  [✓] OAuth keys are OK
      Now executing firefly-iii:correct-account-balance
  [i] This command has already been executed.
      Now executing firefly-iii:create-group-memberships
  [✓] Validated group memberships
      Now executing firefly-iii:upgrade-group-information
[2024-09-29 22:13:20] production.ERROR: Exception is: {"class":"Error","errorMessage":"Class \"GeneaLabs\\LaravelModelCaching\\EloquentBuilder\" not found","time":"Sun, 29 Sep 2024 22:13:20 -0400","file":"\\/firefly\/firefly\/vendor\/genealabs\/laravel-model-caching\/src\/Traits\/ModelCaching.php","line":109,"code":0,"version":"6.1.21","url":"http:\/\/localhost","userAgent":"Symfony","json":true,"method":"GET","post":""}  
[2024-09-29 22:13:21] production.ERROR: Class "GeneaLabs\LaravelModelCaching\EloquentBuilder" not found {"exception":"[object] (Error(code: 0): Class \"GeneaLabs\\LaravelModelCaching\\EloquentBuilder\" not found at /firefly/vendor/genealabs/laravel-model-caching/src/Traits/ModelCaching.php:109)
[stacktrace]
#0 /firefly/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1532): FireflyIII\\Models\\Account->newEloquentBuilder()
#1 /firefly/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1569): Illuminate\\Database\\Eloquent\\Model->newModelQuery()
#2 /firefly/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1522): Illuminate\\Database\\Eloquent\\Model->newQueryWithoutScopes()
#3 /firefly/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(2367): Illuminate\\Database\\Eloquent\\Model->newQuery()
#4 /firefly/vendor/genealabs/laravel-model-caching/src/Traits/Caching.php(26): Illuminate\\Database\\Eloquent\\Model->__call()
#5 /firefly/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(2379): FireflyIII\\Models\\Account->__call()
#6 /firefly/app/Console/Commands/Integrity/UpdateGroupInformation.php(111): Illuminate\\Database\\Eloquent\\Model::__callStatic()
#7 /firefly/app/Console/Commands/Integrity/UpdateGroupInformation.php(104): FireflyIII\\Console\\Commands\\Integrity\\UpdateGroupInformation->updateGroupInfoForObject()
#8 /firefly/app/Console/Commands/Integrity/UpdateGroupInformation.php(72): FireflyIII\\Console\\Commands\\Integrity\\UpdateGroupInformation->updateGroupInfo()
#9 /firefly/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): FireflyIII\\Console\\Commands\\Integrity\\UpdateGroupInformation->handle()
#10 /firefly/vendor/laravel/framework/src/Illuminate/Container/Util.php(43): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#11 /firefly/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(95): Illuminate\\Container\\Util::unwrapIfClosure()
#12 /firefly/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(35): Illuminate\\Container\\BoundMethod::callBoundMethod()
#13 /firefly/vendor/laravel/framework/src/Illuminate/Container/Container.php(690): Illuminate\\Container\\BoundMethod::call()
#14 /firefly/vendor/laravel/framework/src/Illuminate/Console/Command.php(213): Illuminate\\Container\\Container->call()
#15 /firefly/vendor/symfony/console/Command/Command.php(279): Illuminate\\Console\\Command->execute()
#16 /firefly/vendor/laravel/framework/src/Illuminate/Console/Command.php(182): Symfony\\Component\\Console\\Command\\Command->run()
#17 /firefly/vendor/laravel/framework/src/Illuminate/Console/Concerns/CallsCommands.php(67): Illuminate\\Console\\Command->run()
#18 /firefly/vendor/laravel/framework/src/Illuminate/Console/Concerns/CallsCommands.php(28): Illuminate\\Console\\Command->runCommand()
#19 /firefly/app/Console/Commands/Upgrade/UpgradeDatabase.php(81): Illuminate\\Console\\Command->call()
#20 /firefly/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): FireflyIII\\Console\\Commands\\Upgrade\\UpgradeDatabase->handle()
#21 /firefly/vendor/laravel/framework/src/Illuminate/Container/Util.php(43): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#22 /firefly/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(95): Illuminate\\Container\\Util::unwrapIfClosure()
#23 /firefly/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(35): Illuminate\\Container\\BoundMethod::callBoundMethod()
#24 /firefly/vendor/laravel/framework/src/Illuminate/Container/Container.php(690): Illuminate\\Container\\BoundMethod::call()
#25 /firefly/vendor/laravel/framework/src/Illuminate/Console/Command.php(213): Illuminate\\Container\\Container->call()
#26 /firefly/vendor/symfony/console/Command/Command.php(279): Illuminate\\Console\\Command->execute()
#27 /firefly/vendor/laravel/framework/src/Illuminate/Console/Command.php(182): Symfony\\Component\\Console\\Command\\Command->run()
#28 /firefly/vendor/symfony/console/Application.php(1047): Illuminate\\Console\\Command->run()
#29 /firefly/vendor/symfony/console/Application.php(316): Symfony\\Component\\Console\\Application->doRunCommand()
#30 /firefly/vendor/symfony/console/Application.php(167): Symfony\\Component\\Console\\Application->doRun()
#31 /firefly/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(197): Symfony\\Component\\Console\\Application->run()
#32 /firefly/artisan(35): Illuminate\\Foundation\\Console\\Kernel->handle()
#33 {main}
"} 

   Error 

  Class "GeneaLabs\LaravelModelCaching\EloquentBuilder" not found

  at vendor/genealabs/laravel-model-caching/src/Traits/ModelCaching.php:109
    105▕     {
    106▕         if (! $this->isCachable()) {
    107▕             $this->isCachable = false;
    108▕ 
  ➜ 109▕             return new EloquentBuilder($query);
    110▕         }
    111▕ 
    112▕         return new CachedBuilder($query);
    113▕     }

      +6 vendor frames 

  7   app/Console/Commands/Integrity/UpdateGroupInformation.php:111
      Illuminate\Database\Eloquent\Model::__callStatic()

  8   app/Console/Commands/Integrity/UpdateGroupInformation.php:104
      FireflyIII\Console\Commands\Integrity\UpdateGroupInformation::updateGroupInfoForObject()
```

### Debug information

500 error (we don't get past the migrate step)

### Additional info

It might be related to the following `genealabs/laravel-model-caching` issues: https://github.com/mikebronner/laravel-model-caching/issues/390 https://github.com/mikebronner/laravel-model-caching/issues/376

We are using Laravel here so the autoloader should just find it.
PHP v.8.3.12
Upgrading from `6.1.19` to `6.1.21` so my first release with the model cacheing

**Comment by JC5** [comment]
Did you run composer install?

**Comment by yparitcher** [comment]
The dependency was installed, (i checked in the vendor folder) i guess the service did not get registered by the autoloader for some reason.

I am running self hosted.
