### ISSUE TITLE
6.1.22 & develop version throws exception while creating new transaction

### ISSUE THREAD

**Issue by ItsEcholot** [firefly-iii/firefly-iii#9472]
### Support guidelines

- [x] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [x] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [x] ... there are no open or closed issues that are related to my problem
- [x] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

The following error gets thrown while creating a new transaction. v6.1.21 works fine.

### Debug information
```
[2024-11-17 14:40:46] production.ERROR: FireflyIII\Support\Models\AccountBalanceCalculator::getLatestBalance(): Return value must be of type string, float returned {"userId":1,"exception":"[object] (TypeError(code: 0): FireflyIII\\Support\\Models\\AccountBalanceCalculator::getLatestBalance(): Return value must be of type string, float returned at /var/www/html/app/Support/Models/AccountBalanceCalculator.php:101)
[stacktrace]
#0 /var/www/html/app/Support/Models/AccountBalanceCalculator.php(161): FireflyIII\\Support\\Models\\AccountBalanceCalculator->getLatestBalance()
#1 /var/www/html/app/Support/Models/AccountBalanceCalculator.php(73): FireflyIII\\Support\\Models\\AccountBalanceCalculator->optimizedCalculation()
#2 /var/www/html/app/Handlers/Observer/TransactionObserver.php(55): FireflyIII\\Support\\Models\\AccountBalanceCalculator::recalculateForJournal()
#3 /var/www/html/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(478): FireflyIII\\Handlers\\Observer\\TransactionObserver->created()
#4 /var/www/html/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(286): Illuminate\\Events\\Dispatcher->Illuminate\\Events\\{closure}()
#5 /var/www/html/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(266): Illuminate\\Events\\Dispatcher->invokeListeners()
#6 /var/www/html/vendor/genealabs/laravel-pivot-events/src/Traits/ExtendFireModelEventTrait.php(48): Illuminate\\Events\\Dispatcher->dispatch()
#7 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1344): FireflyIII\\Models\\Transaction->fireModelEvent()
#8 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1162): Illuminate\\Database\\Eloquent\\Model->performInsert()
#9 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(1079): Illuminate\\Database\\Eloquent\\Model->save()
#10 /var/www/html/vendor/laravel/framework/src/Illuminate/Support/helpers.php(380): Illuminate\\Database\\Eloquent\\Builder->Illuminate\\Database\\Eloquent\\{closure}()
#11 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(1078): tap()
#12 /var/www/html/vendor/laravel/framework/src/Illuminate/Support/Traits/ForwardsCalls.php(23): Illuminate\\Database\\Eloquent\\Builder->create()
#13 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(2367): Illuminate\\Database\\Eloquent\\Model->forwardCallTo()
#14 /var/www/html/vendor/genealabs/laravel-model-caching/src/Traits/Caching.php(26): Illuminate\\Database\\Eloquent\\Model->__call()
#15 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(2379): FireflyIII\\Models\\Transaction->__call()
#16 /var/www/html/app/Factory/TransactionFactory.php(97): Illuminate\\Database\\Eloquent\\Model::__callStatic()
#17 /var/www/html/app/Factory/TransactionFactory.php(184): FireflyIII\\Factory\\TransactionFactory->create()
#18 /var/www/html/app/Factory/TransactionJournalFactory.php(283): FireflyIII\\Factory\\TransactionFactory->createPositive()
#19 /var/www/html/app/Factory/TransactionJournalFactory.php(118): FireflyIII\\Factory\\TransactionJournalFactory->createJournal()
#20 /var/www/html/app/Factory/TransactionGroupFactory.php(60): FireflyIII\\Factory\\TransactionJournalFactory->create()
#21 /var/www/html/app/Repositories/TransactionGroup/TransactionGroupRepository.php(411): FireflyIII\\Factory\\TransactionGroupFactory->create()
#22 /var/www/html/app/Api/V1/Controllers/Models/Transaction/StoreController.php(89): FireflyIII\\Repositories\\TransactionGroup\\TransactionGroupRepository->store()
#23 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): FireflyIII\\Api\\V1\\Controllers\\Models\\Transaction\\StoreController->store()
#24 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(43): Illuminate\\Routing\\Controller->callAction()
#25 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Route.php(264): Illuminate\\Routing\\ControllerDispatcher->dispatch()
#26 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Route.php(210): Illuminate\\Routing\\Route->runController()
#27 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(808): Illuminate\\Routing\\Route->run()
#28 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(144): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}()
#29 /var/www/html/app/Api/V1/Controllers/Models/Transaction/StoreController.php(65): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#30 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(165): FireflyIII\\Api\\V1\\Controllers\\Models\\Transaction\\StoreController->FireflyIII\\Api\\V1\\Controllers\\Models\\Transaction\\{closure}()
#31 /var/www/html/app/Api/V1/Controllers/Controller.php(74): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#32 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(165): FireflyIII\\Api\\V1\\Controllers\\Controller->FireflyIII\\Api\\V1\\Controllers\\{closure}()
#33 /var/www/html/app/Http/Middleware/Binder.php(75): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#34 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): FireflyIII\\Http\\Middleware\\Binder->handle()
#35 /var/www/html/app/Http/Middleware/Authenticate.php(66): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#36 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): FireflyIII\\Http\\Middleware\\Authenticate->handle()
#37 /var/www/html/vendor/laravel/sanctum/src/Http/Middleware/EnsureFrontendRequestsAreStateful.php(25): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#38 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(144): Laravel\\Sanctum\\Http\\Middleware\\EnsureFrontendRequestsAreStateful->Laravel\\Sanctum\\Http\\Middleware\\{closure}()
#39 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(119): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#40 /var/www/html/vendor/laravel/sanctum/src/Http/Middleware/EnsureFrontendRequestsAreStateful.php(24): Illuminate\\Pipeline\\Pipeline->then()
#41 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Laravel\\Sanctum\\Http\\Middleware\\EnsureFrontendRequestsAreStateful->handle()
#42 /var/www/html/app/Http/Middleware/AcceptHeaders.php(72): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#43 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): FireflyIII\\Http\\Middleware\\AcceptHeaders->handle()
#44 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(119): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#45 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(807): Illuminate\\Pipeline\\Pipeline->then()
#46 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(786): Illuminate\\Routing\\Router->runRouteWithinStack()
#47 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(750): Illuminate\\Routing\\Router->runRoute()
#48 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(739): Illuminate\\Routing\\Router->dispatchToRoute()
#49 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(201): Illuminate\\Routing\\Router->dispatch()
#50 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(144): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}()
#51 /var/www/html/app/Http/Middleware/InstallationId.php(47): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#52 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): FireflyIII\\Http\\Middleware\\InstallationId->handle()
#53 /var/www/html/vendor/laravel/framework/src/Illuminate/Http/Middleware/TrustProxies.php(58): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#54 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Http\\Middleware\\TrustProxies->handle()
#55 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#56 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.php(31): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#57 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Foundation\\Http\\Middleware\\ConvertEmptyStringsToNull->handle()
#58 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#59 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php(51): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#60 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Foundation\\Http\\Middleware\\TrimStrings->handle()
#61 /var/www/html/vendor/laravel/framework/src/Illuminate/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#62 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Http\\Middleware\\ValidatePostSize->handle()
#63 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(110): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#64 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance->handle()
#65 /var/www/html/app/Http/Middleware/SecureHeaders.php(52): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#66 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): FireflyIII\\Http\\Middleware\\SecureHeaders->handle()
#67 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(119): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#68 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(176): Illuminate\\Pipeline\\Pipeline->then()
#69 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(145): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter()
#70 /var/www/html/public/index.php(73): Illuminate\\Foundation\\Http\\Kernel->handle()
#71 {main}
"}
```

**Comment by JC5** [comment]
Hi, thanks for opening an issue.

Please see https://github.com/firefly-iii/firefly-iii/issues/9458
