### ISSUE TITLE
data-importer develop failing on CSV file

### ISSUE THREAD

**Issue by MacPaille** [firefly-iii/firefly-iii#9505]
### Support guidelines

- [x] I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)

### I've found a bug and checked that ...

- [x] ... [the documentation](https://docs.firefly-iii.org/) does not mention anything about my problem
- [x] ... there are no open or closed issues that are related to my problem
- [ ] ... it's [definitely a Firefly III issue, not me](https://github.com/firefly-iii/firefly-iii/blob/main/.github/its_you_not_me.md)

### Description

With the latest develop snapshot it seems the csv import fails (gocardless works fine). But it does no fail when accessing the UI and selecting the files to import. It fails in the automatic way that starts, processes the files on the disk and then stops.

I'm testing more to try understand if the issue on my side but I did not change anything to my config json file and whatever the data is inside the csv I have the same issue.

```
[2024-11-28 09:08:02] production.INFO: Done converting 14 line(s) into transactions.  
[2024-11-28 09:08:02] production.DEBUG: Now in setConversionStatus(conv_done)  
[2024-11-28 09:08:02] production.DEBUG: Found "conversion-phm4mA0GhJPp" in the session  
[2024-11-28 09:08:02] production.DEBUG: Now in startOrFindConversion(conversion-phm4mA0GhJPp)  
[2024-11-28 09:08:02] production.DEBUG: Conversion status is "conv_running"  
[2024-11-28 09:08:02] production.DEBUG: Now in storeConversionStatus(conversion-phm4mA0GhJPp): conv_done  
[2024-11-28 09:08:02] production.DEBUG: Messages: 0, warnings: 0, errors: 0  
[2024-11-28 09:08:02] production.ERROR: Typed property App\Services\CSV\Conversion\RoutineManager::$allRateLimits must not be accessed before initialization {"exception":"[object] (Error(code: 0): Typed property App\\Services\\CSV\\Conversion\\RoutineManager::$allRateLimits must not be accessed before initialization at /var/www/html/app/Services/Shared/Conversion/CombinedProgressInformation.php:42)
[stacktrace]
#0 /var/www/html/app/Console/AutoImports.php(420): App\\Services\\CSV\\Conversion\\RoutineManager->getAllRateLimits()
#1 /var/www/html/app/Console/AutoImports.php(260): App\\Console\\Commands\\AutoImport->startConversion()
#2 /var/www/html/app/Console/AutoImports.php(179): App\\Console\\Commands\\AutoImport->importFile()
#3 /var/www/html/app/Console/Commands/AutoImport.php(102): App\\Console\\Commands\\AutoImport->importFiles()
#4 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): App\\Console\\Commands\\AutoImport->handle()
#5 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Util.php(43): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#6 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(95): Illuminate\\Container\\Util::unwrapIfClosure()
#7 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(35): Illuminate\\Container\\BoundMethod::callBoundMethod()
#8 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(690): Illuminate\\Container\\BoundMethod::call()
#9 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(213): Illuminate\\Container\\Container->call()
#10 /var/www/html/vendor/symfony/console/Command/Command.php(279): Illuminate\\Console\\Command->execute()
#11 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(182): Symfony\\Component\\Console\\Command\\Command->run()
#12 /var/www/html/vendor/symfony/console/Application.php(1047): Illuminate\\Console\\Command->run()
#13 /var/www/html/vendor/symfony/console/Application.php(316): Symfony\\Component\\Console\\Application->doRunCommand()
#14 /var/www/html/vendor/symfony/console/Application.php(167): Symfony\\Component\\Console\\Application->doRun()
#15 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(197): Symfony\\Component\\Console\\Application->run()
#16 /var/www/html/artisan(35): Illuminate\\Foundation\\Console\\Kernel->handle()
#17 {main}
"} 

```

### Debug information

Not possible in automatic mode, logs provided above

**Comment by JC5** [comment]
Ah thanks, I'll check it out!

**Comment by JC5** [comment]
A new develop build is out, let me know if it works as expected!
